# Spatial GRN Integration of the Dentate Gyrus

## Step2:Gene Regulatory Network uisng SCENIC+:
## Tutorial 2c: SCENIC+

**Author:** Xuan Cao  
**Affiliation:** Icahn School of Medicine at Mount Sinai  
**Email:** xuan.cao@mssm.edu  

**Contributors:** Donghoon Lee, Panos Roussos  

**Date:** March 20, 2026  

---

### Overview
This notebook demonstrates a pipeline for spatial imputation and integration of gene regulatory networks (GRNs) in the dentate gyrus. Using Tangram, we map single-cell transcriptomic profiles onto spatial transcriptomics data to enable downstream GRN inference in a spatially resolved context.

### scenicplus version 
0.1.dev454+g9320635

### Install conda environment
Adapted from the SCENIC+ GitHub repository<br>
conda create --name scenicplus python=3.11 -y<br>
conda activate scenicplus<br>
git clone https://github.com/aertslab/scenicplus<br>
cd scenicplus<br>
pip install .<br>


### Contents
1. Data loading 
2. Generate pseudobulk ATAC-seq profiles  
3. Peak Calling  
4. Creating cisTopic object
5. Running topic model
6. Visualization of topics
7. Topic binarization & QC
8. Differentially Accessible Regions (DARs)
9. Export cistopic object

# Imports

In [1]:
import numpy as np
import scanpy as sc
import pandas as pd
import pyranges as pr

sc.set_figure_params(scanpy=True, dpi=100, dpi_save=150, fontsize=12)
sc.set_figure_params(dpi=100, color_map = 'viridis_r')
sc.settings.verbosity = 1
sc.logging.print_header()
from matplotlib.pyplot import rc_context

import gc

import sys
import os
import pickle

import warnings
warnings.simplefilter(action='ignore')
import scenicplus
scenicplus.__version__

/sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
/sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

scanpy==1.8.2 anndata==0.8.0 umap==0.5.3 numpy==1.23.5 scipy==1.9.3 pandas==1.5.1 scikit-learn==1.3.2 statsmodels==0.13.5 python-igraph==0.10.2 pynndescent==0.5.11

/sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

'0.1.dev454+g9320635'

# Set dirs

In [2]:
master_dir ='SpatialGRN/Output'
cistopic_dir = f'{master_dir}/02a.pycisTopic'
cistarget_dir = f'{master_dir}/02b.pycisTarget'
scplus_dir = f'{master_dir}/02c.scenic+'

tmp_dir = "tmp/"
log_dir=f'{cistopic_dir}/00.log'
run_dir = f'{scplus_dir}/00.run'
 
if not os.path.exists(scplus_dir):
    os.makedirs(scplus_dir)
    
if not os.path.exists(tmp_dir):
    os.makedirs(tmp_dir)

if not os.path.exists(tmp_dir):
    os.makedirs(log_dir)

# 1. build scenicplus object

In [3]:
# Input data path
rna_h5ad = 'data/human_DG_snrna.h5ad'
cistopic_path = f'{cistopic_dir}/cistopic_obj.pkl'
menr_path = f'{cistarget_dir}/menr.pkl'

# Load data
rna = sc.read_h5ad(rna_h5ad)
cistopic_obj = pickle.load(open(cistopic_path, 'rb'))
menr = pickle.load(open(menr_path, 'rb'))
# change the cellbarcode to the same form
rna.obs_names = rna.obs_names + '___human_DG'

In [14]:
#######
from pycisTopic.cistopic_class import *
from scenicplus.scenicplus_class import SCENICPLUS, create_SCENICPLUS_object

# create scenicplus object
scplus_obj = create_SCENICPLUS_object(
    GEX_anndata = rna,
    cisTopic_obj = cistopic_obj,
    menr = menr,
)
scplus_obj.X_EXP = scplus_obj.X_EXP.toarray()
print(scplus_obj)
print("1.create_SCENICPLUS_object done!")

2026-06-13 10:40:19,959 cisTopic     INFO     Imputing drop-outs
2026-06-13 10:40:31,814 cisTopic     INFO     Scaling
2026-06-13 10:40:43,028 cisTopic     INFO     Keep non zero rows
2026-06-13 10:40:56,265 cisTopic     INFO     Imputed accessibility sparsity: 0.5326049393648504
2026-06-13 10:40:56,268 cisTopic     INFO     Create CistopicImputedFeatures object
2026-06-13 10:40:56,269 cisTopic     INFO     Done!
SCENIC+ object with n_cells x n_genes = 9856 x 36601 and n_cells x n_regions = 9856 x 594681
	metadata_regions:'Chromosome', 'Start', 'End', 'Width', 'cisTopic_nr_frag', 'cisTopic_log_nr_frag', 'cisTopic_nr_acc', 'cisTopic_log_nr_acc'
	metadata_cell:'GEX_class', 'GEX_subclass', 'GEX_subtype', 'ACC_cisTopic_nr_frag', 'ACC_cisTopic_log_nr_frag', 'ACC_cisTopic_nr_acc', 'ACC_cisTopic_log_nr_acc', 'ACC_sample_id', 'ACC_Unique_nr_frag', 'ACC_barcode', 'ACC_class', 'ACC_subclass', 'ACC_subtype'
	menr:'CTX_topics_otsu_All', 'CTX_topics_otsu_No_promoters', 'DEM_topics_otsu_All', 'DEM_topics_otsu_No_promoters', 'CTX_topics_top_3_All', 'CTX_topics_top_3_No_promoters', 'DEM_topics_top_3_All', 'DEM_topics_top_3_No_promoters', 'CTX_DARs_All', 'CTX_DARs_No_promoters', 'DEM_DARs_All', 'DEM_DARs_No_promoters'
	dr_cell:'ACC_UMAP'
1.create_SCENICPLUS_object done!

# 2. Merge cistromes (all)

In [15]:
# 2. Merge cistromes (all)

from scenicplus.cistromes import *
merge_cistromes(scplus_obj)

tfs = list(scplus_obj.uns['Cistromes']['Unfiltered'].keys())
print('tf numbers from motif dir',len(tfs))
print(scplus_obj.uns['Cistromes']['Unfiltered'][tfs[0]])

cistromes = scplus_obj.uns['Cistromes']  
with open(scplus_dir + '/02.Cistromes.pkl', 'wb') as f:
  pickle.dump(cistromes, f)
  
print("2. Merge cistromes done!")

tf numbers from motif dir 2349
+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int32)   | (int32)   |
|--------------+-----------+-----------|
| chr1         | 8987871   | 8988371   |
| chr1         | 201042804 | 201043304 |
| chr1         | 230073510 | 230074010 |
| chr1         | 87393468  | 87393968  |
| ...          | ...       | ...       |
| chrX         | 3697647   | 3698147   |
| chrX         | 103782596 | 103783096 |
| chrX         | 101415560 | 101416060 |
| chrX         | 123764982 | 123765482 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,248 rows and 3 columns from 23 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
2. Merge cistromes done!

# 3. Infer enhancer to gene relationships

## 3A. get gene space

In [16]:
annot = pickle.load(open('resources/hg38_annot.get_search_space.pkl', 'rb'))
chromszies_file = "resources/hg38.chrom.sizes"
upstream = [1000, 150000]
downstream = [1000, 150000]

# read chromsize
import pandas as pd
import pyranges as pr

if not any(['chr' in c for c in scplus_obj.region_names]):
    annot.Chromosome = annot.Chromosome.str.replace('chr', '')

chromsizes = pd.read_csv(chromszies_file, sep='\t', header=None)
chromsizes.columns = ['Chromosome', 'End']
chromsizes['Start'] = [0]*chromsizes.shape[0]
chromsizes = chromsizes.loc[:, ['Chromosome', 'Start', 'End']]
if not any(['chr' in c for c in scplus_obj.region_names]):
    annot.Chromosome = annot.Chromosome.str.replace('chr', '')
chromsizes = pr.PyRanges(chromsizes)

#------------------------------------
from scenicplus.enhancer_to_gene import get_search_space, calculate_regions_to_genes_relationships, GBM_KWARGS
get_search_space(scplus_obj,
                 pr_annot = annot,
                 pr_chromsizes = chromsizes,
                 upstream = upstream,
                 downstream = downstream)

search_space = scplus_obj.uns['search_space']
with open(scplus_dir + '/03.search_space.pkl', 'wb') as f:
  pickle.dump(search_space, f)

print(search_space)
print(scplus_obj.uns.keys())

print("3A.Get search space done!")

2026-06-13 10:44:20,546 R2G          INFO     Extending promoter annotation to 10 bp upstream and 10 downstream
2026-06-13 10:44:22,219 R2G          INFO     Extending search space to:
            						150000 bp downstream of the end of the gene.
            						150000 bp upstream of the start of the gene.
2026-06-13 10:44:35,262 R2G          INFO     Intersecting with regions.

join: Strand data from other will be added as strand data to self.
If this is undesired use the flag apply_strand_suffix=False.
To turn off the warning set apply_strand_suffix to True or False.

2026-06-13 10:44:36,237 R2G          INFO     Calculating distances from region to gene
2026-06-13 10:47:39,049 R2G          INFO     Imploding multiple entries per region and gene
2026-06-13 10:52:34,759 R2G          INFO     Done!
                           Name     Gene   Distance
0        chr1:12565881-12566381  AADACL3   [149979]
1        chr1:12567468-12567968  AADACL3   [148392]
2        chr1:12573022-12573522  AADACL3   [142838]
3        chr1:12573707-12574207  AADACL3   [142153]
4        chr1:12581110-12581610  AADACL3   [134750]
...                         ...      ...        ...
2111193  chrY:13479199-13479699      UTY        [0]
2111194  chrY:13479821-13480321      UTY        [0]
2111195  chrY:13493456-13493956      UTY    [13033]
2111196  chrY:13543836-13544336      UTY    [63413]
2111197  chrY:13852133-13852633      VCY  [-133389]

[2111198 rows x 3 columns]
dict_keys(['Cistromes', 'search_space'])
3A.Get search space done!

## 3B.Region-to-gene calculate

In [17]:
# calculate region_to_gene relationship
from scenicplus.enhancer_to_gene import get_search_space, calculate_regions_to_genes_relationships, GBM_KWARGS
ncpu = 10

calculate_regions_to_genes_relationships(
    scplus_obj,
    ray_n_cpu = ncpu,
    _temp_dir = tmp_dir,
    importance_scoring_method = 'GBM',
    importance_scoring_kwargs = GBM_KWARGS
)

2026-06-13 11:26:28,710 R2G          INFO     Calculating region to gene importances, using GBM method

2026-06-13 11:26:42,938	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
initializing: 100%|██████████| 19206/19206 [30:28<00:00, 10.50it/s]
Running using 10 cores: 100%|██████████| 19206/19206 [21:14<00:00, 15.07it/s]

2026-06-13 12:18:29,475 R2G          INFO     Took 3120.7636647224426 seconds
2026-06-13 12:18:29,477 R2G          INFO     Calculating region to gene correlation, using SR method

2026-06-13 12:18:37,518	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(_score_regions_to_single_gene_ray pid=2881520) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
(_score_regions_to_single_gene_ray pid=2881520)   warnings.warn(stats.ConstantInputWarning(warn_msg))
(_score_regions_to_single_gene_ray pid=2881520) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
(_score_regions_to_single_gene_ray pid=2881520)   warnings.warn(stats.ConstantInputWarning(warn_msg))
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 14x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 14x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 11x across cluster]
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 11x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 6x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 9x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 9x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 3x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 3x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 9x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 9x across cluster]
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg))
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg))
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg))
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881519) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881519)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 3x across cluster]
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 3x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 4x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881519) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881519)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881522) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881522)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 5x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881517)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 10x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 8x across cluster]
(_score_regions_to_single_gene_ray pid=2881524) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881524)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 2x across cluster]
(_score_regions_to_single_gene_ray pid=2881521) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881521)   warnings.warn(stats.ConstantInputWarning(warn_msg)) [repeated 7x across cluster]
(_score_regions_to_single_gene_ray pid=2881517) /sc/arion/projects/YuanLab/gcproj/xuan/anaconda3/envs/scenicplus/lib/python3.8/site-packages/scipy/stats/_stats_py.py:4881: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined. [repeated 2x across cluster]

2026-06-13 12:47:33,977 R2G          INFO     Took 1744.4988021850586 seconds
2026-06-13 12:47:45,382 R2G          INFO     Done!

# 4. Infer TF to gene relationships

In [29]:
from scenicplus.TF_to_gene import *
tf_file='resources/utoronto_human_tfs_v_1.01.txt'
ncpu = 20

calculate_TFs_to_genes_relationships(
    scplus_obj,
    tf_file = tf_file,
    ray_n_cpu = ncpu,
    method = 'GBM',
    _temp_dir = tmp_dir,
    key= 'TF2G_adj'
)

2026-06-13 18:03:43,963	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266

2026-06-13 18:03:45,281 TF2G         INFO     Calculating TF to gene correlation, using GBM method

(raylet) Spilled 7188 MiB, 15 objects, write throughput 2494 MiB/s. Set RAY_verbose_spill_logs=0 to disable this message.
(raylet) Spilled 12938 MiB, 27 objects, write throughput 3277 MiB/s.
(raylet) Spilled 34442 MiB, 70 objects, write throughput 2676 MiB/s. [repeated 3x across cluster]
(raylet) Spilled 133639 MiB, 277 objects, write throughput 3665 MiB/s. [repeated 2x across cluster]
(raylet) Spilled 267922 MiB, 546 objects, write throughput 4207 MiB/s.
(raylet) Spilled 525536 MiB, 1067 objects, write throughput 5671 MiB/s.
(raylet) Spilled 1049727 MiB, 2112 objects, write throughput 5775 MiB/s.
(raylet) Spilled 2100434 MiB, 4240 objects, write throughput 5768 MiB/s.
(raylet) Spilled 4194475 MiB, 8478 objects, write throughput 5715 MiB/s.
(raylet) Spilled 8390755 MiB, 17005 objects, write throughput 5727 MiB/s.
(raylet) Spilled 16778637 MiB, 34006 objects, write throughput 5753 MiB/s.
initializing: 100%|██████████| 36601/36601 [1:34:22<00:00,  6.46it/s]
Running using 20 cores: 100%|██████████| 36601/36601 [04:47<00:00, 127.48it/s]

2026-06-13 19:42:59,681 TF2G         INFO     Took 5954.397935152054 seconds
2026-06-13 19:42:59,683 TF2G         INFO     Adding correlation coefficients to adjacencies.
2026-06-13 19:45:12,764 TF2G         INFO     Warning: adding TFs as their own target to adjecencies matrix. Importance values will be max + 1e-05
2026-06-13 19:45:19,006 TF2G         INFO     Adding importance x rho scores to adjacencies.
2026-06-13 19:45:19,033 TF2G         INFO     Took 139.350195646286 seconds

# 5. Build GRN

In [ ]:
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ': Start build GRN.',sep="")
# Load functions
from scenicplus.grn_builder.gsea_approach import build_grn
build_grn(scplus_obj,
          min_target_genes = 10,
          adj_pval_thr = 1,
          min_regions_per_gene = 0,
          quantiles = (0.85, 0.90, 0.95),
          top_n_regionTogenes_per_gene = (5, 10, 15),
          top_n_regionTogenes_per_region = (),
          binarize_using_basc = True,
          rho_dichotomize_tf2g = True,
          rho_dichotomize_r2g = True,
          rho_dichotomize_eregulon = True,
          rho_threshold = 0.001,
          keep_extended_motif_annot = True,
          merge_eRegulons = True,
          order_regions_to_genes_by = 'importance',
          order_TFs_to_genes_by = 'importance',
          key_added = 'eRegulons_importance',
          cistromes_key = 'Unfiltered',
          disable_tqdm = False, #If running in notebook, set to True
          ray_n_cpu = 40,
          _temp_dir = tmp_dir)

print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':End build GRN.',sep="")

2026-06-13 20:14:10: Start build GRN.
2026-06-13 20:14:13,753 GSEA         INFO     Thresholding region to gene relationships

2026-06-13 20:14:29,072	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8266
  0%|          | 0/14 [00:00<?, ?it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   0%|          | 0/2349 [00:00<?, ?it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   0%|          | 2/2349 [00:00<02:10, 17.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   0%|          | 5/2349 [00:00<01:48, 21.67it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   0%|          | 8/2349 [00:00<01:46, 22.04it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   0%|          | 11/2349 [00:00<01:57, 19.82it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 14/2349 [00:00<01:56, 20.03it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 17/2349 [00:00<01:46, 21.83it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 20/2349 [00:00<01:56, 19.92it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 23/2349 [00:01<02:21, 16.48it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 25/2349 [00:01<02:18, 16.75it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|          | 28/2349 [00:01<02:33, 15.11it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|▏         | 30/2349 [00:01<02:56, 13.11it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|▏         | 33/2349 [00:01<02:37, 14.73it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   1%|▏         | 35/2349 [00:02<03:07, 12.37it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 37/2349 [00:02<03:03, 12.59it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 40/2349 [00:02<02:40, 14.43it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 42/2349 [00:02<02:29, 15.41it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 45/2349 [00:02<02:11, 17.58it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 48/2349 [00:02<02:01, 18.94it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 50/2349 [00:03<02:14, 17.11it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 52/2349 [00:03<02:13, 17.24it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 55/2349 [00:03<01:58, 19.33it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   2%|▏         | 57/2349 [00:03<02:00, 18.94it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 60/2349 [00:03<01:57, 19.41it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 62/2349 [00:03<01:59, 19.19it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 64/2349 [00:03<02:02, 18.58it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 66/2349 [00:03<02:07, 17.96it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 68/2349 [00:04<02:38, 14.35it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 70/2349 [00:04<02:57, 12.87it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 72/2349 [00:04<02:55, 12.96it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 74/2349 [00:04<03:08, 12.06it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 77/2349 [00:04<02:37, 14.45it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 79/2349 [00:04<02:28, 15.33it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   3%|▎         | 81/2349 [00:05<02:49, 13.41it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▎         | 83/2349 [00:05<02:59, 12.61it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▎         | 85/2349 [00:05<02:41, 13.98it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▎         | 87/2349 [00:05<02:28, 15.28it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 89/2349 [00:05<02:22, 15.83it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 91/2349 [00:05<02:21, 16.01it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 93/2349 [00:05<02:24, 15.61it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 95/2349 [00:05<02:43, 13.82it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 97/2349 [00:06<02:35, 14.49it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 99/2349 [00:06<02:29, 15.06it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 101/2349 [00:06<02:26, 15.32it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 103/2349 [00:06<03:31, 10.64it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   4%|▍         | 105/2349 [00:07<04:31,  8.26it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 107/2349 [00:10<23:19,  1.60it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 108/2349 [00:10<20:17,  1.84it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 109/2349 [00:10<16:59,  2.20it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 110/2349 [00:11<14:17,  2.61it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 112/2349 [00:11<09:38,  3.87it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 114/2349 [00:11<08:52,  4.20it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 115/2349 [00:11<07:57,  4.68it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 116/2349 [00:11<07:18,  5.10it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▍         | 117/2349 [00:11<06:36,  5.64it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 118/2349 [00:12<06:24,  5.81it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 119/2349 [00:12<06:09,  6.03it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 120/2349 [00:12<05:31,  6.73it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 121/2349 [00:12<05:09,  7.21it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 122/2349 [00:12<04:44,  7.84it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 123/2349 [00:12<05:13,  7.11it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 124/2349 [00:12<05:07,  7.23it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 125/2349 [00:13<05:02,  7.35it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 127/2349 [00:13<04:09,  8.89it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   5%|▌         | 128/2349 [00:13<04:14,  8.73it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 130/2349 [00:13<03:26, 10.73it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 132/2349 [00:13<03:21, 11.01it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 134/2349 [00:13<03:46,  9.78it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 136/2349 [00:14<03:56,  9.37it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 137/2349 [00:14<04:10,  8.84it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 138/2349 [00:14<04:13,  8.74it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 139/2349 [00:14<04:22,  8.42it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 141/2349 [00:14<04:26,  8.30it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 142/2349 [00:14<04:38,  7.93it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 143/2349 [00:14<04:28,  8.20it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 144/2349 [00:15<04:32,  8.11it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▌         | 146/2349 [00:15<03:40,  9.97it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▋         | 148/2349 [00:15<03:13, 11.39it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▋         | 150/2349 [00:15<02:44, 13.39it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   6%|▋         | 152/2349 [00:19<25:30,  1.44it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 153/2349 [00:19<21:44,  1.68it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 154/2349 [00:19<18:10,  2.01it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 155/2349 [00:19<15:07,  2.42it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 156/2349 [00:19<12:34,  2.91it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 158/2349 [00:20<08:13,  4.44it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 161/2349 [00:20<05:07,  7.12it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 164/2349 [00:20<03:39,  9.96it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 168/2349 [00:20<02:32, 14.28it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 171/2349 [00:20<02:24, 15.07it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   7%|▋         | 174/2349 [00:20<02:07, 17.12it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 177/2349 [00:20<01:54, 19.02it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 180/2349 [00:20<01:44, 20.81it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 183/2349 [00:21<02:10, 16.54it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 187/2349 [00:21<01:46, 20.30it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 191/2349 [00:21<01:51, 19.44it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 194/2349 [00:21<02:06, 17.08it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   8%|▊         | 197/2349 [00:21<01:53, 18.90it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▊         | 200/2349 [00:22<01:49, 19.56it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▊         | 203/2349 [00:22<02:12, 16.20it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▊         | 205/2349 [00:22<02:13, 16.02it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 208/2349 [00:22<01:58, 18.10it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 211/2349 [00:22<01:53, 18.90it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 214/2349 [00:22<01:54, 18.59it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 217/2349 [00:23<01:43, 20.64it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 220/2349 [00:23<01:42, 20.82it/s]
2;1mProcessing: negative r2g, 0.85 quantile:   9%|▉         | 223/2349 [00:23<01:37, 21.84it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|▉         | 226/2349 [00:23<01:35, 22.21it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|▉         | 229/2349 [00:23<01:44, 20.24it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|▉         | 232/2349 [00:23<02:03, 17.13it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|█         | 235/2349 [00:23<01:50, 19.07it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|█         | 238/2349 [00:24<02:00, 17.49it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|█         | 241/2349 [00:24<01:48, 19.42it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  10%|█         | 244/2349 [00:24<02:07, 16.50it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 247/2349 [00:24<01:57, 17.96it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 251/2349 [00:24<01:38, 21.26it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 254/2349 [00:25<01:59, 17.50it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 256/2349 [00:25<01:59, 17.56it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 260/2349 [00:25<01:39, 20.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█         | 263/2349 [00:25<01:39, 21.07it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█▏        | 266/2349 [00:25<01:38, 21.19it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  11%|█▏        | 269/2349 [00:25<01:58, 17.62it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 271/2349 [00:25<01:56, 17.87it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 274/2349 [00:26<01:53, 18.27it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 276/2349 [00:26<01:52, 18.45it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 278/2349 [00:26<02:06, 16.39it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 281/2349 [00:26<01:54, 18.03it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 284/2349 [00:26<01:44, 19.68it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 287/2349 [00:26<01:34, 21.75it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 290/2349 [00:26<01:33, 21.99it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  12%|█▏        | 293/2349 [00:26<01:27, 23.58it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 296/2349 [00:27<01:25, 24.14it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 299/2349 [00:27<01:25, 23.87it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 302/2349 [00:27<01:30, 22.68it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 306/2349 [00:27<01:17, 26.47it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 309/2349 [00:27<01:17, 26.19it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 312/2349 [00:27<01:37, 20.81it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  13%|█▎        | 315/2349 [00:27<01:35, 21.35it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▎        | 318/2349 [00:28<01:44, 19.52it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▎        | 321/2349 [00:28<02:10, 15.50it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 323/2349 [00:28<02:09, 15.65it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 325/2349 [00:28<02:10, 15.53it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 328/2349 [00:28<01:53, 17.79it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 331/2349 [00:28<01:47, 18.74it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 333/2349 [00:29<02:22, 14.12it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 335/2349 [00:29<02:59, 11.24it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 337/2349 [00:29<03:32,  9.46it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 339/2349 [00:30<04:17,  7.82it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  14%|█▍        | 340/2349 [00:30<04:29,  7.45it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 341/2349 [00:34<33:01,  1.01it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 342/2349 [00:35<27:19,  1.22it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 343/2349 [00:35<22:48,  1.47it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 344/2349 [00:35<19:03,  1.75it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 345/2349 [00:35<16:16,  2.05it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 346/2349 [00:36<13:39,  2.44it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 347/2349 [00:36<11:27,  2.91it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 348/2349 [00:36<09:58,  3.34it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 349/2349 [00:36<09:11,  3.62it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 350/2349 [00:36<08:10,  4.07it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 351/2349 [00:36<07:34,  4.40it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▍        | 352/2349 [00:37<07:23,  4.51it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 353/2349 [00:37<07:07,  4.66it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 355/2349 [00:37<04:50,  6.86it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 357/2349 [00:37<03:47,  8.74it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 359/2349 [00:37<03:20,  9.93it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 361/2349 [00:37<03:12, 10.33it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  15%|█▌        | 363/2349 [00:38<02:50, 11.67it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 365/2349 [00:38<02:37, 12.63it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 367/2349 [00:38<02:39, 12.44it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 369/2349 [00:38<02:29, 13.21it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 371/2349 [00:38<02:15, 14.63it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 373/2349 [00:38<02:36, 12.61it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 375/2349 [00:39<03:04, 10.70it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 377/2349 [00:39<03:27,  9.52it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 379/2349 [00:39<03:01, 10.87it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▌        | 381/2349 [00:39<03:45,  8.75it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▋        | 383/2349 [00:39<03:12, 10.19it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▋        | 385/2349 [00:40<02:51, 11.48it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  16%|█▋        | 387/2349 [00:40<02:40, 12.24it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 389/2349 [00:40<02:24, 13.57it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 391/2349 [00:40<02:10, 14.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 394/2349 [00:40<01:48, 18.09it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 397/2349 [00:40<01:41, 19.27it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 400/2349 [00:40<01:35, 20.31it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 403/2349 [00:40<01:47, 18.12it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 405/2349 [00:41<02:08, 15.13it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 408/2349 [00:41<01:53, 17.14it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  17%|█▋        | 411/2349 [00:41<01:55, 16.80it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 414/2349 [00:41<01:50, 17.49it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 416/2349 [00:41<01:49, 17.71it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 419/2349 [00:41<01:40, 19.16it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 422/2349 [00:42<02:01, 15.85it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 424/2349 [00:42<02:03, 15.54it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 426/2349 [00:42<02:03, 15.54it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 428/2349 [00:42<02:06, 15.17it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 430/2349 [00:42<01:59, 16.12it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 432/2349 [00:42<02:00, 15.90it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  18%|█▊        | 434/2349 [00:42<02:17, 13.94it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▊        | 436/2349 [00:43<02:54, 10.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▊        | 438/2349 [00:43<03:22,  9.41it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▊        | 440/2349 [00:43<04:00,  7.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 442/2349 [00:44<03:38,  8.75it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 444/2349 [00:44<03:04, 10.32it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 446/2349 [00:44<02:53, 10.95it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 448/2349 [00:44<02:40, 11.84it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 451/2349 [00:44<02:07, 14.89it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 454/2349 [00:44<01:52, 16.92it/s]
2;1mProcessing: negative r2g, 0.85 quantile:  19%|█▉        | 457/2349 [00:44<01:47, 17.60it/s]

Processing: negative r2g, 0.9 quantile:  29%|██▊       | 723/2529 [00:41<01:10, 25.48it/s]
Processing: negative r2g, 0.9 quantile:  29%|██▉       | 729/2529 [00:41<00:55, 32.55it/s]
Processing: negative r2g, 0.9 quantile:  29%|██▉       | 734/2529 [00:42<00:59, 30.42it/s]
Processing: negative r2g, 0.9 quantile:  29%|██▉       | 738/2529 [00:42<01:10, 25.47it/s]
Processing: negative r2g, 0.9 quantile:  29%|██▉       | 743/2529 [00:42<01:00, 29.51it/s]
Processing: negative r2g, 0.9 quantile:  30%|██▉       | 747/2529 [00:42<01:00, 29.32it/s]
Processing: negative r2g, 0.9 quantile:  30%|██▉       | 751/2529 [00:42<01:02, 28.32it/s]
Processing: negative r2g, 0.9 quantile:  30%|██▉       | 754/2529 [00:42<01:06, 26.74it/s]
Processing: negative r2g, 0.9 quantile:  30%|██▉       | 757/2529 [00:43<01:08, 25.71it/s]
Processing: negative r2g, 0.9 quantile:  30%|███       | 762/2529 [00:43<00:56, 31.12it/s]
Processing: negative r2g, 0.9 quantile:  30%|███       | 766/2529 [00:43<00:53, 32.85it/s]
Processing: negative r2g, 0.9 quantile:  30%|███       | 771/2529 [00:43<00:49, 35.19it/s]
Processing: negative r2g, 0.9 quantile:  31%|███       | 776/2529 [00:43<00:45, 38.49it/s]
Processing: negative r2g, 0.9 quantile:  31%|███       | 780/2529 [00:43<00:46, 37.52it/s]
Processing: negative r2g, 0.9 quantile:  31%|███       | 784/2529 [00:43<00:49, 35.29it/s]
Processing: negative r2g, 0.9 quantile:  31%|███       | 788/2529 [00:43<00:55, 31.48it/s]
Processing: negative r2g, 0.9 quantile:  31%|███▏      | 792/2529 [00:44<01:06, 26.20it/s]
Processing: negative r2g, 0.9 quantile:  31%|███▏      | 796/2529 [00:44<01:07, 25.60it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 799/2529 [00:44<01:08, 25.42it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 803/2529 [00:44<01:00, 28.47it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 807/2529 [00:44<01:18, 21.82it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 811/2529 [00:44<01:10, 24.53it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 815/2529 [00:45<01:07, 25.54it/s]
Processing: negative r2g, 0.9 quantile:  32%|███▏      | 819/2529 [00:45<01:02, 27.41it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 824/2529 [00:45<00:52, 32.20it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 828/2529 [00:45<01:07, 25.37it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 833/2529 [00:45<00:56, 29.91it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 837/2529 [00:45<00:57, 29.60it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 842/2529 [00:45<00:50, 33.20it/s]
Processing: negative r2g, 0.9 quantile:  33%|███▎      | 846/2529 [00:45<00:50, 33.62it/s]
Processing: negative r2g, 0.9 quantile:  34%|███▎      | 850/2529 [00:46<00:49, 34.05it/s]
Processing: negative r2g, 0.9 quantile:  34%|███▍      | 855/2529 [00:46<00:44, 37.84it/s]
Processing: negative r2g, 0.9 quantile:  34%|███▍      | 861/2529 [00:46<00:39, 42.44it/s]
Processing: negative r2g, 0.9 quantile:  34%|███▍      | 866/2529 [00:46<00:38, 43.35it/s]
Processing: negative r2g, 0.9 quantile:  34%|███▍      | 872/2529 [00:46<00:37, 44.78it/s]
Processing: negative r2g, 0.9 quantile:  35%|███▍      | 877/2529 [00:46<00:37, 44.47it/s]
Processing: negative r2g, 0.9 quantile:  35%|███▍      | 882/2529 [00:46<00:44, 36.65it/s]
Processing: negative r2g, 0.9 quantile:  35%|███▌      | 887/2529 [00:46<00:41, 39.37it/s]
Processing: negative r2g, 0.9 quantile:  35%|███▌      | 892/2529 [00:47<00:40, 40.64it/s]
Processing: negative r2g, 0.9 quantile:  36%|███▌      | 898/2529 [00:47<00:37, 43.96it/s]
Processing: negative r2g, 0.9 quantile:  36%|███▌      | 903/2529 [00:47<00:44, 36.54it/s]
Processing: negative r2g, 0.9 quantile:  36%|███▌      | 908/2529 [00:47<00:41, 38.64it/s]
Processing: negative r2g, 0.9 quantile:  36%|███▌      | 913/2529 [00:47<00:42, 37.94it/s]
Processing: negative r2g, 0.9 quantile:  36%|███▋      | 918/2529 [00:47<00:42, 38.15it/s]
Processing: negative r2g, 0.9 quantile:  37%|███▋      | 924/2529 [00:47<00:37, 42.82it/s]
Processing: negative r2g, 0.9 quantile:  37%|███▋      | 931/2529 [00:48<00:34, 46.60it/s]
Processing: negative r2g, 0.9 quantile:  37%|███▋      | 936/2529 [00:48<00:41, 38.06it/s]
Processing: negative r2g, 0.9 quantile:  37%|███▋      | 941/2529 [00:48<00:46, 34.48it/s]
Processing: negative r2g, 0.9 quantile:  37%|███▋      | 945/2529 [00:48<00:47, 33.66it/s]
Processing: negative r2g, 0.9 quantile:  38%|███▊      | 950/2529 [00:48<00:43, 36.63it/s]
Processing: negative r2g, 0.9 quantile:  38%|███▊      | 954/2529 [00:48<00:44, 35.55it/s]
Processing: negative r2g, 0.9 quantile:  38%|███▊      | 958/2529 [00:48<00:44, 35.66it/s]
Processing: negative r2g, 0.9 quantile:  38%|███▊      | 965/2529 [00:48<00:36, 43.07it/s]
Processing: negative r2g, 0.9 quantile:  38%|███▊      | 970/2529 [00:49<00:40, 38.90it/s]
Processing: negative r2g, 0.9 quantile:  39%|███▊      | 976/2529 [00:49<00:37, 41.33it/s]
Processing: negative r2g, 0.9 quantile:  39%|███▉      | 981/2529 [00:49<00:41, 37.15it/s]
Processing: negative r2g, 0.9 quantile:  39%|███▉      | 986/2529 [00:49<00:41, 37.19it/s]
Processing: negative r2g, 0.9 quantile:  39%|███▉      | 991/2529 [00:49<00:38, 40.05it/s]
Processing: negative r2g, 0.9 quantile:  39%|███▉      | 996/2529 [00:49<00:37, 40.86it/s]
Processing: negative r2g, 0.9 quantile:  40%|███▉      | 1002/2529 [00:49<00:34, 44.40it/s]
Processing: negative r2g, 0.9 quantile:  40%|███▉      | 1007/2529 [00:50<00:36, 41.82it/s]
Processing: negative r2g, 0.9 quantile:  40%|███▉      | 1007/2529 [01:08<00:36, 41.82it/s]
Processing: negative r2g, 0.9 quantile:  40%|███▉      | 1008/2529 [01:09<36:50,  1.45s/it]
Processing: negative r2g, 0.9 quantile:  40%|████      | 1012/2529 [01:09<25:53,  1.02s/it]
Processing: negative r2g, 0.9 quantile:  40%|████      | 1017/2529 [01:09<17:09,  1.47it/s]
Processing: negative r2g, 0.9 quantile:  40%|████      | 1023/2529 [01:09<10:51,  2.31it/s]
Processing: negative r2g, 0.9 quantile:  41%|████      | 1028/2529 [01:09<07:43,  3.24it/s]
Processing: negative r2g, 0.9 quantile:  41%|████      | 1034/2529 [01:09<05:11,  4.80it/s]
Processing: negative r2g, 0.9 quantile:  41%|████      | 1039/2529 [01:09<03:50,  6.46it/s]
Processing: negative r2g, 0.9 quantile:  41%|████▏     | 1044/2529 [01:09<02:53,  8.57it/s]
Processing: negative r2g, 0.9 quantile:  41%|████▏     | 1049/2529 [01:10<02:11, 11.22it/s]
Processing: negative r2g, 0.9 quantile:  42%|████▏     | 1054/2529 [01:10<01:49, 13.48it/s]
Processing: negative r2g, 0.9 quantile:  42%|████▏     | 1059/2529 [01:10<01:26, 16.99it/s]
Processing: negative r2g, 0.9 quantile:  42%|████▏     | 1065/2529 [01:10<01:08, 21.53it/s]
Processing: negative r2g, 0.9 quantile:  42%|████▏     | 1070/2529 [01:10<00:58, 25.04it/s]
Processing: negative r2g, 0.9 quantile:  43%|████▎     | 1075/2529 [01:10<00:54, 26.51it/s]
Processing: negative r2g, 0.9 quantile:  43%|████▎     | 1080/2529 [01:10<00:49, 29.43it/s]
Processing: negative r2g, 0.9 quantile:  43%|████▎     | 1087/2529 [01:11<00:39, 36.48it/s]
Processing: negative r2g, 0.9 quantile:  43%|████▎     | 1092/2529 [01:11<00:38, 37.42it/s]
Processing: negative r2g, 0.9 quantile:  43%|████▎     | 1097/2529 [01:11<00:36, 39.08it/s]
Processing: negative r2g, 0.9 quantile:  44%|████▎     | 1102/2529 [01:11<00:35, 40.34it/s]
Processing: negative r2g, 0.9 quantile:  44%|████▍     | 1107/2529 [01:11<00:37, 38.26it/s]
Processing: negative r2g, 0.9 quantile:  44%|████▍     | 1113/2529 [01:11<00:33, 42.47it/s]
Processing: negative r2g, 0.9 quantile:  44%|████▍     | 1118/2529 [01:11<00:32, 43.35it/s]
Processing: negative r2g, 0.9 quantile:  44%|████▍     | 1123/2529 [01:11<00:31, 44.86it/s]
Processing: negative r2g, 0.9 quantile:  45%|████▍     | 1128/2529 [01:11<00:33, 42.25it/s]
Processing: negative r2g, 0.9 quantile:  45%|████▍     | 1133/2529 [01:12<00:34, 39.92it/s]
Processing: negative r2g, 0.9 quantile:  45%|████▍     | 1138/2529 [01:12<00:33, 41.17it/s]
Processing: negative r2g, 0.9 quantile:  45%|████▌     | 1143/2529 [01:12<00:32, 42.37it/s]
Processing: negative r2g, 0.9 quantile:  45%|████▌     | 1148/2529 [01:12<00:31, 44.23it/s]
Processing: negative r2g, 0.9 quantile:  46%|████▌     | 1153/2529 [01:12<00:34, 40.12it/s]
Processing: negative r2g, 0.9 quantile:  46%|████▌     | 1158/2529 [01:12<00:33, 41.20it/s]
Processing: negative r2g, 0.9 quantile:  46%|████▌     | 1163/2529 [01:12<00:33, 40.24it/s]
Processing: negative r2g, 0.9 quantile:  46%|████▌     | 1169/2529 [01:12<00:30, 44.07it/s]
Processing: negative r2g, 0.9 quantile:  46%|████▋     | 1174/2529 [01:13<00:30, 43.85it/s]
Processing: negative r2g, 0.9 quantile:  47%|████▋     | 1180/2529 [01:13<00:29, 46.03it/s]
Processing: negative r2g, 0.9 quantile:  47%|████▋     | 1186/2529 [01:13<00:27, 48.96it/s]
Processing: negative r2g, 0.9 quantile:  47%|████▋     | 1191/2529 [01:13<00:29, 46.05it/s]
Processing: negative r2g, 0.9 quantile:  47%|████▋     | 1196/2529 [01:13<00:33, 39.47it/s]
Processing: negative r2g, 0.9 quantile:  47%|████▋     | 1201/2529 [01:13<00:34, 38.40it/s]
Processing: negative r2g, 0.9 quantile:  48%|████▊     | 1206/2529 [01:13<00:32, 40.26it/s]
Processing: negative r2g, 0.9 quantile:  48%|████▊     | 1211/2529 [01:13<00:34, 38.03it/s]
Processing: negative r2g, 0.9 quantile:  48%|████▊     | 1216/2529 [01:14<00:33, 39.14it/s]
Processing: negative r2g, 0.9 quantile:  48%|████▊     | 1221/2529 [01:14<00:32, 40.07it/s]
Processing: negative r2g, 0.9 quantile:  48%|████▊     | 1226/2529 [01:14<00:33, 39.18it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▊     | 1230/2529 [01:14<00:33, 38.64it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▉     | 1234/2529 [01:14<00:34, 37.54it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▉     | 1239/2529 [01:14<00:33, 38.33it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▉     | 1243/2529 [01:14<00:42, 30.05it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▉     | 1247/2529 [01:15<00:47, 27.05it/s]
Processing: negative r2g, 0.9 quantile:  49%|████▉     | 1251/2529 [01:15<00:44, 28.72it/s]
Processing: negative r2g, 0.9 quantile:  50%|████▉     | 1255/2529 [01:15<00:44, 28.32it/s]
Processing: negative r2g, 0.9 quantile:  50%|████▉     | 1258/2529 [01:15<00:49, 25.47it/s]
Processing: negative r2g, 0.9 quantile:  50%|████▉     | 1263/2529 [01:15<00:42, 29.89it/s]
Processing: negative r2g, 0.9 quantile:  50%|█████     | 1267/2529 [01:15<00:44, 28.67it/s]
Processing: negative r2g, 0.9 quantile:  50%|█████     | 1272/2529 [01:15<00:39, 31.94it/s]
Processing: negative r2g, 0.9 quantile:  50%|█████     | 1276/2529 [01:16<00:45, 27.26it/s]
Processing: negative r2g, 0.9 quantile:  51%|█████     | 1280/2529 [01:16<00:43, 28.53it/s]
Processing: negative r2g, 0.9 quantile:  51%|█████     | 1285/2529 [01:16<00:37, 33.37it/s]
Processing: negative r2g, 0.9 quantile:  51%|█████     | 1291/2529 [01:16<00:31, 39.64it/s]
Processing: negative r2g, 0.9 quantile:  51%|█████▏    | 1297/2529 [01:16<00:29, 42.23it/s]
Processing: negative r2g, 0.9 quantile:  51%|█████▏    | 1302/2529 [01:16<00:32, 37.72it/s]
Processing: negative r2g, 0.9 quantile:  52%|█████▏    | 1307/2529 [01:16<00:37, 32.52it/s]
Processing: negative r2g, 0.9 quantile:  52%|█████▏    | 1312/2529 [01:17<00:34, 35.73it/s]
Processing: negative r2g, 0.9 quantile:  52%|█████▏    | 1317/2529 [01:17<00:31, 38.88it/s]
Processing: negative r2g, 0.9 quantile:  52%|█████▏    | 1322/2529 [01:17<00:35, 34.44it/s]
Processing: negative r2g, 0.9 quantile:  52%|█████▏    | 1326/2529 [01:17<00:34, 35.00it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1330/2529 [01:17<00:33, 36.09it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1334/2529 [01:17<00:39, 30.32it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1338/2529 [01:17<00:36, 32.52it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1343/2529 [01:17<00:32, 36.43it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1347/2529 [01:18<00:32, 36.87it/s]
Processing: negative r2g, 0.9 quantile:  53%|█████▎    | 1351/2529 [01:18<00:53, 22.01it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▎    | 1355/2529 [01:18<00:54, 21.55it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▎    | 1358/2529 [01:18<00:51, 22.53it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1361/2529 [01:18<00:52, 22.10it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1364/2529 [01:19<00:56, 20.59it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1367/2529 [01:19<01:02, 18.65it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1370/2529 [01:19<01:05, 17.75it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1372/2529 [01:19<01:07, 17.12it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1375/2529 [01:19<01:01, 18.74it/s]
Processing: negative r2g, 0.9 quantile:  54%|█████▍    | 1378/2529 [01:19<00:56, 20.30it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▍    | 1381/2529 [01:19<00:57, 19.86it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▍    | 1384/2529 [01:20<00:53, 21.53it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▍    | 1389/2529 [01:20<00:48, 23.42it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▌    | 1392/2529 [01:20<00:55, 20.60it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▌    | 1395/2529 [01:20<00:59, 18.90it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▌    | 1397/2529 [01:20<01:00, 18.66it/s]
Processing: negative r2g, 0.9 quantile:  55%|█████▌    | 1401/2529 [01:20<00:52, 21.48it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1404/2529 [01:21<00:50, 22.12it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1407/2529 [01:21<00:52, 21.48it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1410/2529 [01:21<00:53, 20.77it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1413/2529 [01:21<00:50, 22.28it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1417/2529 [01:21<00:43, 25.51it/s]

Processing: negative r2g, 0.9 quantile:  56%|█████▌    | 1421/2529 [01:21<00:39, 28.20it/s]
Processing: negative r2g, 0.9 quantile:  56%|█████▋    | 1425/2529 [01:21<00:39, 27.83it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1429/2529 [01:21<00:38, 28.85it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1433/2529 [01:22<00:35, 31.10it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1437/2529 [01:22<00:32, 33.23it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1441/2529 [01:22<00:39, 27.41it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1445/2529 [01:22<00:36, 30.09it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1449/2529 [01:22<00:33, 32.41it/s]
Processing: negative r2g, 0.9 quantile:  57%|█████▋    | 1453/2529 [01:22<00:38, 27.89it/s]
Processing: negative r2g, 0.9 quantile:  58%|█████▊    | 1459/2529 [01:22<00:31, 34.51it/s]
Processing: negative r2g, 0.9 quantile:  58%|█████▊    | 1463/2529 [01:23<00:33, 31.62it/s]
Processing: negative r2g, 0.9 quantile:  58%|█████▊    | 1469/2529 [01:23<00:28, 36.91it/s]
Processing: negative r2g, 0.9 quantile:  58%|█████▊    | 1474/2529 [01:23<00:27, 39.02it/s]
Processing: negative r2g, 0.9 quantile:  58%|█████▊    | 1479/2529 [01:23<00:27, 37.73it/s]
Processing: negative r2g, 0.9 quantile:  59%|█████▊    | 1484/2529 [01:23<00:25, 40.29it/s]
Processing: negative r2g, 0.9 quantile:  59%|█████▉    | 1489/2529 [01:23<00:30, 34.32it/s]
Processing: negative r2g, 0.9 quantile:  59%|█████▉    | 1494/2529 [01:23<00:27, 37.26it/s]
Processing: negative r2g, 0.9 quantile:  59%|█████▉    | 1499/2529 [01:23<00:26, 39.40it/s]
Processing: negative r2g, 0.9 quantile:  59%|█████▉    | 1504/2529 [01:24<00:25, 40.76it/s]
Processing: negative r2g, 0.9 quantile:  60%|█████▉    | 1509/2529 [01:24<00:30, 33.86it/s]
Processing: negative r2g, 0.9 quantile:  60%|█████▉    | 1514/2529 [01:24<00:27, 36.30it/s]
Processing: negative r2g, 0.9 quantile:  60%|██████    | 1518/2529 [01:24<00:29, 34.13it/s]
Processing: negative r2g, 0.9 quantile:  60%|██████    | 1524/2529 [01:24<00:26, 37.83it/s]
Processing: negative r2g, 0.9 quantile:  60%|██████    | 1528/2529 [01:24<00:26, 37.96it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████    | 1532/2529 [01:24<00:27, 36.82it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████    | 1536/2529 [01:24<00:27, 35.83it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████    | 1540/2529 [01:25<00:27, 36.04it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████    | 1544/2529 [01:25<00:29, 33.06it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████    | 1549/2529 [01:25<00:27, 35.97it/s]
Processing: negative r2g, 0.9 quantile:  61%|██████▏   | 1555/2529 [01:25<00:24, 40.01it/s]
Processing: negative r2g, 0.9 quantile:  62%|██████▏   | 1561/2529 [01:25<00:22, 42.44it/s]
Processing: negative r2g, 0.9 quantile:  62%|██████▏   | 1566/2529 [01:25<00:24, 39.93it/s]
Processing: negative r2g, 0.9 quantile:  62%|██████▏   | 1571/2529 [01:25<00:24, 38.50it/s]
Processing: negative r2g, 0.9 quantile:  62%|██████▏   | 1577/2529 [01:25<00:22, 41.83it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1582/2529 [01:26<00:28, 33.02it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1586/2529 [01:26<00:27, 34.07it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1590/2529 [01:26<00:27, 34.02it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1594/2529 [01:26<00:31, 29.99it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1598/2529 [01:26<00:30, 30.72it/s]
Processing: negative r2g, 0.9 quantile:  63%|██████▎   | 1602/2529 [01:26<00:28, 32.34it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▎   | 1606/2529 [01:27<00:34, 26.39it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▎   | 1609/2529 [01:27<00:39, 23.10it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▎   | 1612/2529 [01:27<00:45, 20.29it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1615/2529 [01:27<00:53, 17.13it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1617/2529 [01:27<00:53, 16.91it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1619/2529 [01:27<00:55, 16.34it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1621/2529 [01:28<00:59, 15.24it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1623/2529 [01:28<00:59, 15.11it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1625/2529 [01:28<01:02, 14.55it/s]
Processing: negative r2g, 0.9 quantile:  64%|██████▍   | 1629/2529 [01:28<00:45, 19.86it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▍   | 1633/2529 [01:28<00:38, 23.34it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▍   | 1636/2529 [01:28<00:38, 23.13it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▍   | 1639/2529 [01:28<00:36, 24.48it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▍   | 1643/2529 [01:28<00:33, 26.82it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▌   | 1646/2529 [01:29<00:33, 26.38it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▌   | 1649/2529 [01:29<00:43, 20.37it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▌   | 1652/2529 [01:29<00:44, 19.58it/s]
Processing: negative r2g, 0.9 quantile:  65%|██████▌   | 1655/2529 [01:29<00:46, 18.66it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▌   | 1659/2529 [01:29<00:37, 23.03it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▌   | 1662/2529 [01:29<00:37, 23.38it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▌   | 1665/2529 [01:30<00:39, 22.13it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▌   | 1668/2529 [01:30<00:36, 23.86it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▌   | 1671/2529 [01:30<00:35, 24.17it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▋   | 1676/2529 [01:30<00:29, 29.03it/s]
Processing: negative r2g, 0.9 quantile:  66%|██████▋   | 1681/2529 [01:30<00:28, 29.81it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1685/2529 [01:30<00:30, 27.48it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1688/2529 [01:30<00:30, 27.76it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1691/2529 [01:30<00:29, 28.25it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1695/2529 [01:31<00:29, 28.71it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1698/2529 [01:31<00:29, 28.10it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1701/2529 [01:31<00:34, 23.83it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1704/2529 [01:31<00:38, 21.49it/s]
Processing: negative r2g, 0.9 quantile:  67%|██████▋   | 1707/2529 [01:31<00:41, 19.92it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1711/2529 [01:31<00:39, 20.97it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1714/2529 [01:32<00:41, 19.48it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1717/2529 [01:32<00:44, 18.09it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1721/2529 [01:32<00:37, 21.76it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1724/2529 [01:32<00:35, 22.98it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1727/2529 [01:32<00:38, 20.58it/s]
Processing: negative r2g, 0.9 quantile:  68%|██████▊   | 1730/2529 [01:32<00:44, 18.14it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▊   | 1734/2529 [01:33<00:36, 21.79it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▊   | 1737/2529 [01:33<00:33, 23.40it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▉   | 1740/2529 [01:33<00:34, 22.91it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▉   | 1743/2529 [01:33<00:33, 23.52it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▉   | 1747/2529 [01:33<00:28, 27.00it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▉   | 1751/2529 [01:33<00:26, 29.36it/s]
Processing: negative r2g, 0.9 quantile:  69%|██████▉   | 1755/2529 [01:33<00:26, 29.63it/s]
Processing: negative r2g, 0.9 quantile:  70%|██████▉   | 1760/2529 [01:33<00:22, 34.38it/s]
Processing: negative r2g, 0.9 quantile:  70%|██████▉   | 1766/2529 [01:33<00:18, 41.04it/s]
Processing: negative r2g, 0.9 quantile:  70%|███████   | 1771/2529 [01:34<00:20, 36.93it/s]
Processing: negative r2g, 0.9 quantile:  70%|███████   | 1775/2529 [01:34<00:21, 34.80it/s]
Processing: negative r2g, 0.9 quantile:  70%|███████   | 1779/2529 [01:34<00:23, 32.60it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████   | 1785/2529 [01:34<00:20, 35.60it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████   | 1789/2529 [01:34<00:26, 27.58it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████   | 1795/2529 [01:34<00:22, 33.32it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████   | 1800/2529 [01:34<00:20, 35.71it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████▏  | 1804/2529 [01:35<00:21, 33.18it/s]
Processing: negative r2g, 0.9 quantile:  71%|███████▏  | 1808/2529 [01:35<00:23, 30.54it/s]
Processing: negative r2g, 0.9 quantile:  72%|███████▏  | 1812/2529 [01:35<00:22, 32.49it/s]
Processing: negative r2g, 0.9 quantile:  72%|███████▏  | 1817/2529 [01:35<00:20, 35.02it/s]
Processing: negative r2g, 0.9 quantile:  72%|███████▏  | 1821/2529 [01:35<00:19, 35.64it/s]
Processing: negative r2g, 0.9 quantile:  72%|███████▏  | 1826/2529 [01:35<00:19, 36.56it/s]
Processing: negative r2g, 0.9 quantile:  72%|███████▏  | 1830/2529 [01:35<00:20, 34.76it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1834/2529 [01:35<00:20, 34.02it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1838/2529 [01:36<00:22, 30.56it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1842/2529 [01:36<00:25, 26.49it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1845/2529 [01:36<00:28, 23.77it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1849/2529 [01:36<00:26, 25.97it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1852/2529 [01:36<00:26, 25.92it/s]
Processing: negative r2g, 0.9 quantile:  73%|███████▎  | 1856/2529 [01:36<00:23, 28.16it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▎  | 1860/2529 [01:36<00:21, 30.76it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▎  | 1864/2529 [01:37<00:20, 32.41it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▍  | 1868/2529 [01:37<00:20, 32.21it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▍  | 1872/2529 [01:37<00:20, 31.90it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▍  | 1876/2529 [01:37<00:28, 23.02it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▍  | 1879/2529 [01:37<00:29, 22.20it/s]
Processing: negative r2g, 0.9 quantile:  74%|███████▍  | 1882/2529 [01:37<00:28, 22.81it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▍  | 1886/2529 [01:38<00:24, 26.43it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▍  | 1890/2529 [01:38<00:21, 29.52it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▍  | 1894/2529 [01:38<00:22, 28.75it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▌  | 1898/2529 [01:38<00:22, 28.22it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▌  | 1903/2529 [01:38<00:19, 32.68it/s]
Processing: negative r2g, 0.9 quantile:  75%|███████▌  | 1909/2529 [01:38<00:16, 37.35it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▌  | 1913/2529 [01:38<00:21, 28.95it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▌  | 1917/2529 [01:38<00:20, 30.29it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▌  | 1921/2529 [01:39<00:18, 32.24it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▌  | 1926/2529 [01:39<00:17, 35.06it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▋  | 1930/2529 [01:39<00:17, 34.03it/s]
Processing: negative r2g, 0.9 quantile:  76%|███████▋  | 1934/2529 [01:39<00:16, 35.01it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1938/2529 [01:39<00:20, 28.46it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1942/2529 [01:39<00:19, 30.29it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1946/2529 [01:39<00:18, 31.87it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1950/2529 [01:39<00:17, 32.45it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1954/2529 [01:40<00:19, 29.94it/s]
Processing: negative r2g, 0.9 quantile:  77%|███████▋  | 1958/2529 [01:40<00:19, 29.72it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1962/2529 [01:40<00:19, 29.03it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1965/2529 [01:40<00:19, 28.57it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1968/2529 [01:40<00:20, 28.01it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1971/2529 [01:40<00:30, 18.10it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1974/2529 [01:41<00:35, 15.61it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1976/2529 [01:41<00:35, 15.52it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1978/2529 [01:41<00:34, 15.82it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1980/2529 [01:41<00:35, 15.53it/s]
Processing: negative r2g, 0.9 quantile:  78%|███████▊  | 1983/2529 [01:41<00:31, 17.29it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▊  | 1986/2529 [01:41<00:28, 18.76it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▊  | 1989/2529 [01:41<00:25, 20.94it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▉  | 1993/2529 [01:42<00:21, 25.42it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▉  | 1996/2529 [01:42<00:22, 23.28it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▉  | 1999/2529 [01:42<00:25, 20.96it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▉  | 2002/2529 [01:42<00:23, 22.11it/s]
Processing: negative r2g, 0.9 quantile:  79%|███████▉  | 2007/2529 [01:42<00:18, 28.14it/s]
Processing: negative r2g, 0.9 quantile:  80%|███████▉  | 2011/2529 [01:42<00:16, 30.82it/s]
Processing: negative r2g, 0.9 quantile:  80%|███████▉  | 2017/2529 [01:42<00:17, 28.50it/s]
Processing: negative r2g, 0.9 quantile:  80%|███████▉  | 2021/2529 [01:43<00:22, 22.99it/s]

Processing: negative r2g, 0.9 quantile:  80%|████████  | 2025/2529 [01:43<00:19, 25.99it/s]
Processing: negative r2g, 0.9 quantile:  80%|████████  | 2029/2529 [01:43<00:17, 27.83it/s]
Processing: negative r2g, 0.9 quantile:  80%|████████  | 2033/2529 [01:43<00:19, 26.00it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████  | 2036/2529 [01:43<00:19, 25.29it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████  | 2039/2529 [01:43<00:19, 25.01it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████  | 2042/2529 [01:44<00:18, 25.87it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████  | 2048/2529 [01:44<00:14, 33.72it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████  | 2052/2529 [01:44<00:15, 31.34it/s]
Processing: negative r2g, 0.9 quantile:  81%|████████▏ | 2058/2529 [01:44<00:12, 37.36it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2062/2529 [01:44<00:13, 35.04it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2066/2529 [01:44<00:13, 34.29it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2070/2529 [01:44<00:14, 32.42it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2074/2529 [01:44<00:15, 30.13it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2078/2529 [01:45<00:18, 24.87it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2082/2529 [01:45<00:18, 24.10it/s]
Processing: negative r2g, 0.9 quantile:  82%|████████▏ | 2085/2529 [01:45<00:18, 23.87it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2090/2529 [01:45<00:15, 27.99it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2093/2529 [01:45<00:19, 22.59it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2096/2529 [01:45<00:18, 22.79it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2100/2529 [01:46<00:16, 25.87it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2103/2529 [01:46<00:17, 24.55it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2107/2529 [01:46<00:15, 27.83it/s]
Processing: negative r2g, 0.9 quantile:  83%|████████▎ | 2110/2529 [01:46<00:15, 26.48it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▎ | 2115/2529 [01:46<00:14, 28.98it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▎ | 2118/2529 [01:46<00:17, 22.85it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▍ | 2123/2529 [01:46<00:14, 27.89it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▍ | 2127/2529 [01:47<00:14, 28.15it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▍ | 2132/2529 [01:47<00:12, 31.26it/s]
Processing: negative r2g, 0.9 quantile:  84%|████████▍ | 2136/2529 [01:47<00:12, 31.96it/s]
Processing: negative r2g, 0.9 quantile:  85%|████████▍ | 2141/2529 [01:47<00:11, 33.52it/s]
Processing: negative r2g, 0.9 quantile:  85%|████████▍ | 2145/2529 [01:47<00:11, 33.21it/s]
Processing: negative r2g, 0.9 quantile:  85%|████████▌ | 2151/2529 [01:47<00:09, 39.28it/s]
Processing: negative r2g, 0.9 quantile:  85%|████████▌ | 2156/2529 [01:47<00:09, 39.73it/s]
Processing: negative r2g, 0.9 quantile:  85%|████████▌ | 2162/2529 [01:47<00:08, 44.69it/s]
Processing: negative r2g, 0.9 quantile:  86%|████████▌ | 2167/2529 [01:48<00:08, 41.32it/s]
Processing: negative r2g, 0.9 quantile:  86%|████████▌ | 2172/2529 [02:08<07:13,  1.21s/it]
Processing: negative r2g, 0.9 quantile:  86%|████████▌ | 2172/2529 [02:08<07:13,  1.21s/it]
Processing: negative r2g, 0.9 quantile:  86%|████████▌ | 2175/2529 [02:08<05:46,  1.02it/s]
Processing: negative r2g, 0.9 quantile:  86%|████████▌ | 2180/2529 [02:08<03:53,  1.50it/s]
Processing: negative r2g, 0.9 quantile:  86%|████████▋ | 2185/2529 [02:08<02:39,  2.15it/s]
Processing: negative r2g, 0.9 quantile:  87%|████████▋ | 2190/2529 [02:08<01:50,  3.06it/s]
Processing: negative r2g, 0.9 quantile:  87%|████████▋ | 2195/2529 [02:09<01:18,  4.23it/s]
Processing: negative r2g, 0.9 quantile:  87%|████████▋ | 2200/2529 [02:09<00:56,  5.85it/s]
Processing: negative r2g, 0.9 quantile:  87%|████████▋ | 2205/2529 [02:09<00:41,  7.81it/s]
Processing: negative r2g, 0.9 quantile:  87%|████████▋ | 2210/2529 [02:09<00:31, 10.23it/s]
Processing: negative r2g, 0.9 quantile:  88%|████████▊ | 2216/2529 [02:09<00:22, 14.20it/s]
Processing: negative r2g, 0.9 quantile:  88%|████████▊ | 2223/2529 [02:09<00:15, 19.34it/s]
Processing: negative r2g, 0.9 quantile:  88%|████████▊ | 2228/2529 [02:09<00:14, 21.35it/s]
Processing: negative r2g, 0.9 quantile:  88%|████████▊ | 2233/2529 [02:09<00:12, 24.27it/s]
Processing: negative r2g, 0.9 quantile:  88%|████████▊ | 2238/2529 [02:10<00:12, 23.93it/s]
Processing: negative r2g, 0.9 quantile:  89%|████████▊ | 2242/2529 [02:10<00:11, 24.53it/s]
Processing: negative r2g, 0.9 quantile:  89%|████████▉ | 2247/2529 [02:10<00:10, 26.85it/s]
Processing: negative r2g, 0.9 quantile:  89%|████████▉ | 2251/2529 [02:10<00:09, 28.09it/s]
Processing: negative r2g, 0.9 quantile:  89%|████████▉ | 2257/2529 [02:10<00:07, 34.41it/s]
Processing: negative r2g, 0.9 quantile:  89%|████████▉ | 2262/2529 [02:10<00:07, 33.85it/s]
Processing: negative r2g, 0.9 quantile:  90%|████████▉ | 2267/2529 [02:10<00:07, 37.09it/s]
Processing: negative r2g, 0.9 quantile:  90%|████████▉ | 2272/2529 [02:11<00:07, 36.68it/s]
Processing: negative r2g, 0.9 quantile:  90%|████████▉ | 2276/2529 [02:11<00:07, 33.62it/s]
Processing: negative r2g, 0.9 quantile:  90%|█████████ | 2280/2529 [02:11<00:07, 33.46it/s]
Processing: negative r2g, 0.9 quantile:  90%|█████████ | 2286/2529 [02:11<00:06, 38.42it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████ | 2290/2529 [02:11<00:06, 36.99it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████ | 2295/2529 [02:11<00:05, 39.27it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████ | 2301/2529 [02:11<00:05, 39.78it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████ | 2306/2529 [02:11<00:05, 38.79it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████▏| 2310/2529 [02:12<00:06, 35.99it/s]
Processing: negative r2g, 0.9 quantile:  91%|█████████▏| 2314/2529 [02:12<00:06, 31.61it/s]
Processing: negative r2g, 0.9 quantile:  92%|█████████▏| 2318/2529 [02:12<00:06, 33.10it/s]
Processing: negative r2g, 0.9 quantile:  92%|█████████▏| 2324/2529 [02:12<00:05, 38.35it/s]
Processing: negative r2g, 0.9 quantile:  92%|█████████▏| 2328/2529 [02:12<00:05, 35.19it/s]
Processing: negative r2g, 0.9 quantile:  92%|█████████▏| 2334/2529 [02:12<00:04, 39.79it/s]
Processing: negative r2g, 0.9 quantile:  92%|█████████▏| 2339/2529 [02:12<00:04, 39.35it/s]
Processing: negative r2g, 0.9 quantile:  93%|█████████▎| 2344/2529 [02:12<00:04, 41.06it/s]
Processing: negative r2g, 0.9 quantile:  93%|█████████▎| 2349/2529 [02:13<00:04, 38.90it/s]
Processing: negative r2g, 0.9 quantile:  93%|█████████▎| 2353/2529 [02:13<00:05, 33.38it/s]
Processing: negative r2g, 0.9 quantile:  93%|█████████▎| 2358/2529 [02:13<00:04, 35.42it/s]
Processing: negative r2g, 0.9 quantile:  93%|█████████▎| 2364/2529 [02:13<00:04, 40.52it/s]
Processing: negative r2g, 0.9 quantile:  94%|█████████▎| 2369/2529 [02:13<00:04, 36.94it/s]
Processing: negative r2g, 0.9 quantile:  94%|█████████▍| 2373/2529 [02:13<00:04, 35.22it/s]
Processing: negative r2g, 0.9 quantile:  94%|█████████▍| 2377/2529 [02:13<00:04, 35.59it/s]
Processing: negative r2g, 0.9 quantile:  94%|█████████▍| 2381/2529 [02:14<00:04, 36.25it/s]
Processing: negative r2g, 0.9 quantile:  94%|█████████▍| 2388/2529 [02:14<00:03, 44.30it/s]
Processing: negative r2g, 0.9 quantile:  95%|█████████▍| 2393/2529 [02:14<00:03, 41.64it/s]
Processing: negative r2g, 0.9 quantile:  95%|█████████▍| 2398/2529 [02:14<00:03, 43.50it/s]
Processing: negative r2g, 0.9 quantile:  95%|█████████▌| 2404/2529 [02:14<00:02, 47.49it/s]
Processing: negative r2g, 0.9 quantile:  95%|█████████▌| 2409/2529 [02:14<00:03, 39.34it/s]
Processing: negative r2g, 0.9 quantile:  95%|█████████▌| 2414/2529 [02:14<00:02, 40.48it/s]
Processing: negative r2g, 0.9 quantile:  96%|█████████▌| 2420/2529 [02:14<00:02, 42.51it/s]
Processing: negative r2g, 0.9 quantile:  96%|█████████▌| 2425/2529 [02:15<00:02, 43.93it/s]
Processing: negative r2g, 0.9 quantile:  96%|█████████▌| 2430/2529 [02:15<00:02, 44.41it/s]
Processing: negative r2g, 0.9 quantile:  96%|█████████▋| 2435/2529 [02:15<00:02, 40.57it/s]
Processing: negative r2g, 0.9 quantile:  96%|█████████▋| 2440/2529 [02:15<00:02, 38.55it/s]
Processing: negative r2g, 0.9 quantile:  97%|█████████▋| 2446/2529 [02:15<00:01, 41.56it/s]
Processing: negative r2g, 0.9 quantile:  97%|█████████▋| 2451/2529 [02:15<00:01, 41.83it/s]
Processing: negative r2g, 0.9 quantile:  97%|█████████▋| 2456/2529 [02:15<00:01, 37.07it/s]
Processing: negative r2g, 0.9 quantile:  97%|█████████▋| 2461/2529 [02:15<00:01, 39.47it/s]
Processing: negative r2g, 0.9 quantile:  98%|█████████▊| 2466/2529 [02:16<00:01, 36.89it/s]
Processing: negative r2g, 0.9 quantile:  98%|█████████▊| 2472/2529 [02:16<00:01, 41.87it/s]
Processing: negative r2g, 0.9 quantile:  98%|█████████▊| 2477/2529 [02:16<00:01, 41.70it/s]
Processing: negative r2g, 0.9 quantile:  98%|█████████▊| 2482/2529 [02:16<00:01, 43.28it/s]
Processing: negative r2g, 0.9 quantile:  98%|█████████▊| 2488/2529 [02:16<00:00, 47.49it/s]
Processing: negative r2g, 0.9 quantile:  99%|█████████▊| 2495/2529 [02:16<00:00, 51.95it/s]
Processing: negative r2g, 0.9 quantile:  99%|█████████▉| 2501/2529 [02:16<00:00, 38.64it/s]
Processing: negative r2g, 0.9 quantile:  99%|█████████▉| 2506/2529 [02:17<00:00, 37.39it/s]
Processing: negative r2g, 0.9 quantile:  99%|█████████▉| 2511/2529 [02:17<00:00, 38.54it/s]
Processing: negative r2g, 0.9 quantile:  99%|█████████▉| 2516/2529 [02:17<00:00, 39.82it/s]
Processing: negative r2g, 0.9 quantile: 100%|█████████▉| 2521/2529 [02:17<00:00, 40.55it/s]
Processing: negative r2g, 0.9 quantile: 100%|█████████▉| 2526/2529 [02:17<00:00, 42.36it/s]
 14%|█▍        | 2/14 [05:14<30:45, 153.79s/it]
Processing: 0.95 quantile, negative r2g:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: 0.95 quantile, negative r2g:   0%|          | 7/2529 [00:00<00:43, 57.93it/s]
Processing: 0.95 quantile, negative r2g:   1%|          | 13/2529 [00:00<00:48, 52.32it/s]
Processing: 0.95 quantile, negative r2g:   1%|          | 19/2529 [00:00<00:53, 46.53it/s]
Processing: 0.95 quantile, negative r2g:   1%|          | 24/2529 [00:00<01:00, 41.42it/s]
Processing: 0.95 quantile, negative r2g:   1%|          | 29/2529 [00:00<01:01, 40.59it/s]
Processing: 0.95 quantile, negative r2g:   1%|▏         | 34/2529 [00:00<01:05, 38.03it/s]
Processing: 0.95 quantile, negative r2g:   2%|▏         | 38/2529 [00:00<01:04, 38.50it/s]
Processing: 0.95 quantile, negative r2g:   2%|▏         | 43/2529 [00:01<01:02, 39.77it/s]
Processing: 0.95 quantile, negative r2g:   2%|▏         | 48/2529 [00:01<01:05, 37.86it/s]
Processing: 0.95 quantile, negative r2g:   2%|▏         | 53/2529 [00:01<01:03, 38.78it/s]
Processing: 0.95 quantile, negative r2g:   2%|▏         | 61/2529 [00:01<00:51, 48.17it/s]
Processing: 0.95 quantile, negative r2g:   3%|▎         | 68/2529 [00:01<00:46, 53.23it/s]
Processing: 0.95 quantile, negative r2g:   3%|▎         | 74/2529 [00:01<00:53, 45.49it/s]
Processing: 0.95 quantile, negative r2g:   3%|▎         | 79/2529 [00:01<00:56, 43.51it/s]
Processing: 0.95 quantile, negative r2g:   3%|▎         | 85/2529 [00:01<00:54, 45.09it/s]
Processing: 0.95 quantile, negative r2g:   4%|▎         | 90/2529 [00:02<00:56, 43.13it/s]
Processing: 0.95 quantile, negative r2g:   4%|▍         | 96/2529 [00:02<00:52, 46.55it/s]
Processing: 0.95 quantile, negative r2g:   4%|▍         | 101/2529 [00:02<00:59, 40.68it/s]
Processing: 0.95 quantile, negative r2g:   4%|▍         | 108/2529 [00:02<00:51, 46.94it/s]
Processing: 0.95 quantile, negative r2g:   4%|▍         | 113/2529 [00:02<00:52, 45.62it/s]
Processing: 0.95 quantile, negative r2g:   5%|▍         | 118/2529 [00:02<01:18, 30.89it/s]
Processing: 0.95 quantile, negative r2g:   5%|▍         | 122/2529 [00:03<01:22, 29.06it/s]
Processing: 0.95 quantile, negative r2g:   5%|▍         | 126/2529 [00:03<01:17, 30.87it/s]
Processing: 0.95 quantile, negative r2g:   5%|▌         | 130/2529 [00:03<01:31, 26.24it/s]
Processing: 0.95 quantile, negative r2g:   5%|▌         | 134/2529 [00:03<01:42, 23.45it/s]
Processing: 0.95 quantile, negative r2g:   5%|▌         | 137/2529 [00:03<01:48, 21.95it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 140/2529 [00:03<01:46, 22.45it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 143/2529 [00:03<01:39, 23.98it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 146/2529 [00:04<01:37, 24.40it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 149/2529 [00:04<01:37, 24.36it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 155/2529 [00:04<01:23, 28.57it/s]
Processing: 0.95 quantile, negative r2g:   6%|▌         | 158/2529 [00:04<01:34, 25.12it/s]
Processing: 0.95 quantile, negative r2g:   6%|▋         | 161/2529 [00:04<01:42, 23.01it/s]
Processing: 0.95 quantile, negative r2g:   6%|▋         | 164/2529 [00:04<01:42, 22.97it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 168/2529 [00:04<01:34, 25.09it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 171/2529 [00:05<01:33, 25.27it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 174/2529 [00:05<01:39, 23.67it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 177/2529 [00:05<01:35, 24.62it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 181/2529 [00:05<01:23, 28.10it/s]
Processing: 0.95 quantile, negative r2g:   7%|▋         | 187/2529 [00:05<01:07, 34.69it/s]
Processing: 0.95 quantile, negative r2g:   8%|▊         | 191/2529 [00:05<01:08, 34.24it/s]
Processing: 0.95 quantile, negative r2g:   8%|▊         | 196/2529 [00:05<01:03, 36.96it/s]
Processing: 0.95 quantile, negative r2g:   8%|▊         | 202/2529 [00:05<00:54, 42.76it/s]
Processing: 0.95 quantile, negative r2g:   8%|▊         | 207/2529 [00:06<01:01, 37.46it/s]
Processing: 0.95 quantile, negative r2g:   8%|▊         | 213/2529 [00:06<00:59, 39.00it/s]

Processing: 0.95 quantile, negative r2g:   9%|▊         | 218/2529 [00:06<00:56, 40.97it/s]
Processing: 0.95 quantile, negative r2g:   9%|▉         | 224/2529 [00:06<00:50, 45.45it/s]
Processing: 0.95 quantile, negative r2g:   9%|▉         | 229/2529 [00:06<00:50, 45.38it/s]
Processing: 0.95 quantile, negative r2g:   9%|▉         | 235/2529 [00:06<00:46, 48.97it/s]
Processing: 0.95 quantile, negative r2g:  10%|▉         | 241/2529 [00:06<00:46, 49.11it/s]
Processing: 0.95 quantile, negative r2g:  10%|▉         | 246/2529 [00:06<00:46, 48.66it/s]
Processing: 0.95 quantile, negative r2g:  10%|▉         | 251/2529 [00:06<00:51, 44.06it/s]
Processing: 0.95 quantile, negative r2g:  10%|█         | 258/2529 [00:07<00:47, 47.49it/s]
Processing: 0.95 quantile, negative r2g:  10%|█         | 263/2529 [00:07<00:51, 44.30it/s]
Processing: 0.95 quantile, negative r2g:  11%|█         | 269/2529 [00:07<00:47, 48.06it/s]
Processing: 0.95 quantile, negative r2g:  11%|█         | 274/2529 [00:07<00:48, 46.77it/s]
Processing: 0.95 quantile, negative r2g:  11%|█         | 281/2529 [00:07<00:44, 50.79it/s]
Processing: 0.95 quantile, negative r2g:  11%|█▏        | 287/2529 [00:07<00:43, 51.64it/s]
Processing: 0.95 quantile, negative r2g:  12%|█▏        | 293/2529 [00:07<00:47, 46.60it/s]
Processing: 0.95 quantile, negative r2g:  12%|█▏        | 298/2529 [00:08<00:51, 42.93it/s]
Processing: 0.95 quantile, negative r2g:  12%|█▏        | 303/2529 [00:08<00:50, 43.91it/s]
Processing: 0.95 quantile, negative r2g:  12%|█▏        | 310/2529 [00:08<00:45, 49.10it/s]
Processing: 0.95 quantile, negative r2g:  13%|█▎        | 317/2529 [00:08<00:40, 54.46it/s]
Processing: 0.95 quantile, negative r2g:  13%|█▎        | 323/2529 [00:08<00:42, 52.22it/s]
Processing: 0.95 quantile, negative r2g:  13%|█▎        | 329/2529 [00:08<00:42, 51.22it/s]
Processing: 0.95 quantile, negative r2g:  13%|█▎        | 335/2529 [00:08<00:52, 42.12it/s]
Processing: 0.95 quantile, negative r2g:  13%|█▎        | 340/2529 [00:08<00:50, 43.42it/s]
Processing: 0.95 quantile, negative r2g:  14%|█▎        | 345/2529 [00:09<00:55, 39.45it/s]
Processing: 0.95 quantile, negative r2g:  14%|█▍        | 351/2529 [00:09<00:50, 43.55it/s]
Processing: 0.95 quantile, negative r2g:  14%|█▍        | 356/2529 [00:09<00:59, 36.65it/s]
Processing: 0.95 quantile, negative r2g:  14%|█▍        | 360/2529 [00:09<01:12, 29.77it/s]
Processing: 0.95 quantile, negative r2g:  14%|█▍        | 364/2529 [00:09<01:23, 25.97it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▍        | 367/2529 [00:09<01:38, 22.03it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▍        | 370/2529 [00:10<01:41, 21.23it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▍        | 373/2529 [00:10<01:46, 20.21it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▍        | 376/2529 [00:10<01:45, 20.43it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▌        | 382/2529 [00:10<01:16, 28.05it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▌        | 386/2529 [00:10<01:11, 30.13it/s]
Processing: 0.95 quantile, negative r2g:  15%|█▌        | 391/2529 [00:10<01:02, 33.98it/s]
Processing: 0.95 quantile, negative r2g:  16%|█▌        | 395/2529 [00:10<01:06, 31.86it/s]
Processing: 0.95 quantile, negative r2g:  16%|█▌        | 399/2529 [00:11<01:22, 25.74it/s]
Processing: 0.95 quantile, negative r2g:  16%|█▌        | 403/2529 [00:11<01:27, 24.38it/s]
Processing: 0.95 quantile, negative r2g:  16%|█▌        | 408/2529 [00:11<01:11, 29.53it/s]
Processing: 0.95 quantile, negative r2g:  16%|█▋        | 412/2529 [00:11<01:16, 27.82it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 418/2529 [00:11<01:03, 33.04it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 423/2529 [00:11<01:00, 35.10it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 428/2529 [00:11<00:57, 36.69it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 432/2529 [00:12<01:00, 34.94it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 437/2529 [00:12<00:56, 36.77it/s]
Processing: 0.95 quantile, negative r2g:  17%|█▋        | 441/2529 [00:12<00:56, 37.00it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 446/2529 [00:12<00:58, 35.59it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 450/2529 [00:12<01:12, 28.51it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 454/2529 [00:12<01:13, 28.21it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 457/2529 [00:12<01:18, 26.26it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 460/2529 [00:13<01:19, 25.90it/s]
Processing: 0.95 quantile, negative r2g:  18%|█▊        | 465/2529 [00:13<01:05, 31.39it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▊        | 469/2529 [00:13<01:11, 28.99it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▊        | 473/2529 [00:13<01:19, 25.99it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▉        | 477/2529 [00:13<01:13, 28.00it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▉        | 481/2529 [00:13<01:10, 29.15it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▉        | 485/2529 [00:13<01:04, 31.58it/s]
Processing: 0.95 quantile, negative r2g:  19%|█▉        | 493/2529 [00:14<00:49, 41.48it/s]
Processing: 0.95 quantile, negative r2g:  20%|█▉        | 500/2529 [00:14<00:42, 47.65it/s]
Processing: 0.95 quantile, negative r2g:  20%|██        | 506/2529 [00:14<00:40, 49.65it/s]
Processing: 0.95 quantile, negative r2g:  20%|██        | 512/2529 [00:14<00:44, 45.29it/s]
Processing: 0.95 quantile, negative r2g:  20%|██        | 517/2529 [00:14<00:44, 45.22it/s]
Processing: 0.95 quantile, negative r2g:  21%|██        | 522/2529 [00:14<00:43, 46.29it/s]
Processing: 0.95 quantile, negative r2g:  21%|██        | 527/2529 [00:14<00:49, 40.42it/s]
Processing: 0.95 quantile, negative r2g:  21%|██        | 536/2529 [00:14<00:41, 48.22it/s]
Processing: 0.95 quantile, negative r2g:  21%|██▏       | 541/2529 [00:15<00:45, 43.67it/s]
Processing: 0.95 quantile, negative r2g:  22%|██▏       | 546/2529 [00:15<00:48, 40.51it/s]
Processing: 0.95 quantile, negative r2g:  22%|██▏       | 554/2529 [00:15<00:42, 46.00it/s]
Processing: 0.95 quantile, negative r2g:  22%|██▏       | 560/2529 [00:15<00:42, 46.37it/s]
Processing: 0.95 quantile, negative r2g:  22%|██▏       | 567/2529 [00:15<00:42, 46.71it/s]
Processing: 0.95 quantile, negative r2g:  23%|██▎       | 572/2529 [00:15<00:43, 45.16it/s]
Processing: 0.95 quantile, negative r2g:  23%|██▎       | 577/2529 [00:15<00:50, 38.70it/s]
Processing: 0.95 quantile, negative r2g:  23%|██▎       | 581/2529 [00:16<00:51, 37.56it/s]
Processing: 0.95 quantile, negative r2g:  23%|██▎       | 585/2529 [00:16<00:51, 38.07it/s]
Processing: 0.95 quantile, negative r2g:  23%|██▎       | 591/2529 [00:16<00:46, 41.79it/s]
Processing: 0.95 quantile, negative r2g:  24%|██▎       | 598/2529 [00:16<00:45, 42.85it/s]
Processing: 0.95 quantile, negative r2g:  24%|██▍       | 603/2529 [00:16<00:48, 39.65it/s]
Processing: 0.95 quantile, negative r2g:  24%|██▍       | 608/2529 [00:16<01:03, 30.10it/s]
Processing: 0.95 quantile, negative r2g:  24%|██▍       | 612/2529 [00:16<01:01, 31.32it/s]
Processing: 0.95 quantile, negative r2g:  24%|██▍       | 617/2529 [00:17<00:55, 34.66it/s]
Processing: 0.95 quantile, negative r2g:  25%|██▍       | 622/2529 [00:17<00:51, 37.05it/s]
Processing: 0.95 quantile, negative r2g:  25%|██▍       | 626/2529 [00:17<00:51, 37.07it/s]
Processing: 0.95 quantile, negative r2g:  25%|██▌       | 633/2529 [00:17<00:42, 45.03it/s]
Processing: 0.95 quantile, negative r2g:  25%|██▌       | 638/2529 [00:17<00:48, 39.29it/s]
Processing: 0.95 quantile, negative r2g:  25%|██▌       | 643/2529 [00:17<00:46, 40.20it/s]
Processing: 0.95 quantile, negative r2g:  26%|██▌       | 650/2529 [00:17<00:40, 45.90it/s]
Processing: 0.95 quantile, negative r2g:  26%|██▌       | 655/2529 [00:17<00:40, 46.21it/s]
Processing: 0.95 quantile, negative r2g:  26%|██▌       | 660/2529 [00:18<00:49, 37.68it/s]
Processing: 0.95 quantile, negative r2g:  26%|██▋       | 666/2529 [00:18<00:45, 41.19it/s]
Processing: 0.95 quantile, negative r2g:  27%|██▋       | 672/2529 [00:18<00:41, 44.71it/s]
Processing: 0.95 quantile, negative r2g:  27%|██▋       | 677/2529 [00:18<00:42, 43.52it/s]
Processing: 0.95 quantile, negative r2g:  27%|██▋       | 682/2529 [00:18<00:43, 42.71it/s]
Processing: 0.95 quantile, negative r2g:  27%|██▋       | 687/2529 [00:18<00:43, 42.04it/s]
Processing: 0.95 quantile, negative r2g:  27%|██▋       | 692/2529 [00:18<01:05, 28.20it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 696/2529 [00:19<01:15, 24.32it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 699/2529 [00:19<01:15, 24.40it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 702/2529 [00:19<01:19, 23.01it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 706/2529 [00:19<01:10, 25.98it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 709/2529 [00:19<01:08, 26.60it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 713/2529 [00:19<01:01, 29.43it/s]
Processing: 0.95 quantile, negative r2g:  28%|██▊       | 717/2529 [00:20<01:12, 25.16it/s]
Processing: 0.95 quantile, negative r2g:  29%|██▊       | 721/2529 [00:20<01:05, 27.74it/s]
Processing: 0.95 quantile, negative r2g:  29%|██▉       | 728/2529 [00:20<00:50, 35.61it/s]
Processing: 0.95 quantile, negative r2g:  29%|██▉       | 734/2529 [00:20<00:50, 35.68it/s]
Processing: 0.95 quantile, negative r2g:  29%|██▉       | 738/2529 [00:20<01:00, 29.58it/s]
Processing: 0.95 quantile, negative r2g:  29%|██▉       | 744/2529 [00:20<00:50, 35.28it/s]
Processing: 0.95 quantile, negative r2g:  30%|██▉       | 748/2529 [00:20<00:52, 34.08it/s]
Processing: 0.95 quantile, negative r2g:  30%|██▉       | 752/2529 [00:21<00:57, 30.88it/s]
Processing: 0.95 quantile, negative r2g:  30%|██▉       | 756/2529 [00:21<00:57, 30.91it/s]
Processing: 0.95 quantile, negative r2g:  30%|███       | 762/2529 [00:21<00:47, 37.15it/s]
Processing: 0.95 quantile, negative r2g:  30%|███       | 767/2529 [00:21<00:46, 37.88it/s]
Processing: 0.95 quantile, negative r2g:  31%|███       | 775/2529 [00:21<00:37, 47.12it/s]
Processing: 0.95 quantile, negative r2g:  31%|███       | 780/2529 [00:21<00:38, 45.72it/s]
Processing: 0.95 quantile, negative r2g:  31%|███       | 785/2529 [00:21<00:40, 43.12it/s]
Processing: 0.95 quantile, negative r2g:  31%|███       | 790/2529 [00:21<00:47, 36.75it/s]
Processing: 0.95 quantile, negative r2g:  31%|███▏      | 794/2529 [00:22<00:50, 34.62it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 798/2529 [00:22<00:59, 29.06it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 804/2529 [00:22<00:59, 29.21it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 808/2529 [00:22<01:02, 27.64it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 813/2529 [00:22<00:53, 32.01it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 817/2529 [00:22<00:51, 33.23it/s]
Processing: 0.95 quantile, negative r2g:  32%|███▏      | 821/2529 [00:22<00:49, 34.43it/s]
Processing: 0.95 quantile, negative r2g:  33%|███▎      | 826/2529 [00:23<00:44, 38.09it/s]
Processing: 0.95 quantile, negative r2g:  33%|███▎      | 831/2529 [00:23<00:51, 33.00it/s]
Processing: 0.95 quantile, negative r2g:  33%|███▎      | 836/2529 [00:23<00:48, 34.71it/s]
Processing: 0.95 quantile, negative r2g:  33%|███▎      | 842/2529 [00:23<00:41, 40.34it/s]
Processing: 0.95 quantile, negative r2g:  33%|███▎      | 847/2529 [00:23<00:39, 42.76it/s]
Processing: 0.95 quantile, negative r2g:  34%|███▎      | 852/2529 [00:23<00:38, 43.16it/s]
Processing: 0.95 quantile, negative r2g:  34%|███▍      | 860/2529 [00:23<00:32, 51.61it/s]
Processing: 0.95 quantile, negative r2g:  34%|███▍      | 867/2529 [00:23<00:30, 55.25it/s]
Processing: 0.95 quantile, negative r2g:  35%|███▍      | 873/2529 [00:24<00:29, 56.48it/s]
Processing: 0.95 quantile, negative r2g:  35%|███▍      | 879/2529 [00:24<00:32, 50.90it/s]
Processing: 0.95 quantile, negative r2g:  35%|███▍      | 885/2529 [00:24<00:33, 49.23it/s]
Processing: 0.95 quantile, negative r2g:  35%|███▌      | 892/2529 [00:24<00:31, 51.55it/s]
Processing: 0.95 quantile, negative r2g:  36%|███▌      | 900/2529 [00:24<00:30, 52.99it/s]
Processing: 0.95 quantile, negative r2g:  36%|███▌      | 906/2529 [00:24<00:33, 48.19it/s]
Processing: 0.95 quantile, negative r2g:  36%|███▌      | 912/2529 [00:24<00:33, 47.85it/s]
Processing: 0.95 quantile, negative r2g:  36%|███▋      | 918/2529 [00:24<00:32, 49.02it/s]
Processing: 0.95 quantile, negative r2g:  37%|███▋      | 926/2529 [00:25<00:28, 56.59it/s]
Processing: 0.95 quantile, negative r2g:  37%|███▋      | 933/2529 [00:25<00:29, 53.24it/s]
Processing: 0.95 quantile, negative r2g:  37%|███▋      | 939/2529 [00:25<00:32, 49.07it/s]
Processing: 0.95 quantile, negative r2g:  37%|███▋      | 945/2529 [00:25<00:36, 43.17it/s]
Processing: 0.95 quantile, negative r2g:  38%|███▊      | 952/2529 [00:25<00:32, 48.03it/s]
Processing: 0.95 quantile, negative r2g:  38%|███▊      | 958/2529 [00:25<00:35, 44.47it/s]
Processing: 0.95 quantile, negative r2g:  38%|███▊      | 966/2529 [00:25<00:32, 48.78it/s]
Processing: 0.95 quantile, negative r2g:  38%|███▊      | 973/2529 [00:26<00:30, 51.56it/s]
Processing: 0.95 quantile, negative r2g:  39%|███▊      | 979/2529 [00:26<00:32, 48.16it/s]
Processing: 0.95 quantile, negative r2g:  39%|███▉      | 984/2529 [00:26<00:32, 48.24it/s]
Processing: 0.95 quantile, negative r2g:  39%|███▉      | 990/2529 [00:26<00:30, 50.84it/s]
Processing: 0.95 quantile, negative r2g:  39%|███▉      | 996/2529 [00:26<00:29, 52.62it/s]
Processing: 0.95 quantile, negative r2g:  40%|███▉      | 1003/2529 [00:26<00:27, 56.16it/s]
Processing: 0.95 quantile, negative r2g:  40%|███▉      | 1009/2529 [00:26<00:30, 50.14it/s]
Processing: 0.95 quantile, negative r2g:  40%|████      | 1015/2529 [00:26<00:35, 42.96it/s]
Processing: 0.95 quantile, negative r2g:  40%|████      | 1021/2529 [00:27<00:32, 46.31it/s]
Processing: 0.95 quantile, negative r2g:  41%|████      | 1026/2529 [00:27<00:32, 46.92it/s]

Processing: 0.95 quantile, negative r2g:  41%|████      | 1033/2529 [00:27<00:29, 49.95it/s]
Processing: 0.95 quantile, negative r2g:  41%|████      | 1039/2529 [00:27<00:29, 51.36it/s]
Processing: 0.95 quantile, negative r2g:  41%|████▏     | 1045/2529 [00:27<00:28, 51.20it/s]
Processing: 0.95 quantile, negative r2g:  42%|████▏     | 1051/2529 [00:27<00:31, 47.65it/s]
Processing: 0.95 quantile, negative r2g:  42%|████▏     | 1056/2529 [00:27<00:31, 47.02it/s]
Processing: 0.95 quantile, negative r2g:  42%|████▏     | 1063/2529 [00:27<00:27, 52.46it/s]
Processing: 0.95 quantile, negative r2g:  42%|████▏     | 1069/2529 [00:28<00:30, 48.42it/s]
Processing: 0.95 quantile, negative r2g:  42%|████▏     | 1074/2529 [00:28<00:30, 47.74it/s]
Processing: 0.95 quantile, negative r2g:  43%|████▎     | 1080/2529 [00:28<00:30, 47.60it/s]
Processing: 0.95 quantile, negative r2g:  43%|████▎     | 1089/2529 [00:28<00:27, 52.31it/s]
Processing: 0.95 quantile, negative r2g:  43%|████▎     | 1096/2529 [00:28<00:25, 55.23it/s]
Processing: 0.95 quantile, negative r2g:  44%|████▎     | 1103/2529 [00:28<00:26, 53.61it/s]
Processing: 0.95 quantile, negative r2g:  44%|████▍     | 1110/2529 [00:28<00:25, 55.91it/s]
Processing: 0.95 quantile, negative r2g:  44%|████▍     | 1116/2529 [00:28<00:25, 55.87it/s]
Processing: 0.95 quantile, negative r2g:  44%|████▍     | 1123/2529 [00:29<00:23, 59.34it/s]
Processing: 0.95 quantile, negative r2g:  45%|████▍     | 1129/2529 [00:29<00:27, 51.52it/s]
Processing: 0.95 quantile, negative r2g:  45%|████▍     | 1135/2529 [00:29<00:27, 51.33it/s]
Processing: 0.95 quantile, negative r2g:  45%|████▌     | 1143/2529 [00:29<00:24, 56.54it/s]
Processing: 0.95 quantile, negative r2g:  45%|████▌     | 1150/2529 [00:29<00:24, 55.51it/s]
Processing: 0.95 quantile, negative r2g:  46%|████▌     | 1156/2529 [00:29<00:25, 54.57it/s]
Processing: 0.95 quantile, negative r2g:  46%|████▌     | 1162/2529 [00:29<00:24, 55.93it/s]
Processing: 0.95 quantile, negative r2g:  46%|████▌     | 1168/2529 [00:29<00:24, 55.36it/s]
Processing: 0.95 quantile, negative r2g:  46%|████▋     | 1174/2529 [00:29<00:24, 56.37it/s]
Processing: 0.95 quantile, negative r2g:  47%|████▋     | 1182/2529 [00:30<00:22, 60.42it/s]
Processing: 0.95 quantile, negative r2g:  47%|████▋     | 1190/2529 [00:30<00:22, 59.81it/s]
Processing: 0.95 quantile, negative r2g:  47%|████▋     | 1196/2529 [00:30<00:25, 52.64it/s]
Processing: 0.95 quantile, negative r2g:  48%|████▊     | 1202/2529 [00:30<00:27, 48.06it/s]
Processing: 0.95 quantile, negative r2g:  48%|████▊     | 1208/2529 [00:30<00:26, 50.45it/s]
Processing: 0.95 quantile, negative r2g:  48%|████▊     | 1214/2529 [00:30<00:25, 50.68it/s]
Processing: 0.95 quantile, negative r2g:  48%|████▊     | 1220/2529 [00:30<00:25, 50.56it/s]
Processing: 0.95 quantile, negative r2g:  48%|████▊     | 1226/2529 [00:30<00:25, 50.60it/s]
Processing: 0.95 quantile, negative r2g:  49%|████▊     | 1232/2529 [00:31<00:27, 46.83it/s]
Processing: 0.95 quantile, negative r2g:  49%|████▉     | 1239/2529 [00:31<00:25, 49.96it/s]
Processing: 0.95 quantile, negative r2g:  49%|████▉     | 1245/2529 [00:31<00:36, 35.19it/s]
Processing: 0.95 quantile, negative r2g:  49%|████▉     | 1250/2529 [00:31<00:36, 35.34it/s]
Processing: 0.95 quantile, negative r2g:  50%|████▉     | 1255/2529 [00:31<00:36, 35.31it/s]
Processing: 0.95 quantile, negative r2g:  50%|████▉     | 1259/2529 [00:31<00:39, 32.27it/s]
Processing: 0.95 quantile, negative r2g:  50%|████▉     | 1264/2529 [00:32<00:35, 35.34it/s]
Processing: 0.95 quantile, negative r2g:  50%|█████     | 1268/2529 [00:32<00:36, 34.95it/s]
Processing: 0.95 quantile, negative r2g:  50%|█████     | 1274/2529 [00:32<00:34, 36.67it/s]
Processing: 0.95 quantile, negative r2g:  51%|█████     | 1278/2529 [00:32<00:38, 32.67it/s]
Processing: 0.95 quantile, negative r2g:  51%|█████     | 1283/2529 [00:32<00:34, 36.43it/s]
Processing: 0.95 quantile, negative r2g:  51%|█████     | 1291/2529 [00:32<00:26, 46.86it/s]
Processing: 0.95 quantile, negative r2g:  51%|█████▏    | 1298/2529 [00:32<00:23, 52.38it/s]
Processing: 0.95 quantile, negative r2g:  52%|█████▏    | 1304/2529 [00:33<00:27, 43.98it/s]
Processing: 0.95 quantile, negative r2g:  52%|█████▏    | 1309/2529 [00:33<00:29, 41.93it/s]
Processing: 0.95 quantile, negative r2g:  52%|█████▏    | 1316/2529 [00:33<00:25, 47.57it/s]
Processing: 0.95 quantile, negative r2g:  52%|█████▏    | 1322/2529 [00:33<00:27, 43.28it/s]
Processing: 0.95 quantile, negative r2g:  53%|█████▎    | 1328/2529 [00:33<00:26, 44.76it/s]
Processing: 0.95 quantile, negative r2g:  53%|█████▎    | 1333/2529 [00:33<00:30, 39.18it/s]
Processing: 0.95 quantile, negative r2g:  53%|█████▎    | 1338/2529 [00:33<00:29, 40.69it/s]
Processing: 0.95 quantile, negative r2g:  53%|█████▎    | 1344/2529 [00:33<00:26, 45.23it/s]
Processing: 0.95 quantile, negative r2g:  53%|█████▎    | 1349/2529 [00:34<00:33, 35.14it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▎    | 1354/2529 [00:34<00:41, 28.06it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▎    | 1358/2529 [00:34<00:41, 28.40it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1362/2529 [00:34<00:44, 26.46it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1365/2529 [00:34<00:46, 25.26it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1368/2529 [00:35<00:51, 22.72it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1371/2529 [00:35<00:54, 21.16it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1374/2529 [00:35<00:52, 21.85it/s]
Processing: 0.95 quantile, negative r2g:  54%|█████▍    | 1377/2529 [00:35<00:49, 23.51it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▍    | 1380/2529 [00:35<00:47, 24.09it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▍    | 1383/2529 [00:35<00:47, 24.17it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▍    | 1389/2529 [00:35<00:40, 27.99it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▌    | 1392/2529 [00:36<00:45, 24.73it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▌    | 1395/2529 [00:36<00:50, 22.63it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▌    | 1398/2529 [00:36<00:49, 22.71it/s]
Processing: 0.95 quantile, negative r2g:  55%|█████▌    | 1402/2529 [00:36<00:45, 24.91it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▌    | 1406/2529 [00:36<00:42, 26.52it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▌    | 1409/2529 [00:36<00:45, 24.63it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▌    | 1412/2529 [00:36<00:44, 25.08it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▌    | 1416/2529 [00:36<00:39, 28.33it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▌    | 1421/2529 [00:37<00:33, 33.49it/s]
Processing: 0.95 quantile, negative r2g:  56%|█████▋    | 1425/2529 [00:37<00:32, 33.63it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1429/2529 [00:37<00:31, 35.11it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1434/2529 [00:37<00:29, 37.72it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1439/2529 [00:37<00:29, 36.77it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1443/2529 [00:37<00:30, 35.83it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1449/2529 [00:37<00:26, 40.42it/s]
Processing: 0.95 quantile, negative r2g:  57%|█████▋    | 1454/2529 [00:37<00:29, 36.09it/s]
Processing: 0.95 quantile, negative r2g:  58%|█████▊    | 1460/2529 [00:38<00:25, 41.37it/s]
Processing: 0.95 quantile, negative r2g:  58%|█████▊    | 1465/2529 [00:38<00:25, 41.57it/s]
Processing: 0.95 quantile, negative r2g:  58%|█████▊    | 1471/2529 [00:38<00:23, 45.27it/s]
Processing: 0.95 quantile, negative r2g:  58%|█████▊    | 1478/2529 [00:38<00:20, 50.24it/s]
Processing: 0.95 quantile, negative r2g:  59%|█████▊    | 1484/2529 [00:38<00:21, 49.72it/s]
Processing: 0.95 quantile, negative r2g:  59%|█████▉    | 1490/2529 [00:38<00:24, 43.14it/s]
Processing: 0.95 quantile, negative r2g:  59%|█████▉    | 1497/2529 [00:38<00:21, 48.91it/s]
Processing: 0.95 quantile, negative r2g:  59%|█████▉    | 1503/2529 [00:38<00:20, 49.83it/s]
Processing: 0.95 quantile, negative r2g:  60%|█████▉    | 1509/2529 [00:39<00:23, 42.60it/s]
Processing: 0.95 quantile, negative r2g:  60%|█████▉    | 1515/2529 [00:39<00:23, 43.47it/s]
Processing: 0.95 quantile, negative r2g:  60%|██████    | 1521/2529 [00:39<00:21, 46.75it/s]
Processing: 0.95 quantile, negative r2g:  60%|██████    | 1526/2529 [00:39<00:21, 45.69it/s]
Processing: 0.95 quantile, negative r2g:  61%|██████    | 1532/2529 [00:39<00:21, 46.45it/s]
Processing: 0.95 quantile, negative r2g:  61%|██████    | 1537/2529 [00:39<00:22, 44.88it/s]
Processing: 0.95 quantile, negative r2g:  61%|██████    | 1542/2529 [00:39<00:23, 41.36it/s]
Processing: 0.95 quantile, negative r2g:  61%|██████    | 1547/2529 [00:39<00:22, 43.28it/s]
Processing: 0.95 quantile, negative r2g:  61%|██████▏   | 1554/2529 [00:40<00:19, 49.21it/s]
Processing: 0.95 quantile, negative r2g:  62%|██████▏   | 1561/2529 [00:40<00:18, 52.82it/s]
Processing: 0.95 quantile, negative r2g:  62%|██████▏   | 1567/2529 [00:40<00:18, 50.71it/s]
Processing: 0.95 quantile, negative r2g:  62%|██████▏   | 1573/2529 [00:40<00:19, 49.70it/s]
Processing: 0.95 quantile, negative r2g:  62%|██████▏   | 1580/2529 [00:40<00:19, 48.66it/s]
Processing: 0.95 quantile, negative r2g:  63%|██████▎   | 1585/2529 [00:40<00:22, 42.23it/s]
Processing: 0.95 quantile, negative r2g:  63%|██████▎   | 1590/2529 [00:40<00:22, 42.14it/s]
Processing: 0.95 quantile, negative r2g:  63%|██████▎   | 1595/2529 [00:41<00:25, 37.16it/s]
Processing: 0.95 quantile, negative r2g:  63%|██████▎   | 1601/2529 [00:41<00:23, 39.69it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▎   | 1606/2529 [00:41<00:27, 33.17it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▎   | 1610/2529 [00:41<00:32, 28.48it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1614/2529 [00:41<00:38, 23.48it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1617/2529 [00:42<00:42, 21.67it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1620/2529 [00:42<00:44, 20.27it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1623/2529 [00:42<00:46, 19.28it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1626/2529 [00:42<00:45, 19.64it/s]
Processing: 0.95 quantile, negative r2g:  64%|██████▍   | 1631/2529 [00:42<00:35, 25.54it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▍   | 1635/2529 [00:42<00:33, 26.89it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▍   | 1639/2529 [00:42<00:30, 29.18it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▌   | 1644/2529 [00:42<00:27, 32.01it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▌   | 1648/2529 [00:43<00:32, 27.23it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▌   | 1651/2529 [00:43<00:34, 25.31it/s]
Processing: 0.95 quantile, negative r2g:  65%|██████▌   | 1655/2529 [00:43<00:36, 23.97it/s]
Processing: 0.95 quantile, negative r2g:  66%|██████▌   | 1661/2529 [00:43<00:29, 29.01it/s]
Processing: 0.95 quantile, negative r2g:  66%|██████▌   | 1665/2529 [00:43<00:30, 27.97it/s]
Processing: 0.95 quantile, negative r2g:  66%|██████▌   | 1670/2529 [00:43<00:27, 31.09it/s]
Processing: 0.95 quantile, negative r2g:  66%|██████▌   | 1675/2529 [00:44<00:24, 34.38it/s]
Processing: 0.95 quantile, negative r2g:  66%|██████▋   | 1681/2529 [00:44<00:23, 36.26it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1685/2529 [00:44<00:24, 34.04it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1689/2529 [00:44<00:23, 35.32it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1693/2529 [00:44<00:23, 34.99it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1698/2529 [00:44<00:23, 35.90it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1702/2529 [00:44<00:28, 28.79it/s]
Processing: 0.95 quantile, negative r2g:  67%|██████▋   | 1706/2529 [00:45<00:30, 27.12it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1709/2529 [00:45<00:29, 27.54it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1712/2529 [00:45<00:32, 25.01it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1715/2529 [00:45<00:34, 23.80it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1718/2529 [00:45<00:35, 22.94it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1723/2529 [00:45<00:27, 28.94it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1727/2529 [00:45<00:30, 26.04it/s]
Processing: 0.95 quantile, negative r2g:  68%|██████▊   | 1730/2529 [00:46<00:34, 22.91it/s]
Processing: 0.95 quantile, negative r2g:  69%|██████▊   | 1735/2529 [00:46<00:27, 28.62it/s]
Processing: 0.95 quantile, negative r2g:  69%|██████▉   | 1739/2529 [00:46<00:26, 30.37it/s]
Processing: 0.95 quantile, negative r2g:  69%|██████▉   | 1743/2529 [00:46<00:27, 28.55it/s]
Processing: 0.95 quantile, negative r2g:  69%|██████▉   | 1748/2529 [00:46<00:23, 33.41it/s]
Processing: 0.95 quantile, negative r2g:  69%|██████▉   | 1753/2529 [00:46<00:21, 35.74it/s]
Processing: 0.95 quantile, negative r2g:  70%|██████▉   | 1758/2529 [00:46<00:19, 39.07it/s]
Processing: 0.95 quantile, negative r2g:  70%|██████▉   | 1766/2529 [00:46<00:15, 49.87it/s]
Processing: 0.95 quantile, negative r2g:  70%|███████   | 1772/2529 [00:47<00:16, 46.58it/s]
Processing: 0.95 quantile, negative r2g:  70%|███████   | 1777/2529 [00:47<00:18, 40.36it/s]
Processing: 0.95 quantile, negative r2g:  71%|███████   | 1785/2529 [00:47<00:16, 46.43it/s]
Processing: 0.95 quantile, negative r2g:  71%|███████   | 1790/2529 [00:47<00:19, 37.26it/s]
Processing: 0.95 quantile, negative r2g:  71%|███████   | 1798/2529 [00:47<00:15, 46.31it/s]
Processing: 0.95 quantile, negative r2g:  71%|███████▏  | 1804/2529 [00:47<00:16, 42.70it/s]
Processing: 0.95 quantile, negative r2g:  72%|███████▏  | 1809/2529 [00:47<00:18, 38.80it/s]
Processing: 0.95 quantile, negative r2g:  72%|███████▏  | 1816/2529 [00:48<00:16, 44.31it/s]

Processing: 0.95 quantile, negative r2g:  72%|███████▏  | 1822/2529 [00:48<00:15, 46.87it/s]
Processing: 0.95 quantile, negative r2g:  72%|███████▏  | 1828/2529 [00:48<00:15, 45.97it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1834/2529 [00:48<00:15, 44.49it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1839/2529 [00:48<00:17, 39.03it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1844/2529 [00:48<00:20, 33.88it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1848/2529 [00:48<00:20, 32.88it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1852/2529 [00:49<00:20, 33.34it/s]
Processing: 0.95 quantile, negative r2g:  73%|███████▎  | 1857/2529 [00:49<00:18, 36.88it/s]
Processing: 0.95 quantile, negative r2g:  74%|███████▎  | 1863/2529 [00:49<00:16, 39.67it/s]
Processing: 0.95 quantile, negative r2g:  74%|███████▍  | 1868/2529 [00:49<00:16, 41.11it/s]
Processing: 0.95 quantile, negative r2g:  74%|███████▍  | 1873/2529 [00:49<00:17, 36.96it/s]
Processing: 0.95 quantile, negative r2g:  74%|███████▍  | 1877/2529 [00:49<00:22, 29.34it/s]
Processing: 0.95 quantile, negative r2g:  74%|███████▍  | 1881/2529 [00:49<00:21, 30.34it/s]
Processing: 0.95 quantile, negative r2g:  75%|███████▍  | 1886/2529 [00:50<00:19, 33.24it/s]
Processing: 0.95 quantile, negative r2g:  75%|███████▍  | 1891/2529 [00:50<00:17, 36.73it/s]
Processing: 0.95 quantile, negative r2g:  75%|███████▍  | 1895/2529 [00:50<00:18, 35.19it/s]
Processing: 0.95 quantile, negative r2g:  75%|███████▌  | 1900/2529 [00:50<00:17, 36.98it/s]
Processing: 0.95 quantile, negative r2g:  75%|███████▌  | 1907/2529 [00:50<00:13, 45.03it/s]
Processing: 0.95 quantile, negative r2g:  76%|███████▌  | 1912/2529 [00:50<00:16, 37.05it/s]
Processing: 0.95 quantile, negative r2g:  76%|███████▌  | 1918/2529 [00:50<00:14, 41.30it/s]
Processing: 0.95 quantile, negative r2g:  76%|███████▌  | 1924/2529 [00:50<00:14, 43.13it/s]
Processing: 0.95 quantile, negative r2g:  76%|███████▋  | 1929/2529 [00:51<00:14, 42.57it/s]
Processing: 0.95 quantile, negative r2g:  77%|███████▋  | 1935/2529 [00:51<00:13, 43.42it/s]
Processing: 0.95 quantile, negative r2g:  77%|███████▋  | 1940/2529 [00:51<00:15, 38.14it/s]
Processing: 0.95 quantile, negative r2g:  77%|███████▋  | 1945/2529 [00:51<00:14, 39.86it/s]
Processing: 0.95 quantile, negative r2g:  77%|███████▋  | 1950/2529 [00:51<00:13, 41.79it/s]
Processing: 0.95 quantile, negative r2g:  77%|███████▋  | 1955/2529 [00:51<00:15, 38.00it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1960/2529 [00:51<00:14, 38.99it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1965/2529 [00:52<00:15, 37.37it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1969/2529 [00:52<00:17, 31.79it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1973/2529 [00:52<00:25, 22.24it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1976/2529 [00:52<00:25, 21.63it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1979/2529 [00:52<00:26, 21.15it/s]
Processing: 0.95 quantile, negative r2g:  78%|███████▊  | 1982/2529 [00:52<00:24, 22.19it/s]
Processing: 0.95 quantile, negative r2g:  79%|███████▊  | 1986/2529 [00:53<00:23, 23.55it/s]
Processing: 0.95 quantile, negative r2g:  79%|███████▊  | 1988/2529 [01:16<20:00,  2.22s/it]
Processing: 0.95 quantile, negative r2g:  79%|███████▊  | 1988/2529 [01:16<20:00,  2.22s/it]
Processing: 0.95 quantile, negative r2g:  79%|███████▉  | 1993/2529 [01:16<11:54,  1.33s/it]
Processing: 0.95 quantile, negative r2g:  79%|███████▉  | 1997/2529 [01:16<08:11,  1.08it/s]
Processing: 0.95 quantile, negative r2g:  79%|███████▉  | 2000/2529 [01:16<06:12,  1.42it/s]
Processing: 0.95 quantile, negative r2g:  79%|███████▉  | 2005/2529 [01:16<03:54,  2.23it/s]
Processing: 0.95 quantile, negative r2g:  80%|███████▉  | 2011/2529 [01:16<02:24,  3.58it/s]
Processing: 0.95 quantile, negative r2g:  80%|███████▉  | 2017/2529 [01:17<01:37,  5.25it/s]
Processing: 0.95 quantile, negative r2g:  80%|███████▉  | 2021/2529 [01:17<01:19,  6.40it/s]
Processing: 0.95 quantile, negative r2g:  80%|████████  | 2027/2529 [01:17<00:53,  9.34it/s]
Processing: 0.95 quantile, negative r2g:  80%|████████  | 2031/2529 [01:17<00:43, 11.44it/s]
Processing: 0.95 quantile, negative r2g:  80%|████████  | 2035/2529 [01:17<00:35, 13.77it/s]
Processing: 0.95 quantile, negative r2g:  81%|████████  | 2039/2529 [01:17<00:31, 15.51it/s]
Processing: 0.95 quantile, negative r2g:  81%|████████  | 2044/2529 [01:17<00:24, 19.97it/s]
Processing: 0.95 quantile, negative r2g:  81%|████████  | 2050/2529 [01:17<00:18, 25.49it/s]
Processing: 0.95 quantile, negative r2g:  81%|████████▏ | 2056/2529 [01:18<00:15, 31.00it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2062/2529 [01:18<00:13, 34.66it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2067/2529 [01:18<00:13, 35.39it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2072/2529 [01:18<00:13, 34.49it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2076/2529 [01:18<00:13, 34.32it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2080/2529 [01:18<00:13, 32.89it/s]
Processing: 0.95 quantile, negative r2g:  82%|████████▏ | 2084/2529 [01:18<00:16, 27.81it/s]
Processing: 0.95 quantile, negative r2g:  83%|████████▎ | 2090/2529 [01:19<00:12, 34.09it/s]
Processing: 0.95 quantile, negative r2g:  83%|████████▎ | 2094/2529 [01:19<00:16, 26.59it/s]
Processing: 0.95 quantile, negative r2g:  83%|████████▎ | 2100/2529 [01:19<00:13, 32.19it/s]
Processing: 0.95 quantile, negative r2g:  83%|████████▎ | 2104/2529 [01:19<00:13, 31.61it/s]
Processing: 0.95 quantile, negative r2g:  83%|████████▎ | 2109/2529 [01:19<00:12, 33.55it/s]
Processing: 0.95 quantile, negative r2g:  84%|████████▎ | 2115/2529 [01:19<00:11, 35.89it/s]
Processing: 0.95 quantile, negative r2g:  84%|████████▍ | 2119/2529 [01:20<00:13, 30.39it/s]
Processing: 0.95 quantile, negative r2g:  84%|████████▍ | 2124/2529 [01:20<00:11, 33.77it/s]
Processing: 0.95 quantile, negative r2g:  84%|████████▍ | 2129/2529 [01:20<00:11, 36.36it/s]
Processing: 0.95 quantile, negative r2g:  84%|████████▍ | 2135/2529 [01:20<00:09, 41.26it/s]
Processing: 0.95 quantile, negative r2g:  85%|████████▍ | 2141/2529 [01:20<00:09, 42.63it/s]
Processing: 0.95 quantile, negative r2g:  85%|████████▍ | 2146/2529 [01:20<00:08, 43.21it/s]
Processing: 0.95 quantile, negative r2g:  85%|████████▌ | 2154/2529 [01:20<00:07, 51.72it/s]
Processing: 0.95 quantile, negative r2g:  85%|████████▌ | 2161/2529 [01:20<00:06, 55.22it/s]
Processing: 0.95 quantile, negative r2g:  86%|████████▌ | 2167/2529 [01:20<00:06, 52.81it/s]
Processing: 0.95 quantile, negative r2g:  86%|████████▌ | 2173/2529 [01:21<00:07, 50.78it/s]
Processing: 0.95 quantile, negative r2g:  86%|████████▌ | 2179/2529 [01:21<00:06, 50.02it/s]
Processing: 0.95 quantile, negative r2g:  86%|████████▋ | 2185/2529 [01:21<00:06, 51.35it/s]
Processing: 0.95 quantile, negative r2g:  87%|████████▋ | 2192/2529 [01:21<00:06, 56.16it/s]
Processing: 0.95 quantile, negative r2g:  87%|████████▋ | 2198/2529 [01:21<00:06, 49.75it/s]
Processing: 0.95 quantile, negative r2g:  87%|████████▋ | 2205/2529 [01:21<00:06, 50.07it/s]
Processing: 0.95 quantile, negative r2g:  87%|████████▋ | 2211/2529 [01:21<00:06, 50.17it/s]
Processing: 0.95 quantile, negative r2g:  88%|████████▊ | 2219/2529 [01:21<00:05, 57.56it/s]
Processing: 0.95 quantile, negative r2g:  88%|████████▊ | 2226/2529 [01:22<00:05, 54.27it/s]
Processing: 0.95 quantile, negative r2g:  88%|████████▊ | 2232/2529 [01:22<00:05, 52.78it/s]
Processing: 0.95 quantile, negative r2g:  88%|████████▊ | 2238/2529 [01:22<00:06, 44.62it/s]
Processing: 0.95 quantile, negative r2g:  89%|████████▊ | 2243/2529 [01:22<00:06, 42.66it/s]
Processing: 0.95 quantile, negative r2g:  89%|████████▉ | 2248/2529 [01:22<00:06, 42.76it/s]
Processing: 0.95 quantile, negative r2g:  89%|████████▉ | 2253/2529 [01:22<00:06, 44.17it/s]
Processing: 0.95 quantile, negative r2g:  89%|████████▉ | 2260/2529 [01:22<00:05, 47.86it/s]
Processing: 0.95 quantile, negative r2g:  90%|████████▉ | 2266/2529 [01:22<00:05, 50.12it/s]
Processing: 0.95 quantile, negative r2g:  90%|████████▉ | 2272/2529 [01:23<00:05, 50.62it/s]
Processing: 0.95 quantile, negative r2g:  90%|█████████ | 2278/2529 [01:23<00:05, 44.98it/s]
Processing: 0.95 quantile, negative r2g:  90%|█████████ | 2285/2529 [01:23<00:04, 49.58it/s]
Processing: 0.95 quantile, negative r2g:  91%|█████████ | 2291/2529 [01:23<00:04, 49.24it/s]
Processing: 0.95 quantile, negative r2g:  91%|█████████ | 2299/2529 [01:23<00:04, 55.76it/s]
Processing: 0.95 quantile, negative r2g:  91%|█████████ | 2305/2529 [01:23<00:04, 49.85it/s]
Processing: 0.95 quantile, negative r2g:  91%|█████████▏| 2311/2529 [01:23<00:04, 48.95it/s]
Processing: 0.95 quantile, negative r2g:  92%|█████████▏| 2317/2529 [01:24<00:04, 42.53it/s]
Processing: 0.95 quantile, negative r2g:  92%|█████████▏| 2325/2529 [01:24<00:04, 46.75it/s]
Processing: 0.95 quantile, negative r2g:  92%|█████████▏| 2331/2529 [01:24<00:03, 49.70it/s]
Processing: 0.95 quantile, negative r2g:  92%|█████████▏| 2338/2529 [01:24<00:03, 53.94it/s]
Processing: 0.95 quantile, negative r2g:  93%|█████████▎| 2344/2529 [01:24<00:03, 52.75it/s]
Processing: 0.95 quantile, negative r2g:  93%|█████████▎| 2350/2529 [01:24<00:03, 51.86it/s]
Processing: 0.95 quantile, negative r2g:  93%|█████████▎| 2356/2529 [01:24<00:03, 45.19it/s]
Processing: 0.95 quantile, negative r2g:  93%|█████████▎| 2363/2529 [01:24<00:03, 50.57it/s]
Processing: 0.95 quantile, negative r2g:  94%|█████████▎| 2369/2529 [01:25<00:03, 47.77it/s]
Processing: 0.95 quantile, negative r2g:  94%|█████████▍| 2374/2529 [01:25<00:03, 46.92it/s]
Processing: 0.95 quantile, negative r2g:  94%|█████████▍| 2379/2529 [01:25<00:03, 47.06it/s]
Processing: 0.95 quantile, negative r2g:  94%|█████████▍| 2387/2529 [01:25<00:02, 54.29it/s]
Processing: 0.95 quantile, negative r2g:  95%|█████████▍| 2393/2529 [01:25<00:02, 53.81it/s]
Processing: 0.95 quantile, negative r2g:  95%|█████████▍| 2400/2529 [01:25<00:02, 57.24it/s]
Processing: 0.95 quantile, negative r2g:  95%|█████████▌| 2406/2529 [01:25<00:02, 52.52it/s]
Processing: 0.95 quantile, negative r2g:  95%|█████████▌| 2413/2529 [01:25<00:02, 55.47it/s]
Processing: 0.95 quantile, negative r2g:  96%|█████████▌| 2420/2529 [01:25<00:01, 56.77it/s]
Processing: 0.95 quantile, negative r2g:  96%|█████████▌| 2427/2529 [01:26<00:01, 59.60it/s]
Processing: 0.95 quantile, negative r2g:  96%|█████████▌| 2434/2529 [01:26<00:01, 54.11it/s]
Processing: 0.95 quantile, negative r2g:  96%|█████████▋| 2440/2529 [01:26<00:01, 52.38it/s]
Processing: 0.95 quantile, negative r2g:  97%|█████████▋| 2447/2529 [01:26<00:01, 55.49it/s]
Processing: 0.95 quantile, negative r2g:  97%|█████████▋| 2454/2529 [01:26<00:01, 55.04it/s]
Processing: 0.95 quantile, negative r2g:  97%|█████████▋| 2460/2529 [01:26<00:01, 53.20it/s]
Processing: 0.95 quantile, negative r2g:  98%|█████████▊| 2466/2529 [01:26<00:01, 49.10it/s]
Processing: 0.95 quantile, negative r2g:  98%|█████████▊| 2474/2529 [01:26<00:00, 55.76it/s]
Processing: 0.95 quantile, negative r2g:  98%|█████████▊| 2480/2529 [01:27<00:00, 54.70it/s]
Processing: 0.95 quantile, negative r2g:  98%|█████████▊| 2489/2529 [01:27<00:00, 60.94it/s]
Processing: 0.95 quantile, negative r2g:  99%|█████████▊| 2496/2529 [01:27<00:00, 60.74it/s]
Processing: 0.95 quantile, negative r2g:  99%|█████████▉| 2503/2529 [01:27<00:00, 54.10it/s]
Processing: 0.95 quantile, negative r2g:  99%|█████████▉| 2509/2529 [01:27<00:00, 49.90it/s]
Processing: 0.95 quantile, negative r2g:  99%|█████████▉| 2515/2529 [01:27<00:00, 51.77it/s]
Processing: 0.95 quantile, negative r2g: 100%|█████████▉| 2522/2529 [01:27<00:00, 54.47it/s]
Processing: 0.95 quantile, negative r2g: 100%|█████████▉| 2528/2529 [01:27<00:00, 54.76it/s]
 21%|██▏       | 3/14 [06:43<22:46, 124.21s/it]
Processing: Top 5 region-to-gene links per gene, negative r2g:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   0%|          | 4/2529 [00:00<01:06, 38.00it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   0%|          | 8/2529 [00:00<01:05, 38.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   0%|          | 12/2529 [00:00<01:11, 35.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|          | 17/2529 [00:00<01:08, 36.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|          | 21/2529 [00:00<01:24, 29.76it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|          | 25/2529 [00:00<01:23, 29.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|          | 29/2529 [00:00<01:26, 28.95it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|▏         | 32/2529 [00:01<01:36, 25.91it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   1%|▏         | 37/2529 [00:01<01:25, 28.99it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 40/2529 [00:01<01:30, 27.49it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 45/2529 [00:01<01:20, 30.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 49/2529 [00:01<01:28, 27.89it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 52/2529 [00:01<01:28, 28.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 56/2529 [00:01<01:20, 30.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   2%|▏         | 62/2529 [00:01<01:05, 37.51it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   3%|▎         | 67/2529 [00:02<01:01, 39.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   3%|▎         | 72/2529 [00:02<01:11, 34.29it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   3%|▎         | 76/2529 [00:02<01:23, 29.36it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   3%|▎         | 80/2529 [00:02<01:17, 31.47it/s]

Processing: Top 5 region-to-gene links per gene, negative r2g:   3%|▎         | 85/2529 [00:02<01:16, 32.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▎         | 89/2529 [00:02<01:20, 30.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▎         | 94/2529 [00:02<01:11, 33.86it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▍         | 98/2529 [00:03<01:13, 32.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▍         | 102/2529 [00:03<01:25, 28.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▍         | 107/2529 [00:03<01:14, 32.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   4%|▍         | 111/2529 [00:03<01:13, 33.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▍         | 115/2529 [00:03<01:27, 27.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▍         | 119/2529 [00:04<01:51, 21.67it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▍         | 122/2529 [00:04<02:01, 19.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▍         | 125/2529 [00:04<01:55, 20.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 128/2529 [00:04<02:08, 18.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 131/2529 [00:04<02:10, 18.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 133/2529 [00:04<02:22, 16.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 135/2529 [00:04<02:24, 16.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 137/2529 [00:05<02:34, 15.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   5%|▌         | 139/2529 [00:05<02:36, 15.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▌         | 142/2529 [00:05<02:17, 17.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▌         | 145/2529 [00:05<02:14, 17.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▌         | 148/2529 [00:05<02:13, 17.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▌         | 153/2529 [00:05<01:36, 24.55it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▌         | 156/2529 [00:06<01:59, 19.86it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▋         | 159/2529 [00:06<02:09, 18.30it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▋         | 162/2529 [00:06<02:22, 16.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   6%|▋         | 164/2529 [00:06<02:20, 16.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 167/2529 [00:06<02:03, 19.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 170/2529 [00:06<01:58, 19.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 173/2529 [00:07<02:11, 17.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 175/2529 [00:07<02:12, 17.76it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 178/2529 [00:07<02:01, 19.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 181/2529 [00:07<01:48, 21.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 185/2529 [00:07<01:33, 25.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   7%|▋         | 189/2529 [00:07<01:24, 27.64it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 192/2529 [00:07<01:30, 25.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 196/2529 [00:07<01:23, 27.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 200/2529 [00:08<01:17, 29.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 204/2529 [00:08<01:25, 27.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 208/2529 [00:08<01:19, 29.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   8%|▊         | 212/2529 [00:08<01:13, 31.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▊         | 216/2529 [00:08<01:24, 27.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▊         | 221/2529 [00:08<01:11, 32.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▉         | 225/2529 [00:08<01:14, 31.00it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▉         | 230/2529 [00:08<01:06, 34.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▉         | 234/2529 [00:09<01:04, 35.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:   9%|▉         | 239/2529 [00:09<01:00, 37.95it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|▉         | 243/2529 [00:09<01:05, 34.71it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|▉         | 247/2529 [00:09<01:10, 32.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|▉         | 251/2529 [00:09<01:11, 31.75it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|█         | 256/2529 [00:09<01:02, 36.13it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|█         | 260/2529 [00:09<01:04, 35.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  10%|█         | 264/2529 [00:09<01:14, 30.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█         | 269/2529 [00:10<01:07, 33.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█         | 273/2529 [00:10<01:08, 32.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█         | 277/2529 [00:10<01:05, 34.57it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█         | 282/2529 [00:10<01:04, 34.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█▏        | 286/2529 [00:10<01:02, 36.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  11%|█▏        | 290/2529 [00:10<01:06, 33.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 294/2529 [00:10<01:06, 33.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 298/2529 [00:10<01:13, 30.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 302/2529 [00:11<01:10, 31.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 306/2529 [00:11<01:06, 33.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 311/2529 [00:11<01:00, 36.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  12%|█▏        | 316/2529 [00:11<00:56, 39.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  13%|█▎        | 321/2529 [00:11<00:55, 39.89it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  13%|█▎        | 326/2529 [00:11<01:02, 35.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  13%|█▎        | 331/2529 [00:11<01:04, 34.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  13%|█▎        | 335/2529 [00:12<01:13, 29.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  13%|█▎        | 339/2529 [00:12<01:10, 31.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▎        | 343/2529 [00:12<01:18, 27.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▎        | 347/2529 [00:12<01:17, 28.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▍        | 352/2529 [00:12<01:09, 31.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▍        | 356/2529 [00:12<01:21, 26.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▍        | 359/2529 [00:13<01:36, 22.60it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▍        | 362/2529 [00:13<01:52, 19.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  14%|█▍        | 365/2529 [00:13<02:07, 16.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▍        | 367/2529 [00:13<02:23, 15.10it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▍        | 369/2529 [00:13<02:23, 15.05it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▍        | 371/2529 [00:13<02:32, 14.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▍        | 373/2529 [00:14<02:31, 14.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▍        | 375/2529 [00:14<02:36, 13.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▌        | 380/2529 [00:14<01:45, 20.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▌        | 383/2529 [00:14<01:39, 21.52it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▌        | 387/2529 [00:14<01:26, 24.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  15%|█▌        | 391/2529 [00:14<01:19, 26.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 394/2529 [00:14<01:22, 25.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 397/2529 [00:15<01:45, 20.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 400/2529 [00:15<01:50, 19.29it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 403/2529 [00:15<01:57, 18.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 407/2529 [00:15<01:36, 21.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▌        | 410/2529 [00:15<01:35, 22.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  16%|█▋        | 413/2529 [00:15<01:41, 20.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 418/2529 [00:16<01:21, 25.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 421/2529 [00:16<01:19, 26.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 425/2529 [00:16<01:11, 29.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 429/2529 [00:16<01:14, 28.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 432/2529 [00:16<01:19, 26.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 435/2529 [00:16<01:19, 26.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 438/2529 [00:16<01:17, 26.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  17%|█▋        | 441/2529 [00:16<01:15, 27.50it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 444/2529 [00:16<01:17, 26.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 447/2529 [00:17<01:31, 22.86it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 450/2529 [00:17<01:39, 20.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 453/2529 [00:17<01:46, 19.57it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 456/2529 [00:17<01:41, 20.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 459/2529 [00:17<01:46, 19.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 463/2529 [00:17<01:30, 22.80it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  18%|█▊        | 466/2529 [00:18<01:28, 23.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▊        | 469/2529 [00:18<01:33, 21.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▊        | 472/2529 [00:18<01:52, 18.32it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▉        | 475/2529 [00:18<01:39, 20.64it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▉        | 478/2529 [00:18<01:32, 22.21it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▉        | 481/2529 [00:18<01:32, 22.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▉        | 484/2529 [00:18<01:27, 23.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  19%|█▉        | 490/2529 [00:19<01:04, 31.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|█▉        | 494/2529 [00:19<01:03, 31.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|█▉        | 499/2529 [00:19<00:57, 35.56it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|█▉        | 503/2529 [00:19<00:55, 36.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|██        | 507/2529 [00:19<00:59, 34.14it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|██        | 511/2529 [00:19<01:02, 32.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  20%|██        | 515/2529 [00:19<01:05, 30.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  21%|██        | 521/2529 [00:19<00:59, 34.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  21%|██        | 525/2529 [00:20<01:10, 28.36it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  21%|██        | 530/2529 [00:20<01:00, 32.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  21%|██        | 536/2529 [00:20<00:56, 35.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  21%|██▏       | 540/2529 [00:20<01:02, 31.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 544/2529 [00:20<01:11, 27.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 549/2529 [00:20<01:01, 32.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 554/2529 [00:20<00:59, 33.33it/s]

Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 558/2529 [00:21<00:57, 34.23it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 562/2529 [00:21<00:59, 32.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  22%|██▏       | 567/2529 [00:21<00:59, 33.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 571/2529 [00:21<01:00, 32.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 575/2529 [00:21<01:08, 28.71it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 578/2529 [00:21<01:18, 24.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 582/2529 [00:21<01:11, 27.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 585/2529 [00:22<01:11, 27.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 590/2529 [00:22<01:02, 31.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  23%|██▎       | 594/2529 [00:22<01:03, 30.62it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▎       | 598/2529 [00:22<01:03, 30.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▍       | 602/2529 [00:22<01:03, 30.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▍       | 606/2529 [00:22<01:25, 22.56it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▍       | 609/2529 [00:23<01:32, 20.80it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▍       | 612/2529 [00:23<01:26, 22.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  24%|██▍       | 616/2529 [00:23<01:15, 25.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▍       | 620/2529 [00:23<01:10, 27.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▍       | 623/2529 [00:23<01:11, 26.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▍       | 626/2529 [00:23<01:10, 26.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▍       | 631/2529 [00:23<00:59, 32.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▌       | 636/2529 [00:23<00:53, 35.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▌       | 640/2529 [00:24<01:09, 27.08it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  25%|██▌       | 644/2529 [00:24<01:04, 29.36it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▌       | 649/2529 [00:24<00:57, 32.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▌       | 653/2529 [00:24<00:59, 31.55it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▌       | 657/2529 [00:24<00:59, 31.32it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▌       | 661/2529 [00:24<01:07, 27.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▋       | 665/2529 [00:24<01:02, 29.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  26%|██▋       | 670/2529 [00:24<00:56, 33.06it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 674/2529 [00:25<00:57, 32.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 678/2529 [00:25<01:00, 30.51it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 682/2529 [00:25<01:01, 29.95it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 686/2529 [00:25<01:03, 29.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 689/2529 [00:25<01:05, 28.08it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 692/2529 [00:26<01:40, 18.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  27%|██▋       | 695/2529 [00:26<01:53, 16.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 697/2529 [00:26<01:53, 16.14it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 699/2529 [00:26<01:49, 16.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 701/2529 [00:26<01:54, 15.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 704/2529 [00:26<01:44, 17.51it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 707/2529 [00:26<01:34, 19.33it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 710/2529 [00:27<01:26, 20.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 713/2529 [00:27<01:21, 22.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 716/2529 [00:27<01:41, 17.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  28%|██▊       | 719/2529 [00:27<01:33, 19.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▊       | 723/2529 [00:27<01:18, 22.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▉       | 728/2529 [00:27<01:03, 28.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▉       | 734/2529 [00:27<01:04, 27.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▉       | 737/2529 [00:28<01:15, 23.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▉       | 740/2529 [00:28<01:14, 23.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  29%|██▉       | 744/2529 [00:28<01:05, 27.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|██▉       | 747/2529 [00:28<01:08, 25.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|██▉       | 750/2529 [00:28<01:13, 24.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|██▉       | 753/2529 [00:28<01:18, 22.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|██▉       | 756/2529 [00:28<01:18, 22.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|███       | 760/2529 [00:29<01:06, 26.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|███       | 765/2529 [00:29<00:56, 31.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  30%|███       | 769/2529 [00:29<00:58, 30.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███       | 774/2529 [00:29<00:50, 34.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███       | 778/2529 [00:29<00:53, 32.54it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███       | 782/2529 [00:29<00:55, 31.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███       | 786/2529 [00:29<00:55, 31.51it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███       | 790/2529 [00:30<01:06, 26.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███▏      | 793/2529 [00:30<01:12, 24.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  31%|███▏      | 796/2529 [00:30<01:17, 22.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 799/2529 [00:30<01:18, 22.06it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 803/2529 [00:30<01:08, 25.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 806/2529 [00:30<01:24, 20.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 809/2529 [00:30<01:27, 19.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 813/2529 [00:31<01:14, 23.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 816/2529 [00:31<01:12, 23.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  32%|███▏      | 819/2529 [00:31<01:10, 24.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 824/2529 [00:31<00:58, 29.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 828/2529 [00:31<01:15, 22.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 832/2529 [00:31<01:05, 25.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 836/2529 [00:31<01:05, 26.03it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 840/2529 [00:32<00:58, 28.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  33%|███▎      | 845/2529 [00:32<00:53, 31.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  34%|███▎      | 849/2529 [00:32<00:52, 31.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  34%|███▎      | 853/2529 [00:32<00:51, 32.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  34%|███▍      | 859/2529 [00:32<00:44, 37.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  34%|███▍      | 863/2529 [00:32<00:45, 36.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  34%|███▍      | 868/2529 [00:32<00:41, 40.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▍      | 873/2529 [00:32<00:40, 41.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▍      | 878/2529 [00:33<00:43, 38.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▍      | 882/2529 [00:33<00:50, 32.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▌      | 887/2529 [00:33<00:46, 35.52it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▌      | 892/2529 [00:33<00:44, 36.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  35%|███▌      | 897/2529 [00:33<00:41, 39.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  36%|███▌      | 902/2529 [00:33<00:50, 32.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  36%|███▌      | 907/2529 [00:33<00:46, 34.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  36%|███▌      | 911/2529 [00:34<00:45, 35.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  36%|███▌      | 915/2529 [00:34<00:46, 34.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  36%|███▋      | 919/2529 [00:34<00:48, 33.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  37%|███▋      | 925/2529 [00:34<00:40, 39.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  37%|███▋      | 931/2529 [00:34<00:37, 42.50it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  37%|███▋      | 936/2529 [00:34<00:46, 33.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  37%|███▋      | 940/2529 [00:34<00:47, 33.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  37%|███▋      | 944/2529 [00:35<00:55, 28.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 949/2529 [00:35<00:49, 31.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 953/2529 [00:35<00:50, 31.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 957/2529 [00:35<00:50, 31.35it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 963/2529 [00:35<00:42, 36.82it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 967/2529 [00:35<00:46, 33.49it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  38%|███▊      | 973/2529 [00:35<00:41, 37.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▊      | 977/2529 [00:35<00:41, 37.60it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▉      | 981/2529 [00:36<00:46, 33.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▉      | 985/2529 [00:36<00:45, 33.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▉      | 989/2529 [00:36<00:44, 34.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▉      | 993/2529 [00:36<00:43, 35.10it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  39%|███▉      | 998/2529 [00:36<00:41, 37.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  40%|███▉      | 1003/2529 [00:36<00:38, 40.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  40%|███▉      | 1008/2529 [00:36<00:44, 34.03it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  40%|████      | 1012/2529 [00:36<00:44, 34.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  40%|████      | 1016/2529 [00:37<00:53, 28.23it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  40%|████      | 1021/2529 [00:37<00:45, 32.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████      | 1026/2529 [00:37<00:44, 33.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████      | 1030/2529 [00:37<00:43, 34.33it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████      | 1035/2529 [00:37<00:39, 37.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████      | 1039/2529 [00:37<00:41, 36.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████      | 1043/2529 [00:37<00:40, 37.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  41%|████▏     | 1047/2529 [00:37<00:41, 35.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1051/2529 [00:38<00:45, 32.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1055/2529 [00:38<00:46, 31.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1059/2529 [00:38<00:44, 33.03it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1065/2529 [00:38<00:40, 35.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1069/2529 [00:38<00:41, 35.22it/s]

Processing: Top 5 region-to-gene links per gene, negative r2g:  42%|████▏     | 1073/2529 [00:38<00:43, 33.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  43%|████▎     | 1077/2529 [00:38<00:42, 33.80it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  43%|████▎     | 1081/2529 [00:38<00:41, 34.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  43%|████▎     | 1087/2529 [00:39<00:35, 40.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  43%|████▎     | 1092/2529 [00:39<00:36, 39.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  43%|████▎     | 1096/2529 [00:39<00:37, 38.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  44%|████▎     | 1102/2529 [00:39<00:36, 39.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  44%|████▎     | 1106/2529 [00:39<00:38, 37.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  44%|████▍     | 1111/2529 [00:39<00:37, 37.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  44%|████▍     | 1116/2529 [00:39<00:36, 39.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  44%|████▍     | 1121/2529 [00:39<00:34, 40.77it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▍     | 1126/2529 [00:40<00:34, 41.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▍     | 1131/2529 [00:40<00:40, 34.87it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▍     | 1135/2529 [00:40<00:39, 35.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▌     | 1141/2529 [00:40<00:34, 39.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▌     | 1146/2529 [00:40<00:35, 38.67it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  45%|████▌     | 1150/2529 [00:40<00:35, 38.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  46%|████▌     | 1154/2529 [00:40<00:36, 37.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  46%|████▌     | 1158/2529 [00:40<00:36, 37.29it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  46%|████▌     | 1163/2529 [00:41<00:37, 36.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  46%|████▌     | 1168/2529 [00:41<00:34, 39.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  46%|████▋     | 1173/2529 [00:41<00:34, 39.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  47%|████▋     | 1178/2529 [00:41<00:33, 40.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  47%|████▋     | 1184/2529 [00:41<00:31, 42.89it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  47%|████▋     | 1190/2529 [00:41<00:32, 41.55it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  47%|████▋     | 1195/2529 [00:41<00:37, 35.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  47%|████▋     | 1199/2529 [00:42<00:39, 33.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1203/2529 [00:42<00:38, 34.75it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1207/2529 [00:42<00:37, 35.13it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1211/2529 [00:42<00:36, 35.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1216/2529 [00:42<00:36, 36.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1220/2529 [00:42<00:35, 36.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  48%|████▊     | 1224/2529 [00:42<00:36, 35.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▊     | 1228/2529 [00:42<00:37, 35.05it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▊     | 1232/2529 [00:42<00:39, 32.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▉     | 1237/2529 [00:43<00:36, 35.56it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▉     | 1241/2529 [00:43<00:40, 31.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▉     | 1245/2529 [00:43<00:53, 24.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  49%|████▉     | 1248/2529 [00:43<00:54, 23.54it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|████▉     | 1252/2529 [00:43<00:47, 26.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|████▉     | 1255/2529 [00:43<00:50, 25.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|████▉     | 1258/2529 [00:44<00:56, 22.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|████▉     | 1262/2529 [00:44<00:49, 25.82it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|█████     | 1265/2529 [00:44<00:48, 26.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|█████     | 1268/2529 [00:44<00:47, 26.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|█████     | 1272/2529 [00:44<00:42, 29.30it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  50%|█████     | 1276/2529 [00:44<00:52, 24.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  51%|█████     | 1279/2529 [00:44<00:50, 25.00it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  51%|█████     | 1283/2529 [00:44<00:44, 27.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  51%|█████     | 1289/2529 [00:45<00:35, 35.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  51%|█████     | 1294/2529 [00:45<00:32, 38.23it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  51%|█████▏    | 1299/2529 [00:45<00:32, 37.74it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1303/2529 [00:45<00:38, 31.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1307/2529 [00:45<00:42, 28.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1312/2529 [00:45<00:37, 32.29it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1317/2529 [00:45<00:34, 35.29it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1321/2529 [00:46<00:39, 30.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1325/2529 [00:46<00:37, 31.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1329/2529 [00:46<00:37, 31.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1333/2529 [00:46<00:43, 27.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1336/2529 [00:46<00:44, 27.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1342/2529 [00:46<00:36, 32.13it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1346/2529 [00:46<00:35, 33.14it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1350/2529 [00:47<00:53, 22.15it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1353/2529 [00:47<01:00, 19.52it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▎    | 1356/2529 [00:47<00:59, 19.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▎    | 1359/2529 [00:47<00:55, 20.91it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1362/2529 [00:47<01:03, 18.36it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1365/2529 [00:48<01:05, 17.74it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1367/2529 [00:48<01:10, 16.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1369/2529 [00:48<01:13, 15.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1369/2529 [01:14<01:13, 15.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1371/2529 [01:14<1:03:07,  3.27s/it]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1373/2529 [01:14<46:52,  2.43s/it]
Processing: Top 5 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1376/2529 [01:14<30:14,  1.57s/it]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1379/2529 [01:14<20:17,  1.06s/it]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1382/2529 [01:14<13:58,  1.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1387/2529 [01:15<08:00,  2.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1390/2529 [01:15<06:13,  3.05it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1393/2529 [01:15<04:49,  3.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1396/2529 [01:15<03:50,  4.91it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1398/2529 [01:15<03:14,  5.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1401/2529 [01:15<02:26,  7.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1404/2529 [01:16<01:57,  9.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1407/2529 [01:16<01:40, 11.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1409/2529 [01:16<01:32, 12.10it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1411/2529 [01:16<01:24, 13.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1414/2529 [01:16<01:08, 16.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1417/2529 [01:16<00:58, 18.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1421/2529 [01:16<00:49, 22.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▋    | 1425/2529 [01:16<00:47, 23.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  56%|█████▋    | 1428/2529 [01:17<00:45, 24.23it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1431/2529 [01:17<00:43, 25.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1435/2529 [01:17<00:39, 27.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1438/2529 [01:17<00:38, 28.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1441/2529 [01:17<00:45, 23.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1445/2529 [01:17<00:40, 26.87it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1449/2529 [01:17<00:36, 29.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1453/2529 [01:18<00:43, 24.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1458/2529 [01:18<00:36, 29.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1462/2529 [01:18<00:37, 28.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1467/2529 [01:18<00:32, 32.64it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1471/2529 [01:18<00:31, 33.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1476/2529 [01:18<00:28, 36.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▊    | 1480/2529 [01:18<00:30, 34.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▊    | 1485/2529 [01:18<00:30, 34.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1489/2529 [01:19<00:33, 30.67it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1493/2529 [01:19<00:31, 32.76it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1498/2529 [01:19<00:27, 36.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1502/2529 [01:19<00:28, 35.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1506/2529 [01:19<00:33, 30.54it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1510/2529 [01:19<00:32, 31.57it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1514/2529 [01:19<00:31, 32.70it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|██████    | 1518/2529 [01:19<00:33, 30.35it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|██████    | 1524/2529 [01:20<00:29, 34.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  60%|██████    | 1528/2529 [01:20<00:29, 34.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████    | 1532/2529 [01:20<00:30, 33.00it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████    | 1536/2529 [01:20<00:31, 31.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████    | 1540/2529 [01:20<00:30, 32.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████    | 1544/2529 [01:20<00:33, 29.62it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████    | 1548/2529 [01:20<00:31, 31.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  61%|██████▏   | 1553/2529 [01:20<00:27, 35.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1558/2529 [01:21<00:25, 37.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1563/2529 [01:21<00:25, 38.05it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1567/2529 [01:21<00:26, 36.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1571/2529 [01:21<00:28, 34.16it/s]

Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1576/2529 [01:21<00:25, 37.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1580/2529 [01:21<00:28, 33.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1584/2529 [01:21<00:33, 28.35it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1588/2529 [01:22<00:31, 30.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1592/2529 [01:22<00:36, 25.95it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1595/2529 [01:22<00:35, 26.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1599/2529 [01:22<00:32, 28.37it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1602/2529 [01:22<00:32, 28.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1605/2529 [01:22<00:38, 23.71it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1608/2529 [01:22<00:44, 20.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1611/2529 [01:23<00:51, 17.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1613/2529 [01:23<00:56, 16.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1615/2529 [01:23<01:03, 14.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1617/2529 [01:23<01:03, 14.35it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1619/2529 [01:23<01:05, 13.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1621/2529 [01:24<01:09, 13.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1623/2529 [01:24<01:08, 13.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1625/2529 [01:24<01:09, 12.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1629/2529 [01:24<00:49, 18.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1633/2529 [01:24<00:41, 21.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1636/2529 [01:24<00:41, 21.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1639/2529 [01:24<00:39, 22.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1642/2529 [01:24<00:36, 24.13it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1646/2529 [01:25<00:35, 24.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1649/2529 [01:25<00:44, 19.60it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1652/2529 [01:25<00:46, 18.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1655/2529 [01:25<00:48, 17.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1659/2529 [01:25<00:39, 21.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1662/2529 [01:25<00:39, 22.10it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1665/2529 [01:26<00:41, 20.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1669/2529 [01:26<00:35, 23.91it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1672/2529 [01:26<00:35, 24.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▋   | 1676/2529 [01:26<00:31, 27.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  66%|██████▋   | 1681/2529 [01:26<00:29, 28.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1684/2529 [01:26<00:31, 27.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1687/2529 [01:26<00:33, 25.49it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1691/2529 [01:26<00:31, 26.87it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1694/2529 [01:27<00:30, 27.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1697/2529 [01:27<00:30, 26.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1700/2529 [01:27<00:38, 21.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1703/2529 [01:27<00:41, 19.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1706/2529 [01:27<00:40, 20.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1709/2529 [01:27<00:39, 20.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1712/2529 [01:28<00:42, 19.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1714/2529 [01:28<00:43, 18.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1716/2529 [01:28<00:47, 17.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1718/2529 [01:28<00:45, 17.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1722/2529 [01:28<00:36, 21.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1725/2529 [01:28<00:38, 20.83it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1728/2529 [01:28<00:41, 19.10it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1730/2529 [01:29<00:45, 17.59it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▊   | 1734/2529 [01:29<00:36, 21.53it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▊   | 1737/2529 [01:29<00:34, 22.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1740/2529 [01:29<00:35, 22.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1743/2529 [01:29<00:34, 22.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1747/2529 [01:29<00:30, 26.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1751/2529 [01:29<00:27, 28.08it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1754/2529 [01:29<00:27, 27.70it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1758/2529 [01:29<00:25, 30.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1764/2529 [01:30<00:20, 37.77it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1768/2529 [01:30<00:20, 37.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|███████   | 1772/2529 [01:30<00:21, 34.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|███████   | 1776/2529 [01:30<00:23, 32.46it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  70%|███████   | 1780/2529 [01:30<00:23, 31.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████   | 1785/2529 [01:30<00:22, 32.82it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████   | 1789/2529 [01:31<00:29, 25.33it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████   | 1794/2529 [01:31<00:24, 30.09it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████   | 1800/2529 [01:31<00:21, 33.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████▏  | 1804/2529 [01:31<00:23, 31.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  71%|███████▏  | 1808/2529 [01:31<00:25, 28.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1812/2529 [01:31<00:23, 30.34it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1816/2529 [01:31<00:22, 32.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1820/2529 [01:31<00:21, 33.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1824/2529 [01:32<00:20, 34.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1828/2529 [01:32<00:21, 33.21it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1832/2529 [01:32<00:20, 34.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1836/2529 [01:32<00:24, 28.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1840/2529 [01:32<00:25, 27.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1843/2529 [01:32<00:27, 24.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1846/2529 [01:32<00:30, 22.08it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1850/2529 [01:33<00:28, 24.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1853/2529 [01:33<00:27, 24.71it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1857/2529 [01:33<00:24, 27.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▎  | 1861/2529 [01:33<00:22, 29.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▎  | 1865/2529 [01:33<00:21, 30.62it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1869/2529 [01:33<00:21, 30.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1873/2529 [01:33<00:24, 26.70it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1876/2529 [01:34<00:30, 21.57it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1879/2529 [01:34<00:31, 20.77it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1882/2529 [01:34<00:30, 21.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1886/2529 [01:34<00:25, 24.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1890/2529 [01:34<00:23, 27.69it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1893/2529 [01:34<00:23, 27.03it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1896/2529 [01:34<00:24, 25.72it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1900/2529 [01:34<00:22, 27.57it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1906/2529 [01:35<00:18, 33.67it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1910/2529 [01:35<00:20, 29.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1914/2529 [01:35<00:21, 28.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1918/2529 [01:35<00:20, 29.76it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1922/2529 [01:35<00:19, 30.85it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1926/2529 [01:35<00:18, 32.55it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▋  | 1930/2529 [01:35<00:18, 31.86it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  76%|███████▋  | 1934/2529 [01:36<00:18, 32.64it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1938/2529 [01:36<00:22, 26.62it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1941/2529 [01:36<00:21, 27.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1945/2529 [01:36<00:20, 28.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1949/2529 [01:36<00:18, 30.82it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1953/2529 [01:36<00:19, 29.16it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1957/2529 [01:36<00:21, 27.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1961/2529 [01:37<00:20, 27.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1964/2529 [01:37<00:21, 26.15it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1967/2529 [01:37<00:22, 25.21it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1970/2529 [01:37<00:29, 18.75it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1973/2529 [01:37<00:37, 14.75it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1975/2529 [01:38<00:37, 14.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1977/2529 [01:38<00:37, 14.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1979/2529 [01:38<00:37, 14.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1981/2529 [01:38<00:37, 14.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1984/2529 [01:38<00:32, 16.82it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▊  | 1987/2529 [01:38<00:28, 19.33it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▊  | 1990/2529 [01:38<00:26, 20.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▉  | 1994/2529 [01:38<00:22, 23.73it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▉  | 1997/2529 [01:39<00:24, 21.75it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2000/2529 [01:39<00:26, 19.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2003/2529 [01:39<00:24, 21.89it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2007/2529 [01:39<00:20, 26.09it/s]

Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2011/2529 [01:39<00:18, 28.45it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2016/2529 [01:39<00:15, 33.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2020/2529 [01:40<00:23, 21.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2023/2529 [01:40<00:23, 21.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|████████  | 2028/2529 [01:40<00:18, 26.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|████████  | 2032/2529 [01:40<00:19, 25.15it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  80%|████████  | 2035/2529 [01:40<00:19, 24.87it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████  | 2038/2529 [01:40<00:21, 23.35it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████  | 2041/2529 [01:40<00:21, 22.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████  | 2046/2529 [01:41<00:17, 27.18it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████  | 2050/2529 [01:41<00:16, 28.97it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████  | 2054/2529 [01:41<00:15, 30.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  81%|████████▏ | 2059/2529 [01:41<00:13, 34.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2063/2529 [01:41<00:15, 31.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2067/2529 [01:41<00:15, 30.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2071/2529 [01:41<00:15, 30.22it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2075/2529 [01:41<00:16, 27.45it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2078/2529 [01:42<00:19, 22.92it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2082/2529 [01:42<00:19, 22.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2085/2529 [01:42<00:20, 22.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2089/2529 [01:42<00:17, 25.78it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2092/2529 [01:42<00:20, 21.70it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2095/2529 [01:42<00:21, 20.45it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2099/2529 [01:43<00:18, 23.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2102/2529 [01:43<00:19, 22.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2106/2529 [01:43<00:16, 25.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2109/2529 [01:43<00:16, 25.21it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▎ | 2113/2529 [01:43<00:14, 28.63it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▎ | 2117/2529 [01:43<00:17, 23.05it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2120/2529 [01:43<00:18, 22.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2124/2529 [01:44<00:16, 24.98it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2128/2529 [01:44<00:14, 27.50it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2132/2529 [01:44<00:13, 29.33it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2136/2529 [01:44<00:13, 29.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2140/2529 [01:44<00:12, 32.31it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2144/2529 [01:44<00:12, 30.30it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2149/2529 [01:44<00:11, 34.08it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2154/2529 [01:44<00:09, 38.06it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2158/2529 [01:45<00:09, 37.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2163/2529 [01:45<00:09, 40.15it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2168/2529 [01:45<00:09, 38.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2172/2529 [01:45<00:09, 36.14it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2176/2529 [01:45<00:10, 33.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2181/2529 [01:45<00:09, 36.17it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  86%|████████▋ | 2185/2529 [01:45<00:09, 35.89it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2190/2529 [01:45<00:08, 38.03it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2195/2529 [01:46<00:09, 34.79it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2200/2529 [01:46<00:08, 36.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2204/2529 [01:46<00:08, 36.21it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2208/2529 [01:46<00:09, 34.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2212/2529 [01:46<00:09, 35.01it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2217/2529 [01:46<00:08, 38.02it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2223/2529 [01:46<00:07, 41.11it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2228/2529 [01:46<00:08, 36.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2232/2529 [01:47<00:08, 35.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2236/2529 [01:47<00:10, 28.27it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▊ | 2240/2529 [01:47<00:09, 29.80it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▊ | 2244/2529 [01:47<00:09, 30.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2248/2529 [01:47<00:09, 29.48it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2252/2529 [01:47<00:09, 29.94it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2258/2529 [01:47<00:07, 36.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2262/2529 [01:48<00:08, 33.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2267/2529 [01:48<00:07, 35.55it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2271/2529 [01:48<00:07, 35.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2275/2529 [01:48<00:08, 31.42it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|█████████ | 2279/2529 [01:48<00:08, 30.50it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|█████████ | 2284/2529 [01:48<00:07, 34.80it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  90%|█████████ | 2288/2529 [01:48<00:06, 35.77it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████ | 2292/2529 [01:48<00:06, 35.70it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████ | 2297/2529 [01:49<00:06, 38.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████ | 2301/2529 [01:49<00:06, 36.41it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████ | 2305/2529 [01:49<00:06, 34.66it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████▏| 2309/2529 [01:49<00:06, 32.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  91%|█████████▏| 2313/2529 [01:49<00:06, 32.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2317/2529 [01:49<00:07, 28.67it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2322/2529 [01:49<00:06, 33.30it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2326/2529 [01:49<00:06, 33.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2330/2529 [01:50<00:05, 33.99it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2335/2529 [01:50<00:05, 37.50it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2339/2529 [01:50<00:05, 35.87it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2343/2529 [01:50<00:05, 36.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2347/2529 [01:50<00:05, 35.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2351/2529 [01:50<00:05, 32.49it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2355/2529 [01:50<00:05, 31.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2360/2529 [01:50<00:05, 33.54it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▎| 2366/2529 [01:51<00:04, 35.68it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▎| 2370/2529 [01:51<00:04, 35.26it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2374/2529 [01:51<00:04, 33.49it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2378/2529 [01:51<00:04, 33.65it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2382/2529 [01:51<00:04, 33.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2388/2529 [01:51<00:03, 40.20it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2393/2529 [01:51<00:03, 38.13it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2398/2529 [01:51<00:03, 39.96it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2404/2529 [01:52<00:02, 43.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2409/2529 [01:52<00:03, 36.12it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2414/2529 [01:52<00:03, 37.19it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2420/2529 [01:52<00:02, 39.07it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2425/2529 [01:52<00:02, 40.23it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2430/2529 [01:52<00:02, 40.43it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  96%|█████████▋| 2435/2529 [01:52<00:02, 37.14it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  96%|█████████▋| 2439/2529 [01:53<00:02, 34.60it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2445/2529 [01:53<00:02, 38.40it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2450/2529 [01:53<00:02, 37.61it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2454/2529 [01:53<00:01, 37.93it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2458/2529 [01:53<00:02, 35.39it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2462/2529 [01:53<00:01, 35.38it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2466/2529 [01:53<00:01, 33.44it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2472/2529 [01:53<00:01, 38.47it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2477/2529 [01:54<00:01, 38.58it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2481/2529 [01:54<00:01, 38.84it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2487/2529 [01:54<00:00, 42.81it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▊| 2493/2529 [01:54<00:00, 46.24it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2498/2529 [01:54<00:00, 41.04it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2503/2529 [01:54<00:00, 36.36it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2507/2529 [01:54<00:00, 34.25it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2511/2529 [01:54<00:00, 34.90it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2515/2529 [01:55<00:00, 35.28it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2519/2529 [01:55<00:00, 35.51it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2525/2529 [01:55<00:00, 38.88it/s]
Processing: Top 5 region-to-gene links per gene, negative r2g: 100%|██████████| 2529/2529 [01:55<00:00, 38.54it/s]
 29%|██▊       | 4/14 [08:38<20:07, 120.79s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   0%|          | 3/2529 [00:00<01:42, 24.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   0%|          | 6/2529 [00:00<01:39, 25.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   0%|          | 9/2529 [00:00<01:45, 23.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   0%|          | 12/2529 [00:00<01:53, 22.22it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 15/2529 [00:00<01:49, 22.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 18/2529 [00:00<01:43, 24.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 21/2529 [00:00<02:12, 18.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 24/2529 [00:01<02:12, 18.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 27/2529 [00:01<02:01, 20.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|          | 30/2529 [00:01<02:11, 19.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|▏         | 33/2529 [00:01<02:23, 17.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   1%|▏         | 36/2529 [00:01<02:07, 19.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 39/2529 [00:01<02:06, 19.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 42/2529 [00:02<02:11, 18.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 45/2529 [00:02<02:03, 20.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 48/2529 [00:02<02:14, 18.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 50/2529 [00:02<02:12, 18.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 52/2529 [00:02<02:10, 18.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 55/2529 [00:02<02:00, 20.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 58/2529 [00:02<01:47, 22.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   2%|▏         | 62/2529 [00:02<01:35, 25.76it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 65/2529 [00:03<01:33, 26.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 68/2529 [00:03<01:32, 26.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 71/2529 [00:03<01:43, 23.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 74/2529 [00:03<02:02, 20.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 77/2529 [00:03<02:13, 18.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 80/2529 [00:03<01:59, 20.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 83/2529 [00:03<01:52, 21.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   3%|▎         | 86/2529 [00:04<02:02, 19.91it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▎         | 89/2529 [00:04<02:01, 20.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▎         | 92/2529 [00:04<01:54, 21.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 95/2529 [00:04<01:48, 22.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 98/2529 [00:04<01:49, 22.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 101/2529 [00:04<02:10, 18.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 103/2529 [00:04<02:11, 18.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 107/2529 [00:05<01:47, 22.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 110/2529 [00:05<01:48, 22.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   4%|▍         | 113/2529 [00:05<01:49, 22.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▍         | 116/2529 [00:05<02:28, 16.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▍         | 118/2529 [00:05<03:00, 13.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▍         | 120/2529 [00:06<03:00, 13.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▍         | 122/2529 [00:06<03:03, 13.08it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▍         | 124/2529 [00:06<02:58, 13.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 127/2529 [00:06<02:57, 13.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 129/2529 [00:06<03:06, 12.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 131/2529 [00:06<03:12, 12.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 133/2529 [00:07<03:30, 11.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 135/2529 [00:07<03:31, 11.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 137/2529 [00:07<03:43, 10.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   5%|▌         | 139/2529 [00:07<03:43, 10.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 141/2529 [00:07<03:16, 12.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 143/2529 [00:07<03:03, 12.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 145/2529 [00:08<03:11, 12.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 147/2529 [00:08<03:01, 13.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 149/2529 [00:08<02:59, 13.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 152/2529 [00:08<02:20, 16.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 155/2529 [00:08<02:33, 15.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▌         | 157/2529 [00:08<02:55, 13.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▋         | 159/2529 [00:09<03:07, 12.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▋         | 161/2529 [00:09<03:27, 11.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   6%|▋         | 163/2529 [00:09<03:27, 11.41it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 165/2529 [00:09<03:05, 12.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 167/2529 [00:09<02:51, 13.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 169/2529 [00:09<02:59, 13.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 171/2529 [00:10<02:54, 13.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 173/2529 [00:10<03:03, 12.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 175/2529 [00:10<03:06, 12.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 177/2529 [00:10<02:54, 13.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 180/2529 [00:10<02:37, 14.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 183/2529 [00:10<02:17, 17.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 186/2529 [00:10<02:07, 18.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   7%|▋         | 188/2529 [00:11<02:05, 18.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 190/2529 [00:11<02:14, 17.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 192/2529 [00:11<02:11, 17.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 195/2529 [00:11<02:00, 19.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 198/2529 [00:11<02:00, 19.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 201/2529 [00:11<01:47, 21.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 204/2529 [00:11<02:09, 18.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 207/2529 [00:12<02:03, 18.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 210/2529 [00:12<01:54, 20.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   8%|▊         | 213/2529 [00:12<02:02, 18.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▊         | 215/2529 [00:12<02:05, 18.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▊         | 218/2529 [00:12<01:54, 20.23it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▊         | 221/2529 [00:12<01:45, 21.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 224/2529 [00:12<01:41, 22.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 227/2529 [00:13<01:49, 21.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 230/2529 [00:13<01:41, 22.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 233/2529 [00:13<01:39, 23.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 236/2529 [00:13<01:32, 24.69it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:   9%|▉         | 239/2529 [00:13<01:31, 25.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|▉         | 242/2529 [00:13<01:42, 22.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|▉         | 246/2529 [00:13<01:41, 22.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|▉         | 249/2529 [00:13<01:45, 21.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|▉         | 252/2529 [00:14<01:50, 20.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|█         | 255/2529 [00:14<01:40, 22.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|█         | 258/2529 [00:14<01:44, 21.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|█         | 262/2529 [00:14<01:52, 20.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  10%|█         | 265/2529 [00:14<01:52, 20.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█         | 269/2529 [00:14<01:37, 23.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█         | 272/2529 [00:15<01:40, 22.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█         | 275/2529 [00:15<01:44, 21.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█         | 279/2529 [00:15<01:30, 24.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█         | 282/2529 [00:15<01:37, 22.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█▏        | 285/2529 [00:15<01:34, 23.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  11%|█▏        | 288/2529 [00:15<01:32, 24.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 291/2529 [00:15<01:41, 22.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 294/2529 [00:16<01:42, 21.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 297/2529 [00:16<01:42, 21.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 300/2529 [00:16<01:54, 19.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 303/2529 [00:16<01:48, 20.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 306/2529 [00:16<01:41, 21.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 310/2529 [00:16<01:32, 23.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 313/2529 [00:16<01:28, 25.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  12%|█▏        | 316/2529 [00:16<01:25, 25.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 319/2529 [00:17<01:22, 26.69it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 322/2529 [00:17<01:30, 24.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 325/2529 [00:17<01:32, 23.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 328/2529 [00:17<01:31, 24.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 331/2529 [00:17<01:43, 21.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 334/2529 [00:17<01:58, 18.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 337/2529 [00:17<01:54, 19.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  13%|█▎        | 340/2529 [00:18<01:48, 20.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▎        | 343/2529 [00:18<02:03, 17.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▎        | 346/2529 [00:18<01:57, 18.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 348/2529 [00:18<01:58, 18.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 352/2529 [00:18<01:43, 21.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 355/2529 [00:18<01:58, 18.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 357/2529 [00:19<02:11, 16.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 359/2529 [00:19<02:28, 14.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 361/2529 [00:19<02:51, 12.68it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 363/2529 [00:19<03:05, 11.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  14%|█▍        | 365/2529 [00:19<03:17, 10.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 367/2529 [00:20<03:40,  9.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 369/2529 [00:20<03:34, 10.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 371/2529 [00:20<03:44,  9.61it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 373/2529 [00:20<03:38,  9.85it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 375/2529 [00:21<03:43,  9.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▍        | 378/2529 [00:21<02:47, 12.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▌        | 381/2529 [00:21<02:18, 15.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▌        | 383/2529 [00:21<02:20, 15.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▌        | 386/2529 [00:21<02:04, 17.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  15%|█▌        | 389/2529 [00:21<01:57, 18.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 392/2529 [00:21<01:53, 18.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 394/2529 [00:21<01:57, 18.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 396/2529 [00:22<02:28, 14.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 398/2529 [00:51<2:18:51,  3.91s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 398/2529 [00:51<2:18:51,  3.91s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 399/2529 [00:51<1:57:23,  3.31s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 401/2529 [00:51<1:21:18,  2.29s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 403/2529 [00:51<57:26,  1.62s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 405/2529 [00:51<40:26,  1.14s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 408/2529 [00:52<24:53,  1.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▌        | 410/2529 [00:52<18:42,  1.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▋        | 412/2529 [00:52<14:13,  2.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  16%|█▋        | 415/2529 [00:52<09:24,  3.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 418/2529 [00:52<06:41,  5.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 420/2529 [00:52<05:28,  6.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 423/2529 [00:52<04:09,  8.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 427/2529 [00:52<02:58, 11.76it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 430/2529 [00:53<02:47, 12.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 433/2529 [00:53<02:46, 12.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 436/2529 [00:53<02:23, 14.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 438/2529 [00:53<02:17, 15.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  17%|█▋        | 440/2529 [00:53<02:15, 15.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 443/2529 [00:53<01:57, 17.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 446/2529 [00:54<02:04, 16.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 448/2529 [00:54<02:13, 15.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 450/2529 [00:54<02:35, 13.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 452/2529 [00:54<02:40, 12.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 454/2529 [00:54<02:27, 14.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 456/2529 [00:54<02:30, 13.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 458/2529 [00:55<02:27, 14.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 460/2529 [00:55<02:32, 13.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 463/2529 [00:55<02:07, 16.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  18%|█▊        | 466/2529 [00:55<02:04, 16.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▊        | 468/2529 [00:55<02:13, 15.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▊        | 470/2529 [00:55<02:27, 13.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▊        | 472/2529 [00:56<02:42, 12.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▊        | 474/2529 [00:56<02:26, 13.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 477/2529 [00:56<02:13, 15.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 479/2529 [00:56<02:05, 16.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 481/2529 [00:56<02:10, 15.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 483/2529 [00:56<02:07, 16.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 486/2529 [00:56<01:47, 18.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 490/2529 [00:56<01:26, 23.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  19%|█▉        | 493/2529 [00:57<01:29, 22.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|█▉        | 496/2529 [00:57<01:28, 23.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|█▉        | 500/2529 [00:57<01:18, 25.69it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|█▉        | 503/2529 [00:57<01:20, 25.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|██        | 506/2529 [00:57<01:21, 24.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|██        | 509/2529 [00:57<01:29, 22.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|██        | 512/2529 [00:57<01:35, 21.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  20%|██        | 515/2529 [00:58<01:41, 19.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 519/2529 [00:58<01:26, 23.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 522/2529 [00:58<01:33, 21.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 525/2529 [00:58<01:50, 18.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 529/2529 [00:58<01:33, 21.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 533/2529 [00:58<01:22, 24.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██        | 536/2529 [00:58<01:25, 23.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██▏       | 539/2529 [00:59<01:38, 20.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  21%|██▏       | 542/2529 [00:59<01:47, 18.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 544/2529 [00:59<01:49, 18.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 547/2529 [00:59<01:36, 20.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 551/2529 [00:59<01:26, 22.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 554/2529 [00:59<01:26, 22.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 557/2529 [00:59<01:25, 23.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 560/2529 [01:00<01:28, 22.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 563/2529 [01:00<01:27, 22.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  22%|██▏       | 567/2529 [01:00<01:29, 22.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 570/2529 [01:00<01:32, 21.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 573/2529 [01:00<01:31, 21.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 576/2529 [01:00<01:41, 19.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 578/2529 [01:01<01:59, 16.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 581/2529 [01:01<01:48, 18.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 584/2529 [01:01<01:46, 18.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 587/2529 [01:01<01:36, 20.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 590/2529 [01:01<01:32, 21.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  23%|██▎       | 593/2529 [01:01<01:35, 20.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▎       | 596/2529 [01:01<01:27, 22.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▎       | 599/2529 [01:02<01:34, 20.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 602/2529 [01:02<01:36, 20.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 605/2529 [01:02<02:05, 15.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 607/2529 [01:02<02:16, 14.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 609/2529 [01:02<02:19, 13.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 612/2529 [01:03<02:06, 15.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 615/2529 [01:03<01:53, 16.85it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  24%|██▍       | 618/2529 [01:03<01:44, 18.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▍       | 621/2529 [01:03<01:39, 19.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▍       | 623/2529 [01:03<01:40, 18.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▍       | 625/2529 [01:03<01:43, 18.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▍       | 628/2529 [01:03<01:35, 19.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▍       | 632/2529 [01:03<01:21, 23.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▌       | 635/2529 [01:04<01:19, 23.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▌       | 638/2529 [01:04<01:45, 18.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▌       | 641/2529 [01:04<01:42, 18.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  25%|██▌       | 644/2529 [01:04<01:35, 19.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 647/2529 [01:04<01:29, 21.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 650/2529 [01:04<01:23, 22.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 653/2529 [01:04<01:29, 21.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 656/2529 [01:05<01:29, 21.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 659/2529 [01:05<01:38, 19.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▌       | 661/2529 [01:05<01:42, 18.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▋       | 664/2529 [01:05<01:31, 20.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  26%|██▋       | 667/2529 [01:05<01:31, 20.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 671/2529 [01:05<01:20, 23.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 674/2529 [01:05<01:26, 21.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 677/2529 [01:06<01:30, 20.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 680/2529 [01:06<01:33, 19.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 683/2529 [01:06<01:29, 20.56it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 686/2529 [01:06<01:34, 19.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 689/2529 [01:06<01:38, 18.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 691/2529 [01:07<02:19, 13.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 693/2529 [01:07<02:45, 11.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  27%|██▋       | 695/2529 [01:07<02:52, 10.61it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 697/2529 [01:07<02:48, 10.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 699/2529 [01:07<02:40, 11.38it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 701/2529 [01:08<02:45, 11.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 703/2529 [01:08<02:27, 12.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 705/2529 [01:08<02:27, 12.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 707/2529 [01:08<02:11, 13.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 709/2529 [01:08<02:07, 14.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 712/2529 [01:08<01:54, 15.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 714/2529 [01:08<02:11, 13.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 716/2529 [01:09<02:24, 12.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 718/2529 [01:09<02:10, 13.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  28%|██▊       | 720/2529 [01:09<02:02, 14.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▊       | 723/2529 [01:09<01:50, 16.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▊       | 727/2529 [01:09<01:26, 20.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 730/2529 [01:09<01:23, 21.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 734/2529 [01:10<01:36, 18.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 737/2529 [01:10<01:51, 16.08it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 739/2529 [01:10<01:52, 15.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 742/2529 [01:10<01:43, 17.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  29%|██▉       | 745/2529 [01:10<01:42, 17.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|██▉       | 748/2529 [01:10<01:40, 17.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|██▉       | 750/2529 [01:11<01:47, 16.56it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|██▉       | 752/2529 [01:11<01:55, 15.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|██▉       | 755/2529 [01:11<01:54, 15.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|██▉       | 757/2529 [01:11<01:50, 15.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|███       | 760/2529 [01:11<01:35, 18.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|███       | 763/2529 [01:11<01:23, 21.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|███       | 766/2529 [01:11<01:26, 20.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  30%|███       | 769/2529 [01:12<01:25, 20.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 772/2529 [01:12<01:18, 22.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 775/2529 [01:12<01:13, 24.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 778/2529 [01:12<01:20, 21.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 781/2529 [01:12<01:18, 22.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 784/2529 [01:12<01:23, 20.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 787/2529 [01:12<01:35, 18.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███       | 789/2529 [01:13<01:37, 17.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███▏      | 791/2529 [01:13<02:02, 14.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███▏      | 794/2529 [01:13<01:43, 16.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  31%|███▏      | 796/2529 [01:13<01:57, 14.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 798/2529 [01:13<02:04, 13.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 801/2529 [01:13<01:42, 16.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 804/2529 [01:14<02:04, 13.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 806/2529 [01:14<01:59, 14.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 808/2529 [01:14<02:10, 13.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 811/2529 [01:14<01:50, 15.56it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 814/2529 [01:14<01:37, 17.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 816/2529 [01:14<01:42, 16.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 818/2529 [01:14<01:38, 17.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  32%|███▏      | 821/2529 [01:15<01:34, 18.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 825/2529 [01:15<01:27, 19.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 827/2529 [01:15<01:43, 16.49it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 829/2529 [01:15<01:50, 15.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 832/2529 [01:15<01:36, 17.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 834/2529 [01:15<01:37, 17.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 836/2529 [01:15<01:35, 17.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 840/2529 [01:16<01:24, 19.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 843/2529 [01:16<01:18, 21.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  33%|███▎      | 846/2529 [01:16<01:19, 21.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▎      | 849/2529 [01:16<01:17, 21.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▎      | 852/2529 [01:16<01:18, 21.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 855/2529 [01:16<01:11, 23.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 859/2529 [01:16<01:04, 25.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 862/2529 [01:17<01:04, 25.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 865/2529 [01:17<01:06, 25.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 868/2529 [01:17<01:03, 26.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  34%|███▍      | 871/2529 [01:17<01:01, 26.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▍      | 874/2529 [01:17<01:08, 24.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▍      | 878/2529 [01:17<01:07, 24.49it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▍      | 881/2529 [01:17<01:11, 23.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▍      | 884/2529 [01:17<01:19, 20.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▌      | 887/2529 [01:18<01:13, 22.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▌      | 891/2529 [01:18<01:05, 25.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▌      | 894/2529 [01:18<01:08, 23.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  35%|███▌      | 897/2529 [01:18<01:07, 24.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 900/2529 [01:18<01:12, 22.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 903/2529 [01:18<01:22, 19.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 906/2529 [01:18<01:17, 21.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 909/2529 [01:19<01:16, 21.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 912/2529 [01:19<01:17, 20.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▌      | 915/2529 [01:19<01:12, 22.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▋      | 918/2529 [01:19<01:15, 21.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  36%|███▋      | 921/2529 [01:19<01:10, 22.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 925/2529 [01:19<01:02, 25.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 929/2529 [01:19<00:57, 27.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 932/2529 [01:19<00:59, 26.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 935/2529 [01:20<01:14, 21.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 938/2529 [01:20<01:14, 21.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 941/2529 [01:20<01:30, 17.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 943/2529 [01:20<01:36, 16.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  37%|███▋      | 947/2529 [01:20<01:18, 20.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 950/2529 [01:20<01:16, 20.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 953/2529 [01:21<01:18, 20.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 956/2529 [01:21<01:20, 19.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 959/2529 [01:21<01:13, 21.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 963/2529 [01:21<01:03, 24.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 966/2529 [01:21<01:10, 22.23it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 969/2529 [01:21<01:08, 22.91it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  38%|███▊      | 973/2529 [01:21<01:04, 24.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▊      | 976/2529 [01:22<01:03, 24.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▊      | 979/2529 [01:22<01:13, 20.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 982/2529 [01:22<01:09, 22.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 985/2529 [01:22<01:11, 21.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 988/2529 [01:22<01:11, 21.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 991/2529 [01:22<01:06, 23.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 994/2529 [01:22<01:07, 22.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  39%|███▉      | 997/2529 [01:23<01:03, 24.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|███▉      | 1000/2529 [01:23<01:01, 24.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|███▉      | 1003/2529 [01:23<01:00, 25.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|███▉      | 1006/2529 [01:23<01:05, 23.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|███▉      | 1009/2529 [01:23<01:11, 21.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|████      | 1012/2529 [01:23<01:12, 20.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|████      | 1015/2529 [01:23<01:25, 17.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|████      | 1017/2529 [01:24<01:24, 17.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|████      | 1021/2529 [01:24<01:10, 21.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  40%|████      | 1024/2529 [01:24<01:06, 22.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1027/2529 [01:24<01:07, 22.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1030/2529 [01:24<01:09, 21.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1033/2529 [01:24<01:05, 22.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1037/2529 [01:24<01:00, 24.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1040/2529 [01:25<01:03, 23.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████      | 1043/2529 [01:25<01:02, 23.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████▏     | 1046/2529 [01:25<01:06, 22.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  41%|████▏     | 1049/2529 [01:25<01:02, 23.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1052/2529 [01:25<01:17, 19.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1055/2529 [01:25<01:12, 20.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1058/2529 [01:25<01:07, 21.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1061/2529 [01:25<01:03, 23.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1064/2529 [01:26<00:58, 24.95it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1067/2529 [01:26<01:05, 22.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1070/2529 [01:26<01:03, 23.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  42%|████▏     | 1073/2529 [01:26<01:10, 20.69it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1076/2529 [01:26<01:06, 21.85it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1079/2529 [01:26<01:05, 22.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1082/2529 [01:26<01:02, 23.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1086/2529 [01:27<00:55, 25.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1089/2529 [01:27<01:01, 23.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1093/2529 [01:27<00:58, 24.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1096/2529 [01:27<00:57, 24.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  43%|████▎     | 1100/2529 [01:27<00:51, 27.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▎     | 1103/2529 [01:27<01:02, 22.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▎     | 1106/2529 [01:27<01:00, 23.51it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1109/2529 [01:28<00:58, 24.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1112/2529 [01:28<00:57, 24.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1115/2529 [01:28<00:54, 25.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1118/2529 [01:28<00:55, 25.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1121/2529 [01:28<00:55, 25.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  44%|████▍     | 1124/2529 [01:28<00:52, 26.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▍     | 1127/2529 [01:28<00:59, 23.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▍     | 1130/2529 [01:28<01:06, 21.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▍     | 1134/2529 [01:29<01:05, 21.41it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▍     | 1138/2529 [01:29<00:56, 24.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▌     | 1141/2529 [01:29<00:55, 25.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▌     | 1144/2529 [01:29<00:57, 24.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▌     | 1147/2529 [01:29<00:55, 24.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  45%|████▌     | 1150/2529 [01:29<00:57, 23.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▌     | 1153/2529 [01:29<01:00, 22.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▌     | 1156/2529 [01:29<00:57, 23.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▌     | 1159/2529 [01:30<00:59, 22.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▌     | 1163/2529 [01:30<00:59, 23.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▌     | 1167/2529 [01:30<00:54, 24.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▋     | 1170/2529 [01:30<00:52, 25.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  46%|████▋     | 1173/2529 [01:30<00:54, 24.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1176/2529 [01:30<00:55, 24.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1180/2529 [01:30<00:50, 26.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1184/2529 [01:31<00:49, 27.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1188/2529 [01:31<00:45, 29.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1191/2529 [01:31<00:52, 25.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1194/2529 [01:31<00:58, 22.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1197/2529 [01:31<01:06, 20.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  47%|████▋     | 1200/2529 [01:31<01:03, 20.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1203/2529 [01:31<01:01, 21.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1207/2529 [01:32<00:59, 22.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1210/2529 [01:32<01:00, 21.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1213/2529 [01:32<00:57, 22.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1216/2529 [01:32<00:56, 23.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1219/2529 [01:32<00:58, 22.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1222/2529 [01:32<00:55, 23.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  48%|████▊     | 1225/2529 [01:32<00:54, 23.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▊     | 1228/2529 [01:33<00:57, 22.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▊     | 1231/2529 [01:33<00:55, 23.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1234/2529 [01:33<00:58, 22.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1237/2529 [01:33<00:57, 22.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1240/2529 [01:33<00:54, 23.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1243/2529 [01:33<01:16, 16.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1245/2529 [01:33<01:24, 15.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1247/2529 [01:34<01:21, 15.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  49%|████▉     | 1249/2529 [01:34<01:20, 15.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|████▉     | 1252/2529 [01:34<01:09, 18.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|████▉     | 1255/2529 [01:34<01:13, 17.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|████▉     | 1257/2529 [01:34<01:20, 15.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|████▉     | 1259/2529 [01:34<01:20, 15.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|████▉     | 1262/2529 [01:34<01:10, 17.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|█████     | 1265/2529 [01:35<01:10, 18.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|█████     | 1267/2529 [01:35<01:11, 17.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|█████     | 1270/2529 [01:35<01:05, 19.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|█████     | 1273/2529 [01:35<00:59, 21.08it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  50%|█████     | 1276/2529 [01:35<01:18, 16.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1278/2529 [01:35<01:15, 16.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1281/2529 [01:36<01:09, 17.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1284/2529 [01:36<01:02, 20.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1288/2529 [01:36<00:53, 23.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1292/2529 [01:36<00:48, 25.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████     | 1295/2529 [01:36<00:47, 26.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████▏    | 1298/2529 [01:36<00:46, 26.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  51%|█████▏    | 1301/2529 [01:36<00:57, 21.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1304/2529 [01:36<01:00, 20.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1307/2529 [01:37<01:06, 18.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1310/2529 [01:37<01:00, 20.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1313/2529 [01:37<00:55, 22.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1316/2529 [01:37<00:52, 23.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1319/2529 [01:37<00:58, 20.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1322/2529 [01:37<00:58, 20.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  52%|█████▏    | 1325/2529 [01:37<00:56, 21.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1328/2529 [01:38<00:56, 21.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1331/2529 [01:38<00:57, 20.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1334/2529 [01:38<01:07, 17.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1336/2529 [01:38<01:06, 17.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1340/2529 [01:38<00:54, 21.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1343/2529 [01:38<00:53, 21.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1346/2529 [01:38<00:54, 21.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1349/2529 [01:39<01:15, 15.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1351/2529 [01:39<01:33, 12.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  53%|█████▎    | 1353/2529 [01:39<01:32, 12.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▎    | 1355/2529 [01:39<01:33, 12.61it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▎    | 1357/2529 [01:40<01:29, 13.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1360/2529 [01:40<01:14, 15.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1362/2529 [01:40<01:34, 12.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1364/2529 [01:40<01:34, 12.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1366/2529 [01:40<01:41, 11.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1368/2529 [01:40<01:46, 10.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1370/2529 [01:41<01:48, 10.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1372/2529 [01:41<01:51, 10.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1374/2529 [01:41<01:42, 11.23it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1376/2529 [01:41<01:35, 12.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  54%|█████▍    | 1378/2529 [01:41<01:26, 13.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1380/2529 [01:41<01:27, 13.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1382/2529 [01:42<01:34, 12.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1385/2529 [01:42<01:14, 15.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1388/2529 [01:42<01:05, 17.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▍    | 1390/2529 [01:42<01:24, 13.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1392/2529 [01:42<01:31, 12.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1394/2529 [01:43<01:35, 11.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1396/2529 [01:43<01:40, 11.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1398/2529 [01:43<01:36, 11.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1401/2529 [01:43<01:22, 13.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  55%|█████▌    | 1403/2529 [01:43<01:18, 14.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1405/2529 [01:43<01:13, 15.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1407/2529 [01:43<01:25, 13.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1409/2529 [01:44<01:27, 12.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1411/2529 [01:44<01:26, 12.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1413/2529 [01:44<01:19, 14.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1415/2529 [01:44<01:14, 14.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1418/2529 [01:44<01:04, 17.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▌    | 1421/2529 [01:44<01:00, 18.31it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▋    | 1423/2529 [01:44<00:59, 18.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▋    | 1425/2529 [01:45<01:03, 17.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  56%|█████▋    | 1427/2529 [01:45<01:03, 17.49it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1429/2529 [01:45<01:00, 18.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1432/2529 [01:45<00:57, 19.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1435/2529 [01:45<00:54, 19.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1438/2529 [01:45<00:54, 19.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1440/2529 [01:45<01:07, 16.23it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1443/2529 [01:46<01:01, 17.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1446/2529 [01:46<00:55, 19.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1449/2529 [01:46<00:53, 20.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  57%|█████▋    | 1452/2529 [01:46<01:04, 16.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1455/2529 [01:46<00:57, 18.61it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1458/2529 [01:46<00:52, 20.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1461/2529 [01:46<00:51, 20.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1464/2529 [01:47<00:54, 19.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1467/2529 [01:47<00:48, 21.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1470/2529 [01:47<00:47, 22.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1473/2529 [01:47<00:46, 22.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1476/2529 [01:47<00:42, 24.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  58%|█████▊    | 1479/2529 [01:47<00:47, 22.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▊    | 1482/2529 [01:47<00:46, 22.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▊    | 1485/2529 [01:47<00:46, 22.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1488/2529 [01:48<00:48, 21.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1491/2529 [01:48<00:51, 20.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1494/2529 [01:48<00:47, 22.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1498/2529 [01:48<00:41, 24.71it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  59%|█████▉    | 1501/2529 [01:48<00:44, 23.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1505/2529 [01:48<00:50, 20.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1508/2529 [01:49<00:50, 20.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1512/2529 [01:49<00:47, 21.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|█████▉    | 1515/2529 [01:49<00:48, 21.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|██████    | 1518/2529 [01:49<00:48, 20.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|██████    | 1522/2529 [01:49<00:42, 23.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|██████    | 1525/2529 [01:49<00:46, 21.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  60%|██████    | 1528/2529 [01:49<00:43, 23.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1531/2529 [01:50<00:43, 23.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1534/2529 [01:50<00:46, 21.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1537/2529 [01:50<00:46, 21.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1540/2529 [01:50<00:46, 21.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1543/2529 [01:50<00:51, 19.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1546/2529 [01:50<00:48, 20.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████    | 1549/2529 [01:50<00:45, 21.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  61%|██████▏   | 1553/2529 [01:51<00:41, 23.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1556/2529 [01:51<00:40, 24.23it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1559/2529 [01:51<00:38, 25.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1562/2529 [01:51<00:38, 25.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1565/2529 [01:51<00:41, 23.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1568/2529 [01:51<00:41, 22.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1571/2529 [01:51<00:42, 22.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1575/2529 [01:51<00:38, 24.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  62%|██████▏   | 1578/2529 [01:52<00:37, 25.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1581/2529 [01:52<00:47, 19.76it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1584/2529 [01:52<00:52, 18.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1587/2529 [01:52<00:48, 19.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1590/2529 [01:52<00:49, 18.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1593/2529 [01:53<00:55, 16.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1595/2529 [01:53<00:54, 16.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1597/2529 [01:53<00:54, 17.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1601/2529 [01:53<00:47, 19.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  63%|██████▎   | 1604/2529 [01:53<00:54, 17.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1606/2529 [01:53<00:58, 15.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1608/2529 [01:54<01:04, 14.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1610/2529 [01:54<01:11, 12.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▎   | 1612/2529 [01:54<01:18, 11.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1614/2529 [01:54<01:28, 10.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1616/2529 [01:54<01:29, 10.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1618/2529 [01:55<01:33,  9.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1620/2529 [01:55<01:35,  9.51it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1621/2529 [01:55<01:38,  9.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1622/2529 [01:55<01:38,  9.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1624/2529 [01:55<01:36,  9.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1625/2529 [01:55<01:36,  9.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1628/2529 [01:55<01:08, 13.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  64%|██████▍   | 1631/2529 [01:56<00:58, 15.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1633/2529 [01:56<00:55, 16.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1635/2529 [01:56<00:57, 15.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1637/2529 [01:56<00:55, 16.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1639/2529 [01:56<00:52, 16.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▍   | 1642/2529 [01:56<00:49, 17.76it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1644/2529 [01:56<00:48, 18.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1646/2529 [01:56<00:49, 17.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1648/2529 [01:57<01:03, 13.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1650/2529 [01:57<01:07, 13.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1652/2529 [01:57<01:09, 12.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1654/2529 [01:57<01:02, 14.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  65%|██████▌   | 1656/2529 [01:57<01:11, 12.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1659/2529 [01:57<00:56, 15.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1661/2529 [01:58<00:55, 15.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1663/2529 [01:58<00:57, 14.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1665/2529 [01:58<00:58, 14.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1668/2529 [01:58<00:51, 16.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1670/2529 [01:58<00:49, 17.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1672/2529 [01:58<00:48, 17.79it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▌   | 1675/2529 [01:58<00:43, 19.59it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▋   | 1678/2529 [01:58<00:39, 21.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  66%|██████▋   | 1681/2529 [01:59<00:43, 19.49it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1684/2529 [01:59<00:45, 18.51it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1686/2529 [01:59<00:51, 16.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1689/2529 [01:59<00:46, 18.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1691/2529 [01:59<00:46, 18.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1693/2529 [01:59<00:47, 17.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1696/2529 [02:00<00:42, 19.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1699/2529 [02:00<00:49, 16.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1701/2529 [02:00<00:53, 15.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1703/2529 [02:00<01:04, 12.91it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  67%|██████▋   | 1706/2529 [02:00<01:01, 13.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1708/2529 [02:01<01:02, 13.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1711/2529 [02:01<00:58, 14.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1713/2529 [02:01<01:01, 13.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1715/2529 [02:01<01:02, 12.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1717/2529 [02:01<01:06, 12.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1719/2529 [02:01<00:58, 13.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1722/2529 [02:01<00:51, 15.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1724/2529 [02:02<00:49, 16.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1726/2529 [02:02<00:57, 13.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1726/2529 [02:34<00:57, 13.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1728/2529 [02:34<1:01:05,  4.58s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1729/2529 [02:34<51:03,  3.83s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  68%|██████▊   | 1731/2529 [02:34<34:46,  2.62s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▊   | 1733/2529 [02:34<23:57,  1.81s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▊   | 1736/2529 [02:34<14:31,  1.10s/it]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▊   | 1738/2529 [02:35<10:39,  1.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1740/2529 [02:35<07:54,  1.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1742/2529 [02:35<05:52,  2.23it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1745/2529 [02:35<03:50,  3.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1748/2529 [02:35<02:40,  4.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1751/2529 [02:35<01:58,  6.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1753/2529 [02:35<01:39,  7.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  69%|██████▉   | 1755/2529 [02:36<01:24,  9.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1758/2529 [02:36<01:05, 11.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1762/2529 [02:36<00:48, 15.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1766/2529 [02:36<00:39, 19.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|██████▉   | 1769/2529 [02:36<00:38, 19.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|███████   | 1772/2529 [02:36<00:39, 18.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|███████   | 1775/2529 [02:36<00:40, 18.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|███████   | 1778/2529 [02:37<00:42, 17.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  70%|███████   | 1782/2529 [02:37<00:35, 20.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1785/2529 [02:37<00:36, 20.56it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1788/2529 [02:37<00:42, 17.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1790/2529 [02:37<00:43, 16.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1793/2529 [02:37<00:37, 19.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1797/2529 [02:37<00:31, 23.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████   | 1800/2529 [02:38<00:32, 22.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████▏  | 1803/2529 [02:38<00:37, 19.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  71%|███████▏  | 1806/2529 [02:38<00:35, 20.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1809/2529 [02:38<00:40, 17.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1812/2529 [02:38<00:35, 20.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1815/2529 [02:38<00:33, 21.49it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1818/2529 [02:38<00:31, 22.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1821/2529 [02:39<00:31, 22.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1824/2529 [02:39<00:31, 22.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1827/2529 [02:39<00:32, 21.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  72%|███████▏  | 1830/2529 [02:39<00:32, 21.18it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1834/2529 [02:39<00:33, 20.89it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1837/2529 [02:39<00:37, 18.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1839/2529 [02:40<00:38, 17.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1841/2529 [02:40<00:40, 17.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1843/2529 [02:40<00:40, 16.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1845/2529 [02:40<00:47, 14.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1847/2529 [02:40<00:44, 15.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1850/2529 [02:40<00:40, 16.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1852/2529 [02:40<00:40, 16.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1855/2529 [02:41<00:37, 18.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  73%|███████▎  | 1858/2529 [02:41<00:34, 19.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▎  | 1861/2529 [02:41<00:32, 20.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▎  | 1864/2529 [02:41<00:32, 20.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1868/2529 [02:41<00:32, 20.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1871/2529 [02:41<00:32, 20.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1874/2529 [02:42<00:43, 15.17it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1876/2529 [02:42<00:43, 14.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1878/2529 [02:42<00:48, 13.50it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1880/2529 [02:42<00:44, 14.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  74%|███████▍  | 1882/2529 [02:42<00:43, 14.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1885/2529 [02:42<00:35, 18.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1887/2529 [02:42<00:34, 18.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1890/2529 [02:43<00:32, 19.53it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1893/2529 [02:43<00:33, 18.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▍  | 1895/2529 [02:43<00:35, 17.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1897/2529 [02:43<00:35, 17.95it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1900/2529 [02:43<00:33, 18.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1904/2529 [02:43<00:28, 22.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  75%|███████▌  | 1907/2529 [02:43<00:26, 23.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1910/2529 [02:44<00:31, 19.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1913/2529 [02:44<00:34, 17.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1916/2529 [02:44<00:33, 18.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1920/2529 [02:44<00:29, 20.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1923/2529 [02:44<00:28, 21.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▌  | 1926/2529 [02:44<00:27, 21.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▋  | 1929/2529 [02:45<00:29, 20.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  76%|███████▋  | 1933/2529 [02:45<00:25, 23.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1936/2529 [02:45<00:31, 18.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1939/2529 [02:45<00:32, 18.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1941/2529 [02:45<00:32, 17.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1944/2529 [02:45<00:31, 18.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1948/2529 [02:45<00:26, 21.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1951/2529 [02:46<00:28, 20.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1954/2529 [02:46<00:31, 18.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1956/2529 [02:46<00:33, 17.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  77%|███████▋  | 1959/2529 [02:46<00:30, 18.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1962/2529 [02:46<00:31, 17.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1964/2529 [02:46<00:32, 17.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1966/2529 [02:47<00:31, 17.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1968/2529 [02:47<00:32, 17.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1970/2529 [02:47<00:48, 11.63it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1972/2529 [02:47<00:55, 10.01it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1974/2529 [02:47<00:59,  9.41it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1976/2529 [02:48<00:57,  9.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1978/2529 [02:48<00:54, 10.08it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1980/2529 [02:48<00:54, 10.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1982/2529 [02:48<00:48, 11.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  78%|███████▊  | 1984/2529 [02:48<00:46, 11.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▊  | 1986/2529 [02:48<00:43, 12.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▊  | 1988/2529 [02:49<00:40, 13.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▊  | 1991/2529 [02:49<00:32, 16.38it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 1993/2529 [02:49<00:31, 17.12it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 1995/2529 [02:49<00:37, 14.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 1998/2529 [02:49<00:39, 13.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2000/2529 [02:49<00:36, 14.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2002/2529 [02:49<00:35, 15.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2005/2529 [02:50<00:30, 17.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  79%|███████▉  | 2008/2529 [02:50<00:26, 19.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2011/2529 [02:50<00:24, 21.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2014/2529 [02:50<00:22, 22.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2017/2529 [02:50<00:28, 17.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2020/2529 [02:50<00:33, 15.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|███████▉  | 2022/2529 [02:51<00:33, 15.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|████████  | 2025/2529 [02:51<00:30, 16.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|████████  | 2028/2529 [02:51<00:26, 19.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|████████  | 2031/2529 [02:51<00:27, 18.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  80%|████████  | 2033/2529 [02:51<00:31, 15.73it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2036/2529 [02:51<00:31, 15.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2039/2529 [02:52<00:31, 15.66it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2041/2529 [02:52<00:30, 16.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2044/2529 [02:52<00:26, 18.64it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2047/2529 [02:52<00:22, 21.06it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2050/2529 [02:52<00:23, 20.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████  | 2053/2529 [02:52<00:22, 20.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████▏ | 2056/2529 [02:52<00:21, 22.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  81%|████████▏ | 2059/2529 [02:52<00:19, 23.92it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2062/2529 [02:53<00:21, 21.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2065/2529 [02:53<00:21, 21.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2068/2529 [02:53<00:23, 19.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2071/2529 [02:53<00:23, 19.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2074/2529 [02:53<00:24, 18.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2076/2529 [02:53<00:26, 17.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2078/2529 [02:54<00:30, 14.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2081/2529 [02:54<00:25, 17.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2083/2529 [02:54<00:32, 13.55it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  82%|████████▏ | 2085/2529 [02:54<00:30, 14.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2088/2529 [02:54<00:25, 17.50it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2091/2529 [02:54<00:30, 14.21it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2093/2529 [02:55<00:29, 14.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2095/2529 [02:55<00:30, 14.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2098/2529 [02:55<00:26, 16.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2101/2529 [02:55<00:25, 16.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2103/2529 [02:55<00:26, 16.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2106/2529 [02:55<00:23, 17.90it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2108/2529 [02:55<00:23, 17.93it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  83%|████████▎ | 2110/2529 [02:56<00:24, 17.43it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▎ | 2114/2529 [02:56<00:19, 21.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▎ | 2117/2529 [02:56<00:26, 15.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2119/2529 [02:56<00:27, 14.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2122/2529 [02:56<00:23, 17.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2124/2529 [02:56<00:23, 17.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2126/2529 [02:56<00:23, 17.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2129/2529 [02:57<00:21, 18.88it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2132/2529 [02:57<00:18, 21.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  84%|████████▍ | 2135/2529 [02:57<00:18, 21.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2138/2529 [02:57<00:17, 22.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2141/2529 [02:57<00:18, 21.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2144/2529 [02:57<00:18, 20.47it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▍ | 2147/2529 [02:57<00:17, 21.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2151/2529 [02:58<00:15, 24.67it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2154/2529 [02:58<00:14, 25.44it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2157/2529 [02:58<00:15, 24.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  85%|████████▌ | 2161/2529 [02:58<00:13, 26.96it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2164/2529 [02:58<00:13, 26.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2167/2529 [02:58<00:15, 23.91it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2171/2529 [02:58<00:14, 24.31it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2174/2529 [02:58<00:15, 23.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2177/2529 [02:59<00:16, 21.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▌ | 2180/2529 [02:59<00:15, 22.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▋ | 2184/2529 [02:59<00:13, 24.74it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  86%|████████▋ | 2187/2529 [02:59<00:14, 23.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2190/2529 [02:59<00:14, 23.68it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2194/2529 [02:59<00:13, 24.54it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2197/2529 [03:00<00:15, 21.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2201/2529 [03:00<00:14, 23.13it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2204/2529 [03:00<00:13, 23.51it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2207/2529 [03:00<00:14, 21.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  87%|████████▋ | 2210/2529 [03:00<00:14, 21.32it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2214/2529 [03:00<00:12, 24.45it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2217/2529 [03:00<00:12, 25.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2221/2529 [03:00<00:11, 27.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2224/2529 [03:01<00:11, 27.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2227/2529 [03:01<00:12, 23.40it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2230/2529 [03:01<00:14, 21.26it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2233/2529 [03:01<00:13, 22.56it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  88%|████████▊ | 2236/2529 [03:01<00:16, 17.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▊ | 2240/2529 [03:01<00:15, 18.99it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▊ | 2243/2529 [03:02<00:15, 18.84it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2246/2529 [03:02<00:13, 20.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2249/2529 [03:02<00:15, 18.33it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2252/2529 [03:02<00:13, 20.10it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2256/2529 [03:02<00:11, 23.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2260/2529 [03:02<00:12, 22.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  89%|████████▉ | 2263/2529 [03:03<00:11, 22.52it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2266/2529 [03:03<00:11, 23.57it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2270/2529 [03:03<00:10, 24.07it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2273/2529 [03:03<00:12, 20.39it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|████████▉ | 2276/2529 [03:03<00:11, 21.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|█████████ | 2279/2529 [03:03<00:12, 20.29it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|█████████ | 2283/2529 [03:03<00:10, 23.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  90%|█████████ | 2286/2529 [03:04<00:10, 23.87it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2289/2529 [03:04<00:10, 23.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2292/2529 [03:04<00:10, 23.02it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2295/2529 [03:04<00:09, 23.62it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2299/2529 [03:04<00:08, 26.14it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2302/2529 [03:04<00:09, 23.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████ | 2305/2529 [03:04<00:10, 21.77it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████▏| 2308/2529 [03:05<00:10, 21.00it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████▏| 2311/2529 [03:05<00:09, 21.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  91%|█████████▏| 2314/2529 [03:05<00:11, 18.37it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2316/2529 [03:05<00:11, 18.19it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2320/2529 [03:05<00:09, 21.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2323/2529 [03:05<00:09, 22.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2326/2529 [03:05<00:09, 22.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2329/2529 [03:06<00:09, 22.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2332/2529 [03:06<00:08, 23.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2336/2529 [03:06<00:07, 25.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  92%|█████████▏| 2339/2529 [03:06<00:08, 23.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2342/2529 [03:06<00:07, 23.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2345/2529 [03:06<00:07, 23.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2348/2529 [03:06<00:07, 23.16it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2351/2529 [03:06<00:08, 20.70it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2354/2529 [03:07<00:09, 19.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2358/2529 [03:07<00:07, 21.46it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  93%|█████████▎| 2361/2529 [03:07<00:07, 22.83it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▎| 2365/2529 [03:07<00:06, 25.35it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▎| 2368/2529 [03:07<00:07, 22.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2371/2529 [03:07<00:06, 23.42it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2374/2529 [03:07<00:07, 21.25it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2377/2529 [03:08<00:07, 21.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2380/2529 [03:08<00:06, 22.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2383/2529 [03:08<00:06, 23.04it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  94%|█████████▍| 2387/2529 [03:08<00:05, 25.78it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2391/2529 [03:08<00:05, 27.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2394/2529 [03:08<00:05, 24.76it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2397/2529 [03:08<00:05, 24.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▍| 2400/2529 [03:09<00:05, 25.60it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2404/2529 [03:09<00:04, 28.03it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2407/2529 [03:09<00:05, 21.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2411/2529 [03:09<00:05, 23.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  95%|█████████▌| 2414/2529 [03:09<00:04, 23.98it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2417/2529 [03:09<00:04, 25.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2420/2529 [03:09<00:04, 25.24it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2424/2529 [03:09<00:04, 25.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2427/2529 [03:10<00:03, 26.65it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2430/2529 [03:10<00:03, 26.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▌| 2433/2529 [03:10<00:04, 22.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▋| 2436/2529 [03:10<00:04, 22.27it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  96%|█████████▋| 2439/2529 [03:10<00:04, 21.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2443/2529 [03:10<00:03, 24.94it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2446/2529 [03:10<00:03, 24.75it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2449/2529 [03:11<00:03, 24.82it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2452/2529 [03:11<00:03, 25.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2455/2529 [03:11<00:03, 20.58it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2459/2529 [03:11<00:03, 23.20it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2462/2529 [03:11<00:02, 22.72it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  97%|█████████▋| 2465/2529 [03:11<00:02, 24.11it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2468/2529 [03:11<00:02, 22.48it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2471/2529 [03:11<00:02, 24.09it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2474/2529 [03:12<00:02, 25.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2477/2529 [03:12<00:02, 24.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2480/2529 [03:12<00:02, 24.34it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2484/2529 [03:12<00:01, 26.61it/s]

Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2487/2529 [03:12<00:01, 27.36it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  98%|█████████▊| 2490/2529 [03:12<00:01, 27.97it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▊| 2494/2529 [03:12<00:01, 30.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2498/2529 [03:13<00:01, 25.28it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2501/2529 [03:13<00:01, 21.41it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2504/2529 [03:13<00:01, 21.22it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2507/2529 [03:13<00:01, 21.81it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2510/2529 [03:13<00:00, 22.05it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g:  99%|█████████▉| 2514/2529 [03:13<00:00, 22.30it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2517/2529 [03:13<00:00, 23.80it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2520/2529 [03:14<00:00, 23.86it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2524/2529 [03:14<00:00, 26.15it/s]
Processing: Top 10 region-to-gene links per gene, negative r2g: 100%|█████████▉| 2527/2529 [03:14<00:00, 25.32it/s]
 36%|███▌      | 5/14 [11:53<22:06, 147.37s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 2/2529 [00:00<02:29, 16.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 4/2529 [00:00<02:28, 17.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 7/2529 [00:00<02:18, 18.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 9/2529 [00:00<02:18, 18.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   0%|          | 11/2529 [00:00<02:17, 18.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 13/2529 [00:00<02:30, 16.76it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 15/2529 [00:00<02:28, 16.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 17/2529 [00:00<02:24, 17.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 19/2529 [00:01<02:45, 15.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 21/2529 [00:01<02:54, 14.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 23/2529 [00:01<02:59, 13.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 25/2529 [00:01<02:46, 14.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 27/2529 [00:01<02:36, 15.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 29/2529 [00:01<02:54, 14.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|          | 31/2529 [00:02<03:05, 13.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|▏         | 33/2529 [00:02<03:10, 13.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   1%|▏         | 36/2529 [00:02<02:45, 15.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 38/2529 [00:02<02:54, 14.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 40/2529 [00:02<02:59, 13.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 42/2529 [00:02<02:47, 14.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 44/2529 [00:02<02:37, 15.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 46/2529 [00:02<02:31, 16.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 48/2529 [00:03<03:01, 13.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 50/2529 [00:03<02:57, 13.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 52/2529 [00:03<02:52, 14.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 54/2529 [00:03<02:46, 14.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 57/2529 [00:03<02:27, 16.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 60/2529 [00:03<02:10, 18.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   2%|▏         | 63/2529 [00:03<02:04, 19.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 66/2529 [00:04<02:05, 19.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 68/2529 [00:04<02:06, 19.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 70/2529 [00:04<02:15, 18.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 72/2529 [00:04<02:36, 15.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 74/2529 [00:04<02:49, 14.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 76/2529 [00:04<03:04, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 78/2529 [00:04<02:52, 14.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 80/2529 [00:05<02:38, 15.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 82/2529 [00:05<02:30, 16.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 85/2529 [00:05<02:33, 15.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   3%|▎         | 87/2529 [00:05<02:38, 15.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▎         | 89/2529 [00:05<02:44, 14.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▎         | 91/2529 [00:05<02:38, 15.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▎         | 94/2529 [00:05<02:20, 17.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 96/2529 [00:06<02:26, 16.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 98/2529 [00:06<02:27, 16.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 100/2529 [00:06<02:57, 13.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 102/2529 [00:06<02:53, 13.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 104/2529 [00:06<02:46, 14.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 107/2529 [00:06<02:19, 17.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 109/2529 [00:06<02:28, 16.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 111/2529 [00:07<02:21, 17.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   4%|▍         | 113/2529 [00:07<02:23, 16.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 115/2529 [00:07<03:06, 12.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 117/2529 [00:07<03:44, 10.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 119/2529 [00:07<03:54, 10.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 121/2529 [00:08<04:05,  9.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 123/2529 [00:08<03:52, 10.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▍         | 125/2529 [00:08<03:47, 10.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 127/2529 [00:08<03:57, 10.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 129/2529 [00:08<04:04,  9.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 131/2529 [00:09<04:09,  9.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 132/2529 [00:09<04:22,  9.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 133/2529 [00:09<04:32,  8.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 134/2529 [00:09<04:31,  8.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 135/2529 [00:09<04:31,  8.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 136/2529 [00:09<04:36,  8.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 137/2529 [00:09<04:50,  8.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 138/2529 [00:09<04:47,  8.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   5%|▌         | 139/2529 [00:10<04:46,  8.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 141/2529 [00:10<03:54, 10.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 143/2529 [00:10<03:38, 10.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 145/2529 [00:10<03:53, 10.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 147/2529 [00:10<03:42, 10.71it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 149/2529 [00:10<03:41, 10.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 152/2529 [00:11<02:56, 13.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 154/2529 [00:11<02:48, 14.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 156/2529 [00:11<03:40, 10.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▌         | 158/2529 [00:11<03:58,  9.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▋         | 160/2529 [00:12<04:10,  9.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▋         | 162/2529 [00:12<04:20,  9.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   6%|▋         | 163/2529 [00:12<04:22,  9.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 165/2529 [00:12<03:51, 10.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 167/2529 [00:12<03:33, 11.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 169/2529 [00:12<03:44, 10.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 171/2529 [00:13<03:39, 10.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 173/2529 [00:13<03:50, 10.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 175/2529 [00:13<03:53, 10.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 177/2529 [00:13<03:40, 10.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 179/2529 [00:13<03:18, 11.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 181/2529 [00:13<03:13, 12.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 183/2529 [00:14<02:52, 13.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 185/2529 [00:14<02:46, 14.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 187/2529 [00:14<02:37, 14.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   7%|▋         | 189/2529 [00:14<02:35, 15.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 191/2529 [00:14<02:53, 13.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 193/2529 [00:14<02:48, 13.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 195/2529 [00:14<02:38, 14.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 197/2529 [00:14<02:35, 15.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 199/2529 [00:15<02:31, 15.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 201/2529 [00:15<02:25, 16.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 203/2529 [00:15<02:41, 14.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 205/2529 [00:15<02:56, 13.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 207/2529 [00:15<02:46, 13.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 209/2529 [00:15<02:36, 14.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 211/2529 [00:15<02:27, 15.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   8%|▊         | 213/2529 [00:16<02:45, 13.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▊         | 215/2529 [00:16<02:49, 13.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▊         | 217/2529 [00:16<02:39, 14.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▊         | 220/2529 [00:16<02:17, 16.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 222/2529 [00:16<02:14, 17.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 224/2529 [00:16<02:16, 16.92it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 226/2529 [00:16<02:33, 14.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 229/2529 [00:17<02:18, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 231/2529 [00:17<02:12, 17.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 233/2529 [00:17<02:13, 17.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 236/2529 [00:17<02:03, 18.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 238/2529 [00:17<02:01, 18.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:   9%|▉         | 240/2529 [00:17<02:18, 16.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 242/2529 [00:17<02:17, 16.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 244/2529 [00:17<02:10, 17.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 246/2529 [00:18<02:17, 16.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 248/2529 [00:18<02:29, 15.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 250/2529 [00:18<02:37, 14.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|▉         | 252/2529 [00:18<02:26, 15.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|█         | 255/2529 [00:18<02:10, 17.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|█         | 257/2529 [00:18<02:12, 17.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|█         | 259/2529 [00:18<02:12, 17.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|█         | 262/2529 [00:19<02:32, 14.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  10%|█         | 264/2529 [00:19<02:27, 15.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 266/2529 [00:19<02:26, 15.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 269/2529 [00:19<02:07, 17.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 272/2529 [00:19<02:13, 16.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 274/2529 [00:19<02:15, 16.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 276/2529 [00:19<02:13, 16.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 279/2529 [00:19<01:59, 18.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 281/2529 [00:20<02:05, 17.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█         | 283/2529 [00:20<02:11, 17.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 285/2529 [00:20<02:07, 17.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 288/2529 [00:20<02:03, 18.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 290/2529 [00:20<02:18, 16.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 292/2529 [00:20<02:16, 16.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 294/2529 [00:20<02:16, 16.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 296/2529 [00:21<02:17, 16.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 298/2529 [00:21<02:36, 14.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 300/2529 [00:21<02:30, 14.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 302/2529 [00:21<02:23, 15.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 304/2529 [00:21<02:20, 15.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 306/2529 [00:21<02:12, 16.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 309/2529 [00:21<01:59, 18.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 311/2529 [00:21<01:59, 18.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 314/2529 [00:22<01:52, 19.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 316/2529 [00:22<01:53, 19.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 319/2529 [00:22<01:51, 19.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 321/2529 [00:22<01:56, 18.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 323/2529 [00:22<02:05, 17.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 325/2529 [00:22<02:06, 17.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 327/2529 [00:22<02:10, 16.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 330/2529 [00:22<02:00, 18.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 332/2529 [00:23<02:35, 14.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 334/2529 [00:23<02:42, 13.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 336/2529 [00:23<02:34, 14.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 338/2529 [00:23<02:25, 15.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 340/2529 [00:23<02:26, 14.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 342/2529 [00:23<02:27, 14.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 344/2529 [00:24<02:47, 13.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 346/2529 [00:24<02:37, 13.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 348/2529 [00:24<02:37, 13.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 351/2529 [00:24<02:10, 16.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 353/2529 [00:24<02:15, 16.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 355/2529 [00:24<02:41, 13.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 357/2529 [00:25<02:59, 12.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 359/2529 [00:25<03:21, 10.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 361/2529 [00:25<03:46,  9.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 363/2529 [00:25<04:00,  9.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 364/2529 [00:25<04:00,  9.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 365/2529 [00:26<04:16,  8.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 366/2529 [00:26<04:34,  7.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 367/2529 [00:26<04:49,  7.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 368/2529 [00:26<04:44,  7.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 369/2529 [00:26<04:30,  7.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 370/2529 [00:26<04:34,  7.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 371/2529 [00:26<04:47,  7.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 372/2529 [00:26<04:41,  7.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 373/2529 [00:27<04:30,  7.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 374/2529 [00:27<04:36,  7.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 375/2529 [00:27<04:38,  7.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 377/2529 [00:27<03:22, 10.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 379/2529 [00:27<02:47, 12.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 381/2529 [00:27<02:28, 14.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 383/2529 [00:27<02:40, 13.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 385/2529 [00:27<02:31, 14.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 387/2529 [00:28<02:23, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 389/2529 [00:28<02:20, 15.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 391/2529 [00:28<02:16, 15.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 393/2529 [00:28<02:18, 15.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 395/2529 [00:28<02:45, 12.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 397/2529 [00:28<03:24, 10.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 399/2529 [00:29<03:29, 10.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 401/2529 [00:29<03:13, 10.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 403/2529 [00:29<03:44,  9.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 405/2529 [00:29<03:22, 10.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 408/2529 [00:29<02:43, 12.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 410/2529 [00:30<02:47, 12.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 412/2529 [00:30<03:00, 11.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 414/2529 [00:30<02:46, 12.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 417/2529 [00:30<02:23, 14.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 419/2529 [00:30<02:31, 13.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 421/2529 [00:30<02:21, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 423/2529 [00:30<02:19, 15.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 426/2529 [00:31<02:01, 17.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 428/2529 [00:31<02:21, 14.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 430/2529 [00:31<02:18, 15.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 432/2529 [00:31<02:36, 13.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 434/2529 [00:31<02:37, 13.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 436/2529 [00:31<02:28, 14.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 438/2529 [00:31<02:27, 14.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 440/2529 [00:32<02:32, 13.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 442/2529 [00:32<02:24, 14.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 444/2529 [00:32<02:26, 14.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 446/2529 [00:32<02:30, 13.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 448/2529 [00:32<02:45, 12.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 450/2529 [00:33<03:17, 10.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 452/2529 [00:33<03:23, 10.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 454/2529 [00:33<03:06, 11.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 456/2529 [00:33<03:10, 10.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 458/2529 [00:33<03:05, 11.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 460/2529 [00:33<03:13, 10.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 462/2529 [00:34<02:46, 12.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 464/2529 [00:34<02:43, 12.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 466/2529 [00:34<02:39, 12.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 468/2529 [00:34<02:52, 11.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 470/2529 [00:34<03:10, 10.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 472/2529 [00:34<03:29,  9.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 474/2529 [00:35<03:09, 10.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 476/2529 [00:35<02:46, 12.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 478/2529 [00:35<02:47, 12.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 480/2529 [00:35<02:36, 13.08it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 482/2529 [00:35<02:54, 11.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 484/2529 [00:35<02:33, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 486/2529 [00:35<02:18, 14.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 489/2529 [00:36<01:56, 17.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 491/2529 [00:36<01:52, 18.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 493/2529 [00:36<01:57, 17.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 495/2529 [00:36<01:56, 17.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 497/2529 [00:36<01:52, 18.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 500/2529 [00:36<01:44, 19.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 503/2529 [00:36<01:48, 18.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 505/2529 [00:36<01:49, 18.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|██        | 507/2529 [00:37<02:04, 16.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|██        | 509/2529 [00:37<02:00, 16.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|██        | 511/2529 [00:37<02:13, 15.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|██        | 513/2529 [00:37<02:28, 13.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  20%|██        | 516/2529 [00:37<02:06, 15.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 519/2529 [00:37<01:51, 18.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 521/2529 [00:37<01:59, 16.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 523/2529 [00:38<02:01, 16.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 525/2529 [00:38<02:31, 13.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 528/2529 [00:38<02:08, 15.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 531/2529 [00:38<01:55, 17.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 534/2529 [00:38<01:43, 19.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██        | 537/2529 [00:38<01:53, 17.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 539/2529 [00:39<02:13, 14.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 541/2529 [00:39<02:12, 15.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 543/2529 [00:39<02:26, 13.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 545/2529 [00:39<02:26, 13.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 548/2529 [00:39<02:02, 16.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 551/2529 [00:39<01:55, 17.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 554/2529 [00:40<01:56, 17.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 556/2529 [00:40<01:52, 17.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 558/2529 [00:40<01:53, 17.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 560/2529 [00:40<01:59, 16.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 562/2529 [00:40<02:00, 16.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 565/2529 [00:40<01:46, 18.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 567/2529 [00:40<02:03, 15.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 569/2529 [00:40<01:59, 16.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 571/2529 [00:41<02:03, 15.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 573/2529 [00:41<02:05, 15.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 575/2529 [00:41<02:23, 13.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 577/2529 [00:41<02:31, 12.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 579/2529 [00:41<02:37, 12.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 581/2529 [00:41<02:23, 13.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 583/2529 [00:41<02:16, 14.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 585/2529 [00:42<02:16, 14.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 588/2529 [00:42<02:03, 15.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 590/2529 [00:42<01:58, 16.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 592/2529 [00:42<02:09, 14.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 594/2529 [00:42<02:00, 16.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▎       | 596/2529 [00:42<01:53, 16.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▎       | 598/2529 [00:42<02:08, 15.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▎       | 600/2529 [00:43<02:01, 15.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 602/2529 [00:43<02:09, 14.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 604/2529 [00:43<02:58, 10.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 606/2529 [00:43<02:57, 10.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 608/2529 [00:43<03:12,  9.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 610/2529 [00:44<02:52, 11.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 612/2529 [00:44<02:47, 11.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 615/2529 [00:44<02:27, 12.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 617/2529 [00:44<02:22, 13.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 620/2529 [00:44<02:08, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 622/2529 [00:44<02:11, 14.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 624/2529 [00:45<02:16, 14.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 626/2529 [00:45<02:11, 14.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 628/2529 [00:45<02:02, 15.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 631/2529 [00:45<01:48, 17.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 633/2529 [00:45<01:45, 17.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 636/2529 [00:45<01:42, 18.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 636/2529 [01:22<01:42, 18.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 637/2529 [01:22<2:53:04,  5.49s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 638/2529 [01:22<2:23:36,  4.56s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 640/2529 [01:22<1:36:38,  3.07s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 642/2529 [01:23<1:06:08,  2.10s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 644/2529 [01:23<45:47,  1.46s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 647/2529 [01:23<27:59,  1.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 649/2529 [01:23<20:38,  1.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 651/2529 [01:23<15:31,  2.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 653/2529 [01:23<11:29,  2.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 656/2529 [01:23<07:51,  3.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 658/2529 [01:24<06:30,  4.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 660/2529 [01:24<05:28,  5.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 663/2529 [01:24<04:01,  7.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 665/2529 [01:24<03:26,  9.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 667/2529 [01:24<03:00, 10.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 670/2529 [01:24<02:23, 12.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 672/2529 [01:24<02:22, 13.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 674/2529 [01:25<02:14, 13.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 676/2529 [01:25<02:09, 14.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 678/2529 [01:25<02:12, 13.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 680/2529 [01:25<02:13, 13.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 682/2529 [01:25<02:07, 14.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 684/2529 [01:25<02:09, 14.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 686/2529 [01:25<02:08, 14.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 688/2529 [01:25<02:05, 14.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 690/2529 [01:26<02:45, 11.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 692/2529 [01:26<03:31,  8.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 694/2529 [01:26<03:56,  7.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 696/2529 [01:27<03:41,  8.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 697/2529 [01:27<03:37,  8.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 698/2529 [01:27<03:32,  8.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 700/2529 [01:27<03:25,  8.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 701/2529 [01:27<03:26,  8.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 702/2529 [01:27<03:22,  9.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 704/2529 [01:27<02:57, 10.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 706/2529 [01:28<02:38, 11.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 708/2529 [01:28<02:26, 12.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 710/2529 [01:28<02:32, 11.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 712/2529 [01:28<02:25, 12.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 714/2529 [01:28<02:49, 10.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 716/2529 [01:28<03:03,  9.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 718/2529 [01:29<02:44, 11.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 720/2529 [01:29<02:36, 11.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 722/2529 [01:29<02:17, 13.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 724/2529 [01:29<02:12, 13.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 727/2529 [01:29<01:52, 15.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 729/2529 [01:29<01:51, 16.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 732/2529 [01:29<01:40, 17.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 734/2529 [01:30<02:12, 13.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 736/2529 [01:30<02:14, 13.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 738/2529 [01:30<02:46, 10.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 740/2529 [01:30<02:27, 12.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 742/2529 [01:30<02:15, 13.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 744/2529 [01:30<02:02, 14.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 746/2529 [01:31<02:08, 13.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 748/2529 [01:31<02:16, 13.09it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 750/2529 [01:31<02:25, 12.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 752/2529 [01:31<02:32, 11.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 754/2529 [01:31<02:21, 12.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 756/2529 [01:31<02:32, 11.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 758/2529 [01:32<02:22, 12.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|███       | 761/2529 [01:32<01:54, 15.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|███       | 763/2529 [01:32<01:48, 16.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|███       | 765/2529 [01:32<01:44, 16.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|███       | 767/2529 [01:32<02:06, 13.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  30%|███       | 770/2529 [01:32<01:47, 16.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 772/2529 [01:32<01:42, 17.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 775/2529 [01:33<01:36, 18.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 777/2529 [01:33<01:36, 18.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 779/2529 [01:33<01:44, 16.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 781/2529 [01:33<01:47, 16.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 783/2529 [01:33<01:55, 15.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 785/2529 [01:33<01:55, 15.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 787/2529 [01:33<02:11, 13.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███       | 789/2529 [01:34<02:11, 13.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 791/2529 [01:34<02:45, 10.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 793/2529 [01:34<02:22, 12.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 796/2529 [01:34<02:31, 11.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 798/2529 [01:34<02:38, 10.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 801/2529 [01:35<02:11, 13.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 803/2529 [01:35<02:07, 13.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 805/2529 [01:35<02:36, 10.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 807/2529 [01:35<02:53,  9.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 809/2529 [01:35<02:40, 10.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 811/2529 [01:36<02:23, 12.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 813/2529 [01:36<02:13, 12.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 815/2529 [01:36<02:18, 12.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 817/2529 [01:36<02:05, 13.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 819/2529 [01:36<02:06, 13.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 821/2529 [01:36<01:59, 14.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 824/2529 [01:36<01:43, 16.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 826/2529 [01:37<01:54, 14.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 828/2529 [01:37<02:35, 10.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 830/2529 [01:37<02:21, 12.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 833/2529 [01:37<01:58, 14.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 835/2529 [01:37<02:02, 13.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 837/2529 [01:37<02:02, 13.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 840/2529 [01:38<01:53, 14.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 843/2529 [01:38<01:45, 16.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 845/2529 [01:38<01:43, 16.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 847/2529 [01:38<01:42, 16.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▎      | 849/2529 [01:38<01:43, 16.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▎      | 851/2529 [01:38<01:47, 15.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▎      | 853/2529 [01:38<01:41, 16.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 856/2529 [01:38<01:33, 17.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 859/2529 [01:39<01:25, 19.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 861/2529 [01:39<01:26, 19.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 863/2529 [01:39<01:32, 18.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 866/2529 [01:39<01:24, 19.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 868/2529 [01:39<01:25, 19.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 871/2529 [01:39<01:22, 20.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 874/2529 [01:39<01:32, 17.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 877/2529 [01:40<01:26, 19.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 879/2529 [01:40<01:39, 16.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 881/2529 [01:40<01:36, 17.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 883/2529 [01:40<01:52, 14.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 886/2529 [01:40<01:40, 16.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 888/2529 [01:40<01:37, 16.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 891/2529 [01:40<01:25, 19.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 893/2529 [01:41<01:33, 17.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 895/2529 [01:41<01:32, 17.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 898/2529 [01:41<01:27, 18.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 900/2529 [01:41<01:37, 16.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 902/2529 [01:41<01:56, 13.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 904/2529 [01:41<01:50, 14.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 907/2529 [01:41<01:37, 16.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 909/2529 [01:42<01:41, 16.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 912/2529 [01:42<01:43, 15.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 915/2529 [01:42<01:36, 16.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 918/2529 [01:42<01:39, 16.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 920/2529 [01:42<01:37, 16.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 923/2529 [01:42<01:26, 18.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 926/2529 [01:42<01:20, 19.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 929/2529 [01:43<01:15, 21.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 932/2529 [01:43<01:19, 20.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 935/2529 [01:43<01:38, 16.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 937/2529 [01:43<01:42, 15.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 939/2529 [01:43<01:46, 14.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 941/2529 [01:44<01:58, 13.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 943/2529 [01:44<02:07, 12.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 946/2529 [01:44<01:46, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 948/2529 [01:44<01:41, 15.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 950/2529 [01:44<01:37, 16.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 953/2529 [01:44<01:42, 15.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 955/2529 [01:44<01:47, 14.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 957/2529 [01:45<01:41, 15.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 960/2529 [01:45<01:31, 17.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 963/2529 [01:45<01:23, 18.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 966/2529 [01:45<01:31, 17.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 968/2529 [01:45<01:31, 17.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 970/2529 [01:45<01:29, 17.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 973/2529 [01:45<01:24, 18.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▊      | 976/2529 [01:46<01:24, 18.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▊      | 978/2529 [01:46<01:40, 15.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 980/2529 [01:46<01:37, 15.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 983/2529 [01:46<01:39, 15.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 986/2529 [01:46<01:34, 16.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 988/2529 [01:46<01:33, 16.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 991/2529 [01:46<01:25, 17.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 993/2529 [01:47<01:29, 17.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 995/2529 [01:47<01:26, 17.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 998/2529 [01:47<01:25, 18.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1001/2529 [01:47<01:18, 19.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1003/2529 [01:47<01:21, 18.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1005/2529 [01:47<01:30, 16.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1008/2529 [01:48<01:39, 15.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1010/2529 [01:48<01:40, 15.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1012/2529 [01:48<01:35, 15.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1014/2529 [01:48<01:40, 15.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1016/2529 [01:48<02:00, 12.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1018/2529 [01:48<01:49, 13.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1021/2529 [01:48<01:33, 16.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  40%|████      | 1023/2529 [01:48<01:31, 16.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1026/2529 [01:49<01:35, 15.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1028/2529 [01:49<01:38, 15.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1031/2529 [01:49<01:27, 17.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1033/2529 [01:49<01:26, 17.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1036/2529 [01:49<01:18, 18.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1038/2529 [01:49<01:29, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████      | 1041/2529 [01:50<01:26, 17.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1044/2529 [01:50<01:26, 17.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1046/2529 [01:50<01:28, 16.84it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1048/2529 [01:50<01:25, 17.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1050/2529 [01:50<01:38, 15.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1052/2529 [01:50<01:43, 14.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1054/2529 [01:50<01:38, 14.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1057/2529 [01:51<01:30, 16.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1059/2529 [01:51<01:28, 16.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1062/2529 [01:51<01:18, 18.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1065/2529 [01:51<01:24, 17.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1067/2529 [01:51<01:24, 17.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1069/2529 [01:51<01:25, 17.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1072/2529 [01:51<01:18, 18.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1074/2529 [01:52<01:31, 15.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1076/2529 [01:52<01:29, 16.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1078/2529 [01:52<01:28, 16.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1080/2529 [01:52<01:31, 15.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1083/2529 [01:52<01:19, 18.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1086/2529 [01:52<01:14, 19.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1089/2529 [01:52<01:22, 17.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1092/2529 [01:53<01:17, 18.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1094/2529 [01:53<01:19, 18.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1096/2529 [01:53<01:18, 18.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1099/2529 [01:53<01:10, 20.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▎     | 1102/2529 [01:53<01:18, 18.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▎     | 1104/2529 [01:53<01:28, 16.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1107/2529 [01:53<01:23, 16.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1110/2529 [01:54<01:16, 18.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1112/2529 [01:54<01:16, 18.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1114/2529 [01:54<01:15, 18.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1116/2529 [01:54<01:16, 18.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1119/2529 [01:54<01:11, 19.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1121/2529 [01:54<01:13, 19.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1124/2529 [01:54<01:10, 19.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1126/2529 [01:54<01:13, 19.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1128/2529 [01:55<01:19, 17.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1130/2529 [01:55<01:33, 15.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1133/2529 [01:55<01:23, 16.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1135/2529 [01:55<01:28, 15.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1138/2529 [01:55<01:17, 17.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1141/2529 [01:55<01:15, 18.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1143/2529 [01:55<01:16, 18.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1145/2529 [01:55<01:14, 18.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1147/2529 [01:56<01:16, 18.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1150/2529 [01:56<01:19, 17.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1152/2529 [01:56<01:24, 16.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1155/2529 [01:56<01:17, 17.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1157/2529 [01:56<01:15, 18.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1159/2529 [01:56<01:21, 16.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1162/2529 [01:56<01:12, 18.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1164/2529 [01:57<01:20, 17.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1167/2529 [01:57<01:14, 18.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1169/2529 [01:57<01:13, 18.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1171/2529 [01:57<01:12, 18.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1173/2529 [01:57<01:14, 18.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1175/2529 [01:57<01:16, 17.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1178/2529 [01:57<01:09, 19.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1181/2529 [01:57<01:05, 20.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1184/2529 [01:58<01:07, 20.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1187/2529 [01:58<01:02, 21.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1190/2529 [01:58<01:12, 18.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1192/2529 [01:58<01:12, 18.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1194/2529 [01:58<01:20, 16.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1196/2529 [01:58<01:26, 15.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1198/2529 [01:58<01:28, 15.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1200/2529 [01:59<01:27, 15.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1202/2529 [01:59<01:26, 15.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1205/2529 [01:59<01:16, 17.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1207/2529 [01:59<01:20, 16.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1209/2529 [01:59<01:17, 17.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1211/2529 [01:59<01:19, 16.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1213/2529 [01:59<01:18, 16.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1216/2529 [02:00<01:15, 17.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1219/2529 [02:00<01:17, 16.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1222/2529 [02:00<01:14, 17.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1224/2529 [02:00<01:15, 17.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1226/2529 [02:00<01:14, 17.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1228/2529 [02:00<01:17, 16.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1230/2529 [02:00<01:15, 17.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1232/2529 [02:01<01:24, 15.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1235/2529 [02:01<01:14, 17.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1237/2529 [02:01<01:15, 17.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1239/2529 [02:01<01:14, 17.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1241/2529 [02:01<01:27, 14.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1243/2529 [02:01<01:43, 12.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1245/2529 [02:02<01:54, 11.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1247/2529 [02:02<01:48, 11.76it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1249/2529 [02:02<01:45, 12.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1251/2529 [02:02<01:35, 13.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1253/2529 [02:02<01:26, 14.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1255/2529 [02:02<01:37, 13.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1257/2529 [02:02<01:47, 11.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1259/2529 [02:03<01:46, 11.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1261/2529 [02:03<01:35, 13.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1263/2529 [02:03<01:27, 14.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1265/2529 [02:03<01:32, 13.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1267/2529 [02:03<01:34, 13.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1269/2529 [02:03<01:27, 14.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1271/2529 [02:03<01:21, 15.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1273/2529 [02:03<01:18, 16.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1275/2529 [02:04<01:40, 12.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1277/2529 [02:04<01:43, 12.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1279/2529 [02:04<01:37, 12.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1281/2529 [02:04<01:30, 13.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1283/2529 [02:04<01:23, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1286/2529 [02:04<01:14, 16.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1289/2529 [02:05<01:05, 19.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1292/2529 [02:05<01:02, 19.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1295/2529 [02:05<01:02, 19.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████▏    | 1298/2529 [02:05<01:01, 20.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  51%|█████▏    | 1301/2529 [02:05<01:15, 16.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1303/2529 [02:05<01:21, 15.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1305/2529 [02:06<01:25, 14.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1307/2529 [02:06<01:27, 13.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1309/2529 [02:06<01:20, 15.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1311/2529 [02:06<01:16, 15.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1314/2529 [02:06<01:07, 17.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1316/2529 [02:06<01:07, 17.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1318/2529 [02:06<01:12, 16.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1320/2529 [02:06<01:15, 15.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1322/2529 [02:07<01:20, 15.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1324/2529 [02:07<01:16, 15.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1326/2529 [02:07<01:18, 15.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1328/2529 [02:07<01:15, 16.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1330/2529 [02:07<01:13, 16.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1332/2529 [02:07<01:22, 14.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1334/2529 [02:07<01:32, 12.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1336/2529 [02:08<01:30, 13.26it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1339/2529 [02:08<01:14, 15.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1342/2529 [02:08<01:13, 16.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1344/2529 [02:08<01:10, 16.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1346/2529 [02:08<01:11, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1348/2529 [02:08<01:33, 12.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1350/2529 [02:09<01:54, 10.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1352/2529 [02:09<02:00,  9.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1354/2529 [02:09<02:03,  9.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1356/2529 [02:09<01:55, 10.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1358/2529 [02:09<01:52, 10.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1360/2529 [02:10<01:38, 11.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1362/2529 [02:10<02:03,  9.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1364/2529 [02:10<02:01,  9.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1366/2529 [02:10<02:09,  9.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1367/2529 [02:10<02:12,  8.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1368/2529 [02:11<02:15,  8.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1369/2529 [02:11<02:14,  8.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1370/2529 [02:11<02:18,  8.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1371/2529 [02:11<02:23,  8.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1372/2529 [02:11<02:21,  8.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1373/2529 [02:11<02:19,  8.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1375/2529 [02:11<01:53, 10.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1377/2529 [02:12<01:46, 10.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1379/2529 [02:12<01:53, 10.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1381/2529 [02:12<01:47, 10.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1383/2529 [02:12<01:47, 10.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1386/2529 [02:12<01:25, 13.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1388/2529 [02:12<01:21, 13.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1390/2529 [02:13<01:48, 10.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1392/2529 [02:13<01:56,  9.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1394/2529 [02:13<02:01,  9.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1396/2529 [02:13<02:06,  8.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1397/2529 [02:14<02:06,  8.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1399/2529 [02:14<01:51, 10.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1401/2529 [02:14<01:42, 10.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1403/2529 [02:14<01:38, 11.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1405/2529 [02:14<01:32, 12.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1407/2529 [02:14<01:47, 10.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1409/2529 [02:15<01:49, 10.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1411/2529 [02:15<01:49, 10.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1413/2529 [02:15<01:40, 11.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1415/2529 [02:15<01:35, 11.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1417/2529 [02:15<01:25, 13.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1419/2529 [02:15<01:22, 13.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1421/2529 [02:15<01:16, 14.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1423/2529 [02:16<01:16, 14.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1425/2529 [02:16<01:22, 13.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1427/2529 [02:16<01:21, 13.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1429/2529 [02:16<01:18, 13.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1431/2529 [02:16<01:16, 14.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1433/2529 [02:16<01:11, 15.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1435/2529 [02:16<01:12, 15.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1437/2529 [02:16<01:07, 16.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1439/2529 [02:17<01:22, 13.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1441/2529 [02:17<01:27, 12.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1443/2529 [02:17<01:21, 13.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1445/2529 [02:17<01:15, 14.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1447/2529 [02:17<01:10, 15.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1449/2529 [02:17<01:09, 15.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1451/2529 [02:18<01:26, 12.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1453/2529 [02:18<01:24, 12.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1456/2529 [02:18<01:10, 15.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1458/2529 [02:18<01:07, 15.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1460/2529 [02:18<01:06, 16.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1462/2529 [02:18<01:15, 14.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1464/2529 [02:18<01:09, 15.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1467/2529 [02:19<01:02, 16.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1469/2529 [02:19<01:02, 17.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1471/2529 [02:19<01:02, 16.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1473/2529 [02:19<01:00, 17.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1476/2529 [02:19<00:56, 18.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1478/2529 [02:19<00:57, 18.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1480/2529 [02:19<01:03, 16.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1482/2529 [02:19<01:04, 16.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1485/2529 [02:20<01:03, 16.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1487/2529 [02:20<01:08, 15.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1489/2529 [02:20<01:11, 14.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1491/2529 [02:20<01:08, 15.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1493/2529 [02:20<01:03, 16.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1496/2529 [02:20<00:57, 18.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1499/2529 [02:20<00:56, 18.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1501/2529 [02:21<00:57, 17.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1504/2529 [02:21<00:54, 18.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1506/2529 [02:21<01:09, 14.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1508/2529 [02:21<01:10, 14.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1511/2529 [02:21<01:01, 16.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1513/2529 [02:21<01:02, 16.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1515/2529 [02:21<01:07, 15.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1517/2529 [02:22<01:05, 15.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1519/2529 [02:22<01:03, 15.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1522/2529 [02:22<00:56, 17.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1524/2529 [02:22<00:59, 16.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1526/2529 [02:22<01:02, 15.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1529/2529 [02:22<00:56, 17.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1531/2529 [02:22<00:58, 17.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1533/2529 [02:23<01:04, 15.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1535/2529 [02:23<01:03, 15.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1537/2529 [02:23<01:02, 15.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1539/2529 [02:23<01:03, 15.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1541/2529 [02:23<01:10, 14.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1543/2529 [02:23<01:07, 14.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1545/2529 [02:23<01:04, 15.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1547/2529 [02:23<01:02, 15.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1549/2529 [02:24<00:58, 16.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████▏   | 1552/2529 [02:24<00:52, 18.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  61%|██████▏   | 1554/2529 [02:24<00:52, 18.59it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1556/2529 [02:24<00:52, 18.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1559/2529 [02:24<00:49, 19.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1561/2529 [02:24<00:50, 19.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1563/2529 [02:24<00:52, 18.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1565/2529 [02:24<00:56, 16.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1567/2529 [02:25<00:54, 17.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1569/2529 [02:25<01:01, 15.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1572/2529 [02:25<00:55, 17.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1575/2529 [02:25<00:51, 18.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1577/2529 [02:25<00:50, 18.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1580/2529 [02:25<00:58, 16.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1582/2529 [02:26<01:11, 13.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1584/2529 [02:26<01:08, 13.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1586/2529 [02:26<01:05, 14.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1588/2529 [02:26<01:01, 15.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1590/2529 [02:26<01:03, 14.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1592/2529 [02:26<01:14, 12.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1594/2529 [02:26<01:11, 13.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1596/2529 [02:27<01:12, 12.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1598/2529 [02:27<01:04, 14.33it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1601/2529 [02:27<01:00, 15.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1603/2529 [02:27<01:05, 14.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1605/2529 [02:27<01:14, 12.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1607/2529 [02:27<01:18, 11.76it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1609/2529 [02:28<01:30, 10.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1611/2529 [02:28<01:40,  9.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1612/2529 [02:28<01:41,  9.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1613/2529 [02:28<01:48,  8.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1614/2529 [02:28<01:56,  7.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1615/2529 [02:29<02:03,  7.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1617/2529 [02:29<01:57,  7.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1618/2529 [02:29<01:57,  7.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1619/2529 [02:29<01:56,  7.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1620/2529 [02:29<01:59,  7.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1621/2529 [02:29<02:05,  7.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1622/2529 [02:29<02:03,  7.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1623/2529 [02:30<01:59,  7.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1624/2529 [02:30<02:00,  7.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1625/2529 [02:30<02:00,  7.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1627/2529 [02:30<01:27, 10.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1629/2529 [02:30<01:15, 11.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1631/2529 [02:30<01:07, 13.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1633/2529 [02:30<01:05, 13.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1635/2529 [02:31<01:11, 12.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1637/2529 [02:31<01:09, 12.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1639/2529 [02:31<01:07, 13.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1641/2529 [02:31<01:03, 13.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1643/2529 [02:31<01:01, 14.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1645/2529 [02:31<01:01, 14.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1647/2529 [02:31<01:11, 12.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1649/2529 [02:32<01:26, 10.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1651/2529 [02:32<01:28,  9.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1653/2529 [02:32<01:21, 10.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1655/2529 [02:32<01:34,  9.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1657/2529 [02:33<01:24, 10.30it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1660/2529 [02:33<01:07, 12.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1662/2529 [02:33<01:09, 12.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1664/2529 [02:33<01:14, 11.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1666/2529 [02:33<01:13, 11.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1668/2529 [02:33<01:04, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1670/2529 [02:33<01:02, 13.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1672/2529 [02:34<01:01, 13.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1674/2529 [02:34<00:57, 14.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1676/2529 [02:34<00:56, 15.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1679/2529 [02:34<00:49, 17.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1681/2529 [02:34<00:57, 14.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1683/2529 [02:34<00:58, 14.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1685/2529 [02:34<01:04, 13.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1687/2529 [02:35<01:04, 13.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1689/2529 [02:35<01:00, 13.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1691/2529 [02:35<00:59, 13.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1693/2529 [02:35<01:01, 13.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1695/2529 [02:35<00:58, 14.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1697/2529 [02:35<00:58, 14.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1699/2529 [02:36<01:04, 12.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1701/2529 [02:36<01:10, 11.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1703/2529 [02:36<01:22,  9.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1706/2529 [02:36<01:17, 10.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1708/2529 [02:36<01:19, 10.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1711/2529 [02:37<01:13, 11.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1713/2529 [02:37<01:17, 10.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1715/2529 [02:37<01:19, 10.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1717/2529 [02:37<01:23,  9.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1719/2529 [02:37<01:14, 10.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1721/2529 [02:38<01:06, 12.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1723/2529 [02:38<01:02, 12.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1725/2529 [02:38<01:12, 11.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1727/2529 [02:38<01:13, 10.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1729/2529 [02:38<01:21,  9.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1731/2529 [02:39<01:18, 10.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1733/2529 [02:39<01:10, 11.22it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1735/2529 [02:39<01:02, 12.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1737/2529 [02:39<01:03, 12.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1739/2529 [02:39<00:59, 13.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1741/2529 [02:39<01:10, 11.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1743/2529 [02:39<01:03, 12.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1745/2529 [02:40<00:58, 13.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1747/2529 [02:40<00:53, 14.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1749/2529 [02:40<00:51, 15.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1751/2529 [02:40<00:50, 15.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1753/2529 [02:40<00:51, 15.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1755/2529 [02:40<00:52, 14.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1757/2529 [02:40<00:49, 15.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1760/2529 [02:41<00:44, 17.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1763/2529 [02:41<00:39, 19.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1766/2529 [02:41<00:38, 19.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1769/2529 [02:41<00:41, 18.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1771/2529 [02:41<00:46, 16.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1773/2529 [02:41<00:45, 16.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1775/2529 [02:41<00:50, 15.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1777/2529 [02:42<00:56, 13.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1780/2529 [02:42<00:47, 15.64it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1783/2529 [02:42<00:43, 17.23it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1785/2529 [02:42<00:46, 16.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1787/2529 [02:42<00:50, 14.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1789/2529 [02:42<01:01, 12.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1792/2529 [02:43<00:50, 14.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1794/2529 [02:43<00:47, 15.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1797/2529 [02:43<00:41, 17.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1800/2529 [02:43<00:42, 17.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1802/2529 [02:43<00:41, 17.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1804/2529 [02:43<00:49, 14.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1806/2529 [02:43<00:48, 14.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1808/2529 [02:44<00:53, 13.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1810/2529 [02:44<00:53, 13.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1813/2529 [02:44<00:44, 16.14it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1815/2529 [02:44<00:43, 16.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1817/2529 [02:44<00:41, 17.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1819/2529 [02:44<00:43, 16.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1821/2529 [02:44<00:41, 17.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1823/2529 [02:44<00:40, 17.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1825/2529 [02:45<00:40, 17.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1827/2529 [02:45<00:42, 16.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1829/2529 [02:45<00:45, 15.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1832/2529 [02:45<00:39, 17.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1834/2529 [02:45<00:44, 15.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1836/2529 [02:45<00:50, 13.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1838/2529 [02:45<00:49, 13.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1840/2529 [02:46<00:50, 13.68it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1842/2529 [02:46<00:57, 12.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1844/2529 [02:46<00:58, 11.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1846/2529 [02:46<01:00, 11.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1848/2529 [02:46<00:55, 12.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1850/2529 [02:46<00:51, 13.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1852/2529 [02:47<00:52, 13.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1854/2529 [02:47<00:48, 13.80it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1856/2529 [02:47<00:46, 14.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1858/2529 [02:47<00:43, 15.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1860/2529 [02:47<00:43, 15.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1862/2529 [02:47<00:40, 16.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1864/2529 [02:47<00:41, 15.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1867/2529 [02:47<00:36, 18.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1869/2529 [02:48<00:43, 15.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1871/2529 [02:48<00:43, 15.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1873/2529 [02:48<00:49, 13.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1875/2529 [02:48<01:00, 10.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1877/2529 [02:49<01:04, 10.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1879/2529 [02:49<01:01, 10.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1881/2529 [02:49<00:56, 11.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1883/2529 [02:49<00:54, 11.96it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1886/2529 [02:49<00:48, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1888/2529 [02:49<00:46, 13.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1891/2529 [02:49<00:42, 15.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1893/2529 [02:50<00:43, 14.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1895/2529 [02:50<00:45, 13.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1897/2529 [02:50<00:45, 13.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1899/2529 [02:50<00:43, 14.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1901/2529 [02:50<00:40, 15.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1904/2529 [02:50<00:36, 17.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1906/2529 [02:50<00:34, 17.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1909/2529 [02:51<00:33, 18.43it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1911/2529 [02:51<00:46, 13.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1913/2529 [02:51<00:46, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1915/2529 [02:51<00:43, 14.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1917/2529 [02:51<00:41, 14.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1920/2529 [02:51<00:38, 16.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1922/2529 [02:51<00:37, 16.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1924/2529 [02:52<00:36, 16.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1926/2529 [02:52<00:35, 17.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1928/2529 [02:52<00:39, 15.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▋  | 1931/2529 [02:52<00:35, 16.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  76%|███████▋  | 1934/2529 [02:52<00:36, 16.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1936/2529 [02:52<00:41, 14.24it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1938/2529 [02:53<00:44, 13.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1940/2529 [02:53<00:42, 13.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1942/2529 [02:53<00:39, 14.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1944/2529 [02:53<00:40, 14.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1947/2529 [02:53<00:34, 16.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1949/2529 [02:53<00:36, 15.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1951/2529 [02:53<00:36, 15.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1953/2529 [02:54<00:38, 14.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1955/2529 [02:54<00:42, 13.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1957/2529 [02:54<00:41, 13.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1959/2529 [02:54<00:39, 14.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1961/2529 [02:54<00:38, 14.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1963/2529 [02:54<00:41, 13.51it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1965/2529 [02:54<00:40, 13.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1967/2529 [02:55<00:42, 13.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1969/2529 [02:55<00:50, 11.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1971/2529 [02:55<01:05,  8.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1972/2529 [02:55<01:09,  8.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1973/2529 [02:56<01:15,  7.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1974/2529 [02:56<01:13,  7.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1975/2529 [02:56<01:13,  7.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1976/2529 [02:56<01:10,  7.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1977/2529 [02:56<01:08,  8.04it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1978/2529 [02:56<01:05,  8.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1979/2529 [02:56<01:07,  8.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1980/2529 [02:56<01:06,  8.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1981/2529 [02:56<01:05,  8.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1983/2529 [02:57<00:55,  9.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1985/2529 [02:57<00:48, 11.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1987/2529 [02:57<00:47, 11.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1989/2529 [02:57<00:47, 11.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1991/2529 [02:57<00:40, 13.13it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1993/2529 [02:57<00:39, 13.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1995/2529 [02:58<00:47, 11.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1997/2529 [02:58<00:42, 12.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1999/2529 [02:58<00:49, 10.76it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2001/2529 [02:58<00:49, 10.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2004/2529 [02:58<00:38, 13.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2006/2529 [02:58<00:37, 13.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2008/2529 [02:59<00:34, 15.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2010/2529 [02:59<00:34, 15.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2013/2529 [02:59<00:30, 17.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2016/2529 [02:59<00:27, 18.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2018/2529 [02:59<00:37, 13.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2020/2529 [02:59<00:47, 10.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2022/2529 [03:00<00:45, 11.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2024/2529 [03:00<00:40, 12.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2026/2529 [03:00<00:37, 13.47it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2029/2529 [03:00<00:36, 13.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2029/2529 [03:42<00:36, 13.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2031/2529 [03:42<46:44,  5.63s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2032/2529 [03:42<39:19,  4.75s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2034/2529 [03:42<27:08,  3.29s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2036/2529 [03:43<18:55,  2.30s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2038/2529 [03:43<13:14,  1.62s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2040/2529 [03:43<09:25,  1.16s/it]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2042/2529 [03:43<06:42,  1.21it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2045/2529 [03:43<04:10,  1.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2047/2529 [03:43<03:08,  2.56it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2049/2529 [03:43<02:21,  3.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2051/2529 [03:44<01:55,  4.15it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2054/2529 [03:44<01:18,  6.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2056/2529 [03:44<01:04,  7.35it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2059/2529 [03:44<00:49,  9.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2061/2529 [03:44<00:42, 10.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2063/2529 [03:44<00:43, 10.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2065/2529 [03:44<00:38, 12.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2067/2529 [03:45<00:38, 12.07it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2069/2529 [03:45<00:35, 12.89it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2071/2529 [03:45<00:34, 13.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2073/2529 [03:45<00:35, 12.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2075/2529 [03:45<00:35, 12.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2077/2529 [03:45<00:43, 10.29it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2079/2529 [03:45<00:37, 11.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2082/2529 [03:46<00:39, 11.18it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2084/2529 [03:46<00:41, 10.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2087/2529 [03:46<00:33, 13.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2089/2529 [03:46<00:31, 13.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2091/2529 [03:47<00:40, 10.77it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2093/2529 [03:47<00:38, 11.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2095/2529 [03:47<00:39, 11.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2097/2529 [03:47<00:35, 12.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2099/2529 [03:47<00:33, 13.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2101/2529 [03:47<00:32, 13.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2103/2529 [03:47<00:34, 12.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2105/2529 [03:48<00:30, 13.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2107/2529 [03:48<00:29, 14.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2109/2529 [03:48<00:31, 13.38it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2111/2529 [03:48<00:29, 14.30it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2113/2529 [03:48<00:26, 15.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2115/2529 [03:48<00:29, 14.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2117/2529 [03:49<00:36, 11.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2119/2529 [03:49<00:37, 10.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2121/2529 [03:49<00:33, 12.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2124/2529 [03:49<00:30, 13.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2126/2529 [03:49<00:30, 13.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2129/2529 [03:49<00:27, 14.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2132/2529 [03:50<00:24, 15.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2135/2529 [03:50<00:24, 16.26it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2137/2529 [03:50<00:24, 16.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2140/2529 [03:50<00:23, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2142/2529 [03:50<00:25, 15.03it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2144/2529 [03:50<00:24, 15.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2146/2529 [03:50<00:23, 16.06it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2149/2529 [03:51<00:21, 17.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2152/2529 [03:51<00:19, 19.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2154/2529 [03:51<00:19, 19.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2156/2529 [03:51<00:20, 17.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2159/2529 [03:51<00:18, 19.54it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2162/2529 [03:51<00:18, 19.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2164/2529 [03:51<00:18, 19.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2166/2529 [03:51<00:18, 19.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2168/2529 [03:52<00:20, 17.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2171/2529 [03:52<00:20, 17.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2173/2529 [03:52<00:22, 16.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2175/2529 [03:52<00:24, 14.62it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2177/2529 [03:52<00:22, 15.71it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2180/2529 [03:52<00:20, 16.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▋ | 2183/2529 [03:52<00:18, 18.39it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  86%|████████▋ | 2185/2529 [03:53<00:20, 16.71it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2188/2529 [03:53<00:19, 17.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2190/2529 [03:53<00:18, 18.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2193/2529 [03:53<00:17, 19.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2195/2529 [03:53<00:21, 15.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2197/2529 [03:53<00:20, 15.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2200/2529 [03:53<00:18, 17.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2202/2529 [03:54<00:19, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2205/2529 [03:54<00:20, 16.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2207/2529 [03:54<00:19, 16.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2210/2529 [03:54<00:19, 16.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2213/2529 [03:54<00:17, 17.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2216/2529 [03:54<00:16, 18.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2219/2529 [03:54<00:15, 19.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2222/2529 [03:55<00:14, 20.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2225/2529 [03:55<00:15, 20.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2228/2529 [03:55<00:18, 16.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2230/2529 [03:55<00:19, 15.42it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2233/2529 [03:55<00:17, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2235/2529 [03:56<00:22, 12.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2237/2529 [03:56<00:20, 13.93it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▊ | 2240/2529 [03:56<00:20, 14.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▊ | 2242/2529 [03:56<00:20, 13.92it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2245/2529 [03:56<00:18, 15.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2247/2529 [03:56<00:19, 14.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2249/2529 [03:57<00:20, 13.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2251/2529 [03:57<00:18, 15.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2254/2529 [03:57<00:16, 16.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2257/2529 [03:57<00:14, 18.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2260/2529 [03:57<00:16, 16.78it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2262/2529 [03:57<00:15, 16.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2265/2529 [03:57<00:14, 18.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2267/2529 [03:58<00:14, 17.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2270/2529 [03:58<00:14, 17.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2272/2529 [03:58<00:15, 17.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2274/2529 [03:58<00:17, 14.66it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2276/2529 [03:58<00:16, 15.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2278/2529 [03:58<00:17, 14.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2280/2529 [03:58<00:16, 15.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2283/2529 [03:59<00:14, 17.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2285/2529 [03:59<00:13, 17.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2288/2529 [03:59<00:13, 17.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2290/2529 [03:59<00:14, 16.90it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2292/2529 [03:59<00:13, 17.34it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2294/2529 [03:59<00:13, 17.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2297/2529 [03:59<00:12, 19.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2300/2529 [03:59<00:11, 20.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2303/2529 [04:00<00:12, 18.09it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2305/2529 [04:00<00:14, 15.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2307/2529 [04:00<00:14, 15.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2309/2529 [04:00<00:14, 15.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2311/2529 [04:00<00:13, 16.02it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2313/2529 [04:00<00:14, 15.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2315/2529 [04:01<00:17, 12.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2317/2529 [04:01<00:15, 13.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2320/2529 [04:01<00:13, 15.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2322/2529 [04:01<00:12, 16.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2325/2529 [04:01<00:12, 16.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2327/2529 [04:01<00:13, 15.40it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2330/2529 [04:01<00:11, 17.50it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2332/2529 [04:01<00:11, 17.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2335/2529 [04:02<00:10, 18.87it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2337/2529 [04:02<00:10, 18.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2339/2529 [04:02<00:10, 17.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2341/2529 [04:02<00:10, 17.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2343/2529 [04:02<00:10, 17.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2345/2529 [04:02<00:10, 17.45it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2347/2529 [04:02<00:10, 16.73it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2349/2529 [04:02<00:10, 17.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2351/2529 [04:03<00:12, 14.72it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2353/2529 [04:03<00:12, 13.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2355/2529 [04:03<00:11, 14.84it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2358/2529 [04:03<00:10, 16.10it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2360/2529 [04:03<00:10, 16.58it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2363/2529 [04:03<00:08, 18.79it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2366/2529 [04:04<00:09, 17.27it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2368/2529 [04:04<00:09, 17.32it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2370/2529 [04:04<00:09, 17.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2373/2529 [04:04<00:10, 15.55it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2375/2529 [04:04<00:09, 15.81it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2377/2529 [04:04<00:09, 15.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2379/2529 [04:04<00:09, 16.48it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2381/2529 [04:04<00:08, 16.44it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2384/2529 [04:05<00:07, 18.41it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2387/2529 [04:05<00:07, 19.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2390/2529 [04:05<00:06, 20.12it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2393/2529 [04:05<00:07, 17.91it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2396/2529 [04:05<00:07, 18.20it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2399/2529 [04:05<00:07, 18.49it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2402/2529 [04:05<00:06, 20.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2405/2529 [04:06<00:06, 18.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2407/2529 [04:06<00:07, 15.95it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2410/2529 [04:06<00:06, 17.52it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2412/2529 [04:06<00:06, 17.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2414/2529 [04:06<00:06, 17.86it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2417/2529 [04:06<00:05, 18.73it/s]

Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2420/2529 [04:07<00:05, 18.75it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2423/2529 [04:07<00:05, 19.74it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2425/2529 [04:07<00:05, 19.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2428/2529 [04:07<00:05, 19.70it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2430/2529 [04:07<00:05, 19.01it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2432/2529 [04:07<00:05, 16.31it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2434/2529 [04:07<00:05, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▋| 2436/2529 [04:07<00:05, 15.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  96%|█████████▋| 2438/2529 [04:08<00:05, 15.19it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2441/2529 [04:08<00:04, 17.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2444/2529 [04:08<00:04, 18.65it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2446/2529 [04:08<00:04, 17.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2448/2529 [04:08<00:04, 17.16it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2450/2529 [04:08<00:04, 16.99it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2453/2529 [04:08<00:03, 19.17it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2455/2529 [04:09<00:05, 14.53it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2458/2529 [04:09<00:04, 16.57it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2461/2529 [04:09<00:04, 16.82it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2463/2529 [04:09<00:03, 17.36it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2465/2529 [04:09<00:03, 17.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2467/2529 [04:09<00:03, 15.69it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2470/2529 [04:09<00:03, 17.94it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2472/2529 [04:10<00:03, 17.80it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2475/2529 [04:10<00:02, 18.98it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2477/2529 [04:10<00:02, 17.61it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2480/2529 [04:10<00:02, 17.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2483/2529 [04:10<00:02, 19.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2486/2529 [04:10<00:02, 20.08it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2489/2529 [04:10<00:02, 19.83it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▊| 2492/2529 [04:11<00:01, 20.85it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▊| 2495/2529 [04:11<00:01, 21.97it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2498/2529 [04:11<00:01, 17.88it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2500/2529 [04:11<00:01, 16.37it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2502/2529 [04:11<00:01, 15.33it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2504/2529 [04:11<00:01, 15.05it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2506/2529 [04:11<00:01, 15.28it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2508/2529 [04:12<00:01, 15.11it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2511/2529 [04:12<00:01, 17.00it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2514/2529 [04:12<00:00, 16.63it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2517/2529 [04:12<00:00, 17.67it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2519/2529 [04:12<00:00, 17.25it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2522/2529 [04:12<00:00, 18.60it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2525/2529 [04:13<00:00, 18.46it/s]
Processing: negative r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2528/2529 [04:13<00:00, 18.14it/s]
 43%|████▎     | 6/14 [16:06<24:27, 183.42s/it]
Processing: negative r2g, BASC binarized:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: negative r2g, BASC binarized:   0%|          | 1/2529 [00:00<06:11,  6.80it/s]
Processing: negative r2g, BASC binarized:   0%|          | 2/2529 [00:00<05:19,  7.91it/s]
Processing: negative r2g, BASC binarized:   0%|          | 3/2529 [00:00<05:05,  8.26it/s]
Processing: negative r2g, BASC binarized:   0%|          | 4/2529 [00:00<05:11,  8.10it/s]
Processing: negative r2g, BASC binarized:   0%|          | 5/2529 [00:00<04:52,  8.64it/s]
Processing: negative r2g, BASC binarized:   0%|          | 6/2529 [00:00<04:38,  9.05it/s]
Processing: negative r2g, BASC binarized:   0%|          | 7/2529 [00:00<04:53,  8.58it/s]
Processing: negative r2g, BASC binarized:   0%|          | 8/2529 [00:00<04:51,  8.66it/s]
Processing: negative r2g, BASC binarized:   0%|          | 9/2529 [00:01<04:49,  8.70it/s]
Processing: negative r2g, BASC binarized:   0%|          | 10/2529 [00:01<04:44,  8.84it/s]
Processing: negative r2g, BASC binarized:   0%|          | 11/2529 [00:01<04:46,  8.79it/s]
Processing: negative r2g, BASC binarized:   0%|          | 12/2529 [00:01<05:28,  7.66it/s]
Processing: negative r2g, BASC binarized:   1%|          | 13/2529 [00:01<05:14,  8.00it/s]
Processing: negative r2g, BASC binarized:   1%|          | 14/2529 [00:01<05:10,  8.10it/s]
Processing: negative r2g, BASC binarized:   1%|          | 15/2529 [00:01<05:02,  8.30it/s]
Processing: negative r2g, BASC binarized:   1%|          | 17/2529 [00:02<04:47,  8.74it/s]
Processing: negative r2g, BASC binarized:   1%|          | 19/2529 [00:02<05:33,  7.53it/s]
Processing: negative r2g, BASC binarized:   1%|          | 20/2529 [00:02<05:56,  7.03it/s]
Processing: negative r2g, BASC binarized:   1%|          | 21/2529 [00:02<05:41,  7.34it/s]
Processing: negative r2g, BASC binarized:   1%|          | 22/2529 [00:02<05:26,  7.67it/s]
Processing: negative r2g, BASC binarized:   1%|          | 23/2529 [00:02<05:57,  7.00it/s]
Processing: negative r2g, BASC binarized:   1%|          | 24/2529 [00:03<05:35,  7.47it/s]
Processing: negative r2g, BASC binarized:   1%|          | 25/2529 [00:03<05:23,  7.74it/s]
Processing: negative r2g, BASC binarized:   1%|          | 26/2529 [00:03<05:07,  8.15it/s]
Processing: negative r2g, BASC binarized:   1%|          | 27/2529 [00:03<05:00,  8.34it/s]
Processing: negative r2g, BASC binarized:   1%|          | 28/2529 [00:03<04:50,  8.61it/s]
Processing: negative r2g, BASC binarized:   1%|          | 29/2529 [00:03<06:06,  6.82it/s]
Processing: negative r2g, BASC binarized:   1%|          | 30/2529 [00:03<05:53,  7.07it/s]
Processing: negative r2g, BASC binarized:   1%|          | 31/2529 [00:04<06:24,  6.49it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 32/2529 [00:04<06:47,  6.12it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 33/2529 [00:04<06:09,  6.76it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 34/2529 [00:04<05:36,  7.41it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 35/2529 [00:04<05:21,  7.77it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 36/2529 [00:04<05:07,  8.10it/s]
Processing: negative r2g, BASC binarized:   1%|▏         | 37/2529 [00:04<05:29,  7.55it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 38/2529 [00:04<05:45,  7.21it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 40/2529 [00:05<05:52,  7.06it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 41/2529 [00:05<05:39,  7.34it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 42/2529 [00:05<05:22,  7.72it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 43/2529 [00:05<05:15,  7.89it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 45/2529 [00:05<04:56,  8.38it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 47/2529 [00:06<05:20,  7.75it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 48/2529 [00:06<05:51,  7.06it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 49/2529 [00:06<05:46,  7.17it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 50/2529 [00:06<05:40,  7.28it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 51/2529 [00:06<05:32,  7.44it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 52/2529 [00:06<05:30,  7.50it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 53/2529 [00:06<05:25,  7.61it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 54/2529 [00:07<05:14,  7.87it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 56/2529 [00:07<04:48,  8.56it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 57/2529 [00:07<04:38,  8.87it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 59/2529 [00:07<04:18,  9.56it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 61/2529 [00:07<04:17,  9.60it/s]
Processing: negative r2g, BASC binarized:   2%|▏         | 63/2529 [00:07<04:09,  9.88it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 64/2529 [00:08<04:14,  9.68it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 65/2529 [00:08<04:16,  9.62it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 66/2529 [00:08<04:14,  9.69it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 67/2529 [00:08<04:15,  9.65it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 68/2529 [00:08<04:20,  9.45it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 70/2529 [00:08<04:40,  8.77it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 71/2529 [00:08<04:50,  8.45it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 72/2529 [00:09<05:29,  7.46it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 73/2529 [00:09<05:14,  7.81it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 74/2529 [00:09<05:46,  7.09it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 75/2529 [00:09<06:09,  6.63it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 76/2529 [00:09<06:06,  6.70it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 77/2529 [00:09<05:57,  6.87it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 78/2529 [00:09<05:24,  7.55it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 80/2529 [00:10<04:52,  8.38it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 82/2529 [00:10<04:36,  8.86it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 83/2529 [00:10<04:35,  8.88it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 85/2529 [00:10<05:00,  8.14it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 86/2529 [00:10<05:24,  7.54it/s]
Processing: negative r2g, BASC binarized:   3%|▎         | 88/2529 [00:11<05:26,  7.48it/s]
Processing: negative r2g, BASC binarized:   4%|▎         | 89/2529 [00:11<05:14,  7.76it/s]
Processing: negative r2g, BASC binarized:   4%|▎         | 90/2529 [00:11<05:07,  7.93it/s]
Processing: negative r2g, BASC binarized:   4%|▎         | 91/2529 [00:11<04:57,  8.18it/s]
Processing: negative r2g, BASC binarized:   4%|▎         | 92/2529 [00:11<04:53,  8.30it/s]
Processing: negative r2g, BASC binarized:   4%|▎         | 94/2529 [00:11<04:26,  9.15it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 95/2529 [00:11<04:45,  8.53it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 96/2529 [00:12<04:44,  8.54it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 97/2529 [00:12<04:42,  8.62it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 98/2529 [00:12<04:50,  8.36it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 99/2529 [00:12<05:23,  7.52it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 100/2529 [00:12<06:07,  6.61it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 101/2529 [00:12<05:51,  6.91it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 102/2529 [00:12<05:40,  7.13it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 103/2529 [00:13<05:41,  7.10it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 105/2529 [00:13<04:51,  8.33it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 107/2529 [00:13<04:18,  9.38it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 109/2529 [00:13<04:40,  8.64it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 111/2529 [00:13<04:29,  8.98it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 112/2529 [00:13<04:39,  8.64it/s]
Processing: negative r2g, BASC binarized:   4%|▍         | 113/2529 [00:14<04:37,  8.70it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 114/2529 [00:14<04:31,  8.88it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 115/2529 [00:14<06:28,  6.21it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 116/2529 [00:14<06:52,  5.86it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 117/2529 [00:14<07:21,  5.47it/s]

Processing: negative r2g, BASC binarized:   5%|▍         | 118/2529 [00:15<08:02,  5.00it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 119/2529 [00:15<07:01,  5.72it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 120/2529 [00:15<07:25,  5.40it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 121/2529 [00:15<07:10,  5.59it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 122/2529 [00:15<07:10,  5.59it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 123/2529 [00:15<06:21,  6.31it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 124/2529 [00:16<06:41,  5.99it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 125/2529 [00:16<06:04,  6.60it/s]
Processing: negative r2g, BASC binarized:   5%|▍         | 126/2529 [00:16<05:33,  7.21it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 127/2529 [00:16<06:59,  5.72it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 128/2529 [00:16<07:31,  5.31it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 129/2529 [00:16<07:05,  5.64it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 130/2529 [00:17<07:03,  5.66it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 131/2529 [00:17<07:21,  5.44it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 132/2529 [00:17<07:47,  5.12it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 133/2529 [00:17<08:00,  4.98it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 134/2529 [00:17<07:52,  5.07it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 135/2529 [00:18<07:45,  5.14it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 136/2529 [00:18<07:57,  5.01it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 137/2529 [00:18<08:15,  4.83it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 138/2529 [00:18<08:05,  4.92it/s]
Processing: negative r2g, BASC binarized:   5%|▌         | 139/2529 [00:18<07:59,  4.99it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 140/2529 [00:19<07:02,  5.65it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 141/2529 [00:19<06:43,  5.92it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 142/2529 [00:19<06:43,  5.92it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 143/2529 [00:19<06:12,  6.40it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 144/2529 [00:19<06:00,  6.62it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 145/2529 [00:19<07:05,  5.60it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 146/2529 [00:20<06:20,  6.27it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 147/2529 [00:20<06:40,  5.95it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 148/2529 [00:20<07:10,  5.54it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 149/2529 [00:20<06:22,  6.22it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 150/2529 [00:20<05:49,  6.81it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 152/2529 [00:20<04:52,  8.12it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 154/2529 [00:21<04:55,  8.05it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 155/2529 [00:21<06:04,  6.51it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 156/2529 [00:21<06:45,  5.85it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 157/2529 [00:21<06:55,  5.70it/s]
Processing: negative r2g, BASC binarized:   6%|▌         | 158/2529 [00:22<07:25,  5.33it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 159/2529 [00:22<07:21,  5.36it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 160/2529 [00:22<07:44,  5.10it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 161/2529 [00:22<08:04,  4.89it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 162/2529 [00:22<07:47,  5.06it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 163/2529 [00:23<07:45,  5.08it/s]
Processing: negative r2g, BASC binarized:   6%|▋         | 164/2529 [00:23<07:19,  5.38it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 165/2529 [00:23<06:31,  6.05it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 166/2529 [00:23<05:53,  6.69it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 167/2529 [00:23<06:17,  6.25it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 168/2529 [00:23<06:36,  5.96it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 169/2529 [00:23<06:46,  5.80it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 171/2529 [00:24<06:31,  6.02it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 172/2529 [00:24<06:49,  5.76it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 173/2529 [00:24<06:50,  5.74it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 174/2529 [00:24<06:56,  5.66it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 175/2529 [00:25<06:53,  5.69it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 176/2529 [00:25<06:46,  5.80it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 177/2529 [00:25<06:25,  6.09it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 178/2529 [00:25<06:09,  6.37it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 179/2529 [00:25<05:40,  6.90it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 180/2529 [00:25<05:58,  6.55it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 181/2529 [00:25<05:35,  7.00it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 182/2529 [00:25<05:10,  7.55it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 183/2529 [00:26<05:01,  7.78it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 184/2529 [00:26<05:10,  7.56it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 185/2529 [00:26<04:53,  7.98it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 186/2529 [00:26<04:42,  8.30it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 187/2529 [00:26<04:39,  8.38it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 188/2529 [00:26<04:55,  7.93it/s]
Processing: negative r2g, BASC binarized:   7%|▋         | 189/2529 [00:26<04:43,  8.25it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 190/2529 [00:27<05:38,  6.91it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 191/2529 [00:27<05:17,  7.37it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 192/2529 [00:27<05:24,  7.20it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 193/2529 [00:27<05:09,  7.55it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 194/2529 [00:27<05:00,  7.78it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 195/2529 [00:27<04:49,  8.07it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 196/2529 [00:27<04:59,  7.78it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 197/2529 [00:27<04:49,  8.07it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 198/2529 [00:28<05:06,  7.61it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 200/2529 [00:28<04:35,  8.44it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 202/2529 [00:28<04:14,  9.15it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 203/2529 [00:28<05:01,  7.72it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 204/2529 [00:28<05:39,  6.86it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 205/2529 [00:28<05:24,  7.17it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 206/2529 [00:29<05:11,  7.47it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 207/2529 [00:29<05:05,  7.59it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 208/2529 [00:29<04:54,  7.87it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 209/2529 [00:29<04:47,  8.07it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 210/2529 [00:29<04:37,  8.36it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 211/2529 [00:29<04:32,  8.49it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 212/2529 [00:29<04:26,  8.70it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 213/2529 [00:29<05:31,  6.99it/s]
Processing: negative r2g, BASC binarized:   8%|▊         | 214/2529 [00:30<05:58,  6.46it/s]
Processing: negative r2g, BASC binarized:   9%|▊         | 216/2529 [00:30<05:15,  7.33it/s]
Processing: negative r2g, BASC binarized:   9%|▊         | 218/2529 [00:30<04:35,  8.39it/s]
Processing: negative r2g, BASC binarized:   9%|▊         | 220/2529 [00:30<04:12,  9.14it/s]
Processing: negative r2g, BASC binarized:   9%|▊         | 221/2529 [00:30<04:20,  8.87it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 223/2529 [00:31<04:13,  9.11it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 224/2529 [00:31<04:18,  8.92it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 225/2529 [00:31<04:56,  7.77it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 226/2529 [00:31<04:47,  8.01it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 228/2529 [00:31<04:15,  9.02it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 229/2529 [00:31<04:15,  8.99it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 230/2529 [00:31<04:16,  8.98it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 231/2529 [00:32<04:11,  9.12it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 232/2529 [00:32<04:18,  8.90it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 233/2529 [00:32<04:21,  8.77it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 235/2529 [00:32<04:10,  9.16it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 237/2529 [00:32<03:59,  9.59it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 238/2529 [00:32<04:04,  9.38it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 239/2529 [00:32<04:07,  9.26it/s]
Processing: negative r2g, BASC binarized:   9%|▉         | 240/2529 [00:33<04:47,  7.95it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 241/2529 [00:33<04:35,  8.31it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 242/2529 [00:33<04:43,  8.08it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 243/2529 [00:33<04:35,  8.30it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 245/2529 [00:33<04:02,  9.43it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 246/2529 [00:33<04:43,  8.06it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 247/2529 [00:33<05:16,  7.20it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 248/2529 [00:34<05:02,  7.54it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 250/2529 [00:34<05:05,  7.46it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 251/2529 [00:34<04:54,  7.72it/s]
Processing: negative r2g, BASC binarized:  10%|▉         | 252/2529 [00:34<04:46,  7.96it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 254/2529 [00:34<04:19,  8.76it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 256/2529 [00:34<04:02,  9.38it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 257/2529 [00:35<04:16,  8.86it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 258/2529 [00:35<04:29,  8.43it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 260/2529 [00:35<04:10,  9.07it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 261/2529 [00:35<04:07,  9.16it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 262/2529 [00:35<05:31,  6.84it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 263/2529 [00:35<05:14,  7.21it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 264/2529 [00:36<05:03,  7.47it/s]
Processing: negative r2g, BASC binarized:  10%|█         | 265/2529 [00:36<05:09,  7.33it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 266/2529 [00:36<04:47,  7.86it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 267/2529 [00:36<04:32,  8.30it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 269/2529 [00:36<04:05,  9.22it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 271/2529 [00:36<03:58,  9.49it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 272/2529 [00:36<04:34,  8.22it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 273/2529 [00:37<04:35,  8.19it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 274/2529 [00:37<04:28,  8.41it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 275/2529 [00:37<04:38,  8.09it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 277/2529 [00:37<04:08,  9.05it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 279/2529 [00:37<03:56,  9.51it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 280/2529 [00:37<03:58,  9.43it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 281/2529 [00:37<04:15,  8.80it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 282/2529 [00:38<04:38,  8.07it/s]
Processing: negative r2g, BASC binarized:  11%|█         | 283/2529 [00:38<04:33,  8.22it/s]
Processing: negative r2g, BASC binarized:  11%|█▏        | 285/2529 [00:38<04:19,  8.65it/s]
Processing: negative r2g, BASC binarized:  11%|█▏        | 286/2529 [00:38<04:19,  8.65it/s]
Processing: negative r2g, BASC binarized:  11%|█▏        | 288/2529 [00:38<04:10,  8.96it/s]
Processing: negative r2g, BASC binarized:  11%|█▏        | 289/2529 [00:38<04:37,  8.09it/s]
Processing: negative r2g, BASC binarized:  11%|█▏        | 290/2529 [00:39<04:44,  7.87it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 291/2529 [00:39<04:34,  8.14it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 292/2529 [00:39<04:31,  8.24it/s]

Processing: negative r2g, BASC binarized:  12%|█▏        | 293/2529 [00:39<04:35,  8.12it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 294/2529 [00:39<04:27,  8.37it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 295/2529 [00:39<04:38,  8.01it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 296/2529 [00:39<04:28,  8.32it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 297/2529 [00:39<04:22,  8.51it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 298/2529 [00:40<05:23,  6.90it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 299/2529 [00:40<05:05,  7.29it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 300/2529 [00:40<04:50,  7.66it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 301/2529 [00:40<04:40,  7.94it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 302/2529 [00:40<04:29,  8.25it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 303/2529 [00:40<04:25,  8.37it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 304/2529 [00:40<04:22,  8.49it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 305/2529 [00:40<04:16,  8.66it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 306/2529 [00:40<04:07,  9.00it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 307/2529 [00:41<04:00,  9.24it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 309/2529 [00:41<03:47,  9.78it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 310/2529 [00:41<03:53,  9.50it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 311/2529 [00:41<03:54,  9.46it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 313/2529 [00:41<03:53,  9.49it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 315/2529 [00:41<03:48,  9.68it/s]
Processing: negative r2g, BASC binarized:  12%|█▏        | 316/2529 [00:42<03:52,  9.53it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 318/2529 [00:42<03:45,  9.79it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 319/2529 [00:42<03:49,  9.61it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 320/2529 [00:42<03:56,  9.35it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 321/2529 [00:42<04:00,  9.19it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 322/2529 [00:42<04:25,  8.32it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 323/2529 [00:42<04:22,  8.41it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 324/2529 [00:42<04:11,  8.78it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 325/2529 [00:43<04:31,  8.12it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 326/2529 [00:43<05:00,  7.34it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 328/2529 [00:43<04:12,  8.70it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 329/2529 [00:43<04:12,  8.73it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 331/2529 [00:43<04:47,  7.66it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 332/2529 [00:44<05:16,  6.95it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 333/2529 [00:44<05:40,  6.45it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 334/2529 [00:44<05:14,  6.99it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 335/2529 [00:44<05:08,  7.10it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 336/2529 [00:44<04:51,  7.52it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 337/2529 [00:44<04:53,  7.46it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 339/2529 [00:44<04:35,  7.96it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 340/2529 [00:45<04:36,  7.92it/s]
Processing: negative r2g, BASC binarized:  13%|█▎        | 341/2529 [00:45<04:32,  8.02it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 342/2529 [00:45<04:41,  7.77it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 343/2529 [00:45<05:43,  6.36it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 344/2529 [00:45<05:21,  6.80it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 345/2529 [00:45<05:03,  7.20it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 346/2529 [00:45<04:47,  7.59it/s]
Processing: negative r2g, BASC binarized:  14%|█▎        | 347/2529 [00:46<05:04,  7.17it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 348/2529 [00:46<04:52,  7.45it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 350/2529 [00:46<04:06,  8.83it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 352/2529 [00:46<04:13,  8.59it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 353/2529 [00:46<04:16,  8.49it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 354/2529 [00:46<04:48,  7.54it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 355/2529 [00:47<05:17,  6.84it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 356/2529 [00:47<05:35,  6.47it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 357/2529 [00:47<05:53,  6.14it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 358/2529 [00:47<05:47,  6.25it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 359/2529 [00:47<06:36,  5.47it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 360/2529 [00:48<07:07,  5.07it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 361/2529 [00:48<07:10,  5.04it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 362/2529 [00:48<07:02,  5.12it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 363/2529 [00:48<07:23,  4.89it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 364/2529 [00:48<07:08,  5.06it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 365/2529 [00:49<07:36,  4.74it/s]
Processing: negative r2g, BASC binarized:  14%|█▍        | 366/2529 [00:49<08:08,  4.43it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 367/2529 [00:49<08:24,  4.29it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 368/2529 [00:49<08:04,  4.46it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 369/2529 [00:50<07:36,  4.74it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 370/2529 [00:50<07:42,  4.67it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 371/2529 [00:50<07:59,  4.50it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 372/2529 [00:50<07:45,  4.64it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 373/2529 [00:50<07:25,  4.84it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 374/2529 [00:51<07:34,  4.74it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 375/2529 [00:51<07:36,  4.72it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 376/2529 [00:51<06:38,  5.41it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 378/2529 [00:51<05:06,  7.02it/s]
Processing: negative r2g, BASC binarized:  15%|█▍        | 379/2529 [00:51<04:52,  7.34it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 380/2529 [00:51<04:39,  7.70it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 381/2529 [00:51<04:31,  7.92it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 382/2529 [00:52<04:38,  7.71it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 383/2529 [00:52<05:05,  7.03it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 384/2529 [00:52<04:45,  7.50it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 385/2529 [00:52<04:44,  7.55it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 386/2529 [00:52<04:31,  7.91it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 387/2529 [00:52<04:27,  8.02it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 388/2529 [00:52<04:23,  8.13it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 389/2529 [00:52<04:23,  8.11it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 390/2529 [00:53<04:18,  8.26it/s]
Processing: negative r2g, BASC binarized:  15%|█▌        | 391/2529 [00:53<04:13,  8.45it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 392/2529 [00:53<04:27,  7.98it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 393/2529 [00:53<04:22,  8.15it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 394/2529 [00:53<04:59,  7.13it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 395/2529 [00:53<05:33,  6.40it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 396/2529 [00:54<06:55,  5.13it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 397/2529 [00:54<07:00,  5.07it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 398/2529 [00:54<06:48,  5.21it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 399/2529 [00:54<06:45,  5.26it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 400/2529 [00:54<06:38,  5.35it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 402/2529 [00:55<05:40,  6.25it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 403/2529 [00:55<06:58,  5.07it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 404/2529 [00:55<06:26,  5.50it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 405/2529 [00:55<05:54,  5.99it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 407/2529 [00:55<04:44,  7.47it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 408/2529 [00:56<04:37,  7.64it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 409/2529 [00:56<05:00,  7.05it/s]
Processing: negative r2g, BASC binarized:  16%|█▌        | 410/2529 [00:56<05:04,  6.96it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 411/2529 [00:56<05:33,  6.34it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 412/2529 [00:56<05:41,  6.20it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 413/2529 [00:56<05:36,  6.29it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 415/2529 [00:57<04:31,  7.79it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 416/2529 [00:57<04:24,  7.99it/s]
Processing: negative r2g, BASC binarized:  16%|█▋        | 417/2529 [00:57<04:16,  8.23it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 418/2529 [00:57<04:28,  7.85it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 419/2529 [00:57<04:58,  7.07it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 421/2529 [00:57<04:27,  7.89it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 422/2529 [00:57<04:22,  8.02it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 423/2529 [00:58<04:24,  7.96it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 425/2529 [00:58<03:58,  8.82it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 427/2529 [00:58<03:49,  9.14it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 428/2529 [00:58<04:40,  7.49it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 429/2529 [00:58<04:37,  7.56it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 430/2529 [00:58<04:33,  7.67it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 431/2529 [00:59<04:50,  7.22it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 432/2529 [00:59<05:18,  6.57it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 433/2529 [00:59<05:38,  6.19it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 435/2529 [00:59<04:47,  7.28it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 436/2529 [00:59<04:38,  7.51it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 437/2529 [00:59<04:31,  7.71it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 438/2529 [01:00<04:42,  7.41it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 439/2529 [01:00<05:05,  6.85it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 440/2529 [01:00<04:44,  7.33it/s]
Processing: negative r2g, BASC binarized:  17%|█▋        | 442/2529 [01:00<04:27,  7.81it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 444/2529 [01:00<04:34,  7.59it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 446/2529 [01:01<04:46,  7.26it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 447/2529 [01:01<05:40,  6.11it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 448/2529 [01:01<05:10,  6.70it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 449/2529 [01:01<05:49,  5.96it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 450/2529 [01:02<06:28,  5.34it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 452/2529 [01:02<06:28,  5.34it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 453/2529 [01:02<06:25,  5.39it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 455/2529 [01:02<05:10,  6.67it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 456/2529 [01:03<06:01,  5.74it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 457/2529 [01:03<06:10,  5.59it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 458/2529 [01:03<05:43,  6.03it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 459/2529 [01:03<06:14,  5.52it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 460/2529 [01:03<05:57,  5.79it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 461/2529 [01:03<05:24,  6.38it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 462/2529 [01:03<04:51,  7.10it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 463/2529 [01:04<04:49,  7.13it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 464/2529 [01:04<05:01,  6.86it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 466/2529 [01:04<04:51,  7.08it/s]
Processing: negative r2g, BASC binarized:  18%|█▊        | 467/2529 [01:04<05:08,  6.69it/s]

Processing: negative r2g, BASC binarized:  19%|█▊        | 468/2529 [01:04<05:21,  6.41it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 469/2529 [01:05<05:28,  6.28it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 470/2529 [01:05<06:11,  5.55it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 471/2529 [01:05<06:20,  5.41it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 472/2529 [01:05<06:50,  5.01it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 473/2529 [01:05<05:51,  5.84it/s]
Processing: negative r2g, BASC binarized:  19%|█▊        | 474/2529 [01:05<05:53,  5.81it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 475/2529 [01:06<05:24,  6.33it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 476/2529 [01:06<04:51,  7.04it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 477/2529 [01:06<05:14,  6.53it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 478/2529 [01:06<04:52,  7.01it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 479/2529 [01:06<04:40,  7.31it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 480/2529 [01:06<04:28,  7.64it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 481/2529 [01:06<05:06,  6.69it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 482/2529 [01:07<05:28,  6.23it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 483/2529 [01:07<05:00,  6.82it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 484/2529 [01:07<04:39,  7.31it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 485/2529 [01:07<04:26,  7.66it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 487/2529 [01:07<03:51,  8.84it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 489/2529 [01:07<03:33,  9.57it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 491/2529 [01:08<03:33,  9.56it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 492/2529 [01:08<03:36,  9.39it/s]
Processing: negative r2g, BASC binarized:  19%|█▉        | 493/2529 [01:08<03:52,  8.76it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 494/2529 [01:08<03:52,  8.76it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 495/2529 [01:08<03:50,  8.82it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 496/2529 [01:08<03:50,  8.82it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 498/2529 [01:08<03:43,  9.09it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 500/2529 [01:09<03:32,  9.57it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 501/2529 [01:09<03:32,  9.55it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 503/2529 [01:09<03:46,  8.95it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 504/2529 [01:09<03:45,  8.96it/s]
Processing: negative r2g, BASC binarized:  20%|█▉        | 505/2529 [01:09<03:47,  8.88it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 506/2529 [01:09<03:47,  8.90it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 507/2529 [01:09<04:22,  7.69it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 508/2529 [01:10<04:15,  7.91it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 509/2529 [01:10<04:04,  8.28it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 510/2529 [01:10<04:29,  7.49it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 511/2529 [01:10<04:39,  7.23it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 512/2529 [01:10<04:22,  7.68it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 513/2529 [01:10<05:20,  6.29it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 515/2529 [01:10<04:21,  7.69it/s]
Processing: negative r2g, BASC binarized:  20%|██        | 517/2529 [01:11<03:51,  8.70it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 519/2529 [01:11<03:34,  9.39it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 521/2529 [01:11<03:53,  8.60it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 522/2529 [01:11<03:54,  8.55it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 523/2529 [01:11<03:57,  8.45it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 524/2529 [01:12<04:47,  6.98it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 525/2529 [01:12<05:13,  6.40it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 526/2529 [01:12<04:43,  7.06it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 528/2529 [01:12<04:03,  8.22it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 530/2529 [01:12<03:48,  8.74it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 532/2529 [01:12<03:34,  9.33it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 534/2529 [01:13<03:22,  9.86it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 536/2529 [01:13<03:46,  8.82it/s]
Processing: negative r2g, BASC binarized:  21%|██        | 537/2529 [01:13<03:51,  8.61it/s]
Processing: negative r2g, BASC binarized:  21%|██▏       | 538/2529 [01:13<04:52,  6.80it/s]
Processing: negative r2g, BASC binarized:  21%|██▏       | 540/2529 [01:13<04:21,  7.60it/s]
Processing: negative r2g, BASC binarized:  21%|██▏       | 541/2529 [01:14<04:21,  7.59it/s]
Processing: negative r2g, BASC binarized:  21%|██▏       | 542/2529 [01:14<04:59,  6.64it/s]
Processing: negative r2g, BASC binarized:  21%|██▏       | 543/2529 [01:14<04:46,  6.92it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 544/2529 [01:14<04:56,  6.70it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 545/2529 [01:14<04:38,  7.13it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 547/2529 [01:14<03:58,  8.32it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 549/2529 [01:15<03:42,  8.88it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 551/2529 [01:15<03:34,  9.20it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 552/2529 [01:15<03:35,  9.17it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 553/2529 [01:15<03:32,  9.32it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 554/2529 [01:15<03:56,  8.36it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 555/2529 [01:15<03:53,  8.44it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 557/2529 [01:16<03:48,  8.64it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 558/2529 [01:16<03:45,  8.74it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 559/2529 [01:16<03:51,  8.51it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 560/2529 [01:16<04:04,  8.06it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 561/2529 [01:16<04:00,  8.17it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 562/2529 [01:16<04:03,  8.08it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 564/2529 [01:16<03:40,  8.89it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 566/2529 [01:17<03:31,  9.29it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 567/2529 [01:17<04:10,  7.84it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 568/2529 [01:17<04:03,  8.04it/s]
Processing: negative r2g, BASC binarized:  22%|██▏       | 569/2529 [01:17<04:01,  8.11it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 570/2529 [01:17<04:16,  7.63it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 571/2529 [01:17<04:08,  7.89it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 572/2529 [01:17<04:21,  7.49it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 573/2529 [01:18<04:09,  7.82it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 574/2529 [01:18<04:36,  7.08it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 575/2529 [01:18<04:55,  6.62it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 576/2529 [01:18<04:32,  7.17it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 577/2529 [01:18<05:10,  6.28it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 578/2529 [01:18<05:30,  5.91it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 579/2529 [01:19<05:02,  6.44it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 580/2529 [01:19<04:37,  7.03it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 581/2529 [01:19<04:20,  7.49it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 582/2529 [01:19<04:07,  7.87it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 583/2529 [01:19<04:07,  7.87it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 584/2529 [01:19<04:30,  7.19it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 585/2529 [01:19<04:17,  7.56it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 587/2529 [01:19<03:51,  8.41it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 588/2529 [01:20<03:52,  8.37it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 589/2529 [01:20<03:42,  8.72it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 590/2529 [01:20<03:47,  8.53it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 591/2529 [01:20<04:06,  7.85it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 592/2529 [01:20<04:17,  7.53it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 593/2529 [01:20<04:01,  8.01it/s]
Processing: negative r2g, BASC binarized:  23%|██▎       | 594/2529 [01:20<03:52,  8.33it/s]
Processing: negative r2g, BASC binarized:  24%|██▎       | 595/2529 [01:20<03:50,  8.40it/s]
Processing: negative r2g, BASC binarized:  24%|██▎       | 597/2529 [01:21<03:25,  9.41it/s]
Processing: negative r2g, BASC binarized:  24%|██▎       | 598/2529 [01:21<04:17,  7.50it/s]
Processing: negative r2g, BASC binarized:  24%|██▎       | 599/2529 [01:21<04:06,  7.81it/s]
Processing: negative r2g, BASC binarized:  24%|██▎       | 600/2529 [01:21<03:54,  8.24it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 601/2529 [01:21<04:12,  7.62it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 602/2529 [01:21<04:16,  7.50it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 603/2529 [01:22<04:53,  6.57it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 604/2529 [01:22<06:28,  4.95it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 605/2529 [01:22<05:55,  5.42it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 606/2529 [01:22<05:55,  5.42it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 607/2529 [01:22<06:03,  5.29it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 608/2529 [01:23<06:05,  5.25it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 609/2529 [01:23<05:40,  5.64it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 610/2529 [01:23<05:04,  6.30it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 611/2529 [01:23<04:36,  6.93it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 612/2529 [01:23<04:58,  6.43it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 613/2529 [01:23<04:26,  7.19it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 614/2529 [01:23<04:09,  7.68it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 615/2529 [01:24<04:28,  7.13it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 616/2529 [01:24<04:08,  7.71it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 617/2529 [01:24<04:21,  7.32it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 618/2529 [01:24<04:02,  7.88it/s]
Processing: negative r2g, BASC binarized:  24%|██▍       | 619/2529 [01:24<03:47,  8.41it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 620/2529 [01:24<03:56,  8.09it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 621/2529 [01:24<04:00,  7.93it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 622/2529 [01:24<04:12,  7.55it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 623/2529 [01:25<04:12,  7.55it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 624/2529 [01:25<04:29,  7.06it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 625/2529 [01:25<04:18,  7.38it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 626/2529 [01:25<04:10,  7.61it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 627/2529 [01:25<04:03,  7.80it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 629/2529 [01:25<03:34,  8.84it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 630/2529 [01:25<03:33,  8.88it/s]
Processing: negative r2g, BASC binarized:  25%|██▍       | 632/2529 [01:26<03:18,  9.54it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 633/2529 [01:26<03:21,  9.42it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 634/2529 [01:26<03:24,  9.26it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 636/2529 [01:26<03:18,  9.56it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 637/2529 [01:26<04:30,  7.01it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 638/2529 [01:26<04:47,  6.57it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 639/2529 [01:27<05:00,  6.29it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 641/2529 [01:27<04:15,  7.40it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 642/2529 [01:27<04:12,  7.48it/s]
Processing: negative r2g, BASC binarized:  25%|██▌       | 643/2529 [01:27<04:04,  7.72it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 645/2529 [01:27<03:37,  8.67it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 647/2529 [01:27<03:36,  8.69it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 649/2529 [01:28<03:28,  9.03it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 650/2529 [01:28<03:28,  9.03it/s]

Processing: negative r2g, BASC binarized:  26%|██▌       | 651/2529 [01:28<04:01,  7.77it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 652/2529 [01:28<03:53,  8.05it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 654/2529 [01:28<03:26,  9.06it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 655/2529 [01:28<03:26,  9.09it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 656/2529 [01:29<03:54,  7.97it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 657/2529 [01:29<03:57,  7.89it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 658/2529 [01:29<04:32,  6.86it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 659/2529 [01:29<04:21,  7.15it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 660/2529 [01:29<04:53,  6.37it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 662/2529 [01:29<03:59,  7.80it/s]
Processing: negative r2g, BASC binarized:  26%|██▌       | 663/2529 [01:30<04:02,  7.68it/s]
Processing: negative r2g, BASC binarized:  26%|██▋       | 665/2529 [01:30<03:53,  8.00it/s]
Processing: negative r2g, BASC binarized:  26%|██▋       | 666/2529 [01:30<04:03,  7.66it/s]
Processing: negative r2g, BASC binarized:  26%|██▋       | 667/2529 [01:30<03:51,  8.05it/s]
Processing: negative r2g, BASC binarized:  26%|██▋       | 669/2529 [01:30<03:29,  8.88it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 671/2529 [01:30<03:22,  9.19it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 672/2529 [01:31<03:45,  8.22it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 673/2529 [01:31<03:41,  8.37it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 674/2529 [01:31<03:38,  8.49it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 675/2529 [01:31<03:35,  8.60it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 676/2529 [01:31<03:39,  8.46it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 677/2529 [01:31<04:01,  7.67it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 678/2529 [01:31<03:56,  7.84it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 679/2529 [01:31<04:05,  7.53it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 680/2529 [01:32<04:01,  7.67it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 681/2529 [01:32<03:49,  8.07it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 682/2529 [01:32<03:48,  8.08it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 683/2529 [01:32<03:39,  8.41it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 684/2529 [01:32<03:59,  7.70it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 685/2529 [01:32<04:00,  7.67it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 686/2529 [01:32<03:56,  7.78it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 687/2529 [01:32<03:50,  8.00it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 688/2529 [01:33<03:55,  7.80it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 689/2529 [01:33<04:16,  7.18it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 690/2529 [01:33<05:46,  5.31it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 691/2529 [01:33<06:47,  4.51it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 692/2529 [01:34<07:06,  4.31it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 693/2529 [01:34<07:20,  4.17it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 694/2529 [01:34<07:28,  4.09it/s]
Processing: negative r2g, BASC binarized:  27%|██▋       | 695/2529 [01:34<06:45,  4.52it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 696/2529 [01:34<06:24,  4.77it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 697/2529 [01:35<06:08,  4.97it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 698/2529 [01:35<05:58,  5.11it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 699/2529 [01:35<05:33,  5.49it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 700/2529 [01:35<05:56,  5.13it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 701/2529 [01:35<05:59,  5.08it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 702/2529 [01:36<05:52,  5.19it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 703/2529 [01:36<05:02,  6.04it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 704/2529 [01:36<05:10,  5.88it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 705/2529 [01:36<05:07,  5.92it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 707/2529 [01:36<04:33,  6.67it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 709/2529 [01:37<04:37,  6.55it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 710/2529 [01:37<04:21,  6.96it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 711/2529 [01:37<04:09,  7.30it/s]
Processing: negative r2g, BASC binarized:  28%|██▊       | 712/2529 [02:25<6:18:30, 12.50s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 713/2529 [02:26<4:38:47,  9.21s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 714/2529 [02:26<3:23:50,  6.74s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 715/2529 [02:26<2:27:22,  4.87s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 716/2529 [02:26<1:47:16,  3.55s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 717/2529 [02:26<1:17:01,  2.55s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 718/2529 [02:27<55:39,  1.84s/it]
Processing: negative r2g, BASC binarized:  28%|██▊       | 719/2529 [02:27<40:49,  1.35s/it]
Processing: negative r2g, BASC binarized:  29%|██▊       | 721/2529 [02:27<23:37,  1.28it/s]
Processing: negative r2g, BASC binarized:  29%|██▊       | 723/2529 [02:27<15:49,  1.90it/s]
Processing: negative r2g, BASC binarized:  29%|██▊       | 725/2529 [02:27<11:04,  2.71it/s]
Processing: negative r2g, BASC binarized:  29%|██▊       | 727/2529 [02:28<08:16,  3.63it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 728/2529 [02:28<07:31,  3.99it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 730/2529 [02:28<05:56,  5.05it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 732/2529 [02:28<04:51,  6.16it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 734/2529 [02:29<05:24,  5.54it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 736/2529 [02:29<05:05,  5.88it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 737/2529 [02:29<05:41,  5.24it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 738/2529 [02:29<05:51,  5.10it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 739/2529 [02:29<05:12,  5.74it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 740/2529 [02:30<04:50,  6.16it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 741/2529 [02:30<04:27,  6.68it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 742/2529 [02:30<04:18,  6.91it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 744/2529 [02:30<03:48,  7.80it/s]
Processing: negative r2g, BASC binarized:  29%|██▉       | 745/2529 [02:30<04:16,  6.96it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 747/2529 [02:31<04:04,  7.27it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 748/2529 [02:31<04:13,  7.01it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 749/2529 [02:31<04:50,  6.13it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 750/2529 [02:31<04:27,  6.66it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 751/2529 [02:31<04:06,  7.23it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 752/2529 [02:31<05:02,  5.87it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 753/2529 [02:32<04:53,  6.04it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 755/2529 [02:32<04:36,  6.41it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 756/2529 [02:32<04:34,  6.47it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 757/2529 [02:32<04:20,  6.80it/s]
Processing: negative r2g, BASC binarized:  30%|██▉       | 758/2529 [02:32<04:10,  7.07it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 760/2529 [02:32<03:31,  8.36it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 762/2529 [02:33<03:25,  8.58it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 764/2529 [02:33<03:14,  9.08it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 766/2529 [02:33<03:29,  8.40it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 767/2529 [02:33<03:51,  7.63it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 769/2529 [02:33<03:24,  8.59it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 770/2529 [02:34<03:22,  8.69it/s]
Processing: negative r2g, BASC binarized:  30%|███       | 771/2529 [02:34<03:21,  8.73it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 773/2529 [02:34<03:10,  9.24it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 775/2529 [02:34<03:04,  9.50it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 776/2529 [02:34<03:13,  9.07it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 778/2529 [02:34<03:31,  8.27it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 780/2529 [02:35<03:23,  8.60it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 781/2529 [02:35<03:29,  8.33it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 782/2529 [02:35<03:49,  7.61it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 783/2529 [02:35<03:42,  7.83it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 784/2529 [02:35<03:41,  7.88it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 785/2529 [02:35<03:43,  7.81it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 786/2529 [02:36<03:43,  7.81it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 787/2529 [02:36<04:26,  6.53it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 788/2529 [02:36<04:15,  6.82it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 789/2529 [02:36<04:20,  6.68it/s]
Processing: negative r2g, BASC binarized:  31%|███       | 790/2529 [02:36<04:36,  6.29it/s]
Processing: negative r2g, BASC binarized:  31%|███▏      | 791/2529 [02:36<05:43,  5.06it/s]
Processing: negative r2g, BASC binarized:  31%|███▏      | 792/2529 [02:37<05:01,  5.75it/s]
Processing: negative r2g, BASC binarized:  31%|███▏      | 794/2529 [02:37<04:07,  7.02it/s]
Processing: negative r2g, BASC binarized:  31%|███▏      | 796/2529 [02:37<04:52,  5.92it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 797/2529 [02:37<05:02,  5.72it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 798/2529 [02:38<04:59,  5.79it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 799/2529 [02:38<04:26,  6.48it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 800/2529 [02:38<04:05,  7.03it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 801/2529 [02:38<03:53,  7.41it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 802/2529 [02:38<03:47,  7.58it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 803/2529 [02:38<03:44,  7.70it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 804/2529 [02:39<05:38,  5.10it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 805/2529 [02:39<04:52,  5.90it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 806/2529 [02:39<04:58,  5.77it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 807/2529 [02:39<05:37,  5.11it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 808/2529 [02:39<05:17,  5.42it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 809/2529 [02:39<04:44,  6.04it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 810/2529 [02:39<04:16,  6.69it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 811/2529 [02:40<04:00,  7.13it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 812/2529 [02:40<03:58,  7.21it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 813/2529 [02:40<03:46,  7.57it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 815/2529 [02:40<04:05,  6.97it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 816/2529 [02:40<03:50,  7.45it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 817/2529 [02:40<03:49,  7.46it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 818/2529 [02:41<03:48,  7.50it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 819/2529 [02:41<04:06,  6.95it/s]
Processing: negative r2g, BASC binarized:  32%|███▏      | 821/2529 [02:41<03:51,  7.38it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 823/2529 [02:41<03:25,  8.28it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 824/2529 [02:41<03:25,  8.30it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 825/2529 [02:41<03:49,  7.42it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 826/2529 [02:42<03:43,  7.64it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 827/2529 [02:42<04:49,  5.88it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 828/2529 [02:42<05:17,  5.36it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 829/2529 [02:42<04:47,  5.92it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 830/2529 [02:42<04:26,  6.37it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 832/2529 [02:43<03:48,  7.42it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 833/2529 [02:43<03:35,  7.88it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 834/2529 [02:43<04:02,  6.99it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 836/2529 [02:43<03:56,  7.15it/s]

Processing: negative r2g, BASC binarized:  33%|███▎      | 837/2529 [02:43<03:45,  7.52it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 839/2529 [02:43<03:21,  8.40it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 840/2529 [02:44<03:34,  7.87it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 842/2529 [02:44<03:20,  8.43it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 843/2529 [02:44<03:18,  8.50it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 845/2529 [02:44<03:19,  8.46it/s]
Processing: negative r2g, BASC binarized:  33%|███▎      | 846/2529 [02:44<03:26,  8.16it/s]
Processing: negative r2g, BASC binarized:  34%|███▎      | 848/2529 [02:44<03:26,  8.12it/s]
Processing: negative r2g, BASC binarized:  34%|███▎      | 850/2529 [02:45<03:29,  8.01it/s]
Processing: negative r2g, BASC binarized:  34%|███▎      | 851/2529 [02:45<03:25,  8.17it/s]
Processing: negative r2g, BASC binarized:  34%|███▎      | 852/2529 [02:45<03:20,  8.36it/s]
Processing: negative r2g, BASC binarized:  34%|███▎      | 853/2529 [02:45<03:16,  8.51it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 854/2529 [02:45<03:12,  8.70it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 856/2529 [02:45<03:04,  9.07it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 858/2529 [02:46<02:54,  9.59it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 859/2529 [02:46<02:54,  9.59it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 860/2529 [02:46<02:56,  9.44it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 861/2529 [02:46<02:54,  9.54it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 862/2529 [02:46<02:57,  9.41it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 863/2529 [02:46<03:16,  8.50it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 864/2529 [02:46<03:11,  8.70it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 866/2529 [02:46<02:55,  9.49it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 868/2529 [02:47<02:57,  9.37it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 869/2529 [02:47<02:57,  9.35it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 870/2529 [02:47<02:58,  9.28it/s]
Processing: negative r2g, BASC binarized:  34%|███▍      | 872/2529 [02:47<03:00,  9.20it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 873/2529 [02:47<02:58,  9.28it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 874/2529 [02:47<03:25,  8.06it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 875/2529 [02:47<03:17,  8.36it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 877/2529 [02:48<03:02,  9.07it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 878/2529 [02:48<03:20,  8.22it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 879/2529 [02:48<03:36,  7.64it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 880/2529 [02:48<03:28,  7.90it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 882/2529 [02:48<03:48,  7.21it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 883/2529 [02:49<03:38,  7.53it/s]
Processing: negative r2g, BASC binarized:  35%|███▍      | 884/2529 [02:49<03:26,  7.97it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 886/2529 [02:49<03:09,  8.66it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 887/2529 [02:49<03:10,  8.64it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 888/2529 [02:49<03:05,  8.86it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 890/2529 [02:49<02:52,  9.53it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 892/2529 [02:50<03:11,  8.56it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 894/2529 [02:50<03:00,  9.04it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 895/2529 [02:50<03:04,  8.86it/s]
Processing: negative r2g, BASC binarized:  35%|███▌      | 896/2529 [02:50<03:09,  8.60it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 898/2529 [02:50<02:54,  9.35it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 900/2529 [02:50<03:16,  8.29it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 901/2529 [02:51<03:26,  7.88it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 902/2529 [02:51<03:58,  6.82it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 903/2529 [02:51<03:42,  7.30it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 904/2529 [02:51<03:42,  7.30it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 905/2529 [02:51<03:29,  7.74it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 907/2529 [02:51<03:07,  8.63it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 908/2529 [02:51<03:07,  8.65it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 909/2529 [02:52<03:19,  8.10it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 911/2529 [02:52<03:01,  8.91it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 912/2529 [02:52<03:26,  7.81it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 914/2529 [02:52<03:06,  8.66it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 915/2529 [02:52<03:10,  8.45it/s]
Processing: negative r2g, BASC binarized:  36%|███▌      | 916/2529 [02:52<03:05,  8.70it/s]
Processing: negative r2g, BASC binarized:  36%|███▋      | 918/2529 [02:53<03:23,  7.93it/s]
Processing: negative r2g, BASC binarized:  36%|███▋      | 919/2529 [02:53<03:27,  7.76it/s]
Processing: negative r2g, BASC binarized:  36%|███▋      | 921/2529 [02:53<03:01,  8.85it/s]
Processing: negative r2g, BASC binarized:  36%|███▋      | 923/2529 [02:53<02:49,  9.45it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 925/2529 [02:53<02:45,  9.68it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 927/2529 [02:54<02:40,  9.96it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 929/2529 [02:54<02:38, 10.08it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 931/2529 [02:54<02:50,  9.39it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 933/2529 [02:54<03:20,  7.97it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 935/2529 [02:55<03:16,  8.10it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 936/2529 [02:55<03:34,  7.44it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 937/2529 [02:55<03:23,  7.83it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 939/2529 [02:55<03:26,  7.69it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 940/2529 [02:55<03:28,  7.63it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 941/2529 [02:56<03:58,  6.65it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 942/2529 [02:56<04:23,  6.03it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 943/2529 [02:56<04:04,  6.48it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 945/2529 [02:56<03:24,  7.74it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 947/2529 [02:56<03:03,  8.61it/s]
Processing: negative r2g, BASC binarized:  37%|███▋      | 948/2529 [02:56<03:12,  8.21it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 949/2529 [02:56<03:09,  8.33it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 950/2529 [02:57<03:07,  8.44it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 952/2529 [02:57<02:58,  8.82it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 953/2529 [02:57<03:28,  7.55it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 954/2529 [02:57<03:22,  7.78it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 955/2529 [02:57<03:43,  7.05it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 956/2529 [02:57<03:33,  7.36it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 957/2529 [02:58<03:23,  7.74it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 958/2529 [02:58<03:18,  7.93it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 960/2529 [02:58<02:59,  8.75it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 961/2529 [02:58<02:58,  8.79it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 963/2529 [02:58<02:46,  9.42it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 965/2529 [02:58<02:36, 10.02it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 966/2529 [02:59<03:17,  7.90it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 967/2529 [02:59<03:23,  7.68it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 969/2529 [02:59<03:03,  8.52it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 970/2529 [02:59<03:00,  8.63it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 972/2529 [02:59<02:48,  9.25it/s]
Processing: negative r2g, BASC binarized:  38%|███▊      | 973/2529 [02:59<02:56,  8.81it/s]
Processing: negative r2g, BASC binarized:  39%|███▊      | 975/2529 [03:00<02:46,  9.31it/s]
Processing: negative r2g, BASC binarized:  39%|███▊      | 976/2529 [03:00<02:56,  8.80it/s]
Processing: negative r2g, BASC binarized:  39%|███▊      | 977/2529 [03:00<02:56,  8.82it/s]
Processing: negative r2g, BASC binarized:  39%|███▊      | 978/2529 [03:00<03:39,  7.07it/s]
Processing: negative r2g, BASC binarized:  39%|███▊      | 979/2529 [03:00<03:29,  7.39it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 980/2529 [03:00<03:21,  7.67it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 981/2529 [03:00<03:15,  7.91it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 983/2529 [03:01<03:24,  7.55it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 984/2529 [03:01<03:14,  7.93it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 986/2529 [03:01<03:12,  8.03it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 987/2529 [03:01<03:07,  8.21it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 988/2529 [03:01<03:07,  8.21it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 990/2529 [03:01<02:50,  9.02it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 991/2529 [03:02<02:50,  9.04it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 992/2529 [03:02<02:50,  9.03it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 993/2529 [03:02<03:05,  8.27it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 994/2529 [03:02<03:01,  8.45it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 995/2529 [03:02<02:53,  8.82it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 997/2529 [03:02<02:45,  9.27it/s]
Processing: negative r2g, BASC binarized:  39%|███▉      | 998/2529 [03:02<02:53,  8.84it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1000/2529 [03:03<02:39,  9.59it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1002/2529 [03:03<02:33,  9.92it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1003/2529 [03:03<02:44,  9.29it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1005/2529 [03:03<03:01,  8.40it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1006/2529 [03:03<02:55,  8.68it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1008/2529 [03:04<03:17,  7.70it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1009/2529 [03:04<03:08,  8.07it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1010/2529 [03:04<03:27,  7.31it/s]
Processing: negative r2g, BASC binarized:  40%|███▉      | 1011/2529 [03:04<03:14,  7.82it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1012/2529 [03:04<03:09,  8.01it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1013/2529 [03:04<03:33,  7.09it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1015/2529 [03:05<03:47,  6.66it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1016/2529 [03:05<03:52,  6.50it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1017/2529 [03:05<03:36,  7.00it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1018/2529 [03:05<03:19,  7.59it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1019/2529 [03:05<03:09,  7.96it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1021/2529 [03:05<02:48,  8.94it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1022/2529 [03:05<02:50,  8.86it/s]
Processing: negative r2g, BASC binarized:  40%|████      | 1023/2529 [03:05<02:51,  8.77it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1025/2529 [03:06<02:38,  9.47it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1026/2529 [03:06<03:05,  8.10it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1028/2529 [03:06<03:10,  7.87it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1030/2529 [03:06<02:51,  8.75it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1031/2529 [03:06<02:47,  8.94it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1033/2529 [03:07<02:48,  8.89it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1035/2529 [03:07<02:38,  9.42it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1037/2529 [03:07<02:39,  9.37it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1038/2529 [03:07<02:56,  8.46it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1040/2529 [03:07<02:48,  8.84it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1041/2529 [03:08<02:53,  8.57it/s]
Processing: negative r2g, BASC binarized:  41%|████      | 1042/2529 [03:08<02:50,  8.70it/s]
Processing: negative r2g, BASC binarized:  41%|████▏     | 1044/2529 [03:08<02:53,  8.55it/s]
Processing: negative r2g, BASC binarized:  41%|████▏     | 1045/2529 [03:08<02:57,  8.38it/s]
Processing: negative r2g, BASC binarized:  41%|████▏     | 1046/2529 [03:08<02:59,  8.28it/s]

Processing: negative r2g, BASC binarized:  41%|████▏     | 1047/2529 [03:08<02:53,  8.55it/s]
Processing: negative r2g, BASC binarized:  41%|████▏     | 1048/2529 [03:08<02:50,  8.66it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1050/2529 [03:09<03:20,  7.37it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1051/2529 [03:09<03:13,  7.63it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1052/2529 [03:09<03:32,  6.94it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1053/2529 [03:09<03:33,  6.92it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1055/2529 [03:09<03:04,  8.00it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1057/2529 [03:10<02:58,  8.27it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1059/2529 [03:10<02:54,  8.44it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1061/2529 [03:10<02:42,  9.04it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1063/2529 [03:10<02:35,  9.42it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1064/2529 [03:10<02:35,  9.45it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1065/2529 [03:10<03:00,  8.12it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1066/2529 [03:11<02:52,  8.49it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1067/2529 [03:11<02:57,  8.23it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1068/2529 [03:11<03:03,  7.94it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1069/2529 [03:11<02:54,  8.34it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1071/2529 [03:11<02:40,  9.10it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1072/2529 [03:11<02:39,  9.11it/s]
Processing: negative r2g, BASC binarized:  42%|████▏     | 1073/2529 [03:11<03:17,  7.38it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1075/2529 [03:12<03:07,  7.74it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1077/2529 [03:12<03:01,  8.02it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1079/2529 [03:12<02:50,  8.51it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1080/2529 [03:12<02:58,  8.13it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1081/2529 [03:12<02:50,  8.47it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1083/2529 [03:13<02:36,  9.24it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1084/2529 [03:13<02:34,  9.37it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1086/2529 [03:13<02:28,  9.70it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1087/2529 [03:13<02:31,  9.51it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1089/2529 [03:13<02:53,  8.29it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1090/2529 [03:13<02:48,  8.56it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1092/2529 [03:14<02:34,  9.30it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1093/2529 [03:14<02:42,  8.82it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1094/2529 [03:14<02:41,  8.88it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1096/2529 [03:14<02:38,  9.03it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1098/2529 [03:14<02:28,  9.64it/s]
Processing: negative r2g, BASC binarized:  43%|████▎     | 1100/2529 [03:14<02:21, 10.08it/s]
Processing: negative r2g, BASC binarized:  44%|████▎     | 1102/2529 [03:15<02:39,  8.92it/s]
Processing: negative r2g, BASC binarized:  44%|████▎     | 1103/2529 [03:15<02:58,  7.99it/s]
Processing: negative r2g, BASC binarized:  44%|████▎     | 1104/2529 [03:15<03:01,  7.85it/s]
Processing: negative r2g, BASC binarized:  44%|████▎     | 1106/2529 [03:15<02:45,  8.62it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1107/2529 [03:15<02:51,  8.28it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1109/2529 [03:15<02:36,  9.06it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1111/2529 [03:16<02:36,  9.03it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1113/2529 [03:16<02:30,  9.38it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1114/2529 [03:16<02:34,  9.19it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1116/2529 [03:16<02:39,  8.86it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1118/2529 [03:16<02:32,  9.24it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1120/2529 [03:17<02:32,  9.22it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1122/2529 [03:17<02:27,  9.51it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1123/2529 [03:17<02:29,  9.42it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1124/2529 [03:17<02:28,  9.43it/s]
Processing: negative r2g, BASC binarized:  44%|████▍     | 1125/2529 [03:17<02:34,  9.06it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1126/2529 [03:17<02:34,  9.06it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1127/2529 [03:17<02:55,  7.99it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1128/2529 [03:18<02:46,  8.41it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1129/2529 [03:18<03:19,  7.00it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1130/2529 [03:18<03:10,  7.33it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1131/2529 [03:18<03:02,  7.67it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1133/2529 [03:18<02:41,  8.67it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1134/2529 [03:18<03:04,  7.57it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1136/2529 [03:19<02:42,  8.60it/s]
Processing: negative r2g, BASC binarized:  45%|████▍     | 1138/2529 [03:19<02:28,  9.35it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1140/2529 [03:19<02:22,  9.73it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1141/2529 [03:19<02:27,  9.40it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1142/2529 [03:19<02:33,  9.06it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1143/2529 [03:19<02:34,  8.95it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1144/2529 [03:19<02:35,  8.90it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1146/2529 [03:20<02:37,  8.77it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1148/2529 [03:20<02:24,  9.59it/s]
Processing: negative r2g, BASC binarized:  45%|████▌     | 1150/2529 [03:20<02:37,  8.74it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1152/2529 [03:20<02:47,  8.22it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1153/2529 [03:20<02:43,  8.40it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1155/2529 [03:21<02:35,  8.86it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1156/2529 [03:21<02:34,  8.86it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1158/2529 [03:21<02:39,  8.61it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1159/2529 [03:21<02:43,  8.39it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1161/2529 [03:21<02:28,  9.19it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1162/2529 [03:21<02:26,  9.30it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1163/2529 [03:22<02:49,  8.05it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1165/2529 [03:22<02:33,  8.88it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1167/2529 [03:22<02:29,  9.14it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1168/2529 [03:22<02:28,  9.19it/s]
Processing: negative r2g, BASC binarized:  46%|████▌     | 1169/2529 [03:22<02:26,  9.29it/s]
Processing: negative r2g, BASC binarized:  46%|████▋     | 1171/2529 [03:22<02:26,  9.29it/s]
Processing: negative r2g, BASC binarized:  46%|████▋     | 1172/2529 [03:23<02:34,  8.81it/s]
Processing: negative r2g, BASC binarized:  46%|████▋     | 1173/2529 [03:23<02:29,  9.04it/s]
Processing: negative r2g, BASC binarized:  46%|████▋     | 1175/2529 [03:23<02:34,  8.78it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1177/2529 [03:23<02:23,  9.40it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1179/2529 [03:23<02:17,  9.82it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1180/2529 [03:23<02:17,  9.79it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1182/2529 [03:24<02:16,  9.85it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1184/2529 [03:24<02:20,  9.55it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1186/2529 [03:24<02:15,  9.89it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1188/2529 [03:24<02:14,  9.99it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1190/2529 [03:25<02:35,  8.63it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1191/2529 [03:25<02:31,  8.81it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1192/2529 [03:25<02:34,  8.64it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1193/2529 [03:25<02:57,  7.54it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1194/2529 [03:25<02:47,  7.96it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1195/2529 [03:25<03:06,  7.15it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1196/2529 [03:25<02:56,  7.56it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1197/2529 [03:25<03:11,  6.95it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1199/2529 [03:26<02:59,  7.40it/s]
Processing: negative r2g, BASC binarized:  47%|████▋     | 1201/2529 [03:26<02:40,  8.29it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1202/2529 [03:26<02:49,  7.84it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1203/2529 [03:26<02:41,  8.22it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1205/2529 [03:26<02:28,  8.94it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1207/2529 [03:27<02:38,  8.34it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1209/2529 [03:27<02:31,  8.70it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1210/2529 [03:27<02:41,  8.15it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1211/2529 [03:27<02:35,  8.47it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1212/2529 [03:27<02:30,  8.72it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1213/2529 [03:27<02:37,  8.34it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1215/2529 [03:28<02:27,  8.90it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1216/2529 [03:28<02:33,  8.54it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1217/2529 [03:28<02:31,  8.64it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1219/2529 [03:28<02:37,  8.33it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1221/2529 [03:28<02:28,  8.83it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1222/2529 [03:28<02:33,  8.49it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1223/2529 [03:29<02:32,  8.58it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1224/2529 [03:29<02:35,  8.38it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1225/2529 [03:29<02:30,  8.67it/s]
Processing: negative r2g, BASC binarized:  48%|████▊     | 1226/2529 [03:29<02:33,  8.50it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1227/2529 [03:29<02:38,  8.21it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1228/2529 [03:29<02:40,  8.13it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1229/2529 [03:29<02:36,  8.29it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1230/2529 [03:29<02:33,  8.48it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1231/2529 [03:29<02:31,  8.55it/s]
Processing: negative r2g, BASC binarized:  49%|████▊     | 1232/2529 [03:30<03:01,  7.13it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1234/2529 [03:30<02:35,  8.32it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1235/2529 [03:30<02:32,  8.47it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1236/2529 [03:30<02:31,  8.56it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1237/2529 [03:30<02:33,  8.39it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1239/2529 [03:30<02:30,  8.59it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1241/2529 [03:31<02:57,  7.24it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1242/2529 [03:31<03:19,  6.44it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1243/2529 [03:31<03:30,  6.10it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1244/2529 [03:31<03:39,  5.86it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1245/2529 [03:32<03:51,  5.56it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1246/2529 [03:32<03:35,  5.95it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1247/2529 [03:32<03:28,  6.16it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1248/2529 [03:32<03:33,  6.00it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1249/2529 [03:32<03:13,  6.63it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1250/2529 [03:32<02:59,  7.11it/s]
Processing: negative r2g, BASC binarized:  49%|████▉     | 1251/2529 [03:32<02:48,  7.58it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1252/2529 [03:32<02:41,  7.92it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1254/2529 [03:33<02:27,  8.65it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1255/2529 [03:33<03:12,  6.62it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1256/2529 [03:33<03:24,  6.24it/s]

Processing: negative r2g, BASC binarized:  50%|████▉     | 1257/2529 [03:33<03:32,  5.98it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1258/2529 [03:34<03:39,  5.78it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1259/2529 [03:34<03:17,  6.42it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1260/2529 [03:34<03:01,  6.99it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1261/2529 [03:34<02:51,  7.40it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1262/2529 [03:34<02:45,  7.66it/s]
Processing: negative r2g, BASC binarized:  50%|████▉     | 1264/2529 [03:34<02:42,  7.81it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1265/2529 [03:34<02:51,  7.35it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1267/2529 [03:35<02:56,  7.15it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1268/2529 [03:35<02:50,  7.40it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1269/2529 [03:35<02:43,  7.73it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1270/2529 [03:35<02:39,  7.87it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1271/2529 [03:35<02:31,  8.28it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1272/2529 [03:35<02:34,  8.13it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1274/2529 [03:36<02:54,  7.19it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1275/2529 [03:36<03:17,  6.36it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1276/2529 [03:36<03:30,  5.95it/s]
Processing: negative r2g, BASC binarized:  50%|█████     | 1277/2529 [03:36<03:18,  6.29it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1278/2529 [03:36<03:08,  6.63it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1279/2529 [03:36<03:01,  6.88it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1280/2529 [03:37<02:55,  7.13it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1281/2529 [03:37<02:46,  7.49it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1283/2529 [03:37<02:34,  8.08it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1284/2529 [03:37<02:27,  8.45it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1286/2529 [03:37<02:18,  8.97it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1288/2529 [03:37<02:08,  9.65it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1290/2529 [03:38<02:08,  9.62it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1292/2529 [03:38<02:05,  9.88it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1293/2529 [03:38<02:07,  9.72it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1294/2529 [03:38<02:07,  9.66it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1295/2529 [03:38<02:06,  9.73it/s]
Processing: negative r2g, BASC binarized:  51%|█████     | 1296/2529 [03:38<02:07,  9.66it/s]
Processing: negative r2g, BASC binarized:  51%|█████▏    | 1297/2529 [03:38<02:10,  9.43it/s]
Processing: negative r2g, BASC binarized:  51%|█████▏    | 1299/2529 [03:39<02:24,  8.51it/s]
Processing: negative r2g, BASC binarized:  51%|█████▏    | 1300/2529 [03:39<02:30,  8.15it/s]
Processing: negative r2g, BASC binarized:  51%|█████▏    | 1301/2529 [03:39<02:49,  7.25it/s]
Processing: negative r2g, BASC binarized:  51%|█████▏    | 1302/2529 [03:39<02:40,  7.62it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1303/2529 [03:39<02:56,  6.95it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1304/2529 [03:39<02:47,  7.31it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1305/2529 [03:39<03:01,  6.73it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1306/2529 [03:40<03:02,  6.69it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1307/2529 [03:40<02:58,  6.83it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1308/2529 [03:40<02:45,  7.38it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1309/2529 [03:40<02:35,  7.84it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1310/2529 [03:40<02:28,  8.21it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1311/2529 [03:40<02:24,  8.43it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1313/2529 [03:40<02:12,  9.19it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1315/2529 [03:41<02:11,  9.22it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1316/2529 [03:41<02:12,  9.16it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1318/2529 [03:41<02:26,  8.24it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1319/2529 [03:41<02:40,  7.55it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1321/2529 [03:41<02:42,  7.42it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1322/2529 [03:42<02:37,  7.68it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1323/2529 [03:42<02:33,  7.84it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1324/2529 [03:42<02:28,  8.11it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1325/2529 [03:42<02:28,  8.11it/s]
Processing: negative r2g, BASC binarized:  52%|█████▏    | 1326/2529 [03:42<02:34,  7.80it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1328/2529 [03:42<02:28,  8.06it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1329/2529 [03:42<02:27,  8.11it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1330/2529 [03:43<02:24,  8.27it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1331/2529 [03:43<02:33,  7.82it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1332/2529 [03:43<02:51,  7.00it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1333/2529 [03:43<03:12,  6.22it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1334/2529 [03:43<03:04,  6.48it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1335/2529 [03:43<02:57,  6.72it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1336/2529 [03:43<02:56,  6.75it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1338/2529 [03:44<02:28,  8.03it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1340/2529 [03:44<02:10,  9.09it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1342/2529 [03:44<02:20,  8.42it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1344/2529 [03:44<02:15,  8.78it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1345/2529 [03:44<02:19,  8.47it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1346/2529 [03:45<02:19,  8.48it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1347/2529 [03:45<02:16,  8.67it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1348/2529 [03:45<03:20,  5.90it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1349/2529 [03:45<03:35,  5.48it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1350/2529 [03:45<03:53,  5.04it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1351/2529 [03:46<04:19,  4.54it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1352/2529 [03:46<03:43,  5.27it/s]
Processing: negative r2g, BASC binarized:  53%|█████▎    | 1353/2529 [03:46<03:51,  5.07it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1354/2529 [03:46<03:41,  5.31it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1355/2529 [03:46<03:38,  5.36it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1356/2529 [03:47<03:13,  6.05it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1357/2529 [03:47<03:23,  5.77it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1358/2529 [03:47<03:06,  6.28it/s]
Processing: negative r2g, BASC binarized:  54%|█████▎    | 1359/2529 [03:47<02:49,  6.90it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1360/2529 [03:47<02:37,  7.42it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1361/2529 [03:47<03:31,  5.53it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1362/2529 [03:48<03:46,  5.15it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1363/2529 [03:48<03:34,  5.44it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1364/2529 [03:48<03:39,  5.31it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1365/2529 [03:48<03:45,  5.17it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1366/2529 [03:48<03:56,  4.93it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1367/2529 [03:49<04:01,  4.82it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1368/2529 [03:49<04:03,  4.78it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1369/2529 [03:49<03:57,  4.88it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1370/2529 [03:49<04:05,  4.72it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1371/2529 [03:49<04:11,  4.60it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1372/2529 [03:50<04:04,  4.72it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1373/2529 [03:50<03:59,  4.82it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1374/2529 [03:50<03:31,  5.46it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1375/2529 [03:50<03:21,  5.74it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1376/2529 [03:50<03:20,  5.76it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1377/2529 [03:50<03:05,  6.19it/s]
Processing: negative r2g, BASC binarized:  54%|█████▍    | 1378/2529 [03:51<02:59,  6.43it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1379/2529 [03:51<03:30,  5.46it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1380/2529 [03:51<03:06,  6.15it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1381/2529 [03:51<03:16,  5.83it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1382/2529 [03:51<03:31,  5.42it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1383/2529 [03:51<03:08,  6.08it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1384/2529 [03:52<02:51,  6.66it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1385/2529 [03:52<02:35,  7.37it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1387/2529 [03:52<02:11,  8.66it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1388/2529 [03:52<02:27,  7.74it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1389/2529 [03:52<03:12,  5.91it/s]
Processing: negative r2g, BASC binarized:  55%|█████▍    | 1390/2529 [03:53<03:31,  5.37it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1391/2529 [03:53<03:33,  5.34it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1392/2529 [03:53<03:42,  5.12it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1393/2529 [03:53<03:37,  5.23it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1394/2529 [03:53<03:47,  4.99it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1395/2529 [03:54<03:55,  4.82it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1396/2529 [03:54<03:48,  4.96it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1397/2529 [03:54<03:45,  5.01it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1398/2529 [03:54<03:31,  5.34it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1399/2529 [03:54<03:08,  5.99it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1400/2529 [03:54<02:50,  6.63it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1401/2529 [03:55<03:01,  6.22it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1402/2529 [03:55<03:10,  5.92it/s]
Processing: negative r2g, BASC binarized:  55%|█████▌    | 1403/2529 [03:55<02:48,  6.69it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1404/2529 [03:55<02:59,  6.25it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1406/2529 [03:55<02:59,  6.26it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1407/2529 [03:56<03:11,  5.87it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1408/2529 [03:56<03:13,  5.80it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1409/2529 [03:56<03:16,  5.69it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1410/2529 [03:56<03:18,  5.62it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1411/2529 [03:56<03:15,  5.73it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1412/2529 [03:56<03:06,  6.00it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1413/2529 [03:57<02:57,  6.29it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1414/2529 [03:57<02:43,  6.83it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1415/2529 [03:57<02:52,  6.47it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1416/2529 [03:57<02:41,  6.88it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1417/2529 [03:57<02:30,  7.38it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1418/2529 [03:57<02:26,  7.60it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1419/2529 [03:57<02:30,  7.37it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1420/2529 [03:57<02:22,  7.81it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1421/2529 [03:58<02:19,  7.94it/s]
Processing: negative r2g, BASC binarized:  56%|█████▌    | 1422/2529 [03:58<02:16,  8.11it/s]
Processing: negative r2g, BASC binarized:  56%|█████▋    | 1423/2529 [03:58<02:22,  7.74it/s]
Processing: negative r2g, BASC binarized:  56%|█████▋    | 1424/2529 [03:58<02:16,  8.07it/s]
Processing: negative r2g, BASC binarized:  56%|█████▋    | 1425/2529 [03:58<02:42,  6.80it/s]
Processing: negative r2g, BASC binarized:  56%|█████▋    | 1426/2529 [03:58<02:35,  7.08it/s]

Processing: negative r2g, BASC binarized:  56%|█████▋    | 1427/2529 [03:58<02:38,  6.95it/s]
Processing: negative r2g, BASC binarized:  56%|█████▋    | 1428/2529 [03:59<02:33,  7.18it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1429/2529 [03:59<02:30,  7.31it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1430/2529 [03:59<02:22,  7.69it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1431/2529 [03:59<02:29,  7.33it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1432/2529 [03:59<02:23,  7.65it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1433/2529 [03:59<02:15,  8.08it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1434/2529 [03:59<02:25,  7.55it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1435/2529 [03:59<02:17,  7.98it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1436/2529 [04:00<02:13,  8.19it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1438/2529 [04:00<02:17,  7.94it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1439/2529 [04:00<02:39,  6.85it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1440/2529 [04:00<02:54,  6.25it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1441/2529 [04:00<02:44,  6.62it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1442/2529 [04:00<02:34,  7.03it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1443/2529 [04:01<02:29,  7.25it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1444/2529 [04:01<02:22,  7.60it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1445/2529 [04:01<02:18,  7.84it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1446/2529 [04:01<02:13,  8.12it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1447/2529 [04:01<02:10,  8.29it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1448/2529 [04:01<02:07,  8.46it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1449/2529 [04:01<02:18,  7.82it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1450/2529 [04:02<02:47,  6.43it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1451/2529 [04:02<02:58,  6.05it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1452/2529 [04:02<02:54,  6.19it/s]
Processing: negative r2g, BASC binarized:  57%|█████▋    | 1453/2529 [04:02<02:47,  6.43it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1455/2529 [04:02<02:17,  7.82it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1457/2529 [04:02<02:03,  8.66it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1458/2529 [04:03<02:06,  8.46it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1460/2529 [04:03<02:10,  8.22it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1461/2529 [04:03<02:10,  8.16it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1462/2529 [04:03<02:27,  7.24it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1463/2529 [04:03<02:21,  7.53it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1465/2529 [04:03<02:03,  8.64it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1467/2529 [04:04<01:57,  9.03it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1468/2529 [04:04<01:57,  9.00it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1469/2529 [04:04<01:59,  8.90it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1470/2529 [04:04<02:02,  8.64it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1471/2529 [04:04<02:02,  8.64it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1472/2529 [04:04<01:58,  8.89it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1473/2529 [04:04<01:57,  8.97it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1475/2529 [04:04<01:50,  9.52it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1476/2529 [04:05<01:53,  9.26it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1477/2529 [04:05<01:56,  9.01it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1478/2529 [04:05<01:58,  8.89it/s]
Processing: negative r2g, BASC binarized:  58%|█████▊    | 1479/2529 [04:05<02:18,  7.61it/s]
Processing: negative r2g, BASC binarized:  59%|█████▊    | 1480/2529 [04:05<02:10,  8.04it/s]
Processing: negative r2g, BASC binarized:  59%|█████▊    | 1481/2529 [04:05<02:13,  7.86it/s]
Processing: negative r2g, BASC binarized:  59%|█████▊    | 1482/2529 [04:05<02:09,  8.12it/s]
Processing: negative r2g, BASC binarized:  59%|█████▊    | 1484/2529 [04:06<01:52,  9.28it/s]
Processing: negative r2g, BASC binarized:  59%|█████▊    | 1485/2529 [04:06<02:11,  7.97it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1486/2529 [04:06<02:27,  7.09it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1487/2529 [04:06<02:19,  7.45it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1489/2529 [04:06<02:21,  7.38it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1490/2529 [04:06<02:16,  7.63it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1491/2529 [04:07<02:13,  7.79it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1493/2529 [04:07<02:02,  8.46it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1495/2529 [04:07<01:53,  9.09it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1497/2529 [04:07<01:48,  9.54it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1499/2529 [04:07<01:52,  9.19it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1500/2529 [04:08<01:58,  8.70it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1502/2529 [04:08<01:51,  9.24it/s]
Processing: negative r2g, BASC binarized:  59%|█████▉    | 1504/2529 [04:08<01:48,  9.46it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1505/2529 [04:08<02:26,  7.00it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1506/2529 [04:08<02:21,  7.23it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1507/2529 [04:08<02:17,  7.43it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1508/2529 [04:09<02:20,  7.28it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1509/2529 [04:09<02:11,  7.77it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1511/2529 [04:09<01:55,  8.83it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1512/2529 [04:09<02:08,  7.94it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1514/2529 [04:09<01:59,  8.51it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1515/2529 [04:09<02:12,  7.63it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1516/2529 [04:10<02:11,  7.71it/s]
Processing: negative r2g, BASC binarized:  60%|█████▉    | 1517/2529 [04:10<02:06,  7.99it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1518/2529 [04:10<02:10,  7.76it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1520/2529 [04:10<01:56,  8.65it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1522/2529 [04:10<01:47,  9.33it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1523/2529 [04:10<01:48,  9.24it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1524/2529 [04:10<02:00,  8.37it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1525/2529 [04:11<02:12,  7.56it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1526/2529 [04:11<02:08,  7.78it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1528/2529 [04:11<01:58,  8.44it/s]
Processing: negative r2g, BASC binarized:  60%|██████    | 1530/2529 [04:11<01:54,  8.76it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1531/2529 [04:11<01:56,  8.55it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1532/2529 [04:11<02:07,  7.81it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1533/2529 [04:12<02:12,  7.53it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1534/2529 [04:12<02:06,  7.85it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1535/2529 [04:12<02:04,  7.99it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1536/2529 [04:12<02:05,  7.89it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1537/2529 [04:12<02:02,  8.08it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1538/2529 [04:12<02:07,  7.75it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1539/2529 [04:12<02:03,  7.99it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1540/2529 [04:12<02:00,  8.24it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1541/2529 [04:13<02:27,  6.69it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1542/2529 [04:13<02:19,  7.08it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1543/2529 [04:13<02:12,  7.47it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1544/2529 [04:13<02:07,  7.73it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1545/2529 [04:13<02:02,  8.06it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1546/2529 [04:13<01:59,  8.23it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1547/2529 [04:13<01:57,  8.34it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1548/2529 [04:13<01:54,  8.55it/s]
Processing: negative r2g, BASC binarized:  61%|██████    | 1549/2529 [04:14<01:50,  8.87it/s]
Processing: negative r2g, BASC binarized:  61%|██████▏   | 1550/2529 [04:14<01:47,  9.09it/s]
Processing: negative r2g, BASC binarized:  61%|██████▏   | 1552/2529 [04:14<01:41,  9.63it/s]
Processing: negative r2g, BASC binarized:  61%|██████▏   | 1553/2529 [04:14<01:44,  9.37it/s]
Processing: negative r2g, BASC binarized:  61%|██████▏   | 1554/2529 [04:14<01:44,  9.33it/s]
Processing: negative r2g, BASC binarized:  61%|██████▏   | 1555/2529 [04:14<01:44,  9.29it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1556/2529 [04:14<01:45,  9.22it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1557/2529 [04:14<01:44,  9.27it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1558/2529 [04:15<01:46,  9.13it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1560/2529 [04:15<01:41,  9.54it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1561/2529 [04:15<01:46,  9.08it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1562/2529 [04:15<01:48,  8.91it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1563/2529 [04:15<01:53,  8.48it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1564/2529 [04:15<01:53,  8.51it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1565/2529 [04:15<02:04,  7.72it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1566/2529 [04:16<02:01,  7.93it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1567/2529 [04:16<01:54,  8.38it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1568/2529 [04:16<02:03,  7.79it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1569/2529 [04:16<02:17,  6.99it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1570/2529 [04:16<02:06,  7.58it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1571/2529 [04:16<01:57,  8.13it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1572/2529 [04:16<01:51,  8.57it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1573/2529 [04:16<01:47,  8.90it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1574/2529 [04:16<01:44,  9.15it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1575/2529 [04:17<01:42,  9.33it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1576/2529 [04:17<01:41,  9.40it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1577/2529 [04:17<01:44,  9.12it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1579/2529 [04:17<01:40,  9.50it/s]
Processing: negative r2g, BASC binarized:  62%|██████▏   | 1580/2529 [04:17<02:11,  7.21it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1581/2529 [04:17<02:24,  6.55it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1582/2529 [04:18<02:43,  5.79it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1583/2529 [04:18<02:27,  6.43it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1584/2529 [04:18<02:21,  6.66it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1585/2529 [04:18<02:11,  7.16it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1586/2529 [04:18<02:11,  7.16it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1588/2529 [04:18<02:01,  7.73it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1589/2529 [04:19<02:01,  7.72it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1590/2529 [04:19<02:07,  7.36it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1591/2529 [04:19<02:10,  7.19it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1592/2529 [04:19<02:35,  6.03it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1593/2529 [04:19<02:27,  6.35it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1594/2529 [04:19<02:18,  6.76it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1595/2529 [04:19<02:17,  6.79it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1596/2529 [04:20<02:22,  6.53it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1597/2529 [04:20<02:14,  6.94it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1599/2529 [04:20<01:50,  8.38it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1600/2529 [04:20<01:49,  8.48it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1601/2529 [04:20<01:57,  7.91it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1602/2529 [04:20<01:56,  7.95it/s]

Processing: negative r2g, BASC binarized:  63%|██████▎   | 1603/2529 [04:21<02:15,  6.85it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1604/2529 [04:21<02:27,  6.28it/s]
Processing: negative r2g, BASC binarized:  63%|██████▎   | 1605/2529 [04:21<02:32,  6.07it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1606/2529 [04:21<02:37,  5.85it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1607/2529 [04:21<02:32,  6.04it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1608/2529 [04:21<02:51,  5.38it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1609/2529 [04:22<02:55,  5.24it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1610/2529 [04:22<02:57,  5.19it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1611/2529 [04:22<03:10,  4.82it/s]
Processing: negative r2g, BASC binarized:  64%|██████▎   | 1612/2529 [04:22<03:06,  4.93it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1613/2529 [04:23<03:17,  4.64it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1614/2529 [04:23<03:30,  4.35it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1615/2529 [04:23<03:38,  4.17it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1616/2529 [04:23<03:17,  4.62it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1617/2529 [04:23<03:25,  4.44it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1618/2529 [04:24<03:21,  4.52it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1619/2529 [04:24<03:19,  4.56it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1620/2529 [04:24<03:24,  4.45it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1621/2529 [04:24<03:30,  4.31it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1622/2529 [04:25<03:25,  4.41it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1623/2529 [04:25<03:17,  4.59it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1624/2529 [04:25<03:19,  4.53it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1625/2529 [04:25<03:18,  4.55it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1626/2529 [04:25<02:52,  5.23it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1628/2529 [04:26<02:17,  6.54it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1629/2529 [04:26<02:12,  6.81it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1630/2529 [04:26<02:04,  7.25it/s]
Processing: negative r2g, BASC binarized:  64%|██████▍   | 1631/2529 [04:26<02:05,  7.15it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1632/2529 [04:26<02:00,  7.47it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1633/2529 [04:26<02:04,  7.20it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1634/2529 [04:26<02:14,  6.67it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1635/2529 [04:27<02:15,  6.60it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1636/2529 [04:27<02:11,  6.80it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1637/2529 [04:27<02:10,  6.82it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1638/2529 [04:27<02:07,  7.01it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1639/2529 [04:27<02:02,  7.24it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1640/2529 [04:27<01:59,  7.42it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1641/2529 [04:27<01:54,  7.73it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1642/2529 [04:28<01:58,  7.47it/s]
Processing: negative r2g, BASC binarized:  65%|██████▍   | 1643/2529 [04:28<01:53,  7.79it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1644/2529 [04:28<01:57,  7.51it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1645/2529 [04:28<01:53,  7.77it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1646/2529 [04:28<02:08,  6.88it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1647/2529 [04:28<02:21,  6.23it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1648/2529 [04:29<02:54,  5.05it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1649/2529 [04:29<02:56,  5.00it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1650/2529 [04:29<02:49,  5.20it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1651/2529 [04:29<02:49,  5.19it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1652/2529 [04:29<02:47,  5.25it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1654/2529 [04:30<02:22,  6.12it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1655/2529 [04:30<02:54,  5.00it/s]
Processing: negative r2g, BASC binarized:  65%|██████▌   | 1656/2529 [04:30<02:41,  5.42it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1657/2529 [04:30<02:27,  5.91it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1659/2529 [04:30<01:58,  7.37it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1660/2529 [04:30<01:55,  7.52it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1661/2529 [04:31<02:05,  6.94it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1662/2529 [04:31<02:06,  6.86it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1663/2529 [04:31<02:18,  6.25it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1664/2529 [04:31<02:20,  6.14it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1665/2529 [04:31<02:18,  6.23it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1666/2529 [04:31<02:18,  6.24it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1668/2529 [04:32<01:56,  7.37it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1669/2529 [04:32<01:53,  7.58it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1670/2529 [04:32<01:57,  7.29it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1671/2529 [04:32<02:07,  6.73it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1673/2529 [04:32<01:47,  8.00it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1674/2529 [04:32<01:46,  7.99it/s]
Processing: negative r2g, BASC binarized:  66%|██████▌   | 1675/2529 [04:33<01:45,  8.07it/s]
Processing: negative r2g, BASC binarized:  66%|██████▋   | 1676/2529 [04:33<01:47,  7.97it/s]
Processing: negative r2g, BASC binarized:  66%|██████▋   | 1678/2529 [04:33<01:36,  8.79it/s]
Processing: negative r2g, BASC binarized:  66%|██████▋   | 1680/2529 [04:33<01:34,  8.99it/s]
Processing: negative r2g, BASC binarized:  66%|██████▋   | 1681/2529 [04:33<01:56,  7.27it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1682/2529 [04:34<02:00,  7.05it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1683/2529 [04:34<01:57,  7.23it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1684/2529 [04:34<02:01,  6.93it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1685/2529 [04:34<02:12,  6.36it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1686/2529 [04:34<02:20,  6.02it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1688/2529 [04:34<01:57,  7.15it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1689/2529 [04:35<01:53,  7.40it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1690/2529 [04:35<01:50,  7.61it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1691/2529 [04:35<01:54,  7.32it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1692/2529 [04:35<02:03,  6.76it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1693/2529 [04:35<01:55,  7.25it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1695/2529 [04:35<01:47,  7.73it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1697/2529 [04:36<01:50,  7.50it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1698/2529 [04:36<01:54,  7.28it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1699/2529 [04:36<02:07,  6.52it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1700/2529 [04:36<02:32,  5.42it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1701/2529 [04:36<02:15,  6.11it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1702/2529 [04:37<02:34,  5.36it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1703/2529 [04:37<02:48,  4.90it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1704/2529 [04:37<02:24,  5.71it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1706/2529 [04:37<02:28,  5.55it/s]
Processing: negative r2g, BASC binarized:  67%|██████▋   | 1707/2529 [04:38<02:34,  5.32it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1708/2529 [04:38<02:28,  5.54it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1710/2529 [04:38<01:58,  6.90it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1711/2529 [04:38<02:21,  5.77it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1712/2529 [04:38<02:32,  5.35it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1713/2529 [04:39<02:31,  5.37it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1714/2529 [04:39<02:31,  5.38it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1715/2529 [04:39<02:33,  5.32it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1716/2529 [04:39<02:43,  4.96it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1717/2529 [04:39<02:39,  5.09it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1718/2529 [04:39<02:28,  5.46it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1719/2529 [04:40<02:13,  6.09it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1720/2529 [04:40<01:58,  6.85it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1721/2529 [04:40<01:57,  6.90it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1722/2529 [04:40<02:01,  6.67it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1724/2529 [04:40<01:55,  6.95it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1725/2529 [04:41<02:12,  6.06it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1726/2529 [04:41<02:16,  5.90it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1727/2529 [04:41<02:16,  5.89it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1728/2529 [04:41<02:31,  5.30it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1729/2529 [04:41<02:32,  5.24it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1730/2529 [04:42<02:43,  4.89it/s]
Processing: negative r2g, BASC binarized:  68%|██████▊   | 1732/2529 [04:42<02:03,  6.44it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1733/2529 [04:42<02:07,  6.26it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1734/2529 [04:42<02:00,  6.62it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1735/2529 [04:42<01:50,  7.22it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1736/2529 [04:42<01:59,  6.66it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1737/2529 [04:42<01:51,  7.09it/s]
Processing: negative r2g, BASC binarized:  69%|██████▊   | 1738/2529 [04:43<01:47,  7.35it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1739/2529 [04:43<01:43,  7.64it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1740/2529 [04:43<02:05,  6.30it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1741/2529 [04:43<02:17,  5.74it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1742/2529 [04:43<02:03,  6.36it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1743/2529 [04:43<01:54,  6.89it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1744/2529 [04:43<01:52,  6.96it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1745/2529 [04:44<01:44,  7.47it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1746/2529 [04:44<01:39,  7.85it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1747/2529 [04:44<01:37,  8.04it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1748/2529 [04:44<01:34,  8.26it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1749/2529 [04:44<01:35,  8.16it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1750/2529 [04:44<01:36,  8.06it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1751/2529 [04:44<01:36,  8.07it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1752/2529 [04:44<01:41,  7.66it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1753/2529 [04:45<01:39,  7.77it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1754/2529 [04:45<01:44,  7.43it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1755/2529 [04:45<01:41,  7.61it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1756/2529 [04:45<01:37,  7.97it/s]
Processing: negative r2g, BASC binarized:  69%|██████▉   | 1757/2529 [04:45<01:36,  8.04it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1759/2529 [04:45<01:29,  8.62it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1761/2529 [04:45<01:20,  9.53it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1763/2529 [04:46<01:18,  9.80it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1765/2529 [04:46<01:16,  9.95it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1766/2529 [04:46<01:17,  9.79it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1767/2529 [04:46<01:26,  8.85it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1768/2529 [04:46<01:25,  8.85it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1769/2529 [04:46<01:26,  8.77it/s]
Processing: negative r2g, BASC binarized:  70%|██████▉   | 1770/2529 [04:46<01:26,  8.73it/s]

Processing: negative r2g, BASC binarized:  70%|███████   | 1771/2529 [04:47<01:40,  7.53it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1772/2529 [04:47<01:37,  7.76it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1773/2529 [04:47<01:32,  8.15it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1774/2529 [04:47<01:42,  7.36it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1775/2529 [04:47<01:47,  7.00it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1776/2529 [04:47<01:41,  7.39it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1777/2529 [04:48<02:03,  6.11it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1779/2529 [04:48<01:40,  7.46it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1781/2529 [04:48<01:28,  8.48it/s]
Processing: negative r2g, BASC binarized:  70%|███████   | 1782/2529 [04:48<01:26,  8.60it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1783/2529 [04:48<01:25,  8.68it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1785/2529 [04:48<01:31,  8.09it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1786/2529 [04:49<01:32,  8.06it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1787/2529 [04:49<01:44,  7.08it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1788/2529 [04:49<02:00,  6.15it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1789/2529 [04:49<02:10,  5.66it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1790/2529 [04:49<01:55,  6.41it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1792/2529 [04:49<01:35,  7.72it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1793/2529 [04:50<01:31,  8.01it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1794/2529 [04:50<01:29,  8.25it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1795/2529 [04:50<01:24,  8.65it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1797/2529 [04:50<01:16,  9.54it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1799/2529 [04:50<01:13,  9.92it/s]
Processing: negative r2g, BASC binarized:  71%|███████   | 1800/2529 [04:50<01:27,  8.29it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1802/2529 [04:51<01:23,  8.66it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1803/2529 [04:51<01:47,  6.77it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1805/2529 [04:51<01:35,  7.56it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1806/2529 [04:51<01:35,  7.54it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1807/2529 [04:51<01:49,  6.61it/s]
Processing: negative r2g, BASC binarized:  71%|███████▏  | 1808/2529 [04:52<01:44,  6.89it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1809/2529 [04:52<01:48,  6.66it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1810/2529 [04:52<01:41,  7.07it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1812/2529 [04:52<01:26,  8.25it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1814/2529 [04:52<01:24,  8.47it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1816/2529 [04:52<01:20,  8.82it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1817/2529 [04:53<01:20,  8.86it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1818/2529 [04:53<01:18,  9.06it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1819/2529 [04:53<01:26,  8.18it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1821/2529 [04:53<01:21,  8.71it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1823/2529 [04:53<01:20,  8.78it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1824/2529 [04:53<01:20,  8.79it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1825/2529 [04:53<01:20,  8.75it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1826/2529 [04:54<01:22,  8.51it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1827/2529 [04:54<01:27,  8.02it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1828/2529 [04:54<01:26,  8.12it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1829/2529 [04:54<01:35,  7.30it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1830/2529 [04:54<01:28,  7.89it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1832/2529 [04:54<01:17,  8.96it/s]
Processing: negative r2g, BASC binarized:  72%|███████▏  | 1833/2529 [04:54<01:18,  8.90it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1834/2529 [04:55<01:34,  7.36it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1835/2529 [04:55<01:47,  6.46it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1836/2529 [04:55<01:41,  6.80it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1837/2529 [04:55<01:43,  6.72it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1838/2529 [04:55<01:36,  7.19it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1839/2529 [04:55<01:44,  6.63it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1840/2529 [04:56<01:36,  7.13it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1841/2529 [04:56<01:50,  6.25it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1842/2529 [04:56<01:53,  6.06it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1843/2529 [04:56<01:43,  6.64it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1844/2529 [04:56<01:57,  5.85it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1845/2529 [04:56<02:03,  5.54it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1846/2529 [04:57<01:53,  6.02it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1847/2529 [04:57<01:48,  6.31it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1848/2529 [04:57<01:39,  6.87it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1849/2529 [04:57<01:33,  7.25it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1850/2529 [04:57<01:32,  7.31it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1851/2529 [04:57<01:40,  6.76it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1852/2529 [04:57<01:35,  7.10it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1853/2529 [04:58<01:29,  7.53it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1854/2529 [04:58<01:30,  7.49it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1855/2529 [04:58<01:27,  7.67it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1856/2529 [04:58<01:26,  7.79it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1857/2529 [04:58<01:20,  8.31it/s]
Processing: negative r2g, BASC binarized:  73%|███████▎  | 1858/2529 [04:58<01:22,  8.16it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1859/2529 [04:58<01:27,  7.69it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1860/2529 [04:58<01:21,  8.25it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1861/2529 [04:59<01:17,  8.58it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1862/2529 [04:59<01:16,  8.69it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1863/2529 [04:59<01:25,  7.77it/s]
Processing: negative r2g, BASC binarized:  74%|███████▎  | 1864/2529 [04:59<01:23,  7.96it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1866/2529 [04:59<01:13,  8.98it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1868/2529 [04:59<01:25,  7.75it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1869/2529 [05:00<01:22,  7.98it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1870/2529 [05:00<01:19,  8.30it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1871/2529 [05:00<01:26,  7.57it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1872/2529 [05:00<01:28,  7.46it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1873/2529 [05:00<01:45,  6.24it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1874/2529 [05:00<02:15,  4.84it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1875/2529 [05:01<02:03,  5.31it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1876/2529 [05:01<02:02,  5.31it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1877/2529 [05:01<02:04,  5.22it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1878/2529 [05:01<02:05,  5.18it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1879/2529 [05:01<01:51,  5.86it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1880/2529 [05:01<01:47,  6.04it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1881/2529 [05:02<01:37,  6.68it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1882/2529 [05:02<01:43,  6.26it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1883/2529 [05:02<01:31,  7.03it/s]
Processing: negative r2g, BASC binarized:  74%|███████▍  | 1884/2529 [05:02<01:25,  7.53it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1885/2529 [05:02<01:19,  8.12it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1886/2529 [05:02<01:26,  7.40it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1887/2529 [05:02<01:21,  7.91it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1888/2529 [05:03<01:27,  7.36it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1889/2529 [05:03<01:21,  7.90it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1890/2529 [05:03<01:17,  8.23it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1891/2529 [05:03<01:20,  7.96it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1892/2529 [05:03<01:21,  7.82it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1893/2529 [05:03<01:26,  7.37it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1894/2529 [05:03<01:27,  7.29it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1895/2529 [05:03<01:31,  6.90it/s]
Processing: negative r2g, BASC binarized:  75%|███████▍  | 1896/2529 [05:04<01:31,  6.88it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1897/2529 [05:04<01:29,  7.10it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1898/2529 [05:04<01:24,  7.48it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1899/2529 [05:04<01:22,  7.66it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1900/2529 [05:04<01:20,  7.80it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1902/2529 [05:04<01:11,  8.81it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1903/2529 [05:04<01:10,  8.84it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1904/2529 [05:04<01:10,  8.89it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1906/2529 [05:05<01:07,  9.19it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1907/2529 [05:05<01:08,  9.02it/s]
Processing: negative r2g, BASC binarized:  75%|███████▌  | 1909/2529 [05:05<01:06,  9.30it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1910/2529 [05:05<01:30,  6.85it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1911/2529 [05:05<01:36,  6.42it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1912/2529 [05:06<01:41,  6.06it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1914/2529 [05:06<01:26,  7.14it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1915/2529 [05:06<01:25,  7.21it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1916/2529 [05:06<01:24,  7.22it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1917/2529 [05:06<01:21,  7.49it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1919/2529 [05:06<01:12,  8.43it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1920/2529 [05:07<01:16,  7.95it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1921/2529 [05:07<01:20,  7.59it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1922/2529 [05:07<01:16,  7.91it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1924/2529 [05:07<01:14,  8.14it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1926/2529 [05:07<01:10,  8.52it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1927/2529 [05:07<01:10,  8.48it/s]
Processing: negative r2g, BASC binarized:  76%|███████▌  | 1928/2529 [06:05<2:15:18, 13.51s/it]
Processing: negative r2g, BASC binarized:  76%|███████▋  | 1929/2529 [06:05<1:41:39, 10.17s/it]
Processing: negative r2g, BASC binarized:  76%|███████▋  | 1931/2529 [06:05<59:28,  5.97s/it]
Processing: negative r2g, BASC binarized:  76%|███████▋  | 1933/2529 [06:05<37:31,  3.78s/it]
Processing: negative r2g, BASC binarized:  76%|███████▋  | 1934/2529 [06:06<29:57,  3.02s/it]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1935/2529 [06:06<23:23,  2.36s/it]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1936/2529 [06:06<18:03,  1.83s/it]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1937/2529 [06:06<13:39,  1.38s/it]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1938/2529 [06:06<10:28,  1.06s/it]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1940/2529 [06:07<06:24,  1.53it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1941/2529 [06:07<05:12,  1.88it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1942/2529 [06:07<04:07,  2.37it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1943/2529 [06:07<03:24,  2.87it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1944/2529 [06:07<02:52,  3.40it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1945/2529 [06:07<02:21,  4.14it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1946/2529 [06:07<01:57,  4.95it/s]

Processing: negative r2g, BASC binarized:  77%|███████▋  | 1947/2529 [06:07<01:40,  5.79it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1949/2529 [06:08<01:30,  6.39it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1950/2529 [06:08<01:27,  6.64it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1951/2529 [06:08<01:23,  6.95it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1952/2529 [06:08<01:18,  7.32it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1953/2529 [06:08<01:25,  6.73it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1954/2529 [06:08<01:29,  6.41it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1955/2529 [06:09<01:31,  6.28it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1956/2529 [06:09<01:29,  6.37it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1957/2529 [06:09<01:23,  6.87it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1958/2529 [06:09<01:17,  7.33it/s]
Processing: negative r2g, BASC binarized:  77%|███████▋  | 1959/2529 [06:09<01:18,  7.25it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1960/2529 [06:09<01:16,  7.42it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1961/2529 [06:09<01:15,  7.49it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1962/2529 [06:10<01:20,  7.02it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1963/2529 [06:10<01:24,  6.68it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1964/2529 [06:10<01:21,  6.96it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1965/2529 [06:10<01:19,  7.05it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1966/2529 [06:10<01:20,  6.99it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1967/2529 [06:10<01:25,  6.58it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1968/2529 [06:10<01:18,  7.17it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1969/2529 [06:11<01:48,  5.15it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1970/2529 [06:11<02:09,  4.31it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1971/2529 [06:11<02:17,  4.06it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1972/2529 [06:12<02:21,  3.94it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1973/2529 [06:12<02:28,  3.74it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1974/2529 [06:12<02:16,  4.07it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1975/2529 [06:12<02:11,  4.23it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1976/2529 [06:12<02:03,  4.49it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1977/2529 [06:13<01:58,  4.67it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1978/2529 [06:13<01:53,  4.87it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1979/2529 [06:13<01:58,  4.66it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1980/2529 [06:13<01:57,  4.69it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1981/2529 [06:14<01:56,  4.72it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1982/2529 [06:14<01:38,  5.57it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1983/2529 [06:14<01:39,  5.49it/s]
Processing: negative r2g, BASC binarized:  78%|███████▊  | 1984/2529 [06:14<01:37,  5.58it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1986/2529 [06:14<01:30,  6.03it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1987/2529 [06:14<01:21,  6.66it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1988/2529 [06:15<01:30,  5.98it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1989/2529 [06:15<01:23,  6.50it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1990/2529 [06:15<01:16,  7.00it/s]
Processing: negative r2g, BASC binarized:  79%|███████▊  | 1991/2529 [06:15<01:10,  7.61it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1992/2529 [06:15<01:16,  6.98it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1994/2529 [06:15<01:13,  7.26it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1995/2529 [06:16<01:30,  5.91it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1997/2529 [06:16<01:20,  6.64it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1998/2529 [06:16<01:41,  5.25it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 1999/2529 [06:16<01:32,  5.72it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2000/2529 [06:16<01:28,  5.95it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2001/2529 [06:17<01:32,  5.68it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2003/2529 [06:17<01:15,  7.01it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2005/2529 [06:17<01:13,  7.16it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2007/2529 [06:17<01:04,  8.09it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2008/2529 [06:17<01:05,  7.96it/s]
Processing: negative r2g, BASC binarized:  79%|███████▉  | 2010/2529 [06:18<01:05,  7.92it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2012/2529 [06:18<01:00,  8.56it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2013/2529 [06:18<01:00,  8.50it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2015/2529 [06:18<00:56,  9.09it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2016/2529 [06:18<00:57,  8.90it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2017/2529 [06:19<01:28,  5.77it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2019/2529 [06:19<01:24,  6.01it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2020/2529 [06:19<01:41,  5.02it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2021/2529 [06:20<01:43,  4.90it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2022/2529 [06:20<01:30,  5.62it/s]
Processing: negative r2g, BASC binarized:  80%|███████▉  | 2023/2529 [06:20<01:23,  6.04it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2024/2529 [06:20<01:16,  6.61it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2025/2529 [06:20<01:13,  6.83it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2026/2529 [06:20<01:07,  7.46it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2028/2529 [06:20<01:00,  8.32it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2029/2529 [06:21<01:09,  7.16it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2031/2529 [06:21<01:07,  7.36it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2032/2529 [06:21<01:10,  7.08it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2033/2529 [06:21<01:22,  6.05it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2034/2529 [06:21<01:15,  6.55it/s]
Processing: negative r2g, BASC binarized:  80%|████████  | 2035/2529 [06:21<01:09,  7.10it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2036/2529 [06:22<01:26,  5.69it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2037/2529 [06:22<01:23,  5.86it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2038/2529 [06:22<01:13,  6.66it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2039/2529 [06:22<01:20,  6.11it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2040/2529 [06:22<01:18,  6.23it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2041/2529 [06:22<01:13,  6.62it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2042/2529 [06:23<01:11,  6.85it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2044/2529 [06:23<00:59,  8.18it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2046/2529 [06:23<00:57,  8.35it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2048/2529 [06:23<00:53,  8.99it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2049/2529 [06:23<00:53,  8.97it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2050/2529 [06:24<01:01,  7.83it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2051/2529 [06:24<01:07,  7.08it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2053/2529 [06:24<00:58,  8.19it/s]
Processing: negative r2g, BASC binarized:  81%|████████  | 2054/2529 [06:24<00:56,  8.38it/s]
Processing: negative r2g, BASC binarized:  81%|████████▏ | 2055/2529 [06:24<00:56,  8.36it/s]
Processing: negative r2g, BASC binarized:  81%|████████▏ | 2057/2529 [06:24<00:52,  8.98it/s]
Processing: negative r2g, BASC binarized:  81%|████████▏ | 2059/2529 [06:25<00:51,  9.17it/s]
Processing: negative r2g, BASC binarized:  81%|████████▏ | 2060/2529 [06:25<00:53,  8.75it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2062/2529 [06:25<00:59,  7.87it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2063/2529 [06:25<01:02,  7.47it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2065/2529 [06:25<00:58,  7.97it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2066/2529 [06:25<00:59,  7.85it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2067/2529 [06:26<01:04,  7.18it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2068/2529 [06:26<01:03,  7.29it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2069/2529 [06:26<01:01,  7.42it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2070/2529 [06:26<01:01,  7.43it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2071/2529 [06:26<01:01,  7.46it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2072/2529 [06:26<01:12,  6.27it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2073/2529 [06:27<01:05,  6.92it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2074/2529 [06:27<01:04,  7.11it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2075/2529 [06:27<01:07,  6.74it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2076/2529 [06:27<01:11,  6.30it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2077/2529 [06:27<01:30,  5.01it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2078/2529 [06:27<01:20,  5.62it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2079/2529 [06:28<01:09,  6.47it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2080/2529 [06:28<01:04,  6.99it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2082/2529 [06:28<01:18,  5.67it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2083/2529 [06:28<01:20,  5.51it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2084/2529 [06:28<01:19,  5.57it/s]
Processing: negative r2g, BASC binarized:  82%|████████▏ | 2086/2529 [06:29<01:05,  6.73it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2087/2529 [06:29<01:01,  7.20it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2088/2529 [06:29<00:59,  7.46it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2089/2529 [06:29<00:58,  7.54it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2090/2529 [06:29<00:57,  7.59it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2091/2529 [06:30<01:27,  5.02it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2092/2529 [06:30<01:15,  5.78it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2093/2529 [06:30<01:17,  5.65it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2094/2529 [06:30<01:26,  5.03it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2095/2529 [06:30<01:13,  5.87it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2096/2529 [06:30<01:07,  6.46it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2097/2529 [06:30<01:01,  7.03it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2098/2529 [06:31<00:59,  7.29it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2099/2529 [06:31<00:58,  7.37it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2100/2529 [06:31<00:56,  7.62it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2101/2529 [06:31<00:59,  7.19it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2102/2529 [06:31<01:10,  6.07it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2103/2529 [06:31<01:02,  6.81it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2104/2529 [06:31<01:01,  6.93it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2105/2529 [06:31<00:55,  7.58it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2106/2529 [06:32<00:56,  7.50it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2107/2529 [06:32<00:54,  7.71it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2108/2529 [06:32<01:00,  6.99it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2109/2529 [06:32<01:02,  6.76it/s]
Processing: negative r2g, BASC binarized:  83%|████████▎ | 2110/2529 [06:32<01:03,  6.63it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2112/2529 [06:32<00:52,  7.89it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2113/2529 [06:33<00:52,  7.98it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2115/2529 [06:33<00:58,  7.07it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2116/2529 [06:33<00:56,  7.31it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2117/2529 [06:33<01:14,  5.51it/s]
Processing: negative r2g, BASC binarized:  84%|████████▎ | 2118/2529 [06:34<01:20,  5.11it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2119/2529 [06:34<01:11,  5.70it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2120/2529 [06:34<01:06,  6.12it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2122/2529 [06:34<00:56,  7.22it/s]

Processing: negative r2g, BASC binarized:  84%|████████▍ | 2123/2529 [06:34<00:53,  7.60it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2124/2529 [06:34<00:59,  6.78it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2125/2529 [06:34<00:54,  7.37it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2126/2529 [06:35<00:59,  6.80it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2128/2529 [06:35<00:51,  7.82it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2129/2529 [06:35<00:54,  7.32it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2130/2529 [06:35<00:51,  7.68it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2132/2529 [06:35<00:47,  8.28it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2133/2529 [06:35<00:48,  8.25it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2135/2529 [06:36<00:47,  8.29it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2136/2529 [06:36<00:49,  7.92it/s]
Processing: negative r2g, BASC binarized:  84%|████████▍ | 2137/2529 [06:36<00:47,  8.31it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2139/2529 [06:36<00:44,  8.76it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2140/2529 [06:36<00:47,  8.15it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2141/2529 [06:36<00:51,  7.58it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2142/2529 [06:37<00:53,  7.21it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2143/2529 [06:37<00:52,  7.37it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2144/2529 [06:37<00:51,  7.54it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2145/2529 [06:37<00:50,  7.60it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2146/2529 [06:37<00:48,  7.88it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2147/2529 [06:37<00:45,  8.38it/s]
Processing: negative r2g, BASC binarized:  85%|████████▍ | 2148/2529 [06:37<00:44,  8.60it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2150/2529 [06:38<00:40,  9.26it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2152/2529 [06:38<00:39,  9.60it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2153/2529 [06:38<00:40,  9.32it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2154/2529 [06:38<00:39,  9.41it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2155/2529 [06:38<00:44,  8.50it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2156/2529 [06:38<00:43,  8.57it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2157/2529 [06:38<00:42,  8.73it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2159/2529 [06:38<00:39,  9.43it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2161/2529 [06:39<00:38,  9.59it/s]
Processing: negative r2g, BASC binarized:  85%|████████▌ | 2162/2529 [06:39<00:39,  9.36it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2163/2529 [06:39<00:40,  9.02it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2164/2529 [06:39<00:39,  9.24it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2165/2529 [06:39<00:41,  8.82it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2166/2529 [06:39<00:40,  8.91it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2167/2529 [06:39<00:47,  7.68it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2168/2529 [06:40<00:44,  8.03it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2170/2529 [06:40<00:40,  8.90it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2171/2529 [06:40<00:44,  8.02it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2172/2529 [06:40<00:47,  7.45it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2173/2529 [06:40<00:46,  7.72it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2175/2529 [06:41<00:50,  7.07it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2176/2529 [06:41<00:46,  7.59it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2177/2529 [06:41<00:44,  7.84it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2179/2529 [06:41<00:41,  8.48it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2180/2529 [06:41<00:40,  8.55it/s]
Processing: negative r2g, BASC binarized:  86%|████████▌ | 2181/2529 [06:41<00:39,  8.79it/s]
Processing: negative r2g, BASC binarized:  86%|████████▋ | 2183/2529 [06:41<00:36,  9.38it/s]
Processing: negative r2g, BASC binarized:  86%|████████▋ | 2184/2529 [06:41<00:36,  9.34it/s]
Processing: negative r2g, BASC binarized:  86%|████████▋ | 2185/2529 [06:42<00:43,  7.95it/s]
Processing: negative r2g, BASC binarized:  86%|████████▋ | 2187/2529 [06:42<00:39,  8.76it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2188/2529 [06:42<00:39,  8.53it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2189/2529 [06:42<00:40,  8.30it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2191/2529 [06:42<00:37,  8.91it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2193/2529 [06:42<00:35,  9.53it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2194/2529 [06:43<00:39,  8.57it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2195/2529 [06:43<00:47,  7.08it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2196/2529 [06:43<00:44,  7.50it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2197/2529 [06:43<00:44,  7.41it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2198/2529 [06:43<00:42,  7.80it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2200/2529 [06:43<00:38,  8.65it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2201/2529 [06:44<00:38,  8.61it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2202/2529 [06:44<00:41,  7.96it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2204/2529 [06:44<00:37,  8.76it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2205/2529 [06:44<00:42,  7.64it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2206/2529 [06:44<00:40,  8.07it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2207/2529 [06:44<00:40,  7.92it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2208/2529 [06:44<00:38,  8.27it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2210/2529 [06:45<00:42,  7.53it/s]
Processing: negative r2g, BASC binarized:  87%|████████▋ | 2212/2529 [06:45<00:37,  8.52it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2214/2529 [06:45<00:34,  9.13it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2216/2529 [06:45<00:34,  9.03it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2217/2529 [06:45<00:34,  9.15it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2218/2529 [06:46<00:33,  9.29it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2220/2529 [06:46<00:32,  9.64it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2222/2529 [06:46<00:31,  9.82it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2223/2529 [06:46<00:33,  9.02it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2225/2529 [06:46<00:31,  9.56it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2226/2529 [06:46<00:40,  7.47it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2228/2529 [06:47<00:38,  7.78it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2230/2529 [06:47<00:40,  7.45it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2231/2529 [06:47<00:38,  7.84it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2233/2529 [06:47<00:36,  8.22it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2234/2529 [06:48<00:42,  6.91it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2235/2529 [06:48<00:47,  6.23it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2236/2529 [06:48<00:44,  6.60it/s]
Processing: negative r2g, BASC binarized:  88%|████████▊ | 2238/2529 [06:48<00:37,  7.79it/s]
Processing: negative r2g, BASC binarized:  89%|████████▊ | 2240/2529 [06:48<00:38,  7.53it/s]
Processing: negative r2g, BASC binarized:  89%|████████▊ | 2242/2529 [06:49<00:39,  7.26it/s]
Processing: negative r2g, BASC binarized:  89%|████████▊ | 2243/2529 [06:49<00:38,  7.48it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2245/2529 [06:49<00:35,  8.07it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2246/2529 [06:49<00:34,  8.18it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2247/2529 [06:49<00:39,  7.18it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2248/2529 [06:49<00:37,  7.43it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2249/2529 [06:50<00:41,  6.78it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2250/2529 [06:50<00:39,  7.14it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2251/2529 [06:50<00:36,  7.53it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2252/2529 [06:50<00:35,  7.80it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2254/2529 [06:50<00:31,  8.62it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2255/2529 [06:50<00:30,  8.89it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2257/2529 [06:50<00:28,  9.43it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2259/2529 [06:51<00:26, 10.00it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2260/2529 [06:51<00:33,  7.96it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2261/2529 [06:51<00:34,  7.67it/s]
Processing: negative r2g, BASC binarized:  89%|████████▉ | 2263/2529 [06:51<00:31,  8.34it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2264/2529 [06:51<00:30,  8.61it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2266/2529 [06:52<00:30,  8.65it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2267/2529 [06:52<00:29,  8.89it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2269/2529 [06:52<00:27,  9.32it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2270/2529 [06:52<00:30,  8.47it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2271/2529 [06:52<00:31,  8.13it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2272/2529 [06:52<00:31,  8.23it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2273/2529 [06:53<00:38,  6.69it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2274/2529 [06:53<00:35,  7.12it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2275/2529 [06:53<00:34,  7.43it/s]
Processing: negative r2g, BASC binarized:  90%|████████▉ | 2276/2529 [06:53<00:32,  7.70it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2278/2529 [06:53<00:33,  7.42it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2279/2529 [06:53<00:34,  7.34it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2280/2529 [06:53<00:31,  7.81it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2282/2529 [06:54<00:28,  8.75it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2283/2529 [06:54<00:28,  8.70it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2284/2529 [06:54<00:28,  8.52it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2285/2529 [06:54<00:27,  8.86it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2287/2529 [06:54<00:26,  9.14it/s]
Processing: negative r2g, BASC binarized:  90%|█████████ | 2288/2529 [06:54<00:28,  8.36it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2289/2529 [06:54<00:28,  8.44it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2290/2529 [06:55<00:30,  7.86it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2291/2529 [06:55<00:29,  8.08it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2292/2529 [06:55<00:27,  8.52it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2293/2529 [06:55<00:27,  8.65it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2294/2529 [06:55<00:28,  8.33it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2296/2529 [06:55<00:25,  9.28it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2297/2529 [06:55<00:24,  9.44it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2299/2529 [06:55<00:23,  9.79it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2301/2529 [06:56<00:26,  8.59it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2302/2529 [06:56<00:25,  8.82it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2304/2529 [06:56<00:29,  7.69it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2306/2529 [06:56<00:26,  8.49it/s]
Processing: negative r2g, BASC binarized:  91%|█████████ | 2307/2529 [06:57<00:28,  7.66it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2308/2529 [06:57<00:28,  7.63it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2309/2529 [06:57<00:28,  7.73it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2310/2529 [06:57<00:27,  7.89it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2311/2529 [06:57<00:26,  8.33it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2312/2529 [06:57<00:29,  7.27it/s]
Processing: negative r2g, BASC binarized:  91%|█████████▏| 2314/2529 [06:58<00:32,  6.67it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2315/2529 [06:58<00:32,  6.50it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2316/2529 [06:58<00:30,  6.97it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2317/2529 [06:58<00:28,  7.39it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2319/2529 [06:58<00:24,  8.48it/s]

Processing: negative r2g, BASC binarized:  92%|█████████▏| 2320/2529 [06:58<00:24,  8.48it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2321/2529 [06:58<00:24,  8.48it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2323/2529 [06:59<00:22,  9.05it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2325/2529 [06:59<00:24,  8.24it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2327/2529 [06:59<00:25,  7.95it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2329/2529 [06:59<00:22,  8.71it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2330/2529 [06:59<00:22,  8.86it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2332/2529 [07:00<00:22,  8.80it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2334/2529 [07:00<00:20,  9.30it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2335/2529 [07:00<00:20,  9.36it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2337/2529 [07:00<00:20,  9.21it/s]
Processing: negative r2g, BASC binarized:  92%|█████████▏| 2339/2529 [07:00<00:22,  8.56it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2341/2529 [07:01<00:21,  8.85it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2342/2529 [07:01<00:21,  8.58it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2343/2529 [07:01<00:21,  8.65it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2345/2529 [07:01<00:21,  8.48it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2346/2529 [07:01<00:21,  8.34it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2347/2529 [07:01<00:22,  8.23it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2348/2529 [07:01<00:21,  8.38it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2349/2529 [07:02<00:21,  8.48it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2351/2529 [07:02<00:24,  7.29it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2352/2529 [07:02<00:23,  7.56it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2353/2529 [07:02<00:25,  6.86it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2354/2529 [07:02<00:25,  6.86it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2356/2529 [07:03<00:21,  7.89it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2358/2529 [07:03<00:21,  8.13it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2360/2529 [07:03<00:20,  8.31it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2362/2529 [07:03<00:18,  8.92it/s]
Processing: negative r2g, BASC binarized:  93%|█████████▎| 2364/2529 [07:03<00:17,  9.27it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▎| 2365/2529 [07:04<00:17,  9.26it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▎| 2366/2529 [07:04<00:20,  8.00it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▎| 2368/2529 [07:04<00:19,  8.23it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▎| 2369/2529 [07:04<00:19,  8.01it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▎| 2370/2529 [07:04<00:19,  8.31it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2372/2529 [07:04<00:17,  8.76it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2373/2529 [07:05<00:21,  7.34it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2375/2529 [07:05<00:20,  7.65it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2377/2529 [07:05<00:19,  7.85it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2379/2529 [07:05<00:18,  8.09it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2380/2529 [07:05<00:17,  8.40it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2381/2529 [07:06<00:18,  7.97it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2382/2529 [07:06<00:17,  8.29it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2384/2529 [07:06<00:16,  8.97it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2386/2529 [07:06<00:15,  9.44it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2387/2529 [07:06<00:14,  9.55it/s]
Processing: negative r2g, BASC binarized:  94%|█████████▍| 2389/2529 [07:06<00:14,  9.87it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2390/2529 [07:06<00:14,  9.57it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2392/2529 [07:07<00:16,  8.29it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2393/2529 [07:07<00:15,  8.54it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2395/2529 [07:07<00:14,  9.20it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2396/2529 [07:07<00:15,  8.73it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2397/2529 [07:07<00:14,  8.82it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2398/2529 [07:07<00:14,  9.00it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2399/2529 [07:08<00:14,  8.87it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▍| 2401/2529 [07:08<00:13,  9.58it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2403/2529 [07:08<00:12, 10.04it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2405/2529 [07:08<00:14,  8.75it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2406/2529 [07:08<00:16,  7.64it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2407/2529 [07:09<00:16,  7.57it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2409/2529 [07:09<00:14,  8.40it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2410/2529 [07:09<00:13,  8.69it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2411/2529 [07:09<00:14,  8.27it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2413/2529 [07:09<00:12,  9.04it/s]
Processing: negative r2g, BASC binarized:  95%|█████████▌| 2414/2529 [07:09<00:13,  8.77it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2416/2529 [07:09<00:12,  9.20it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2417/2529 [07:10<00:12,  9.00it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2419/2529 [07:10<00:11,  9.49it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2420/2529 [07:10<00:12,  8.69it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2422/2529 [07:10<00:11,  9.08it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2424/2529 [07:10<00:11,  9.06it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2426/2529 [07:11<00:10,  9.37it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2427/2529 [07:11<00:10,  9.28it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2428/2529 [07:11<00:10,  9.29it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2429/2529 [07:11<00:11,  8.92it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2430/2529 [07:11<00:11,  8.92it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2431/2529 [07:11<00:10,  9.12it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2432/2529 [07:11<00:13,  7.32it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2433/2529 [07:11<00:12,  7.53it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▌| 2434/2529 [07:12<00:12,  7.81it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▋| 2436/2529 [07:12<00:12,  7.69it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▋| 2437/2529 [07:12<00:13,  6.97it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▋| 2438/2529 [07:12<00:12,  7.54it/s]
Processing: negative r2g, BASC binarized:  96%|█████████▋| 2440/2529 [07:12<00:10,  8.72it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2442/2529 [07:13<00:09,  9.31it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2444/2529 [07:13<00:08,  9.58it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2445/2529 [07:13<00:09,  9.05it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2446/2529 [07:13<00:09,  8.90it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2447/2529 [07:13<00:09,  8.69it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2448/2529 [07:13<00:09,  8.66it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2450/2529 [07:13<00:09,  8.55it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2452/2529 [07:14<00:08,  9.37it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2454/2529 [07:14<00:08,  8.53it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2455/2529 [07:14<00:10,  7.31it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2456/2529 [07:14<00:09,  7.63it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2458/2529 [07:14<00:08,  8.53it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2459/2529 [07:15<00:08,  8.59it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2461/2529 [07:15<00:08,  8.37it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2462/2529 [07:15<00:08,  8.17it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2464/2529 [07:15<00:07,  8.97it/s]
Processing: negative r2g, BASC binarized:  97%|█████████▋| 2465/2529 [07:15<00:07,  8.91it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2466/2529 [07:15<00:08,  7.44it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2468/2529 [07:16<00:07,  8.43it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2470/2529 [07:16<00:06,  9.07it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2471/2529 [07:16<00:06,  8.96it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2472/2529 [07:16<00:06,  9.01it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2473/2529 [07:16<00:06,  9.14it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2474/2529 [07:16<00:05,  9.23it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2475/2529 [07:16<00:05,  9.39it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2476/2529 [07:16<00:05,  9.14it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2477/2529 [07:17<00:06,  8.53it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2478/2529 [07:17<00:05,  8.85it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2479/2529 [07:17<00:05,  9.14it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2480/2529 [07:17<00:05,  8.42it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2482/2529 [07:17<00:05,  9.17it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2484/2529 [07:17<00:04,  9.43it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2486/2529 [07:18<00:04,  9.88it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2487/2529 [07:18<00:04,  9.66it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2489/2529 [07:18<00:04,  9.51it/s]
Processing: negative r2g, BASC binarized:  98%|█████████▊| 2491/2529 [07:18<00:03,  9.89it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▊| 2492/2529 [07:18<00:03,  9.85it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▊| 2494/2529 [07:18<00:03, 10.04it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▊| 2496/2529 [07:19<00:03,  8.54it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▊| 2497/2529 [07:19<00:03,  8.78it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2498/2529 [07:19<00:03,  8.56it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2499/2529 [07:19<00:04,  7.44it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2500/2529 [07:19<00:03,  7.86it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2501/2529 [07:19<00:03,  7.05it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2502/2529 [07:19<00:03,  7.52it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2504/2529 [07:20<00:03,  7.44it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2506/2529 [07:20<00:03,  7.63it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2508/2529 [07:20<00:02,  7.73it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2509/2529 [07:20<00:02,  8.04it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2510/2529 [07:20<00:02,  8.40it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2511/2529 [07:21<00:02,  8.59it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2512/2529 [07:21<00:01,  8.86it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2514/2529 [07:21<00:01,  8.13it/s]
Processing: negative r2g, BASC binarized:  99%|█████████▉| 2515/2529 [07:21<00:01,  8.43it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2517/2529 [07:21<00:01,  8.59it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2519/2529 [07:21<00:01,  8.25it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2520/2529 [07:22<00:01,  8.45it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2522/2529 [07:22<00:00,  8.97it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2524/2529 [07:22<00:00,  9.48it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2525/2529 [07:22<00:00,  8.83it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2527/2529 [07:22<00:00,  8.98it/s]
Processing: negative r2g, BASC binarized: 100%|█████████▉| 2528/2529 [07:22<00:00,  8.54it/s]
Processing: negative r2g, BASC binarized: 100%|██████████| 2529/2529 [07:23<00:00,  8.62it/s]
 50%|█████     | 7/14 [23:31<31:23, 269.06s/it]
Processing: positive r2g, 0.85 quantile:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, 0.85 quantile:   0%|          | 4/2529 [00:00<01:24, 29.73it/s]
Processing: positive r2g, 0.85 quantile:   0%|          | 8/2529 [00:00<01:19, 31.70it/s]
Processing: positive r2g, 0.85 quantile:   0%|          | 12/2529 [00:00<01:23, 30.14it/s]

Processing: positive r2g, 0.85 quantile:   1%|          | 16/2529 [00:00<01:19, 31.47it/s]
Processing: positive r2g, 0.85 quantile:   1%|          | 20/2529 [00:00<01:36, 26.07it/s]
Processing: positive r2g, 0.85 quantile:   1%|          | 23/2529 [00:00<01:39, 25.12it/s]
Processing: positive r2g, 0.85 quantile:   1%|          | 27/2529 [00:00<01:31, 27.46it/s]
Processing: positive r2g, 0.85 quantile:   1%|          | 30/2529 [00:01<01:39, 25.09it/s]
Processing: positive r2g, 0.85 quantile:   1%|▏         | 33/2529 [00:01<01:50, 22.64it/s]
Processing: positive r2g, 0.85 quantile:   1%|▏         | 37/2529 [00:01<01:40, 24.78it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 40/2529 [00:01<01:45, 23.50it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 44/2529 [00:01<01:34, 26.26it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 47/2529 [00:01<01:38, 25.24it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 50/2529 [00:01<01:44, 23.71it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 53/2529 [00:02<01:42, 24.16it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 57/2529 [00:02<01:29, 27.47it/s]
Processing: positive r2g, 0.85 quantile:   2%|▏         | 62/2529 [00:02<01:16, 32.36it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 66/2529 [00:02<01:13, 33.61it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 70/2529 [00:02<01:16, 32.25it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 74/2529 [00:02<01:31, 26.89it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 77/2529 [00:02<01:40, 24.45it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 81/2529 [00:02<01:28, 27.73it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 85/2529 [00:03<01:28, 27.54it/s]
Processing: positive r2g, 0.85 quantile:   3%|▎         | 88/2529 [00:03<01:35, 25.65it/s]
Processing: positive r2g, 0.85 quantile:   4%|▎         | 92/2529 [00:03<01:28, 27.54it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 96/2529 [00:03<01:24, 28.83it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 99/2529 [00:03<01:29, 27.23it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 102/2529 [00:03<01:40, 24.27it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 106/2529 [00:03<01:29, 27.19it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 109/2529 [00:04<01:27, 27.69it/s]
Processing: positive r2g, 0.85 quantile:   4%|▍         | 112/2529 [00:04<01:25, 28.22it/s]
Processing: positive r2g, 0.85 quantile:   5%|▍         | 115/2529 [00:04<01:45, 22.95it/s]
Processing: positive r2g, 0.85 quantile:   5%|▍         | 118/2529 [00:04<02:18, 17.43it/s]
Processing: positive r2g, 0.85 quantile:   5%|▍         | 121/2529 [00:04<02:19, 17.20it/s]
Processing: positive r2g, 0.85 quantile:   5%|▍         | 123/2529 [00:04<02:16, 17.69it/s]
Processing: positive r2g, 0.85 quantile:   5%|▍         | 125/2529 [00:04<02:14, 17.90it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 127/2529 [00:05<02:22, 16.86it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 129/2529 [00:05<02:29, 16.01it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 131/2529 [00:05<02:35, 15.45it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 133/2529 [00:05<02:51, 14.00it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 135/2529 [00:05<02:52, 13.89it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 137/2529 [00:05<03:02, 13.11it/s]
Processing: positive r2g, 0.85 quantile:   5%|▌         | 139/2529 [00:06<03:02, 13.10it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 142/2529 [00:06<02:37, 15.15it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 145/2529 [00:06<02:34, 15.42it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 147/2529 [00:06<02:26, 16.21it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 149/2529 [00:06<02:25, 16.41it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 154/2529 [00:06<01:49, 21.77it/s]
Processing: positive r2g, 0.85 quantile:   6%|▌         | 157/2529 [00:07<02:20, 16.90it/s]
Processing: positive r2g, 0.85 quantile:   6%|▋         | 159/2529 [00:07<02:28, 15.93it/s]
Processing: positive r2g, 0.85 quantile:   6%|▋         | 161/2529 [00:07<02:44, 14.39it/s]
Processing: positive r2g, 0.85 quantile:   6%|▋         | 163/2529 [00:07<02:45, 14.31it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 166/2529 [00:07<02:19, 16.98it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 168/2529 [00:07<02:24, 16.36it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 171/2529 [00:07<02:21, 16.64it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 173/2529 [00:08<02:28, 15.86it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 175/2529 [00:08<02:30, 15.61it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 177/2529 [00:08<02:22, 16.54it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 180/2529 [00:08<02:08, 18.35it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 184/2529 [00:08<01:49, 21.51it/s]
Processing: positive r2g, 0.85 quantile:   7%|▋         | 188/2529 [00:08<01:38, 23.73it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 191/2529 [00:08<01:42, 22.84it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 194/2529 [00:09<01:39, 23.58it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 197/2529 [00:09<01:32, 25.09it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 200/2529 [00:09<01:29, 26.03it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 203/2529 [00:09<01:31, 25.52it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 206/2529 [00:09<01:38, 23.60it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 209/2529 [00:09<01:32, 25.12it/s]
Processing: positive r2g, 0.85 quantile:   8%|▊         | 213/2529 [00:09<01:34, 24.44it/s]
Processing: positive r2g, 0.85 quantile:   9%|▊         | 216/2529 [00:09<01:37, 23.75it/s]
Processing: positive r2g, 0.85 quantile:   9%|▊         | 221/2529 [00:10<01:22, 27.93it/s]
Processing: positive r2g, 0.85 quantile:   9%|▉         | 225/2529 [00:10<01:25, 26.82it/s]
Processing: positive r2g, 0.85 quantile:   9%|▉         | 229/2529 [00:10<01:19, 29.08it/s]
Processing: positive r2g, 0.85 quantile:   9%|▉         | 233/2529 [00:10<01:16, 30.13it/s]
Processing: positive r2g, 0.85 quantile:   9%|▉         | 238/2529 [00:10<01:10, 32.72it/s]
Processing: positive r2g, 0.85 quantile:  10%|▉         | 242/2529 [00:10<01:16, 29.78it/s]
Processing: positive r2g, 0.85 quantile:  10%|▉         | 246/2529 [00:10<01:16, 29.79it/s]
Processing: positive r2g, 0.85 quantile:  10%|▉         | 250/2529 [00:11<01:25, 26.62it/s]
Processing: positive r2g, 0.85 quantile:  10%|█         | 254/2529 [00:11<01:18, 29.13it/s]
Processing: positive r2g, 0.85 quantile:  10%|█         | 258/2529 [00:11<01:18, 28.98it/s]
Processing: positive r2g, 0.85 quantile:  10%|█         | 262/2529 [00:11<01:25, 26.62it/s]
Processing: positive r2g, 0.85 quantile:  10%|█         | 265/2529 [00:11<01:26, 26.31it/s]
Processing: positive r2g, 0.85 quantile:  11%|█         | 270/2529 [00:11<01:13, 30.80it/s]
Processing: positive r2g, 0.85 quantile:  11%|█         | 274/2529 [00:11<01:18, 28.56it/s]
Processing: positive r2g, 0.85 quantile:  11%|█         | 278/2529 [00:11<01:13, 30.79it/s]
Processing: positive r2g, 0.85 quantile:  11%|█         | 282/2529 [00:12<01:15, 29.77it/s]
Processing: positive r2g, 0.85 quantile:  11%|█▏        | 286/2529 [00:12<01:12, 30.88it/s]
Processing: positive r2g, 0.85 quantile:  11%|█▏        | 290/2529 [00:12<01:17, 28.94it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 293/2529 [00:12<01:17, 28.67it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 296/2529 [00:12<01:17, 28.66it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 299/2529 [00:12<01:27, 25.56it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 303/2529 [00:12<01:22, 27.14it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 307/2529 [00:12<01:15, 29.30it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 311/2529 [00:13<01:10, 31.68it/s]
Processing: positive r2g, 0.85 quantile:  12%|█▏        | 315/2529 [00:13<01:06, 33.51it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 319/2529 [00:13<01:03, 34.78it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 323/2529 [00:13<01:08, 32.06it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 327/2529 [00:13<01:12, 30.32it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 331/2529 [00:13<01:17, 28.42it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 334/2529 [00:13<01:28, 24.71it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 337/2529 [00:14<01:27, 25.12it/s]
Processing: positive r2g, 0.85 quantile:  13%|█▎        | 340/2529 [00:14<01:24, 25.86it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▎        | 343/2529 [00:14<01:36, 22.56it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▎        | 346/2529 [00:14<01:32, 23.72it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 349/2529 [00:14<01:28, 24.55it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 353/2529 [00:14<01:21, 26.58it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 356/2529 [00:14<01:39, 21.87it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 359/2529 [00:15<01:56, 18.62it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 362/2529 [00:15<02:14, 16.06it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 364/2529 [00:15<02:23, 15.05it/s]
Processing: positive r2g, 0.85 quantile:  14%|█▍        | 366/2529 [00:15<02:42, 13.32it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▍        | 368/2529 [00:15<02:51, 12.57it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▍        | 370/2529 [00:16<02:51, 12.58it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▍        | 372/2529 [00:16<02:58, 12.12it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▍        | 374/2529 [00:16<02:57, 12.13it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▍        | 376/2529 [00:16<02:45, 12.98it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▌        | 380/2529 [00:16<01:57, 18.32it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▌        | 383/2529 [00:16<01:51, 19.29it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▌        | 386/2529 [00:16<01:39, 21.53it/s]
Processing: positive r2g, 0.85 quantile:  15%|█▌        | 389/2529 [00:17<01:33, 23.01it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 392/2529 [00:17<01:30, 23.73it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 395/2529 [00:17<01:39, 21.37it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 398/2529 [00:17<02:03, 17.21it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 400/2529 [00:17<02:08, 16.59it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 403/2529 [00:17<02:15, 15.74it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 406/2529 [00:18<01:56, 18.17it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▌        | 409/2529 [00:18<01:47, 19.68it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▋        | 412/2529 [00:18<01:53, 18.58it/s]
Processing: positive r2g, 0.85 quantile:  16%|█▋        | 416/2529 [00:18<01:36, 21.85it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 419/2529 [00:18<01:35, 21.98it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 422/2529 [00:18<01:28, 23.76it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 426/2529 [00:18<01:17, 27.18it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 429/2529 [00:18<01:27, 24.11it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 432/2529 [00:19<01:33, 22.38it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 435/2529 [00:19<01:33, 22.48it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 438/2529 [00:19<01:30, 23.03it/s]
Processing: positive r2g, 0.85 quantile:  17%|█▋        | 441/2529 [00:19<01:28, 23.60it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 444/2529 [00:19<01:30, 23.11it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 447/2529 [00:19<01:43, 20.06it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 450/2529 [00:20<01:53, 18.33it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 452/2529 [00:20<01:59, 17.40it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 455/2529 [00:20<01:45, 19.60it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 458/2529 [00:20<01:58, 17.52it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 460/2529 [00:20<02:02, 16.89it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 464/2529 [00:20<01:43, 19.86it/s]
Processing: positive r2g, 0.85 quantile:  18%|█▊        | 467/2529 [00:20<01:43, 19.90it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▊        | 470/2529 [00:21<01:55, 17.76it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▊        | 472/2529 [00:21<02:07, 16.09it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 475/2529 [00:21<01:52, 18.18it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 478/2529 [00:21<01:45, 19.53it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 481/2529 [00:21<01:44, 19.58it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 484/2529 [00:21<01:38, 20.86it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 489/2529 [00:21<01:16, 26.57it/s]
Processing: positive r2g, 0.85 quantile:  19%|█▉        | 493/2529 [00:22<01:14, 27.50it/s]
Processing: positive r2g, 0.85 quantile:  20%|█▉        | 497/2529 [00:22<01:08, 29.45it/s]
Processing: positive r2g, 0.85 quantile:  20%|█▉        | 502/2529 [00:22<01:01, 32.90it/s]
Processing: positive r2g, 0.85 quantile:  20%|██        | 506/2529 [00:22<01:03, 31.68it/s]

Processing: positive r2g, 0.85 quantile:  20%|██        | 510/2529 [00:22<01:11, 28.10it/s]
Processing: positive r2g, 0.85 quantile:  20%|██        | 513/2529 [00:22<01:21, 24.74it/s]
Processing: positive r2g, 0.85 quantile:  20%|██        | 518/2529 [00:22<01:07, 29.72it/s]
Processing: positive r2g, 0.85 quantile:  21%|██        | 522/2529 [00:23<01:09, 28.81it/s]
Processing: positive r2g, 0.85 quantile:  21%|██        | 526/2529 [00:23<01:20, 24.88it/s]
Processing: positive r2g, 0.85 quantile:  21%|██        | 531/2529 [00:23<01:09, 28.87it/s]
Processing: positive r2g, 0.85 quantile:  21%|██        | 536/2529 [00:23<01:05, 30.51it/s]
Processing: positive r2g, 0.85 quantile:  21%|██▏       | 540/2529 [00:23<01:13, 27.09it/s]
Processing: positive r2g, 0.85 quantile:  21%|██▏       | 543/2529 [00:23<01:21, 24.46it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 546/2529 [00:23<01:19, 25.10it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 551/2529 [00:24<01:08, 28.86it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 554/2529 [00:24<01:08, 28.83it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 558/2529 [00:24<01:06, 29.72it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 562/2529 [00:24<01:09, 28.26it/s]
Processing: positive r2g, 0.85 quantile:  22%|██▏       | 567/2529 [00:24<01:09, 28.28it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 570/2529 [00:24<01:10, 27.64it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 573/2529 [00:24<01:10, 27.64it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 576/2529 [00:25<01:18, 24.74it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 579/2529 [00:25<01:31, 21.41it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 583/2529 [00:25<01:22, 23.69it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 586/2529 [00:25<01:19, 24.51it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 590/2529 [00:25<01:13, 26.55it/s]
Processing: positive r2g, 0.85 quantile:  23%|██▎       | 593/2529 [00:25<01:15, 25.72it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▎       | 598/2529 [00:25<01:13, 26.24it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 601/2529 [00:26<01:12, 26.51it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 604/2529 [00:26<01:36, 19.98it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 607/2529 [00:26<01:42, 18.67it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 610/2529 [00:26<01:41, 18.96it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 613/2529 [00:26<01:34, 20.36it/s]
Processing: positive r2g, 0.85 quantile:  24%|██▍       | 616/2529 [00:26<01:26, 21.99it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▍       | 620/2529 [00:26<01:20, 23.77it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▍       | 623/2529 [00:27<01:21, 23.25it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▍       | 626/2529 [00:27<01:22, 23.16it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▍       | 630/2529 [00:27<01:11, 26.55it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▌       | 634/2529 [00:27<01:05, 29.14it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▌       | 638/2529 [00:27<01:19, 23.86it/s]
Processing: positive r2g, 0.85 quantile:  25%|██▌       | 641/2529 [00:27<01:17, 24.27it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 645/2529 [00:27<01:10, 26.73it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 649/2529 [00:28<01:06, 28.34it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 652/2529 [00:28<01:10, 26.56it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 656/2529 [00:28<01:08, 27.45it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 659/2529 [00:28<01:15, 24.85it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▌       | 662/2529 [00:28<01:14, 24.95it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▋       | 665/2529 [00:28<01:12, 25.64it/s]
Processing: positive r2g, 0.85 quantile:  26%|██▋       | 669/2529 [00:28<01:06, 27.89it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 672/2529 [00:28<01:07, 27.44it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 675/2529 [00:29<01:06, 27.93it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 678/2529 [00:29<01:11, 25.97it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 681/2529 [00:29<01:12, 25.50it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 684/2529 [00:29<01:13, 25.04it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 687/2529 [00:29<01:12, 25.34it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 690/2529 [00:29<01:33, 19.64it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 693/2529 [00:30<02:08, 14.28it/s]
Processing: positive r2g, 0.85 quantile:  27%|██▋       | 695/2529 [00:30<02:14, 13.66it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 697/2529 [00:30<02:12, 13.85it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 699/2529 [00:30<02:06, 14.49it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 701/2529 [00:30<02:12, 13.82it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 704/2529 [00:30<01:59, 15.27it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 707/2529 [00:31<01:47, 16.99it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 709/2529 [00:31<01:43, 17.54it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 712/2529 [00:31<01:32, 19.57it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 715/2529 [00:31<01:44, 17.39it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 717/2529 [00:31<01:50, 16.41it/s]
Processing: positive r2g, 0.85 quantile:  28%|██▊       | 719/2529 [00:31<01:48, 16.66it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▊       | 723/2529 [00:31<01:29, 20.14it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▉       | 728/2529 [00:31<01:12, 24.86it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▉       | 733/2529 [00:32<01:00, 29.45it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▉       | 737/2529 [00:32<01:30, 19.84it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▉       | 740/2529 [00:32<01:28, 20.12it/s]
Processing: positive r2g, 0.85 quantile:  29%|██▉       | 744/2529 [00:32<01:18, 22.88it/s]
Processing: positive r2g, 0.85 quantile:  30%|██▉       | 747/2529 [00:32<01:20, 22.07it/s]
Processing: positive r2g, 0.85 quantile:  30%|██▉       | 750/2529 [00:33<01:26, 20.61it/s]
Processing: positive r2g, 0.85 quantile:  30%|██▉       | 753/2529 [00:33<01:30, 19.60it/s]
Processing: positive r2g, 0.85 quantile:  30%|██▉       | 756/2529 [00:33<01:30, 19.62it/s]
Processing: positive r2g, 0.85 quantile:  30%|███       | 759/2529 [00:33<01:21, 21.66it/s]
Processing: positive r2g, 0.85 quantile:  30%|███       | 764/2529 [00:33<01:07, 26.30it/s]
Processing: positive r2g, 0.85 quantile:  30%|███       | 767/2529 [00:33<01:12, 24.17it/s]
Processing: positive r2g, 0.85 quantile:  30%|███       | 771/2529 [00:33<01:03, 27.55it/s]
Processing: positive r2g, 0.85 quantile:  31%|███       | 775/2529 [00:33<00:57, 30.53it/s]
Processing: positive r2g, 0.85 quantile:  31%|███       | 779/2529 [00:34<01:01, 28.48it/s]
Processing: positive r2g, 0.85 quantile:  31%|███       | 783/2529 [00:34<01:05, 26.52it/s]
Processing: positive r2g, 0.85 quantile:  31%|███       | 786/2529 [00:34<01:06, 26.23it/s]
Processing: positive r2g, 0.85 quantile:  31%|███       | 789/2529 [00:34<01:16, 22.62it/s]
Processing: positive r2g, 0.85 quantile:  31%|███▏      | 792/2529 [00:34<01:31, 19.07it/s]
Processing: positive r2g, 0.85 quantile:  31%|███▏      | 796/2529 [00:35<01:31, 19.03it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 799/2529 [00:35<01:31, 18.99it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 803/2529 [00:35<01:20, 21.55it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 806/2529 [00:35<01:37, 17.74it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 808/2529 [00:35<01:43, 16.56it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 812/2529 [00:35<01:27, 19.62it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 815/2529 [00:36<01:26, 19.88it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 818/2529 [00:36<01:18, 21.93it/s]
Processing: positive r2g, 0.85 quantile:  32%|███▏      | 821/2529 [00:36<01:15, 22.48it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 825/2529 [00:36<01:09, 24.43it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 828/2529 [00:36<01:28, 19.27it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 832/2529 [00:36<01:15, 22.45it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 835/2529 [00:36<01:13, 23.17it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 838/2529 [00:36<01:09, 24.30it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 842/2529 [00:37<01:04, 26.24it/s]
Processing: positive r2g, 0.85 quantile:  33%|███▎      | 845/2529 [00:37<01:02, 26.87it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▎      | 848/2529 [00:37<01:03, 26.48it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▎      | 851/2529 [00:37<01:02, 26.64it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▍      | 855/2529 [00:37<00:55, 30.01it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▍      | 860/2529 [00:37<00:50, 33.12it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▍      | 864/2529 [00:37<00:51, 32.33it/s]
Processing: positive r2g, 0.85 quantile:  34%|███▍      | 869/2529 [00:37<00:47, 34.73it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▍      | 873/2529 [00:38<00:46, 35.27it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▍      | 877/2529 [00:38<00:47, 34.42it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▍      | 881/2529 [00:38<00:53, 30.99it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▍      | 885/2529 [00:38<00:57, 28.75it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▌      | 889/2529 [00:38<00:53, 30.92it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▌      | 893/2529 [00:38<00:52, 31.20it/s]
Processing: positive r2g, 0.85 quantile:  35%|███▌      | 897/2529 [00:38<00:49, 32.70it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▌      | 901/2529 [00:38<00:54, 29.61it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▌      | 905/2529 [00:39<00:59, 27.12it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▌      | 909/2529 [00:39<00:56, 28.53it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▌      | 912/2529 [00:39<00:57, 28.18it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▌      | 916/2529 [00:39<00:52, 30.70it/s]
Processing: positive r2g, 0.85 quantile:  36%|███▋      | 920/2529 [00:39<00:54, 29.42it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 925/2529 [00:39<00:47, 33.95it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 930/2529 [00:39<00:42, 37.84it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 934/2529 [00:40<00:50, 31.28it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 938/2529 [00:40<00:53, 29.71it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 942/2529 [00:40<01:09, 22.89it/s]
Processing: positive r2g, 0.85 quantile:  37%|███▋      | 946/2529 [00:40<01:00, 26.08it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 950/2529 [00:40<00:57, 27.62it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 954/2529 [00:40<00:58, 27.08it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 957/2529 [00:40<00:58, 26.80it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 962/2529 [00:41<00:50, 30.77it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 966/2529 [00:41<00:52, 29.79it/s]
Processing: positive r2g, 0.85 quantile:  38%|███▊      | 970/2529 [00:41<00:50, 30.57it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▊      | 974/2529 [00:41<00:47, 32.56it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▊      | 978/2529 [00:41<00:54, 28.24it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▉      | 982/2529 [00:41<00:51, 30.16it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▉      | 986/2529 [00:41<00:54, 28.52it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▉      | 990/2529 [00:42<00:50, 30.42it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▉      | 994/2529 [00:42<00:50, 30.50it/s]
Processing: positive r2g, 0.85 quantile:  39%|███▉      | 998/2529 [00:42<00:48, 31.69it/s]
Processing: positive r2g, 0.85 quantile:  40%|███▉      | 1003/2529 [00:42<00:44, 34.08it/s]
Processing: positive r2g, 0.85 quantile:  40%|███▉      | 1007/2529 [00:42<00:46, 32.68it/s]
Processing: positive r2g, 0.85 quantile:  40%|███▉      | 1011/2529 [00:42<00:54, 28.02it/s]
Processing: positive r2g, 0.85 quantile:  40%|████      | 1014/2529 [00:42<00:55, 27.38it/s]
Processing: positive r2g, 0.85 quantile:  40%|████      | 1017/2529 [00:43<01:03, 23.63it/s]
Processing: positive r2g, 0.85 quantile:  40%|████      | 1022/2529 [00:43<00:53, 27.96it/s]
Processing: positive r2g, 0.85 quantile:  41%|████      | 1026/2529 [00:43<00:53, 28.28it/s]
Processing: positive r2g, 0.85 quantile:  41%|████      | 1029/2529 [00:43<00:52, 28.35it/s]
Processing: positive r2g, 0.85 quantile:  41%|████      | 1033/2529 [00:43<00:48, 30.92it/s]
Processing: positive r2g, 0.85 quantile:  41%|████      | 1037/2529 [00:43<00:45, 33.11it/s]
Processing: positive r2g, 0.85 quantile:  41%|████      | 1041/2529 [00:43<00:48, 30.82it/s]
Processing: positive r2g, 0.85 quantile:  41%|████▏     | 1045/2529 [00:43<00:48, 30.60it/s]
Processing: positive r2g, 0.85 quantile:  41%|████▏     | 1049/2529 [00:43<00:46, 31.55it/s]
Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1053/2529 [00:44<00:57, 25.47it/s]
Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1057/2529 [00:44<00:52, 28.05it/s]
Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1061/2529 [00:44<00:47, 30.81it/s]

Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1065/2529 [00:44<00:47, 30.51it/s]
Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1069/2529 [00:44<00:48, 30.30it/s]
Processing: positive r2g, 0.85 quantile:  42%|████▏     | 1073/2529 [00:44<00:50, 28.68it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1077/2529 [00:44<00:49, 29.17it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1080/2529 [00:45<00:49, 29.27it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1085/2529 [00:45<00:42, 34.06it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1089/2529 [00:45<00:44, 32.03it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1093/2529 [00:45<00:43, 33.30it/s]
Processing: positive r2g, 0.85 quantile:  43%|████▎     | 1097/2529 [00:45<00:41, 34.63it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▎     | 1102/2529 [00:45<00:41, 34.26it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▎     | 1106/2529 [00:45<00:44, 31.78it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▍     | 1110/2529 [00:45<00:43, 32.91it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▍     | 1114/2529 [00:46<00:41, 33.82it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▍     | 1118/2529 [00:46<00:40, 34.48it/s]
Processing: positive r2g, 0.85 quantile:  44%|████▍     | 1122/2529 [00:46<00:39, 35.22it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▍     | 1126/2529 [00:46<00:40, 34.69it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▍     | 1130/2529 [00:46<00:48, 28.72it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▍     | 1134/2529 [00:46<00:48, 28.97it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▌     | 1139/2529 [00:46<00:41, 33.50it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▌     | 1143/2529 [00:46<00:41, 33.16it/s]
Processing: positive r2g, 0.85 quantile:  45%|████▌     | 1147/2529 [00:47<00:41, 33.60it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▌     | 1151/2529 [00:47<00:41, 33.13it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▌     | 1155/2529 [00:47<00:43, 31.77it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▌     | 1159/2529 [00:47<00:44, 30.82it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▌     | 1163/2529 [00:47<00:44, 30.70it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▌     | 1168/2529 [00:47<00:40, 33.63it/s]
Processing: positive r2g, 0.85 quantile:  46%|████▋     | 1172/2529 [00:47<00:41, 33.04it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1176/2529 [00:47<00:40, 33.42it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1181/2529 [00:48<00:36, 37.03it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1185/2529 [00:48<00:35, 37.40it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1190/2529 [00:48<00:38, 35.14it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1194/2529 [00:48<00:41, 32.00it/s]
Processing: positive r2g, 0.85 quantile:  47%|████▋     | 1198/2529 [00:48<00:46, 28.69it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1202/2529 [00:48<00:46, 28.37it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1207/2529 [00:48<00:44, 29.65it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1211/2529 [00:49<00:43, 30.21it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1215/2529 [00:49<00:42, 31.27it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1219/2529 [00:49<00:43, 29.94it/s]
Processing: positive r2g, 0.85 quantile:  48%|████▊     | 1223/2529 [00:49<00:41, 31.27it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▊     | 1227/2529 [00:49<00:43, 30.27it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▊     | 1231/2529 [00:49<00:42, 30.89it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▉     | 1235/2529 [00:49<00:43, 29.92it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▉     | 1239/2529 [00:50<00:43, 29.97it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▉     | 1243/2529 [00:50<00:55, 23.29it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▉     | 1246/2529 [00:50<01:01, 21.02it/s]
Processing: positive r2g, 0.85 quantile:  49%|████▉     | 1249/2529 [00:50<01:00, 21.09it/s]
Processing: positive r2g, 0.85 quantile:  50%|████▉     | 1253/2529 [00:50<00:52, 24.28it/s]
Processing: positive r2g, 0.85 quantile:  50%|████▉     | 1256/2529 [00:50<01:00, 21.21it/s]
Processing: positive r2g, 0.85 quantile:  50%|████▉     | 1259/2529 [00:51<01:02, 20.23it/s]
Processing: positive r2g, 0.85 quantile:  50%|████▉     | 1263/2529 [00:51<00:54, 23.41it/s]
Processing: positive r2g, 0.85 quantile:  50%|█████     | 1266/2529 [00:51<00:53, 23.67it/s]
Processing: positive r2g, 0.85 quantile:  50%|█████     | 1269/2529 [00:51<00:54, 23.21it/s]
Processing: positive r2g, 0.85 quantile:  50%|█████     | 1272/2529 [00:51<00:50, 24.78it/s]
Processing: positive r2g, 0.85 quantile:  50%|█████     | 1275/2529 [00:51<00:58, 21.61it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████     | 1278/2529 [00:51<00:59, 21.01it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████     | 1281/2529 [00:52<00:55, 22.48it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████     | 1285/2529 [00:52<00:46, 26.57it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████     | 1290/2529 [00:52<00:39, 31.08it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████     | 1295/2529 [00:52<00:36, 33.79it/s]
Processing: positive r2g, 0.85 quantile:  51%|█████▏    | 1299/2529 [00:52<00:37, 32.67it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1303/2529 [00:52<00:44, 27.44it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1306/2529 [00:52<00:48, 25.30it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1310/2529 [00:52<00:45, 26.99it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1315/2529 [00:53<00:40, 29.94it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1319/2529 [00:53<00:43, 27.75it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1322/2529 [00:53<00:44, 27.29it/s]
Processing: positive r2g, 0.85 quantile:  52%|█████▏    | 1326/2529 [00:53<00:43, 27.63it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1329/2529 [00:53<00:42, 28.15it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1332/2529 [00:53<00:46, 25.99it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1335/2529 [00:53<00:51, 23.24it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1339/2529 [00:54<00:44, 26.50it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1342/2529 [00:54<00:43, 27.35it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1346/2529 [00:54<00:41, 28.44it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1349/2529 [00:54<00:57, 20.49it/s]
Processing: positive r2g, 0.85 quantile:  53%|█████▎    | 1352/2529 [00:54<01:09, 17.04it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▎    | 1355/2529 [00:55<01:13, 16.02it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▎    | 1357/2529 [00:55<01:10, 16.58it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1361/2529 [00:55<01:08, 17.14it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1363/2529 [00:55<01:11, 16.36it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1365/2529 [00:55<01:15, 15.35it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1367/2529 [00:55<01:22, 14.14it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1369/2529 [00:55<01:24, 13.69it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1371/2529 [00:56<01:29, 12.87it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1373/2529 [00:56<01:29, 12.98it/s]
Processing: positive r2g, 0.85 quantile:  54%|█████▍    | 1376/2529 [00:56<01:16, 15.08it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▍    | 1379/2529 [00:56<01:14, 15.41it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▍    | 1381/2529 [00:56<01:10, 16.25it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▍    | 1383/2529 [00:56<01:09, 16.48it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▍    | 1388/2529 [00:56<00:52, 21.67it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1391/2529 [00:57<01:08, 16.60it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1393/2529 [00:57<01:12, 15.71it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1395/2529 [00:57<01:19, 14.28it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1397/2529 [00:57<01:20, 14.12it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1400/2529 [00:57<01:07, 16.84it/s]
Processing: positive r2g, 0.85 quantile:  55%|█████▌    | 1402/2529 [00:58<01:09, 16.24it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1405/2529 [00:58<00:59, 18.90it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1408/2529 [00:58<01:08, 16.32it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1410/2529 [00:58<01:10, 15.86it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1412/2529 [00:58<01:06, 16.69it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1415/2529 [00:58<01:00, 18.39it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▌    | 1419/2529 [00:58<00:52, 21.28it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▋    | 1423/2529 [00:59<00:47, 23.28it/s]
Processing: positive r2g, 0.85 quantile:  56%|█████▋    | 1426/2529 [00:59<00:49, 22.22it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1429/2529 [00:59<00:48, 22.62it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1432/2529 [00:59<00:46, 23.78it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1435/2529 [00:59<00:43, 25.03it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1438/2529 [00:59<00:43, 25.27it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1441/2529 [00:59<00:51, 21.16it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1444/2529 [00:59<00:47, 23.06it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1448/2529 [01:00<00:41, 25.92it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1451/2529 [01:00<00:50, 21.56it/s]
Processing: positive r2g, 0.85 quantile:  57%|█████▋    | 1454/2529 [01:00<00:47, 22.67it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1458/2529 [01:00<00:41, 26.12it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1461/2529 [01:00<00:40, 26.44it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1464/2529 [01:00<00:42, 25.35it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1468/2529 [01:00<00:36, 28.90it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1472/2529 [01:00<00:36, 29.27it/s]
Processing: positive r2g, 0.85 quantile:  58%|█████▊    | 1476/2529 [01:01<00:33, 31.85it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▊    | 1480/2529 [01:01<00:35, 29.58it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▊    | 1484/2529 [01:01<00:33, 31.10it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▉    | 1488/2529 [01:01<00:37, 27.69it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▉    | 1491/2529 [01:01<00:39, 26.18it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▉    | 1495/2529 [01:01<00:35, 29.14it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▉    | 1499/2529 [01:01<00:33, 30.46it/s]
Processing: positive r2g, 0.85 quantile:  59%|█████▉    | 1503/2529 [01:01<00:32, 31.33it/s]
Processing: positive r2g, 0.85 quantile:  60%|█████▉    | 1507/2529 [01:02<00:39, 25.75it/s]
Processing: positive r2g, 0.85 quantile:  60%|█████▉    | 1511/2529 [01:02<00:36, 27.79it/s]
Processing: positive r2g, 0.85 quantile:  60%|█████▉    | 1514/2529 [01:02<00:36, 27.68it/s]
Processing: positive r2g, 0.85 quantile:  60%|█████▉    | 1517/2529 [01:02<00:38, 26.06it/s]
Processing: positive r2g, 0.85 quantile:  60%|██████    | 1521/2529 [01:02<00:35, 28.77it/s]
Processing: positive r2g, 0.85 quantile:  60%|██████    | 1524/2529 [01:02<00:34, 28.84it/s]
Processing: positive r2g, 0.85 quantile:  60%|██████    | 1527/2529 [01:02<00:34, 28.71it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1531/2529 [01:03<00:33, 29.53it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1534/2529 [01:03<00:36, 27.05it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1537/2529 [01:03<00:36, 27.11it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1540/2529 [01:03<00:35, 27.48it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1543/2529 [01:03<00:40, 24.62it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████    | 1547/2529 [01:03<00:37, 26.53it/s]
Processing: positive r2g, 0.85 quantile:  61%|██████▏   | 1552/2529 [01:03<00:32, 30.52it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1556/2529 [01:03<00:30, 31.39it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1560/2529 [01:03<00:28, 33.59it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1564/2529 [01:04<00:29, 32.22it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1568/2529 [01:04<00:31, 30.25it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1572/2529 [01:04<00:32, 29.85it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1576/2529 [01:04<00:29, 32.02it/s]
Processing: positive r2g, 0.85 quantile:  62%|██████▏   | 1580/2529 [01:04<00:33, 28.54it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1583/2529 [01:04<00:39, 23.96it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1586/2529 [01:04<00:38, 24.51it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1589/2529 [01:05<00:36, 25.44it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1592/2529 [01:05<00:43, 21.43it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1595/2529 [01:05<00:42, 21.87it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1598/2529 [01:05<00:40, 22.92it/s]

Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1602/2529 [01:05<00:37, 24.79it/s]
Processing: positive r2g, 0.85 quantile:  63%|██████▎   | 1605/2529 [01:05<00:45, 20.51it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▎   | 1608/2529 [01:06<00:50, 18.08it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▎   | 1610/2529 [01:06<00:55, 16.47it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▎   | 1612/2529 [01:06<01:01, 14.92it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1614/2529 [01:06<01:09, 13.13it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1616/2529 [01:06<01:10, 12.87it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1618/2529 [01:06<01:14, 12.17it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1620/2529 [01:07<01:16, 11.82it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1622/2529 [01:07<01:19, 11.43it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1624/2529 [01:07<01:18, 11.49it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1626/2529 [01:07<01:12, 12.49it/s]
Processing: positive r2g, 0.85 quantile:  64%|██████▍   | 1630/2529 [01:07<00:51, 17.29it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▍   | 1633/2529 [01:07<00:47, 19.02it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▍   | 1636/2529 [01:08<00:47, 18.98it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▍   | 1639/2529 [01:08<00:44, 20.10it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▍   | 1642/2529 [01:08<00:41, 21.27it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▌   | 1645/2529 [01:08<00:39, 22.65it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▌   | 1648/2529 [01:08<00:50, 17.54it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▌   | 1650/2529 [01:08<00:53, 16.42it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▌   | 1652/2529 [01:08<00:55, 15.82it/s]
Processing: positive r2g, 0.85 quantile:  65%|██████▌   | 1655/2529 [01:09<00:58, 15.01it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1658/2529 [01:09<00:49, 17.58it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1661/2529 [01:09<00:44, 19.37it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1664/2529 [01:09<00:46, 18.45it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1666/2529 [01:09<00:46, 18.62it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1670/2529 [01:09<00:39, 21.66it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▌   | 1673/2529 [01:09<00:36, 23.18it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▋   | 1676/2529 [01:10<00:35, 24.10it/s]
Processing: positive r2g, 0.85 quantile:  66%|██████▋   | 1680/2529 [01:10<00:30, 27.84it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1683/2529 [01:10<00:35, 23.60it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1686/2529 [01:10<00:40, 20.58it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1690/2529 [01:10<00:36, 23.15it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1693/2529 [01:10<00:37, 22.22it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1697/2529 [01:10<00:35, 23.16it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1700/2529 [01:11<00:43, 19.14it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1703/2529 [01:11<00:47, 17.56it/s]
Processing: positive r2g, 0.85 quantile:  67%|██████▋   | 1706/2529 [01:11<00:45, 17.92it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1708/2529 [01:11<00:47, 17.24it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1711/2529 [01:11<00:45, 17.99it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1713/2529 [01:12<00:48, 16.68it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1715/2529 [01:12<00:50, 16.23it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1717/2529 [01:12<00:53, 15.22it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1720/2529 [01:12<00:44, 18.35it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1723/2529 [01:12<00:39, 20.26it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1726/2529 [01:12<00:46, 17.37it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1728/2529 [01:12<00:49, 16.25it/s]
Processing: positive r2g, 0.85 quantile:  68%|██████▊   | 1730/2529 [01:13<00:53, 14.93it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▊   | 1733/2529 [01:13<00:44, 17.90it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▊   | 1736/2529 [01:13<00:40, 19.47it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1739/2529 [01:13<00:37, 21.00it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1742/2529 [01:13<00:41, 18.75it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1745/2529 [01:13<00:37, 20.87it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1749/2529 [01:13<00:32, 23.80it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1752/2529 [01:13<00:32, 23.98it/s]
Processing: positive r2g, 0.85 quantile:  69%|██████▉   | 1755/2529 [01:14<00:31, 24.19it/s]
Processing: positive r2g, 0.85 quantile:  70%|██████▉   | 1759/2529 [01:14<00:28, 26.89it/s]
Processing: positive r2g, 0.85 quantile:  70%|██████▉   | 1764/2529 [01:14<00:23, 32.49it/s]
Processing: positive r2g, 0.85 quantile:  70%|██████▉   | 1768/2529 [01:14<00:23, 31.95it/s]
Processing: positive r2g, 0.85 quantile:  70%|███████   | 1772/2529 [01:14<00:25, 29.29it/s]
Processing: positive r2g, 0.85 quantile:  70%|███████   | 1776/2529 [01:14<00:27, 27.61it/s]
Processing: positive r2g, 0.85 quantile:  70%|███████   | 1779/2529 [01:14<00:29, 25.75it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████   | 1784/2529 [01:15<00:24, 30.26it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████   | 1788/2529 [01:15<00:31, 23.39it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████   | 1791/2529 [01:15<00:31, 23.46it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████   | 1795/2529 [01:15<00:27, 26.77it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████   | 1800/2529 [01:15<00:25, 28.85it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████▏  | 1804/2529 [01:15<00:27, 26.61it/s]
Processing: positive r2g, 0.85 quantile:  71%|███████▏  | 1807/2529 [01:16<00:29, 24.16it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1810/2529 [01:16<00:30, 23.88it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1814/2529 [01:16<00:26, 27.13it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1818/2529 [01:16<00:24, 29.60it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1822/2529 [01:16<00:23, 29.83it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1826/2529 [01:16<00:24, 29.12it/s]
Processing: positive r2g, 0.85 quantile:  72%|███████▏  | 1829/2529 [01:16<00:26, 26.92it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1834/2529 [01:16<00:25, 27.35it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1837/2529 [01:17<00:28, 24.02it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1840/2529 [01:17<00:28, 24.05it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1843/2529 [01:17<00:31, 21.72it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1846/2529 [01:17<00:35, 19.20it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1849/2529 [01:17<00:32, 20.85it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1852/2529 [01:17<00:32, 20.99it/s]
Processing: positive r2g, 0.85 quantile:  73%|███████▎  | 1855/2529 [01:17<00:30, 22.45it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▎  | 1859/2529 [01:18<00:28, 23.92it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▎  | 1863/2529 [01:18<00:25, 25.74it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1868/2529 [01:18<00:25, 26.30it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1871/2529 [01:18<00:25, 26.30it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1874/2529 [01:18<00:33, 19.55it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1877/2529 [01:19<00:35, 18.37it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1880/2529 [01:19<00:34, 18.61it/s]
Processing: positive r2g, 0.85 quantile:  74%|███████▍  | 1883/2529 [01:19<00:32, 20.03it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▍  | 1886/2529 [01:19<00:29, 21.79it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▍  | 1889/2529 [01:19<00:27, 23.52it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▍  | 1892/2529 [01:19<00:26, 24.26it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▍  | 1895/2529 [01:19<00:27, 22.65it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▌  | 1898/2529 [01:19<00:27, 23.10it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▌  | 1902/2529 [01:20<00:24, 26.04it/s]
Processing: positive r2g, 0.85 quantile:  75%|███████▌  | 1906/2529 [01:20<00:21, 28.90it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1910/2529 [01:20<00:24, 25.27it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1913/2529 [01:20<00:26, 23.35it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1916/2529 [01:20<00:25, 24.00it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1920/2529 [01:20<00:22, 26.71it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1924/2529 [01:20<00:22, 27.25it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▌  | 1928/2529 [01:21<00:22, 26.30it/s]
Processing: positive r2g, 0.85 quantile:  76%|███████▋  | 1933/2529 [01:21<00:19, 30.05it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1937/2529 [01:21<00:23, 24.71it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1940/2529 [01:21<00:25, 23.38it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1943/2529 [01:21<00:24, 24.27it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1947/2529 [01:21<00:21, 26.72it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1950/2529 [01:21<00:22, 25.84it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1953/2529 [01:22<00:23, 24.91it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1956/2529 [01:22<00:25, 22.45it/s]
Processing: positive r2g, 0.85 quantile:  77%|███████▋  | 1959/2529 [01:22<00:23, 23.82it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1962/2529 [01:22<00:24, 23.24it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1965/2529 [01:22<00:24, 22.81it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1968/2529 [01:22<00:24, 22.53it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1971/2529 [01:23<00:38, 14.60it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1973/2529 [01:23<00:44, 12.58it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1975/2529 [01:23<00:43, 12.63it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1977/2529 [01:23<00:42, 12.89it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1979/2529 [01:23<00:42, 12.88it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1981/2529 [01:23<00:42, 13.02it/s]
Processing: positive r2g, 0.85 quantile:  78%|███████▊  | 1984/2529 [01:24<00:36, 14.86it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▊  | 1987/2529 [01:24<00:31, 17.24it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▊  | 1989/2529 [01:24<00:31, 17.35it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 1992/2529 [01:24<00:27, 19.84it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 1995/2529 [01:24<00:28, 18.50it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 1998/2529 [01:24<00:30, 17.24it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 2001/2529 [01:24<00:29, 17.82it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 2005/2529 [01:25<00:24, 21.30it/s]
Processing: positive r2g, 0.85 quantile:  79%|███████▉  | 2009/2529 [01:25<00:20, 25.03it/s]
Processing: positive r2g, 0.85 quantile:  80%|███████▉  | 2013/2529 [01:25<00:19, 26.89it/s]
Processing: positive r2g, 0.85 quantile:  80%|███████▉  | 2017/2529 [01:25<00:22, 22.87it/s]
Processing: positive r2g, 0.85 quantile:  80%|███████▉  | 2020/2529 [01:25<00:26, 19.33it/s]
Processing: positive r2g, 0.85 quantile:  80%|███████▉  | 2023/2529 [01:25<00:25, 19.74it/s]
Processing: positive r2g, 0.85 quantile:  80%|████████  | 2027/2529 [01:26<00:21, 23.19it/s]
Processing: positive r2g, 0.85 quantile:  80%|████████  | 2030/2529 [01:26<00:21, 23.21it/s]
Processing: positive r2g, 0.85 quantile:  80%|████████  | 2033/2529 [01:26<00:24, 20.25it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2036/2529 [01:26<00:24, 20.06it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2039/2529 [01:26<00:24, 20.01it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2042/2529 [01:26<00:23, 20.74it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2046/2529 [01:26<00:19, 24.98it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2050/2529 [01:27<00:18, 26.13it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████  | 2053/2529 [01:27<00:17, 26.60it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████▏ | 2057/2529 [01:27<00:15, 29.58it/s]
Processing: positive r2g, 0.85 quantile:  81%|████████▏ | 2061/2529 [01:27<00:15, 31.10it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2065/2529 [01:27<00:16, 27.52it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2068/2529 [01:27<00:18, 25.56it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2071/2529 [01:27<00:17, 25.55it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2074/2529 [01:27<00:19, 23.64it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2077/2529 [01:28<00:23, 18.88it/s]
Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2081/2529 [01:28<00:19, 22.56it/s]

Processing: positive r2g, 0.85 quantile:  82%|████████▏ | 2084/2529 [01:28<00:25, 17.69it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2088/2529 [01:28<00:20, 21.49it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2091/2529 [01:28<00:24, 17.99it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2094/2529 [01:29<00:25, 17.22it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2098/2529 [01:29<00:21, 20.50it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2101/2529 [01:29<00:20, 21.03it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2104/2529 [01:29<00:20, 20.75it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2108/2529 [01:29<00:18, 22.24it/s]
Processing: positive r2g, 0.85 quantile:  83%|████████▎ | 2111/2529 [01:29<00:18, 22.86it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▎ | 2115/2529 [01:29<00:17, 23.28it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▎ | 2118/2529 [01:30<00:22, 18.38it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▍ | 2122/2529 [01:30<00:18, 21.59it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▍ | 2125/2529 [01:30<00:17, 22.62it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▍ | 2128/2529 [01:30<00:16, 23.94it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▍ | 2132/2529 [01:30<00:15, 25.78it/s]
Processing: positive r2g, 0.85 quantile:  84%|████████▍ | 2135/2529 [01:30<00:14, 26.67it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▍ | 2139/2529 [01:30<00:13, 29.17it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▍ | 2143/2529 [01:31<00:14, 25.96it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▍ | 2147/2529 [01:31<00:13, 28.26it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▌ | 2152/2529 [01:31<00:11, 32.51it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▌ | 2156/2529 [01:31<00:11, 31.85it/s]
Processing: positive r2g, 0.85 quantile:  85%|████████▌ | 2161/2529 [01:31<00:10, 35.51it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▌ | 2165/2529 [01:31<00:10, 34.64it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▌ | 2169/2529 [01:31<00:10, 33.70it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▌ | 2173/2529 [01:31<00:11, 30.54it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▌ | 2177/2529 [01:32<00:12, 28.88it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▌ | 2181/2529 [01:32<00:11, 30.96it/s]
Processing: positive r2g, 0.85 quantile:  86%|████████▋ | 2185/2529 [01:32<00:11, 30.77it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2189/2529 [01:32<00:10, 32.31it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2194/2529 [01:32<00:09, 33.75it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2198/2529 [01:32<00:11, 29.57it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2202/2529 [01:32<00:10, 30.36it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2206/2529 [01:33<00:10, 30.17it/s]
Processing: positive r2g, 0.85 quantile:  87%|████████▋ | 2210/2529 [01:33<00:10, 29.24it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2215/2529 [01:33<00:09, 34.10it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2219/2529 [01:33<00:08, 34.89it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2223/2529 [01:33<00:08, 35.56it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2227/2529 [01:33<00:09, 31.85it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2231/2529 [01:33<00:10, 29.55it/s]
Processing: positive r2g, 0.85 quantile:  88%|████████▊ | 2235/2529 [01:34<00:12, 24.31it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▊ | 2239/2529 [01:34<00:10, 27.50it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▊ | 2243/2529 [01:34<00:11, 25.04it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▉ | 2247/2529 [01:34<00:11, 25.45it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▉ | 2250/2529 [01:34<00:11, 25.35it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▉ | 2254/2529 [01:34<00:09, 28.46it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▉ | 2259/2529 [01:34<00:08, 33.37it/s]
Processing: positive r2g, 0.85 quantile:  89%|████████▉ | 2263/2529 [01:35<00:09, 28.94it/s]
Processing: positive r2g, 0.85 quantile:  90%|████████▉ | 2267/2529 [01:35<00:08, 30.94it/s]
Processing: positive r2g, 0.85 quantile:  90%|████████▉ | 2271/2529 [01:35<00:08, 30.37it/s]
Processing: positive r2g, 0.85 quantile:  90%|████████▉ | 2275/2529 [01:35<00:09, 27.23it/s]
Processing: positive r2g, 0.85 quantile:  90%|█████████ | 2278/2529 [01:35<00:09, 26.95it/s]
Processing: positive r2g, 0.85 quantile:  90%|█████████ | 2282/2529 [01:35<00:08, 29.54it/s]
Processing: positive r2g, 0.85 quantile:  90%|█████████ | 2286/2529 [01:35<00:07, 31.27it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████ | 2290/2529 [01:35<00:08, 29.61it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████ | 2294/2529 [01:36<00:07, 30.49it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████ | 2299/2529 [01:36<00:06, 34.33it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████ | 2303/2529 [01:36<00:06, 32.87it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████ | 2307/2529 [01:36<00:07, 28.28it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████▏| 2310/2529 [01:36<00:07, 28.09it/s]
Processing: positive r2g, 0.85 quantile:  91%|█████████▏| 2313/2529 [01:36<00:07, 27.89it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2316/2529 [01:36<00:08, 23.76it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2320/2529 [01:37<00:07, 27.45it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2324/2529 [01:37<00:06, 30.55it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2328/2529 [01:37<00:07, 27.81it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2332/2529 [01:37<00:06, 30.44it/s]
Processing: positive r2g, 0.85 quantile:  92%|█████████▏| 2337/2529 [01:37<00:05, 33.07it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2341/2529 [01:37<00:05, 32.30it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2345/2529 [01:37<00:05, 31.40it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2349/2529 [01:37<00:05, 31.05it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2353/2529 [01:38<00:06, 26.36it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2357/2529 [01:38<00:06, 28.40it/s]
Processing: positive r2g, 0.85 quantile:  93%|█████████▎| 2360/2529 [01:38<00:05, 28.66it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▎| 2365/2529 [01:38<00:04, 33.16it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▎| 2369/2529 [01:38<00:05, 29.28it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▍| 2373/2529 [01:38<00:05, 28.04it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▍| 2377/2529 [01:38<00:05, 28.62it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▍| 2381/2529 [01:39<00:05, 29.00it/s]
Processing: positive r2g, 0.85 quantile:  94%|█████████▍| 2386/2529 [01:39<00:04, 33.29it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▍| 2391/2529 [01:39<00:03, 36.34it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▍| 2395/2529 [01:39<00:03, 34.04it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▍| 2399/2529 [01:39<00:03, 33.29it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▌| 2404/2529 [01:39<00:03, 37.23it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▌| 2408/2529 [01:39<00:04, 30.07it/s]
Processing: positive r2g, 0.85 quantile:  95%|█████████▌| 2412/2529 [01:39<00:03, 31.66it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▌| 2416/2529 [01:40<00:03, 33.32it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▌| 2420/2529 [01:40<00:03, 33.19it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▌| 2424/2529 [01:40<00:03, 33.92it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▌| 2429/2529 [01:40<00:02, 34.70it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▌| 2433/2529 [01:40<00:03, 30.83it/s]
Processing: positive r2g, 0.85 quantile:  96%|█████████▋| 2437/2529 [01:40<00:03, 28.26it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2442/2529 [01:40<00:02, 32.78it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2446/2529 [01:40<00:02, 33.42it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2450/2529 [01:41<00:02, 31.83it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2454/2529 [01:41<00:02, 31.52it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2458/2529 [01:41<00:02, 29.70it/s]
Processing: positive r2g, 0.85 quantile:  97%|█████████▋| 2462/2529 [01:41<00:02, 29.72it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2466/2529 [01:41<00:02, 28.38it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2471/2529 [01:41<00:01, 32.31it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2475/2529 [01:41<00:01, 33.89it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2479/2529 [01:42<00:01, 33.25it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2483/2529 [01:42<00:01, 34.23it/s]
Processing: positive r2g, 0.85 quantile:  98%|█████████▊| 2488/2529 [01:42<00:01, 36.71it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▊| 2493/2529 [01:42<00:00, 38.76it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▊| 2497/2529 [01:42<00:00, 35.10it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▉| 2501/2529 [01:42<00:00, 29.39it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▉| 2505/2529 [01:42<00:00, 29.57it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▉| 2509/2529 [01:42<00:00, 28.55it/s]
Processing: positive r2g, 0.85 quantile:  99%|█████████▉| 2514/2529 [01:43<00:00, 29.75it/s]
Processing: positive r2g, 0.85 quantile: 100%|█████████▉| 2519/2529 [01:43<00:00, 30.95it/s]
Processing: positive r2g, 0.85 quantile: 100%|█████████▉| 2524/2529 [01:43<00:00, 34.41it/s]
Processing: positive r2g, 0.85 quantile: 100%|█████████▉| 2528/2529 [01:43<00:00, 32.70it/s]
 57%|█████▋    | 8/14 [25:17<21:42, 217.07s/it]
Processing: positive r2g, 0.9 quantile:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, 0.9 quantile:   0%|          | 5/2529 [00:00<00:56, 44.76it/s]
Processing: positive r2g, 0.9 quantile:   0%|          | 10/2529 [00:00<00:58, 43.04it/s]
Processing: positive r2g, 0.9 quantile:   1%|          | 15/2529 [00:00<01:04, 39.19it/s]
Processing: positive r2g, 0.9 quantile:   1%|          | 19/2529 [00:00<01:10, 35.44it/s]
Processing: positive r2g, 0.9 quantile:   1%|          | 23/2529 [00:00<01:19, 31.43it/s]
Processing: positive r2g, 0.9 quantile:   1%|          | 28/2529 [00:00<01:10, 35.27it/s]
Processing: positive r2g, 0.9 quantile:   1%|▏         | 32/2529 [00:00<01:29, 28.05it/s]
Processing: positive r2g, 0.9 quantile:   1%|▏         | 37/2529 [00:01<01:20, 31.04it/s]
Processing: positive r2g, 0.9 quantile:   2%|▏         | 41/2529 [00:01<01:22, 30.06it/s]
Processing: positive r2g, 0.9 quantile:   2%|▏         | 46/2529 [00:01<01:12, 34.04it/s]
Processing: positive r2g, 0.9 quantile:   2%|▏         | 50/2529 [00:01<01:23, 29.55it/s]
Processing: positive r2g, 0.9 quantile:   2%|▏         | 54/2529 [00:01<01:20, 30.79it/s]
Processing: positive r2g, 0.9 quantile:   2%|▏         | 61/2529 [00:01<01:04, 38.34it/s]
Processing: positive r2g, 0.9 quantile:   3%|▎         | 67/2529 [00:01<00:58, 42.26it/s]
Processing: positive r2g, 0.9 quantile:   3%|▎         | 72/2529 [00:02<01:05, 37.46it/s]
Processing: positive r2g, 0.9 quantile:   3%|▎         | 76/2529 [00:02<01:15, 32.66it/s]
Processing: positive r2g, 0.9 quantile:   3%|▎         | 81/2529 [00:02<01:08, 35.57it/s]
Processing: positive r2g, 0.9 quantile:   3%|▎         | 85/2529 [00:02<01:09, 35.13it/s]
Processing: positive r2g, 0.9 quantile:   4%|▎         | 89/2529 [00:02<01:13, 33.17it/s]
Processing: positive r2g, 0.9 quantile:   4%|▎         | 94/2529 [00:02<01:05, 37.01it/s]
Processing: positive r2g, 0.9 quantile:   4%|▍         | 98/2529 [00:02<01:07, 36.14it/s]
Processing: positive r2g, 0.9 quantile:   4%|▍         | 102/2529 [00:03<01:18, 30.88it/s]
Processing: positive r2g, 0.9 quantile:   4%|▍         | 108/2529 [00:03<01:05, 37.00it/s]
Processing: positive r2g, 0.9 quantile:   4%|▍         | 112/2529 [00:03<01:08, 35.17it/s]
Processing: positive r2g, 0.9 quantile:   5%|▍         | 116/2529 [00:03<01:26, 27.79it/s]
Processing: positive r2g, 0.9 quantile:   5%|▍         | 120/2529 [00:03<01:46, 22.65it/s]
Processing: positive r2g, 0.9 quantile:   5%|▍         | 123/2529 [00:03<01:46, 22.67it/s]
Processing: positive r2g, 0.9 quantile:   5%|▍         | 126/2529 [00:03<01:41, 23.70it/s]
Processing: positive r2g, 0.9 quantile:   5%|▌         | 129/2529 [00:04<01:58, 20.23it/s]
Processing: positive r2g, 0.9 quantile:   5%|▌         | 132/2529 [00:04<02:08, 18.71it/s]
Processing: positive r2g, 0.9 quantile:   5%|▌         | 135/2529 [00:04<02:14, 17.76it/s]
Processing: positive r2g, 0.9 quantile:   5%|▌         | 137/2529 [00:04<02:22, 16.75it/s]
Processing: positive r2g, 0.9 quantile:   5%|▌         | 139/2529 [00:04<02:24, 16.56it/s]
Processing: positive r2g, 0.9 quantile:   6%|▌         | 142/2529 [00:04<02:08, 18.61it/s]
Processing: positive r2g, 0.9 quantile:   6%|▌         | 145/2529 [00:05<02:06, 18.91it/s]
Processing: positive r2g, 0.9 quantile:   6%|▌         | 148/2529 [00:05<02:04, 19.11it/s]
Processing: positive r2g, 0.9 quantile:   6%|▌         | 154/2529 [00:05<01:31, 25.91it/s]
Processing: positive r2g, 0.9 quantile:   6%|▌         | 157/2529 [00:05<01:53, 20.83it/s]
Processing: positive r2g, 0.9 quantile:   6%|▋         | 160/2529 [00:05<02:05, 18.92it/s]
Processing: positive r2g, 0.9 quantile:   6%|▋         | 163/2529 [00:06<02:12, 17.91it/s]

Processing: positive r2g, 0.9 quantile:   7%|▋         | 167/2529 [00:06<01:56, 20.32it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 170/2529 [00:06<01:51, 21.11it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 173/2529 [00:06<02:02, 19.24it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 176/2529 [00:06<02:02, 19.28it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 180/2529 [00:06<01:47, 21.76it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 184/2529 [00:06<01:33, 25.15it/s]
Processing: positive r2g, 0.9 quantile:   7%|▋         | 188/2529 [00:06<01:23, 28.15it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 191/2529 [00:07<01:24, 27.61it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 195/2529 [00:07<01:18, 29.78it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 199/2529 [00:07<01:14, 31.38it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 203/2529 [00:07<01:13, 31.65it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 207/2529 [00:07<01:17, 30.02it/s]
Processing: positive r2g, 0.9 quantile:   8%|▊         | 212/2529 [00:07<01:08, 33.88it/s]
Processing: positive r2g, 0.9 quantile:   9%|▊         | 216/2529 [00:07<01:18, 29.60it/s]
Processing: positive r2g, 0.9 quantile:   9%|▉         | 222/2529 [00:08<01:04, 35.74it/s]
Processing: positive r2g, 0.9 quantile:   9%|▉         | 226/2529 [00:08<01:08, 33.59it/s]
Processing: positive r2g, 0.9 quantile:   9%|▉         | 232/2529 [00:08<01:00, 37.79it/s]
Processing: positive r2g, 0.9 quantile:   9%|▉         | 237/2529 [00:08<00:56, 40.79it/s]
Processing: positive r2g, 0.9 quantile:  10%|▉         | 242/2529 [00:08<01:00, 37.89it/s]
Processing: positive r2g, 0.9 quantile:  10%|▉         | 246/2529 [00:08<01:00, 38.00it/s]
Processing: positive r2g, 0.9 quantile:  10%|▉         | 250/2529 [00:08<01:07, 33.97it/s]
Processing: positive r2g, 0.9 quantile:  10%|█         | 256/2529 [00:08<00:58, 39.13it/s]
Processing: positive r2g, 0.9 quantile:  10%|█         | 261/2529 [00:09<00:57, 39.15it/s]
Processing: positive r2g, 0.9 quantile:  11%|█         | 266/2529 [00:09<01:07, 33.46it/s]
Processing: positive r2g, 0.9 quantile:  11%|█         | 272/2529 [00:09<01:01, 36.66it/s]
Processing: positive r2g, 0.9 quantile:  11%|█         | 276/2529 [00:09<01:01, 36.90it/s]
Processing: positive r2g, 0.9 quantile:  11%|█         | 281/2529 [00:09<00:56, 39.79it/s]
Processing: positive r2g, 0.9 quantile:  11%|█▏        | 286/2529 [00:09<00:57, 39.24it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 291/2529 [00:09<00:59, 37.40it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 295/2529 [00:09<01:01, 36.20it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 299/2529 [00:10<01:06, 33.47it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 303/2529 [00:10<01:03, 34.97it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 308/2529 [00:10<00:57, 38.78it/s]
Processing: positive r2g, 0.9 quantile:  12%|█▏        | 313/2529 [00:10<00:53, 41.15it/s]
Processing: positive r2g, 0.9 quantile:  13%|█▎        | 319/2529 [00:10<00:49, 44.40it/s]
Processing: positive r2g, 0.9 quantile:  13%|█▎        | 324/2529 [00:10<00:52, 41.87it/s]
Processing: positive r2g, 0.9 quantile:  13%|█▎        | 329/2529 [00:10<00:54, 40.02it/s]
Processing: positive r2g, 0.9 quantile:  13%|█▎        | 334/2529 [00:11<01:07, 32.52it/s]
Processing: positive r2g, 0.9 quantile:  13%|█▎        | 338/2529 [00:11<01:04, 33.86it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▎        | 342/2529 [00:11<01:06, 32.86it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▎        | 346/2529 [00:11<01:12, 30.15it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▍        | 350/2529 [00:11<01:07, 32.33it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▍        | 354/2529 [00:11<01:09, 31.14it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▍        | 358/2529 [00:11<01:22, 26.28it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▍        | 361/2529 [00:12<01:42, 21.20it/s]
Processing: positive r2g, 0.9 quantile:  14%|█▍        | 364/2529 [00:12<01:52, 19.32it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▍        | 367/2529 [00:12<02:11, 16.41it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▍        | 369/2529 [00:12<02:12, 16.36it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▍        | 371/2529 [00:12<02:20, 15.41it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▍        | 373/2529 [00:12<02:18, 15.53it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▍        | 375/2529 [00:13<02:23, 14.99it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▌        | 380/2529 [00:13<01:37, 22.09it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▌        | 383/2529 [00:13<01:32, 23.30it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▌        | 387/2529 [00:13<01:20, 26.77it/s]
Processing: positive r2g, 0.9 quantile:  15%|█▌        | 391/2529 [00:13<01:13, 29.18it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▌        | 395/2529 [00:13<01:20, 26.58it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▌        | 398/2529 [00:13<01:38, 21.61it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▌        | 401/2529 [00:14<01:36, 22.07it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▌        | 404/2529 [00:14<01:46, 19.88it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▌        | 409/2529 [00:14<01:28, 23.83it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▋        | 412/2529 [00:14<01:33, 22.74it/s]
Processing: positive r2g, 0.9 quantile:  16%|█▋        | 417/2529 [00:14<01:16, 27.50it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 420/2529 [00:14<01:15, 27.82it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 424/2529 [00:14<01:09, 30.34it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 428/2529 [00:15<01:09, 30.42it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 432/2529 [00:15<01:13, 28.51it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 435/2529 [00:15<01:12, 28.76it/s]
Processing: positive r2g, 0.9 quantile:  17%|█▋        | 439/2529 [00:15<01:14, 28.16it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 444/2529 [00:15<01:09, 29.82it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 448/2529 [00:15<01:17, 26.99it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 451/2529 [00:15<01:25, 24.24it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 454/2529 [00:16<01:32, 22.38it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 457/2529 [00:16<01:38, 20.97it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 460/2529 [00:16<01:38, 21.02it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 464/2529 [00:16<01:25, 24.25it/s]
Processing: positive r2g, 0.9 quantile:  18%|█▊        | 467/2529 [00:16<01:24, 24.42it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▊        | 470/2529 [00:16<01:34, 21.89it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▊        | 473/2529 [00:16<01:37, 21.10it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▉        | 477/2529 [00:17<01:29, 22.84it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▉        | 481/2529 [00:17<01:25, 23.88it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▉        | 484/2529 [00:17<01:22, 24.93it/s]
Processing: positive r2g, 0.9 quantile:  19%|█▉        | 491/2529 [00:17<01:00, 33.46it/s]
Processing: positive r2g, 0.9 quantile:  20%|█▉        | 495/2529 [00:17<00:59, 34.19it/s]
Processing: positive r2g, 0.9 quantile:  20%|█▉        | 501/2529 [00:17<00:51, 39.42it/s]
Processing: positive r2g, 0.9 quantile:  20%|██        | 506/2529 [00:17<00:51, 39.31it/s]
Processing: positive r2g, 0.9 quantile:  20%|██        | 510/2529 [00:17<00:56, 35.54it/s]
Processing: positive r2g, 0.9 quantile:  20%|██        | 514/2529 [00:18<01:02, 32.07it/s]
Processing: positive r2g, 0.9 quantile:  21%|██        | 521/2529 [00:18<00:54, 36.98it/s]
Processing: positive r2g, 0.9 quantile:  21%|██        | 525/2529 [00:18<01:05, 30.74it/s]
Processing: positive r2g, 0.9 quantile:  21%|██        | 531/2529 [00:18<00:54, 36.43it/s]
Processing: positive r2g, 0.9 quantile:  21%|██        | 531/2529 [01:23<00:54, 36.43it/s]
Processing: positive r2g, 0.9 quantile:  21%|██        | 536/2529 [01:23<2:07:05,  3.83s/it]
Processing: positive r2g, 0.9 quantile:  21%|██▏       | 538/2529 [01:23<1:49:05,  3.29s/it]
Processing: positive r2g, 0.9 quantile:  21%|██▏       | 542/2529 [01:24<1:17:38,  2.34s/it]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 546/2529 [01:24<55:03,  1.67s/it]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 552/2529 [01:24<33:58,  1.03s/it]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 556/2529 [01:24<25:02,  1.31it/s]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 560/2529 [01:24<18:20,  1.79it/s]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 565/2529 [01:24<12:27,  2.63it/s]
Processing: positive r2g, 0.9 quantile:  22%|██▏       | 569/2529 [01:24<09:19,  3.50it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 573/2529 [01:24<06:59,  4.67it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 577/2529 [01:25<05:26,  5.99it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 581/2529 [01:25<04:10,  7.77it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 584/2529 [01:25<03:27,  9.39it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 589/2529 [01:25<02:27, 13.15it/s]
Processing: positive r2g, 0.9 quantile:  23%|██▎       | 593/2529 [01:25<02:02, 15.76it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▎       | 598/2529 [01:25<01:39, 19.42it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▍       | 602/2529 [01:25<01:28, 21.77it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▍       | 606/2529 [01:26<01:40, 19.16it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▍       | 609/2529 [01:26<01:41, 18.94it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▍       | 612/2529 [01:26<01:32, 20.72it/s]
Processing: positive r2g, 0.9 quantile:  24%|██▍       | 616/2529 [01:26<01:18, 24.48it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▍       | 620/2529 [01:26<01:10, 27.09it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▍       | 624/2529 [01:26<01:11, 26.52it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▍       | 628/2529 [01:26<01:04, 29.35it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▌       | 634/2529 [01:26<00:53, 35.15it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▌       | 638/2529 [01:27<01:03, 29.97it/s]
Processing: positive r2g, 0.9 quantile:  25%|██▌       | 642/2529 [01:27<01:02, 30.36it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▌       | 647/2529 [01:27<00:55, 34.08it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▌       | 651/2529 [01:27<00:56, 33.32it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▌       | 656/2529 [01:27<00:53, 34.96it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▌       | 660/2529 [01:27<01:03, 29.52it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▋       | 665/2529 [01:27<00:56, 33.07it/s]
Processing: positive r2g, 0.9 quantile:  26%|██▋       | 670/2529 [01:28<00:50, 36.46it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 674/2529 [01:28<00:53, 34.99it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 678/2529 [01:28<00:55, 33.55it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 682/2529 [01:28<00:56, 32.58it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 686/2529 [01:28<00:57, 31.80it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 690/2529 [01:28<01:10, 26.11it/s]
Processing: positive r2g, 0.9 quantile:  27%|██▋       | 693/2529 [01:29<01:35, 19.16it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 696/2529 [01:29<01:42, 17.96it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 699/2529 [01:29<01:39, 18.40it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 702/2529 [01:29<01:44, 17.50it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 705/2529 [01:29<01:35, 19.06it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 709/2529 [01:29<01:25, 21.21it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 713/2529 [01:30<01:17, 23.43it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 716/2529 [01:30<01:33, 19.45it/s]
Processing: positive r2g, 0.9 quantile:  28%|██▊       | 719/2529 [01:30<01:28, 20.53it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▊       | 723/2529 [01:30<01:14, 24.21it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▉       | 728/2529 [01:30<01:00, 29.97it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▉       | 734/2529 [01:30<01:01, 29.33it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▉       | 738/2529 [01:31<01:14, 24.10it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▉       | 742/2529 [01:31<01:06, 27.07it/s]
Processing: positive r2g, 0.9 quantile:  29%|██▉       | 746/2529 [01:31<01:02, 28.51it/s]
Processing: positive r2g, 0.9 quantile:  30%|██▉       | 750/2529 [01:31<01:07, 26.23it/s]
Processing: positive r2g, 0.9 quantile:  30%|██▉       | 753/2529 [01:31<01:12, 24.49it/s]
Processing: positive r2g, 0.9 quantile:  30%|██▉       | 756/2529 [01:31<01:12, 24.51it/s]
Processing: positive r2g, 0.9 quantile:  30%|███       | 761/2529 [01:31<00:59, 29.73it/s]
Processing: positive r2g, 0.9 quantile:  30%|███       | 766/2529 [01:31<00:55, 31.76it/s]
Processing: positive r2g, 0.9 quantile:  30%|███       | 770/2529 [01:32<00:52, 33.20it/s]
Processing: positive r2g, 0.9 quantile:  31%|███       | 776/2529 [01:32<00:47, 37.13it/s]
Processing: positive r2g, 0.9 quantile:  31%|███       | 780/2529 [01:32<00:48, 36.30it/s]
Processing: positive r2g, 0.9 quantile:  31%|███       | 784/2529 [01:32<00:51, 33.81it/s]
Processing: positive r2g, 0.9 quantile:  31%|███       | 788/2529 [01:32<00:57, 30.07it/s]
Processing: positive r2g, 0.9 quantile:  31%|███▏      | 792/2529 [01:32<01:09, 25.13it/s]

Processing: positive r2g, 0.9 quantile:  31%|███▏      | 796/2529 [01:33<01:10, 24.42it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 799/2529 [01:33<01:11, 24.18it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 803/2529 [01:33<01:03, 27.17it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 806/2529 [01:33<01:18, 22.07it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 809/2529 [01:33<01:20, 21.30it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 813/2529 [01:33<01:08, 24.95it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 816/2529 [01:33<01:07, 25.56it/s]
Processing: positive r2g, 0.9 quantile:  32%|███▏      | 819/2529 [01:33<01:05, 26.15it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 824/2529 [01:34<00:54, 31.24it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 828/2529 [01:34<01:10, 24.17it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 833/2529 [01:34<00:59, 28.73it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 837/2529 [01:34<00:59, 28.60it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 842/2529 [01:34<00:52, 32.09it/s]
Processing: positive r2g, 0.9 quantile:  33%|███▎      | 846/2529 [01:34<00:51, 32.73it/s]
Processing: positive r2g, 0.9 quantile:  34%|███▎      | 850/2529 [01:34<00:50, 32.93it/s]
Processing: positive r2g, 0.9 quantile:  34%|███▍      | 855/2529 [01:35<00:45, 36.98it/s]
Processing: positive r2g, 0.9 quantile:  34%|███▍      | 861/2529 [01:35<00:39, 41.73it/s]
Processing: positive r2g, 0.9 quantile:  34%|███▍      | 866/2529 [01:35<00:39, 42.41it/s]
Processing: positive r2g, 0.9 quantile:  34%|███▍      | 872/2529 [01:35<00:37, 43.97it/s]
Processing: positive r2g, 0.9 quantile:  35%|███▍      | 877/2529 [01:35<00:38, 43.33it/s]
Processing: positive r2g, 0.9 quantile:  35%|███▍      | 882/2529 [01:35<00:45, 35.91it/s]
Processing: positive r2g, 0.9 quantile:  35%|███▌      | 887/2529 [01:35<00:42, 38.30it/s]
Processing: positive r2g, 0.9 quantile:  35%|███▌      | 892/2529 [01:35<00:41, 39.76it/s]
Processing: positive r2g, 0.9 quantile:  36%|███▌      | 898/2529 [01:36<00:37, 43.46it/s]
Processing: positive r2g, 0.9 quantile:  36%|███▌      | 903/2529 [01:36<00:45, 35.36it/s]
Processing: positive r2g, 0.9 quantile:  36%|███▌      | 908/2529 [01:36<00:43, 37.53it/s]
Processing: positive r2g, 0.9 quantile:  36%|███▌      | 913/2529 [01:36<00:43, 36.99it/s]
Processing: positive r2g, 0.9 quantile:  36%|███▋      | 918/2529 [01:36<00:43, 36.97it/s]
Processing: positive r2g, 0.9 quantile:  37%|███▋      | 924/2529 [01:36<00:38, 41.96it/s]
Processing: positive r2g, 0.9 quantile:  37%|███▋      | 931/2529 [01:36<00:34, 45.89it/s]
Processing: positive r2g, 0.9 quantile:  37%|███▋      | 936/2529 [01:37<00:43, 37.03it/s]
Processing: positive r2g, 0.9 quantile:  37%|███▋      | 941/2529 [01:37<00:47, 33.33it/s]
Processing: positive r2g, 0.9 quantile:  37%|███▋      | 945/2529 [01:37<00:48, 32.75it/s]
Processing: positive r2g, 0.9 quantile:  38%|███▊      | 950/2529 [01:37<00:44, 35.57it/s]
Processing: positive r2g, 0.9 quantile:  38%|███▊      | 954/2529 [01:37<00:45, 34.70it/s]
Processing: positive r2g, 0.9 quantile:  38%|███▊      | 958/2529 [01:37<00:45, 34.73it/s]
Processing: positive r2g, 0.9 quantile:  38%|███▊      | 965/2529 [01:37<00:37, 42.11it/s]
Processing: positive r2g, 0.9 quantile:  38%|███▊      | 970/2529 [01:38<00:41, 38.00it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▊      | 976/2529 [01:38<00:38, 40.22it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▉      | 981/2529 [01:38<00:42, 36.50it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▉      | 985/2529 [01:38<00:41, 37.02it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▉      | 989/2529 [01:38<00:41, 37.28it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▉      | 993/2529 [01:38<00:40, 37.92it/s]
Processing: positive r2g, 0.9 quantile:  39%|███▉      | 998/2529 [01:38<00:37, 40.34it/s]
Processing: positive r2g, 0.9 quantile:  40%|███▉      | 1004/2529 [01:38<00:34, 44.71it/s]
Processing: positive r2g, 0.9 quantile:  40%|███▉      | 1009/2529 [01:39<00:40, 37.69it/s]
Processing: positive r2g, 0.9 quantile:  40%|████      | 1013/2529 [01:39<00:43, 34.58it/s]
Processing: positive r2g, 0.9 quantile:  40%|████      | 1017/2529 [01:39<00:48, 31.13it/s]
Processing: positive r2g, 0.9 quantile:  40%|████      | 1023/2529 [01:39<00:41, 36.43it/s]
Processing: positive r2g, 0.9 quantile:  41%|████      | 1027/2529 [01:39<00:40, 37.09it/s]
Processing: positive r2g, 0.9 quantile:  41%|████      | 1031/2529 [01:39<00:39, 37.75it/s]
Processing: positive r2g, 0.9 quantile:  41%|████      | 1037/2529 [01:39<00:36, 40.96it/s]
Processing: positive r2g, 0.9 quantile:  41%|████      | 1042/2529 [01:39<00:37, 39.30it/s]
Processing: positive r2g, 0.9 quantile:  41%|████▏     | 1046/2529 [01:40<00:38, 38.29it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1050/2529 [01:40<00:41, 35.43it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1054/2529 [01:40<00:43, 34.20it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1059/2529 [01:40<00:40, 36.45it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1065/2529 [01:40<00:37, 39.18it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1069/2529 [01:40<00:38, 38.38it/s]
Processing: positive r2g, 0.9 quantile:  42%|████▏     | 1073/2529 [01:40<00:39, 36.45it/s]
Processing: positive r2g, 0.9 quantile:  43%|████▎     | 1077/2529 [01:40<00:39, 37.18it/s]
Processing: positive r2g, 0.9 quantile:  43%|████▎     | 1082/2529 [01:40<00:36, 39.43it/s]
Processing: positive r2g, 0.9 quantile:  43%|████▎     | 1088/2529 [01:41<00:32, 44.83it/s]
Processing: positive r2g, 0.9 quantile:  43%|████▎     | 1093/2529 [01:41<00:34, 41.24it/s]
Processing: positive r2g, 0.9 quantile:  43%|████▎     | 1099/2529 [01:41<00:31, 45.43it/s]
Processing: positive r2g, 0.9 quantile:  44%|████▎     | 1104/2529 [01:41<00:36, 38.78it/s]
Processing: positive r2g, 0.9 quantile:  44%|████▍     | 1109/2529 [01:41<00:34, 41.47it/s]
Processing: positive r2g, 0.9 quantile:  44%|████▍     | 1114/2529 [01:41<00:32, 43.57it/s]
Processing: positive r2g, 0.9 quantile:  44%|████▍     | 1119/2529 [01:41<00:31, 44.53it/s]
Processing: positive r2g, 0.9 quantile:  44%|████▍     | 1124/2529 [01:41<00:30, 45.58it/s]
Processing: positive r2g, 0.9 quantile:  45%|████▍     | 1129/2529 [01:42<00:36, 37.92it/s]
Processing: positive r2g, 0.9 quantile:  45%|████▍     | 1134/2529 [01:42<00:36, 37.85it/s]
Processing: positive r2g, 0.9 quantile:  45%|████▌     | 1141/2529 [01:42<00:32, 43.23it/s]
Processing: positive r2g, 0.9 quantile:  45%|████▌     | 1146/2529 [01:42<00:32, 41.99it/s]
Processing: positive r2g, 0.9 quantile:  46%|████▌     | 1151/2529 [01:42<00:32, 42.79it/s]
Processing: positive r2g, 0.9 quantile:  46%|████▌     | 1156/2529 [01:42<00:33, 41.06it/s]
Processing: positive r2g, 0.9 quantile:  46%|████▌     | 1161/2529 [01:42<00:32, 41.83it/s]
Processing: positive r2g, 0.9 quantile:  46%|████▌     | 1166/2529 [01:42<00:32, 41.78it/s]
Processing: positive r2g, 0.9 quantile:  46%|████▋     | 1171/2529 [01:43<00:31, 42.90it/s]
Processing: positive r2g, 0.9 quantile:  47%|████▋     | 1176/2529 [01:43<00:32, 41.74it/s]
Processing: positive r2g, 0.9 quantile:  47%|████▋     | 1182/2529 [01:43<00:29, 46.03it/s]
Processing: positive r2g, 0.9 quantile:  47%|████▋     | 1189/2529 [01:43<00:26, 50.92it/s]
Processing: positive r2g, 0.9 quantile:  47%|████▋     | 1195/2529 [01:43<00:34, 38.43it/s]
Processing: positive r2g, 0.9 quantile:  47%|████▋     | 1200/2529 [01:43<00:35, 37.08it/s]
Processing: positive r2g, 0.9 quantile:  48%|████▊     | 1205/2529 [01:43<00:33, 39.08it/s]
Processing: positive r2g, 0.9 quantile:  48%|████▊     | 1210/2529 [01:44<00:35, 37.15it/s]
Processing: positive r2g, 0.9 quantile:  48%|████▊     | 1215/2529 [01:44<00:33, 39.55it/s]
Processing: positive r2g, 0.9 quantile:  48%|████▊     | 1220/2529 [01:44<00:33, 39.11it/s]
Processing: positive r2g, 0.9 quantile:  48%|████▊     | 1225/2529 [01:44<00:33, 39.32it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▊     | 1230/2529 [01:44<00:33, 38.41it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▉     | 1234/2529 [01:44<00:35, 37.00it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▉     | 1239/2529 [01:44<00:34, 37.90it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▉     | 1243/2529 [01:45<00:44, 29.03it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▉     | 1247/2529 [01:45<00:49, 25.71it/s]
Processing: positive r2g, 0.9 quantile:  49%|████▉     | 1251/2529 [01:45<00:46, 27.36it/s]
Processing: positive r2g, 0.9 quantile:  50%|████▉     | 1255/2529 [01:45<00:47, 26.87it/s]
Processing: positive r2g, 0.9 quantile:  50%|████▉     | 1258/2529 [01:45<00:53, 23.98it/s]
Processing: positive r2g, 0.9 quantile:  50%|████▉     | 1262/2529 [01:45<00:46, 27.09it/s]
Processing: positive r2g, 0.9 quantile:  50%|█████     | 1265/2529 [01:45<00:46, 27.47it/s]
Processing: positive r2g, 0.9 quantile:  50%|█████     | 1268/2529 [01:46<00:45, 27.82it/s]
Processing: positive r2g, 0.9 quantile:  50%|█████     | 1273/2529 [01:46<00:39, 31.95it/s]
Processing: positive r2g, 0.9 quantile:  50%|█████     | 1277/2529 [01:46<00:49, 25.16it/s]
Processing: positive r2g, 0.9 quantile:  51%|█████     | 1281/2529 [01:46<00:46, 26.99it/s]
Processing: positive r2g, 0.9 quantile:  51%|█████     | 1286/2529 [01:46<00:38, 32.01it/s]
Processing: positive r2g, 0.9 quantile:  51%|█████     | 1293/2529 [01:46<00:31, 39.37it/s]
Processing: positive r2g, 0.9 quantile:  51%|█████▏    | 1298/2529 [01:46<00:29, 41.63it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1303/2529 [01:47<00:35, 34.13it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1307/2529 [01:47<00:39, 31.26it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1312/2529 [01:47<00:34, 34.84it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1317/2529 [01:47<00:32, 37.85it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1322/2529 [01:47<00:36, 33.16it/s]
Processing: positive r2g, 0.9 quantile:  52%|█████▏    | 1326/2529 [01:47<00:35, 33.48it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1330/2529 [01:47<00:34, 34.80it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1334/2529 [01:48<00:40, 29.19it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1338/2529 [01:48<00:38, 31.04it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1343/2529 [01:48<00:34, 34.88it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1347/2529 [01:48<00:33, 35.53it/s]
Processing: positive r2g, 0.9 quantile:  53%|█████▎    | 1351/2529 [01:48<00:56, 20.84it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▎    | 1354/2529 [01:48<00:56, 20.74it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▎    | 1357/2529 [01:49<00:56, 20.71it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1361/2529 [01:49<00:54, 21.25it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1364/2529 [01:49<00:59, 19.61it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1367/2529 [01:49<01:05, 17.73it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1369/2529 [01:49<01:07, 17.06it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1371/2529 [01:49<01:12, 16.03it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1373/2529 [01:50<01:12, 15.86it/s]
Processing: positive r2g, 0.9 quantile:  54%|█████▍    | 1376/2529 [01:50<01:03, 18.09it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▍    | 1379/2529 [01:50<01:02, 18.26it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▍    | 1382/2529 [01:50<01:01, 18.65it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▍    | 1388/2529 [01:50<00:45, 25.18it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▌    | 1391/2529 [01:50<00:56, 20.12it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▌    | 1394/2529 [01:51<01:02, 18.29it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▌    | 1396/2529 [01:51<01:04, 17.50it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▌    | 1398/2529 [01:51<01:03, 17.67it/s]
Processing: positive r2g, 0.9 quantile:  55%|█████▌    | 1401/2529 [01:51<00:55, 20.18it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1404/2529 [01:51<00:54, 20.68it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1407/2529 [01:51<00:55, 20.15it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1410/2529 [01:51<00:58, 19.26it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1413/2529 [01:51<00:53, 20.78it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1417/2529 [01:52<00:45, 24.18it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▌    | 1421/2529 [01:52<00:41, 26.72it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▋    | 1425/2529 [01:52<00:41, 26.65it/s]
Processing: positive r2g, 0.9 quantile:  56%|█████▋    | 1428/2529 [01:52<00:40, 27.16it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1432/2529 [01:52<00:37, 29.03it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1436/2529 [01:52<00:35, 31.05it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1440/2529 [01:52<00:41, 26.41it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1444/2529 [01:52<00:37, 28.90it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1449/2529 [01:53<00:34, 31.47it/s]
Processing: positive r2g, 0.9 quantile:  57%|█████▋    | 1453/2529 [01:53<00:39, 26.92it/s]
Processing: positive r2g, 0.9 quantile:  58%|█████▊    | 1458/2529 [01:53<00:33, 31.83it/s]
Processing: positive r2g, 0.9 quantile:  58%|█████▊    | 1462/2529 [01:53<00:35, 30.31it/s]
Processing: positive r2g, 0.9 quantile:  58%|█████▊    | 1468/2529 [01:53<00:30, 35.13it/s]
Processing: positive r2g, 0.9 quantile:  58%|█████▊    | 1472/2529 [01:53<00:29, 35.78it/s]
Processing: positive r2g, 0.9 quantile:  58%|█████▊    | 1477/2529 [01:53<00:27, 38.84it/s]

Processing: positive r2g, 0.9 quantile:  59%|█████▊    | 1482/2529 [01:54<00:29, 35.94it/s]
Processing: positive r2g, 0.9 quantile:  59%|█████▉    | 1486/2529 [01:54<00:31, 33.55it/s]
Processing: positive r2g, 0.9 quantile:  59%|█████▉    | 1490/2529 [01:54<00:31, 33.47it/s]
Processing: positive r2g, 0.9 quantile:  59%|█████▉    | 1495/2529 [01:54<00:28, 36.89it/s]
Processing: positive r2g, 0.9 quantile:  59%|█████▉    | 1500/2529 [01:54<00:27, 37.07it/s]
Processing: positive r2g, 0.9 quantile:  60%|█████▉    | 1505/2529 [01:54<00:30, 33.45it/s]
Processing: positive r2g, 0.9 quantile:  60%|█████▉    | 1509/2529 [01:54<00:30, 33.71it/s]
Processing: positive r2g, 0.9 quantile:  60%|█████▉    | 1514/2529 [01:54<00:28, 36.04it/s]
Processing: positive r2g, 0.9 quantile:  60%|██████    | 1518/2529 [01:55<00:30, 33.36it/s]
Processing: positive r2g, 0.9 quantile:  60%|██████    | 1524/2529 [01:55<00:27, 37.09it/s]
Processing: positive r2g, 0.9 quantile:  60%|██████    | 1528/2529 [01:55<00:27, 36.86it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████    | 1532/2529 [01:55<00:27, 35.62it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████    | 1536/2529 [01:55<00:28, 34.33it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████    | 1540/2529 [01:55<00:28, 34.76it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████    | 1544/2529 [01:55<00:31, 31.64it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████    | 1549/2529 [01:56<00:28, 34.63it/s]
Processing: positive r2g, 0.9 quantile:  61%|██████▏   | 1554/2529 [01:56<00:25, 38.33it/s]
Processing: positive r2g, 0.9 quantile:  62%|██████▏   | 1559/2529 [01:56<00:23, 41.25it/s]
Processing: positive r2g, 0.9 quantile:  62%|██████▏   | 1564/2529 [01:56<00:23, 40.35it/s]
Processing: positive r2g, 0.9 quantile:  62%|██████▏   | 1569/2529 [01:56<00:26, 36.03it/s]
Processing: positive r2g, 0.9 quantile:  62%|██████▏   | 1575/2529 [01:56<00:23, 40.24it/s]
Processing: positive r2g, 0.9 quantile:  62%|██████▏   | 1580/2529 [01:56<00:25, 37.06it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1584/2529 [01:56<00:30, 31.36it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1588/2529 [01:57<00:28, 32.84it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1592/2529 [01:57<00:33, 28.12it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1596/2529 [01:57<00:33, 27.69it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1601/2529 [01:57<00:30, 30.87it/s]
Processing: positive r2g, 0.9 quantile:  63%|██████▎   | 1605/2529 [01:57<00:35, 26.39it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▎   | 1608/2529 [01:57<00:39, 23.24it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▎   | 1611/2529 [01:58<00:46, 19.84it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1614/2529 [01:58<00:52, 17.31it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1616/2529 [01:58<00:54, 16.69it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1618/2529 [01:58<00:58, 15.56it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1620/2529 [01:58<01:00, 14.94it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1622/2529 [01:59<01:03, 14.21it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1624/2529 [01:59<01:04, 14.14it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1626/2529 [01:59<00:59, 15.28it/s]
Processing: positive r2g, 0.9 quantile:  64%|██████▍   | 1631/2529 [01:59<00:41, 21.66it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▍   | 1634/2529 [01:59<00:39, 22.66it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▍   | 1637/2529 [01:59<00:38, 23.42it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▍   | 1641/2529 [01:59<00:34, 25.83it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▌   | 1644/2529 [01:59<00:32, 26.86it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▌   | 1647/2529 [02:00<00:35, 24.93it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▌   | 1650/2529 [02:00<00:43, 20.26it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▌   | 1653/2529 [02:00<00:42, 20.81it/s]
Processing: positive r2g, 0.9 quantile:  65%|██████▌   | 1656/2529 [02:00<00:46, 18.89it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▌   | 1661/2529 [02:00<00:37, 23.09it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▌   | 1664/2529 [02:00<00:39, 22.09it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▌   | 1667/2529 [02:00<00:36, 23.77it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▌   | 1671/2529 [02:01<00:34, 24.70it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▋   | 1676/2529 [02:01<00:29, 29.08it/s]
Processing: positive r2g, 0.9 quantile:  66%|██████▋   | 1681/2529 [02:01<00:28, 30.09it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1685/2529 [02:01<00:30, 27.70it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1688/2529 [02:01<00:30, 27.95it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1692/2529 [02:01<00:30, 27.52it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1697/2529 [02:01<00:28, 29.23it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1700/2529 [02:02<00:34, 24.07it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1703/2529 [02:02<00:37, 21.87it/s]
Processing: positive r2g, 0.9 quantile:  67%|██████▋   | 1706/2529 [02:02<00:37, 22.18it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1709/2529 [02:02<00:36, 22.55it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1712/2529 [02:02<00:40, 20.37it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1715/2529 [02:02<00:41, 19.42it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1717/2529 [02:03<00:44, 18.32it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1721/2529 [02:03<00:36, 22.16it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1724/2529 [02:03<00:34, 23.29it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1727/2529 [02:03<00:38, 20.84it/s]
Processing: positive r2g, 0.9 quantile:  68%|██████▊   | 1730/2529 [02:03<00:44, 18.09it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▊   | 1734/2529 [02:03<00:36, 21.96it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▊   | 1737/2529 [02:03<00:33, 23.55it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▉   | 1740/2529 [02:04<00:34, 23.01it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▉   | 1743/2529 [02:04<00:33, 23.65it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▉   | 1747/2529 [02:04<00:28, 27.21it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▉   | 1751/2529 [02:04<00:26, 29.58it/s]
Processing: positive r2g, 0.9 quantile:  69%|██████▉   | 1755/2529 [02:04<00:26, 29.71it/s]
Processing: positive r2g, 0.9 quantile:  70%|██████▉   | 1760/2529 [02:04<00:22, 34.44it/s]
Processing: positive r2g, 0.9 quantile:  70%|██████▉   | 1767/2529 [02:04<00:19, 39.83it/s]
Processing: positive r2g, 0.9 quantile:  70%|███████   | 1772/2529 [02:04<00:20, 37.43it/s]
Processing: positive r2g, 0.9 quantile:  70%|███████   | 1776/2529 [02:05<00:21, 35.41it/s]
Processing: positive r2g, 0.9 quantile:  70%|███████   | 1780/2529 [02:05<00:22, 34.01it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████   | 1785/2529 [02:05<00:20, 35.61it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████   | 1789/2529 [02:05<00:26, 27.44it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████   | 1795/2529 [02:05<00:22, 33.19it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████   | 1800/2529 [02:05<00:20, 35.80it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████▏  | 1804/2529 [02:05<00:21, 33.41it/s]
Processing: positive r2g, 0.9 quantile:  71%|███████▏  | 1808/2529 [02:06<00:23, 30.56it/s]
Processing: positive r2g, 0.9 quantile:  72%|███████▏  | 1812/2529 [02:06<00:22, 32.51it/s]
Processing: positive r2g, 0.9 quantile:  72%|███████▏  | 1817/2529 [02:06<00:20, 35.41it/s]
Processing: positive r2g, 0.9 quantile:  72%|███████▏  | 1821/2529 [02:06<00:19, 35.92it/s]
Processing: positive r2g, 0.9 quantile:  72%|███████▏  | 1826/2529 [02:06<00:19, 36.78it/s]
Processing: positive r2g, 0.9 quantile:  72%|███████▏  | 1830/2529 [02:06<00:20, 34.86it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1834/2529 [02:06<00:20, 34.49it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1838/2529 [02:06<00:22, 30.97it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1842/2529 [02:07<00:25, 26.75it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1845/2529 [02:07<00:28, 24.04it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1849/2529 [02:07<00:25, 26.16it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1852/2529 [02:07<00:25, 26.09it/s]
Processing: positive r2g, 0.9 quantile:  73%|███████▎  | 1856/2529 [02:07<00:23, 28.39it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▎  | 1860/2529 [02:07<00:21, 30.93it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▎  | 1864/2529 [02:07<00:20, 32.54it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▍  | 1868/2529 [02:07<00:20, 32.54it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▍  | 1872/2529 [02:08<00:20, 32.18it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▍  | 1876/2529 [02:08<00:28, 23.23it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▍  | 1879/2529 [02:08<00:29, 22.39it/s]
Processing: positive r2g, 0.9 quantile:  74%|███████▍  | 1882/2529 [02:08<00:28, 22.94it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▍  | 1886/2529 [02:08<00:24, 26.70it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▍  | 1890/2529 [02:08<00:21, 29.69it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▍  | 1894/2529 [02:09<00:22, 28.72it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▌  | 1898/2529 [02:09<00:22, 28.37it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▌  | 1903/2529 [02:09<00:19, 32.61it/s]
Processing: positive r2g, 0.9 quantile:  75%|███████▌  | 1908/2529 [02:09<00:16, 36.84it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▌  | 1912/2529 [02:09<00:21, 28.14it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▌  | 1916/2529 [02:09<00:20, 30.28it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▌  | 1921/2529 [02:09<00:18, 32.71it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▌  | 1926/2529 [02:09<00:17, 35.38it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▋  | 1930/2529 [02:10<00:17, 34.58it/s]
Processing: positive r2g, 0.9 quantile:  76%|███████▋  | 1934/2529 [02:10<00:16, 35.35it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1938/2529 [02:10<00:20, 28.91it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1942/2529 [02:10<00:19, 30.70it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1946/2529 [02:10<00:18, 32.22it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1950/2529 [02:10<00:17, 32.66it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1954/2529 [02:10<00:19, 30.17it/s]
Processing: positive r2g, 0.9 quantile:  77%|███████▋  | 1958/2529 [02:11<00:19, 29.91it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1962/2529 [02:11<00:19, 29.34it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1965/2529 [02:11<00:19, 28.85it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1968/2529 [02:11<00:19, 28.29it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1971/2529 [02:11<00:30, 18.43it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1974/2529 [02:11<00:34, 15.91it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1976/2529 [02:12<00:34, 15.82it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1978/2529 [02:12<00:34, 16.14it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1980/2529 [02:12<00:34, 15.70it/s]
Processing: positive r2g, 0.9 quantile:  78%|███████▊  | 1983/2529 [02:12<00:31, 17.43it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▊  | 1986/2529 [02:12<00:28, 18.99it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▊  | 1989/2529 [02:12<00:25, 21.10it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▉  | 1993/2529 [02:12<00:21, 25.47it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▉  | 1996/2529 [02:12<00:22, 23.37it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▉  | 1999/2529 [02:13<00:25, 21.03it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▉  | 2002/2529 [02:13<00:23, 22.24it/s]
Processing: positive r2g, 0.9 quantile:  79%|███████▉  | 2007/2529 [02:13<00:18, 28.21it/s]
Processing: positive r2g, 0.9 quantile:  80%|███████▉  | 2011/2529 [02:13<00:16, 30.95it/s]
Processing: positive r2g, 0.9 quantile:  80%|███████▉  | 2017/2529 [02:13<00:17, 28.60it/s]
Processing: positive r2g, 0.9 quantile:  80%|███████▉  | 2021/2529 [02:13<00:21, 23.12it/s]
Processing: positive r2g, 0.9 quantile:  80%|████████  | 2025/2529 [02:14<00:19, 26.03it/s]
Processing: positive r2g, 0.9 quantile:  80%|████████  | 2029/2529 [02:14<00:17, 27.95it/s]
Processing: positive r2g, 0.9 quantile:  80%|████████  | 2033/2529 [02:14<00:19, 26.10it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████  | 2036/2529 [02:14<00:19, 25.41it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████  | 2039/2529 [02:14<00:19, 25.14it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████  | 2042/2529 [02:14<00:18, 26.02it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████  | 2048/2529 [02:14<00:14, 33.95it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████  | 2052/2529 [02:14<00:15, 31.67it/s]
Processing: positive r2g, 0.9 quantile:  81%|████████▏ | 2058/2529 [02:15<00:12, 37.60it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2062/2529 [02:15<00:13, 35.27it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2066/2529 [02:15<00:13, 34.64it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2070/2529 [02:15<00:14, 32.70it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2074/2529 [02:15<00:14, 30.54it/s]

Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2078/2529 [02:15<00:17, 25.20it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2082/2529 [02:16<00:18, 24.44it/s]
Processing: positive r2g, 0.9 quantile:  82%|████████▏ | 2085/2529 [02:16<00:18, 24.20it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2090/2529 [02:16<00:15, 28.39it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2093/2529 [02:16<00:18, 23.00it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2096/2529 [02:16<00:18, 23.25it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2100/2529 [02:16<00:16, 26.27it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2103/2529 [02:16<00:17, 24.87it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2107/2529 [02:16<00:15, 28.12it/s]
Processing: positive r2g, 0.9 quantile:  83%|████████▎ | 2110/2529 [02:17<00:15, 26.52it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▎ | 2115/2529 [02:17<00:14, 29.03it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▎ | 2118/2529 [02:17<00:17, 22.89it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▍ | 2123/2529 [02:17<00:14, 28.04it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▍ | 2127/2529 [02:17<00:14, 28.14it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▍ | 2132/2529 [02:17<00:12, 31.37it/s]
Processing: positive r2g, 0.9 quantile:  84%|████████▍ | 2136/2529 [02:17<00:12, 31.88it/s]
Processing: positive r2g, 0.9 quantile:  85%|████████▍ | 2141/2529 [02:18<00:11, 33.62it/s]
Processing: positive r2g, 0.9 quantile:  85%|████████▍ | 2145/2529 [02:18<00:11, 33.16it/s]
Processing: positive r2g, 0.9 quantile:  85%|████████▌ | 2151/2529 [02:18<00:09, 39.27it/s]
Processing: positive r2g, 0.9 quantile:  85%|████████▌ | 2156/2529 [02:18<00:09, 39.80it/s]
Processing: positive r2g, 0.9 quantile:  85%|████████▌ | 2162/2529 [02:18<00:08, 44.14it/s]
Processing: positive r2g, 0.9 quantile:  86%|████████▌ | 2167/2529 [02:18<00:08, 41.11it/s]
Processing: positive r2g, 0.9 quantile:  86%|████████▌ | 2172/2529 [02:18<00:09, 39.52it/s]
Processing: positive r2g, 0.9 quantile:  86%|████████▌ | 2177/2529 [02:19<00:09, 37.47it/s]
Processing: positive r2g, 0.9 quantile:  86%|████████▋ | 2183/2529 [02:19<00:08, 41.53it/s]
Processing: positive r2g, 0.9 quantile:  87%|████████▋ | 2188/2529 [02:19<00:08, 40.52it/s]
Processing: positive r2g, 0.9 quantile:  87%|████████▋ | 2194/2529 [02:19<00:07, 42.49it/s]
Processing: positive r2g, 0.9 quantile:  87%|████████▋ | 2199/2529 [02:19<00:08, 38.57it/s]
Processing: positive r2g, 0.9 quantile:  87%|████████▋ | 2204/2529 [02:19<00:08, 40.17it/s]
Processing: positive r2g, 0.9 quantile:  87%|████████▋ | 2209/2529 [02:19<00:08, 39.32it/s]
Processing: positive r2g, 0.9 quantile:  88%|████████▊ | 2214/2529 [02:19<00:07, 40.57it/s]
Processing: positive r2g, 0.9 quantile:  88%|████████▊ | 2220/2529 [02:20<00:06, 44.29it/s]
Processing: positive r2g, 0.9 quantile:  88%|████████▊ | 2226/2529 [02:20<00:07, 40.21it/s]
Processing: positive r2g, 0.9 quantile:  88%|████████▊ | 2231/2529 [02:20<00:07, 38.78it/s]
Processing: positive r2g, 0.9 quantile:  88%|████████▊ | 2235/2529 [02:20<00:09, 32.04it/s]
Processing: positive r2g, 0.9 quantile:  89%|████████▊ | 2240/2529 [02:20<00:08, 33.63it/s]
Processing: positive r2g, 0.9 quantile:  89%|████████▊ | 2244/2529 [02:20<00:08, 33.90it/s]
Processing: positive r2g, 0.9 quantile:  89%|████████▉ | 2248/2529 [02:20<00:08, 32.81it/s]
Processing: positive r2g, 0.9 quantile:  89%|████████▉ | 2252/2529 [02:21<00:08, 33.22it/s]
Processing: positive r2g, 0.9 quantile:  89%|████████▉ | 2259/2529 [02:21<00:06, 41.19it/s]
Processing: positive r2g, 0.9 quantile:  90%|████████▉ | 2264/2529 [02:21<00:07, 37.37it/s]
Processing: positive r2g, 0.9 quantile:  90%|████████▉ | 2270/2529 [02:21<00:06, 39.22it/s]
Processing: positive r2g, 0.9 quantile:  90%|████████▉ | 2275/2529 [02:21<00:07, 34.88it/s]
Processing: positive r2g, 0.9 quantile:  90%|█████████ | 2279/2529 [02:21<00:07, 33.95it/s]
Processing: positive r2g, 0.9 quantile:  90%|█████████ | 2285/2529 [02:21<00:06, 38.89it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████ | 2290/2529 [02:21<00:06, 37.98it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████ | 2295/2529 [02:22<00:05, 39.69it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████ | 2301/2529 [02:22<00:05, 40.53it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████ | 2306/2529 [02:22<00:05, 39.38it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████▏| 2310/2529 [02:22<00:05, 36.69it/s]
Processing: positive r2g, 0.9 quantile:  91%|█████████▏| 2314/2529 [02:22<00:06, 32.39it/s]
Processing: positive r2g, 0.9 quantile:  92%|█████████▏| 2318/2529 [02:22<00:06, 33.62it/s]
Processing: positive r2g, 0.9 quantile:  92%|█████████▏| 2324/2529 [02:22<00:05, 38.94it/s]
Processing: positive r2g, 0.9 quantile:  92%|█████████▏| 2329/2529 [02:23<00:05, 36.89it/s]
Processing: positive r2g, 0.9 quantile:  92%|█████████▏| 2335/2529 [02:23<00:04, 41.05it/s]
Processing: positive r2g, 0.9 quantile:  93%|█████████▎| 2340/2529 [02:23<00:04, 40.29it/s]
Processing: positive r2g, 0.9 quantile:  93%|█████████▎| 2345/2529 [02:23<00:04, 39.80it/s]
Processing: positive r2g, 0.9 quantile:  93%|█████████▎| 2350/2529 [02:23<00:04, 40.25it/s]
Processing: positive r2g, 0.9 quantile:  93%|█████████▎| 2355/2529 [02:23<00:05, 33.91it/s]
Processing: positive r2g, 0.9 quantile:  93%|█████████▎| 2360/2529 [02:23<00:04, 36.01it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▎| 2366/2529 [02:23<00:04, 38.50it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▎| 2370/2529 [02:24<00:04, 37.98it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▍| 2374/2529 [02:24<00:04, 36.39it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▍| 2378/2529 [02:24<00:04, 36.86it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▍| 2382/2529 [02:24<00:03, 37.17it/s]
Processing: positive r2g, 0.9 quantile:  94%|█████████▍| 2389/2529 [02:24<00:03, 45.38it/s]
Processing: positive r2g, 0.9 quantile:  95%|█████████▍| 2394/2529 [02:24<00:03, 42.96it/s]
Processing: positive r2g, 0.9 quantile:  95%|█████████▍| 2399/2529 [02:24<00:03, 43.14it/s]
Processing: positive r2g, 0.9 quantile:  95%|█████████▌| 2405/2529 [02:24<00:02, 44.00it/s]
Processing: positive r2g, 0.9 quantile:  95%|█████████▌| 2410/2529 [02:25<00:02, 41.13it/s]
Processing: positive r2g, 0.9 quantile:  95%|█████████▌| 2415/2529 [02:25<00:02, 42.32it/s]
Processing: positive r2g, 0.9 quantile:  96%|█████████▌| 2420/2529 [02:25<00:02, 43.16it/s]
Processing: positive r2g, 0.9 quantile:  96%|█████████▌| 2425/2529 [02:25<00:02, 44.63it/s]
Processing: positive r2g, 0.9 quantile:  96%|█████████▌| 2430/2529 [02:25<00:02, 45.12it/s]
Processing: positive r2g, 0.9 quantile:  96%|█████████▋| 2435/2529 [02:25<00:02, 40.99it/s]
Processing: positive r2g, 0.9 quantile:  96%|█████████▋| 2440/2529 [02:25<00:02, 38.94it/s]
Processing: positive r2g, 0.9 quantile:  97%|█████████▋| 2446/2529 [02:25<00:01, 42.23it/s]
Processing: positive r2g, 0.9 quantile:  97%|█████████▋| 2451/2529 [02:26<00:01, 42.30it/s]
Processing: positive r2g, 0.9 quantile:  97%|█████████▋| 2456/2529 [02:26<00:01, 37.54it/s]
Processing: positive r2g, 0.9 quantile:  97%|█████████▋| 2461/2529 [02:26<00:01, 40.22it/s]
Processing: positive r2g, 0.9 quantile:  98%|█████████▊| 2466/2529 [02:26<00:01, 37.68it/s]
Processing: positive r2g, 0.9 quantile:  98%|█████████▊| 2472/2529 [02:26<00:01, 42.63it/s]
Processing: positive r2g, 0.9 quantile:  98%|█████████▊| 2477/2529 [02:26<00:01, 42.74it/s]
Processing: positive r2g, 0.9 quantile:  98%|█████████▊| 2482/2529 [02:26<00:01, 44.02it/s]
Processing: positive r2g, 0.9 quantile:  98%|█████████▊| 2488/2529 [02:26<00:00, 48.05it/s]
Processing: positive r2g, 0.9 quantile:  99%|█████████▊| 2495/2529 [02:26<00:00, 52.28it/s]
Processing: positive r2g, 0.9 quantile:  99%|█████████▉| 2501/2529 [02:27<00:00, 39.25it/s]
Processing: positive r2g, 0.9 quantile:  99%|█████████▉| 2506/2529 [02:27<00:00, 37.99it/s]
Processing: positive r2g, 0.9 quantile:  99%|█████████▉| 2511/2529 [02:27<00:00, 39.41it/s]
Processing: positive r2g, 0.9 quantile:  99%|█████████▉| 2516/2529 [02:27<00:00, 40.35it/s]
Processing: positive r2g, 0.9 quantile: 100%|█████████▉| 2521/2529 [02:27<00:00, 41.07it/s]
Processing: positive r2g, 0.9 quantile: 100%|█████████▉| 2526/2529 [02:27<00:00, 42.84it/s]
 64%|██████▍   | 9/14 [27:46<16:18, 195.76s/it]
Processing: positive r2g, 0.95 quantile:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, 0.95 quantile:   0%|          | 7/2529 [00:00<00:43, 58.10it/s]
Processing: positive r2g, 0.95 quantile:   1%|          | 13/2529 [00:00<00:47, 52.79it/s]
Processing: positive r2g, 0.95 quantile:   1%|          | 19/2529 [00:00<00:53, 46.64it/s]
Processing: positive r2g, 0.95 quantile:   1%|          | 24/2529 [00:00<01:00, 41.58it/s]
Processing: positive r2g, 0.95 quantile:   1%|          | 29/2529 [00:00<01:01, 40.86it/s]
Processing: positive r2g, 0.95 quantile:   1%|▏         | 34/2529 [00:00<01:06, 37.49it/s]
Processing: positive r2g, 0.95 quantile:   2%|▏         | 38/2529 [00:00<01:05, 38.09it/s]
Processing: positive r2g, 0.95 quantile:   2%|▏         | 43/2529 [00:01<01:03, 39.36it/s]
Processing: positive r2g, 0.95 quantile:   2%|▏         | 48/2529 [00:01<01:05, 37.62it/s]
Processing: positive r2g, 0.95 quantile:   2%|▏         | 52/2529 [00:01<01:04, 38.17it/s]
Processing: positive r2g, 0.95 quantile:   2%|▏         | 59/2529 [00:01<00:53, 46.15it/s]
Processing: positive r2g, 0.95 quantile:   3%|▎         | 67/2529 [00:01<00:45, 53.53it/s]
Processing: positive r2g, 0.95 quantile:   3%|▎         | 73/2529 [00:01<00:50, 48.35it/s]
Processing: positive r2g, 0.95 quantile:   3%|▎         | 78/2529 [00:01<00:57, 42.66it/s]
Processing: positive r2g, 0.95 quantile:   3%|▎         | 85/2529 [00:01<00:53, 45.60it/s]
Processing: positive r2g, 0.95 quantile:   4%|▎         | 90/2529 [00:02<00:55, 43.65it/s]
Processing: positive r2g, 0.95 quantile:   4%|▍         | 96/2529 [00:02<00:51, 46.87it/s]
Processing: positive r2g, 0.95 quantile:   4%|▍         | 101/2529 [00:02<00:59, 41.12it/s]
Processing: positive r2g, 0.95 quantile:   4%|▍         | 108/2529 [00:02<00:51, 47.14it/s]
Processing: positive r2g, 0.95 quantile:   4%|▍         | 113/2529 [00:02<00:52, 45.82it/s]
Processing: positive r2g, 0.95 quantile:   5%|▍         | 118/2529 [00:02<01:16, 31.38it/s]
Processing: positive r2g, 0.95 quantile:   5%|▍         | 122/2529 [00:03<01:21, 29.65it/s]
Processing: positive r2g, 0.95 quantile:   5%|▍         | 126/2529 [00:03<01:16, 31.39it/s]
Processing: positive r2g, 0.95 quantile:   5%|▌         | 130/2529 [00:03<01:29, 26.76it/s]
Processing: positive r2g, 0.95 quantile:   5%|▌         | 134/2529 [00:03<01:40, 23.76it/s]
Processing: positive r2g, 0.95 quantile:   5%|▌         | 137/2529 [00:03<01:47, 22.26it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 140/2529 [00:03<01:45, 22.72it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 143/2529 [00:03<01:38, 24.21it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 146/2529 [00:04<01:36, 24.62it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 149/2529 [00:04<01:37, 24.51it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 155/2529 [00:04<01:22, 28.78it/s]
Processing: positive r2g, 0.95 quantile:   6%|▌         | 158/2529 [00:04<01:34, 25.20it/s]
Processing: positive r2g, 0.95 quantile:   6%|▋         | 161/2529 [00:04<01:42, 23.05it/s]
Processing: positive r2g, 0.95 quantile:   6%|▋         | 164/2529 [00:04<01:42, 23.14it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 168/2529 [00:04<01:33, 25.22it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 171/2529 [00:05<01:32, 25.43it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 174/2529 [00:05<01:38, 24.00it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 177/2529 [00:05<01:34, 24.86it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 181/2529 [00:05<01:22, 28.36it/s]
Processing: positive r2g, 0.95 quantile:   7%|▋         | 187/2529 [00:05<01:07, 34.91it/s]
Processing: positive r2g, 0.95 quantile:   8%|▊         | 191/2529 [00:05<01:07, 34.68it/s]
Processing: positive r2g, 0.95 quantile:   8%|▊         | 196/2529 [00:05<01:02, 37.29it/s]
Processing: positive r2g, 0.95 quantile:   8%|▊         | 202/2529 [00:05<00:54, 42.91it/s]
Processing: positive r2g, 0.95 quantile:   8%|▊         | 207/2529 [00:06<01:01, 37.79it/s]
Processing: positive r2g, 0.95 quantile:   8%|▊         | 213/2529 [00:06<00:58, 39.38it/s]
Processing: positive r2g, 0.95 quantile:   9%|▊         | 218/2529 [00:06<00:56, 41.26it/s]
Processing: positive r2g, 0.95 quantile:   9%|▉         | 224/2529 [00:06<00:50, 45.78it/s]
Processing: positive r2g, 0.95 quantile:   9%|▉         | 229/2529 [00:06<00:50, 45.83it/s]
Processing: positive r2g, 0.95 quantile:   9%|▉         | 235/2529 [00:06<00:46, 49.34it/s]
Processing: positive r2g, 0.95 quantile:  10%|▉         | 241/2529 [00:06<00:46, 49.59it/s]
Processing: positive r2g, 0.95 quantile:  10%|▉         | 247/2529 [00:06<00:49, 45.90it/s]
Processing: positive r2g, 0.95 quantile:  10%|▉         | 252/2529 [00:06<00:49, 45.90it/s]
Processing: positive r2g, 0.95 quantile:  10%|█         | 258/2529 [00:07<00:46, 48.57it/s]
Processing: positive r2g, 0.95 quantile:  10%|█         | 263/2529 [00:07<00:50, 45.04it/s]
Processing: positive r2g, 0.95 quantile:  11%|█         | 269/2529 [00:07<00:46, 48.81it/s]
Processing: positive r2g, 0.95 quantile:  11%|█         | 274/2529 [00:07<00:47, 47.67it/s]
Processing: positive r2g, 0.95 quantile:  11%|█         | 281/2529 [00:07<00:43, 51.65it/s]
Processing: positive r2g, 0.95 quantile:  11%|█▏        | 287/2529 [00:07<00:42, 52.27it/s]
Processing: positive r2g, 0.95 quantile:  12%|█▏        | 293/2529 [00:07<00:47, 47.44it/s]
Processing: positive r2g, 0.95 quantile:  12%|█▏        | 298/2529 [00:07<00:51, 43.59it/s]

Processing: positive r2g, 0.95 quantile:  12%|█▏        | 303/2529 [00:08<00:49, 44.59it/s]
Processing: positive r2g, 0.95 quantile:  12%|█▏        | 310/2529 [00:08<00:44, 49.89it/s]
Processing: positive r2g, 0.95 quantile:  13%|█▎        | 318/2529 [00:08<00:39, 55.67it/s]
Processing: positive r2g, 0.95 quantile:  13%|█▎        | 324/2529 [00:08<00:41, 53.36it/s]
Processing: positive r2g, 0.95 quantile:  13%|█▎        | 330/2529 [00:08<00:42, 52.15it/s]
Processing: positive r2g, 0.95 quantile:  13%|█▎        | 336/2529 [00:08<00:51, 42.47it/s]
Processing: positive r2g, 0.95 quantile:  13%|█▎        | 341/2529 [00:08<00:50, 43.33it/s]
Processing: positive r2g, 0.95 quantile:  14%|█▎        | 346/2529 [00:08<00:55, 39.42it/s]
Processing: positive r2g, 0.95 quantile:  14%|█▍        | 352/2529 [00:09<00:51, 42.31it/s]
Processing: positive r2g, 0.95 quantile:  14%|█▍        | 357/2529 [00:09<01:01, 35.13it/s]
Processing: positive r2g, 0.95 quantile:  14%|█▍        | 361/2529 [00:09<01:14, 28.95it/s]
Processing: positive r2g, 0.95 quantile:  14%|█▍        | 365/2529 [00:09<01:26, 25.09it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▍        | 368/2529 [00:09<01:37, 22.17it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▍        | 371/2529 [00:10<01:43, 20.90it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▍        | 374/2529 [00:10<01:45, 20.34it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▍        | 378/2529 [00:10<01:29, 24.02it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▌        | 383/2529 [00:10<01:16, 28.09it/s]
Processing: positive r2g, 0.95 quantile:  15%|█▌        | 388/2529 [00:10<01:06, 32.30it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▌        | 393/2529 [00:10<01:00, 35.31it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▌        | 397/2529 [00:10<01:17, 27.45it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▌        | 401/2529 [00:11<01:17, 27.41it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▌        | 405/2529 [00:11<01:22, 25.72it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▌        | 410/2529 [00:11<01:11, 29.64it/s]
Processing: positive r2g, 0.95 quantile:  16%|█▋        | 414/2529 [00:11<01:11, 29.63it/s]
Processing: positive r2g, 0.95 quantile:  17%|█▋        | 419/2529 [00:11<01:04, 32.67it/s]
Processing: positive r2g, 0.95 quantile:  17%|█▋        | 425/2529 [00:11<00:54, 38.56it/s]
Processing: positive r2g, 0.95 quantile:  17%|█▋        | 430/2529 [00:11<00:56, 37.39it/s]
Processing: positive r2g, 0.95 quantile:  17%|█▋        | 434/2529 [00:12<00:59, 35.00it/s]
Processing: positive r2g, 0.95 quantile:  17%|█▋        | 439/2529 [00:12<00:59, 35.39it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 444/2529 [00:12<00:55, 37.33it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 448/2529 [00:12<01:01, 33.70it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 452/2529 [00:12<01:15, 27.62it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 456/2529 [00:12<01:15, 27.63it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 459/2529 [00:12<01:19, 25.99it/s]
Processing: positive r2g, 0.95 quantile:  18%|█▊        | 464/2529 [00:13<01:09, 29.80it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▊        | 468/2529 [00:13<01:09, 29.48it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▊        | 472/2529 [00:13<01:21, 25.24it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▉        | 477/2529 [00:13<01:11, 28.59it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▉        | 481/2529 [00:13<01:08, 29.77it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▉        | 485/2529 [00:13<01:03, 31.97it/s]
Processing: positive r2g, 0.95 quantile:  19%|█▉        | 493/2529 [00:13<00:48, 41.63it/s]
Processing: positive r2g, 0.95 quantile:  20%|█▉        | 500/2529 [00:14<00:42, 47.81it/s]
Processing: positive r2g, 0.95 quantile:  20%|██        | 506/2529 [00:14<00:40, 49.76it/s]
Processing: positive r2g, 0.95 quantile:  20%|██        | 512/2529 [00:14<00:44, 45.46it/s]
Processing: positive r2g, 0.95 quantile:  20%|██        | 517/2529 [00:14<00:44, 45.56it/s]
Processing: positive r2g, 0.95 quantile:  21%|██        | 523/2529 [00:14<00:43, 46.37it/s]
Processing: positive r2g, 0.95 quantile:  21%|██        | 528/2529 [00:14<00:47, 41.91it/s]
Processing: positive r2g, 0.95 quantile:  21%|██        | 536/2529 [00:14<00:41, 48.19it/s]
Processing: positive r2g, 0.95 quantile:  21%|██▏       | 541/2529 [00:14<00:45, 43.76it/s]
Processing: positive r2g, 0.95 quantile:  22%|██▏       | 546/2529 [00:15<00:48, 40.71it/s]
Processing: positive r2g, 0.95 quantile:  22%|██▏       | 554/2529 [00:15<00:42, 46.27it/s]
Processing: positive r2g, 0.95 quantile:  22%|██▏       | 560/2529 [00:15<00:42, 46.56it/s]
Processing: positive r2g, 0.95 quantile:  22%|██▏       | 567/2529 [00:15<00:41, 46.92it/s]
Processing: positive r2g, 0.95 quantile:  23%|██▎       | 572/2529 [00:15<00:43, 45.46it/s]
Processing: positive r2g, 0.95 quantile:  23%|██▎       | 577/2529 [00:15<00:50, 39.04it/s]
Processing: positive r2g, 0.95 quantile:  23%|██▎       | 582/2529 [00:15<00:50, 38.48it/s]
Processing: positive r2g, 0.95 quantile:  23%|██▎       | 587/2529 [00:16<00:48, 40.11it/s]
Processing: positive r2g, 0.95 quantile:  23%|██▎       | 592/2529 [00:16<00:47, 40.95it/s]
Processing: positive r2g, 0.95 quantile:  24%|██▎       | 598/2529 [00:16<00:44, 43.04it/s]
Processing: positive r2g, 0.95 quantile:  24%|██▍       | 603/2529 [00:16<00:48, 39.83it/s]
Processing: positive r2g, 0.95 quantile:  24%|██▍       | 608/2529 [00:16<01:03, 30.21it/s]
Processing: positive r2g, 0.95 quantile:  24%|██▍       | 612/2529 [00:16<01:00, 31.54it/s]
Processing: positive r2g, 0.95 quantile:  24%|██▍       | 617/2529 [00:16<00:54, 34.89it/s]
Processing: positive r2g, 0.95 quantile:  25%|██▍       | 622/2529 [00:17<00:51, 37.33it/s]
Processing: positive r2g, 0.95 quantile:  25%|██▍       | 627/2529 [00:17<00:50, 37.61it/s]
Processing: positive r2g, 0.95 quantile:  25%|██▌       | 635/2529 [00:17<00:40, 47.07it/s]
Processing: positive r2g, 0.95 quantile:  25%|██▌       | 640/2529 [00:17<00:48, 38.80it/s]
Processing: positive r2g, 0.95 quantile:  26%|██▌       | 647/2529 [00:17<00:43, 43.46it/s]
Processing: positive r2g, 0.95 quantile:  26%|██▌       | 652/2529 [00:17<00:43, 43.37it/s]
Processing: positive r2g, 0.95 quantile:  26%|██▌       | 657/2529 [00:17<00:42, 44.09it/s]
Processing: positive r2g, 0.95 quantile:  26%|██▌       | 662/2529 [00:17<00:45, 40.85it/s]
Processing: positive r2g, 0.95 quantile:  26%|██▋       | 667/2529 [00:18<00:44, 42.17it/s]
Processing: positive r2g, 0.95 quantile:  27%|██▋       | 673/2529 [00:18<00:41, 45.09it/s]
Processing: positive r2g, 0.95 quantile:  27%|██▋       | 678/2529 [00:18<00:42, 43.87it/s]
Processing: positive r2g, 0.95 quantile:  27%|██▋       | 683/2529 [00:18<00:42, 43.75it/s]
Processing: positive r2g, 0.95 quantile:  27%|██▋       | 688/2529 [00:18<00:43, 41.92it/s]
Processing: positive r2g, 0.95 quantile:  27%|██▋       | 693/2529 [00:18<01:09, 26.35it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 697/2529 [00:19<01:14, 24.51it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 700/2529 [00:19<01:16, 23.92it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 703/2529 [00:19<01:14, 24.58it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 707/2529 [00:19<01:09, 26.17it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 711/2529 [00:19<01:02, 29.11it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 715/2529 [00:19<01:07, 26.86it/s]
Processing: positive r2g, 0.95 quantile:  28%|██▊       | 718/2529 [00:19<01:10, 25.65it/s]
Processing: positive r2g, 0.95 quantile:  29%|██▊       | 723/2529 [00:20<01:01, 29.33it/s]
Processing: positive r2g, 0.95 quantile:  29%|██▉       | 730/2529 [00:20<00:46, 38.37it/s]
Processing: positive r2g, 0.95 quantile:  29%|██▉       | 735/2529 [00:20<00:48, 36.70it/s]
Processing: positive r2g, 0.95 quantile:  29%|██▉       | 739/2529 [00:20<01:00, 29.83it/s]
Processing: positive r2g, 0.95 quantile:  29%|██▉       | 745/2529 [00:20<00:53, 33.24it/s]
Processing: positive r2g, 0.95 quantile:  30%|██▉       | 749/2529 [00:20<00:55, 31.93it/s]
Processing: positive r2g, 0.95 quantile:  30%|██▉       | 753/2529 [00:20<00:56, 31.33it/s]
Processing: positive r2g, 0.95 quantile:  30%|██▉       | 757/2529 [00:21<00:56, 31.59it/s]
Processing: positive r2g, 0.95 quantile:  30%|███       | 764/2529 [00:21<00:44, 39.78it/s]
Processing: positive r2g, 0.95 quantile:  30%|███       | 769/2529 [00:21<00:43, 40.31it/s]
Processing: positive r2g, 0.95 quantile:  31%|███       | 776/2529 [00:21<00:37, 46.15it/s]
Processing: positive r2g, 0.95 quantile:  31%|███       | 781/2529 [00:21<00:39, 44.47it/s]
Processing: positive r2g, 0.95 quantile:  31%|███       | 786/2529 [00:21<00:40, 42.53it/s]
Processing: positive r2g, 0.95 quantile:  31%|███▏      | 791/2529 [00:21<00:53, 32.43it/s]
Processing: positive r2g, 0.95 quantile:  31%|███▏      | 796/2529 [00:22<00:53, 32.12it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 800/2529 [00:22<00:53, 32.48it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 804/2529 [00:22<00:58, 29.38it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 808/2529 [00:22<01:02, 27.73it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 813/2529 [00:22<00:52, 32.44it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 817/2529 [00:22<00:50, 33.80it/s]
Processing: positive r2g, 0.95 quantile:  32%|███▏      | 821/2529 [00:22<00:49, 34.73it/s]
Processing: positive r2g, 0.95 quantile:  33%|███▎      | 826/2529 [00:22<00:44, 38.45it/s]
Processing: positive r2g, 0.95 quantile:  33%|███▎      | 831/2529 [00:23<00:50, 33.35it/s]
Processing: positive r2g, 0.95 quantile:  33%|███▎      | 836/2529 [00:23<00:48, 35.06it/s]
Processing: positive r2g, 0.95 quantile:  33%|███▎      | 842/2529 [00:23<00:41, 40.73it/s]
Processing: positive r2g, 0.95 quantile:  34%|███▎      | 848/2529 [00:23<00:39, 42.52it/s]
Processing: positive r2g, 0.95 quantile:  34%|███▍      | 854/2529 [00:23<00:36, 45.84it/s]
Processing: positive r2g, 0.95 quantile:  34%|███▍      | 862/2529 [00:23<00:31, 53.34it/s]
Processing: positive r2g, 0.95 quantile:  34%|███▍      | 868/2529 [00:23<00:30, 54.95it/s]
Processing: positive r2g, 0.95 quantile:  35%|███▍      | 874/2529 [00:23<00:30, 53.89it/s]
Processing: positive r2g, 0.95 quantile:  35%|███▍      | 880/2529 [00:23<00:31, 52.03it/s]
Processing: positive r2g, 0.95 quantile:  35%|███▌      | 886/2529 [00:24<00:32, 50.48it/s]
Processing: positive r2g, 0.95 quantile:  35%|███▌      | 892/2529 [00:24<00:31, 52.35it/s]
Processing: positive r2g, 0.95 quantile:  36%|███▌      | 900/2529 [00:24<00:30, 53.59it/s]
Processing: positive r2g, 0.95 quantile:  36%|███▌      | 906/2529 [00:24<00:33, 48.67it/s]
Processing: positive r2g, 0.95 quantile:  36%|███▌      | 912/2529 [00:24<00:33, 48.34it/s]
Processing: positive r2g, 0.95 quantile:  36%|███▋      | 918/2529 [00:24<00:32, 49.34it/s]
Processing: positive r2g, 0.95 quantile:  37%|███▋      | 926/2529 [00:24<00:28, 57.02it/s]
Processing: positive r2g, 0.95 quantile:  37%|███▋      | 933/2529 [00:25<00:29, 53.64it/s]
Processing: positive r2g, 0.95 quantile:  37%|███▋      | 939/2529 [00:25<00:32, 49.51it/s]
Processing: positive r2g, 0.95 quantile:  37%|███▋      | 945/2529 [00:25<00:36, 43.50it/s]
Processing: positive r2g, 0.95 quantile:  38%|███▊      | 952/2529 [00:25<00:32, 48.30it/s]
Processing: positive r2g, 0.95 quantile:  38%|███▊      | 958/2529 [00:25<00:35, 44.61it/s]
Processing: positive r2g, 0.95 quantile:  38%|███▊      | 966/2529 [00:25<00:31, 48.89it/s]
Processing: positive r2g, 0.95 quantile:  38%|███▊      | 973/2529 [00:25<00:30, 51.67it/s]
Processing: positive r2g, 0.95 quantile:  39%|███▊      | 979/2529 [00:26<00:31, 48.49it/s]
Processing: positive r2g, 0.95 quantile:  39%|███▉      | 984/2529 [00:26<00:31, 48.64it/s]
Processing: positive r2g, 0.95 quantile:  39%|███▉      | 990/2529 [00:26<00:30, 50.96it/s]
Processing: positive r2g, 0.95 quantile:  39%|███▉      | 996/2529 [00:26<00:29, 52.77it/s]
Processing: positive r2g, 0.95 quantile:  40%|███▉      | 1003/2529 [00:26<00:27, 56.44it/s]
Processing: positive r2g, 0.95 quantile:  40%|███▉      | 1009/2529 [00:26<00:29, 50.67it/s]
Processing: positive r2g, 0.95 quantile:  40%|████      | 1015/2529 [00:26<00:34, 43.58it/s]
Processing: positive r2g, 0.95 quantile:  40%|████      | 1021/2529 [00:26<00:32, 46.92it/s]
Processing: positive r2g, 0.95 quantile:  41%|████      | 1026/2529 [00:26<00:31, 47.43it/s]
Processing: positive r2g, 0.95 quantile:  41%|████      | 1033/2529 [00:27<00:29, 50.60it/s]
Processing: positive r2g, 0.95 quantile:  41%|████      | 1039/2529 [00:27<00:28, 51.90it/s]
Processing: positive r2g, 0.95 quantile:  41%|████▏     | 1045/2529 [00:27<00:28, 51.65it/s]
Processing: positive r2g, 0.95 quantile:  42%|████▏     | 1051/2529 [00:27<00:30, 48.52it/s]
Processing: positive r2g, 0.95 quantile:  42%|████▏     | 1056/2529 [00:27<00:30, 47.67it/s]
Processing: positive r2g, 0.95 quantile:  42%|████▏     | 1063/2529 [00:27<00:27, 53.12it/s]
Processing: positive r2g, 0.95 quantile:  42%|████▏     | 1069/2529 [00:27<00:29, 49.40it/s]
Processing: positive r2g, 0.95 quantile:  43%|████▎     | 1075/2529 [00:27<00:30, 47.64it/s]
Processing: positive r2g, 0.95 quantile:  43%|████▎     | 1081/2529 [00:28<00:29, 49.83it/s]
Processing: positive r2g, 0.95 quantile:  43%|████▎     | 1089/2529 [00:28<00:26, 53.47it/s]
Processing: positive r2g, 0.95 quantile:  43%|████▎     | 1096/2529 [00:28<00:25, 56.30it/s]
Processing: positive r2g, 0.95 quantile:  44%|████▎     | 1103/2529 [00:28<00:26, 54.39it/s]
Processing: positive r2g, 0.95 quantile:  44%|████▍     | 1110/2529 [00:28<00:25, 56.62it/s]
Processing: positive r2g, 0.95 quantile:  44%|████▍     | 1116/2529 [00:28<00:24, 56.95it/s]
Processing: positive r2g, 0.95 quantile:  44%|████▍     | 1123/2529 [00:28<00:23, 60.24it/s]
Processing: positive r2g, 0.95 quantile:  45%|████▍     | 1130/2529 [00:28<00:26, 52.05it/s]

Processing: positive r2g, 0.95 quantile:  45%|████▍     | 1136/2529 [00:29<00:26, 53.52it/s]
Processing: positive r2g, 0.95 quantile:  45%|████▌     | 1143/2529 [00:29<00:24, 57.09it/s]
Processing: positive r2g, 0.95 quantile:  45%|████▌     | 1150/2529 [00:29<00:24, 56.29it/s]
Processing: positive r2g, 0.95 quantile:  46%|████▌     | 1156/2529 [00:29<00:24, 55.24it/s]
Processing: positive r2g, 0.95 quantile:  46%|████▌     | 1163/2529 [00:29<00:25, 53.22it/s]
Processing: positive r2g, 0.95 quantile:  46%|████▋     | 1171/2529 [00:29<00:23, 58.08it/s]
Processing: positive r2g, 0.95 quantile:  47%|████▋     | 1177/2529 [00:29<00:23, 58.15it/s]
Processing: positive r2g, 0.95 quantile:  47%|████▋     | 1185/2529 [00:29<00:21, 63.24it/s]
Processing: positive r2g, 0.95 quantile:  47%|████▋     | 1192/2529 [00:29<00:22, 60.18it/s]
Processing: positive r2g, 0.95 quantile:  47%|████▋     | 1199/2529 [00:30<00:26, 49.73it/s]
Processing: positive r2g, 0.95 quantile:  48%|████▊     | 1206/2529 [00:30<00:24, 53.60it/s]
Processing: positive r2g, 0.95 quantile:  48%|████▊     | 1212/2529 [00:30<00:25, 51.34it/s]
Processing: positive r2g, 0.95 quantile:  48%|████▊     | 1218/2529 [00:30<00:24, 52.53it/s]
Processing: positive r2g, 0.95 quantile:  48%|████▊     | 1224/2529 [00:30<00:25, 50.91it/s]
Processing: positive r2g, 0.95 quantile:  49%|████▊     | 1230/2529 [00:30<00:26, 49.24it/s]
Processing: positive r2g, 0.95 quantile:  49%|████▉     | 1236/2529 [00:30<00:26, 49.07it/s]
Processing: positive r2g, 0.95 quantile:  49%|████▉     | 1241/2529 [00:31<00:29, 44.23it/s]
Processing: positive r2g, 0.95 quantile:  49%|████▉     | 1246/2529 [00:31<00:37, 34.02it/s]
Processing: positive r2g, 0.95 quantile:  49%|████▉     | 1250/2529 [00:31<00:37, 34.55it/s]
Processing: positive r2g, 0.95 quantile:  50%|████▉     | 1255/2529 [00:31<00:36, 34.83it/s]
Processing: positive r2g, 0.95 quantile:  50%|████▉     | 1259/2529 [00:31<00:39, 31.82it/s]
Processing: positive r2g, 0.95 quantile:  50%|████▉     | 1264/2529 [00:31<00:35, 35.27it/s]
Processing: positive r2g, 0.95 quantile:  50%|█████     | 1268/2529 [00:31<00:35, 35.03it/s]
Processing: positive r2g, 0.95 quantile:  50%|█████     | 1274/2529 [00:32<00:34, 36.77it/s]
Processing: positive r2g, 0.95 quantile:  51%|█████     | 1278/2529 [00:32<00:38, 32.69it/s]
Processing: positive r2g, 0.95 quantile:  51%|█████     | 1283/2529 [00:32<00:34, 36.51it/s]
Processing: positive r2g, 0.95 quantile:  51%|█████     | 1291/2529 [00:32<00:26, 47.02it/s]
Processing: positive r2g, 0.95 quantile:  51%|█████▏    | 1298/2529 [00:32<00:23, 52.44it/s]
Processing: positive r2g, 0.95 quantile:  52%|█████▏    | 1304/2529 [00:32<00:27, 44.27it/s]
Processing: positive r2g, 0.95 quantile:  52%|█████▏    | 1309/2529 [00:32<00:28, 42.40it/s]
Processing: positive r2g, 0.95 quantile:  52%|█████▏    | 1316/2529 [00:32<00:25, 48.11it/s]
Processing: positive r2g, 0.95 quantile:  52%|█████▏    | 1322/2529 [00:33<00:27, 43.83it/s]
Processing: positive r2g, 0.95 quantile:  53%|█████▎    | 1328/2529 [00:33<00:26, 45.25it/s]
Processing: positive r2g, 0.95 quantile:  53%|█████▎    | 1333/2529 [00:33<00:30, 39.68it/s]
Processing: positive r2g, 0.95 quantile:  53%|█████▎    | 1338/2529 [00:33<00:28, 41.14it/s]
Processing: positive r2g, 0.95 quantile:  53%|█████▎    | 1344/2529 [00:33<00:26, 45.54it/s]
Processing: positive r2g, 0.95 quantile:  53%|█████▎    | 1349/2529 [00:33<00:33, 35.61it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▎    | 1354/2529 [00:34<00:41, 28.59it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▎    | 1358/2529 [00:34<00:40, 28.94it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1362/2529 [00:34<00:43, 26.90it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1365/2529 [00:34<00:45, 25.53it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1368/2529 [00:34<00:50, 22.98it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1371/2529 [00:34<00:54, 21.34it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1374/2529 [00:35<00:52, 21.96it/s]
Processing: positive r2g, 0.95 quantile:  54%|█████▍    | 1377/2529 [00:35<00:48, 23.63it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▍    | 1380/2529 [00:35<00:47, 24.28it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▍    | 1383/2529 [00:35<00:47, 24.25it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▍    | 1389/2529 [00:35<00:40, 28.08it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▌    | 1392/2529 [00:35<00:45, 24.79it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▌    | 1395/2529 [00:35<00:49, 22.69it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▌    | 1398/2529 [00:35<00:49, 22.77it/s]
Processing: positive r2g, 0.95 quantile:  55%|█████▌    | 1402/2529 [00:36<00:45, 24.93it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▌    | 1406/2529 [00:36<00:42, 26.61it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▌    | 1409/2529 [00:36<00:45, 24.74it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▌    | 1412/2529 [00:36<00:44, 25.27it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▌    | 1416/2529 [00:36<00:39, 28.51it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▌    | 1421/2529 [00:36<00:32, 33.66it/s]
Processing: positive r2g, 0.95 quantile:  56%|█████▋    | 1425/2529 [00:36<00:32, 33.77it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1429/2529 [00:36<00:31, 35.14it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1434/2529 [00:37<00:28, 37.78it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1439/2529 [00:37<00:29, 36.85it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1443/2529 [00:37<00:30, 35.84it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1449/2529 [00:37<00:26, 40.44it/s]
Processing: positive r2g, 0.95 quantile:  57%|█████▋    | 1454/2529 [00:37<00:29, 35.98it/s]
Processing: positive r2g, 0.95 quantile:  58%|█████▊    | 1460/2529 [00:37<00:25, 41.18it/s]
Processing: positive r2g, 0.95 quantile:  58%|█████▊    | 1465/2529 [00:37<00:25, 41.56it/s]
Processing: positive r2g, 0.95 quantile:  58%|█████▊    | 1471/2529 [00:37<00:23, 45.32it/s]
Processing: positive r2g, 0.95 quantile:  58%|█████▊    | 1478/2529 [00:38<00:20, 50.12it/s]
Processing: positive r2g, 0.95 quantile:  59%|█████▊    | 1484/2529 [00:38<00:21, 49.67it/s]
Processing: positive r2g, 0.95 quantile:  59%|█████▉    | 1490/2529 [00:38<00:24, 43.18it/s]
Processing: positive r2g, 0.95 quantile:  59%|█████▉    | 1497/2529 [00:38<00:21, 48.97it/s]
Processing: positive r2g, 0.95 quantile:  59%|█████▉    | 1503/2529 [00:38<00:20, 50.03it/s]
Processing: positive r2g, 0.95 quantile:  60%|█████▉    | 1509/2529 [00:38<00:23, 42.75it/s]
Processing: positive r2g, 0.95 quantile:  60%|█████▉    | 1515/2529 [00:38<00:23, 43.57it/s]
Processing: positive r2g, 0.95 quantile:  60%|██████    | 1521/2529 [00:39<00:21, 46.77it/s]
Processing: positive r2g, 0.95 quantile:  60%|██████    | 1526/2529 [00:39<00:21, 45.65it/s]
Processing: positive r2g, 0.95 quantile:  61%|██████    | 1532/2529 [00:39<00:21, 46.41it/s]
Processing: positive r2g, 0.95 quantile:  61%|██████    | 1537/2529 [00:39<00:22, 45.05it/s]
Processing: positive r2g, 0.95 quantile:  61%|██████    | 1542/2529 [00:39<00:23, 41.48it/s]
Processing: positive r2g, 0.95 quantile:  61%|██████    | 1547/2529 [00:39<00:22, 43.37it/s]
Processing: positive r2g, 0.95 quantile:  61%|██████▏   | 1554/2529 [00:39<00:19, 49.47it/s]
Processing: positive r2g, 0.95 quantile:  62%|██████▏   | 1561/2529 [00:39<00:18, 53.05it/s]
Processing: positive r2g, 0.95 quantile:  62%|██████▏   | 1567/2529 [00:39<00:18, 51.00it/s]
Processing: positive r2g, 0.95 quantile:  62%|██████▏   | 1573/2529 [00:40<00:19, 49.91it/s]
Processing: positive r2g, 0.95 quantile:  62%|██████▏   | 1580/2529 [00:40<00:19, 48.78it/s]
Processing: positive r2g, 0.95 quantile:  63%|██████▎   | 1585/2529 [00:40<00:22, 42.20it/s]
Processing: positive r2g, 0.95 quantile:  63%|██████▎   | 1590/2529 [00:40<00:22, 41.92it/s]
Processing: positive r2g, 0.95 quantile:  63%|██████▎   | 1595/2529 [00:40<00:25, 37.01it/s]
Processing: positive r2g, 0.95 quantile:  63%|██████▎   | 1600/2529 [00:40<00:23, 39.88it/s]
Processing: positive r2g, 0.95 quantile:  63%|██████▎   | 1605/2529 [00:41<00:27, 34.05it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▎   | 1609/2529 [00:41<00:31, 29.16it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1613/2529 [00:41<00:37, 24.62it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1616/2529 [00:41<00:40, 22.29it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1619/2529 [00:41<00:44, 20.62it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1622/2529 [00:41<00:47, 19.17it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1625/2529 [00:42<00:48, 18.74it/s]
Processing: positive r2g, 0.95 quantile:  64%|██████▍   | 1631/2529 [00:42<00:35, 25.35it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▍   | 1635/2529 [00:42<00:33, 26.72it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▍   | 1639/2529 [00:42<00:30, 28.93it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▌   | 1644/2529 [00:42<00:27, 31.82it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▌   | 1648/2529 [00:42<00:32, 27.31it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▌   | 1651/2529 [00:42<00:34, 25.36it/s]
Processing: positive r2g, 0.95 quantile:  65%|██████▌   | 1655/2529 [00:43<00:36, 23.99it/s]
Processing: positive r2g, 0.95 quantile:  66%|██████▌   | 1660/2529 [00:43<00:29, 29.40it/s]
Processing: positive r2g, 0.95 quantile:  66%|██████▌   | 1664/2529 [00:43<00:31, 27.66it/s]
Processing: positive r2g, 0.95 quantile:  66%|██████▌   | 1668/2529 [00:43<00:28, 30.24it/s]
Processing: positive r2g, 0.95 quantile:  66%|██████▌   | 1672/2529 [00:43<00:26, 31.82it/s]
Processing: positive r2g, 0.95 quantile:  66%|██████▋   | 1678/2529 [00:43<00:22, 38.28it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1683/2529 [00:43<00:23, 35.84it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1687/2529 [00:44<00:24, 33.68it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1692/2529 [00:44<00:24, 34.26it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1697/2529 [00:44<00:22, 36.21it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1701/2529 [00:44<00:26, 31.06it/s]
Processing: positive r2g, 0.95 quantile:  67%|██████▋   | 1705/2529 [00:44<00:28, 29.07it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1709/2529 [00:44<00:30, 26.73it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1712/2529 [00:45<00:33, 24.63it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1715/2529 [00:45<00:34, 23.62it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1718/2529 [00:45<00:35, 22.79it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1723/2529 [00:45<00:28, 28.49it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1727/2529 [00:45<00:30, 25.88it/s]
Processing: positive r2g, 0.95 quantile:  68%|██████▊   | 1730/2529 [00:45<00:35, 22.82it/s]
Processing: positive r2g, 0.95 quantile:  69%|██████▊   | 1735/2529 [00:45<00:27, 28.43it/s]
Processing: positive r2g, 0.95 quantile:  69%|██████▉   | 1739/2529 [00:45<00:26, 30.22it/s]
Processing: positive r2g, 0.95 quantile:  69%|██████▉   | 1743/2529 [00:46<00:27, 28.40it/s]
Processing: positive r2g, 0.95 quantile:  69%|██████▉   | 1748/2529 [00:46<00:23, 33.28it/s]
Processing: positive r2g, 0.95 quantile:  69%|██████▉   | 1753/2529 [00:46<00:21, 35.46it/s]
Processing: positive r2g, 0.95 quantile:  70%|██████▉   | 1758/2529 [00:46<00:19, 38.74it/s]
Processing: positive r2g, 0.95 quantile:  70%|██████▉   | 1766/2529 [00:46<00:15, 49.42it/s]
Processing: positive r2g, 0.95 quantile:  70%|███████   | 1772/2529 [00:46<00:16, 46.36it/s]
Processing: positive r2g, 0.95 quantile:  70%|███████   | 1777/2529 [00:46<00:18, 40.33it/s]
Processing: positive r2g, 0.95 quantile:  71%|███████   | 1785/2529 [00:47<00:16, 46.32it/s]
Processing: positive r2g, 0.95 quantile:  71%|███████   | 1790/2529 [00:47<00:19, 37.21it/s]
Processing: positive r2g, 0.95 quantile:  71%|███████   | 1798/2529 [00:47<00:15, 46.14it/s]
Processing: positive r2g, 0.95 quantile:  71%|███████▏  | 1804/2529 [00:47<00:16, 42.67it/s]
Processing: positive r2g, 0.95 quantile:  72%|███████▏  | 1809/2529 [00:47<00:18, 38.77it/s]
Processing: positive r2g, 0.95 quantile:  72%|███████▏  | 1816/2529 [00:47<00:16, 44.31it/s]
Processing: positive r2g, 0.95 quantile:  72%|███████▏  | 1822/2529 [00:47<00:15, 46.93it/s]
Processing: positive r2g, 0.95 quantile:  72%|███████▏  | 1828/2529 [00:48<00:15, 45.93it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1834/2529 [00:48<00:15, 44.54it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1839/2529 [00:48<00:17, 39.06it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1844/2529 [00:48<00:20, 33.97it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1848/2529 [00:48<00:20, 32.99it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1852/2529 [00:48<00:20, 33.48it/s]
Processing: positive r2g, 0.95 quantile:  73%|███████▎  | 1857/2529 [00:48<00:18, 36.89it/s]
Processing: positive r2g, 0.95 quantile:  74%|███████▎  | 1863/2529 [00:49<00:16, 39.60it/s]
Processing: positive r2g, 0.95 quantile:  74%|███████▍  | 1868/2529 [00:49<00:16, 41.10it/s]
Processing: positive r2g, 0.95 quantile:  74%|███████▍  | 1873/2529 [00:49<00:17, 37.04it/s]
Processing: positive r2g, 0.95 quantile:  74%|███████▍  | 1877/2529 [00:49<00:22, 29.47it/s]
Processing: positive r2g, 0.95 quantile:  74%|███████▍  | 1881/2529 [00:49<00:21, 30.38it/s]
Processing: positive r2g, 0.95 quantile:  75%|███████▍  | 1886/2529 [00:49<00:19, 33.28it/s]
Processing: positive r2g, 0.95 quantile:  75%|███████▍  | 1891/2529 [00:49<00:17, 36.77it/s]
Processing: positive r2g, 0.95 quantile:  75%|███████▍  | 1895/2529 [00:49<00:18, 34.94it/s]

Processing: positive r2g, 0.95 quantile:  75%|███████▌  | 1900/2529 [00:50<00:17, 36.78it/s]
Processing: positive r2g, 0.95 quantile:  75%|███████▌  | 1907/2529 [00:50<00:14, 44.40it/s]
Processing: positive r2g, 0.95 quantile:  76%|███████▌  | 1912/2529 [00:50<00:16, 36.71it/s]
Processing: positive r2g, 0.95 quantile:  76%|███████▌  | 1917/2529 [00:50<00:15, 39.51it/s]
Processing: positive r2g, 0.95 quantile:  76%|███████▌  | 1923/2529 [00:50<00:13, 43.32it/s]
Processing: positive r2g, 0.95 quantile:  76%|███████▌  | 1928/2529 [00:50<00:14, 41.75it/s]
Processing: positive r2g, 0.95 quantile:  76%|███████▋  | 1934/2529 [00:50<00:13, 44.85it/s]
Processing: positive r2g, 0.95 quantile:  77%|███████▋  | 1939/2529 [00:51<00:15, 38.59it/s]
Processing: positive r2g, 0.95 quantile:  77%|███████▋  | 1944/2529 [00:51<00:15, 38.43it/s]
Processing: positive r2g, 0.95 quantile:  77%|███████▋  | 1950/2529 [00:51<00:13, 41.69it/s]
Processing: positive r2g, 0.95 quantile:  77%|███████▋  | 1955/2529 [00:51<00:15, 38.14it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1960/2529 [00:51<00:14, 39.06it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1965/2529 [00:51<00:15, 37.60it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1969/2529 [00:51<00:17, 32.17it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1973/2529 [00:52<00:24, 22.68it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1976/2529 [00:52<00:25, 22.05it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1979/2529 [00:52<00:25, 21.42it/s]
Processing: positive r2g, 0.95 quantile:  78%|███████▊  | 1982/2529 [00:52<00:24, 22.40it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▊  | 1986/2529 [00:52<00:22, 23.84it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▊  | 1990/2529 [00:52<00:19, 27.18it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▉  | 1995/2529 [00:53<00:19, 28.04it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▉  | 1998/2529 [00:53<00:20, 26.09it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▉  | 2001/2529 [00:53<00:19, 26.87it/s]
Processing: positive r2g, 0.95 quantile:  79%|███████▉  | 2008/2529 [00:53<00:14, 35.92it/s]
Processing: positive r2g, 0.95 quantile:  80%|███████▉  | 2015/2529 [00:53<00:11, 43.31it/s]
Processing: positive r2g, 0.95 quantile:  80%|███████▉  | 2020/2529 [00:53<00:17, 29.87it/s]
Processing: positive r2g, 0.95 quantile:  80%|████████  | 2024/2529 [00:53<00:16, 31.21it/s]
Processing: positive r2g, 0.95 quantile:  80%|████████  | 2029/2529 [00:54<00:14, 34.00it/s]
Processing: positive r2g, 0.95 quantile:  80%|████████  | 2033/2529 [00:54<00:15, 32.46it/s]
Processing: positive r2g, 0.95 quantile:  81%|████████  | 2037/2529 [00:54<00:15, 31.49it/s]
Processing: positive r2g, 0.95 quantile:  81%|████████  | 2041/2529 [00:54<00:15, 31.96it/s]
Processing: positive r2g, 0.95 quantile:  81%|████████  | 2048/2529 [00:54<00:11, 40.78it/s]
Processing: positive r2g, 0.95 quantile:  81%|████████  | 2053/2529 [00:54<00:11, 40.61it/s]
Processing: positive r2g, 0.95 quantile:  81%|████████▏ | 2060/2529 [00:54<00:10, 46.38it/s]
Processing: positive r2g, 0.95 quantile:  82%|████████▏ | 2065/2529 [00:54<00:10, 43.68it/s]
Processing: positive r2g, 0.95 quantile:  82%|████████▏ | 2070/2529 [00:55<00:11, 41.39it/s]
Processing: positive r2g, 0.95 quantile:  82%|████████▏ | 2075/2529 [00:55<00:11, 38.28it/s]
Processing: positive r2g, 0.95 quantile:  82%|████████▏ | 2079/2529 [00:55<00:13, 33.96it/s]
Processing: positive r2g, 0.95 quantile:  82%|████████▏ | 2083/2529 [00:55<00:14, 29.81it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2088/2529 [00:55<00:12, 34.05it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2092/2529 [00:55<00:14, 30.41it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2096/2529 [00:55<00:14, 29.49it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2101/2529 [00:56<00:13, 32.84it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2105/2529 [00:56<00:12, 33.79it/s]
Processing: positive r2g, 0.95 quantile:  83%|████████▎ | 2109/2529 [00:56<00:12, 34.07it/s]
Processing: positive r2g, 0.95 quantile:  84%|████████▎ | 2115/2529 [00:56<00:11, 36.55it/s]
Processing: positive r2g, 0.95 quantile:  84%|████████▍ | 2119/2529 [00:56<00:13, 30.73it/s]
Processing: positive r2g, 0.95 quantile:  84%|████████▍ | 2124/2529 [00:56<00:11, 34.20it/s]
Processing: positive r2g, 0.95 quantile:  84%|████████▍ | 2129/2529 [00:56<00:10, 36.77it/s]
Processing: positive r2g, 0.95 quantile:  84%|████████▍ | 2135/2529 [00:56<00:09, 41.84it/s]
Processing: positive r2g, 0.95 quantile:  85%|████████▍ | 2141/2529 [00:57<00:08, 43.27it/s]
Processing: positive r2g, 0.95 quantile:  85%|████████▍ | 2146/2529 [00:57<00:08, 43.77it/s]
Processing: positive r2g, 0.95 quantile:  85%|████████▌ | 2154/2529 [00:57<00:07, 52.26it/s]
Processing: positive r2g, 0.95 quantile:  85%|████████▌ | 2161/2529 [00:57<00:06, 55.62it/s]
Processing: positive r2g, 0.95 quantile:  86%|████████▌ | 2167/2529 [00:57<00:06, 53.19it/s]
Processing: positive r2g, 0.95 quantile:  86%|████████▌ | 2173/2529 [00:57<00:06, 51.46it/s]
Processing: positive r2g, 0.95 quantile:  86%|████████▌ | 2179/2529 [00:57<00:06, 50.43it/s]
Processing: positive r2g, 0.95 quantile:  86%|████████▋ | 2185/2529 [00:57<00:06, 51.69it/s]
Processing: positive r2g, 0.95 quantile:  87%|████████▋ | 2193/2529 [00:58<00:05, 58.32it/s]
Processing: positive r2g, 0.95 quantile:  87%|████████▋ | 2199/2529 [00:58<00:06, 51.12it/s]
Processing: positive r2g, 0.95 quantile:  87%|████████▋ | 2205/2529 [00:58<00:06, 50.01it/s]
Processing: positive r2g, 0.95 quantile:  87%|████████▋ | 2211/2529 [00:58<00:06, 50.49it/s]
Processing: positive r2g, 0.95 quantile:  88%|████████▊ | 2219/2529 [00:58<00:05, 57.85it/s]
Processing: positive r2g, 0.95 quantile:  88%|████████▊ | 2226/2529 [00:58<00:05, 54.14it/s]
Processing: positive r2g, 0.95 quantile:  88%|████████▊ | 2232/2529 [00:58<00:05, 53.28it/s]
Processing: positive r2g, 0.95 quantile:  88%|████████▊ | 2238/2529 [00:58<00:06, 44.04it/s]
Processing: positive r2g, 0.95 quantile:  89%|████████▊ | 2243/2529 [00:59<00:06, 42.28it/s]
Processing: positive r2g, 0.95 quantile:  89%|████████▉ | 2248/2529 [00:59<00:06, 42.67it/s]
Processing: positive r2g, 0.95 quantile:  89%|████████▉ | 2253/2529 [00:59<00:06, 43.98it/s]
Processing: positive r2g, 0.95 quantile:  89%|████████▉ | 2260/2529 [00:59<00:05, 47.71it/s]
Processing: positive r2g, 0.95 quantile:  90%|████████▉ | 2266/2529 [00:59<00:05, 50.21it/s]
Processing: positive r2g, 0.95 quantile:  90%|████████▉ | 2272/2529 [00:59<00:05, 50.70it/s]
Processing: positive r2g, 0.95 quantile:  90%|█████████ | 2278/2529 [00:59<00:05, 45.28it/s]
Processing: positive r2g, 0.95 quantile:  90%|█████████ | 2285/2529 [00:59<00:04, 50.05it/s]
Processing: positive r2g, 0.95 quantile:  91%|█████████ | 2291/2529 [01:00<00:04, 49.51it/s]
Processing: positive r2g, 0.95 quantile:  91%|█████████ | 2299/2529 [01:00<00:04, 55.79it/s]
Processing: positive r2g, 0.95 quantile:  91%|█████████ | 2305/2529 [01:00<00:04, 50.15it/s]
Processing: positive r2g, 0.95 quantile:  91%|█████████▏| 2311/2529 [01:00<00:04, 49.09it/s]
Processing: positive r2g, 0.95 quantile:  92%|█████████▏| 2317/2529 [01:00<00:04, 42.94it/s]
Processing: positive r2g, 0.95 quantile:  92%|█████████▏| 2325/2529 [01:00<00:04, 47.10it/s]
Processing: positive r2g, 0.95 quantile:  92%|█████████▏| 2332/2529 [01:00<00:03, 49.87it/s]
Processing: positive r2g, 0.95 quantile:  92%|█████████▏| 2339/2529 [01:01<00:03, 51.97it/s]
Processing: positive r2g, 0.95 quantile:  93%|█████████▎| 2345/2529 [01:01<00:03, 52.81it/s]
Processing: positive r2g, 0.95 quantile:  93%|█████████▎| 2351/2529 [01:01<00:03, 48.56it/s]
Processing: positive r2g, 0.95 quantile:  93%|█████████▎| 2356/2529 [01:01<00:03, 47.07it/s]
Processing: positive r2g, 0.95 quantile:  93%|█████████▎| 2363/2529 [01:01<00:03, 52.41it/s]
Processing: positive r2g, 0.95 quantile:  94%|█████████▎| 2369/2529 [01:01<00:03, 49.34it/s]
Processing: positive r2g, 0.95 quantile:  94%|█████████▍| 2375/2529 [01:01<00:03, 47.31it/s]
Processing: positive r2g, 0.95 quantile:  94%|█████████▍| 2381/2529 [01:01<00:03, 48.41it/s]
Processing: positive r2g, 0.95 quantile:  95%|█████████▍| 2390/2529 [01:02<00:02, 58.23it/s]
Processing: positive r2g, 0.95 quantile:  95%|█████████▍| 2397/2529 [01:02<00:02, 55.84it/s]
Processing: positive r2g, 0.95 quantile:  95%|█████████▌| 2405/2529 [01:02<00:02, 57.53it/s]
Processing: positive r2g, 0.95 quantile:  95%|█████████▌| 2411/2529 [01:02<00:02, 53.46it/s]
Processing: positive r2g, 0.95 quantile:  96%|█████████▌| 2419/2529 [01:02<00:01, 58.66it/s]
Processing: positive r2g, 0.95 quantile:  96%|█████████▌| 2425/2529 [01:02<00:01, 57.99it/s]
Processing: positive r2g, 0.95 quantile:  96%|█████████▌| 2432/2529 [01:02<00:01, 54.65it/s]
Processing: positive r2g, 0.95 quantile:  96%|█████████▋| 2438/2529 [01:02<00:01, 50.90it/s]
Processing: positive r2g, 0.95 quantile:  97%|█████████▋| 2446/2529 [01:03<00:01, 56.91it/s]
Processing: positive r2g, 0.95 quantile:  97%|█████████▋| 2453/2529 [01:03<00:01, 58.67it/s]
Processing: positive r2g, 0.95 quantile:  97%|█████████▋| 2459/2529 [01:03<00:01, 52.33it/s]
Processing: positive r2g, 0.95 quantile:  97%|█████████▋| 2465/2529 [01:03<00:01, 53.74it/s]
Processing: positive r2g, 0.95 quantile:  98%|█████████▊| 2471/2529 [01:03<00:01, 53.22it/s]
Processing: positive r2g, 0.95 quantile:  98%|█████████▊| 2477/2529 [01:03<00:00, 54.69it/s]
Processing: positive r2g, 0.95 quantile:  98%|█████████▊| 2484/2529 [01:03<00:00, 58.42it/s]
Processing: positive r2g, 0.95 quantile:  99%|█████████▊| 2492/2529 [01:03<00:00, 64.37it/s]
Processing: positive r2g, 0.95 quantile:  99%|█████████▉| 2499/2529 [01:03<00:00, 55.94it/s]
Processing: positive r2g, 0.95 quantile:  99%|█████████▉| 2505/2529 [01:04<00:00, 52.65it/s]
Processing: positive r2g, 0.95 quantile:  99%|█████████▉| 2511/2529 [01:04<00:00, 51.93it/s]
Processing: positive r2g, 0.95 quantile: 100%|█████████▉| 2517/2529 [01:04<00:00, 52.92it/s]
Processing: positive r2g, 0.95 quantile: 100%|█████████▉| 2524/2529 [01:04<00:00, 56.74it/s]
 71%|███████▏  | 10/14 [28:52<10:22, 155.56s/it]
Processing: positive r2g, Top 5 region-to-gene links per gene:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   0%|          | 4/2529 [00:00<01:07, 37.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   0%|          | 8/2529 [00:00<01:06, 38.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   0%|          | 12/2529 [00:00<01:10, 35.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|          | 16/2529 [00:00<01:07, 37.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|          | 20/2529 [00:00<01:23, 29.91it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|          | 24/2529 [00:00<01:24, 29.55it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|          | 28/2529 [00:00<01:17, 32.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|▏         | 32/2529 [00:01<01:37, 25.69it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   1%|▏         | 37/2529 [00:01<01:27, 28.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 41/2529 [00:01<01:29, 27.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 45/2529 [00:01<01:22, 30.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 49/2529 [00:01<01:29, 27.59it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 52/2529 [00:01<01:28, 27.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 56/2529 [00:01<01:20, 30.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   2%|▏         | 62/2529 [00:01<01:06, 37.36it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   3%|▎         | 67/2529 [00:02<01:02, 39.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   3%|▎         | 72/2529 [00:02<01:11, 34.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   3%|▎         | 76/2529 [00:02<01:22, 29.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   3%|▎         | 80/2529 [00:02<01:17, 31.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   3%|▎         | 85/2529 [00:02<01:15, 32.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▎         | 89/2529 [00:02<01:20, 30.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▎         | 94/2529 [00:02<01:11, 33.89it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▍         | 98/2529 [00:03<01:13, 33.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▍         | 102/2529 [00:03<01:25, 28.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▍         | 107/2529 [00:03<01:13, 32.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   4%|▍         | 111/2529 [00:03<01:12, 33.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▍         | 115/2529 [00:03<01:27, 27.51it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▍         | 119/2529 [00:03<01:49, 21.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▍         | 122/2529 [00:04<01:59, 20.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▍         | 125/2529 [00:04<01:53, 21.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 128/2529 [00:04<02:06, 18.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 131/2529 [00:04<02:08, 18.62it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 133/2529 [00:04<02:20, 17.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 135/2529 [00:04<02:23, 16.68it/s]

Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 137/2529 [00:05<02:33, 15.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   5%|▌         | 139/2529 [00:05<02:35, 15.39it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▌         | 142/2529 [00:05<02:16, 17.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▌         | 145/2529 [00:05<02:14, 17.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▌         | 148/2529 [00:05<02:12, 17.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▌         | 153/2529 [00:05<01:36, 24.69it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▌         | 156/2529 [00:06<01:58, 20.00it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▋         | 159/2529 [00:06<02:08, 18.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▋         | 162/2529 [00:06<02:21, 16.77it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   6%|▋         | 164/2529 [00:06<02:19, 16.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 167/2529 [00:06<02:02, 19.26it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 170/2529 [00:06<01:57, 20.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 173/2529 [00:07<02:10, 18.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 175/2529 [00:07<02:11, 17.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 178/2529 [00:07<02:00, 19.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 181/2529 [00:07<01:48, 21.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 185/2529 [00:07<01:32, 25.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   7%|▋         | 189/2529 [00:07<01:24, 27.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 192/2529 [00:07<01:30, 25.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 196/2529 [00:07<01:23, 27.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 200/2529 [00:07<01:17, 30.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 204/2529 [00:08<01:24, 27.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 208/2529 [00:08<01:19, 29.25it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   8%|▊         | 212/2529 [00:08<01:12, 31.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▊         | 216/2529 [00:08<01:24, 27.47it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▊         | 221/2529 [00:08<01:11, 32.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▉         | 225/2529 [00:08<01:13, 31.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▉         | 230/2529 [00:08<01:06, 34.56it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▉         | 234/2529 [00:08<01:04, 35.59it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:   9%|▉         | 239/2529 [00:09<01:00, 37.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|▉         | 243/2529 [00:09<01:05, 34.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|▉         | 247/2529 [00:09<01:10, 32.55it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|▉         | 251/2529 [00:09<01:11, 32.08it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|█         | 256/2529 [00:09<01:02, 36.37it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|█         | 260/2529 [00:09<01:03, 35.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  10%|█         | 264/2529 [00:09<01:13, 30.77it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  11%|█         | 269/2529 [00:10<01:06, 33.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  11%|█         | 273/2529 [00:10<01:07, 33.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  11%|█         | 278/2529 [00:10<01:02, 35.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  11%|█         | 282/2529 [00:10<01:04, 34.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  11%|█▏        | 287/2529 [00:10<01:00, 37.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 291/2529 [00:10<01:05, 33.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 295/2529 [00:10<01:07, 33.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 299/2529 [00:10<01:12, 30.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 303/2529 [00:11<01:09, 32.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 308/2529 [00:11<01:02, 35.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  12%|█▏        | 313/2529 [00:11<00:58, 37.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 318/2529 [00:11<00:54, 40.68it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 323/2529 [00:11<00:58, 37.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 327/2529 [00:11<01:01, 35.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 331/2529 [00:11<01:05, 33.75it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 335/2529 [00:11<01:14, 29.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  13%|█▎        | 339/2529 [00:12<01:11, 30.62it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▎        | 343/2529 [00:12<01:20, 27.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▎        | 347/2529 [00:12<01:19, 27.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▍        | 352/2529 [00:12<01:11, 30.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▍        | 356/2529 [00:12<01:23, 26.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▍        | 359/2529 [00:12<01:36, 22.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▍        | 362/2529 [00:13<01:52, 19.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  14%|█▍        | 365/2529 [00:13<02:06, 17.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 367/2529 [00:13<02:21, 15.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 369/2529 [00:13<02:22, 15.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 371/2529 [00:13<02:32, 14.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 373/2529 [00:14<02:31, 14.26it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 375/2529 [00:14<02:35, 13.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▍        | 379/2529 [00:14<01:52, 19.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▌        | 383/2529 [00:14<01:38, 21.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▌        | 387/2529 [00:14<01:26, 24.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  15%|█▌        | 391/2529 [00:14<01:20, 26.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 394/2529 [00:14<01:22, 25.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 397/2529 [00:15<01:45, 20.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 400/2529 [00:15<01:50, 19.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 403/2529 [00:15<01:56, 18.29it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 407/2529 [00:15<01:36, 22.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▌        | 410/2529 [00:15<01:35, 22.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  16%|█▋        | 413/2529 [00:15<01:40, 21.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 418/2529 [00:15<01:21, 26.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 421/2529 [00:16<01:19, 26.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 425/2529 [00:16<01:11, 29.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 429/2529 [00:16<01:14, 28.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 432/2529 [00:16<01:20, 26.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 435/2529 [00:16<01:19, 26.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 438/2529 [00:16<01:17, 27.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  17%|█▋        | 441/2529 [00:16<01:15, 27.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 444/2529 [00:16<01:17, 26.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 447/2529 [00:17<01:30, 23.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 450/2529 [00:17<01:39, 20.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 453/2529 [00:17<01:46, 19.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 456/2529 [00:17<01:41, 20.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 459/2529 [00:17<01:46, 19.39it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 463/2529 [00:17<01:31, 22.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  18%|█▊        | 466/2529 [00:17<01:28, 23.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▊        | 469/2529 [00:18<01:34, 21.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▊        | 472/2529 [00:18<01:52, 18.36it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▉        | 475/2529 [00:18<01:39, 20.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▉        | 478/2529 [00:18<01:32, 22.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▉        | 481/2529 [00:18<01:32, 22.23it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▉        | 484/2529 [00:18<01:27, 23.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  19%|█▉        | 490/2529 [00:18<01:04, 31.51it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|█▉        | 494/2529 [00:19<01:04, 31.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|█▉        | 499/2529 [00:19<00:57, 35.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|█▉        | 503/2529 [00:19<00:55, 36.45it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|██        | 507/2529 [00:19<00:58, 34.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|██        | 511/2529 [00:19<01:02, 32.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  20%|██        | 515/2529 [00:19<01:04, 31.20it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  21%|██        | 521/2529 [00:19<00:58, 34.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  21%|██        | 525/2529 [00:20<01:10, 28.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  21%|██        | 530/2529 [00:20<01:00, 33.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  21%|██        | 536/2529 [00:20<00:55, 35.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  21%|██▏       | 540/2529 [00:20<01:02, 31.90it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 544/2529 [00:20<01:10, 28.22it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 549/2529 [00:20<01:00, 32.56it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 554/2529 [00:20<00:59, 33.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 558/2529 [00:20<00:57, 34.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 562/2529 [00:21<00:59, 32.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  22%|██▏       | 567/2529 [00:21<00:59, 33.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 571/2529 [00:21<00:59, 32.91it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 575/2529 [00:21<01:07, 28.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 579/2529 [00:21<01:15, 25.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 583/2529 [00:21<01:09, 27.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 587/2529 [00:22<01:06, 29.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  23%|██▎       | 591/2529 [00:22<01:04, 30.00it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▎       | 595/2529 [00:22<01:01, 31.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▎       | 599/2529 [00:22<01:02, 30.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▍       | 603/2529 [00:22<01:08, 28.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▍       | 606/2529 [00:22<01:25, 22.36it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▍       | 609/2529 [00:22<01:32, 20.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▍       | 612/2529 [00:23<01:26, 22.10it/s]

Processing: positive r2g, Top 5 region-to-gene links per gene:  24%|██▍       | 616/2529 [00:23<01:15, 25.29it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▍       | 620/2529 [00:23<01:10, 27.22it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▍       | 623/2529 [00:23<01:12, 26.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▍       | 626/2529 [00:23<01:12, 26.22it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▍       | 631/2529 [00:23<01:00, 31.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▌       | 636/2529 [00:23<00:54, 34.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▌       | 640/2529 [00:23<01:10, 26.65it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  25%|██▌       | 644/2529 [00:24<01:05, 28.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▌       | 649/2529 [00:24<00:58, 32.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▌       | 653/2529 [00:24<00:59, 31.29it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▌       | 657/2529 [00:24<01:00, 31.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▌       | 661/2529 [00:24<01:07, 27.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▋       | 665/2529 [00:24<01:02, 29.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  26%|██▋       | 670/2529 [00:24<00:56, 32.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 674/2529 [00:25<00:58, 31.88it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 678/2529 [00:25<01:00, 30.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 682/2529 [00:25<01:01, 29.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 686/2529 [00:25<01:03, 29.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 689/2529 [00:25<01:05, 28.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 692/2529 [00:25<01:39, 18.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  27%|██▋       | 695/2529 [00:26<01:52, 16.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 697/2529 [00:26<01:52, 16.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 699/2529 [00:26<01:48, 16.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 701/2529 [00:26<01:54, 15.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 704/2529 [00:26<01:44, 17.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 707/2529 [00:26<01:33, 19.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 710/2529 [00:26<01:26, 20.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 713/2529 [00:27<01:22, 22.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 716/2529 [00:27<01:41, 17.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  28%|██▊       | 719/2529 [00:27<01:34, 19.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▊       | 723/2529 [00:27<01:19, 22.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▉       | 728/2529 [00:27<01:04, 28.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▉       | 734/2529 [00:27<01:05, 27.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▉       | 737/2529 [00:28<01:15, 23.75it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▉       | 740/2529 [00:28<01:15, 23.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  29%|██▉       | 744/2529 [00:28<01:05, 27.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|██▉       | 747/2529 [00:28<01:08, 25.91it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|██▉       | 750/2529 [00:28<01:13, 24.08it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|██▉       | 753/2529 [00:28<01:18, 22.62it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|██▉       | 756/2529 [00:28<01:18, 22.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|███       | 760/2529 [00:28<01:06, 26.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|███       | 765/2529 [00:29<00:56, 31.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  30%|███       | 769/2529 [00:29<00:58, 29.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███       | 774/2529 [00:29<00:51, 34.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███       | 778/2529 [00:29<00:54, 32.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███       | 782/2529 [00:29<00:55, 31.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███       | 786/2529 [00:29<00:55, 31.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███       | 790/2529 [00:29<01:06, 26.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███▏      | 793/2529 [00:30<01:12, 23.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  31%|███▏      | 796/2529 [00:30<01:18, 22.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 799/2529 [00:30<01:18, 21.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 803/2529 [00:30<01:08, 25.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 806/2529 [00:30<01:24, 20.36it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 809/2529 [00:30<01:27, 19.66it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 813/2529 [00:31<01:14, 23.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 816/2529 [00:31<01:12, 23.72it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  32%|███▏      | 819/2529 [00:31<01:10, 24.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 824/2529 [00:31<00:58, 28.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 828/2529 [00:31<01:15, 22.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 832/2529 [00:31<01:05, 25.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 835/2529 [00:31<01:03, 26.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 839/2529 [00:31<00:58, 28.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 843/2529 [00:32<00:55, 30.26it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  33%|███▎      | 847/2529 [00:32<00:53, 31.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  34%|███▎      | 851/2529 [00:32<00:54, 31.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  34%|███▍      | 856/2529 [00:32<00:47, 34.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  34%|███▍      | 861/2529 [00:32<00:43, 38.55it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  34%|███▍      | 865/2529 [00:32<00:43, 38.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  34%|███▍      | 870/2529 [00:32<00:40, 40.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▍      | 875/2529 [00:32<00:42, 38.47it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▍      | 879/2529 [00:33<00:45, 36.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▍      | 883/2529 [00:33<00:49, 33.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▌      | 888/2529 [00:33<00:45, 36.37it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▌      | 892/2529 [00:33<00:44, 36.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  35%|███▌      | 897/2529 [00:33<00:41, 39.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  36%|███▌      | 902/2529 [00:33<00:50, 32.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  36%|███▌      | 907/2529 [00:33<00:46, 35.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  36%|███▌      | 911/2529 [00:33<00:45, 35.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  36%|███▌      | 915/2529 [00:34<00:46, 34.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  36%|███▋      | 919/2529 [00:34<00:48, 33.39it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  37%|███▋      | 925/2529 [00:34<00:40, 39.90it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  37%|███▋      | 931/2529 [00:34<00:37, 42.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  37%|███▋      | 936/2529 [00:34<00:46, 34.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  37%|███▋      | 940/2529 [00:34<00:47, 33.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  37%|███▋      | 944/2529 [00:34<00:55, 28.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 949/2529 [00:35<00:49, 32.22it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 953/2529 [00:35<00:49, 31.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 957/2529 [00:35<00:49, 31.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 962/2529 [00:35<00:43, 35.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 966/2529 [00:35<00:44, 35.03it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  38%|███▊      | 970/2529 [00:35<00:43, 35.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▊      | 975/2529 [00:35<00:39, 39.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▉      | 980/2529 [00:35<00:46, 33.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▉      | 984/2529 [00:36<00:45, 33.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▉      | 988/2529 [00:36<00:45, 34.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▉      | 993/2529 [00:36<00:42, 35.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  39%|███▉      | 998/2529 [00:36<00:40, 37.56it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  40%|███▉      | 1003/2529 [00:36<00:37, 40.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  40%|███▉      | 1008/2529 [00:36<00:44, 34.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  40%|████      | 1012/2529 [00:36<00:44, 34.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  40%|████      | 1016/2529 [00:37<00:52, 28.58it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  40%|████      | 1021/2529 [00:37<00:45, 33.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████      | 1026/2529 [00:37<00:44, 33.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████      | 1030/2529 [00:37<00:43, 34.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████      | 1035/2529 [00:37<00:39, 37.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████      | 1039/2529 [00:37<00:41, 36.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████      | 1043/2529 [00:37<00:40, 37.12it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  41%|████▏     | 1047/2529 [00:37<00:41, 35.72it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1051/2529 [00:37<00:44, 32.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1055/2529 [00:38<00:46, 31.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1059/2529 [00:38<00:44, 33.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1065/2529 [00:38<00:40, 35.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1069/2529 [00:38<00:41, 35.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  42%|████▏     | 1073/2529 [00:38<00:43, 33.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  43%|████▎     | 1077/2529 [00:38<00:42, 34.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  43%|████▎     | 1081/2529 [00:38<00:41, 35.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  43%|████▎     | 1087/2529 [00:38<00:35, 40.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  43%|████▎     | 1092/2529 [00:39<00:36, 39.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  43%|████▎     | 1096/2529 [00:39<00:37, 38.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  44%|████▎     | 1102/2529 [00:39<00:36, 39.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  44%|████▎     | 1106/2529 [00:39<00:38, 37.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  44%|████▍     | 1111/2529 [00:39<00:37, 38.00it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  44%|████▍     | 1116/2529 [00:39<00:35, 39.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  44%|████▍     | 1121/2529 [00:39<00:34, 40.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▍     | 1126/2529 [00:39<00:34, 41.21it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▍     | 1131/2529 [00:40<00:39, 35.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▍     | 1135/2529 [00:40<00:39, 35.40it/s]

Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▌     | 1141/2529 [00:40<00:34, 39.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▌     | 1146/2529 [00:40<00:35, 38.51it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  45%|████▌     | 1150/2529 [00:40<00:35, 38.66it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  46%|████▌     | 1154/2529 [00:40<00:36, 37.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  46%|████▌     | 1158/2529 [00:40<00:36, 37.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  46%|████▌     | 1163/2529 [00:40<00:37, 36.28it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  46%|████▌     | 1168/2529 [00:41<00:34, 39.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  46%|████▋     | 1173/2529 [00:41<00:34, 39.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  47%|████▋     | 1178/2529 [00:41<00:33, 40.72it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  47%|████▋     | 1184/2529 [00:41<00:31, 42.88it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  47%|████▋     | 1190/2529 [00:41<00:32, 41.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  47%|████▋     | 1195/2529 [00:41<00:37, 36.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  47%|████▋     | 1199/2529 [00:41<00:39, 33.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1203/2529 [00:42<00:37, 35.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1207/2529 [00:42<00:37, 35.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1211/2529 [00:42<00:36, 36.08it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1216/2529 [00:42<00:35, 36.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1220/2529 [00:42<00:35, 36.67it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  48%|████▊     | 1224/2529 [00:42<00:36, 35.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▊     | 1228/2529 [00:42<00:37, 34.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▊     | 1232/2529 [00:42<00:39, 32.74it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▉     | 1237/2529 [00:42<00:36, 35.26it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▉     | 1241/2529 [00:43<00:41, 31.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▉     | 1245/2529 [00:43<00:53, 24.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  49%|████▉     | 1248/2529 [00:43<00:54, 23.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|████▉     | 1252/2529 [00:43<00:47, 26.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|████▉     | 1255/2529 [00:43<00:50, 25.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|████▉     | 1258/2529 [00:43<00:56, 22.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|████▉     | 1262/2529 [00:44<00:49, 25.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|█████     | 1265/2529 [00:44<00:48, 26.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|█████     | 1268/2529 [00:44<00:48, 26.23it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|█████     | 1272/2529 [00:44<00:43, 29.12it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  50%|█████     | 1276/2529 [00:44<00:52, 23.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  51%|█████     | 1279/2529 [00:44<00:50, 24.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  51%|█████     | 1283/2529 [00:44<00:44, 27.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  51%|█████     | 1289/2529 [00:44<00:35, 34.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  51%|█████     | 1294/2529 [00:45<00:32, 37.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  51%|█████▏    | 1299/2529 [00:45<00:32, 37.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1303/2529 [00:45<00:38, 31.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1307/2529 [00:45<00:41, 29.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1312/2529 [00:45<00:37, 32.56it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1317/2529 [00:45<00:34, 35.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1321/2529 [00:45<00:39, 30.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  52%|█████▏    | 1325/2529 [00:46<00:37, 32.20it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1329/2529 [00:46<00:37, 31.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1333/2529 [00:46<00:43, 27.74it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1336/2529 [00:46<00:43, 27.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1342/2529 [00:46<00:36, 32.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1346/2529 [00:46<00:35, 33.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1350/2529 [00:47<00:52, 22.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  53%|█████▎    | 1353/2529 [00:47<00:59, 19.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▎    | 1356/2529 [00:47<00:58, 20.14it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▎    | 1359/2529 [00:47<00:55, 21.25it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1362/2529 [00:47<01:02, 18.65it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1365/2529 [00:47<01:04, 17.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1367/2529 [00:48<01:10, 16.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1369/2529 [00:48<01:12, 16.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1371/2529 [00:48<01:17, 14.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1373/2529 [00:48<01:17, 14.91it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  54%|█████▍    | 1376/2529 [00:48<01:07, 17.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▍    | 1379/2529 [00:48<01:05, 17.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▍    | 1382/2529 [00:48<01:04, 17.67it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▍    | 1387/2529 [00:49<00:46, 24.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▍    | 1390/2529 [00:49<00:58, 19.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▌    | 1393/2529 [00:49<01:03, 17.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▌    | 1396/2529 [00:49<01:08, 16.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▌    | 1398/2529 [00:49<01:07, 16.68it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  55%|█████▌    | 1401/2529 [00:49<00:59, 19.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1404/2529 [00:50<00:57, 19.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1407/2529 [00:50<00:58, 19.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1410/2529 [00:50<01:00, 18.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1413/2529 [00:50<00:56, 19.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1416/2529 [00:50<00:51, 21.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▌    | 1420/2529 [00:50<00:44, 25.12it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▋    | 1424/2529 [00:50<00:40, 27.29it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  56%|█████▋    | 1427/2529 [00:51<00:43, 25.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1431/2529 [00:51<00:41, 26.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1435/2529 [00:51<00:38, 28.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1438/2529 [00:51<00:37, 28.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1441/2529 [00:51<00:44, 24.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1445/2529 [00:51<00:40, 26.66it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1449/2529 [00:51<00:37, 28.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  57%|█████▋    | 1452/2529 [00:52<00:44, 24.20it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1457/2529 [00:52<00:36, 29.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1461/2529 [00:52<00:35, 29.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1465/2529 [00:52<00:35, 30.14it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1470/2529 [00:52<00:32, 32.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1475/2529 [00:52<00:29, 35.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  58%|█████▊    | 1479/2529 [00:52<00:31, 33.65it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  59%|█████▊    | 1483/2529 [00:52<00:29, 35.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  59%|█████▉    | 1487/2529 [00:53<00:32, 31.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  59%|█████▉    | 1491/2529 [00:53<00:33, 31.25it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  59%|█████▉    | 1496/2529 [00:53<00:29, 35.25it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  59%|█████▉    | 1500/2529 [00:53<00:30, 34.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|█████▉    | 1505/2529 [00:53<00:33, 30.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|█████▉    | 1509/2529 [00:53<00:32, 31.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|█████▉    | 1513/2529 [00:53<00:30, 33.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|█████▉    | 1517/2529 [00:53<00:32, 31.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|██████    | 1522/2529 [00:54<00:28, 35.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  60%|██████    | 1526/2529 [00:54<00:30, 33.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████    | 1531/2529 [00:54<00:28, 35.13it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████    | 1535/2529 [00:54<00:30, 32.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████    | 1539/2529 [00:54<00:31, 31.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████    | 1543/2529 [00:54<00:33, 29.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████    | 1547/2529 [00:54<00:31, 31.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  61%|██████▏   | 1552/2529 [00:54<00:27, 35.54it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1557/2529 [00:55<00:26, 37.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1562/2529 [00:55<00:24, 38.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1566/2529 [00:55<00:26, 36.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1570/2529 [00:55<00:28, 34.08it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1575/2529 [00:55<00:25, 37.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  62%|██████▏   | 1580/2529 [00:55<00:27, 34.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1584/2529 [00:55<00:32, 28.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1588/2529 [00:56<00:31, 30.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1592/2529 [00:56<00:35, 26.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1595/2529 [00:56<00:35, 26.28it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1599/2529 [00:56<00:32, 28.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1602/2529 [00:56<00:32, 28.75it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  63%|██████▎   | 1605/2529 [00:56<00:38, 23.80it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▎   | 1608/2529 [00:56<00:43, 20.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▎   | 1611/2529 [00:57<00:51, 17.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1613/2529 [00:57<00:55, 16.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1615/2529 [00:57<01:02, 14.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1617/2529 [00:57<01:02, 14.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1619/2529 [00:57<01:03, 14.28it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1621/2529 [00:58<01:07, 13.36it/s]

Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1623/2529 [00:58<01:06, 13.54it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1625/2529 [00:58<01:08, 13.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  64%|██████▍   | 1629/2529 [00:58<00:48, 18.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▍   | 1633/2529 [00:58<00:41, 21.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▍   | 1636/2529 [00:58<00:41, 21.75it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▍   | 1639/2529 [00:58<00:38, 23.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▍   | 1642/2529 [00:58<00:36, 24.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▌   | 1646/2529 [00:59<00:35, 25.06it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▌   | 1649/2529 [00:59<00:44, 19.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▌   | 1652/2529 [00:59<00:46, 18.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  65%|██████▌   | 1655/2529 [00:59<00:48, 18.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▌   | 1659/2529 [00:59<00:39, 21.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▌   | 1662/2529 [00:59<00:39, 22.20it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▌   | 1665/2529 [01:00<00:41, 21.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▌   | 1669/2529 [01:00<00:35, 24.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▌   | 1672/2529 [01:00<00:34, 24.58it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▋   | 1676/2529 [01:00<00:31, 27.45it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  66%|██████▋   | 1681/2529 [01:00<00:29, 28.37it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1684/2529 [01:00<00:31, 27.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1687/2529 [01:00<00:33, 25.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1691/2529 [01:00<00:31, 26.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1694/2529 [01:01<00:30, 27.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1697/2529 [01:01<00:31, 26.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1700/2529 [01:01<00:38, 21.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1703/2529 [01:01<00:41, 19.88it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  67%|██████▋   | 1706/2529 [01:01<00:40, 20.43it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1709/2529 [01:01<00:39, 20.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1712/2529 [01:02<00:42, 19.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1714/2529 [01:02<00:43, 18.63it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1716/2529 [01:02<00:47, 17.25it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1718/2529 [01:02<00:45, 17.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1722/2529 [01:02<00:37, 21.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1725/2529 [01:02<00:38, 20.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1728/2529 [01:02<00:41, 19.10it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  68%|██████▊   | 1730/2529 [01:03<00:45, 17.64it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▊   | 1734/2529 [01:03<00:36, 21.55it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▊   | 1737/2529 [01:03<00:34, 22.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▉   | 1740/2529 [01:03<00:35, 22.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▉   | 1743/2529 [01:03<00:34, 22.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▉   | 1747/2529 [01:03<00:29, 26.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▉   | 1751/2529 [01:03<00:27, 28.14it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  69%|██████▉   | 1754/2529 [01:03<00:27, 27.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|██████▉   | 1758/2529 [01:03<00:25, 30.80it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|██████▉   | 1764/2529 [01:04<00:20, 37.65it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|██████▉   | 1768/2529 [01:04<00:20, 37.14it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|███████   | 1772/2529 [01:04<00:21, 34.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|███████   | 1776/2529 [01:04<00:23, 32.54it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  70%|███████   | 1780/2529 [01:04<00:23, 31.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████   | 1785/2529 [01:04<00:22, 32.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████   | 1789/2529 [01:05<00:29, 25.36it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████   | 1794/2529 [01:05<00:24, 30.00it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████   | 1800/2529 [01:05<00:21, 33.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████▏  | 1804/2529 [01:05<00:23, 31.22it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  71%|███████▏  | 1808/2529 [01:05<00:25, 28.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1812/2529 [01:05<00:23, 30.59it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1816/2529 [01:05<00:21, 32.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1820/2529 [01:05<00:21, 33.47it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1824/2529 [01:06<00:20, 34.51it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1828/2529 [01:06<00:20, 33.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  72%|███████▏  | 1832/2529 [01:06<00:19, 34.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1836/2529 [01:06<00:24, 28.74it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1840/2529 [01:06<00:24, 27.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1843/2529 [01:06<00:27, 25.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1846/2529 [01:06<00:30, 22.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1850/2529 [01:07<00:27, 24.48it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1853/2529 [01:07<00:27, 25.03it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  73%|███████▎  | 1857/2529 [01:07<00:24, 27.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▎  | 1861/2529 [01:07<00:22, 29.45it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▎  | 1865/2529 [01:07<00:21, 30.77it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▍  | 1869/2529 [01:07<00:21, 30.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▍  | 1873/2529 [01:07<00:24, 26.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▍  | 1876/2529 [01:08<00:29, 21.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▍  | 1879/2529 [01:08<00:30, 21.03it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  74%|███████▍  | 1882/2529 [01:08<00:29, 21.61it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▍  | 1886/2529 [01:08<00:25, 25.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▍  | 1890/2529 [01:08<00:22, 27.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▍  | 1893/2529 [01:08<00:23, 27.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▍  | 1896/2529 [01:08<00:24, 25.89it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▌  | 1900/2529 [01:08<00:22, 27.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  75%|███████▌  | 1905/2529 [01:09<00:18, 33.03it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▌  | 1910/2529 [01:09<00:20, 29.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▌  | 1914/2529 [01:09<00:21, 28.37it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▌  | 1918/2529 [01:09<00:20, 29.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▌  | 1922/2529 [01:09<00:19, 30.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▌  | 1926/2529 [01:09<00:18, 32.74it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▋  | 1930/2529 [01:09<00:18, 32.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  76%|███████▋  | 1934/2529 [01:09<00:18, 32.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1938/2529 [01:10<00:22, 26.77it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1941/2529 [01:10<00:21, 27.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1944/2529 [01:10<00:20, 27.97it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1949/2529 [01:10<00:18, 31.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1953/2529 [01:10<00:19, 29.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  77%|███████▋  | 1957/2529 [01:10<00:20, 27.33it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1960/2529 [01:10<00:20, 27.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1963/2529 [01:11<00:21, 26.50it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1966/2529 [01:11<00:21, 26.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1969/2529 [01:11<00:25, 21.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1972/2529 [01:11<00:34, 16.04it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1974/2529 [01:11<00:37, 14.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1976/2529 [01:12<00:37, 14.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1978/2529 [01:12<00:36, 15.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1980/2529 [01:12<00:37, 14.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  78%|███████▊  | 1983/2529 [01:12<00:33, 16.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▊  | 1986/2529 [01:12<00:30, 17.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▊  | 1989/2529 [01:12<00:27, 19.86it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 1993/2529 [01:12<00:22, 23.90it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 1996/2529 [01:12<00:24, 22.03it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 1999/2529 [01:13<00:26, 19.93it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 2002/2529 [01:13<00:25, 20.99it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 2006/2529 [01:13<00:20, 25.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  79%|███████▉  | 2010/2529 [01:13<00:18, 28.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|███████▉  | 2015/2529 [01:13<00:15, 33.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|███████▉  | 2019/2529 [01:13<00:20, 25.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|███████▉  | 2022/2529 [01:14<00:23, 21.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|████████  | 2026/2529 [01:14<00:20, 24.59it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|████████  | 2029/2529 [01:14<00:19, 25.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|████████  | 2032/2529 [01:14<00:19, 25.94it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  80%|████████  | 2035/2529 [01:14<00:19, 25.31it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████  | 2038/2529 [01:14<00:20, 23.45it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████  | 2041/2529 [01:14<00:21, 22.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████  | 2046/2529 [01:14<00:17, 27.76it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████  | 2050/2529 [01:15<00:16, 29.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████  | 2054/2529 [01:15<00:15, 31.14it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  81%|████████▏ | 2059/2529 [01:15<00:13, 35.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2063/2529 [01:15<00:14, 31.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2067/2529 [01:15<00:15, 30.71it/s]

Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2071/2529 [01:15<00:14, 30.55it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2075/2529 [01:15<00:16, 27.73it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2078/2529 [01:16<00:19, 23.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2082/2529 [01:16<00:19, 22.66it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  82%|████████▏ | 2085/2529 [01:16<00:19, 22.40it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2089/2529 [01:16<00:16, 26.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2092/2529 [01:16<00:19, 21.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2095/2529 [01:16<00:20, 20.84it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2099/2529 [01:16<00:18, 23.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2102/2529 [01:17<00:19, 22.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2106/2529 [01:17<00:16, 25.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  83%|████████▎ | 2109/2529 [01:17<00:16, 25.68it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▎ | 2113/2529 [01:17<00:14, 28.89it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▎ | 2117/2529 [01:17<00:17, 23.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▍ | 2120/2529 [01:17<00:17, 22.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▍ | 2124/2529 [01:17<00:15, 25.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▍ | 2128/2529 [01:18<00:14, 28.07it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▍ | 2132/2529 [01:18<00:13, 29.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  84%|████████▍ | 2136/2529 [01:18<00:12, 30.34it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  85%|████████▍ | 2140/2529 [01:18<00:11, 32.62it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  85%|████████▍ | 2144/2529 [01:18<00:12, 30.92it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  85%|████████▍ | 2149/2529 [01:18<00:11, 34.49it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  85%|████████▌ | 2154/2529 [01:18<00:09, 38.16it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  85%|████████▌ | 2158/2529 [01:18<00:09, 38.20it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▌ | 2163/2529 [01:18<00:09, 40.35it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▌ | 2168/2529 [01:19<00:09, 38.19it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▌ | 2172/2529 [01:19<00:09, 36.09it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▌ | 2176/2529 [01:19<00:10, 33.91it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▌ | 2180/2529 [01:19<00:09, 34.96it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  86%|████████▋ | 2185/2529 [01:19<00:09, 35.57it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2190/2529 [01:19<00:08, 38.11it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2195/2529 [01:19<00:09, 34.88it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2200/2529 [01:20<00:08, 36.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2204/2529 [01:20<00:08, 37.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2208/2529 [01:20<00:09, 35.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  87%|████████▋ | 2212/2529 [01:20<00:08, 35.66it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  88%|████████▊ | 2217/2529 [01:20<00:08, 38.83it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  88%|████████▊ | 2223/2529 [01:20<00:07, 41.75it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  88%|████████▊ | 2228/2529 [01:20<00:08, 36.69it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  88%|████████▊ | 2232/2529 [01:20<00:08, 36.47it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  88%|████████▊ | 2236/2529 [01:21<00:10, 28.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▊ | 2240/2529 [01:21<00:09, 30.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▊ | 2244/2529 [01:21<00:09, 30.70it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▉ | 2248/2529 [01:21<00:09, 29.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▉ | 2252/2529 [01:21<00:09, 30.54it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▉ | 2258/2529 [01:21<00:07, 36.89it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  89%|████████▉ | 2262/2529 [01:21<00:07, 33.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|████████▉ | 2267/2529 [01:21<00:07, 36.15it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|████████▉ | 2271/2529 [01:22<00:07, 35.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|████████▉ | 2275/2529 [01:22<00:07, 31.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|█████████ | 2279/2529 [01:22<00:08, 31.08it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|█████████ | 2284/2529 [01:22<00:06, 35.17it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  90%|█████████ | 2288/2529 [01:22<00:06, 35.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████ | 2292/2529 [01:22<00:06, 35.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████ | 2297/2529 [01:22<00:06, 38.44it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████ | 2301/2529 [01:22<00:06, 36.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████ | 2305/2529 [01:23<00:06, 35.01it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████▏| 2309/2529 [01:23<00:06, 33.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  91%|█████████▏| 2313/2529 [01:23<00:06, 33.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2317/2529 [01:23<00:07, 29.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2322/2529 [01:23<00:06, 33.87it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2326/2529 [01:23<00:05, 34.27it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2330/2529 [01:23<00:05, 34.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2335/2529 [01:23<00:05, 37.95it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  92%|█████████▏| 2339/2529 [01:24<00:05, 36.41it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  93%|█████████▎| 2343/2529 [01:24<00:04, 37.28it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  93%|█████████▎| 2347/2529 [01:24<00:05, 35.78it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  93%|█████████▎| 2351/2529 [01:24<00:05, 32.82it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  93%|█████████▎| 2355/2529 [01:24<00:05, 31.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  93%|█████████▎| 2360/2529 [01:24<00:05, 33.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▎| 2366/2529 [01:24<00:04, 35.98it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▎| 2370/2529 [01:24<00:04, 35.46it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▍| 2374/2529 [01:25<00:04, 33.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▍| 2378/2529 [01:25<00:04, 34.18it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▍| 2382/2529 [01:25<00:04, 34.29it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  94%|█████████▍| 2388/2529 [01:25<00:03, 40.62it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  95%|█████████▍| 2393/2529 [01:25<00:03, 38.68it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  95%|█████████▍| 2398/2529 [01:25<00:03, 40.21it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  95%|█████████▌| 2404/2529 [01:25<00:02, 43.59it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  95%|█████████▌| 2409/2529 [01:26<00:03, 36.23it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  95%|█████████▌| 2414/2529 [01:26<00:03, 37.53it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  96%|█████████▌| 2420/2529 [01:26<00:02, 39.21it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  96%|█████████▌| 2425/2529 [01:26<00:02, 40.30it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  96%|█████████▌| 2430/2529 [01:26<00:02, 40.71it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  96%|█████████▋| 2435/2529 [01:26<00:02, 37.32it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  96%|█████████▋| 2439/2529 [01:26<00:02, 34.79it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  97%|█████████▋| 2445/2529 [01:26<00:02, 38.60it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  97%|█████████▋| 2449/2529 [01:27<00:02, 38.80it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  97%|█████████▋| 2454/2529 [01:27<00:01, 37.52it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  97%|█████████▋| 2458/2529 [01:27<00:02, 35.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  97%|█████████▋| 2462/2529 [01:27<00:04, 16.05it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  98%|█████████▊| 2466/2529 [01:28<00:03, 18.42it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  98%|█████████▊| 2472/2529 [01:28<00:02, 24.21it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  98%|█████████▊| 2477/2529 [01:28<00:01, 27.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  98%|█████████▊| 2482/2529 [01:28<00:01, 30.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  98%|█████████▊| 2488/2529 [01:28<00:01, 35.85it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▊| 2494/2529 [01:28<00:00, 40.38it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▉| 2499/2529 [01:28<00:00, 34.68it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▉| 2503/2529 [01:28<00:00, 34.58it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▉| 2507/2529 [01:29<00:00, 33.24it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▉| 2511/2529 [01:29<00:00, 34.28it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene:  99%|█████████▉| 2515/2529 [01:29<00:00, 35.02it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene: 100%|█████████▉| 2519/2529 [01:29<00:00, 35.37it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene: 100%|█████████▉| 2525/2529 [01:29<00:00, 38.81it/s]
Processing: positive r2g, Top 5 region-to-gene links per gene: 100%|██████████| 2529/2529 [01:29<00:00, 38.61it/s]
 79%|███████▊  | 11/14 [30:21<06:46, 135.43s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   0%|          | 3/2529 [00:00<01:37, 25.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   0%|          | 6/2529 [00:00<01:35, 26.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   0%|          | 9/2529 [00:00<01:42, 24.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   0%|          | 12/2529 [00:00<01:50, 22.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 15/2529 [00:00<01:48, 23.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 18/2529 [00:00<01:41, 24.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 21/2529 [00:00<02:10, 19.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 24/2529 [00:01<02:10, 19.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 27/2529 [00:01<02:00, 20.80it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|          | 30/2529 [00:01<02:10, 19.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|▏         | 33/2529 [00:01<02:22, 17.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   1%|▏         | 36/2529 [00:01<02:07, 19.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 39/2529 [00:01<02:06, 19.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 42/2529 [00:02<02:12, 18.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 45/2529 [00:02<02:03, 20.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 48/2529 [00:02<02:14, 18.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 50/2529 [00:02<02:12, 18.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 53/2529 [00:02<02:09, 19.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 56/2529 [00:02<01:58, 20.91it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:   2%|▏         | 60/2529 [00:02<01:40, 24.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 64/2529 [00:03<01:35, 25.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 67/2529 [00:03<01:32, 26.70it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 70/2529 [00:03<01:38, 24.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 73/2529 [00:03<01:51, 22.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 76/2529 [00:03<02:11, 18.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 79/2529 [00:03<02:01, 20.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 82/2529 [00:03<01:53, 21.51it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 85/2529 [00:04<01:55, 21.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   3%|▎         | 88/2529 [00:04<02:03, 19.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▎         | 91/2529 [00:04<01:56, 20.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▎         | 94/2529 [00:04<01:46, 22.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 97/2529 [00:04<01:48, 22.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 100/2529 [00:04<02:08, 18.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 103/2529 [00:04<02:08, 18.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 107/2529 [00:05<01:47, 22.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 110/2529 [00:05<01:47, 22.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   4%|▍         | 113/2529 [00:05<01:48, 22.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▍         | 116/2529 [00:05<02:25, 16.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▍         | 118/2529 [00:05<02:54, 13.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▍         | 120/2529 [00:06<02:55, 13.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▍         | 122/2529 [00:06<02:58, 13.50it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▍         | 124/2529 [00:06<02:53, 13.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 127/2529 [00:06<02:53, 13.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 129/2529 [00:06<03:02, 13.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 131/2529 [00:06<03:09, 12.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 133/2529 [00:07<03:28, 11.51it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 135/2529 [00:07<03:30, 11.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 137/2529 [00:07<03:43, 10.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   5%|▌         | 139/2529 [00:07<03:43, 10.70it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 141/2529 [00:07<03:15, 12.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 143/2529 [00:07<03:02, 13.09it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 145/2529 [00:08<03:11, 12.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 147/2529 [00:08<03:01, 13.13it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 149/2529 [00:08<02:59, 13.29it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 152/2529 [00:08<02:20, 16.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 155/2529 [00:08<02:34, 15.35it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▌         | 157/2529 [00:08<02:56, 13.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▋         | 159/2529 [00:09<03:07, 12.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▋         | 161/2529 [00:09<03:27, 11.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   6%|▋         | 163/2529 [00:09<03:30, 11.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 165/2529 [00:09<03:08, 12.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 167/2529 [00:09<02:52, 13.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 169/2529 [00:09<03:01, 13.03it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 171/2529 [00:10<02:55, 13.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 173/2529 [00:10<03:06, 12.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 175/2529 [00:10<03:07, 12.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 177/2529 [00:10<02:55, 13.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 180/2529 [00:10<02:37, 14.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 183/2529 [00:10<02:16, 17.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 186/2529 [00:10<02:05, 18.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   7%|▋         | 189/2529 [00:11<02:00, 19.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 191/2529 [00:11<02:10, 17.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 193/2529 [00:11<02:08, 18.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 196/2529 [00:11<02:01, 19.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 199/2529 [00:11<01:54, 20.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 202/2529 [00:11<01:44, 22.35it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 205/2529 [00:11<02:08, 18.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 208/2529 [00:12<02:01, 19.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 211/2529 [00:12<01:53, 20.51it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   8%|▊         | 214/2529 [00:12<02:11, 17.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▊         | 217/2529 [00:12<02:00, 19.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▊         | 221/2529 [00:12<01:47, 21.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 224/2529 [00:12<01:42, 22.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 227/2529 [00:12<01:49, 21.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 230/2529 [00:13<01:42, 22.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 233/2529 [00:13<01:40, 22.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 236/2529 [00:13<01:33, 24.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:   9%|▉         | 239/2529 [00:13<01:31, 25.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|▉         | 242/2529 [00:13<01:42, 22.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|▉         | 246/2529 [00:13<01:40, 22.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|▉         | 249/2529 [00:13<01:45, 21.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|▉         | 252/2529 [00:14<01:49, 20.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|█         | 255/2529 [00:14<01:39, 22.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|█         | 258/2529 [00:14<01:43, 22.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|█         | 262/2529 [00:14<01:51, 20.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  10%|█         | 265/2529 [00:14<01:51, 20.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█         | 269/2529 [00:14<01:37, 23.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█         | 272/2529 [00:14<01:40, 22.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█         | 275/2529 [00:15<01:43, 21.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█         | 279/2529 [00:15<01:30, 24.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█         | 282/2529 [00:15<01:37, 23.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█▏        | 285/2529 [00:15<01:34, 23.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  11%|█▏        | 288/2529 [00:15<01:32, 24.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 291/2529 [00:15<01:41, 22.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 294/2529 [00:15<01:41, 21.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 297/2529 [00:16<01:41, 21.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 300/2529 [00:16<01:53, 19.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 303/2529 [00:16<01:47, 20.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 306/2529 [00:16<01:41, 21.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 310/2529 [00:16<01:31, 24.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 313/2529 [00:16<01:28, 25.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  12%|█▏        | 316/2529 [00:16<01:25, 26.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 319/2529 [00:16<01:22, 26.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 322/2529 [00:17<01:30, 24.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 325/2529 [00:17<01:31, 23.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 328/2529 [00:17<01:31, 24.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 331/2529 [00:17<01:43, 21.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 334/2529 [00:17<01:58, 18.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 337/2529 [00:17<01:54, 19.13it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  13%|█▎        | 340/2529 [00:17<01:49, 20.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▎        | 343/2529 [00:18<02:05, 17.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▎        | 346/2529 [00:18<01:58, 18.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 348/2529 [00:18<02:00, 18.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 352/2529 [00:18<01:44, 20.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 355/2529 [00:18<01:59, 18.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 357/2529 [00:19<02:12, 16.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 359/2529 [00:19<02:29, 14.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 361/2529 [00:19<02:54, 12.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 363/2529 [00:19<03:06, 11.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  14%|█▍        | 365/2529 [00:19<03:16, 11.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 367/2529 [00:20<03:38,  9.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 369/2529 [00:20<03:32, 10.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 371/2529 [00:20<03:42,  9.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 373/2529 [00:20<03:35,  9.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 375/2529 [00:20<03:40,  9.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▍        | 378/2529 [00:21<02:45, 12.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▌        | 381/2529 [00:21<02:18, 15.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▌        | 383/2529 [00:21<02:19, 15.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▌        | 386/2529 [00:21<02:04, 17.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  15%|█▌        | 389/2529 [00:21<01:56, 18.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 392/2529 [00:21<01:52, 18.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 394/2529 [00:21<01:57, 18.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 396/2529 [00:22<02:27, 14.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 398/2529 [00:22<02:36, 13.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 400/2529 [00:22<02:41, 13.17it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 402/2529 [00:22<02:26, 14.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 404/2529 [00:22<02:48, 12.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 407/2529 [00:22<02:14, 15.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▌        | 409/2529 [00:22<02:13, 15.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▋        | 411/2529 [00:23<02:19, 15.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▋        | 413/2529 [00:23<02:19, 15.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  16%|█▋        | 417/2529 [00:23<01:50, 19.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 419/2529 [00:23<01:56, 18.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 422/2529 [00:23<01:47, 19.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 425/2529 [00:23<01:39, 21.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 428/2529 [00:23<01:46, 19.80it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 431/2529 [00:24<01:48, 19.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 433/2529 [00:24<02:04, 16.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 436/2529 [00:24<01:52, 18.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 438/2529 [00:24<01:52, 18.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  17%|█▋        | 440/2529 [00:24<01:56, 17.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 443/2529 [00:24<01:43, 20.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 446/2529 [00:24<01:55, 18.09it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 448/2529 [00:25<02:06, 16.50it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 450/2529 [00:25<02:28, 13.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 452/2529 [00:25<02:34, 13.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 454/2529 [00:25<02:22, 14.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 456/2529 [00:25<02:27, 14.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 458/2529 [00:25<02:24, 14.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 460/2529 [00:25<02:30, 13.70it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 463/2529 [00:26<02:06, 16.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  18%|█▊        | 466/2529 [00:26<02:03, 16.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▊        | 468/2529 [00:26<02:12, 15.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▊        | 470/2529 [00:26<02:26, 14.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▊        | 472/2529 [00:26<02:42, 12.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▊        | 474/2529 [00:26<02:26, 14.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 477/2529 [00:27<02:13, 15.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 479/2529 [00:27<02:05, 16.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 481/2529 [00:27<02:09, 15.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 483/2529 [00:27<02:06, 16.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 486/2529 [00:27<01:47, 19.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 490/2529 [00:27<01:26, 23.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  19%|█▉        | 493/2529 [00:27<01:30, 22.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|█▉        | 496/2529 [00:27<01:28, 23.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|█▉        | 500/2529 [00:28<01:18, 25.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|█▉        | 503/2529 [00:28<01:20, 25.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|██        | 506/2529 [00:28<01:20, 25.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|██        | 509/2529 [00:28<01:28, 22.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|██        | 512/2529 [00:28<01:34, 21.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  20%|██        | 515/2529 [00:28<01:40, 20.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 519/2529 [00:28<01:26, 23.33it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 522/2529 [00:29<01:32, 21.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 525/2529 [00:29<01:49, 18.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 529/2529 [00:29<01:33, 21.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 533/2529 [00:29<01:23, 24.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██        | 536/2529 [00:29<01:25, 23.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██▏       | 539/2529 [00:29<01:37, 20.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  21%|██▏       | 542/2529 [00:30<01:46, 18.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 544/2529 [00:30<01:48, 18.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 547/2529 [00:30<01:35, 20.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 551/2529 [00:30<01:26, 22.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 554/2529 [00:30<01:26, 22.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 557/2529 [00:30<01:24, 23.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 560/2529 [00:30<01:27, 22.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 563/2529 [00:30<01:26, 22.61it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  22%|██▏       | 567/2529 [00:31<01:29, 22.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 570/2529 [00:31<01:31, 21.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 573/2529 [00:31<01:30, 21.50it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 576/2529 [00:31<01:40, 19.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 578/2529 [00:31<01:57, 16.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 581/2529 [00:31<01:46, 18.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 584/2529 [00:32<01:45, 18.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 587/2529 [00:32<01:35, 20.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 590/2529 [00:32<01:31, 21.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  23%|██▎       | 593/2529 [00:32<01:34, 20.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▎       | 596/2529 [00:32<01:26, 22.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▎       | 599/2529 [00:32<01:34, 20.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 602/2529 [00:32<01:35, 20.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 605/2529 [00:33<02:04, 15.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 607/2529 [00:33<02:14, 14.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 609/2529 [00:33<02:17, 13.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 612/2529 [00:33<02:05, 15.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 615/2529 [00:33<01:52, 17.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  24%|██▍       | 618/2529 [00:34<01:43, 18.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▍       | 621/2529 [00:34<01:38, 19.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▍       | 624/2529 [00:34<01:43, 18.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▍       | 627/2529 [00:34<01:39, 19.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▍       | 631/2529 [00:34<01:25, 22.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▌       | 634/2529 [00:34<01:22, 23.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▌       | 637/2529 [00:34<01:35, 19.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▌       | 640/2529 [00:35<01:42, 18.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  25%|██▌       | 643/2529 [00:35<01:37, 19.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 647/2529 [00:35<01:27, 21.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 650/2529 [00:35<01:22, 22.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 653/2529 [00:35<01:27, 21.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 656/2529 [00:35<01:28, 21.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 659/2529 [00:36<01:37, 19.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▌       | 661/2529 [00:36<01:41, 18.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▋       | 664/2529 [00:36<01:31, 20.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  26%|██▋       | 667/2529 [00:36<01:30, 20.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 671/2529 [00:36<01:19, 23.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 674/2529 [00:36<01:25, 21.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 677/2529 [00:36<01:30, 20.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 680/2529 [00:37<01:32, 19.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 683/2529 [00:37<01:29, 20.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 686/2529 [00:37<01:33, 19.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 689/2529 [00:37<01:36, 19.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 691/2529 [00:37<02:17, 13.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 693/2529 [00:38<02:41, 11.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  27%|██▋       | 695/2529 [00:38<02:48, 10.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 697/2529 [00:38<02:45, 11.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 699/2529 [00:38<02:37, 11.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 701/2529 [00:38<02:44, 11.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 703/2529 [00:38<02:28, 12.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 705/2529 [00:39<02:26, 12.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 707/2529 [00:39<02:10, 13.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 709/2529 [00:39<02:06, 14.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 712/2529 [00:39<01:53, 16.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 714/2529 [00:39<02:10, 13.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 716/2529 [00:39<02:22, 12.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 718/2529 [00:39<02:09, 14.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  28%|██▊       | 720/2529 [00:40<02:01, 14.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▊       | 723/2529 [00:40<01:49, 16.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▊       | 727/2529 [00:40<01:26, 20.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 730/2529 [00:40<01:23, 21.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 734/2529 [00:40<01:35, 18.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 737/2529 [00:40<01:50, 16.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 739/2529 [00:41<01:50, 16.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 742/2529 [00:41<01:41, 17.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 742/2529 [01:57<01:41, 17.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  29%|██▉       | 745/2529 [01:57<3:55:23,  7.92s/it]

Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|██▉       | 747/2529 [01:57<3:01:58,  6.13s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|██▉       | 749/2529 [01:57<2:17:48,  4.65s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|██▉       | 752/2529 [01:58<1:30:49,  3.07s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|██▉       | 755/2529 [01:58<1:01:22,  2.08s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|██▉       | 757/2529 [01:58<47:03,  1.59s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|███       | 760/2529 [01:58<31:25,  1.07s/it]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|███       | 763/2529 [01:58<21:29,  1.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|███       | 766/2529 [01:58<15:07,  1.94it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  30%|███       | 769/2529 [01:58<10:49,  2.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 772/2529 [01:58<07:47,  3.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 775/2529 [01:59<05:42,  5.11it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 778/2529 [01:59<04:27,  6.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 781/2529 [01:59<03:28,  8.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 784/2529 [01:59<02:55,  9.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 787/2529 [01:59<02:38, 10.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███       | 789/2529 [01:59<02:26, 11.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███▏      | 791/2529 [02:00<02:38, 10.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███▏      | 794/2529 [02:00<02:08, 13.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  31%|███▏      | 796/2529 [02:00<02:16, 12.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 798/2529 [02:00<02:17, 12.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 801/2529 [02:00<01:51, 15.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 804/2529 [02:00<02:09, 13.33it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 806/2529 [02:01<02:02, 14.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 808/2529 [02:01<02:12, 13.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 811/2529 [02:01<01:51, 15.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 814/2529 [02:01<01:37, 17.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 816/2529 [02:01<01:43, 16.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 818/2529 [02:01<01:38, 17.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  32%|███▏      | 820/2529 [02:01<01:35, 17.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 823/2529 [02:02<01:25, 20.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 826/2529 [02:02<01:27, 19.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 828/2529 [02:02<01:57, 14.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 831/2529 [02:02<01:41, 16.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 834/2529 [02:02<01:36, 17.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 836/2529 [02:02<01:36, 17.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 840/2529 [02:02<01:24, 19.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 843/2529 [02:03<01:19, 21.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  33%|███▎      | 846/2529 [02:03<01:20, 21.03it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▎      | 849/2529 [02:03<01:17, 21.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▎      | 852/2529 [02:03<01:18, 21.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 855/2529 [02:03<01:11, 23.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 859/2529 [02:03<01:05, 25.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 862/2529 [02:03<01:04, 25.84it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 865/2529 [02:03<01:06, 24.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 868/2529 [02:04<01:04, 25.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  34%|███▍      | 872/2529 [02:04<01:02, 26.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▍      | 875/2529 [02:04<01:07, 24.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▍      | 878/2529 [02:04<01:07, 24.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▍      | 881/2529 [02:04<01:10, 23.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▍      | 884/2529 [02:04<01:18, 20.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▌      | 887/2529 [02:04<01:13, 22.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▌      | 891/2529 [02:05<01:04, 25.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▌      | 894/2529 [02:05<01:08, 23.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  35%|███▌      | 897/2529 [02:05<01:07, 24.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 900/2529 [02:05<01:11, 22.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 903/2529 [02:05<01:22, 19.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 906/2529 [02:05<01:17, 21.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 909/2529 [02:05<01:15, 21.33it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 912/2529 [02:06<01:17, 20.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▌      | 915/2529 [02:06<01:12, 22.13it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▋      | 918/2529 [02:06<01:15, 21.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  36%|███▋      | 921/2529 [02:06<01:11, 22.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 925/2529 [02:06<01:02, 25.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 929/2529 [02:06<00:57, 27.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 932/2529 [02:06<00:59, 27.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 935/2529 [02:07<01:12, 21.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 938/2529 [02:07<01:13, 21.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 941/2529 [02:07<01:29, 17.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 943/2529 [02:07<01:35, 16.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  37%|███▋      | 947/2529 [02:07<01:18, 20.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 950/2529 [02:07<01:15, 20.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 953/2529 [02:07<01:18, 20.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 956/2529 [02:08<01:19, 19.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 959/2529 [02:08<01:13, 21.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 963/2529 [02:08<01:03, 24.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 966/2529 [02:08<01:10, 22.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 969/2529 [02:08<01:08, 22.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  38%|███▊      | 972/2529 [02:08<01:03, 24.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▊      | 975/2529 [02:08<01:02, 24.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▊      | 978/2529 [02:09<01:15, 20.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 981/2529 [02:09<01:11, 21.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 984/2529 [02:09<01:12, 21.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 987/2529 [02:09<01:10, 21.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 990/2529 [02:09<01:06, 23.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 993/2529 [02:09<01:08, 22.51it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  39%|███▉      | 996/2529 [02:09<01:03, 24.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|███▉      | 999/2529 [02:09<01:02, 24.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|███▉      | 1003/2529 [02:10<00:59, 25.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|███▉      | 1006/2529 [02:10<01:03, 23.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|███▉      | 1009/2529 [02:10<01:09, 21.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|████      | 1012/2529 [02:10<01:11, 21.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|████      | 1015/2529 [02:10<01:23, 18.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|████      | 1017/2529 [02:10<01:23, 18.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|████      | 1020/2529 [02:11<01:12, 20.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  40%|████      | 1023/2529 [02:11<01:07, 22.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1026/2529 [02:11<01:09, 21.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1029/2529 [02:11<01:09, 21.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1033/2529 [02:11<01:03, 23.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1037/2529 [02:11<00:59, 25.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1040/2529 [02:11<01:02, 23.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████      | 1043/2529 [02:11<01:01, 24.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████▏     | 1046/2529 [02:12<01:06, 22.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  41%|████▏     | 1049/2529 [02:12<01:02, 23.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1052/2529 [02:12<01:16, 19.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1055/2529 [02:12<01:11, 20.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1058/2529 [02:12<01:06, 22.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1061/2529 [02:12<01:02, 23.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1065/2529 [02:12<01:03, 23.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1068/2529 [02:13<01:04, 22.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  42%|████▏     | 1072/2529 [02:13<00:58, 24.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1075/2529 [02:13<01:08, 21.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1078/2529 [02:13<01:04, 22.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1081/2529 [02:13<01:04, 22.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1085/2529 [02:13<00:57, 25.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1088/2529 [02:13<00:54, 26.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1091/2529 [02:14<00:59, 24.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1094/2529 [02:14<00:58, 24.35it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  43%|████▎     | 1097/2529 [02:14<00:56, 25.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▎     | 1101/2529 [02:14<00:51, 27.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▎     | 1104/2529 [02:14<01:05, 21.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1107/2529 [02:14<01:02, 22.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1111/2529 [02:14<00:58, 24.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1114/2529 [02:14<00:56, 25.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1117/2529 [02:15<00:55, 25.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1120/2529 [02:15<00:55, 25.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  44%|████▍     | 1123/2529 [02:15<00:53, 26.39it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▍     | 1126/2529 [02:15<00:54, 25.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▍     | 1129/2529 [02:15<01:05, 21.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▍     | 1132/2529 [02:15<01:02, 22.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▍     | 1135/2529 [02:15<01:03, 21.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▌     | 1139/2529 [02:16<00:55, 24.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▌     | 1142/2529 [02:16<00:56, 24.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▌     | 1145/2529 [02:16<00:55, 25.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  45%|████▌     | 1148/2529 [02:16<00:54, 25.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1151/2529 [02:16<00:56, 24.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1154/2529 [02:16<00:59, 23.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1157/2529 [02:16<00:56, 24.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1160/2529 [02:16<00:58, 23.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1163/2529 [02:17<01:00, 22.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▌     | 1167/2529 [02:17<00:55, 24.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▋     | 1170/2529 [02:17<00:52, 25.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  46%|████▋     | 1173/2529 [02:17<00:55, 24.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1176/2529 [02:17<00:55, 24.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1180/2529 [02:17<00:50, 26.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1184/2529 [02:17<00:49, 27.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1188/2529 [02:17<00:45, 29.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1191/2529 [02:18<00:52, 25.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1194/2529 [02:18<00:58, 22.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1197/2529 [02:18<01:05, 20.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  47%|████▋     | 1200/2529 [02:18<01:02, 21.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1203/2529 [02:18<01:01, 21.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1207/2529 [02:18<00:59, 22.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1210/2529 [02:19<00:59, 22.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1213/2529 [02:19<00:57, 23.03it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1216/2529 [02:19<00:55, 23.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1219/2529 [02:19<00:57, 22.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1222/2529 [02:19<00:55, 23.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  48%|████▊     | 1225/2529 [02:19<00:54, 23.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▊     | 1228/2529 [02:19<00:57, 22.61it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▊     | 1231/2529 [02:19<00:55, 23.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1234/2529 [02:20<00:58, 22.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1237/2529 [02:20<00:56, 22.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1240/2529 [02:20<00:54, 23.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1243/2529 [02:20<01:16, 16.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1245/2529 [02:20<01:23, 15.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1247/2529 [02:20<01:21, 15.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  49%|████▉     | 1249/2529 [02:21<01:20, 15.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|████▉     | 1252/2529 [02:21<01:09, 18.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|████▉     | 1255/2529 [02:21<01:13, 17.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|████▉     | 1257/2529 [02:21<01:20, 15.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|████▉     | 1259/2529 [02:21<01:20, 15.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|████▉     | 1262/2529 [02:21<01:10, 17.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|█████     | 1265/2529 [02:21<01:09, 18.11it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|█████     | 1267/2529 [02:22<01:11, 17.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|█████     | 1270/2529 [02:22<01:05, 19.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|█████     | 1273/2529 [02:22<00:59, 21.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  50%|█████     | 1276/2529 [02:22<01:17, 16.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1278/2529 [02:22<01:14, 16.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1280/2529 [02:22<01:11, 17.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1283/2529 [02:22<01:04, 19.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1286/2529 [02:22<00:57, 21.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1290/2529 [02:23<00:49, 24.84it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1293/2529 [02:23<00:47, 26.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████     | 1296/2529 [02:23<00:45, 26.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████▏    | 1299/2529 [02:23<00:49, 24.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  51%|█████▏    | 1302/2529 [02:23<00:55, 22.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1305/2529 [02:23<01:03, 19.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1308/2529 [02:23<01:03, 19.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1311/2529 [02:24<00:58, 20.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1315/2529 [02:24<00:52, 22.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1318/2529 [02:24<00:54, 22.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1321/2529 [02:24<00:59, 20.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1324/2529 [02:24<00:56, 21.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  52%|█████▏    | 1327/2529 [02:24<00:55, 21.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1330/2529 [02:24<00:55, 21.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1333/2529 [02:25<01:06, 18.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1335/2529 [02:25<01:06, 18.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1338/2529 [02:25<00:59, 19.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1342/2529 [02:25<00:54, 21.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1345/2529 [02:25<00:53, 22.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1348/2529 [02:25<01:06, 17.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1350/2529 [02:26<01:21, 14.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  53%|█████▎    | 1352/2529 [02:26<01:27, 13.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▎    | 1354/2529 [02:26<01:31, 12.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▎    | 1356/2529 [02:26<01:27, 13.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▎    | 1358/2529 [02:26<01:25, 13.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1361/2529 [02:27<01:25, 13.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1363/2529 [02:27<01:30, 12.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1365/2529 [02:27<01:35, 12.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1367/2529 [02:27<01:43, 11.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1369/2529 [02:27<01:46, 10.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1371/2529 [02:28<01:52, 10.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1373/2529 [02:28<01:51, 10.35it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1375/2529 [02:28<01:37, 11.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  54%|█████▍    | 1377/2529 [02:28<01:30, 12.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▍    | 1379/2529 [02:28<01:34, 12.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▍    | 1381/2529 [02:28<01:28, 12.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▍    | 1383/2529 [02:28<01:27, 13.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▍    | 1386/2529 [02:29<01:08, 16.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▍    | 1389/2529 [02:29<01:16, 14.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1391/2529 [02:29<01:27, 13.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1393/2529 [02:29<01:32, 12.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1395/2529 [02:29<01:41, 11.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1397/2529 [02:30<01:42, 11.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1399/2529 [02:30<01:30, 12.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1401/2529 [02:30<01:23, 13.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  55%|█████▌    | 1403/2529 [02:30<01:19, 14.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1405/2529 [02:30<01:13, 15.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1407/2529 [02:30<01:26, 12.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1409/2529 [02:30<01:28, 12.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1411/2529 [02:31<01:27, 12.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1413/2529 [02:31<01:20, 13.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1415/2529 [02:31<01:14, 14.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1418/2529 [02:31<01:04, 17.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▌    | 1421/2529 [02:31<01:00, 18.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▋    | 1423/2529 [02:31<00:59, 18.61it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▋    | 1425/2529 [02:31<01:03, 17.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  56%|█████▋    | 1427/2529 [02:31<01:03, 17.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1429/2529 [02:32<01:01, 17.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1432/2529 [02:32<00:57, 19.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1435/2529 [02:32<00:54, 19.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1438/2529 [02:32<00:54, 19.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1440/2529 [02:32<01:06, 16.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1442/2529 [02:32<01:03, 17.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1445/2529 [02:32<00:57, 18.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1448/2529 [02:32<00:52, 20.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1451/2529 [02:33<01:04, 16.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  57%|█████▋    | 1453/2529 [02:33<01:04, 16.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1457/2529 [02:33<00:52, 20.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1460/2529 [02:33<00:51, 20.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1463/2529 [02:33<00:56, 18.94it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1467/2529 [02:33<00:48, 21.93it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1470/2529 [02:34<00:47, 22.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1473/2529 [02:34<00:46, 22.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1476/2529 [02:34<00:42, 24.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  58%|█████▊    | 1479/2529 [02:34<00:47, 22.11it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▊    | 1482/2529 [02:34<00:47, 22.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▊    | 1485/2529 [02:34<00:46, 22.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1488/2529 [02:34<00:48, 21.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1491/2529 [02:35<00:51, 20.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1494/2529 [02:35<00:47, 21.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1498/2529 [02:35<00:42, 24.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1501/2529 [02:35<00:44, 22.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  59%|█████▉    | 1504/2529 [02:35<00:41, 24.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|█████▉    | 1507/2529 [02:35<00:52, 19.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|█████▉    | 1510/2529 [02:35<00:50, 20.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|█████▉    | 1513/2529 [02:36<00:47, 21.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|█████▉    | 1516/2529 [02:36<00:50, 19.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|██████    | 1519/2529 [02:36<00:48, 20.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|██████    | 1523/2529 [02:36<00:43, 23.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|██████    | 1526/2529 [02:36<00:46, 21.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  60%|██████    | 1529/2529 [02:36<00:42, 23.29it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1532/2529 [02:36<00:46, 21.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1535/2529 [02:37<00:47, 20.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1538/2529 [02:37<00:48, 20.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1541/2529 [02:37<00:51, 19.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1544/2529 [02:37<00:49, 19.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████    | 1547/2529 [02:37<00:46, 20.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████▏   | 1550/2529 [02:37<00:43, 22.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  61%|██████▏   | 1553/2529 [02:37<00:40, 24.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1556/2529 [02:38<00:39, 24.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1559/2529 [02:38<00:37, 25.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1562/2529 [02:38<00:37, 25.52it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1565/2529 [02:38<00:41, 23.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1568/2529 [02:38<00:41, 23.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1571/2529 [02:38<00:42, 22.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1575/2529 [02:38<00:38, 24.84it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  62%|██████▏   | 1578/2529 [02:38<00:37, 25.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1581/2529 [02:39<00:48, 19.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1584/2529 [02:39<00:52, 18.13it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1587/2529 [02:39<00:48, 19.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1590/2529 [02:39<00:49, 18.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1593/2529 [02:39<00:56, 16.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1595/2529 [02:39<00:55, 16.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1597/2529 [02:40<00:55, 16.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1601/2529 [02:40<00:47, 19.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1603/2529 [02:40<00:51, 18.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  63%|██████▎   | 1605/2529 [02:40<00:58, 15.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▎   | 1607/2529 [02:40<01:00, 15.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▎   | 1609/2529 [02:40<01:10, 13.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▎   | 1611/2529 [02:41<01:18, 11.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1613/2529 [02:41<01:23, 10.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1615/2529 [02:41<01:33,  9.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1617/2529 [02:41<01:32,  9.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1619/2529 [02:42<01:32,  9.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1621/2529 [02:42<01:37,  9.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1622/2529 [02:42<01:36,  9.35it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1624/2529 [02:42<01:35,  9.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1625/2529 [02:42<01:36,  9.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1628/2529 [02:42<01:09, 12.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  64%|██████▍   | 1631/2529 [02:42<00:59, 15.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▍   | 1633/2529 [02:43<00:55, 16.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▍   | 1635/2529 [02:43<00:57, 15.44it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▍   | 1637/2529 [02:43<00:55, 16.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▍   | 1639/2529 [02:43<00:53, 16.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▍   | 1642/2529 [02:43<00:50, 17.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1644/2529 [02:43<00:48, 18.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1646/2529 [02:43<00:49, 17.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1648/2529 [02:44<01:04, 13.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1650/2529 [02:44<01:07, 13.09it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1652/2529 [02:44<01:09, 12.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1654/2529 [02:44<01:02, 14.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  65%|██████▌   | 1656/2529 [02:44<01:11, 12.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1659/2529 [02:44<00:56, 15.51it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1661/2529 [02:44<00:55, 15.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1663/2529 [02:45<00:58, 14.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1665/2529 [02:45<00:57, 14.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1668/2529 [02:45<00:51, 16.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1670/2529 [02:45<00:49, 17.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1672/2529 [02:45<00:48, 17.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▌   | 1675/2529 [02:45<00:44, 19.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▋   | 1678/2529 [02:45<00:40, 21.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  66%|██████▋   | 1681/2529 [02:45<00:43, 19.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1683/2529 [02:46<00:44, 18.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1685/2529 [02:46<00:49, 17.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1687/2529 [02:46<00:49, 16.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1690/2529 [02:46<00:45, 18.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1692/2529 [02:46<00:49, 16.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1695/2529 [02:46<00:44, 18.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1697/2529 [02:46<00:45, 18.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1699/2529 [02:47<00:49, 16.70it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1701/2529 [02:47<00:53, 15.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1703/2529 [02:47<01:04, 12.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  67%|██████▋   | 1706/2529 [02:47<01:00, 13.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1708/2529 [02:47<01:02, 13.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1711/2529 [02:47<00:57, 14.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1713/2529 [02:48<01:01, 13.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1715/2529 [02:48<01:02, 12.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1717/2529 [02:48<01:06, 12.26it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1720/2529 [02:48<00:54, 14.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1722/2529 [02:48<00:53, 15.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1724/2529 [02:48<00:50, 15.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1726/2529 [02:49<00:58, 13.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1728/2529 [02:49<01:02, 12.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  68%|██████▊   | 1730/2529 [02:49<01:07, 11.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▊   | 1733/2529 [02:49<00:54, 14.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▊   | 1736/2529 [02:49<00:50, 15.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▊   | 1738/2529 [02:49<00:47, 16.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1740/2529 [02:50<00:51, 15.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1742/2529 [02:50<00:51, 15.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1745/2529 [02:50<00:45, 17.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1748/2529 [02:50<00:40, 19.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1751/2529 [02:50<00:39, 19.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1753/2529 [02:50<00:40, 19.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  69%|██████▉   | 1755/2529 [02:50<00:40, 19.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|██████▉   | 1758/2529 [02:50<00:36, 21.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|██████▉   | 1762/2529 [02:51<00:31, 24.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|██████▉   | 1766/2529 [02:51<00:29, 26.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|██████▉   | 1769/2529 [02:51<00:30, 24.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|███████   | 1772/2529 [02:51<00:34, 22.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|███████   | 1775/2529 [02:51<00:36, 20.74it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|███████   | 1778/2529 [02:51<00:39, 18.94it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  70%|███████   | 1782/2529 [02:51<00:33, 22.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1785/2529 [02:52<00:34, 21.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1788/2529 [02:52<00:41, 17.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1790/2529 [02:52<00:42, 17.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1793/2529 [02:52<00:36, 19.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1797/2529 [02:52<00:31, 23.14it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████   | 1800/2529 [02:52<00:32, 22.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████▏  | 1803/2529 [02:53<00:36, 19.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  71%|███████▏  | 1806/2529 [02:53<00:35, 20.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1809/2529 [02:53<00:40, 17.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1812/2529 [02:53<00:35, 20.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1815/2529 [02:53<00:32, 21.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1818/2529 [02:53<00:31, 22.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1821/2529 [02:53<00:31, 22.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1824/2529 [02:53<00:30, 22.80it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1827/2529 [02:54<00:32, 21.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  72%|███████▏  | 1830/2529 [02:54<00:32, 21.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1834/2529 [02:54<00:33, 21.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1837/2529 [02:54<00:37, 18.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1839/2529 [02:54<00:38, 18.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1841/2529 [02:54<00:39, 17.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1843/2529 [02:55<00:40, 17.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1845/2529 [02:55<00:46, 14.57it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1847/2529 [02:55<00:44, 15.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1850/2529 [02:55<00:39, 17.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1852/2529 [02:55<00:39, 16.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1855/2529 [02:55<00:37, 18.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  73%|███████▎  | 1858/2529 [02:55<00:34, 19.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▎  | 1861/2529 [02:56<00:32, 20.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▎  | 1864/2529 [02:56<00:32, 20.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1868/2529 [02:56<00:32, 20.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1871/2529 [02:56<00:32, 20.53it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1874/2529 [02:56<00:42, 15.32it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1876/2529 [02:56<00:43, 15.06it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1878/2529 [02:57<00:47, 13.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1880/2529 [02:57<00:43, 14.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  74%|███████▍  | 1882/2529 [02:57<00:42, 15.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▍  | 1885/2529 [02:57<00:35, 18.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▍  | 1887/2529 [02:57<00:34, 18.59it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▍  | 1889/2529 [02:57<00:33, 18.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▍  | 1892/2529 [02:57<00:32, 19.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▍  | 1895/2529 [02:58<00:35, 18.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▌  | 1897/2529 [02:58<00:35, 17.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▌  | 1900/2529 [02:58<00:33, 18.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▌  | 1904/2529 [02:58<00:28, 22.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  75%|███████▌  | 1907/2529 [02:58<00:26, 23.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1910/2529 [02:58<00:31, 19.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1913/2529 [02:58<00:34, 18.10it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1916/2529 [02:59<00:32, 18.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1920/2529 [02:59<00:29, 20.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1923/2529 [02:59<00:28, 21.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▌  | 1926/2529 [02:59<00:27, 22.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▋  | 1929/2529 [02:59<00:29, 20.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  76%|███████▋  | 1933/2529 [02:59<00:25, 23.33it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1936/2529 [03:00<00:31, 18.91it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1939/2529 [03:00<00:31, 18.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1941/2529 [03:00<00:32, 18.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1944/2529 [03:00<00:31, 18.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1947/2529 [03:00<00:27, 21.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1950/2529 [03:00<00:29, 19.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1953/2529 [03:00<00:29, 19.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1956/2529 [03:01<00:32, 17.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  77%|███████▋  | 1959/2529 [03:01<00:30, 18.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1961/2529 [03:01<00:30, 18.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1963/2529 [03:01<00:32, 17.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1965/2529 [03:01<00:31, 18.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1967/2529 [03:01<00:32, 17.23it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1969/2529 [03:01<00:39, 14.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1971/2529 [03:02<00:50, 10.94it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1973/2529 [03:02<00:58,  9.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1975/2529 [03:02<00:56,  9.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1977/2529 [03:02<00:54, 10.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1979/2529 [03:03<00:53, 10.22it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1981/2529 [03:03<00:52, 10.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1983/2529 [03:03<00:46, 11.73it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  78%|███████▊  | 1985/2529 [03:03<00:40, 13.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▊  | 1987/2529 [03:03<00:38, 13.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▊  | 1989/2529 [03:03<00:38, 13.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 1992/2529 [03:03<00:33, 16.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 1995/2529 [03:04<00:35, 14.88it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 1998/2529 [03:04<00:38, 13.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 2000/2529 [03:04<00:35, 14.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 2002/2529 [03:04<00:34, 15.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 2005/2529 [03:04<00:30, 17.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  79%|███████▉  | 2008/2529 [03:04<00:26, 19.77it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|███████▉  | 2011/2529 [03:04<00:24, 20.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|███████▉  | 2014/2529 [03:05<00:22, 23.07it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|███████▉  | 2017/2529 [03:05<00:28, 17.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|███████▉  | 2020/2529 [03:05<00:33, 15.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|███████▉  | 2022/2529 [03:05<00:33, 15.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|████████  | 2025/2529 [03:05<00:30, 16.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|████████  | 2028/2529 [03:05<00:25, 19.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|████████  | 2031/2529 [03:06<00:27, 18.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  80%|████████  | 2033/2529 [03:06<00:30, 16.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2036/2529 [03:06<00:30, 15.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2039/2529 [03:06<00:30, 15.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2041/2529 [03:06<00:29, 16.29it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2044/2529 [03:06<00:25, 18.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2047/2529 [03:06<00:22, 21.09it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2050/2529 [03:07<00:23, 20.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████  | 2053/2529 [03:07<00:22, 20.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████▏ | 2056/2529 [03:07<00:20, 22.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  81%|████████▏ | 2059/2529 [03:07<00:19, 24.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2062/2529 [03:07<00:21, 21.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2065/2529 [03:07<00:21, 21.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2068/2529 [03:07<00:22, 20.09it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2071/2529 [03:08<00:22, 20.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2074/2529 [03:08<00:24, 18.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2076/2529 [03:08<00:26, 17.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2078/2529 [03:08<00:30, 14.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2081/2529 [03:08<00:25, 17.86it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2083/2529 [03:09<00:32, 13.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  82%|████████▏ | 2085/2529 [03:09<00:30, 14.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2088/2529 [03:09<00:24, 17.66it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2091/2529 [03:09<00:30, 14.42it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2093/2529 [03:09<00:29, 14.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2095/2529 [03:09<00:29, 14.63it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2098/2529 [03:09<00:25, 16.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2101/2529 [03:10<00:24, 17.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2103/2529 [03:10<00:25, 16.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2106/2529 [03:10<00:23, 18.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2108/2529 [03:10<00:23, 18.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  83%|████████▎ | 2110/2529 [03:10<00:23, 17.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▎ | 2114/2529 [03:10<00:19, 21.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▎ | 2117/2529 [03:11<00:26, 15.65it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2119/2529 [03:11<00:27, 14.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2122/2529 [03:11<00:23, 17.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2124/2529 [03:11<00:23, 17.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2126/2529 [03:11<00:22, 17.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2129/2529 [03:11<00:21, 19.04it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2132/2529 [03:11<00:18, 21.29it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  84%|████████▍ | 2135/2529 [03:11<00:18, 21.55it/s]

Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▍ | 2138/2529 [03:12<00:17, 22.71it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▍ | 2141/2529 [03:12<00:18, 21.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▍ | 2144/2529 [03:12<00:18, 20.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▍ | 2147/2529 [03:12<00:17, 21.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▌ | 2151/2529 [03:12<00:15, 24.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▌ | 2154/2529 [03:12<00:14, 25.50it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▌ | 2157/2529 [03:12<00:15, 24.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  85%|████████▌ | 2161/2529 [03:12<00:13, 26.98it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2164/2529 [03:13<00:13, 26.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2167/2529 [03:13<00:14, 24.20it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2171/2529 [03:13<00:14, 24.48it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2174/2529 [03:13<00:15, 23.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2177/2529 [03:13<00:16, 21.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▌ | 2180/2529 [03:13<00:15, 22.61it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▋ | 2184/2529 [03:13<00:13, 24.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  86%|████████▋ | 2187/2529 [03:14<00:14, 23.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2190/2529 [03:14<00:14, 24.05it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2194/2529 [03:14<00:13, 24.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2197/2529 [03:14<00:15, 21.49it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2201/2529 [03:14<00:14, 23.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2204/2529 [03:14<00:13, 23.78it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2207/2529 [03:14<00:14, 21.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  87%|████████▋ | 2210/2529 [03:15<00:14, 21.55it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2214/2529 [03:15<00:12, 24.76it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2217/2529 [03:15<00:12, 25.15it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2221/2529 [03:15<00:11, 27.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2224/2529 [03:15<00:11, 27.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2227/2529 [03:15<00:12, 23.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2230/2529 [03:15<00:13, 21.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2233/2529 [03:16<00:13, 22.75it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  88%|████████▊ | 2236/2529 [03:16<00:16, 17.68it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▊ | 2240/2529 [03:16<00:14, 19.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▊ | 2243/2529 [03:16<00:15, 19.03it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2246/2529 [03:16<00:13, 20.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2249/2529 [03:16<00:15, 18.64it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2252/2529 [03:17<00:13, 20.34it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2256/2529 [03:17<00:11, 23.27it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2260/2529 [03:17<00:11, 22.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  89%|████████▉ | 2263/2529 [03:17<00:11, 22.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|████████▉ | 2266/2529 [03:17<00:11, 23.83it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|████████▉ | 2270/2529 [03:17<00:10, 24.14it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|████████▉ | 2273/2529 [03:17<00:12, 20.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|████████▉ | 2276/2529 [03:18<00:11, 21.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|█████████ | 2279/2529 [03:18<00:12, 20.50it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|█████████ | 2283/2529 [03:18<00:10, 23.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  90%|█████████ | 2286/2529 [03:18<00:10, 24.08it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2289/2529 [03:18<00:10, 23.36it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2292/2529 [03:18<00:10, 22.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2295/2529 [03:18<00:09, 23.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2299/2529 [03:19<00:08, 25.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2302/2529 [03:19<00:09, 23.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████ | 2305/2529 [03:19<00:10, 21.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████▏| 2308/2529 [03:19<00:10, 20.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████▏| 2311/2529 [03:19<00:09, 21.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  91%|█████████▏| 2314/2529 [03:19<00:11, 18.43it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2316/2529 [03:19<00:11, 18.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2320/2529 [03:20<00:09, 21.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2323/2529 [03:20<00:09, 22.80it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2326/2529 [03:20<00:09, 22.38it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2329/2529 [03:20<00:09, 21.96it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2332/2529 [03:20<00:08, 23.18it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2336/2529 [03:20<00:07, 25.70it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  92%|█████████▏| 2339/2529 [03:20<00:08, 23.58it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2342/2529 [03:20<00:07, 23.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2345/2529 [03:21<00:07, 23.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2348/2529 [03:21<00:07, 23.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2351/2529 [03:21<00:08, 20.89it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2354/2529 [03:21<00:08, 19.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2358/2529 [03:21<00:07, 21.72it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  93%|█████████▎| 2361/2529 [03:21<00:07, 23.02it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▎| 2365/2529 [03:21<00:06, 25.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▎| 2368/2529 [03:22<00:06, 23.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2371/2529 [03:22<00:06, 23.62it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2374/2529 [03:22<00:07, 21.54it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2377/2529 [03:22<00:07, 21.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2380/2529 [03:22<00:06, 22.46it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2383/2529 [03:22<00:06, 23.24it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  94%|█████████▍| 2387/2529 [03:22<00:05, 25.92it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▍| 2391/2529 [03:23<00:05, 27.47it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▍| 2394/2529 [03:23<00:05, 24.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▍| 2397/2529 [03:23<00:05, 25.01it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▍| 2400/2529 [03:23<00:04, 25.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▌| 2404/2529 [03:23<00:04, 28.28it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▌| 2407/2529 [03:23<00:05, 21.67it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▌| 2411/2529 [03:23<00:05, 23.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  95%|█████████▌| 2414/2529 [03:24<00:04, 24.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2417/2529 [03:24<00:04, 25.25it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2420/2529 [03:24<00:04, 25.16it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2423/2529 [03:24<00:04, 26.39it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2426/2529 [03:24<00:03, 26.37it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2429/2529 [03:24<00:03, 25.95it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▌| 2432/2529 [03:24<00:04, 22.87it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▋| 2435/2529 [03:24<00:03, 23.69it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  96%|█████████▋| 2438/2529 [03:25<00:04, 21.00it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2442/2529 [03:25<00:03, 24.30it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2445/2529 [03:25<00:03, 24.93it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2448/2529 [03:25<00:03, 24.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2451/2529 [03:25<00:03, 24.82it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2454/2529 [03:25<00:03, 23.99it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2457/2529 [03:25<00:03, 21.81it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2461/2529 [03:26<00:02, 23.19it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  97%|█████████▋| 2464/2529 [03:26<00:02, 24.11it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2467/2529 [03:26<00:02, 21.85it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2471/2529 [03:26<00:02, 24.21it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2474/2529 [03:26<00:02, 25.29it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2477/2529 [03:26<00:02, 24.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2480/2529 [03:26<00:02, 24.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2484/2529 [03:26<00:01, 26.56it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2487/2529 [03:27<00:01, 27.31it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  98%|█████████▊| 2490/2529 [03:27<00:01, 27.97it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▊| 2494/2529 [03:27<00:01, 30.03it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2498/2529 [03:27<00:01, 25.40it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2501/2529 [03:27<00:01, 21.60it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2504/2529 [03:27<00:01, 21.45it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2507/2529 [03:27<00:01, 21.94it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2510/2529 [03:28<00:00, 22.17it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene:  99%|█████████▉| 2514/2529 [03:28<00:00, 22.41it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene: 100%|█████████▉| 2517/2529 [03:28<00:00, 23.79it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene: 100%|█████████▉| 2520/2529 [03:28<00:00, 23.90it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene: 100%|█████████▉| 2524/2529 [03:28<00:00, 26.12it/s]
Processing: positive r2g, Top 10 region-to-gene links per gene: 100%|█████████▉| 2527/2529 [03:28<00:00, 25.27it/s]
 86%|████████▌ | 12/14 [33:50<05:15, 157.79s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 2/2529 [00:00<02:28, 17.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 4/2529 [00:00<02:26, 17.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 7/2529 [00:00<02:17, 18.35it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 9/2529 [00:00<02:18, 18.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   0%|          | 11/2529 [00:00<02:16, 18.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 13/2529 [00:00<02:29, 16.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 15/2529 [00:00<02:28, 16.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 17/2529 [00:00<02:28, 16.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 19/2529 [00:01<02:49, 14.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 21/2529 [00:01<02:57, 14.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 23/2529 [00:01<03:01, 13.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 25/2529 [00:01<02:48, 14.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 27/2529 [00:01<02:37, 15.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 29/2529 [00:01<02:54, 14.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|          | 31/2529 [00:02<03:05, 13.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|▏         | 33/2529 [00:02<03:09, 13.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   1%|▏         | 36/2529 [00:02<02:44, 15.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 38/2529 [00:02<02:54, 14.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 40/2529 [00:02<03:00, 13.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 42/2529 [00:02<02:48, 14.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 44/2529 [00:02<02:37, 15.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 46/2529 [00:02<02:31, 16.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 48/2529 [00:03<03:01, 13.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 50/2529 [00:03<02:57, 13.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 52/2529 [00:03<02:51, 14.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 54/2529 [00:03<02:45, 14.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 57/2529 [00:03<02:26, 16.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 60/2529 [00:03<02:09, 19.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   2%|▏         | 63/2529 [00:03<02:04, 19.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 66/2529 [00:04<02:03, 19.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 69/2529 [00:04<02:02, 20.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 72/2529 [00:04<02:29, 16.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 74/2529 [00:04<02:39, 15.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 76/2529 [00:04<02:53, 14.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 78/2529 [00:04<02:45, 14.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 81/2529 [00:05<02:27, 16.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 83/2529 [00:05<02:24, 16.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 85/2529 [00:05<02:32, 16.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   3%|▎         | 87/2529 [00:05<02:37, 15.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▎         | 89/2529 [00:05<02:43, 14.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▎         | 91/2529 [00:05<02:35, 15.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▎         | 94/2529 [00:05<02:18, 17.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 96/2529 [00:06<02:24, 16.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 98/2529 [00:06<02:24, 16.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 100/2529 [00:06<02:54, 13.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 102/2529 [00:06<02:49, 14.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 104/2529 [00:06<02:42, 14.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 107/2529 [00:06<02:17, 17.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 109/2529 [00:06<02:26, 16.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 111/2529 [00:06<02:19, 17.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   4%|▍         | 113/2529 [00:07<02:21, 17.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 115/2529 [00:07<03:05, 13.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 117/2529 [00:07<03:39, 11.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 119/2529 [00:07<03:47, 10.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 121/2529 [00:08<03:58, 10.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 123/2529 [00:08<03:45, 10.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▍         | 125/2529 [00:08<03:39, 10.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 127/2529 [00:08<03:51, 10.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 129/2529 [00:08<03:58, 10.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 131/2529 [00:09<04:05,  9.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 133/2529 [00:09<04:26,  8.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 134/2529 [00:09<04:28,  8.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 135/2529 [00:09<04:28,  8.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 136/2529 [00:09<04:34,  8.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 137/2529 [00:09<04:48,  8.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 138/2529 [00:09<04:46,  8.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   5%|▌         | 139/2529 [00:09<04:45,  8.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 141/2529 [00:10<03:54, 10.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 143/2529 [00:10<03:36, 11.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 145/2529 [00:10<03:53, 10.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 147/2529 [00:10<03:42, 10.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 149/2529 [00:10<03:41, 10.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 152/2529 [00:11<02:56, 13.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 154/2529 [00:11<02:48, 14.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 156/2529 [00:11<03:39, 10.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▌         | 158/2529 [00:11<03:58,  9.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▋         | 160/2529 [00:11<04:10,  9.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▋         | 162/2529 [00:12<04:19,  9.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   6%|▋         | 163/2529 [00:12<04:22,  9.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 165/2529 [00:12<03:51, 10.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 167/2529 [00:12<03:33, 11.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 169/2529 [00:12<03:43, 10.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 171/2529 [00:12<03:37, 10.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 173/2529 [00:13<03:49, 10.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 175/2529 [00:13<03:53, 10.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 177/2529 [00:13<03:39, 10.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 179/2529 [00:13<03:16, 11.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 181/2529 [00:13<03:11, 12.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 183/2529 [00:13<02:52, 13.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 185/2529 [00:14<02:45, 14.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 187/2529 [00:14<02:36, 14.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   7%|▋         | 189/2529 [00:14<02:33, 15.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 191/2529 [00:14<02:49, 13.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 193/2529 [00:14<02:47, 13.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 195/2529 [00:14<02:36, 14.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 197/2529 [00:14<02:32, 15.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 199/2529 [00:14<02:29, 15.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 201/2529 [00:15<02:19, 16.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 203/2529 [00:15<02:34, 15.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 205/2529 [00:15<02:49, 13.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 207/2529 [00:15<02:42, 14.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 209/2529 [00:15<02:32, 15.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 211/2529 [00:15<02:24, 16.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   8%|▊         | 213/2529 [00:15<02:42, 14.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▊         | 215/2529 [00:16<02:47, 13.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▊         | 217/2529 [00:16<02:39, 14.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▊         | 220/2529 [00:16<02:18, 16.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 222/2529 [00:16<02:15, 17.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 224/2529 [00:16<02:16, 16.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 226/2529 [00:16<02:32, 15.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 229/2529 [00:16<02:17, 16.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 231/2529 [00:16<02:11, 17.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 233/2529 [00:17<02:12, 17.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 236/2529 [00:17<02:02, 18.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:   9%|▉         | 239/2529 [00:17<02:01, 18.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 241/2529 [00:17<02:14, 17.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 243/2529 [00:17<02:16, 16.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 246/2529 [00:17<02:15, 16.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 248/2529 [00:17<02:26, 15.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 250/2529 [00:18<02:32, 14.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|▉         | 252/2529 [00:18<02:23, 15.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|█         | 255/2529 [00:18<02:09, 17.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|█         | 257/2529 [00:18<02:10, 17.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|█         | 259/2529 [00:18<02:10, 17.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|█         | 262/2529 [00:18<02:30, 15.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  10%|█         | 264/2529 [00:18<02:26, 15.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 266/2529 [00:19<02:26, 15.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 269/2529 [00:19<02:07, 17.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 272/2529 [00:19<02:13, 16.84it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 274/2529 [00:19<02:15, 16.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 276/2529 [00:19<02:13, 16.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 279/2529 [00:19<02:00, 18.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 281/2529 [00:19<02:04, 17.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█         | 283/2529 [00:20<02:11, 17.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 285/2529 [00:20<02:08, 17.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 288/2529 [00:20<02:03, 18.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  11%|█▏        | 290/2529 [00:20<02:17, 16.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 292/2529 [00:20<02:15, 16.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 294/2529 [00:20<02:15, 16.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 296/2529 [00:20<02:15, 16.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 298/2529 [00:21<02:35, 14.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 300/2529 [00:21<02:29, 14.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 302/2529 [00:21<02:22, 15.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 304/2529 [00:21<02:18, 16.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 306/2529 [00:21<02:10, 16.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 309/2529 [00:21<01:58, 18.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 311/2529 [00:21<01:58, 18.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 314/2529 [00:21<01:51, 19.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  12%|█▏        | 316/2529 [00:21<01:52, 19.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 319/2529 [00:22<01:50, 20.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 321/2529 [00:22<01:55, 19.11it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 323/2529 [00:22<02:03, 17.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 325/2529 [00:22<02:05, 17.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 327/2529 [00:22<02:09, 17.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 330/2529 [00:22<01:59, 18.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 332/2529 [00:22<02:36, 14.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 334/2529 [00:23<02:42, 13.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 336/2529 [00:23<02:34, 14.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 338/2529 [00:23<02:25, 15.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  13%|█▎        | 340/2529 [00:23<02:27, 14.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 342/2529 [00:23<02:28, 14.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 344/2529 [00:23<02:49, 12.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▎        | 346/2529 [00:23<02:40, 13.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 348/2529 [00:24<02:41, 13.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 351/2529 [00:24<02:13, 16.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 353/2529 [00:24<02:19, 15.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 355/2529 [00:24<02:44, 13.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 357/2529 [00:24<03:02, 11.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 359/2529 [00:25<03:21, 10.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 361/2529 [00:25<03:45,  9.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 363/2529 [00:25<03:59,  9.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 364/2529 [00:25<03:59,  9.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 365/2529 [00:25<04:15,  8.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  14%|█▍        | 366/2529 [00:25<04:33,  7.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 367/2529 [00:26<04:47,  7.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 368/2529 [00:26<04:42,  7.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 369/2529 [00:26<04:28,  8.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 370/2529 [00:26<04:34,  7.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 371/2529 [00:26<04:46,  7.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 372/2529 [00:26<04:39,  7.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 373/2529 [00:26<04:28,  8.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 374/2529 [00:27<04:34,  7.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 375/2529 [00:27<04:35,  7.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 377/2529 [00:27<03:21, 10.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▍        | 379/2529 [00:27<02:47, 12.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 381/2529 [00:27<02:29, 14.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 383/2529 [00:27<02:40, 13.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 385/2529 [00:27<02:31, 14.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 387/2529 [00:27<02:24, 14.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 389/2529 [00:28<02:22, 15.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  15%|█▌        | 391/2529 [00:28<02:17, 15.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 393/2529 [00:28<02:20, 15.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 395/2529 [00:28<02:46, 12.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 397/2529 [00:28<03:25, 10.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 399/2529 [00:28<03:30, 10.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 401/2529 [00:29<03:14, 10.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 403/2529 [00:29<03:44,  9.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 405/2529 [00:29<03:23, 10.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 408/2529 [00:29<02:44, 12.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▌        | 410/2529 [00:29<02:48, 12.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 412/2529 [00:30<03:01, 11.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 414/2529 [00:30<02:47, 12.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  16%|█▋        | 416/2529 [00:30<02:29, 14.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 418/2529 [00:30<02:25, 14.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 420/2529 [00:30<02:30, 14.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 422/2529 [00:30<02:26, 14.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 424/2529 [00:30<02:18, 15.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 427/2529 [00:30<02:04, 16.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 429/2529 [00:31<02:25, 14.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 431/2529 [00:31<02:29, 14.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 433/2529 [00:31<02:51, 12.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 435/2529 [00:31<02:35, 13.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 437/2529 [00:31<02:29, 14.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 439/2529 [00:31<02:41, 12.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  17%|█▋        | 441/2529 [00:32<02:24, 14.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 443/2529 [00:32<02:18, 15.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 445/2529 [00:32<02:22, 14.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 447/2529 [00:32<03:01, 11.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 449/2529 [00:32<02:59, 11.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 451/2529 [00:32<03:01, 11.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 453/2529 [00:33<03:30,  9.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 456/2529 [00:33<03:12, 10.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 458/2529 [00:33<03:08, 10.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 460/2529 [00:33<03:14, 10.62it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 462/2529 [00:33<02:49, 12.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 464/2529 [00:34<02:47, 12.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  18%|█▊        | 466/2529 [00:34<02:42, 12.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 468/2529 [00:34<02:54, 11.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 470/2529 [00:34<03:11, 10.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 472/2529 [00:34<03:30,  9.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▊        | 474/2529 [00:35<03:10, 10.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 476/2529 [00:35<02:47, 12.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 478/2529 [00:35<02:48, 12.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 480/2529 [00:35<02:37, 13.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 482/2529 [00:35<02:54, 11.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 484/2529 [00:35<02:34, 13.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 486/2529 [00:35<02:19, 14.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 489/2529 [00:35<01:58, 17.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 491/2529 [00:36<01:54, 17.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  19%|█▉        | 493/2529 [00:36<01:59, 17.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 495/2529 [00:36<01:57, 17.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 497/2529 [00:36<01:52, 18.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 500/2529 [00:36<01:45, 19.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 503/2529 [00:36<01:48, 18.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|█▉        | 505/2529 [00:36<01:49, 18.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|██        | 507/2529 [00:37<02:03, 16.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|██        | 509/2529 [00:37<02:00, 16.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|██        | 511/2529 [00:37<02:12, 15.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|██        | 513/2529 [00:37<02:28, 13.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  20%|██        | 516/2529 [00:37<02:06, 15.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 519/2529 [00:37<01:51, 18.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 521/2529 [00:37<01:59, 16.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 523/2529 [00:37<02:01, 16.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 525/2529 [00:38<02:31, 13.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 528/2529 [00:38<02:09, 15.47it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 531/2529 [00:38<01:56, 17.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 534/2529 [00:38<01:44, 19.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██        | 537/2529 [00:38<01:53, 17.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 539/2529 [00:39<02:13, 14.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 541/2529 [00:39<02:11, 15.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  21%|██▏       | 543/2529 [00:39<02:26, 13.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 545/2529 [00:39<02:25, 13.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 548/2529 [00:39<02:02, 16.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 551/2529 [00:39<01:55, 17.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 554/2529 [00:39<01:55, 17.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 556/2529 [00:40<01:52, 17.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 558/2529 [00:40<01:54, 17.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 560/2529 [00:40<02:00, 16.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 562/2529 [00:40<02:01, 16.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 565/2529 [00:40<01:47, 18.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 567/2529 [00:40<02:04, 15.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  22%|██▏       | 569/2529 [00:40<02:00, 16.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 571/2529 [00:40<02:04, 15.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 573/2529 [00:41<02:05, 15.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 575/2529 [00:41<02:22, 13.67it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 577/2529 [00:41<02:31, 12.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 579/2529 [00:41<02:36, 12.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 581/2529 [00:41<02:22, 13.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 583/2529 [00:41<02:15, 14.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 585/2529 [00:42<02:15, 14.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 588/2529 [00:42<02:02, 15.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 590/2529 [00:42<01:57, 16.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 592/2529 [00:42<02:08, 15.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  23%|██▎       | 594/2529 [00:42<01:59, 16.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▎       | 597/2529 [00:42<01:48, 17.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▎       | 599/2529 [00:42<02:07, 15.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 601/2529 [00:43<02:06, 15.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 603/2529 [00:43<02:20, 13.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 605/2529 [00:43<02:54, 11.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 607/2529 [00:43<03:06, 10.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 609/2529 [00:43<03:06, 10.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 611/2529 [00:44<02:41, 11.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 613/2529 [00:44<02:36, 12.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 615/2529 [00:44<02:29, 12.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  24%|██▍       | 617/2529 [00:44<02:22, 13.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 620/2529 [00:44<02:07, 14.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 622/2529 [00:44<02:10, 14.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 624/2529 [00:44<02:16, 13.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 626/2529 [00:45<02:12, 14.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 628/2529 [00:45<02:04, 15.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▍       | 631/2529 [00:45<01:49, 17.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 633/2529 [00:45<01:46, 17.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 635/2529 [00:45<01:43, 18.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 637/2529 [00:45<02:13, 14.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 639/2529 [00:45<02:31, 12.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 642/2529 [00:46<02:13, 14.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  25%|██▌       | 644/2529 [00:46<02:03, 15.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 647/2529 [00:46<01:55, 16.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 649/2529 [00:46<01:49, 17.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 651/2529 [00:46<02:02, 15.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 653/2529 [00:46<01:56, 16.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 656/2529 [00:46<01:57, 15.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 658/2529 [00:47<02:11, 14.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 660/2529 [00:47<02:21, 13.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▌       | 663/2529 [00:47<02:04, 15.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 665/2529 [00:47<02:00, 15.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 667/2529 [00:47<01:57, 15.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  26%|██▋       | 670/2529 [00:47<01:44, 17.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 672/2529 [00:47<01:53, 16.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 674/2529 [00:48<01:52, 16.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 676/2529 [00:48<01:53, 16.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 678/2529 [00:48<02:02, 15.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 680/2529 [00:48<02:07, 14.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 682/2529 [00:48<02:03, 14.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 684/2529 [00:48<02:06, 14.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 686/2529 [00:48<02:06, 14.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 688/2529 [00:49<02:04, 14.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 690/2529 [00:49<02:44, 11.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 692/2529 [00:49<03:28,  8.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  27%|██▋       | 694/2529 [00:49<03:51,  7.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 696/2529 [00:50<03:37,  8.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 697/2529 [00:50<03:32,  8.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 698/2529 [00:50<03:29,  8.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 700/2529 [00:50<03:24,  8.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 701/2529 [00:50<03:27,  8.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 702/2529 [00:50<03:24,  8.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 704/2529 [00:50<02:58, 10.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 706/2529 [00:51<02:38, 11.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 708/2529 [00:51<02:26, 12.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 710/2529 [00:51<02:33, 11.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 712/2529 [00:51<02:26, 12.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 714/2529 [00:51<02:50, 10.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 716/2529 [00:52<03:03,  9.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 718/2529 [00:52<02:46, 10.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  28%|██▊       | 720/2529 [00:52<02:37, 11.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 722/2529 [00:52<02:18, 13.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 724/2529 [00:52<02:13, 13.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▊       | 727/2529 [00:52<01:51, 16.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 729/2529 [00:52<01:51, 16.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 732/2529 [00:52<01:40, 17.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 734/2529 [00:53<02:11, 13.62it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 736/2529 [00:53<02:13, 13.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 738/2529 [00:53<02:45, 10.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 740/2529 [00:53<02:26, 12.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 742/2529 [00:53<02:14, 13.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 744/2529 [00:53<02:01, 14.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  29%|██▉       | 746/2529 [00:54<02:07, 14.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 748/2529 [00:54<02:14, 13.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 750/2529 [00:54<02:23, 12.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 752/2529 [00:54<02:31, 11.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 754/2529 [00:54<02:20, 12.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 756/2529 [00:55<02:30, 11.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|██▉       | 758/2529 [00:55<02:20, 12.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|███       | 761/2529 [00:55<01:54, 15.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|███       | 763/2529 [00:55<01:49, 16.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|███       | 765/2529 [00:55<01:43, 16.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|███       | 767/2529 [00:55<02:06, 13.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  30%|███       | 770/2529 [00:55<01:47, 16.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 772/2529 [00:55<01:42, 17.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 775/2529 [00:56<01:36, 18.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 777/2529 [00:56<01:35, 18.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 779/2529 [00:56<01:44, 16.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 781/2529 [00:56<01:46, 16.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 783/2529 [00:56<01:54, 15.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 785/2529 [00:56<01:54, 15.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 787/2529 [00:56<02:10, 13.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███       | 789/2529 [00:57<02:10, 13.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 791/2529 [00:57<02:43, 10.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 793/2529 [00:57<02:21, 12.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  31%|███▏      | 795/2529 [00:57<02:05, 13.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 797/2529 [00:57<02:45, 10.46it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 799/2529 [00:58<02:31, 11.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 801/2529 [00:58<02:13, 12.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 803/2529 [00:58<02:06, 13.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 805/2529 [00:58<02:38, 10.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 807/2529 [00:58<02:54,  9.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 809/2529 [00:58<02:40, 10.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 811/2529 [00:59<02:21, 12.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 813/2529 [00:59<02:12, 12.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 815/2529 [00:59<02:16, 12.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 817/2529 [00:59<02:04, 13.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 819/2529 [00:59<02:07, 13.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  32%|███▏      | 821/2529 [00:59<02:02, 13.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 824/2529 [00:59<01:45, 16.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 826/2529 [01:00<01:55, 14.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 828/2529 [01:00<02:36, 10.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 830/2529 [01:00<02:21, 12.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 833/2529 [01:00<01:58, 14.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 835/2529 [01:00<02:01, 13.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 837/2529 [01:00<02:01, 13.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 840/2529 [01:01<01:52, 14.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 843/2529 [01:01<01:45, 16.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 845/2529 [01:01<01:44, 16.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  33%|███▎      | 847/2529 [01:01<01:42, 16.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▎      | 849/2529 [01:01<01:43, 16.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▎      | 851/2529 [01:01<01:47, 15.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 854/2529 [01:01<01:37, 17.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 857/2529 [01:02<01:30, 18.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 860/2529 [01:02<01:27, 19.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 863/2529 [01:02<01:30, 18.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 866/2529 [01:02<01:24, 19.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 868/2529 [01:02<01:24, 19.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 870/2529 [01:02<01:24, 19.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  34%|███▍      | 872/2529 [01:02<01:25, 19.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 874/2529 [01:02<01:32, 17.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 877/2529 [01:03<01:26, 19.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 879/2529 [01:03<01:39, 16.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 881/2529 [01:03<01:35, 17.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▍      | 883/2529 [01:03<01:52, 14.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 886/2529 [01:03<01:39, 16.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 888/2529 [01:03<01:36, 17.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 891/2529 [01:03<01:25, 19.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 893/2529 [01:04<01:33, 17.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  35%|███▌      | 895/2529 [01:04<01:31, 17.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 898/2529 [01:04<01:26, 18.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 900/2529 [01:04<01:36, 16.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 902/2529 [01:04<01:56, 13.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 904/2529 [01:04<01:50, 14.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 907/2529 [01:04<01:36, 16.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 909/2529 [01:05<01:40, 16.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 912/2529 [01:05<01:41, 15.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▌      | 915/2529 [01:05<01:35, 16.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 918/2529 [01:05<01:38, 16.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 920/2529 [01:05<01:36, 16.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  36%|███▋      | 923/2529 [01:05<01:26, 18.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 926/2529 [01:05<01:20, 19.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 929/2529 [01:06<01:15, 21.11it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 932/2529 [01:06<01:19, 20.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 935/2529 [01:06<01:37, 16.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 937/2529 [01:06<01:41, 15.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 939/2529 [01:06<01:45, 15.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 941/2529 [01:07<01:57, 13.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 943/2529 [01:07<02:05, 12.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 946/2529 [01:07<01:45, 15.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  37%|███▋      | 948/2529 [01:07<01:41, 15.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 950/2529 [01:07<01:36, 16.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 953/2529 [01:07<01:41, 15.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 955/2529 [01:07<01:46, 14.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 957/2529 [01:08<01:40, 15.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 959/2529 [01:08<01:34, 16.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 962/2529 [01:08<01:25, 18.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 965/2529 [01:08<01:17, 20.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 968/2529 [01:08<01:34, 16.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 970/2529 [01:08<01:30, 17.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  38%|███▊      | 973/2529 [01:08<01:26, 18.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▊      | 976/2529 [01:09<01:24, 18.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▊      | 978/2529 [01:09<01:40, 15.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 980/2529 [01:09<01:36, 16.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 983/2529 [01:09<01:38, 15.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 986/2529 [01:09<01:34, 16.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 988/2529 [01:09<01:33, 16.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 991/2529 [01:09<01:25, 17.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 993/2529 [01:10<01:30, 17.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 995/2529 [01:10<01:26, 17.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  39%|███▉      | 998/2529 [01:10<01:25, 17.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1001/2529 [01:10<01:19, 19.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1003/2529 [01:10<01:20, 18.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1005/2529 [01:10<01:29, 17.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1008/2529 [01:10<01:36, 15.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|███▉      | 1010/2529 [01:11<01:38, 15.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1012/2529 [01:11<01:33, 16.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1014/2529 [01:11<01:37, 15.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1016/2529 [01:11<01:58, 12.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1018/2529 [01:11<01:46, 14.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1021/2529 [01:11<01:31, 16.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  40%|████      | 1023/2529 [01:11<01:30, 16.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1026/2529 [01:12<01:32, 16.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1028/2529 [01:12<01:35, 15.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1031/2529 [01:12<01:24, 17.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1033/2529 [01:12<01:23, 17.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1036/2529 [01:12<01:17, 19.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1038/2529 [01:12<01:26, 17.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████      | 1041/2529 [01:12<01:25, 17.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1044/2529 [01:13<01:24, 17.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1046/2529 [01:13<01:26, 17.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  41%|████▏     | 1048/2529 [01:13<01:23, 17.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1050/2529 [01:13<01:35, 15.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1052/2529 [01:13<01:41, 14.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1054/2529 [01:13<01:36, 15.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1057/2529 [01:13<01:29, 16.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1059/2529 [01:14<01:27, 16.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1062/2529 [01:14<01:17, 18.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1065/2529 [01:14<01:23, 17.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1067/2529 [01:14<01:23, 17.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1069/2529 [01:14<01:24, 17.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1072/2529 [01:14<01:17, 18.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  42%|████▏     | 1074/2529 [01:14<01:28, 16.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1076/2529 [01:15<01:28, 16.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1078/2529 [01:15<01:26, 16.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1080/2529 [01:15<01:30, 16.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1083/2529 [01:15<01:18, 18.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1086/2529 [01:15<01:13, 19.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1089/2529 [01:15<01:22, 17.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1092/2529 [01:15<01:15, 18.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1094/2529 [01:16<01:18, 18.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1096/2529 [01:16<01:17, 18.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  43%|████▎     | 1099/2529 [01:16<01:10, 20.32it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▎     | 1102/2529 [01:16<01:17, 18.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▎     | 1104/2529 [01:16<01:27, 16.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1107/2529 [01:16<01:24, 16.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1110/2529 [01:16<01:17, 18.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1112/2529 [01:17<01:17, 18.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1114/2529 [01:17<01:16, 18.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1116/2529 [01:17<01:18, 18.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1119/2529 [01:17<01:12, 19.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1121/2529 [01:17<01:14, 18.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  44%|████▍     | 1124/2529 [01:17<01:11, 19.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1126/2529 [01:17<01:15, 18.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1128/2529 [01:17<01:20, 17.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1130/2529 [01:18<01:33, 14.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1133/2529 [01:18<01:23, 16.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1135/2529 [01:18<01:28, 15.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▍     | 1138/2529 [01:18<01:17, 17.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1141/2529 [01:18<01:14, 18.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1143/2529 [01:18<01:16, 18.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1145/2529 [01:18<01:14, 18.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1147/2529 [01:18<01:15, 18.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  45%|████▌     | 1150/2529 [01:19<01:18, 17.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1152/2529 [01:19<01:23, 16.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1155/2529 [01:19<01:17, 17.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1157/2529 [01:19<01:15, 18.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1159/2529 [01:19<01:21, 16.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1162/2529 [01:19<01:13, 18.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1164/2529 [01:19<01:20, 17.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▌     | 1167/2529 [01:20<01:15, 18.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1170/2529 [01:20<01:11, 18.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1172/2529 [01:20<01:16, 17.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  46%|████▋     | 1175/2529 [01:20<01:15, 17.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1178/2529 [01:20<01:09, 19.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1181/2529 [01:20<01:06, 20.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1184/2529 [01:20<01:07, 19.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1187/2529 [01:21<01:03, 21.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1190/2529 [01:21<01:12, 18.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1192/2529 [01:21<01:12, 18.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1194/2529 [01:21<01:20, 16.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1196/2529 [01:21<01:25, 15.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1198/2529 [01:21<01:28, 15.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  47%|████▋     | 1200/2529 [01:21<01:26, 15.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1202/2529 [01:22<01:26, 15.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1205/2529 [01:22<01:16, 17.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1207/2529 [01:22<01:20, 16.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1209/2529 [01:22<01:17, 17.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1211/2529 [01:22<01:18, 16.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1213/2529 [01:22<01:18, 16.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1216/2529 [01:22<01:15, 17.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1219/2529 [01:23<01:17, 16.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1222/2529 [01:23<01:15, 17.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1224/2529 [01:23<01:15, 17.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  48%|████▊     | 1226/2529 [01:23<01:14, 17.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1228/2529 [01:23<01:18, 16.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1230/2529 [01:23<01:15, 17.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▊     | 1232/2529 [01:23<01:24, 15.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1235/2529 [01:24<01:15, 17.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1237/2529 [01:24<01:15, 17.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1239/2529 [01:24<01:15, 17.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1241/2529 [01:24<01:26, 14.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1243/2529 [01:24<01:43, 12.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1245/2529 [01:24<01:53, 11.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1247/2529 [01:25<01:48, 11.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1249/2529 [01:25<01:45, 12.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  49%|████▉     | 1251/2529 [01:25<01:35, 13.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1253/2529 [01:25<01:26, 14.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1255/2529 [01:25<01:37, 13.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1257/2529 [01:25<01:47, 11.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1259/2529 [01:25<01:46, 11.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1261/2529 [01:26<01:35, 13.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|████▉     | 1263/2529 [01:26<01:27, 14.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1265/2529 [01:26<01:33, 13.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1267/2529 [01:26<01:34, 13.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1269/2529 [01:26<01:27, 14.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1271/2529 [01:26<01:22, 15.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1273/2529 [01:26<01:18, 15.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1275/2529 [01:27<01:41, 12.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  50%|█████     | 1277/2529 [01:27<01:44, 12.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1279/2529 [01:27<01:38, 12.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1281/2529 [01:27<01:31, 13.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1283/2529 [01:27<01:24, 14.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1286/2529 [01:27<01:15, 16.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1289/2529 [01:27<01:05, 18.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1291/2529 [01:28<01:05, 18.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1293/2529 [01:28<01:05, 18.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████     | 1296/2529 [01:28<01:03, 19.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████▏    | 1298/2529 [01:28<01:02, 19.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████▏    | 1300/2529 [01:28<01:12, 16.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  51%|█████▏    | 1302/2529 [01:28<01:19, 15.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1304/2529 [01:28<01:24, 14.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1306/2529 [01:29<01:32, 13.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1308/2529 [01:29<01:27, 13.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1310/2529 [01:29<01:20, 15.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1313/2529 [01:29<01:11, 16.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1315/2529 [01:29<01:09, 17.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1318/2529 [01:29<01:13, 16.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1320/2529 [01:29<01:16, 15.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1322/2529 [01:30<01:20, 15.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1324/2529 [01:30<01:16, 15.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  52%|█████▏    | 1326/2529 [01:30<01:18, 15.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1328/2529 [01:30<01:15, 15.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1330/2529 [01:30<01:13, 16.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1332/2529 [01:30<01:22, 14.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1334/2529 [01:30<01:31, 13.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1336/2529 [01:31<01:29, 13.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1339/2529 [01:31<01:14, 15.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1342/2529 [01:31<01:13, 16.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1344/2529 [01:31<01:10, 16.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1346/2529 [01:31<01:11, 16.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1348/2529 [01:31<01:33, 12.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1350/2529 [01:32<01:53, 10.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  53%|█████▎    | 1352/2529 [01:32<01:58,  9.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1354/2529 [01:32<02:02,  9.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1356/2529 [01:32<01:54, 10.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▎    | 1358/2529 [01:32<01:50, 10.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1360/2529 [01:32<01:36, 12.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1362/2529 [01:33<02:01,  9.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1364/2529 [01:33<02:00,  9.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1366/2529 [01:33<02:09,  9.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1367/2529 [01:33<02:13,  8.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1368/2529 [01:34<02:16,  8.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1369/2529 [01:34<02:15,  8.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1370/2529 [01:34<02:20,  8.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1371/2529 [01:34<02:25,  7.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1372/2529 [01:34<02:23,  8.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1373/2529 [01:34<02:21,  8.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1375/2529 [01:34<01:55,  9.99it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  54%|█████▍    | 1377/2529 [01:34<01:46, 10.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1379/2529 [01:35<01:54, 10.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1381/2529 [01:35<01:49, 10.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1383/2529 [01:35<01:48, 10.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1386/2529 [01:35<01:26, 13.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1388/2529 [01:35<01:22, 13.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▍    | 1390/2529 [01:36<01:49, 10.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1392/2529 [01:36<01:57,  9.67it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1394/2529 [01:36<02:02,  9.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1396/2529 [01:36<02:07,  8.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1397/2529 [01:36<02:08,  8.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1399/2529 [01:37<01:53, 10.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1401/2529 [01:37<01:43, 10.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  55%|█████▌    | 1403/2529 [01:37<01:39, 11.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1405/2529 [01:37<01:33, 12.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1407/2529 [01:37<01:48, 10.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1409/2529 [01:38<01:51, 10.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1411/2529 [01:38<01:50, 10.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1413/2529 [01:38<01:41, 11.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1415/2529 [01:38<01:35, 11.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1417/2529 [01:38<01:25, 12.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1419/2529 [01:38<01:22, 13.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▌    | 1421/2529 [01:38<01:17, 14.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1423/2529 [01:39<01:16, 14.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1425/2529 [01:39<01:22, 13.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  56%|█████▋    | 1427/2529 [01:39<01:21, 13.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1429/2529 [01:39<01:18, 14.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1431/2529 [01:39<01:16, 14.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1433/2529 [01:39<01:11, 15.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1435/2529 [01:39<01:11, 15.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1437/2529 [01:39<01:07, 16.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1439/2529 [01:40<01:22, 13.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1441/2529 [01:40<01:27, 12.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1443/2529 [01:40<01:21, 13.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1445/2529 [01:40<01:15, 14.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1447/2529 [01:40<01:10, 15.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1449/2529 [01:40<01:09, 15.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1451/2529 [01:41<01:27, 12.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  57%|█████▋    | 1453/2529 [01:41<01:25, 12.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1456/2529 [01:41<01:11, 15.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1458/2529 [01:41<01:08, 15.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1460/2529 [01:41<01:07, 15.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1462/2529 [01:41<01:16, 13.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1464/2529 [01:41<01:10, 15.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1467/2529 [01:42<01:02, 16.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1469/2529 [01:42<01:01, 17.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1471/2529 [01:42<01:02, 16.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1473/2529 [01:42<00:59, 17.62it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1476/2529 [01:42<00:55, 18.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  58%|█████▊    | 1478/2529 [01:42<00:57, 18.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1480/2529 [01:42<01:03, 16.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1482/2529 [01:42<01:04, 16.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▊    | 1485/2529 [01:43<01:03, 16.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1487/2529 [01:43<01:07, 15.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1489/2529 [01:43<01:10, 14.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1491/2529 [01:43<01:07, 15.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1494/2529 [01:43<01:00, 17.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1497/2529 [01:43<00:55, 18.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1499/2529 [01:43<00:57, 17.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1501/2529 [01:43<00:58, 17.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  59%|█████▉    | 1504/2529 [01:44<00:54, 18.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1506/2529 [01:44<01:10, 14.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1508/2529 [01:44<01:10, 14.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1511/2529 [01:44<01:01, 16.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1513/2529 [01:44<01:01, 16.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1515/2529 [01:44<01:06, 15.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|█████▉    | 1517/2529 [01:45<01:05, 15.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1519/2529 [01:45<01:03, 15.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1522/2529 [01:45<00:56, 17.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1524/2529 [01:45<00:59, 16.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1526/2529 [01:45<01:02, 15.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  60%|██████    | 1529/2529 [01:45<00:56, 17.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1531/2529 [01:45<00:58, 17.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1533/2529 [01:46<01:05, 15.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1535/2529 [01:46<01:03, 15.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1537/2529 [01:46<01:02, 15.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1539/2529 [01:46<01:02, 15.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1541/2529 [01:46<01:09, 14.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1543/2529 [01:46<01:06, 14.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1545/2529 [01:46<01:03, 15.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1547/2529 [01:46<01:01, 15.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████    | 1549/2529 [01:47<00:57, 16.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████▏   | 1552/2529 [01:47<00:51, 18.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  61%|██████▏   | 1554/2529 [01:47<00:51, 18.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1556/2529 [01:47<00:51, 18.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1559/2529 [01:47<00:49, 19.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1561/2529 [01:47<00:50, 19.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1563/2529 [01:47<00:52, 18.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1565/2529 [01:47<00:56, 17.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1568/2529 [01:48<00:55, 17.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1570/2529 [01:48<00:58, 16.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1573/2529 [01:48<00:53, 17.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1576/2529 [01:48<00:49, 19.11it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1578/2529 [01:48<00:49, 19.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  62%|██████▏   | 1580/2529 [01:48<00:59, 15.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1582/2529 [01:48<01:13, 12.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1584/2529 [01:49<01:09, 13.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1586/2529 [01:49<01:06, 14.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1588/2529 [01:49<01:02, 15.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1590/2529 [01:49<01:05, 14.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1592/2529 [01:49<01:16, 12.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1594/2529 [01:49<01:12, 12.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1596/2529 [01:50<01:14, 12.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1598/2529 [01:50<01:06, 13.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1601/2529 [01:50<01:01, 15.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1603/2529 [01:50<01:06, 13.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  63%|██████▎   | 1605/2529 [01:50<01:15, 12.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1607/2529 [01:50<01:18, 11.67it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1609/2529 [01:51<01:30, 10.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1611/2529 [01:51<01:39,  9.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▎   | 1612/2529 [01:51<01:40,  9.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1613/2529 [01:51<01:46,  8.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1614/2529 [01:51<01:54,  8.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1615/2529 [01:51<02:01,  7.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1617/2529 [01:52<01:55,  7.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1618/2529 [01:52<01:55,  7.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1619/2529 [01:52<01:55,  7.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1620/2529 [01:52<01:58,  7.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1621/2529 [01:52<02:02,  7.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1622/2529 [01:52<02:00,  7.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1623/2529 [01:52<01:56,  7.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1624/2529 [01:53<01:58,  7.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1625/2529 [01:53<01:57,  7.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1627/2529 [01:53<01:25, 10.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1629/2529 [01:53<01:13, 12.19it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  64%|██████▍   | 1631/2529 [01:53<01:06, 13.41it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1633/2529 [01:53<01:04, 13.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1635/2529 [01:53<01:08, 12.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1637/2529 [01:54<01:07, 13.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1639/2529 [01:54<01:03, 13.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1641/2529 [01:54<01:01, 14.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▍   | 1643/2529 [01:54<01:00, 14.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1645/2529 [01:54<00:59, 14.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1647/2529 [01:54<01:09, 12.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1649/2529 [01:55<01:25, 10.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1651/2529 [01:55<01:26, 10.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1653/2529 [01:55<01:20, 10.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  65%|██████▌   | 1655/2529 [01:55<01:32,  9.45it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1657/2529 [01:55<01:23, 10.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1660/2529 [01:55<01:06, 12.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1662/2529 [01:56<01:08, 12.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1664/2529 [01:56<01:15, 11.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1666/2529 [01:56<01:14, 11.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1668/2529 [01:56<01:05, 13.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1670/2529 [01:56<01:03, 13.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1672/2529 [01:56<01:02, 13.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▌   | 1674/2529 [01:57<00:57, 14.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1676/2529 [01:57<00:56, 15.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1679/2529 [01:57<00:49, 17.28it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  66%|██████▋   | 1681/2529 [01:57<00:57, 14.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1683/2529 [01:57<00:57, 14.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1685/2529 [01:57<01:04, 13.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1687/2529 [01:57<01:04, 13.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1689/2529 [01:58<01:01, 13.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1691/2529 [01:58<01:00, 13.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1693/2529 [01:58<01:02, 13.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1695/2529 [01:58<00:58, 14.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1697/2529 [01:58<00:58, 14.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1699/2529 [01:58<01:04, 12.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1701/2529 [01:59<01:09, 11.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1703/2529 [01:59<01:22, 10.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  67%|██████▋   | 1706/2529 [01:59<01:16, 10.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1708/2529 [01:59<01:18, 10.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1711/2529 [02:00<01:12, 11.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1713/2529 [02:00<01:17, 10.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1715/2529 [02:00<01:18, 10.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1717/2529 [02:00<01:22,  9.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1719/2529 [02:00<01:14, 10.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1721/2529 [02:00<01:06, 12.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1723/2529 [02:01<01:02, 12.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1725/2529 [02:01<01:11, 11.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1727/2529 [02:01<01:12, 11.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1729/2529 [02:01<01:20,  9.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  68%|██████▊   | 1731/2529 [02:01<01:17, 10.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1733/2529 [02:02<01:10, 11.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1735/2529 [02:02<01:02, 12.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▊   | 1737/2529 [02:02<01:03, 12.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1739/2529 [02:02<00:59, 13.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1741/2529 [02:02<01:09, 11.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1743/2529 [02:02<01:02, 12.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1745/2529 [02:02<00:58, 13.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1747/2529 [02:03<00:53, 14.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1749/2529 [02:03<00:51, 15.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1751/2529 [02:03<00:51, 15.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1753/2529 [02:03<00:52, 14.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1755/2529 [02:03<00:52, 14.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  69%|██████▉   | 1757/2529 [02:03<00:49, 15.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1760/2529 [02:03<00:44, 17.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1763/2529 [02:03<00:39, 19.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1766/2529 [02:04<00:38, 20.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|██████▉   | 1769/2529 [02:04<00:41, 18.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1771/2529 [02:04<00:45, 16.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1773/2529 [02:04<00:44, 16.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1775/2529 [02:04<00:49, 15.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1777/2529 [02:04<00:55, 13.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  70%|███████   | 1780/2529 [02:05<00:47, 15.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1783/2529 [02:05<00:42, 17.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1785/2529 [02:05<00:45, 16.41it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1787/2529 [02:05<00:49, 14.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1789/2529 [02:05<01:00, 12.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1792/2529 [02:05<00:50, 14.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1794/2529 [02:05<00:46, 15.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1797/2529 [02:06<00:40, 17.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████   | 1800/2529 [02:06<00:42, 17.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1803/2529 [02:06<00:48, 14.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1805/2529 [02:06<00:45, 15.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  71%|███████▏  | 1807/2529 [02:06<00:51, 14.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1809/2529 [02:06<00:51, 13.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1811/2529 [02:07<00:47, 15.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1814/2529 [02:07<00:43, 16.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1816/2529 [02:07<00:41, 17.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1819/2529 [02:07<00:41, 17.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1821/2529 [02:07<00:40, 17.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1823/2529 [02:07<00:39, 17.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1825/2529 [02:07<00:39, 17.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1827/2529 [02:07<00:42, 16.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1829/2529 [02:08<00:44, 15.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  72%|███████▏  | 1832/2529 [02:08<00:39, 17.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1834/2529 [02:08<00:44, 15.47it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1836/2529 [02:08<00:50, 13.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1838/2529 [02:08<00:49, 14.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1840/2529 [02:08<00:49, 13.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1842/2529 [02:09<00:56, 12.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1844/2529 [02:09<00:58, 11.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1846/2529 [02:09<00:59, 11.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1848/2529 [02:09<00:54, 12.56it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1850/2529 [02:09<00:51, 13.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1852/2529 [02:09<00:51, 13.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1854/2529 [02:10<00:48, 13.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1856/2529 [02:10<00:46, 14.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  73%|███████▎  | 1858/2529 [02:10<00:43, 15.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1860/2529 [02:10<00:42, 15.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1862/2529 [02:10<00:39, 16.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▎  | 1864/2529 [02:10<00:41, 15.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1867/2529 [02:10<00:36, 18.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1869/2529 [02:10<00:43, 15.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1871/2529 [02:11<00:43, 15.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1873/2529 [02:11<00:49, 13.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1875/2529 [02:11<01:00, 10.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1877/2529 [02:11<01:03, 10.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1879/2529 [02:11<01:01, 10.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1881/2529 [02:12<00:55, 11.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  74%|███████▍  | 1883/2529 [02:12<00:53, 12.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1886/2529 [02:12<00:47, 13.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1888/2529 [02:12<00:46, 13.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1891/2529 [02:12<00:42, 15.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1893/2529 [02:12<00:43, 14.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▍  | 1895/2529 [02:12<00:45, 13.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1897/2529 [02:13<00:45, 13.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1899/2529 [02:13<00:44, 14.23it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1901/2529 [02:13<00:40, 15.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1904/2529 [02:13<00:36, 17.06it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1906/2529 [02:13<00:35, 17.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  75%|███████▌  | 1909/2529 [02:13<00:34, 18.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1911/2529 [02:14<00:47, 13.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1913/2529 [02:14<00:46, 13.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1915/2529 [02:14<00:44, 13.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1917/2529 [02:14<00:42, 14.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1920/2529 [02:14<00:38, 15.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1922/2529 [02:14<00:37, 16.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1924/2529 [02:14<00:36, 16.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1926/2529 [02:14<00:35, 17.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▌  | 1928/2529 [02:15<00:39, 15.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▋  | 1931/2529 [02:15<00:35, 16.84it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  76%|███████▋  | 1934/2529 [02:15<00:36, 16.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1936/2529 [02:15<00:41, 14.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1938/2529 [02:15<00:44, 13.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1940/2529 [02:15<00:42, 13.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1942/2529 [02:16<00:39, 14.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1944/2529 [02:16<00:40, 14.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1947/2529 [02:16<00:34, 16.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1949/2529 [02:16<00:36, 16.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1951/2529 [02:16<00:36, 15.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1953/2529 [02:16<00:38, 14.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1955/2529 [02:16<00:42, 13.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1957/2529 [02:17<00:40, 13.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  77%|███████▋  | 1959/2529 [02:17<00:39, 14.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1961/2529 [02:17<00:38, 14.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1963/2529 [02:17<00:41, 13.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1965/2529 [02:17<00:40, 14.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1967/2529 [02:17<00:41, 13.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1969/2529 [02:18<00:49, 11.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1971/2529 [02:18<01:03,  8.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1973/2529 [02:18<01:12,  7.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1974/2529 [02:18<01:10,  7.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1975/2529 [02:18<01:10,  7.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1976/2529 [02:19<01:08,  8.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1977/2529 [02:19<01:06,  8.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1978/2529 [02:19<01:04,  8.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1979/2529 [02:19<01:06,  8.27it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1980/2529 [02:19<01:06,  8.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1981/2529 [02:19<01:05,  8.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1983/2529 [02:19<00:54, 10.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  78%|███████▊  | 1985/2529 [02:19<00:47, 11.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1987/2529 [02:20<00:46, 11.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1989/2529 [02:20<00:47, 11.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▊  | 1991/2529 [02:20<00:40, 13.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1993/2529 [02:20<00:39, 13.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1995/2529 [02:20<00:47, 11.31it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1997/2529 [02:20<00:42, 12.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 1999/2529 [02:21<00:49, 10.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2001/2529 [02:21<00:49, 10.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2004/2529 [02:21<00:38, 13.59it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2006/2529 [02:21<00:37, 13.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2008/2529 [02:21<00:34, 15.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  79%|███████▉  | 2010/2529 [02:21<00:33, 15.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2013/2529 [02:21<00:30, 17.12it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2016/2529 [02:22<00:27, 18.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2018/2529 [02:22<00:37, 13.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2020/2529 [02:22<00:47, 10.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|███████▉  | 2022/2529 [02:22<00:45, 11.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2024/2529 [02:22<00:40, 12.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2026/2529 [02:23<00:37, 13.54it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2029/2529 [02:23<00:36, 13.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2031/2529 [02:23<00:35, 14.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2033/2529 [02:23<00:40, 12.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  80%|████████  | 2035/2529 [02:23<00:35, 13.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2037/2529 [02:23<00:41, 11.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2039/2529 [02:24<00:40, 12.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2041/2529 [02:24<00:39, 12.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2043/2529 [02:24<00:35, 13.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2046/2529 [02:24<00:30, 15.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2049/2529 [02:24<00:27, 17.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2051/2529 [02:24<00:33, 14.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████  | 2054/2529 [02:25<00:29, 16.17it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2056/2529 [02:25<00:27, 16.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2059/2529 [02:25<00:26, 17.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  81%|████████▏ | 2061/2529 [02:25<00:25, 18.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2063/2529 [02:25<00:30, 15.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2065/2529 [02:25<00:28, 16.04it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2067/2529 [02:25<00:31, 14.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2069/2529 [02:25<00:30, 14.91it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2071/2529 [02:26<00:30, 14.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2073/2529 [02:26<00:33, 13.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2075/2529 [02:26<00:33, 13.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2077/2529 [02:26<00:42, 10.75it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2079/2529 [02:26<00:36, 12.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2082/2529 [02:27<00:39, 11.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  82%|████████▏ | 2084/2529 [02:27<00:40, 10.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2087/2529 [02:27<00:33, 13.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2089/2529 [02:27<00:31, 14.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2091/2529 [02:27<00:39, 11.00it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2093/2529 [02:28<00:37, 11.53it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2095/2529 [02:28<00:38, 11.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2097/2529 [02:28<00:34, 12.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2099/2529 [02:28<00:32, 13.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2101/2529 [02:28<00:31, 13.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2103/2529 [02:28<00:33, 12.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2105/2529 [02:28<00:30, 14.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2107/2529 [02:28<00:28, 14.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2109/2529 [02:29<00:30, 13.67it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  83%|████████▎ | 2111/2529 [02:29<00:28, 14.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2114/2529 [02:29<00:24, 16.69it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2116/2529 [02:29<00:29, 14.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▎ | 2118/2529 [02:29<00:39, 10.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2120/2529 [02:30<00:35, 11.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2123/2529 [02:30<00:28, 14.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2125/2529 [02:30<00:29, 13.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2127/2529 [02:30<00:28, 14.01it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2129/2529 [02:30<00:28, 14.26it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2132/2529 [02:30<00:24, 16.03it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2134/2529 [02:30<00:23, 16.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  84%|████████▍ | 2136/2529 [02:31<00:25, 15.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2139/2529 [02:31<00:22, 17.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2141/2529 [02:31<00:24, 15.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2143/2529 [02:31<00:25, 15.29it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2145/2529 [02:31<00:24, 15.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▍ | 2148/2529 [02:31<00:21, 17.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2151/2529 [02:31<00:19, 19.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2153/2529 [02:31<00:19, 19.25it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2155/2529 [02:32<00:20, 18.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2158/2529 [02:32<00:19, 19.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  85%|████████▌ | 2161/2529 [02:32<00:17, 20.51it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2164/2529 [02:32<00:18, 20.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2167/2529 [02:32<00:19, 18.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2170/2529 [02:32<00:18, 19.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2172/2529 [02:32<00:21, 16.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2174/2529 [02:33<00:20, 17.59it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2176/2529 [02:33<00:22, 15.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2179/2529 [02:33<00:20, 16.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▌ | 2181/2529 [02:33<00:19, 17.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▋ | 2184/2529 [02:33<00:18, 18.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  86%|████████▋ | 2186/2529 [02:33<00:19, 17.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2188/2529 [02:33<00:19, 17.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2191/2529 [02:34<00:17, 18.81it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2194/2529 [02:34<00:17, 18.64it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2196/2529 [02:34<00:20, 16.13it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2198/2529 [02:34<00:20, 16.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2201/2529 [02:34<00:18, 17.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2203/2529 [02:34<00:18, 17.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2205/2529 [02:34<00:19, 16.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2207/2529 [02:35<00:19, 16.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  87%|████████▋ | 2210/2529 [02:35<00:19, 16.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2213/2529 [02:35<00:17, 18.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2216/2529 [02:35<00:16, 18.82it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2219/2529 [02:35<00:15, 20.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2222/2529 [02:35<00:14, 21.16it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2225/2529 [02:35<00:14, 20.38it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2228/2529 [02:36<00:18, 16.62it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2230/2529 [02:36<00:18, 15.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2233/2529 [02:36<00:17, 16.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2235/2529 [02:36<00:22, 13.15it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  88%|████████▊ | 2237/2529 [02:36<00:20, 14.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▊ | 2240/2529 [02:37<00:19, 14.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▊ | 2242/2529 [02:37<00:20, 14.22it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2245/2529 [02:37<00:17, 15.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2247/2529 [02:37<00:19, 14.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2249/2529 [02:37<00:19, 14.35it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2251/2529 [02:37<00:18, 15.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2254/2529 [02:37<00:16, 16.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2257/2529 [02:38<00:14, 18.90it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2260/2529 [02:38<00:15, 17.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  89%|████████▉ | 2262/2529 [02:38<00:15, 17.11it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2265/2529 [02:38<00:14, 18.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2267/2529 [02:38<00:14, 18.30it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2270/2529 [02:38<00:14, 18.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2272/2529 [02:38<00:14, 17.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2274/2529 [02:39<00:16, 15.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|████████▉ | 2276/2529 [02:39<00:16, 15.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2278/2529 [02:39<00:16, 15.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2280/2529 [02:39<00:15, 15.68it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2283/2529 [02:39<00:13, 17.72it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2285/2529 [02:39<00:13, 18.11it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  90%|█████████ | 2288/2529 [02:39<00:13, 17.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2290/2529 [02:39<00:14, 17.07it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2292/2529 [02:40<00:13, 17.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2294/2529 [02:40<00:13, 17.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2297/2529 [02:40<00:11, 19.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2300/2529 [02:40<00:11, 20.49it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2303/2529 [02:40<00:12, 18.43it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2305/2529 [02:40<00:13, 16.09it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████ | 2307/2529 [02:40<00:14, 15.62it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2309/2529 [02:41<00:14, 15.60it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2311/2529 [02:41<00:13, 16.36it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  91%|█████████▏| 2313/2529 [02:41<00:13, 15.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2315/2529 [02:41<00:16, 12.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2317/2529 [02:41<00:15, 14.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2320/2529 [02:41<00:12, 16.08it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2322/2529 [02:41<00:12, 16.85it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2325/2529 [02:42<00:12, 16.10it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2327/2529 [02:42<00:12, 15.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2330/2529 [02:42<00:11, 17.58it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2332/2529 [02:42<00:11, 17.77it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2335/2529 [02:42<00:10, 19.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2337/2529 [02:42<00:10, 18.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  92%|█████████▏| 2339/2529 [02:42<00:10, 17.61it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2342/2529 [02:43<00:10, 17.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2345/2529 [02:43<00:10, 17.89it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2347/2529 [02:43<00:10, 17.42it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2349/2529 [02:43<00:10, 17.70it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2351/2529 [02:43<00:11, 15.44it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2353/2529 [02:43<00:12, 14.57it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2355/2529 [02:43<00:11, 15.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2358/2529 [02:44<00:10, 16.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2360/2529 [02:44<00:09, 16.95it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  93%|█████████▎| 2363/2529 [02:44<00:08, 19.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2366/2529 [02:44<00:09, 17.63it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2368/2529 [02:44<00:09, 17.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▎| 2370/2529 [02:44<00:09, 17.46it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2373/2529 [02:44<00:09, 15.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2375/2529 [02:45<00:09, 16.20it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2377/2529 [02:45<00:09, 16.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2379/2529 [02:45<00:08, 16.93it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2381/2529 [02:45<00:08, 16.80it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2384/2529 [02:45<00:07, 18.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  94%|█████████▍| 2387/2529 [02:45<00:07, 20.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2390/2529 [02:45<00:06, 20.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2393/2529 [02:45<00:07, 18.40it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2396/2529 [02:46<00:07, 18.79it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2399/2529 [02:46<00:06, 18.98it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▍| 2402/2529 [02:46<00:06, 20.52it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2405/2529 [02:46<00:06, 18.67it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2407/2529 [02:46<00:07, 16.24it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2410/2529 [02:46<00:06, 17.83it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2412/2529 [02:47<00:06, 17.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  95%|█████████▌| 2414/2529 [02:47<00:06, 17.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2417/2529 [02:47<00:05, 19.05it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2420/2529 [02:47<00:05, 19.02it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2423/2529 [02:47<00:05, 19.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2426/2529 [02:47<00:05, 19.73it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2429/2529 [02:47<00:05, 19.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2432/2529 [02:48<00:05, 17.18it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▌| 2434/2529 [02:48<00:05, 17.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▋| 2436/2529 [02:48<00:05, 16.74it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  96%|█████████▋| 2438/2529 [02:48<00:05, 15.78it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2441/2529 [02:48<00:04, 17.96it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2444/2529 [02:48<00:04, 19.32it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2446/2529 [02:48<00:04, 18.48it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2448/2529 [02:48<00:04, 17.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2450/2529 [02:49<00:04, 17.76it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2453/2529 [02:49<00:03, 19.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2455/2529 [02:49<00:04, 15.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2458/2529 [02:49<00:04, 17.14it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2461/2529 [02:49<00:03, 17.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2461/2529 [04:19<00:03, 17.33it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2462/2529 [04:19<13:55, 12.47s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  97%|█████████▋| 2464/2529 [04:19<09:41,  8.95s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2466/2529 [04:19<06:43,  6.40s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2469/2529 [04:19<03:58,  3.97s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2471/2529 [04:20<02:49,  2.93s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2474/2529 [04:20<01:43,  1.88s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2476/2529 [04:20<01:14,  1.41s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2478/2529 [04:20<00:53,  1.05s/it]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2480/2529 [04:20<00:37,  1.29it/s]

Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2483/2529 [04:20<00:23,  1.99it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2486/2529 [04:20<00:14,  2.92it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  98%|█████████▊| 2489/2529 [04:20<00:09,  4.06it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▊| 2492/2529 [04:21<00:06,  5.55it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▊| 2495/2529 [04:21<00:04,  7.34it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2498/2529 [04:21<00:03,  8.50it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2500/2529 [04:21<00:03,  9.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2502/2529 [04:21<00:02,  9.97it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2504/2529 [04:21<00:02, 10.86it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2506/2529 [04:21<00:01, 11.88it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2508/2529 [04:22<00:01, 12.65it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2511/2529 [04:22<00:01, 14.94it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene:  99%|█████████▉| 2514/2529 [04:22<00:00, 15.39it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2517/2529 [04:22<00:00, 16.87it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2519/2529 [04:22<00:00, 16.66it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2522/2529 [04:22<00:00, 18.21it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2525/2529 [04:22<00:00, 18.37it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|█████████▉| 2527/2529 [04:23<00:00, 18.71it/s]
Processing: positive r2g, Top 15 region-to-gene links per gene: 100%|██████████| 2529/2529 [04:23<00:00, 17.75it/s]
 93%|█████████▎| 13/14 [38:14<03:09, 189.78s/it]
Processing: positive r2g, BASC binarized:   0%|          | 0/2529 [00:00<?, ?it/s]
Processing: positive r2g, BASC binarized:   0%|          | 1/2529 [00:00<06:24,  6.57it/s]
Processing: positive r2g, BASC binarized:   0%|          | 2/2529 [00:00<05:22,  7.82it/s]
Processing: positive r2g, BASC binarized:   0%|          | 3/2529 [00:00<05:07,  8.22it/s]
Processing: positive r2g, BASC binarized:   0%|          | 4/2529 [00:00<05:11,  8.10it/s]
Processing: positive r2g, BASC binarized:   0%|          | 5/2529 [00:00<04:53,  8.60it/s]
Processing: positive r2g, BASC binarized:   0%|          | 6/2529 [00:00<04:39,  9.03it/s]
Processing: positive r2g, BASC binarized:   0%|          | 7/2529 [00:00<04:54,  8.55it/s]
Processing: positive r2g, BASC binarized:   0%|          | 8/2529 [00:00<04:51,  8.65it/s]
Processing: positive r2g, BASC binarized:   0%|          | 9/2529 [00:01<04:52,  8.62it/s]
Processing: positive r2g, BASC binarized:   0%|          | 10/2529 [00:01<04:51,  8.64it/s]
Processing: positive r2g, BASC binarized:   0%|          | 11/2529 [00:01<04:52,  8.61it/s]
Processing: positive r2g, BASC binarized:   0%|          | 12/2529 [00:01<05:32,  7.57it/s]
Processing: positive r2g, BASC binarized:   1%|          | 13/2529 [00:01<05:17,  7.94it/s]
Processing: positive r2g, BASC binarized:   1%|          | 14/2529 [00:01<05:11,  8.07it/s]
Processing: positive r2g, BASC binarized:   1%|          | 15/2529 [00:01<05:05,  8.23it/s]
Processing: positive r2g, BASC binarized:   1%|          | 16/2529 [00:01<04:49,  8.68it/s]
Processing: positive r2g, BASC binarized:   1%|          | 17/2529 [00:02<04:54,  8.54it/s]
Processing: positive r2g, BASC binarized:   1%|          | 19/2529 [00:02<05:42,  7.33it/s]
Processing: positive r2g, BASC binarized:   1%|          | 20/2529 [00:02<06:10,  6.77it/s]
Processing: positive r2g, BASC binarized:   1%|          | 21/2529 [00:02<05:50,  7.17it/s]
Processing: positive r2g, BASC binarized:   1%|          | 22/2529 [00:02<05:29,  7.60it/s]
Processing: positive r2g, BASC binarized:   1%|          | 23/2529 [00:02<05:59,  6.97it/s]
Processing: positive r2g, BASC binarized:   1%|          | 24/2529 [00:03<05:38,  7.41it/s]
Processing: positive r2g, BASC binarized:   1%|          | 25/2529 [00:03<05:24,  7.71it/s]
Processing: positive r2g, BASC binarized:   1%|          | 26/2529 [00:03<05:09,  8.08it/s]
Processing: positive r2g, BASC binarized:   1%|          | 27/2529 [00:03<04:59,  8.36it/s]
Processing: positive r2g, BASC binarized:   1%|          | 28/2529 [00:03<04:49,  8.64it/s]
Processing: positive r2g, BASC binarized:   1%|          | 29/2529 [00:03<06:04,  6.86it/s]
Processing: positive r2g, BASC binarized:   1%|          | 30/2529 [00:03<05:54,  7.06it/s]
Processing: positive r2g, BASC binarized:   1%|          | 31/2529 [00:04<06:22,  6.54it/s]
Processing: positive r2g, BASC binarized:   1%|▏         | 32/2529 [00:04<06:44,  6.18it/s]
Processing: positive r2g, BASC binarized:   1%|▏         | 33/2529 [00:04<06:08,  6.77it/s]
Processing: positive r2g, BASC binarized:   1%|▏         | 35/2529 [00:04<05:19,  7.80it/s]
Processing: positive r2g, BASC binarized:   1%|▏         | 36/2529 [00:04<05:10,  8.03it/s]
Processing: positive r2g, BASC binarized:   1%|▏         | 37/2529 [00:04<05:27,  7.61it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 38/2529 [00:04<05:41,  7.30it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 40/2529 [00:05<05:53,  7.04it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 41/2529 [00:05<05:40,  7.31it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 42/2529 [00:05<05:23,  7.69it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 43/2529 [00:05<05:15,  7.87it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 45/2529 [00:05<04:58,  8.31it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 47/2529 [00:06<05:21,  7.72it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 48/2529 [00:06<05:49,  7.10it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 49/2529 [00:06<05:45,  7.17it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 50/2529 [00:06<05:40,  7.27it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 51/2529 [00:06<05:31,  7.48it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 52/2529 [00:06<05:30,  7.49it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 53/2529 [00:06<05:24,  7.64it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 54/2529 [00:07<05:14,  7.87it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 56/2529 [00:07<04:46,  8.62it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 57/2529 [00:07<04:39,  8.85it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 59/2529 [00:07<04:17,  9.59it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 61/2529 [00:07<04:16,  9.62it/s]
Processing: positive r2g, BASC binarized:   2%|▏         | 63/2529 [00:07<04:09,  9.89it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 64/2529 [00:08<04:16,  9.63it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 65/2529 [00:08<04:16,  9.60it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 67/2529 [00:08<04:15,  9.65it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 68/2529 [00:08<04:22,  9.38it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 70/2529 [00:08<04:37,  8.86it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 71/2529 [00:08<04:47,  8.56it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 72/2529 [00:09<05:19,  7.69it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 73/2529 [00:09<05:13,  7.84it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 74/2529 [00:09<05:42,  7.17it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 75/2529 [00:09<06:04,  6.74it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 76/2529 [00:09<06:01,  6.78it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 77/2529 [00:09<05:53,  6.94it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 78/2529 [00:09<05:23,  7.57it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 79/2529 [00:09<05:01,  8.12it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 80/2529 [00:10<04:49,  8.45it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 82/2529 [00:10<04:33,  8.95it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 83/2529 [00:10<04:31,  9.01it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 85/2529 [00:10<04:56,  8.24it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 86/2529 [00:10<05:25,  7.49it/s]
Processing: positive r2g, BASC binarized:   3%|▎         | 88/2529 [00:11<05:28,  7.42it/s]
Processing: positive r2g, BASC binarized:   4%|▎         | 89/2529 [00:11<05:17,  7.69it/s]
Processing: positive r2g, BASC binarized:   4%|▎         | 90/2529 [00:11<05:08,  7.92it/s]
Processing: positive r2g, BASC binarized:   4%|▎         | 91/2529 [00:11<04:58,  8.18it/s]
Processing: positive r2g, BASC binarized:   4%|▎         | 92/2529 [00:11<04:55,  8.25it/s]
Processing: positive r2g, BASC binarized:   4%|▎         | 94/2529 [00:11<04:27,  9.12it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 95/2529 [00:11<04:44,  8.56it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 96/2529 [00:12<04:44,  8.55it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 97/2529 [00:12<04:40,  8.66it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 98/2529 [00:12<04:50,  8.37it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 99/2529 [00:12<05:23,  7.52it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 100/2529 [00:12<06:07,  6.60it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 101/2529 [00:12<05:52,  6.89it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 102/2529 [00:12<05:39,  7.14it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 103/2529 [00:13<05:41,  7.09it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 105/2529 [00:13<04:51,  8.32it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 107/2529 [00:13<04:20,  9.29it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 109/2529 [00:13<04:44,  8.52it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 110/2529 [00:13<04:35,  8.78it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 111/2529 [00:13<04:37,  8.71it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 112/2529 [00:14<04:50,  8.32it/s]
Processing: positive r2g, BASC binarized:   4%|▍         | 113/2529 [00:14<04:45,  8.47it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 114/2529 [00:14<04:38,  8.67it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 115/2529 [00:14<06:42,  6.00it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 116/2529 [00:14<06:58,  5.77it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 117/2529 [00:14<07:23,  5.43it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 118/2529 [00:15<08:03,  4.99it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 119/2529 [00:15<07:01,  5.72it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 120/2529 [00:15<07:27,  5.38it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 121/2529 [00:15<07:09,  5.61it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 122/2529 [00:15<07:10,  5.59it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 123/2529 [00:15<06:26,  6.22it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 124/2529 [00:16<06:44,  5.95it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 125/2529 [00:16<06:07,  6.55it/s]
Processing: positive r2g, BASC binarized:   5%|▍         | 126/2529 [00:16<05:39,  7.07it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 127/2529 [00:16<07:04,  5.66it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 128/2529 [00:16<07:35,  5.27it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 129/2529 [00:17<07:10,  5.58it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 130/2529 [00:17<07:07,  5.62it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 131/2529 [00:17<07:32,  5.30it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 132/2529 [00:17<08:01,  4.98it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 133/2529 [00:17<08:14,  4.84it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 134/2529 [00:18<08:09,  4.90it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 135/2529 [00:18<08:00,  4.98it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 136/2529 [00:18<08:14,  4.84it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 137/2529 [00:18<08:32,  4.67it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 138/2529 [00:18<08:23,  4.75it/s]
Processing: positive r2g, BASC binarized:   5%|▌         | 139/2529 [00:19<08:17,  4.81it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 140/2529 [00:19<07:15,  5.49it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 141/2529 [00:19<06:53,  5.77it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 142/2529 [00:19<06:50,  5.81it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 143/2529 [00:19<06:18,  6.30it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 144/2529 [00:19<06:08,  6.47it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 145/2529 [00:20<07:18,  5.44it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 146/2529 [00:20<06:30,  6.10it/s]

Processing: positive r2g, BASC binarized:   6%|▌         | 147/2529 [00:20<06:53,  5.76it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 148/2529 [00:20<07:23,  5.37it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 149/2529 [00:20<06:34,  6.03it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 150/2529 [00:20<05:59,  6.61it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 152/2529 [00:21<05:00,  7.92it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 154/2529 [00:21<05:03,  7.82it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 155/2529 [00:21<06:14,  6.34it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 156/2529 [00:21<06:57,  5.68it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 157/2529 [00:21<07:07,  5.55it/s]
Processing: positive r2g, BASC binarized:   6%|▌         | 158/2529 [00:22<07:30,  5.26it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 159/2529 [00:22<07:28,  5.29it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 160/2529 [00:22<07:54,  4.99it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 161/2529 [00:22<08:11,  4.82it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 162/2529 [00:23<07:55,  4.98it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 163/2529 [00:23<07:55,  4.98it/s]
Processing: positive r2g, BASC binarized:   6%|▋         | 164/2529 [00:23<07:27,  5.28it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 165/2529 [00:23<06:37,  5.94it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 166/2529 [00:23<06:00,  6.55it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 167/2529 [00:23<06:24,  6.15it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 168/2529 [00:24<06:43,  5.86it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 169/2529 [00:24<06:49,  5.76it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 171/2529 [00:24<06:34,  5.98it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 172/2529 [00:24<06:51,  5.72it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 173/2529 [00:24<06:57,  5.64it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 174/2529 [00:25<07:03,  5.55it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 175/2529 [00:25<07:02,  5.57it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 176/2529 [00:25<06:52,  5.71it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 177/2529 [00:25<06:29,  6.03it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 178/2529 [00:25<06:09,  6.36it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 179/2529 [00:25<05:41,  6.88it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 180/2529 [00:25<05:55,  6.60it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 181/2529 [00:26<05:34,  7.02it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 182/2529 [00:26<05:08,  7.62it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 183/2529 [00:26<04:59,  7.83it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 184/2529 [00:26<05:05,  7.67it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 185/2529 [00:26<04:57,  7.87it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 186/2529 [00:26<04:49,  8.10it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 187/2529 [00:26<04:42,  8.28it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 188/2529 [00:26<04:57,  7.87it/s]
Processing: positive r2g, BASC binarized:   7%|▋         | 189/2529 [00:27<04:44,  8.22it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 190/2529 [00:27<05:40,  6.86it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 191/2529 [00:27<05:20,  7.30it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 192/2529 [00:27<05:26,  7.16it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 193/2529 [00:27<05:12,  7.48it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 194/2529 [00:27<05:00,  7.76it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 195/2529 [00:27<04:50,  8.04it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 196/2529 [00:28<04:58,  7.82it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 197/2529 [00:28<04:49,  8.06it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 198/2529 [00:28<05:06,  7.60it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 200/2529 [00:28<04:37,  8.38it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 202/2529 [00:28<04:17,  9.03it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 203/2529 [00:28<05:03,  7.68it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 204/2529 [00:29<05:36,  6.90it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 205/2529 [00:29<05:23,  7.17it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 206/2529 [00:29<05:09,  7.50it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 207/2529 [00:29<05:05,  7.61it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 208/2529 [00:29<04:52,  7.93it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 209/2529 [00:29<04:47,  8.08it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 210/2529 [00:29<04:36,  8.40it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 211/2529 [00:29<04:33,  8.48it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 212/2529 [00:29<04:24,  8.76it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 213/2529 [00:30<05:31,  6.98it/s]
Processing: positive r2g, BASC binarized:   8%|▊         | 214/2529 [00:30<06:01,  6.40it/s]
Processing: positive r2g, BASC binarized:   9%|▊         | 216/2529 [00:30<05:22,  7.17it/s]
Processing: positive r2g, BASC binarized:   9%|▊         | 218/2529 [00:30<04:41,  8.21it/s]
Processing: positive r2g, BASC binarized:   9%|▊         | 220/2529 [00:31<04:18,  8.92it/s]
Processing: positive r2g, BASC binarized:   9%|▊         | 221/2529 [00:31<04:26,  8.67it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 222/2529 [00:31<04:18,  8.92it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 223/2529 [00:31<04:19,  8.90it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 224/2529 [00:31<04:24,  8.71it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 225/2529 [00:31<05:06,  7.52it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 226/2529 [00:31<04:53,  7.84it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 228/2529 [00:31<04:18,  8.92it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 229/2529 [00:32<04:20,  8.83it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 230/2529 [00:32<04:18,  8.89it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 231/2529 [00:32<04:14,  9.03it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 232/2529 [00:32<04:21,  8.79it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 233/2529 [00:32<04:23,  8.70it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 235/2529 [00:32<04:12,  9.10it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 237/2529 [00:32<03:59,  9.56it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 238/2529 [00:33<04:05,  9.35it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 239/2529 [00:33<04:09,  9.19it/s]
Processing: positive r2g, BASC binarized:   9%|▉         | 240/2529 [00:33<04:48,  7.93it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 241/2529 [00:33<04:36,  8.26it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 242/2529 [00:33<04:44,  8.05it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 243/2529 [00:33<04:36,  8.26it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 245/2529 [00:33<04:04,  9.35it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 246/2529 [00:34<04:45,  7.99it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 247/2529 [00:34<05:18,  7.17it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 248/2529 [00:34<05:04,  7.50it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 250/2529 [00:34<05:07,  7.42it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 251/2529 [00:34<04:56,  7.68it/s]
Processing: positive r2g, BASC binarized:  10%|▉         | 252/2529 [00:34<04:47,  7.92it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 254/2529 [00:35<04:21,  8.71it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 256/2529 [00:35<04:04,  9.31it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 257/2529 [00:35<04:17,  8.82it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 258/2529 [00:35<04:29,  8.44it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 260/2529 [00:35<04:09,  9.09it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 261/2529 [00:35<04:07,  9.16it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 262/2529 [00:36<05:31,  6.84it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 263/2529 [00:36<05:15,  7.17it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 264/2529 [00:36<05:05,  7.42it/s]
Processing: positive r2g, BASC binarized:  10%|█         | 265/2529 [00:36<05:08,  7.34it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 266/2529 [00:36<04:46,  7.89it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 268/2529 [00:36<04:11,  9.00it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 270/2529 [00:36<03:56,  9.53it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 271/2529 [00:37<04:02,  9.32it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 272/2529 [00:37<04:36,  8.15it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 273/2529 [00:37<04:37,  8.13it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 274/2529 [00:37<04:33,  8.24it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 275/2529 [00:37<04:44,  7.93it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 277/2529 [00:37<04:13,  8.90it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 279/2529 [00:37<04:00,  9.36it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 280/2529 [00:38<04:05,  9.18it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 281/2529 [00:38<04:19,  8.66it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 282/2529 [00:38<04:38,  8.06it/s]
Processing: positive r2g, BASC binarized:  11%|█         | 283/2529 [00:38<04:36,  8.14it/s]
Processing: positive r2g, BASC binarized:  11%|█▏        | 285/2529 [00:38<04:20,  8.62it/s]
Processing: positive r2g, BASC binarized:  11%|█▏        | 286/2529 [00:38<04:19,  8.64it/s]
Processing: positive r2g, BASC binarized:  11%|█▏        | 288/2529 [00:39<04:11,  8.92it/s]
Processing: positive r2g, BASC binarized:  11%|█▏        | 289/2529 [00:39<04:36,  8.10it/s]
Processing: positive r2g, BASC binarized:  11%|█▏        | 290/2529 [00:39<04:43,  7.91it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 291/2529 [00:39<04:33,  8.20it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 292/2529 [00:39<04:29,  8.29it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 293/2529 [00:39<04:33,  8.18it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 294/2529 [00:39<04:25,  8.41it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 295/2529 [00:39<04:37,  8.06it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 296/2529 [00:40<04:28,  8.30it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 297/2529 [00:40<04:22,  8.51it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 298/2529 [00:40<05:22,  6.92it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 299/2529 [00:40<05:05,  7.30it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 300/2529 [00:40<04:50,  7.66it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 301/2529 [00:40<04:40,  7.95it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 302/2529 [00:40<04:30,  8.24it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 303/2529 [00:40<04:24,  8.41it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 304/2529 [00:41<04:22,  8.48it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 305/2529 [00:41<04:15,  8.69it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 306/2529 [00:41<04:07,  8.97it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 307/2529 [00:41<04:00,  9.23it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 309/2529 [00:41<03:47,  9.76it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 310/2529 [00:41<03:52,  9.54it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 311/2529 [00:41<03:54,  9.46it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 313/2529 [00:42<03:54,  9.47it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 315/2529 [00:42<03:49,  9.65it/s]
Processing: positive r2g, BASC binarized:  12%|█▏        | 316/2529 [00:42<03:53,  9.50it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 318/2529 [00:42<03:47,  9.74it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 319/2529 [00:42<03:50,  9.58it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 320/2529 [00:42<03:55,  9.36it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 321/2529 [00:42<04:00,  9.18it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 322/2529 [00:43<04:24,  8.35it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 323/2529 [00:43<04:22,  8.40it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 325/2529 [00:43<04:25,  8.29it/s]

Processing: positive r2g, BASC binarized:  13%|█▎        | 326/2529 [00:43<04:52,  7.54it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 328/2529 [00:43<04:14,  8.64it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 329/2529 [00:43<04:13,  8.69it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 330/2529 [00:43<04:06,  8.93it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 331/2529 [00:44<05:03,  7.24it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 332/2529 [00:44<05:36,  6.54it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 333/2529 [00:44<05:57,  6.14it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 334/2529 [00:44<05:30,  6.64it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 335/2529 [00:44<05:22,  6.80it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 336/2529 [00:44<05:00,  7.29it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 337/2529 [00:45<05:04,  7.21it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 339/2529 [00:45<04:42,  7.76it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 340/2529 [00:45<04:43,  7.72it/s]
Processing: positive r2g, BASC binarized:  13%|█▎        | 341/2529 [00:45<04:41,  7.77it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 342/2529 [00:45<04:50,  7.53it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 343/2529 [00:45<05:53,  6.18it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 344/2529 [00:46<05:31,  6.60it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 345/2529 [00:46<05:13,  6.96it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 346/2529 [00:46<04:58,  7.32it/s]
Processing: positive r2g, BASC binarized:  14%|█▎        | 347/2529 [00:46<05:17,  6.88it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 348/2529 [00:46<05:05,  7.13it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 350/2529 [00:46<04:15,  8.54it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 352/2529 [00:47<04:18,  8.43it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 353/2529 [00:47<04:19,  8.38it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 354/2529 [00:47<04:51,  7.46it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 355/2529 [00:47<05:22,  6.75it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 356/2529 [00:47<05:42,  6.34it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 357/2529 [00:47<05:59,  6.05it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 358/2529 [00:48<05:48,  6.22it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 359/2529 [00:48<06:35,  5.49it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 360/2529 [00:48<07:03,  5.12it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 361/2529 [00:48<07:05,  5.10it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 362/2529 [00:48<06:57,  5.19it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 363/2529 [00:49<07:19,  4.93it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 364/2529 [00:49<07:09,  5.04it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 365/2529 [00:49<07:38,  4.72it/s]
Processing: positive r2g, BASC binarized:  14%|█▍        | 366/2529 [00:49<08:17,  4.35it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 367/2529 [00:50<08:29,  4.24it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 368/2529 [00:50<08:08,  4.42it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 369/2529 [00:50<07:40,  4.69it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 370/2529 [00:50<07:46,  4.63it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 371/2529 [00:50<08:00,  4.49it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 372/2529 [00:51<07:47,  4.62it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 373/2529 [00:51<07:26,  4.83it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 374/2529 [00:51<07:35,  4.73it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 375/2529 [00:51<07:37,  4.71it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 376/2529 [00:51<06:42,  5.36it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 378/2529 [00:52<05:09,  6.94it/s]
Processing: positive r2g, BASC binarized:  15%|█▍        | 379/2529 [00:52<04:56,  7.26it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 380/2529 [00:52<04:41,  7.64it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 381/2529 [00:52<04:31,  7.91it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 382/2529 [00:52<04:37,  7.75it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 383/2529 [00:52<05:04,  7.05it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 384/2529 [00:52<04:45,  7.50it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 385/2529 [00:52<04:43,  7.56it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 386/2529 [00:53<04:30,  7.93it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 387/2529 [00:53<04:28,  7.98it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 388/2529 [00:53<04:25,  8.06it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 389/2529 [00:53<04:25,  8.06it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 390/2529 [00:53<04:20,  8.20it/s]
Processing: positive r2g, BASC binarized:  15%|█▌        | 391/2529 [00:53<04:14,  8.40it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 392/2529 [00:53<04:29,  7.92it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 393/2529 [00:53<04:25,  8.05it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 394/2529 [00:54<05:02,  7.05it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 395/2529 [00:54<05:38,  6.30it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 396/2529 [00:54<06:57,  5.11it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 397/2529 [00:54<06:58,  5.09it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 398/2529 [00:54<06:46,  5.25it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 399/2529 [00:55<06:40,  5.31it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 400/2529 [00:55<06:34,  5.40it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 402/2529 [00:55<05:37,  6.29it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 403/2529 [00:55<06:54,  5.13it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 404/2529 [00:55<06:24,  5.53it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 405/2529 [00:56<05:52,  6.02it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 407/2529 [00:56<04:44,  7.47it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 408/2529 [00:56<04:37,  7.65it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 409/2529 [00:56<05:00,  7.06it/s]
Processing: positive r2g, BASC binarized:  16%|█▌        | 410/2529 [00:56<05:05,  6.95it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 411/2529 [00:56<05:35,  6.31it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 412/2529 [00:57<05:41,  6.20it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 413/2529 [00:57<05:33,  6.34it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 415/2529 [00:57<04:29,  7.84it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 416/2529 [00:57<04:22,  8.05it/s]
Processing: positive r2g, BASC binarized:  16%|█▋        | 417/2529 [00:57<04:14,  8.30it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 418/2529 [00:57<04:27,  7.89it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 419/2529 [00:57<04:57,  7.09it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 421/2529 [00:58<04:26,  7.91it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 422/2529 [00:58<04:22,  8.04it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 423/2529 [00:58<04:25,  7.94it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 425/2529 [00:58<03:59,  8.80it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 427/2529 [00:58<03:50,  9.13it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 428/2529 [00:59<04:40,  7.48it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 429/2529 [00:59<04:38,  7.53it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 430/2529 [00:59<04:34,  7.65it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 431/2529 [00:59<04:50,  7.23it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 432/2529 [00:59<05:19,  6.57it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 433/2529 [00:59<05:36,  6.23it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 435/2529 [01:00<04:46,  7.32it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 436/2529 [01:00<04:37,  7.55it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 437/2529 [01:00<04:29,  7.75it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 438/2529 [01:00<04:40,  7.46it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 439/2529 [01:00<05:05,  6.84it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 440/2529 [01:00<04:44,  7.34it/s]
Processing: positive r2g, BASC binarized:  17%|█▋        | 442/2529 [01:00<04:25,  7.85it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 444/2529 [01:01<04:32,  7.65it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 446/2529 [01:01<04:40,  7.43it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 447/2529 [01:01<05:32,  6.26it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 448/2529 [01:01<05:05,  6.81it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 449/2529 [01:02<05:42,  6.07it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 450/2529 [01:02<06:21,  5.45it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 452/2529 [01:02<06:19,  5.48it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 453/2529 [01:02<06:16,  5.51it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 455/2529 [01:03<05:04,  6.81it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 456/2529 [01:03<05:55,  5.83it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 457/2529 [01:03<06:05,  5.67it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 458/2529 [01:03<05:39,  6.09it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 459/2529 [01:03<06:11,  5.58it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 460/2529 [01:04<05:53,  5.85it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 461/2529 [01:04<05:21,  6.44it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 462/2529 [01:04<04:49,  7.15it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 463/2529 [01:04<04:48,  7.17it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 464/2529 [01:04<05:05,  6.76it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 466/2529 [01:04<04:54,  7.00it/s]
Processing: positive r2g, BASC binarized:  18%|█▊        | 467/2529 [01:05<05:11,  6.61it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 468/2529 [01:05<05:25,  6.33it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 469/2529 [01:05<05:28,  6.26it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 470/2529 [01:05<06:10,  5.56it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 471/2529 [01:05<06:18,  5.44it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 472/2529 [01:06<06:49,  5.03it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 473/2529 [01:06<05:50,  5.86it/s]
Processing: positive r2g, BASC binarized:  19%|█▊        | 474/2529 [01:06<05:52,  5.83it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 475/2529 [01:06<05:22,  6.37it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 476/2529 [01:06<04:49,  7.09it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 477/2529 [01:06<05:12,  6.57it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 478/2529 [01:06<04:50,  7.06it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 479/2529 [01:06<04:39,  7.35it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 480/2529 [01:07<04:26,  7.68it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 481/2529 [01:07<05:03,  6.74it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 482/2529 [01:07<05:26,  6.26it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 483/2529 [01:07<04:59,  6.83it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 484/2529 [01:07<04:40,  7.30it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 485/2529 [01:07<04:31,  7.54it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 487/2529 [01:07<03:54,  8.72it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 489/2529 [01:08<03:35,  9.48it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 491/2529 [01:08<03:37,  9.38it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 492/2529 [01:08<03:41,  9.22it/s]
Processing: positive r2g, BASC binarized:  19%|█▉        | 493/2529 [01:08<03:53,  8.70it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 494/2529 [01:08<03:54,  8.68it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 495/2529 [01:08<03:51,  8.78it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 496/2529 [01:08<03:52,  8.75it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 498/2529 [01:09<03:45,  9.02it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 500/2529 [01:09<03:33,  9.53it/s]

Processing: positive r2g, BASC binarized:  20%|█▉        | 501/2529 [01:09<03:33,  9.51it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 503/2529 [01:09<03:46,  8.95it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 504/2529 [01:09<03:45,  8.99it/s]
Processing: positive r2g, BASC binarized:  20%|█▉        | 505/2529 [01:09<03:47,  8.91it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 506/2529 [01:10<03:45,  8.99it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 507/2529 [01:10<04:22,  7.71it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 508/2529 [01:10<04:14,  7.95it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 509/2529 [01:10<04:02,  8.34it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 510/2529 [01:10<04:23,  7.66it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 511/2529 [01:10<04:31,  7.43it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 512/2529 [01:10<04:15,  7.88it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 513/2529 [01:11<05:15,  6.40it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 515/2529 [01:11<04:18,  7.80it/s]
Processing: positive r2g, BASC binarized:  20%|██        | 517/2529 [01:11<03:48,  8.80it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 519/2529 [01:11<03:31,  9.49it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 521/2529 [01:11<03:50,  8.73it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 522/2529 [01:12<03:50,  8.70it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 523/2529 [01:12<03:54,  8.54it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 524/2529 [01:12<04:45,  7.02it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 525/2529 [01:12<05:10,  6.44it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 526/2529 [01:12<04:42,  7.09it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 528/2529 [01:12<04:01,  8.28it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 530/2529 [01:13<03:46,  8.81it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 532/2529 [01:13<03:32,  9.39it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 534/2529 [01:13<03:21,  9.89it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 536/2529 [01:13<03:44,  8.88it/s]
Processing: positive r2g, BASC binarized:  21%|██        | 537/2529 [01:13<03:46,  8.81it/s]
Processing: positive r2g, BASC binarized:  21%|██▏       | 538/2529 [01:14<04:45,  6.99it/s]
Processing: positive r2g, BASC binarized:  21%|██▏       | 540/2529 [01:14<04:16,  7.76it/s]
Processing: positive r2g, BASC binarized:  21%|██▏       | 541/2529 [01:14<04:17,  7.73it/s]
Processing: positive r2g, BASC binarized:  21%|██▏       | 542/2529 [01:14<04:52,  6.79it/s]
Processing: positive r2g, BASC binarized:  21%|██▏       | 543/2529 [01:14<04:42,  7.03it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 544/2529 [01:14<04:51,  6.81it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 545/2529 [01:15<04:34,  7.22it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 547/2529 [01:15<03:56,  8.37it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 549/2529 [01:15<03:43,  8.84it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 551/2529 [01:15<03:35,  9.19it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 552/2529 [01:15<03:35,  9.18it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 553/2529 [01:15<03:31,  9.34it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 554/2529 [01:15<03:55,  8.40it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 555/2529 [01:16<03:52,  8.50it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 557/2529 [01:16<03:47,  8.66it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 558/2529 [01:16<03:45,  8.74it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 559/2529 [01:16<03:49,  8.58it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 560/2529 [01:16<04:02,  8.12it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 561/2529 [01:16<04:00,  8.19it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 562/2529 [01:16<04:01,  8.14it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 564/2529 [01:17<03:39,  8.96it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 566/2529 [01:17<03:31,  9.28it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 567/2529 [01:17<04:10,  7.82it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 568/2529 [01:17<04:03,  8.04it/s]
Processing: positive r2g, BASC binarized:  22%|██▏       | 569/2529 [01:17<04:01,  8.12it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 570/2529 [01:17<04:15,  7.67it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 571/2529 [01:18<04:07,  7.91it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 572/2529 [01:18<04:20,  7.52it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 573/2529 [01:18<04:08,  7.87it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 574/2529 [01:18<04:37,  7.05it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 575/2529 [01:18<04:52,  6.67it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 576/2529 [01:18<04:30,  7.22it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 577/2529 [01:18<05:06,  6.37it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 578/2529 [01:19<05:24,  6.01it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 579/2529 [01:19<04:58,  6.53it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 580/2529 [01:19<04:34,  7.11it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 581/2529 [01:19<04:17,  7.57it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 582/2529 [01:19<04:05,  7.92it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 583/2529 [01:19<04:05,  7.94it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 584/2529 [01:19<04:29,  7.23it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 585/2529 [01:20<04:23,  7.37it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 586/2529 [01:20<04:05,  7.93it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 587/2529 [01:20<03:55,  8.25it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 588/2529 [01:20<03:55,  8.26it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 589/2529 [01:20<03:42,  8.70it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 590/2529 [01:20<03:47,  8.51it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 591/2529 [01:20<04:14,  7.63it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 592/2529 [01:20<04:21,  7.41it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 593/2529 [01:21<04:04,  7.93it/s]
Processing: positive r2g, BASC binarized:  23%|██▎       | 594/2529 [01:21<03:54,  8.27it/s]
Processing: positive r2g, BASC binarized:  24%|██▎       | 595/2529 [01:21<03:50,  8.39it/s]
Processing: positive r2g, BASC binarized:  24%|██▎       | 597/2529 [01:21<03:25,  9.38it/s]
Processing: positive r2g, BASC binarized:  24%|██▎       | 598/2529 [01:21<04:18,  7.48it/s]
Processing: positive r2g, BASC binarized:  24%|██▎       | 599/2529 [01:21<04:07,  7.80it/s]
Processing: positive r2g, BASC binarized:  24%|██▎       | 600/2529 [01:21<03:53,  8.25it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 601/2529 [01:21<04:11,  7.67it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 602/2529 [01:22<04:14,  7.58it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 603/2529 [01:22<04:50,  6.63it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 604/2529 [01:22<06:26,  4.98it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 605/2529 [01:22<05:55,  5.42it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 606/2529 [01:22<05:54,  5.42it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 607/2529 [01:23<06:00,  5.33it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 608/2529 [01:23<06:03,  5.29it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 609/2529 [01:23<05:36,  5.70it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 610/2529 [01:23<05:01,  6.37it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 611/2529 [01:23<04:33,  7.00it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 612/2529 [01:23<04:55,  6.48it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 613/2529 [01:24<04:25,  7.21it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 614/2529 [01:24<04:09,  7.67it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 615/2529 [01:24<04:27,  7.15it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 616/2529 [01:24<04:08,  7.71it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 617/2529 [01:24<04:20,  7.35it/s]
Processing: positive r2g, BASC binarized:  24%|██▍       | 618/2529 [01:24<04:02,  7.89it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 620/2529 [01:24<03:53,  8.19it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 621/2529 [01:25<03:58,  8.02it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 622/2529 [01:25<04:09,  7.66it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 623/2529 [01:25<04:10,  7.60it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 624/2529 [01:25<04:27,  7.12it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 625/2529 [01:25<04:16,  7.43it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 626/2529 [01:25<04:09,  7.64it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 627/2529 [01:25<04:04,  7.79it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 629/2529 [01:26<03:35,  8.83it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 630/2529 [01:26<03:33,  8.90it/s]
Processing: positive r2g, BASC binarized:  25%|██▍       | 631/2529 [01:26<03:27,  9.13it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 633/2529 [01:26<03:22,  9.37it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 634/2529 [01:26<03:26,  9.20it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 636/2529 [01:26<03:20,  9.45it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 637/2529 [01:27<04:28,  7.04it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 638/2529 [01:27<04:46,  6.61it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 639/2529 [01:27<04:58,  6.33it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 641/2529 [01:27<04:13,  7.44it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 642/2529 [01:27<04:11,  7.51it/s]
Processing: positive r2g, BASC binarized:  25%|██▌       | 643/2529 [01:27<04:03,  7.74it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 645/2529 [01:28<03:37,  8.65it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 646/2529 [01:28<03:31,  8.90it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 647/2529 [01:28<03:42,  8.44it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 649/2529 [01:28<03:30,  8.93it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 650/2529 [01:28<03:29,  8.95it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 651/2529 [01:28<04:05,  7.64it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 652/2529 [01:28<03:57,  7.91it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 653/2529 [01:28<03:44,  8.34it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 655/2529 [01:29<03:30,  8.89it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 656/2529 [01:29<03:58,  7.86it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 657/2529 [01:29<04:00,  7.79it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 658/2529 [01:29<04:35,  6.80it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 659/2529 [01:29<04:23,  7.09it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 660/2529 [01:30<04:54,  6.36it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 662/2529 [01:30<04:00,  7.76it/s]
Processing: positive r2g, BASC binarized:  26%|██▌       | 663/2529 [01:30<04:04,  7.64it/s]
Processing: positive r2g, BASC binarized:  26%|██▋       | 665/2529 [01:30<03:55,  7.93it/s]
Processing: positive r2g, BASC binarized:  26%|██▋       | 666/2529 [01:30<04:03,  7.65it/s]
Processing: positive r2g, BASC binarized:  26%|██▋       | 667/2529 [01:30<03:50,  8.09it/s]
Processing: positive r2g, BASC binarized:  26%|██▋       | 669/2529 [01:31<03:29,  8.90it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 671/2529 [01:31<03:22,  9.19it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 672/2529 [01:31<03:45,  8.23it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 673/2529 [01:31<03:41,  8.39it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 674/2529 [01:31<03:37,  8.51it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 675/2529 [01:31<03:34,  8.63it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 676/2529 [01:31<03:38,  8.50it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 677/2529 [01:32<03:59,  7.73it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 678/2529 [01:32<03:53,  7.91it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 679/2529 [01:32<04:03,  7.59it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 680/2529 [01:32<03:59,  7.73it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 681/2529 [01:32<03:52,  7.95it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 682/2529 [01:32<03:50,  8.00it/s]

Processing: positive r2g, BASC binarized:  27%|██▋       | 683/2529 [01:32<03:45,  8.18it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 684/2529 [01:32<04:03,  7.58it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 685/2529 [01:33<04:03,  7.58it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 686/2529 [01:33<03:59,  7.70it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 687/2529 [01:33<03:51,  7.96it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 688/2529 [01:33<03:56,  7.80it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 689/2529 [01:33<04:15,  7.21it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 690/2529 [01:33<05:41,  5.39it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 691/2529 [01:34<06:40,  4.59it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 692/2529 [01:34<06:58,  4.39it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 693/2529 [01:34<07:10,  4.27it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 694/2529 [01:34<07:18,  4.19it/s]
Processing: positive r2g, BASC binarized:  27%|██▋       | 695/2529 [01:35<06:36,  4.63it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 696/2529 [01:35<06:15,  4.88it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 697/2529 [01:35<06:01,  5.06it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 698/2529 [01:35<05:53,  5.18it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 699/2529 [01:35<05:30,  5.53it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 700/2529 [01:36<05:57,  5.12it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 701/2529 [01:36<06:04,  5.01it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 702/2529 [01:36<06:03,  5.03it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 703/2529 [01:36<05:12,  5.85it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 704/2529 [01:36<05:16,  5.76it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 705/2529 [01:36<05:12,  5.85it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 707/2529 [01:37<04:34,  6.63it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 708/2529 [01:37<04:12,  7.22it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 709/2529 [01:37<04:44,  6.40it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 710/2529 [01:37<04:22,  6.92it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 711/2529 [01:37<04:06,  7.37it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 712/2529 [01:37<04:25,  6.84it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 713/2529 [01:37<04:35,  6.59it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 714/2529 [01:38<05:30,  5.48it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 715/2529 [01:38<05:13,  5.78it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 716/2529 [01:38<06:06,  4.94it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 717/2529 [01:38<05:22,  5.61it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 718/2529 [01:38<05:08,  5.87it/s]
Processing: positive r2g, BASC binarized:  28%|██▊       | 719/2529 [01:39<05:12,  5.79it/s]
Processing: positive r2g, BASC binarized:  29%|██▊       | 721/2529 [01:39<04:20,  6.94it/s]
Processing: positive r2g, BASC binarized:  29%|██▊       | 723/2529 [01:39<04:09,  7.23it/s]
Processing: positive r2g, BASC binarized:  29%|██▊       | 725/2529 [01:39<03:40,  8.20it/s]
Processing: positive r2g, BASC binarized:  29%|██▊       | 727/2529 [01:39<03:23,  8.85it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 728/2529 [01:40<03:36,  8.32it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 730/2529 [01:40<03:25,  8.75it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 732/2529 [01:40<03:11,  9.38it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 734/2529 [01:40<04:15,  7.03it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 736/2529 [01:41<04:17,  6.96it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 737/2529 [01:41<05:00,  5.96it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 738/2529 [01:41<05:16,  5.66it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 740/2529 [01:41<04:32,  6.56it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 741/2529 [01:42<04:17,  6.94it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 742/2529 [01:42<04:09,  7.18it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 744/2529 [01:42<03:43,  7.99it/s]
Processing: positive r2g, BASC binarized:  29%|██▉       | 745/2529 [01:42<04:09,  7.15it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 747/2529 [01:42<03:59,  7.44it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 748/2529 [01:42<04:06,  7.22it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 749/2529 [01:43<04:43,  6.28it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 750/2529 [01:43<04:20,  6.82it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 751/2529 [01:43<04:01,  7.36it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 752/2529 [01:43<04:56,  5.98it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 753/2529 [01:43<04:50,  6.12it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 755/2529 [01:44<04:31,  6.52it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 756/2529 [01:44<04:28,  6.61it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 757/2529 [01:44<04:15,  6.92it/s]
Processing: positive r2g, BASC binarized:  30%|██▉       | 758/2529 [01:44<04:06,  7.19it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 760/2529 [01:44<03:29,  8.46it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 762/2529 [01:44<03:24,  8.65it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 764/2529 [01:45<03:13,  9.12it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 766/2529 [01:45<03:29,  8.40it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 767/2529 [01:45<03:49,  7.66it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 769/2529 [01:45<03:24,  8.60it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 770/2529 [01:45<03:21,  8.72it/s]
Processing: positive r2g, BASC binarized:  30%|███       | 771/2529 [01:45<03:21,  8.73it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 773/2529 [01:46<03:09,  9.26it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 775/2529 [01:46<03:04,  9.49it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 776/2529 [01:46<03:12,  9.12it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 778/2529 [01:46<03:30,  8.30it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 780/2529 [01:46<03:21,  8.68it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 781/2529 [01:47<03:26,  8.47it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 782/2529 [01:47<03:47,  7.69it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 783/2529 [01:47<03:41,  7.88it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 784/2529 [01:47<03:38,  7.99it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 785/2529 [01:47<03:41,  7.86it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 786/2529 [01:47<03:40,  7.90it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 787/2529 [01:47<04:24,  6.60it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 788/2529 [01:48<04:13,  6.88it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 789/2529 [01:48<04:26,  6.53it/s]
Processing: positive r2g, BASC binarized:  31%|███       | 790/2529 [01:48<04:42,  6.16it/s]
Processing: positive r2g, BASC binarized:  31%|███▏      | 791/2529 [01:48<05:42,  5.07it/s]
Processing: positive r2g, BASC binarized:  31%|███▏      | 792/2529 [01:48<05:01,  5.77it/s]
Processing: positive r2g, BASC binarized:  31%|███▏      | 794/2529 [01:49<04:05,  7.08it/s]
Processing: positive r2g, BASC binarized:  31%|███▏      | 796/2529 [01:49<04:47,  6.02it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 797/2529 [01:49<04:58,  5.80it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 798/2529 [01:49<04:59,  5.79it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 800/2529 [01:50<04:09,  6.92it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 801/2529 [01:50<03:58,  7.26it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 802/2529 [01:50<03:51,  7.46it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 803/2529 [01:50<03:46,  7.63it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 804/2529 [01:50<05:26,  5.29it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 805/2529 [01:50<04:46,  6.03it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 806/2529 [01:51<04:54,  5.85it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 807/2529 [01:51<05:31,  5.19it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 808/2529 [01:51<05:10,  5.54it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 809/2529 [01:51<04:37,  6.20it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 810/2529 [01:51<04:11,  6.84it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 811/2529 [01:51<03:56,  7.25it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 812/2529 [01:51<03:52,  7.38it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 813/2529 [01:52<03:41,  7.75it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 815/2529 [01:52<03:58,  7.19it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 816/2529 [01:52<03:42,  7.69it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 817/2529 [01:52<03:44,  7.61it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 818/2529 [01:52<03:44,  7.62it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 819/2529 [01:52<04:01,  7.10it/s]
Processing: positive r2g, BASC binarized:  32%|███▏      | 821/2529 [01:53<03:47,  7.52it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 823/2529 [01:53<03:21,  8.45it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 824/2529 [01:53<03:20,  8.52it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 825/2529 [01:53<03:44,  7.58it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 826/2529 [01:53<03:37,  7.84it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 827/2529 [01:54<04:42,  6.02it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 828/2529 [01:54<05:09,  5.50it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 829/2529 [01:54<04:38,  6.11it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 830/2529 [01:54<04:17,  6.59it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 832/2529 [01:54<03:40,  7.68it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 833/2529 [01:54<03:28,  8.13it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 834/2529 [01:54<03:53,  7.26it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 836/2529 [01:55<03:48,  7.42it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 837/2529 [01:55<03:36,  7.83it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 839/2529 [01:55<03:16,  8.62it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 840/2529 [01:55<03:27,  8.12it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 842/2529 [01:55<03:13,  8.70it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 843/2529 [01:55<03:12,  8.74it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 845/2529 [01:56<03:16,  8.58it/s]
Processing: positive r2g, BASC binarized:  33%|███▎      | 846/2529 [01:56<03:23,  8.28it/s]
Processing: positive r2g, BASC binarized:  34%|███▎      | 848/2529 [01:56<03:22,  8.29it/s]
Processing: positive r2g, BASC binarized:  34%|███▎      | 850/2529 [01:56<03:24,  8.20it/s]
Processing: positive r2g, BASC binarized:  34%|███▎      | 851/2529 [01:56<03:21,  8.34it/s]
Processing: positive r2g, BASC binarized:  34%|███▎      | 852/2529 [01:57<03:16,  8.55it/s]
Processing: positive r2g, BASC binarized:  34%|███▎      | 853/2529 [01:57<03:11,  8.76it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 854/2529 [01:57<03:07,  8.92it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 856/2529 [01:57<02:59,  9.30it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 857/2529 [01:57<02:57,  9.43it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 859/2529 [01:57<02:51,  9.76it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 860/2529 [01:57<02:54,  9.55it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 861/2529 [01:57<02:53,  9.63it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 862/2529 [01:58<02:54,  9.56it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 863/2529 [01:58<03:11,  8.68it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 864/2529 [01:58<03:07,  8.87it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 866/2529 [01:58<02:51,  9.70it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 868/2529 [01:58<02:52,  9.63it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 869/2529 [01:58<02:53,  9.57it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 870/2529 [01:58<02:55,  9.45it/s]
Processing: positive r2g, BASC binarized:  34%|███▍      | 872/2529 [01:59<02:56,  9.40it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 873/2529 [01:59<02:54,  9.48it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 874/2529 [01:59<03:20,  8.27it/s]

Processing: positive r2g, BASC binarized:  35%|███▍      | 875/2529 [01:59<03:14,  8.52it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 877/2529 [01:59<02:55,  9.43it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 878/2529 [01:59<03:13,  8.55it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 879/2529 [02:00<03:26,  7.99it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 880/2529 [02:00<03:21,  8.20it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 882/2529 [02:00<03:40,  7.47it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 883/2529 [02:00<03:32,  7.75it/s]
Processing: positive r2g, BASC binarized:  35%|███▍      | 885/2529 [02:00<03:10,  8.64it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 886/2529 [02:00<03:10,  8.63it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 887/2529 [02:00<03:08,  8.70it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 888/2529 [02:01<03:03,  8.94it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 890/2529 [02:01<02:49,  9.69it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 892/2529 [02:01<03:08,  8.68it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 894/2529 [02:01<02:55,  9.32it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 895/2529 [02:01<02:58,  9.14it/s]
Processing: positive r2g, BASC binarized:  35%|███▌      | 896/2529 [02:01<03:01,  9.00it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 898/2529 [02:02<02:48,  9.70it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 900/2529 [02:02<03:09,  8.58it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 901/2529 [02:02<03:22,  8.06it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 902/2529 [02:02<03:51,  7.03it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 903/2529 [02:02<03:36,  7.51it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 904/2529 [02:03<03:34,  7.57it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 905/2529 [02:03<03:23,  7.98it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 907/2529 [02:03<03:02,  8.87it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 908/2529 [02:03<03:03,  8.81it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 909/2529 [02:03<03:15,  8.30it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 911/2529 [02:03<02:56,  9.15it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 912/2529 [02:03<03:24,  7.89it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 914/2529 [02:04<03:05,  8.71it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 915/2529 [02:04<03:12,  8.37it/s]
Processing: positive r2g, BASC binarized:  36%|███▌      | 916/2529 [02:04<03:07,  8.61it/s]
Processing: positive r2g, BASC binarized:  36%|███▋      | 918/2529 [02:04<03:24,  7.89it/s]
Processing: positive r2g, BASC binarized:  36%|███▋      | 919/2529 [02:04<03:25,  7.82it/s]
Processing: positive r2g, BASC binarized:  36%|███▋      | 921/2529 [02:04<03:03,  8.75it/s]
Processing: positive r2g, BASC binarized:  36%|███▋      | 923/2529 [02:05<02:50,  9.44it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 925/2529 [02:05<02:45,  9.70it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 927/2529 [02:05<02:39, 10.04it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 929/2529 [02:05<02:36, 10.20it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 931/2529 [02:05<02:47,  9.57it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 933/2529 [02:06<03:16,  8.14it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 935/2529 [02:06<03:11,  8.31it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 936/2529 [02:06<03:29,  7.60it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 938/2529 [02:06<03:10,  8.36it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 939/2529 [02:07<03:29,  7.59it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 940/2529 [02:07<03:28,  7.60it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 941/2529 [02:07<03:58,  6.66it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 942/2529 [02:07<04:19,  6.12it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 943/2529 [02:07<04:00,  6.59it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 945/2529 [02:07<03:19,  7.93it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 947/2529 [02:08<02:59,  8.79it/s]
Processing: positive r2g, BASC binarized:  37%|███▋      | 948/2529 [02:08<03:07,  8.43it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 949/2529 [02:08<03:05,  8.52it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 950/2529 [02:08<03:03,  8.59it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 952/2529 [02:08<02:54,  9.03it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 953/2529 [02:08<03:21,  7.84it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 954/2529 [02:08<03:17,  7.99it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 955/2529 [02:09<03:38,  7.20it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 956/2529 [02:09<03:28,  7.56it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 957/2529 [02:09<03:18,  7.91it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 958/2529 [02:09<03:13,  8.13it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 960/2529 [02:09<02:55,  8.96it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 962/2529 [02:09<02:45,  9.47it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 964/2529 [02:10<02:36, 10.00it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 966/2529 [02:10<03:03,  8.52it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 967/2529 [02:10<03:10,  8.21it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 969/2529 [02:10<02:54,  8.93it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 970/2529 [02:10<02:56,  8.86it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 972/2529 [02:11<02:44,  9.47it/s]
Processing: positive r2g, BASC binarized:  38%|███▊      | 973/2529 [02:11<02:52,  9.04it/s]
Processing: positive r2g, BASC binarized:  39%|███▊      | 975/2529 [02:11<02:42,  9.55it/s]
Processing: positive r2g, BASC binarized:  39%|███▊      | 976/2529 [02:11<02:52,  9.03it/s]
Processing: positive r2g, BASC binarized:  39%|███▊      | 977/2529 [02:11<02:52,  9.02it/s]
Processing: positive r2g, BASC binarized:  39%|███▊      | 978/2529 [02:11<03:32,  7.28it/s]
Processing: positive r2g, BASC binarized:  39%|███▊      | 979/2529 [02:11<03:22,  7.66it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 980/2529 [02:12<03:15,  7.92it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 981/2529 [02:12<03:10,  8.11it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 983/2529 [02:12<03:19,  7.74it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 984/2529 [02:12<03:09,  8.14it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 986/2529 [02:12<03:09,  8.13it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 987/2529 [02:12<03:06,  8.27it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 988/2529 [02:12<03:07,  8.23it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 990/2529 [02:13<02:49,  9.08it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 991/2529 [02:13<02:48,  9.11it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 992/2529 [02:13<02:51,  8.95it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 993/2529 [02:13<03:06,  8.26it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 994/2529 [02:13<03:03,  8.36it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 996/2529 [02:13<02:46,  9.19it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 997/2529 [02:13<02:46,  9.21it/s]
Processing: positive r2g, BASC binarized:  39%|███▉      | 998/2529 [02:14<02:52,  8.86it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1000/2529 [02:14<02:39,  9.60it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1002/2529 [02:14<02:32, 10.00it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1003/2529 [02:14<02:41,  9.46it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1005/2529 [02:14<02:57,  8.58it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1007/2529 [02:15<02:45,  9.21it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1008/2529 [02:15<03:17,  7.71it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1009/2529 [02:15<03:07,  8.10it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1010/2529 [02:15<03:27,  7.34it/s]
Processing: positive r2g, BASC binarized:  40%|███▉      | 1011/2529 [02:15<03:13,  7.86it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1012/2529 [02:15<03:09,  8.01it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1013/2529 [02:15<03:35,  7.02it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1015/2529 [02:16<03:47,  6.66it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1016/2529 [02:16<03:50,  6.57it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1017/2529 [02:16<03:36,  7.00it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1019/2529 [02:16<03:09,  7.96it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1021/2529 [02:16<02:51,  8.80it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1022/2529 [02:17<02:51,  8.78it/s]
Processing: positive r2g, BASC binarized:  40%|████      | 1023/2529 [02:17<02:51,  8.77it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1025/2529 [02:17<02:41,  9.32it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1026/2529 [02:17<03:05,  8.10it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1028/2529 [02:17<03:09,  7.93it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1030/2529 [02:17<02:49,  8.83it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1031/2529 [02:18<02:45,  9.04it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1033/2529 [02:18<02:46,  9.00it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1035/2529 [02:18<02:36,  9.56it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1037/2529 [02:18<02:37,  9.50it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1038/2529 [02:18<02:53,  8.59it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1040/2529 [02:19<02:45,  9.00it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1041/2529 [02:19<02:50,  8.74it/s]
Processing: positive r2g, BASC binarized:  41%|████      | 1042/2529 [02:19<02:47,  8.86it/s]
Processing: positive r2g, BASC binarized:  41%|████▏     | 1044/2529 [02:19<02:50,  8.72it/s]
Processing: positive r2g, BASC binarized:  41%|████▏     | 1045/2529 [02:19<02:52,  8.60it/s]
Processing: positive r2g, BASC binarized:  41%|████▏     | 1046/2529 [02:19<02:54,  8.49it/s]
Processing: positive r2g, BASC binarized:  41%|████▏     | 1048/2529 [02:19<02:46,  8.91it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1050/2529 [02:20<03:10,  7.76it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1051/2529 [02:20<03:05,  7.97it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1052/2529 [02:20<03:22,  7.28it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1053/2529 [02:20<03:25,  7.19it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1055/2529 [02:20<02:59,  8.21it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1057/2529 [02:21<02:54,  8.43it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1059/2529 [02:21<02:50,  8.62it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1061/2529 [02:21<02:39,  9.18it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1063/2529 [02:21<02:33,  9.56it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1064/2529 [02:21<02:32,  9.58it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1065/2529 [02:22<02:57,  8.24it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1067/2529 [02:22<02:52,  8.49it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1068/2529 [02:22<02:56,  8.27it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1069/2529 [02:22<02:49,  8.61it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1071/2529 [02:22<02:37,  9.29it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1072/2529 [02:22<02:36,  9.30it/s]
Processing: positive r2g, BASC binarized:  42%|████▏     | 1073/2529 [02:23<03:09,  7.68it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1075/2529 [02:23<03:01,  8.00it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1077/2529 [02:23<02:56,  8.24it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1079/2529 [02:23<02:46,  8.72it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1080/2529 [02:23<02:54,  8.32it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1081/2529 [02:23<02:47,  8.63it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1083/2529 [02:24<02:33,  9.41it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1084/2529 [02:24<02:31,  9.51it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1086/2529 [02:24<02:26,  9.86it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1087/2529 [02:24<02:29,  9.66it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1089/2529 [02:24<02:50,  8.44it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1090/2529 [02:24<02:45,  8.71it/s]

Processing: positive r2g, BASC binarized:  43%|████▎     | 1092/2529 [02:25<02:31,  9.46it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1093/2529 [02:25<02:39,  9.02it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1094/2529 [02:25<02:37,  9.09it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1096/2529 [02:25<02:35,  9.24it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1098/2529 [02:25<02:25,  9.82it/s]
Processing: positive r2g, BASC binarized:  43%|████▎     | 1100/2529 [02:25<02:19, 10.23it/s]
Processing: positive r2g, BASC binarized:  44%|████▎     | 1102/2529 [02:26<02:38,  9.02it/s]
Processing: positive r2g, BASC binarized:  44%|████▎     | 1103/2529 [02:26<02:55,  8.13it/s]
Processing: positive r2g, BASC binarized:  44%|████▎     | 1104/2529 [02:26<02:58,  7.99it/s]
Processing: positive r2g, BASC binarized:  44%|████▎     | 1106/2529 [02:26<02:42,  8.78it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1107/2529 [02:26<02:49,  8.39it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1109/2529 [02:26<02:34,  9.16it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1111/2529 [02:27<02:35,  9.14it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1113/2529 [02:27<02:29,  9.50it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1114/2529 [02:27<02:31,  9.32it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1116/2529 [02:27<02:37,  8.97it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1118/2529 [02:27<02:31,  9.31it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1120/2529 [02:28<02:31,  9.30it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1122/2529 [02:28<02:26,  9.59it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1123/2529 [02:28<02:27,  9.53it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1124/2529 [02:28<02:27,  9.56it/s]
Processing: positive r2g, BASC binarized:  44%|████▍     | 1125/2529 [02:28<02:32,  9.19it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1126/2529 [02:28<02:33,  9.14it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1127/2529 [02:28<02:52,  8.14it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1128/2529 [02:29<02:43,  8.56it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1129/2529 [02:29<03:15,  7.15it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1130/2529 [02:29<03:09,  7.40it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1131/2529 [02:29<03:00,  7.76it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1133/2529 [02:29<02:39,  8.76it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1134/2529 [02:29<03:01,  7.69it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1136/2529 [02:30<02:39,  8.72it/s]
Processing: positive r2g, BASC binarized:  45%|████▍     | 1138/2529 [02:30<02:29,  9.32it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1140/2529 [02:30<02:22,  9.75it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1141/2529 [02:30<02:27,  9.42it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1142/2529 [02:30<02:31,  9.14it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1143/2529 [02:30<02:33,  9.01it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1144/2529 [02:30<02:34,  8.95it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1146/2529 [02:31<02:35,  8.88it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1148/2529 [02:31<02:22,  9.69it/s]
Processing: positive r2g, BASC binarized:  45%|████▌     | 1150/2529 [02:31<02:36,  8.81it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1151/2529 [02:31<02:33,  9.00it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1152/2529 [02:31<02:52,  7.97it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1153/2529 [02:31<02:46,  8.28it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1155/2529 [02:32<02:35,  8.83it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1156/2529 [02:32<02:35,  8.82it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1158/2529 [02:32<02:39,  8.59it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1159/2529 [02:32<02:43,  8.38it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1161/2529 [02:32<02:28,  9.18it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1162/2529 [02:32<02:26,  9.31it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1163/2529 [02:33<02:48,  8.12it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1165/2529 [02:33<02:32,  8.97it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1167/2529 [02:33<02:26,  9.27it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1168/2529 [02:33<02:26,  9.31it/s]
Processing: positive r2g, BASC binarized:  46%|████▌     | 1169/2529 [02:33<02:24,  9.39it/s]
Processing: positive r2g, BASC binarized:  46%|████▋     | 1171/2529 [02:33<02:24,  9.41it/s]
Processing: positive r2g, BASC binarized:  46%|████▋     | 1172/2529 [02:34<02:31,  8.98it/s]
Processing: positive r2g, BASC binarized:  46%|████▋     | 1173/2529 [02:34<02:27,  9.18it/s]
Processing: positive r2g, BASC binarized:  46%|████▋     | 1175/2529 [02:34<02:31,  8.92it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1177/2529 [02:34<02:22,  9.50it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1179/2529 [02:34<02:15,  9.93it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1180/2529 [02:34<02:16,  9.91it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1182/2529 [02:35<02:14, 10.00it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1184/2529 [02:35<02:16,  9.85it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1186/2529 [02:35<02:12, 10.15it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1188/2529 [02:35<02:11, 10.16it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1190/2529 [02:35<02:30,  8.87it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1192/2529 [02:36<02:29,  8.95it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1193/2529 [02:36<02:47,  8.00it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1194/2529 [02:36<02:40,  8.31it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1195/2529 [02:36<02:56,  7.55it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1196/2529 [02:36<02:48,  7.92it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1197/2529 [02:36<03:02,  7.30it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1199/2529 [02:37<02:52,  7.72it/s]
Processing: positive r2g, BASC binarized:  47%|████▋     | 1201/2529 [02:37<02:35,  8.53it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1202/2529 [02:37<02:44,  8.08it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1203/2529 [02:37<02:37,  8.44it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1205/2529 [02:37<02:25,  9.12it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1207/2529 [02:38<02:35,  8.49it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1209/2529 [02:38<02:29,  8.85it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1210/2529 [02:38<02:38,  8.31it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1211/2529 [02:38<02:33,  8.61it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1212/2529 [02:38<02:28,  8.85it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1213/2529 [02:38<02:35,  8.47it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1215/2529 [02:38<02:26,  8.99it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1216/2529 [02:39<02:31,  8.66it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1217/2529 [02:39<02:29,  8.75it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1218/2529 [02:39<02:25,  9.03it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1219/2529 [02:39<02:40,  8.14it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1221/2529 [02:39<02:28,  8.81it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1222/2529 [02:39<02:34,  8.47it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1223/2529 [02:39<02:31,  8.63it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1224/2529 [02:39<02:34,  8.42it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1225/2529 [02:40<02:29,  8.75it/s]
Processing: positive r2g, BASC binarized:  48%|████▊     | 1226/2529 [02:40<02:31,  8.58it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1227/2529 [02:40<02:37,  8.29it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1228/2529 [02:40<02:37,  8.24it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1229/2529 [02:40<02:34,  8.41it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1230/2529 [02:40<02:31,  8.59it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1231/2529 [02:40<02:30,  8.63it/s]
Processing: positive r2g, BASC binarized:  49%|████▊     | 1232/2529 [02:40<02:59,  7.22it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1234/2529 [02:41<02:33,  8.43it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1235/2529 [02:41<02:30,  8.59it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1236/2529 [02:41<02:28,  8.68it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1237/2529 [02:41<02:31,  8.54it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1239/2529 [02:41<02:27,  8.74it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1241/2529 [02:42<02:54,  7.39it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1242/2529 [02:42<03:15,  6.57it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1243/2529 [02:42<03:26,  6.23it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1244/2529 [02:42<03:35,  5.96it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1245/2529 [02:42<03:47,  5.65it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1246/2529 [02:43<03:31,  6.05it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1247/2529 [02:43<03:26,  6.21it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1248/2529 [02:43<03:31,  6.06it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1249/2529 [02:43<03:16,  6.52it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1250/2529 [02:43<03:04,  6.94it/s]
Processing: positive r2g, BASC binarized:  49%|████▉     | 1251/2529 [02:43<02:50,  7.48it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1252/2529 [02:43<02:41,  7.90it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1254/2529 [02:44<02:26,  8.70it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1255/2529 [02:44<03:12,  6.64it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1256/2529 [02:44<03:22,  6.29it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1257/2529 [02:44<03:29,  6.06it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1258/2529 [02:44<03:35,  5.89it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1259/2529 [02:44<03:14,  6.53it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1260/2529 [02:45<02:58,  7.10it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1261/2529 [02:45<02:48,  7.51it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1262/2529 [02:45<02:42,  7.79it/s]
Processing: positive r2g, BASC binarized:  50%|████▉     | 1264/2529 [02:45<02:38,  7.96it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1265/2529 [02:45<02:48,  7.51it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1267/2529 [02:45<02:54,  7.23it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1268/2529 [02:46<02:48,  7.49it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1269/2529 [02:46<02:41,  7.82it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1270/2529 [02:46<02:37,  7.98it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1271/2529 [02:46<02:29,  8.41it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1272/2529 [02:46<02:32,  8.25it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1274/2529 [02:46<02:52,  7.28it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1275/2529 [02:47<03:15,  6.43it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1276/2529 [02:47<03:28,  6.01it/s]
Processing: positive r2g, BASC binarized:  50%|█████     | 1277/2529 [02:47<03:15,  6.39it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1278/2529 [02:47<03:05,  6.75it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1279/2529 [02:47<02:58,  6.99it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1280/2529 [02:47<02:52,  7.23it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1281/2529 [02:47<02:43,  7.63it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1283/2529 [02:48<02:31,  8.23it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1284/2529 [02:48<02:24,  8.59it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1286/2529 [02:48<02:16,  9.12it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1288/2529 [02:48<02:06,  9.82it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1290/2529 [02:48<02:06,  9.83it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1292/2529 [02:48<02:02, 10.07it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1294/2529 [02:49<02:06,  9.80it/s]
Processing: positive r2g, BASC binarized:  51%|█████     | 1296/2529 [02:49<02:05,  9.84it/s]

Processing: positive r2g, BASC binarized:  51%|█████▏    | 1297/2529 [02:49<02:08,  9.55it/s]
Processing: positive r2g, BASC binarized:  51%|█████▏    | 1299/2529 [02:49<02:15,  9.06it/s]
Processing: positive r2g, BASC binarized:  51%|█████▏    | 1300/2529 [02:49<02:20,  8.77it/s]
Processing: positive r2g, BASC binarized:  51%|█████▏    | 1301/2529 [02:50<02:36,  7.85it/s]
Processing: positive r2g, BASC binarized:  51%|█████▏    | 1302/2529 [02:50<02:33,  8.01it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1303/2529 [02:50<02:47,  7.34it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1304/2529 [02:50<02:40,  7.64it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1305/2529 [02:50<02:54,  7.02it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1306/2529 [02:50<02:56,  6.95it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1307/2529 [02:50<02:53,  7.05it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1308/2529 [02:51<02:40,  7.59it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1309/2529 [02:51<02:31,  8.05it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1310/2529 [02:51<02:25,  8.38it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1311/2529 [02:51<02:21,  8.62it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1313/2529 [02:51<02:09,  9.38it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1315/2529 [02:51<02:08,  9.43it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1316/2529 [02:51<02:09,  9.38it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1318/2529 [02:52<02:22,  8.50it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1319/2529 [02:52<02:36,  7.74it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1321/2529 [02:52<02:38,  7.60it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1322/2529 [02:52<02:33,  7.86it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1323/2529 [02:52<02:29,  8.05it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1324/2529 [02:52<02:26,  8.25it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1325/2529 [02:53<02:25,  8.25it/s]
Processing: positive r2g, BASC binarized:  52%|█████▏    | 1326/2529 [02:53<02:31,  7.97it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1328/2529 [02:53<02:24,  8.28it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1329/2529 [02:53<02:23,  8.34it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1330/2529 [02:53<02:21,  8.47it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1331/2529 [02:53<02:28,  8.05it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1332/2529 [02:53<02:45,  7.23it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1333/2529 [02:54<03:05,  6.46it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1334/2529 [02:54<02:57,  6.72it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1335/2529 [02:54<02:52,  6.92it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1336/2529 [02:54<02:51,  6.97it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1338/2529 [02:54<02:25,  8.19it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1340/2529 [02:54<02:08,  9.25it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1342/2529 [02:55<02:18,  8.56it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1344/2529 [02:55<02:14,  8.80it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1345/2529 [02:55<02:19,  8.51it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1346/2529 [02:55<02:18,  8.55it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1347/2529 [02:55<02:14,  8.78it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1348/2529 [02:56<03:15,  6.05it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1349/2529 [02:56<03:28,  5.65it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1350/2529 [02:56<03:45,  5.24it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1351/2529 [02:56<04:07,  4.75it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1352/2529 [02:56<03:33,  5.51it/s]
Processing: positive r2g, BASC binarized:  53%|█████▎    | 1353/2529 [02:57<03:42,  5.29it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1354/2529 [02:57<03:32,  5.52it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1355/2529 [02:57<03:30,  5.57it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1356/2529 [02:57<03:09,  6.20it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1357/2529 [02:57<03:16,  5.97it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1358/2529 [02:57<02:59,  6.53it/s]
Processing: positive r2g, BASC binarized:  54%|█████▎    | 1359/2529 [02:57<02:46,  7.04it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1360/2529 [02:58<02:37,  7.44it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1361/2529 [02:58<03:28,  5.61it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1362/2529 [02:58<03:42,  5.24it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1363/2529 [02:58<03:30,  5.54it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1364/2529 [02:58<03:35,  5.41it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1365/2529 [02:59<03:42,  5.23it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1366/2529 [02:59<03:56,  4.92it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1367/2529 [02:59<04:02,  4.80it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1368/2529 [02:59<04:03,  4.77it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1369/2529 [02:59<03:56,  4.90it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1370/2529 [03:00<04:03,  4.75it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1371/2529 [03:00<04:09,  4.65it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1372/2529 [03:00<04:02,  4.77it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1373/2529 [03:00<03:58,  4.85it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1374/2529 [03:00<03:29,  5.52it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1375/2529 [03:01<03:17,  5.83it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1376/2529 [03:01<03:16,  5.88it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1377/2529 [03:01<03:01,  6.34it/s]
Processing: positive r2g, BASC binarized:  54%|█████▍    | 1378/2529 [03:01<02:55,  6.57it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1379/2529 [03:01<03:27,  5.55it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1380/2529 [03:01<03:04,  6.22it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1381/2529 [03:02<03:15,  5.88it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1382/2529 [03:02<03:29,  5.48it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1383/2529 [03:02<03:05,  6.18it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1384/2529 [03:02<02:48,  6.79it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1386/2529 [03:02<02:20,  8.15it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1388/2529 [03:02<02:22,  8.01it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1389/2529 [03:03<03:01,  6.27it/s]
Processing: positive r2g, BASC binarized:  55%|█████▍    | 1390/2529 [03:03<03:20,  5.68it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1391/2529 [03:03<03:24,  5.56it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1392/2529 [03:03<03:34,  5.30it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1393/2529 [03:04<03:31,  5.38it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1394/2529 [03:04<03:43,  5.08it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1395/2529 [03:04<03:50,  4.91it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1396/2529 [03:04<03:46,  5.01it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1397/2529 [03:04<03:44,  5.04it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1398/2529 [03:05<03:30,  5.38it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1399/2529 [03:05<03:06,  6.05it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1400/2529 [03:05<02:48,  6.69it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1401/2529 [03:05<02:58,  6.30it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1402/2529 [03:05<03:08,  5.98it/s]
Processing: positive r2g, BASC binarized:  55%|█████▌    | 1403/2529 [03:05<02:46,  6.75it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1404/2529 [03:05<02:57,  6.36it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1406/2529 [03:06<02:57,  6.34it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1407/2529 [03:06<03:08,  5.96it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1408/2529 [03:06<03:11,  5.84it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1409/2529 [03:06<03:15,  5.72it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1410/2529 [03:06<03:17,  5.67it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1411/2529 [03:07<03:12,  5.80it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1412/2529 [03:07<03:02,  6.12it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1413/2529 [03:07<02:53,  6.44it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1414/2529 [03:07<02:39,  6.97it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1415/2529 [03:07<02:47,  6.66it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1416/2529 [03:07<02:37,  7.09it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1417/2529 [03:07<02:26,  7.58it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1418/2529 [03:08<02:22,  7.80it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1419/2529 [03:08<02:26,  7.59it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1420/2529 [03:08<02:21,  7.84it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1421/2529 [03:08<02:17,  8.03it/s]
Processing: positive r2g, BASC binarized:  56%|█████▌    | 1422/2529 [03:08<02:14,  8.21it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1423/2529 [03:08<02:20,  7.86it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1424/2529 [03:08<02:14,  8.20it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1425/2529 [03:08<02:39,  6.92it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1426/2529 [03:09<02:32,  7.23it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1427/2529 [03:09<02:35,  7.09it/s]
Processing: positive r2g, BASC binarized:  56%|█████▋    | 1428/2529 [03:09<02:29,  7.34it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1429/2529 [03:09<02:26,  7.51it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1430/2529 [03:09<02:19,  7.89it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1431/2529 [03:09<02:25,  7.56it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1432/2529 [03:09<02:19,  7.89it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1433/2529 [03:09<02:12,  8.29it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1434/2529 [03:10<02:21,  7.76it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1435/2529 [03:10<02:13,  8.18it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1436/2529 [03:10<02:10,  8.39it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1438/2529 [03:10<02:14,  8.13it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1439/2529 [03:10<02:35,  7.02it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1440/2529 [03:11<02:56,  6.18it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1441/2529 [03:11<02:45,  6.57it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1442/2529 [03:11<02:34,  7.03it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1443/2529 [03:11<02:28,  7.31it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1444/2529 [03:11<02:20,  7.71it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1445/2529 [03:11<02:15,  7.99it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1446/2529 [03:11<02:10,  8.31it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1447/2529 [03:11<02:06,  8.53it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1448/2529 [03:11<02:03,  8.76it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1449/2529 [03:12<02:13,  8.11it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1450/2529 [03:12<02:43,  6.60it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1451/2529 [03:12<02:54,  6.19it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1452/2529 [03:12<02:50,  6.31it/s]
Processing: positive r2g, BASC binarized:  57%|█████▋    | 1453/2529 [03:12<02:45,  6.51it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1455/2529 [03:12<02:15,  7.93it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1457/2529 [03:13<02:01,  8.79it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1458/2529 [03:13<02:05,  8.56it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1460/2529 [03:13<02:07,  8.37it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1461/2529 [03:13<02:08,  8.30it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1462/2529 [03:13<02:24,  7.41it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1463/2529 [03:13<02:18,  7.69it/s]

Processing: positive r2g, BASC binarized:  58%|█████▊    | 1465/2529 [03:14<02:01,  8.77it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1467/2529 [03:14<01:56,  9.13it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1468/2529 [03:14<01:56,  9.12it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1469/2529 [03:14<01:57,  9.05it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1470/2529 [03:14<02:00,  8.78it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1471/2529 [03:14<02:00,  8.78it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1472/2529 [03:14<01:57,  9.02it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1473/2529 [03:15<01:55,  9.13it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1475/2529 [03:15<01:49,  9.64it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1476/2529 [03:15<01:51,  9.42it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1477/2529 [03:15<01:54,  9.16it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1478/2529 [03:15<01:55,  9.07it/s]
Processing: positive r2g, BASC binarized:  58%|█████▊    | 1479/2529 [03:15<02:15,  7.77it/s]
Processing: positive r2g, BASC binarized:  59%|█████▊    | 1480/2529 [03:15<02:07,  8.21it/s]
Processing: positive r2g, BASC binarized:  59%|█████▊    | 1481/2529 [03:15<02:10,  8.03it/s]
Processing: positive r2g, BASC binarized:  59%|█████▊    | 1482/2529 [03:16<02:06,  8.29it/s]
Processing: positive r2g, BASC binarized:  59%|█████▊    | 1484/2529 [03:16<01:51,  9.41it/s]
Processing: positive r2g, BASC binarized:  59%|█████▊    | 1485/2529 [03:16<02:09,  8.05it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1486/2529 [03:16<02:24,  7.19it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1487/2529 [03:16<02:18,  7.55it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1489/2529 [03:17<02:19,  7.46it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1490/2529 [03:17<02:13,  7.76it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1491/2529 [03:17<02:11,  7.90it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1493/2529 [03:17<02:00,  8.58it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1495/2529 [03:17<01:52,  9.23it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1497/2529 [03:17<01:46,  9.69it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1499/2529 [03:18<01:49,  9.39it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1500/2529 [03:18<01:55,  8.92it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1502/2529 [03:18<01:48,  9.46it/s]
Processing: positive r2g, BASC binarized:  59%|█████▉    | 1504/2529 [03:18<01:45,  9.71it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1505/2529 [03:18<02:23,  7.11it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1506/2529 [03:18<02:19,  7.35it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1507/2529 [03:19<02:15,  7.56it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1508/2529 [03:19<02:17,  7.45it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1509/2529 [03:19<02:08,  7.92it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1511/2529 [03:19<01:53,  8.99it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1512/2529 [03:19<02:05,  8.12it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1514/2529 [03:19<01:56,  8.68it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1515/2529 [03:20<02:09,  7.83it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1516/2529 [03:20<02:08,  7.90it/s]
Processing: positive r2g, BASC binarized:  60%|█████▉    | 1517/2529 [03:20<02:05,  8.06it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1518/2529 [03:20<02:09,  7.83it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1520/2529 [03:20<01:55,  8.72it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1522/2529 [03:20<01:46,  9.42it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1523/2529 [03:20<01:47,  9.38it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1524/2529 [03:21<01:57,  8.57it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1525/2529 [03:21<02:08,  7.80it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1526/2529 [03:21<02:05,  7.96it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1528/2529 [03:21<01:56,  8.63it/s]
Processing: positive r2g, BASC binarized:  60%|██████    | 1530/2529 [03:21<01:51,  8.92it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1531/2529 [03:21<01:54,  8.69it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1532/2529 [03:22<02:05,  7.92it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1533/2529 [03:22<02:10,  7.66it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1534/2529 [03:22<02:04,  8.01it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1535/2529 [03:22<02:01,  8.16it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1536/2529 [03:22<02:02,  8.10it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1537/2529 [03:22<01:59,  8.29it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1538/2529 [03:22<02:04,  7.96it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1539/2529 [03:22<02:00,  8.21it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1540/2529 [03:23<01:56,  8.47it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1541/2529 [03:23<02:22,  6.91it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1542/2529 [03:23<02:14,  7.32it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1543/2529 [03:23<02:08,  7.69it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1544/2529 [03:23<02:03,  7.97it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1545/2529 [03:23<01:58,  8.30it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1546/2529 [03:23<01:56,  8.45it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1547/2529 [03:23<01:54,  8.56it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1548/2529 [03:24<01:52,  8.74it/s]
Processing: positive r2g, BASC binarized:  61%|██████    | 1549/2529 [03:24<01:48,  9.05it/s]
Processing: positive r2g, BASC binarized:  61%|██████▏   | 1550/2529 [03:24<01:45,  9.30it/s]
Processing: positive r2g, BASC binarized:  61%|██████▏   | 1552/2529 [03:24<01:39,  9.84it/s]
Processing: positive r2g, BASC binarized:  61%|██████▏   | 1553/2529 [03:24<01:41,  9.59it/s]
Processing: positive r2g, BASC binarized:  61%|██████▏   | 1554/2529 [03:24<01:42,  9.55it/s]
Processing: positive r2g, BASC binarized:  61%|██████▏   | 1555/2529 [03:24<01:44,  9.30it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1556/2529 [03:24<01:45,  9.26it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1557/2529 [03:24<01:43,  9.35it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1558/2529 [03:25<01:44,  9.26it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1560/2529 [03:25<01:39,  9.70it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1561/2529 [03:25<01:43,  9.39it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1562/2529 [03:25<01:43,  9.32it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1563/2529 [03:25<01:47,  9.01it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1564/2529 [03:25<01:48,  8.92it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1565/2529 [03:25<01:58,  8.12it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1566/2529 [03:26<01:56,  8.28it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1568/2529 [03:26<01:56,  8.28it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1569/2529 [03:26<02:09,  7.42it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1570/2529 [03:26<02:03,  7.78it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1571/2529 [03:26<01:56,  8.24it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1573/2529 [03:26<01:46,  8.94it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1575/2529 [03:27<01:42,  9.33it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1576/2529 [03:27<01:40,  9.46it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1577/2529 [03:27<01:42,  9.27it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1579/2529 [03:27<01:38,  9.65it/s]
Processing: positive r2g, BASC binarized:  62%|██████▏   | 1580/2529 [03:27<02:06,  7.48it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1581/2529 [03:27<02:20,  6.77it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1582/2529 [03:28<02:37,  6.03it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1583/2529 [03:28<02:24,  6.54it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1584/2529 [03:28<02:19,  6.77it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1585/2529 [03:28<02:09,  7.29it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1586/2529 [03:28<02:09,  7.27it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1588/2529 [03:28<01:59,  7.85it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1589/2529 [03:28<02:00,  7.79it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1590/2529 [03:29<02:06,  7.41it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1591/2529 [03:29<02:09,  7.24it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1592/2529 [03:29<02:35,  6.04it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1593/2529 [03:29<02:26,  6.38it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1594/2529 [03:29<02:18,  6.77it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1595/2529 [03:29<02:17,  6.81it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1596/2529 [03:30<02:23,  6.48it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1597/2529 [03:30<02:15,  6.88it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1599/2529 [03:30<01:50,  8.40it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1600/2529 [03:30<01:48,  8.57it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1601/2529 [03:30<01:54,  8.09it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1602/2529 [03:30<01:53,  8.14it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1603/2529 [03:30<02:12,  7.00it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1604/2529 [03:31<02:24,  6.40it/s]
Processing: positive r2g, BASC binarized:  63%|██████▎   | 1605/2529 [03:31<02:31,  6.11it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1606/2529 [03:31<02:35,  5.92it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1607/2529 [03:31<02:30,  6.11it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1608/2529 [03:31<02:46,  5.52it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1609/2529 [03:32<02:50,  5.39it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1610/2529 [03:32<02:51,  5.35it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1611/2529 [03:32<03:04,  4.97it/s]
Processing: positive r2g, BASC binarized:  64%|██████▎   | 1612/2529 [03:32<03:00,  5.09it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1613/2529 [03:32<03:10,  4.80it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1614/2529 [03:33<03:21,  4.53it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1615/2529 [03:33<03:29,  4.36it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1616/2529 [03:33<03:10,  4.80it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1617/2529 [03:33<03:17,  4.61it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1618/2529 [03:34<03:14,  4.69it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1619/2529 [03:34<03:12,  4.72it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1620/2529 [03:34<03:17,  4.59it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1621/2529 [03:34<03:23,  4.45it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1622/2529 [03:34<03:19,  4.54it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1623/2529 [03:35<03:11,  4.73it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1624/2529 [03:35<03:13,  4.67it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1625/2529 [03:35<03:12,  4.69it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1626/2529 [03:35<02:47,  5.39it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1628/2529 [03:35<02:14,  6.72it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1629/2529 [03:35<02:08,  7.00it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1630/2529 [03:36<02:01,  7.42it/s]
Processing: positive r2g, BASC binarized:  64%|██████▍   | 1631/2529 [03:36<02:02,  7.31it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1632/2529 [03:36<01:56,  7.72it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1633/2529 [03:36<02:00,  7.43it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1634/2529 [03:36<02:10,  6.88it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1635/2529 [03:36<02:12,  6.76it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1636/2529 [03:36<02:08,  6.97it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1637/2529 [03:37<02:07,  6.98it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1638/2529 [03:37<02:04,  7.17it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1639/2529 [03:37<02:00,  7.41it/s]

Processing: positive r2g, BASC binarized:  65%|██████▍   | 1640/2529 [03:37<01:57,  7.59it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1641/2529 [03:37<01:52,  7.88it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1642/2529 [03:37<01:56,  7.60it/s]
Processing: positive r2g, BASC binarized:  65%|██████▍   | 1643/2529 [03:37<01:51,  7.94it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1644/2529 [03:37<01:54,  7.70it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1645/2529 [03:38<01:51,  7.89it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1646/2529 [03:38<02:06,  7.00it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1647/2529 [03:38<02:24,  6.09it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1648/2529 [03:38<02:56,  5.00it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1649/2529 [03:38<02:56,  4.99it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1650/2529 [03:39<02:49,  5.18it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1651/2529 [03:39<02:48,  5.22it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1652/2529 [03:39<02:45,  5.31it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1654/2529 [03:39<02:21,  6.19it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1655/2529 [03:40<02:52,  5.07it/s]
Processing: positive r2g, BASC binarized:  65%|██████▌   | 1656/2529 [03:40<02:39,  5.48it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1657/2529 [03:40<02:25,  5.99it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1659/2529 [03:40<01:56,  7.46it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1660/2529 [03:40<01:53,  7.64it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1661/2529 [03:40<02:02,  7.08it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1662/2529 [03:40<02:04,  6.98it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1663/2529 [03:41<02:17,  6.32it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1664/2529 [03:41<02:19,  6.19it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1665/2529 [03:41<02:16,  6.33it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1666/2529 [03:41<02:15,  6.37it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1668/2529 [03:41<01:54,  7.50it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1669/2529 [03:41<01:51,  7.71it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1670/2529 [03:42<01:55,  7.41it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1671/2529 [03:42<02:05,  6.83it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1673/2529 [03:42<01:45,  8.09it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1674/2529 [03:42<01:45,  8.09it/s]
Processing: positive r2g, BASC binarized:  66%|██████▌   | 1675/2529 [03:42<01:44,  8.19it/s]
Processing: positive r2g, BASC binarized:  66%|██████▋   | 1676/2529 [03:42<01:45,  8.06it/s]
Processing: positive r2g, BASC binarized:  66%|██████▋   | 1678/2529 [03:43<01:35,  8.88it/s]
Processing: positive r2g, BASC binarized:  66%|██████▋   | 1680/2529 [03:43<01:33,  9.12it/s]
Processing: positive r2g, BASC binarized:  66%|██████▋   | 1681/2529 [03:43<01:54,  7.40it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1682/2529 [03:43<01:58,  7.14it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1683/2529 [03:43<01:55,  7.33it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1684/2529 [03:43<02:00,  7.03it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1685/2529 [03:44<02:10,  6.45it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1686/2529 [03:44<02:17,  6.14it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1688/2529 [03:44<01:55,  7.25it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1689/2529 [03:44<01:52,  7.50it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1690/2529 [03:44<01:48,  7.70it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1691/2529 [03:44<01:53,  7.41it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1692/2529 [03:45<02:03,  6.80it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1693/2529 [03:45<01:54,  7.31it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1695/2529 [03:45<01:46,  7.82it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1697/2529 [03:45<01:49,  7.63it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1698/2529 [03:45<01:52,  7.40it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1699/2529 [03:46<02:04,  6.68it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1700/2529 [03:46<02:29,  5.56it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1701/2529 [03:46<02:11,  6.29it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1702/2529 [03:46<02:28,  5.55it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1703/2529 [03:46<02:43,  5.06it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1705/2529 [03:47<02:05,  6.57it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1706/2529 [03:47<02:29,  5.52it/s]
Processing: positive r2g, BASC binarized:  67%|██████▋   | 1707/2529 [03:47<02:33,  5.34it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1708/2529 [03:47<02:26,  5.60it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1710/2529 [03:47<01:56,  7.03it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1711/2529 [03:48<02:19,  5.87it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1712/2529 [03:48<02:29,  5.46it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1713/2529 [03:48<02:28,  5.48it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1714/2529 [03:48<02:28,  5.49it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1715/2529 [03:48<02:30,  5.41it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1716/2529 [03:49<02:40,  5.05it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1717/2529 [03:49<02:36,  5.18it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1718/2529 [03:49<02:26,  5.55it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1719/2529 [03:49<02:10,  6.19it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1720/2529 [03:49<01:56,  6.94it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1721/2529 [03:49<01:55,  6.97it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1722/2529 [03:50<02:01,  6.66it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1724/2529 [03:50<01:55,  6.98it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1725/2529 [03:50<02:10,  6.16it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1726/2529 [03:50<02:14,  5.99it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1727/2529 [03:50<02:13,  6.01it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1728/2529 [03:51<02:27,  5.42it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1729/2529 [03:51<02:29,  5.34it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1730/2529 [03:51<02:40,  4.98it/s]
Processing: positive r2g, BASC binarized:  68%|██████▊   | 1732/2529 [03:51<02:01,  6.55it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1733/2529 [03:51<02:05,  6.34it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1734/2529 [03:52<01:58,  6.72it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1735/2529 [03:52<01:48,  7.32it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1736/2529 [03:52<01:57,  6.72it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1737/2529 [03:52<01:50,  7.16it/s]
Processing: positive r2g, BASC binarized:  69%|██████▊   | 1738/2529 [03:52<01:46,  7.45it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1739/2529 [03:52<01:41,  7.76it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1740/2529 [03:52<02:02,  6.44it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1741/2529 [03:53<02:14,  5.86it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1742/2529 [03:53<02:01,  6.47it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1743/2529 [03:53<01:51,  7.02it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1744/2529 [03:53<01:51,  7.06it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1745/2529 [03:53<01:43,  7.57it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1746/2529 [03:53<01:38,  7.99it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1747/2529 [03:53<01:35,  8.17it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1748/2529 [03:53<01:34,  8.25it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1749/2529 [03:54<01:35,  8.15it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1750/2529 [03:54<01:36,  8.11it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1751/2529 [03:54<01:35,  8.11it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1752/2529 [03:54<01:42,  7.61it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1753/2529 [03:54<01:39,  7.77it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1754/2529 [03:54<01:43,  7.47it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1755/2529 [03:54<01:40,  7.70it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1756/2529 [03:54<01:36,  8.05it/s]
Processing: positive r2g, BASC binarized:  69%|██████▉   | 1757/2529 [03:55<01:34,  8.13it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1759/2529 [03:55<01:28,  8.75it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1761/2529 [03:55<01:21,  9.38it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1763/2529 [03:55<01:18,  9.75it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1765/2529 [03:55<01:17,  9.87it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1766/2529 [03:55<01:17,  9.80it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1767/2529 [03:56<01:24,  8.97it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1768/2529 [03:56<01:24,  9.00it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1769/2529 [03:56<01:25,  8.94it/s]
Processing: positive r2g, BASC binarized:  70%|██████▉   | 1770/2529 [03:56<01:24,  8.93it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1771/2529 [03:56<01:39,  7.63it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1772/2529 [03:56<01:36,  7.88it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1773/2529 [03:56<01:30,  8.33it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1774/2529 [03:56<01:39,  7.62it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1775/2529 [03:57<01:43,  7.26it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1776/2529 [03:57<01:38,  7.65it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1777/2529 [03:57<02:00,  6.25it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1779/2529 [03:57<01:38,  7.62it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1781/2529 [03:57<01:26,  8.66it/s]
Processing: positive r2g, BASC binarized:  70%|███████   | 1782/2529 [03:57<01:24,  8.80it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1783/2529 [03:58<01:23,  8.90it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1785/2529 [03:58<01:29,  8.30it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1786/2529 [03:58<01:29,  8.30it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1787/2529 [03:58<01:42,  7.23it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1788/2529 [03:58<01:58,  6.26it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1789/2529 [03:59<02:08,  5.76it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1790/2529 [03:59<01:53,  6.51it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1792/2529 [03:59<01:33,  7.86it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1793/2529 [03:59<01:30,  8.17it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1794/2529 [03:59<01:27,  8.42it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1796/2529 [03:59<01:19,  9.25it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1798/2529 [03:59<01:14,  9.87it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1800/2529 [04:00<01:23,  8.78it/s]
Processing: positive r2g, BASC binarized:  71%|███████   | 1801/2529 [04:00<01:21,  8.97it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1802/2529 [04:00<01:21,  8.90it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1803/2529 [04:00<01:46,  6.83it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1805/2529 [04:00<01:33,  7.74it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1806/2529 [04:01<01:33,  7.74it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1807/2529 [04:01<01:46,  6.76it/s]
Processing: positive r2g, BASC binarized:  71%|███████▏  | 1808/2529 [04:01<01:42,  7.02it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1809/2529 [04:01<01:45,  6.81it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1810/2529 [04:01<01:39,  7.23it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1812/2529 [04:01<01:25,  8.42it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1814/2529 [04:02<01:22,  8.64it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1816/2529 [04:02<01:19,  9.01it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1817/2529 [04:02<01:18,  9.02it/s]

Processing: positive r2g, BASC binarized:  72%|███████▏  | 1819/2529 [04:02<01:23,  8.53it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1820/2529 [04:02<01:20,  8.77it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1821/2529 [04:02<01:20,  8.74it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1823/2529 [04:03<01:20,  8.82it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1824/2529 [04:03<01:19,  8.88it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1825/2529 [04:03<01:19,  8.84it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1826/2529 [04:03<01:21,  8.64it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1827/2529 [04:03<01:25,  8.17it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1828/2529 [04:03<01:25,  8.23it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1829/2529 [04:03<01:33,  7.50it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1831/2529 [04:04<01:21,  8.54it/s]
Processing: positive r2g, BASC binarized:  72%|███████▏  | 1833/2529 [04:04<01:17,  9.02it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1834/2529 [04:04<01:30,  7.68it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1835/2529 [04:04<01:41,  6.82it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1836/2529 [04:04<01:37,  7.10it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1837/2529 [04:04<01:38,  7.00it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1838/2529 [04:05<01:33,  7.38it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1839/2529 [04:05<01:41,  6.80it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1840/2529 [04:05<01:34,  7.30it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1841/2529 [04:05<01:47,  6.40it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1842/2529 [04:05<01:50,  6.20it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1843/2529 [04:05<01:41,  6.78it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1844/2529 [04:06<01:53,  6.05it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1845/2529 [04:06<01:59,  5.73it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1846/2529 [04:06<01:49,  6.22it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1847/2529 [04:06<01:44,  6.51it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1848/2529 [04:06<01:36,  7.05it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1849/2529 [04:06<01:33,  7.26it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1850/2529 [04:06<01:32,  7.34it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1851/2529 [04:07<01:40,  6.78it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1852/2529 [04:07<01:34,  7.16it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1853/2529 [04:07<01:28,  7.63it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1854/2529 [04:07<01:28,  7.60it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1855/2529 [04:07<01:26,  7.81it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1856/2529 [04:07<01:24,  7.96it/s]
Processing: positive r2g, BASC binarized:  73%|███████▎  | 1858/2529 [04:07<01:20,  8.37it/s]
Processing: positive r2g, BASC binarized:  74%|███████▎  | 1859/2529 [04:08<01:23,  7.98it/s]
Processing: positive r2g, BASC binarized:  74%|███████▎  | 1861/2529 [04:08<01:16,  8.68it/s]
Processing: positive r2g, BASC binarized:  74%|███████▎  | 1862/2529 [04:08<01:16,  8.76it/s]
Processing: positive r2g, BASC binarized:  74%|███████▎  | 1863/2529 [04:08<01:24,  7.89it/s]
Processing: positive r2g, BASC binarized:  74%|███████▎  | 1864/2529 [04:08<01:22,  8.10it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1866/2529 [04:08<01:13,  9.03it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1867/2529 [04:08<01:11,  9.24it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1868/2529 [04:09<01:28,  7.43it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1869/2529 [04:09<01:24,  7.80it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1870/2529 [04:09<01:19,  8.27it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1871/2529 [04:09<01:27,  7.55it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1872/2529 [04:09<01:27,  7.51it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1873/2529 [04:09<01:45,  6.24it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1874/2529 [04:10<02:15,  4.84it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1875/2529 [04:10<02:03,  5.31it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1876/2529 [04:10<02:02,  5.35it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1877/2529 [04:10<02:03,  5.29it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1878/2529 [04:10<02:03,  5.27it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1879/2529 [04:10<01:48,  5.98it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1880/2529 [04:11<01:44,  6.18it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1881/2529 [04:11<01:34,  6.85it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1882/2529 [04:11<01:41,  6.39it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1883/2529 [04:11<01:30,  7.15it/s]
Processing: positive r2g, BASC binarized:  74%|███████▍  | 1884/2529 [04:11<01:24,  7.64it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1886/2529 [04:11<01:23,  7.68it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1887/2529 [04:12<01:19,  8.06it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1888/2529 [04:12<01:24,  7.59it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1889/2529 [04:12<01:19,  8.06it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1890/2529 [04:12<01:16,  8.39it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1891/2529 [04:12<01:18,  8.11it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1892/2529 [04:12<01:20,  7.96it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1893/2529 [04:12<01:24,  7.51it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1894/2529 [04:12<01:25,  7.42it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1895/2529 [04:13<01:30,  7.01it/s]
Processing: positive r2g, BASC binarized:  75%|███████▍  | 1896/2529 [04:13<01:30,  6.98it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1897/2529 [04:13<01:27,  7.21it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1898/2529 [04:13<01:23,  7.59it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1899/2529 [04:13<01:20,  7.78it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1900/2529 [04:13<01:19,  7.92it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1902/2529 [04:13<01:10,  8.94it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1903/2529 [04:14<01:09,  8.99it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1904/2529 [04:14<01:08,  9.06it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1906/2529 [04:14<01:06,  9.38it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1907/2529 [04:14<01:07,  9.21it/s]
Processing: positive r2g, BASC binarized:  75%|███████▌  | 1909/2529 [04:14<01:05,  9.49it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1910/2529 [04:14<01:28,  7.02it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1911/2529 [04:15<01:33,  6.62it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1912/2529 [04:15<01:38,  6.28it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1914/2529 [04:15<01:23,  7.40it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1915/2529 [04:15<01:22,  7.47it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1916/2529 [04:15<01:21,  7.48it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1917/2529 [04:15<01:18,  7.75it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1918/2529 [04:15<01:14,  8.25it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1919/2529 [04:16<01:10,  8.66it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1920/2529 [04:16<01:15,  8.10it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1921/2529 [04:16<01:18,  7.75it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1922/2529 [04:16<01:14,  8.13it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1923/2529 [04:16<01:10,  8.56it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1924/2529 [04:16<01:13,  8.18it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1926/2529 [04:16<01:08,  8.75it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1927/2529 [04:17<01:08,  8.74it/s]
Processing: positive r2g, BASC binarized:  76%|███████▌  | 1928/2529 [04:17<01:20,  7.45it/s]
Processing: positive r2g, BASC binarized:  76%|███████▋  | 1929/2529 [04:17<01:17,  7.77it/s]
Processing: positive r2g, BASC binarized:  76%|███████▋  | 1931/2529 [04:17<01:09,  8.66it/s]
Processing: positive r2g, BASC binarized:  76%|███████▋  | 1933/2529 [04:17<01:05,  9.05it/s]
Processing: positive r2g, BASC binarized:  76%|███████▋  | 1934/2529 [04:17<01:13,  8.05it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1935/2529 [04:18<01:20,  7.40it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1936/2529 [04:18<01:29,  6.62it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1937/2529 [04:18<01:25,  6.94it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1938/2529 [04:18<01:33,  6.31it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1940/2529 [04:18<01:22,  7.11it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1941/2529 [04:18<01:22,  7.16it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1943/2529 [04:19<01:16,  7.62it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1944/2529 [04:19<01:18,  7.43it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1945/2529 [04:19<01:13,  7.90it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1947/2529 [04:19<01:06,  8.71it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1949/2529 [04:19<01:10,  8.28it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1950/2529 [04:20<01:10,  8.20it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1951/2529 [04:20<01:10,  8.25it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1952/2529 [04:20<01:08,  8.39it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1953/2529 [04:20<01:15,  7.58it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1954/2529 [04:20<01:20,  7.11it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1955/2529 [04:20<01:23,  6.89it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1956/2529 [04:20<01:23,  6.88it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1957/2529 [04:21<01:17,  7.37it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1958/2529 [04:21<01:13,  7.76it/s]
Processing: positive r2g, BASC binarized:  77%|███████▋  | 1959/2529 [04:21<01:13,  7.73it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1960/2529 [04:21<01:12,  7.84it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1961/2529 [04:21<01:11,  7.94it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1962/2529 [04:21<01:16,  7.41it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1963/2529 [04:21<01:19,  7.13it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1964/2529 [04:21<01:16,  7.39it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1965/2529 [04:22<01:14,  7.54it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1966/2529 [04:22<01:17,  7.27it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1967/2529 [04:22<01:21,  6.88it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1968/2529 [04:22<01:14,  7.48it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1969/2529 [04:22<01:43,  5.40it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1970/2529 [04:23<02:01,  4.58it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1971/2529 [04:23<02:09,  4.30it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1972/2529 [04:23<02:13,  4.18it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1973/2529 [04:23<02:20,  3.97it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1974/2529 [04:24<02:08,  4.32it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1975/2529 [04:24<02:03,  4.49it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1976/2529 [04:24<01:56,  4.74it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1977/2529 [04:24<01:51,  4.94it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1978/2529 [04:24<01:48,  5.10it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1979/2529 [04:25<01:54,  4.82it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1980/2529 [04:25<01:54,  4.82it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1981/2529 [04:25<01:52,  4.87it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1982/2529 [04:25<01:35,  5.74it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1983/2529 [04:25<01:35,  5.73it/s]
Processing: positive r2g, BASC binarized:  78%|███████▊  | 1984/2529 [04:25<01:34,  5.79it/s]
Processing: positive r2g, BASC binarized:  79%|███████▊  | 1986/2529 [04:26<01:26,  6.29it/s]
Processing: positive r2g, BASC binarized:  79%|███████▊  | 1987/2529 [04:26<01:18,  6.91it/s]

Processing: positive r2g, BASC binarized:  79%|███████▊  | 1988/2529 [04:26<01:26,  6.22it/s]
Processing: positive r2g, BASC binarized:  79%|███████▊  | 1989/2529 [04:26<01:19,  6.76it/s]
Processing: positive r2g, BASC binarized:  79%|███████▊  | 1990/2529 [04:26<01:14,  7.24it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1992/2529 [04:26<01:13,  7.30it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1994/2529 [04:27<01:11,  7.47it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1995/2529 [04:27<01:25,  6.26it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1997/2529 [04:27<01:17,  6.90it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1998/2529 [04:28<01:35,  5.57it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 1999/2529 [04:28<01:27,  6.03it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2000/2529 [04:28<01:25,  6.17it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2001/2529 [04:28<01:29,  5.90it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2003/2529 [04:28<01:12,  7.27it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2005/2529 [04:28<01:10,  7.45it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2007/2529 [04:29<01:02,  8.36it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2008/2529 [04:29<01:02,  8.28it/s]
Processing: positive r2g, BASC binarized:  79%|███████▉  | 2010/2529 [04:29<01:03,  8.23it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2012/2529 [04:29<00:58,  8.84it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2013/2529 [04:29<00:58,  8.81it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2015/2529 [04:30<00:54,  9.38it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2016/2529 [04:30<00:55,  9.24it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2017/2529 [04:30<01:25,  6.01it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2019/2529 [04:30<01:21,  6.26it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2020/2529 [04:31<01:37,  5.20it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2021/2529 [04:31<01:39,  5.08it/s]
Processing: positive r2g, BASC binarized:  80%|███████▉  | 2023/2529 [04:31<01:22,  6.14it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2024/2529 [04:31<01:16,  6.59it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2025/2529 [04:31<01:13,  6.85it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2027/2529 [04:31<01:02,  8.06it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2028/2529 [04:32<01:00,  8.23it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2029/2529 [04:32<01:09,  7.19it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2031/2529 [04:32<01:06,  7.51it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2032/2529 [04:32<01:08,  7.27it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2033/2529 [04:32<01:18,  6.28it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2034/2529 [04:33<01:12,  6.85it/s]
Processing: positive r2g, BASC binarized:  80%|████████  | 2035/2529 [04:33<01:06,  7.39it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2036/2529 [04:33<01:22,  5.95it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2037/2529 [04:33<01:20,  6.08it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2039/2529 [04:33<01:15,  6.50it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2040/2529 [04:33<01:14,  6.60it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2041/2529 [04:34<01:10,  6.91it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2042/2529 [04:34<01:08,  7.15it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2044/2529 [04:34<00:57,  8.39it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2046/2529 [04:34<00:56,  8.59it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2048/2529 [04:34<00:51,  9.29it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2049/2529 [04:34<00:51,  9.24it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2050/2529 [04:35<00:59,  8.01it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2051/2529 [04:35<01:07,  7.05it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2053/2529 [04:35<00:57,  8.30it/s]
Processing: positive r2g, BASC binarized:  81%|████████  | 2054/2529 [04:35<00:55,  8.49it/s]
Processing: positive r2g, BASC binarized:  81%|████████▏ | 2055/2529 [04:35<00:55,  8.56it/s]
Processing: positive r2g, BASC binarized:  81%|████████▏ | 2057/2529 [04:35<00:51,  9.20it/s]
Processing: positive r2g, BASC binarized:  81%|████████▏ | 2059/2529 [04:36<00:49,  9.46it/s]
Processing: positive r2g, BASC binarized:  81%|████████▏ | 2060/2529 [04:36<00:51,  9.07it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2062/2529 [04:36<00:57,  8.10it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2063/2529 [04:36<01:00,  7.69it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2065/2529 [04:36<00:56,  8.26it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2066/2529 [04:36<00:56,  8.13it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2067/2529 [04:37<01:02,  7.45it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2068/2529 [04:37<01:00,  7.57it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2069/2529 [04:37<00:59,  7.75it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2070/2529 [04:37<00:59,  7.70it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2071/2529 [04:37<00:58,  7.79it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2072/2529 [04:37<01:10,  6.53it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2073/2529 [04:37<01:02,  7.25it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2074/2529 [04:38<01:01,  7.42it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2075/2529 [04:38<01:03,  7.10it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2076/2529 [04:38<01:08,  6.59it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2077/2529 [04:38<01:25,  5.29it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2078/2529 [04:38<01:15,  5.94it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2080/2529 [04:39<01:02,  7.22it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2082/2529 [04:39<01:13,  6.06it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2083/2529 [04:39<01:16,  5.85it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2084/2529 [04:39<01:16,  5.83it/s]
Processing: positive r2g, BASC binarized:  82%|████████▏ | 2086/2529 [04:40<01:03,  6.98it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2087/2529 [04:40<00:59,  7.45it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2088/2529 [04:40<00:57,  7.71it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2089/2529 [04:40<00:56,  7.82it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2090/2529 [04:40<00:55,  7.90it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2091/2529 [04:40<01:22,  5.32it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2092/2529 [04:40<01:11,  6.10it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2093/2529 [04:41<01:13,  5.93it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2094/2529 [04:41<01:22,  5.25it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2096/2529 [04:41<01:05,  6.60it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2097/2529 [04:41<01:00,  7.09it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2098/2529 [04:41<00:58,  7.42it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2099/2529 [04:41<00:57,  7.49it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2100/2529 [04:42<00:54,  7.83it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2101/2529 [04:42<00:57,  7.48it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2102/2529 [04:42<01:06,  6.40it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2103/2529 [04:42<00:59,  7.13it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2104/2529 [04:42<00:58,  7.22it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2106/2529 [04:42<00:53,  7.86it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2107/2529 [04:42<00:52,  8.02it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2108/2529 [04:43<00:57,  7.38it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2109/2529 [04:43<00:58,  7.15it/s]
Processing: positive r2g, BASC binarized:  83%|████████▎ | 2110/2529 [04:43<00:59,  7.00it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2112/2529 [04:43<00:50,  8.21it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2113/2529 [04:43<00:49,  8.34it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2115/2529 [04:44<00:56,  7.36it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2116/2529 [04:44<00:54,  7.61it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2117/2529 [04:44<01:11,  5.79it/s]
Processing: positive r2g, BASC binarized:  84%|████████▎ | 2118/2529 [04:44<01:16,  5.38it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2119/2529 [04:44<01:08,  6.00it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2120/2529 [04:44<01:02,  6.51it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2122/2529 [04:45<00:53,  7.61it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2124/2529 [04:45<00:54,  7.46it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2126/2529 [04:45<00:53,  7.54it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2128/2529 [04:45<00:48,  8.27it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2129/2529 [04:46<00:50,  7.85it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2130/2529 [04:46<00:48,  8.19it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2132/2529 [04:46<00:45,  8.73it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2133/2529 [04:46<00:45,  8.73it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2135/2529 [04:46<00:45,  8.61it/s]
Processing: positive r2g, BASC binarized:  84%|████████▍ | 2136/2529 [04:46<00:47,  8.33it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2138/2529 [04:47<00:43,  9.04it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2139/2529 [04:47<00:42,  9.13it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2140/2529 [04:47<00:45,  8.48it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2141/2529 [04:47<00:48,  7.95it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2142/2529 [04:47<00:51,  7.54it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2143/2529 [04:47<00:49,  7.73it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2144/2529 [04:47<00:48,  8.00it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2145/2529 [04:47<00:47,  8.06it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2146/2529 [04:48<00:45,  8.42it/s]
Processing: positive r2g, BASC binarized:  85%|████████▍ | 2148/2529 [04:48<00:42,  9.06it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2150/2529 [04:48<00:39,  9.52it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2152/2529 [04:48<00:38,  9.73it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2153/2529 [04:48<00:39,  9.55it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2154/2529 [04:48<00:38,  9.64it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2155/2529 [04:48<00:42,  8.81it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2156/2529 [04:49<00:41,  8.95it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2157/2529 [04:49<00:40,  9.08it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2159/2529 [04:49<00:37,  9.82it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2161/2529 [04:49<00:37,  9.94it/s]
Processing: positive r2g, BASC binarized:  85%|████████▌ | 2162/2529 [04:49<00:37,  9.76it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2163/2529 [04:49<00:38,  9.44it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2165/2529 [04:50<00:38,  9.34it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2166/2529 [04:50<00:38,  9.44it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2167/2529 [04:50<00:44,  8.17it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2168/2529 [04:50<00:42,  8.42it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2170/2529 [04:50<00:38,  9.40it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2171/2529 [04:50<00:42,  8.50it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2172/2529 [04:50<00:44,  7.95it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2173/2529 [04:50<00:43,  8.21it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2175/2529 [04:51<00:47,  7.50it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2177/2529 [04:51<00:42,  8.23it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2179/2529 [04:51<00:40,  8.68it/s]
Processing: positive r2g, BASC binarized:  86%|████████▌ | 2180/2529 [04:51<00:39,  8.75it/s]
Processing: positive r2g, BASC binarized:  86%|████████▋ | 2182/2529 [04:52<00:37,  9.34it/s]
Processing: positive r2g, BASC binarized:  86%|████████▋ | 2184/2529 [04:52<00:35,  9.64it/s]
Processing: positive r2g, BASC binarized:  86%|████████▋ | 2185/2529 [04:52<00:40,  8.52it/s]

Processing: positive r2g, BASC binarized:  86%|████████▋ | 2187/2529 [04:52<00:36,  9.25it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2188/2529 [04:52<00:37,  9.10it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2189/2529 [04:52<00:37,  8.99it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2191/2529 [04:52<00:35,  9.58it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2193/2529 [04:53<00:33, 10.14it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2194/2529 [04:53<00:36,  9.11it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2195/2529 [04:53<00:44,  7.58it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2196/2529 [04:53<00:41,  7.98it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2197/2529 [04:53<00:41,  7.93it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2198/2529 [04:53<00:39,  8.29it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2200/2529 [04:54<00:36,  9.12it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2201/2529 [04:54<00:36,  9.04it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2202/2529 [04:54<00:38,  8.45it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2204/2529 [04:54<00:34,  9.29it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2205/2529 [04:54<00:40,  8.02it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2207/2529 [04:54<00:38,  8.36it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2208/2529 [04:54<00:37,  8.64it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2210/2529 [04:55<00:40,  7.97it/s]
Processing: positive r2g, BASC binarized:  87%|████████▋ | 2212/2529 [04:55<00:36,  8.74it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2214/2529 [04:55<00:33,  9.34it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2216/2529 [04:55<00:33,  9.26it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2218/2529 [04:56<00:32,  9.53it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2220/2529 [04:56<00:31,  9.84it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2222/2529 [04:56<00:30,  9.92it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2223/2529 [04:56<00:33,  9.25it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2225/2529 [04:56<00:31,  9.66it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2226/2529 [04:57<00:39,  7.69it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2228/2529 [04:57<00:37,  8.02it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2230/2529 [04:57<00:38,  7.71it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2232/2529 [04:57<00:35,  8.39it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2233/2529 [04:57<00:35,  8.25it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2234/2529 [04:58<00:42,  6.97it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2235/2529 [04:58<00:46,  6.35it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2236/2529 [04:58<00:43,  6.75it/s]
Processing: positive r2g, BASC binarized:  88%|████████▊ | 2238/2529 [04:58<00:36,  7.96it/s]
Processing: positive r2g, BASC binarized:  89%|████████▊ | 2240/2529 [04:58<00:37,  7.66it/s]
Processing: positive r2g, BASC binarized:  89%|████████▊ | 2242/2529 [04:59<00:38,  7.41it/s]
Processing: positive r2g, BASC binarized:  89%|████████▊ | 2243/2529 [04:59<00:37,  7.63it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2245/2529 [04:59<00:34,  8.22it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2246/2529 [04:59<00:33,  8.35it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2247/2529 [04:59<00:38,  7.40it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2248/2529 [04:59<00:36,  7.61it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2249/2529 [05:00<00:40,  6.97it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2250/2529 [05:00<00:38,  7.34it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2251/2529 [05:00<00:35,  7.73it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2252/2529 [05:00<00:34,  7.94it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2254/2529 [05:00<00:31,  8.79it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2256/2529 [05:00<00:29,  9.31it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2258/2529 [05:01<00:27,  9.85it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2260/2529 [05:01<00:32,  8.37it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2261/2529 [05:01<00:33,  8.07it/s]
Processing: positive r2g, BASC binarized:  89%|████████▉ | 2263/2529 [05:01<00:31,  8.54it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2264/2529 [05:01<00:30,  8.78it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2266/2529 [05:01<00:29,  8.86it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2267/2529 [05:02<00:28,  9.06it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2269/2529 [05:02<00:27,  9.54it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2270/2529 [05:02<00:29,  8.66it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2271/2529 [05:02<00:30,  8.33it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2272/2529 [05:02<00:30,  8.47it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2273/2529 [05:02<00:36,  6.95it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2274/2529 [05:03<00:34,  7.38it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2275/2529 [05:03<00:33,  7.68it/s]
Processing: positive r2g, BASC binarized:  90%|████████▉ | 2276/2529 [05:03<00:32,  7.90it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2278/2529 [05:03<00:33,  7.55it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2279/2529 [05:03<00:34,  7.22it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2280/2529 [05:03<00:32,  7.73it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2282/2529 [05:03<00:28,  8.71it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2283/2529 [05:04<00:28,  8.73it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2284/2529 [05:04<00:28,  8.53it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2286/2529 [05:04<00:26,  9.21it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2287/2529 [05:04<00:26,  9.14it/s]
Processing: positive r2g, BASC binarized:  90%|█████████ | 2288/2529 [05:04<00:29,  8.24it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2289/2529 [05:04<00:29,  8.27it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2290/2529 [05:04<00:30,  7.78it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2291/2529 [05:05<00:29,  8.00it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2293/2529 [05:05<00:27,  8.66it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2294/2529 [05:05<00:27,  8.48it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2296/2529 [05:05<00:25,  9.29it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2298/2529 [05:05<00:23,  9.69it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2300/2529 [05:05<00:22, 10.05it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2301/2529 [05:06<00:26,  8.63it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2302/2529 [05:06<00:25,  8.88it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2304/2529 [05:06<00:28,  7.77it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2305/2529 [05:06<00:27,  8.10it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2306/2529 [05:06<00:26,  8.46it/s]
Processing: positive r2g, BASC binarized:  91%|█████████ | 2307/2529 [05:06<00:29,  7.52it/s]
Processing: positive r2g, BASC binarized:  91%|█████████▏| 2308/2529 [05:07<00:29,  7.59it/s]
Processing: positive r2g, BASC binarized:  91%|█████████▏| 2309/2529 [05:07<00:28,  7.75it/s]
Processing: positive r2g, BASC binarized:  91%|█████████▏| 2310/2529 [05:07<00:27,  7.95it/s]
Processing: positive r2g, BASC binarized:  91%|█████████▏| 2312/2529 [05:07<00:28,  7.61it/s]
Processing: positive r2g, BASC binarized:  91%|█████████▏| 2314/2529 [05:07<00:30,  7.00it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2315/2529 [05:08<00:31,  6.80it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2316/2529 [05:08<00:29,  7.14it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2317/2529 [05:08<00:28,  7.56it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2319/2529 [05:08<00:24,  8.59it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2320/2529 [05:08<00:24,  8.61it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2321/2529 [05:08<00:24,  8.61it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2323/2529 [05:08<00:22,  9.20it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2324/2529 [05:09<00:22,  9.31it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2325/2529 [05:09<00:25,  7.94it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2327/2529 [05:09<00:25,  7.83it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2329/2529 [05:09<00:22,  8.74it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2330/2529 [05:09<00:22,  8.93it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2332/2529 [05:09<00:22,  8.90it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2334/2529 [05:10<00:20,  9.45it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2335/2529 [05:10<00:20,  9.53it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2337/2529 [05:10<00:20,  9.38it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2338/2529 [05:10<00:20,  9.45it/s]
Processing: positive r2g, BASC binarized:  92%|█████████▏| 2339/2529 [05:10<00:22,  8.39it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2341/2529 [05:10<00:21,  8.87it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2342/2529 [05:11<00:21,  8.61it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2343/2529 [05:11<00:21,  8.74it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2345/2529 [05:11<00:21,  8.61it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2346/2529 [05:11<00:21,  8.48it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2347/2529 [05:11<00:21,  8.38it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2348/2529 [05:11<00:21,  8.58it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2349/2529 [05:11<00:20,  8.66it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2351/2529 [05:12<00:23,  7.45it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2352/2529 [05:12<00:23,  7.69it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2353/2529 [05:12<00:25,  7.00it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2354/2529 [05:12<00:25,  6.93it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2356/2529 [05:12<00:21,  8.00it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2358/2529 [05:13<00:20,  8.27it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2360/2529 [05:13<00:19,  8.48it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2362/2529 [05:13<00:18,  9.07it/s]
Processing: positive r2g, BASC binarized:  93%|█████████▎| 2364/2529 [05:13<00:17,  9.42it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▎| 2365/2529 [05:13<00:17,  9.42it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▎| 2366/2529 [05:13<00:20,  8.14it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▎| 2368/2529 [05:14<00:19,  8.40it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▎| 2369/2529 [05:14<00:19,  8.17it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▎| 2370/2529 [05:14<00:18,  8.49it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2372/2529 [05:14<00:17,  8.98it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2373/2529 [05:14<00:20,  7.56it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2375/2529 [05:15<00:19,  7.87it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2377/2529 [05:15<00:18,  8.03it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2379/2529 [05:15<00:18,  8.30it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2381/2529 [05:15<00:17,  8.31it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2382/2529 [05:15<00:17,  8.57it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2384/2529 [05:16<00:15,  9.25it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2386/2529 [05:16<00:14,  9.64it/s]
Processing: positive r2g, BASC binarized:  94%|█████████▍| 2388/2529 [05:16<00:14,  9.85it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2390/2529 [05:16<00:14,  9.88it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2392/2529 [05:16<00:15,  8.76it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2393/2529 [05:17<00:15,  8.95it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2395/2529 [05:17<00:14,  9.54it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2396/2529 [05:17<00:14,  9.10it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2397/2529 [05:17<00:14,  9.14it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2399/2529 [05:17<00:14,  9.25it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▍| 2401/2529 [05:17<00:13,  9.81it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2403/2529 [05:18<00:12, 10.19it/s]

Processing: positive r2g, BASC binarized:  95%|█████████▌| 2405/2529 [05:18<00:13,  8.98it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2406/2529 [05:18<00:15,  7.95it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2407/2529 [05:18<00:15,  7.85it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2409/2529 [05:18<00:13,  8.64it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2410/2529 [05:18<00:13,  8.81it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2411/2529 [05:19<00:14,  8.35it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2413/2529 [05:19<00:12,  9.12it/s]
Processing: positive r2g, BASC binarized:  95%|█████████▌| 2414/2529 [05:19<00:12,  8.86it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2416/2529 [05:19<00:12,  9.37it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2417/2529 [05:19<00:12,  9.20it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2419/2529 [05:19<00:11,  9.71it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2420/2529 [05:20<00:12,  8.85it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2422/2529 [05:20<00:11,  9.27it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2424/2529 [05:20<00:11,  9.26it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2426/2529 [05:20<00:10,  9.56it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2427/2529 [05:20<00:10,  9.50it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2428/2529 [05:20<00:10,  9.54it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2429/2529 [05:20<00:10,  9.16it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2430/2529 [05:21<00:10,  9.12it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2431/2529 [05:21<00:10,  9.32it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2432/2529 [05:21<00:12,  7.54it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2433/2529 [05:21<00:12,  7.68it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▌| 2434/2529 [05:21<00:11,  7.97it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▋| 2436/2529 [05:21<00:11,  7.93it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▋| 2437/2529 [05:22<00:12,  7.22it/s]
Processing: positive r2g, BASC binarized:  96%|█████████▋| 2439/2529 [05:22<00:10,  8.36it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2441/2529 [05:22<00:09,  9.07it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2443/2529 [05:22<00:08,  9.56it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2445/2529 [05:22<00:09,  9.31it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2446/2529 [05:22<00:09,  9.19it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2447/2529 [05:23<00:09,  8.95it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2448/2529 [05:23<00:09,  8.94it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2450/2529 [05:23<00:08,  8.86it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2452/2529 [05:23<00:07,  9.65it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2454/2529 [05:23<00:08,  8.83it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2455/2529 [05:24<00:09,  7.64it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2456/2529 [05:24<00:09,  7.97it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2458/2529 [05:24<00:08,  8.86it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2459/2529 [05:24<00:07,  8.90it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2461/2529 [05:24<00:07,  8.64it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2462/2529 [05:24<00:07,  8.43it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2464/2529 [05:25<00:07,  9.23it/s]
Processing: positive r2g, BASC binarized:  97%|█████████▋| 2465/2529 [05:25<00:06,  9.16it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2466/2529 [05:25<00:08,  7.72it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2468/2529 [05:25<00:07,  8.69it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2470/2529 [05:25<00:06,  9.30it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2471/2529 [05:25<00:06,  9.24it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2472/2529 [05:25<00:06,  9.25it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2473/2529 [05:26<00:05,  9.39it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2474/2529 [05:26<00:05,  9.38it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2476/2529 [05:26<00:05,  9.43it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2477/2529 [05:26<00:05,  8.98it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2478/2529 [05:26<00:05,  9.20it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2480/2529 [05:26<00:05,  8.92it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2482/2529 [05:27<00:04,  9.45it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2484/2529 [05:27<00:04,  9.68it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2486/2529 [05:27<00:04, 10.10it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2488/2529 [05:27<00:04, 10.04it/s]
Processing: positive r2g, BASC binarized:  98%|█████████▊| 2490/2529 [05:27<00:03,  9.96it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▊| 2492/2529 [05:27<00:03, 10.04it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▊| 2494/2529 [05:28<00:03, 10.20it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▊| 2496/2529 [05:28<00:03,  8.92it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2498/2529 [05:28<00:03,  9.01it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2499/2529 [05:28<00:03,  8.07it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2500/2529 [05:28<00:03,  8.37it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2501/2529 [05:29<00:03,  7.58it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2502/2529 [05:29<00:03,  7.96it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2504/2529 [05:29<00:03,  7.86it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2506/2529 [05:29<00:02,  8.03it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2508/2529 [05:29<00:02,  8.10it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2509/2529 [05:30<00:02,  8.40it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2511/2529 [05:30<00:02,  8.89it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2513/2529 [05:30<00:01,  9.41it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2514/2529 [05:30<00:01,  8.36it/s]
Processing: positive r2g, BASC binarized:  99%|█████████▉| 2516/2529 [05:30<00:01,  9.04it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2517/2529 [05:30<00:01,  8.93it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2519/2529 [05:31<00:01,  8.62it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2520/2529 [05:31<00:01,  8.87it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2521/2529 [05:31<00:00,  9.10it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2522/2529 [05:31<00:00,  9.22it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2523/2529 [05:31<00:00,  9.36it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2524/2529 [05:31<00:00,  9.51it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2525/2529 [05:31<00:00,  8.72it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2526/2529 [05:31<00:00,  9.04it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2527/2529 [05:32<00:00,  8.77it/s]
Processing: positive r2g, BASC binarized: 100%|█████████▉| 2528/2529 [05:32<00:00,  8.18it/s]
Processing: positive r2g, BASC binarized: 100%|██████████| 2529/2529 [05:32<00:00,  8.44it/s]
100%|██████████| 14/14 [43:48<00:00, 187.75s/it]

2025-01-12 08:29:16,700 GSEA         INFO     Subsetting TF2G adjacencies for TF with motif.

2025-01-12 08:29:34,032	INFO worker.py:1743 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265

2025-01-12 08:29:35,061 GSEA         INFO     Running GSEA...

initializing: 100%|██████████| 35406/35406 [28:54<00:00, 20.41it/s]
Running using 40 cores: 100%|██████████| 60984/60984 [1:08:18<00:00, 14.88it/s]

2025-01-12 10:06:54,803 GSEA         INFO     Subsetting on adjusted pvalue: 1, minimal NES: 0 and minimal leading edge genes 10
2025-01-12 10:07:28,293 GSEA         INFO     Merging eRegulons
2025-01-12 10:07:42,843 GSEA         INFO     Storing eRegulons in .uns[eRegulons_importance].
2025-01-12 10:09:55:End build GRN.

# 6. Format egrn to get eRegulon metadata and signature

## 6A. Generate eRegulon metadata

In [32]:
from scenicplus.utils import format_egrns
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start.',sep="")

format_egrns(
    scplus_obj, 
    eregulons_key = 'eRegulons_importance', 
    TF2G_key = 'TF2G_adj', 
    key_added = 'eRegulon_metadata'
)
print(scplus_obj.uns['eRegulon_metadata'][0:10])

print("Done! Generate eRegulon metadata!")
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':End.',sep="")

2026-06-14 09:23:12:Start.
  Region_signature_name Gene_signature_name    TF is_extended  \
0        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
1        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
2        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
3        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
4        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
5        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
6        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
7        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
8        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False
9        ATF1_+_+_(41r)      ATF1_+_+_(35g)  ATF1       False

                     Region     Gene  R2G_importance   R2G_rho  \
0   chr19:51311699-51312199     NKG7        0.059735  0.014761
1  chr1:100894774-100895274     DPH5        0.064928  0.059208
2   chr20:53611664-53612164   ZNF217        0.043815  0.072997
3  chr5:132227455-132227955  SLC22A4        0.020647  0.037182
4  chr7:107891127-107891627    CBLL1        0.059131  0.001076
5       chr11:606150-606650    PHRF1        0.012222  0.081742
6       chr11:537154-537654    PHRF1        0.021585  0.091595
7  chr7:100612126-100612626      EPO        0.173112  0.017134
8    chr6:43243241-43243741    TTBK1        0.032814  0.060459
9   chr16:67183614-67184114    ELMO3        0.050778  0.002148

   R2G_importance_x_rho  R2G_importance_x_abs_rho  TF2G_importance  \
0              0.000882                  0.000882         1.425908
1              0.003844                  0.003844         0.715123
2              0.003198                  0.003198         0.573216
3              0.000768                  0.000768         1.121066
4              0.000064                  0.000064         0.563671
5              0.000999                  0.000999         0.659756
6              0.001977                  0.001977         0.659756
7              0.002966                  0.002966         1.236672
8              0.001984                  0.001984         0.578552
9              0.000109                  0.000109         1.200558

   TF2G_regulation  TF2G_rho  TF2G_importance_x_abs_rho  TF2G_importance_x_rho
0                1  0.030550                   0.043561               0.043561
1                0  0.003831                   0.002740               0.002740
2                0  0.011586                   0.006641               0.006641
3                0  0.019709                   0.022095               0.022095
4                0  0.005004                   0.002820               0.002820
5                0  0.015808                   0.010430               0.010430
6                0  0.015808                   0.010430               0.010430
7                1  0.061723                   0.076332               0.076332
8                0  0.013102                   0.007580               0.007580
9                1  0.031567                   0.037898               0.037898
Done! Generate eRegulon metadata!
2026-06-14 09:34:03:End.

## 6B. Format eRegulons

In [42]:
from scenicplus.eregulon_enrichment import *

print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start.',sep="")
get_eRegulons_as_signatures(
    scplus_obj, 
    eRegulon_metadata_key='eRegulon_metadata', 
    key_added='eRegulon_signatures'
)

print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':End.',sep="")
print("Done! Generate eRegulon signatures!")

2026-06-14 09:52:51:Start.
2026-06-14 09:53:44:End.
Done! Generate eRegulon signatures!

In [44]:
scplus_obj.uns['eRegulon_signatures'].keys()

dict_keys(['Gene_based', 'Region_based'])

In [47]:
import dill
with open(f'{scplus_dir}/01.scplus_obj.pkl', 'wb') as f:
    dill.dump(scplus_obj, f)

# 7.score_eRegulons

## 7A. Gene based

In [48]:
# Gene based raking
from scenicplus.eregulon_enrichment import *
from scenicplus.cistromes import *
import time

print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start gene_ranking',sep="")
gene_ranking = make_rankings(scplus_obj, target='gene')
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Done',sep="")

2026-06-14 10:40:44:Start gene_ranking
2026-06-14 10:41:22:Done

In [50]:
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start',sep="")
auc_gene = signature_enrichment(
    rankings = gene_ranking,
    signatures = scplus_obj.uns['eRegulon_signatures']['Gene_based'],
    enrichment_type='gene',
    auc_threshold = 0.05,
    normalize = False,
    n_cpu = 40
)
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Done',sep="")

print(auc_gene.shape)
auc_gene.head()

2026-06-14 11:28:41:Start
2026-06-14 11:29:28:Done
(9856, 1851)

,GABPA_extended_-_-_(53g),ZNF2_extended_-_-_(18g),CARF_+_+_(20g),ZGPAT_extended_+_+_(81g),TCF7L1_extended_-_+_(55g),SOX5_extended_+_-_(1236g),RBAK_extended_-_-_(17g),ZBTB7A_extended_-_+_(152g),ZBTB25_extended_+_+_(44g),ARID5A_extended_-_-_(15g),...,CUX1_extended_-_-_(65g),ZNF273_extended_+_+_(120g),ZNF415_+_-_(20g),CREB5_extended_+_+_(155g),DLX5_extended_+_+_(79g),FOXN3_+_-_(29g),ZNF33B_+_-_(11g),TFDP2_+_+_(99g),TAL1_extended_-_+_(11g),ZNF180_-_+_(25g)
Cell,,,,,,,,,,,,,,,,,,,,,
TGTGGCGGTAATCCCT-1_BICCN-set1-10___human_DG,0.058326,0.045143,0.000000,0.013034,0.049230,0.133885,0.000000,0.069410,0.056309,0.117996,...,0.033720,0.006444,0.002596,0.154303,0.008273,0.001489,0.047740,0.010383,0.018381,0.039126
GACTATTCAGCTACGT-1_BICCN-set1-7___human_DG,0.045427,0.076260,0.038470,0.010423,0.009886,0.139234,0.036419,0.051179,0.009799,0.078470,...,0.065364,0.020961,0.000000,0.204410,0.005990,0.000000,0.006160,0.025186,0.000000,0.031169
CAAGGTAAGGCCTGGT-1_BICCN-set1-1___human_DG,0.004310,0.093139,0.085710,0.027484,0.025643,0.042783,0.000000,0.079350,0.016704,0.143607,...,0.018041,0.006689,0.056585,0.292505,0.018911,0.000000,0.047193,0.017464,0.074516,0.000000
ATACCGGTCGCTATAA-1_BICCN-set1-7___human_DG,0.014641,0.041803,0.055792,0.018519,0.015390,0.033904,0.037673,0.051934,0.049205,0.122878,...,0.024372,0.015893,0.000000,0.276221,0.000000,0.053646,0.000000,0.021748,0.000000,0.045464
CCTGACTTCTAATTGG-1_BICCN-set1-1___human_DG,0.015259,0.000000,0.000000,0.025575,0.039513,0.034780,0.000000,0.029159,0.035345,0.000000,...,0.016780,0.012427,0.062869,0.237314,0.008473,0.007971,0.000000,0.014274,0.056384,0.032459

In [51]:
auc_gene.to_csv(f'{scplus_dir}/07.eRegulon_AUC_Gene_based.csv')

## 7B. Region based

In [56]:
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start region_ranking',sep="")
region_ranking = make_rankings(scplus_obj, target='region')
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Done',sep="")

2026-06-14 11:54:41:Start region_ranking
2026-06-14 12:09:24:Done

In [57]:
# Score region regulons
print("score_eRegulons for region based")
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Start',sep="")
score_eRegulons(
    scplus_obj,
    ranking = region_ranking,
    eRegulon_signatures_key = 'eRegulon_signatures',
    key_added = 'eRegulon_AUC',
    enrichment_type= 'region',
    auc_threshold = 0.05,
    normalize = False,
    n_cpu = 40
)
print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), ':Done',sep="")

auc_region = scplus_obj.uns['eRegulon_AUC']['Region_based']
print(auc_region.shape)
auc_region.head()

score_eRegulons for region based
2026-06-14 12:09:24:Start
2026-06-14 12:11:25:Done
(9856, 1851)

,ZBTB7B_-_-_(27r),ZNF236_extended_-_-_(16r),ZNF350_extended_+_+_(28r),MEIS1_extended_-_+_(31r),TFDP1_-_-_(245r),SNAI1_+_+_(10r),ZIC2_+_+_(15r),TCF4_extended_-_+_(62r),LHX3_extended_+_-_(30r),LEF1_+_+_(119r),...,ZNF205_extended_+_+_(27r),POU3F2_-_-_(161r),ZNF423_-_-_(32r),ZNF3_extended_+_+_(36r),FOSB_extended_-_-_(28r),FOSL2_-_-_(348r),ZNF200_extended_-_+_(77r),ZNF708_extended_+_-_(19r),IRF4_extended_+_-_(171r),FOXC1_+_+_(141r)
Cell,,,,,,,,,,,,,,,,,,,,,
TGTGGCGGTAATCCCT-1_BICCN-set1-10___human_DG,0.469379,0.628115,0.307717,0.210469,0.522774,0.135242,0.096271,0.156516,0.391088,0.118498,...,0.240974,0.313798,0.475198,0.192412,0.343800,0.171972,0.287729,0.068215,0.358976,0.347999
GACTATTCAGCTACGT-1_BICCN-set1-7___human_DG,0.381795,0.514670,0.248991,0.178970,0.428036,0.067162,0.127807,0.109489,0.360327,0.111020,...,0.249790,0.277327,0.409367,0.095337,0.335473,0.160128,0.223050,0.055372,0.328202,0.283635
CAAGGTAAGGCCTGGT-1_BICCN-set1-1___human_DG,0.284864,0.468725,0.291680,0.089094,0.424862,0.063971,0.141432,0.142489,0.409493,0.072834,...,0.250263,0.303769,0.450506,0.011500,0.290252,0.144757,0.204945,0.021413,0.322231,0.192944
ATACCGGTCGCTATAA-1_BICCN-set1-7___human_DG,0.429691,0.618887,0.387445,0.161073,0.552213,0.000000,0.216190,0.183980,0.438672,0.082854,...,0.318666,0.343713,0.573061,0.044093,0.291854,0.176253,0.267071,0.024406,0.358216,0.272253
CCTGACTTCTAATTGG-1_BICCN-set1-1___human_DG,0.318124,0.466257,0.267468,0.137079,0.419639,0.054819,0.156777,0.139286,0.420331,0.071133,...,0.257773,0.286918,0.452442,0.015131,0.315161,0.144245,0.214399,0.031403,0.324401,0.220323

In [58]:
auc_region.to_csv(f'{scplus_dir}/07.eRegulon_AUC_Region_based.csv')

# 8. Generate anndata

In [15]:
import anndata as ad

auc_gene.columns = [x.split('_(')[0] for x in auc_gene.columns]
adata = ad.AnnData(
    auc_gene,
    obs=rna.obs.loc[auc_gene.index]
)

adata

AnnData object with n_obs × n_vars = 9856 × 1851
    obs: 'class', 'subclass', 'subtype'

In [16]:
adata.write_h5ad(f'{scplus_dir}/08.eRegulon_AUC_Gene.h5ad')